### ISSUE TITLE
Some use of optional chaining triggers an hammerhead error

### ISSUE THREAD

**Issue by JSteunou** [DevExpress/testcafe#7387] opened 2022-11-17 16:34 UTC
### What is your Scenario?

testing an app that can contains optional chaining of this sort

```js
const mapping = {
  foo: () => 'bar'
}

function getValue(key) {
  return mapping[key]?.() ?? key
}

const test = getValue('café')
```

Notice that if `key` is not an attribute in `mapping` then `mapping[key]` will be undefined. This is important for what is upcoming.

### What is the Current behavior?

The test cannot go through and we can see this error in devtool

```
Uncaught Error: 'café' is not a function
    at MethodCallInstrumentation._error (hammerhead.js:21125:16)
    at value (hammerhead.js:21146:48)
    at getValue (index.js:7:11)
    at HTMLButtonElement.toggle (index.js:12:16)
    at HTMLButtonElement.dispatchEvent (hammerhead.js:23059:52)
    at EventSimulator._raiseDispatchEvent (hammerhead.js:23853:23)
    at EventSimulator._dispatchMouseEvent (hammerhead.js:23763:22)
    at EventSimulator._dispatchMouseRelatedEvents (hammerhead.js:23705:22)
    at dispatch (hammerhead.js:23421:60)
    at EventSimulator._simulateEvent (hammerhead.js:23445:17)
```

This is due to hammerhead logic that check if a function exists before accepting to call it. This looks like this:

```js
            nativeMethods.objectDefineProperty(window, SCRIPT_PROCESSING_INSTRUCTIONS.callMethod, {
                value: function (owner, methName, args) {
                    if (isNullOrUndefined(owner))
                        MethodCallInstrumentation._error("Cannot call method '".concat(methName, "' of ").concat(inaccessibleTypeToStr(owner)));
                    if (typeof owner[methName] !== 'function')
                        MethodCallInstrumentation._error("'".concat(methName, "' is not a function"));
                    // OPTIMIZATION: previously we've performed the
                    // `this.methodWrappers.hasOwnProperty(methName)`
                    // check which is quite slow. Now we use the
                    // fast RegExp check instead.
                    if (typeof methName === 'string' && shouldInstrumentMethod(methName) &&
                        _this.methodWrappers[methName].condition(owner))
                        return _this.methodWrappers[methName].method(owner, args);
                    return fastApply(owner, methName, args);
                },
                configurable: true,
            });
```

Notice the `if (typeof owner[methName] !== 'function')`

Unfortunately this does not check if there is an optional chaining, hence the error thrown.

### What is the Expected behavior?

All should be fine

### What is your public website URL? (or attach your complete example)

https://vanilla-testcafe-issue-optional-chaining.vercel.app/

### What is your TestCafe test code?

```js
import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`https://vanilla-testcafe-issue-optional-chaining.vercel.app/`

    test('My test', async t => {
        // Test code
        await t
            .expect(Selector('h1').textContent).eql('Hello!')
            .wait(10000)
            // Next click will generate the JS error
            .click(Selector('#action'))
    });

```

### Your complete configuration file

none

### Your complete test report

```
Running tests in:
 - Chrome 107.0.0.0 / Ubuntu 20.04

 Getting Started
 ✖ My first test

   1) A JavaScript error occurred on "https://vanilla-testcafe-issue-optional-chaining.vercel.app/".
      Repeat test actions in the browser and check the console for errors.
      Enable the “skipJsErrors” option to ignore JavaScript errors during test execution. Learn more: "https://testcafe.io/documentation/404038/recipes/debugging/skip-javascript-errors"
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      Error: 'café' is not a function
          at MethodCallInstrumentation._error (http://192.168.1.58:43277/hammerhead.js:21125:16)
          at value (http://192.168.1.58:43277/hammerhead.js:21146:48)
          at getValue (https://vanilla-testcafe-issue-optional-chaining.vercel.app/index.js:7:11)
          at HTMLButtonElement.toggle (https://vanilla-testcafe-issue-optional-chaining.vercel.app/index.js:12:16)
          at HTMLButtonElement.dispatchEvent (http://192.168.1.58:43277/hammerhead.js:23059:52)
          at EventSimulator._raiseDispatchEvent (http://192.168.1.58:43277/hammerhead.js:23853:23)
          at EventSimulator._dispatchMouseEvent (http://192.168.1.58:43277/hammerhead.js:23763:22)
          at EventSimulator._dispatchMouseRelatedEvents (http://192.168.1.58:43277/hammerhead.js:23705:22)
          at dispatch (http://192.168.1.58:43277/hammerhead.js:23421:60)
          at EventSimulator._simulateEvent (http://192.168.1.58:43277/hammerhead.js:23445:17)

      Browser: Chrome 107.0.0.0 / Linux 0.0

          7 |        // Test code
          8 |        await t
          9 |            .expect(Selector('h1').textContent).eql('Hello!')
         10 |            .wait(10000)
         11 |            // Next click will generate the JS error
       > 12 |            .click(Selector('#action'))
         13 |    });
         14 |
         15 |    // To run this test with chrome, launch this command with yarn : yarn testcafe chrome testWithJSError.ts

         at <anonymous> (/home/hbabin/Documents/testcafe/testWithJSError.ts:12:14)
         at <anonymous> (/home/hbabin/Documents/testcafe/testWithJSError.ts:8:71)
         at __awaiter (/home/hbabin/Documents/testcafe/testWithJSError.ts:4:12)
         at <anonymous> (/home/hbabin/Documents/testcafe/testWithJSError.ts:6:37)



 1/1 failed (13s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to Reproduce

1. write code with optional chaining on function call that can be undefined
2. write test
3. launch test

### TestCafe version

2.1.0

### Node.js version

16.14.0

### Command-line arguments

yarn testcafe chromium testWithJSError.ts

### Browser name(s) and version(s)

Chromium 107

### Platform(s) and version(s)

Linux Ubuntu 22.04.1

**Comment by Artem-Babich** [comment] 2022-11-21 06:35
Thank you for the detailed description. I reproduced this issue. We will research it and update this thread once we have news.

For the team: You can reproduce it in hammerhead http-playground by using an "optional function call" operator on the page.

**Comment by JSteunou** [comment] 2022-11-30 09:59
Any news on this issue? ETA maybe?

**Comment by JSteunou** [comment] 2022-12-07 13:19
Tried with 2.1.0. We struggled a little because the option is named `proxyless` and renamed `experimentalProxyless` only since 2.1.1-alpha.1

Then we are stuck because our test are accessible through *https* and Chrome does not allow mixed content with non secure URL. Is there some configuration to force https all way though in proxyless mode?

Were you able to check our test case on your side with the proxyless mode?

**Comment by miherlosev** [comment] 2022-12-08 07:19
> Tried with 2.1.0. We struggled a little because the option is named proxyless and renamed experimentalProxyless only since 2.1.1-alpha.1

We renamed this option according to the Node.js naming convention for the [experimental options](https://nodejs.org/api/cli.html#--experimental-import-meta-resolve).

> Then we are stuck because our test are accessible through https and Chrome does not allow mixed content with non secure URL. Is there some configuration to force https all way though in proxyless mode?
Were you able to check our test case on your side with the proxyless mode?

It's not clear what you mean here. Could you please share a simple example so that we can reproduce the problematic behavior on our side?

**Comment by JSteunou** [comment] 2022-12-08 08:15
The example is shared in post #1 https://github.com/DevExpress/testcafe/issues/7387#issue-1453643278 

Try this website https://vanilla-testcafe-issue-optional-chaining.vercel.app/ with the testcafé snippet above and I think you will have the same issue.

**Comment by AlexKamaev** [comment] 2022-12-09 09:39
I checked your usage scenario again using the `--experimental-proxyless` option and the following TestCafe version: [https://www.npmjs.com/package/testcafe/v/2.1.1-alpha.2](https://www.npmjs.com/package/testcafe/v/2.1.1-alpha.2)
It works without errors.
It looks like you are using the 2.1.1-alpha.1 version which does not have a fix for the `mixed content` issue.
Try the 2.1.1-alpha.2 version. If it still does not work, please try running TestCafe with the `--hostname localhost` option.

**Comment by JSteunou** [comment] 2022-12-14 09:51
Not tested yet, I believe your words if you said it works. It is just we cannot accept this solution because it is an experimental engine on an alpha release. Cannot be used in production.

We might have find a solution for hammerhead instead

```diff
diff --git a/node_modules/testcafe-hammerhead/lib/client/hammerhead.js b/node_modules/testcafe-hammerhead/lib/client/hammerhead.js
index 0daedf9..94d8520 100644
--- a/node_modules/testcafe-hammerhead/lib/client/hammerhead.js
+++ b/node_modules/testcafe-hammerhead/lib/client/hammerhead.js
@@ -4034,6 +4034,7 @@
 	    directive,
 	    extra;
 
+
 	var Syntax = {
 	    AssignmentExpression:     'AssignmentExpression',
 	    AssignmentPattern:        'AssignmentPattern',
@@ -21142,7 +21143,7 @@
 	                if (isNullOrUndefined(owner))
 	                    MethodCallInstrumentation._error("Cannot call method '".concat(methName, "' of ").concat(inaccessibleTypeToStr(owner)));
 	                if (typeof owner[methName] !== 'function')
-	                    MethodCallInstrumentation._error("'".concat(methName, "' is not a function"));
+					    return undefined
 	                // OPTIMIZATION: previously we've performed the
 	                // `this.methodWrappers.hasOwnProperty(methName)`
 	                // check which is quite slow. Now we use the
```

The logic here is to remove the *throw error* and return `undefined` instead, which is the *normal* behavior of a call to undefined function with optional chaining. It could be improved if we can detect if there is an actual optional chaining, but meanwhile it is better to suppose there is, and let the actual code throw if there is not. If it throws, tests won't pass so the error will not be invisible, I guess.

**Comment by miherlosev** [comment] 2022-12-15 06:57
> Not tested yet, I believe your words if you said it works. It is just we cannot accept this solution because it is an experimental engine on an alpha release. Cannot be used in production.

Ok, I get you. 

> We might have find a solution for hammerhead instead

You can create a PR in the `testcafe-hammerhead` repository, and we will review it.

**Comment by bbutel** [comment] 2023-01-04 08:02
Hi,
Could we have an update of this resolution please. When do you think I will be resolved.

I can see that last PR proposal has been closed because the provided fix is not acceptable.
And an advise is to use the option -e from the cli.

But the description of this option (https://testcafe.io/documentation/402639/reference/command-line-interface#-e-messagevalue-stackvalue2-pageurlvalue3---skip-js-errors-messagevalue-stackvalue2-pageurlvalue3) is not clear for me and I'm afraid I will lost all JS error that could happend on browser side. How can I just ignore proxy-hammerhead JS error please ?
(by using message reg exp ?)

Thx a lot for your answer

**Comment by Aleksey28** [comment] 2023-01-10 08:29
Hi @bbutel,

> Could we have an update of this resolution please. When do you think it will be resolved.

I can't give you any time frames so as not to mislead you.

> How can I just ignore proxy-hammerhead JS error please

It depends on the error that you get.
To skip this exact error, you can use `-e` options in the following way:

```cli
testcafe chrome test.js -e stack='/.*MethodCallInstrumentation\._error.*/g'
```

**Comment by bbutel** [comment] 2023-01-11 20:35
Hi,

thx a lot for your answer. However, it is important to have visibility on this fix because it's quite blocking for me.
We did an ugly patchon  hammer-proxy on our side and it is not a situation that we want to accept for the future.

Until now, Testcafe was a great automation tool but I'm surprise that this kind of issue takes so much time to be resolved.

I hope you will be able to prioritize this issue.

Thx a lot

**Comment by Aleksey28** [comment] 2023-01-13 07:21
Would you please elaborate on why the suggested solution is not appropriate for your usage scenario?

**Comment by bbutel** [comment] 2023-01-13 07:37
Hi,

your prososals are:

- alpha feature proxyless: This feature breaks so many our tests that we cannot spent time to adapt them for an alpha experimentation functionnality.
- catching JS error with a reg exp: the risk here is to catch too much errors than expected and we cannot take that risk

That's why we did a patch of hammer-proxy on our side. But a patch should be temporary and we expect that you will fix this testcafe issue soon.

This issue was opened two months ago. I sincerely hope it will be fixed very soon.

thx a lot

**Comment by Aleksey28** [comment] 2023-01-16 08:21
Hi @bbutel,

With the option I mentioned before, you can skip only this error as the author suggested. Other errors won't be ignored. If your patch also skips this error, it will be the same.

```cli
testcafe chrome test.js -e stack='/.*MethodCallInstrumentation\._error.*/g'
```
As for the reason for this error, we will update this thread once we have any news.

**Closed** 2023-02-03 03:22 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, FREQUENCY: level 1, STATE: possibly fixed in proxyless
