### ISSUE TITLE
Typetext is not working on div with contenteditable="plaintext-only"

### ISSUE THREAD

**Issue by PhilippRaab** [DevExpress/testcafe#6540] opened 2021-09-14 08:08 UTC
### What is your Test Scenario?
Type a text in a editable div where the `contenteditable` attribute is set to `plaintext-only`.
Availability: https://caniuse.com/mdn-html_global_attributes_contenteditable_plaintext-only
 
### What is the Current behavior?
Testcafe is not able to change the text, even though it's working in the browser (chrome 93).
 
### What is the Expected behavior?
Testcafe should be able to edit the text inside the div.
 
### What is your web application and your TestCafe test code?
https://github.com/PhilippRaab/testcafe-contenteditable-bug

### Steps to Reproduce:

How to start the test:
 * `yarn install`
 * `yarn start`
 * in another shell: `yarn test`
 
The test should add a text in both of the contenteditable divs, but is only able to add it to the one with `contenteditable="true"`

### Your Environment details:
 
* testcafe version:                   1.16.0
* node.js version:                    v16.9.1
* command-line arguments:  testcafe chrome test.ts
* browser name and version: Chrome 93
* platform and version:          Windows 10

**Comment by AlexanderMoiseev** [comment] 2021-09-15 07:10
Hello, 

Thank you for your input. We have reproduced the problem and need some time to investigate it, please stay tuned.

**Comment by AlexKamaev** [comment] 2023-08-21 14:30
We decided to close the issue since it's not popular among TestCafe users. If you need to use ContentEditable divs with the `plaintext-only` attribute, you can use the following workaround:

```JS
async function typeInPlainTextContentEditable (t, selector, text) {
  await t.click(selector);
  await t.pressKey(text.split('').join(' '));
}

test('Typetext on contenteditable plaintext-only', async (t) => {
  await typeInPlainTextContentEditable(t, Selector('.content-editable-plaintext'), 'add');
  await t.debug();
});
```

**Closed by AlexKamaev** 2023-08-21 14:30 UTC
Labels: TYPE: enhancement, HELP WANTED
