### ISSUE TITLE
TestCafe does not connect to headless Chromium 68.0.3440.75-r0

### ISSUE THREAD

**Issue by dawiddylowicz** [DevExpress/testcafe#2709] opened 2018-08-08 09:22 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
```
$ testcafe 'chromium:headless --no-sandbox' ui-tests --selector-timeout 15000 --skip-js-errors --quarantine-mode
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

On 31th July, [Alpine edge community repository has bumped chromium version](https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium) from `64.0.3282.168-r2` to `68.0.3440.75-r0`. After that, testcafe tests has stopped working due to connection issues with the new browser's version.

### What is the expected behavior?
TestCafe should successfully connect to the chromium headless browser and run the tests.

### How would you reproduce the current behavior (if this is a bug)?
Try to run TestCafe tests using Chromium headless browser from Alpine edge community repository (chromium version: `68.0.3440.75-r0`)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: docker node:8.11.2-alpine
* testcafe version: 0.20.4 (also 0.21.0)
* node.js version: 8.11.2
* chromium version: `68.0.3440.75-r0`

**Comment by AndreyBelym** [comment] 2018-08-08 11:09
Hi @dawiddylowicz, I've rebuilded the official TestCafe image (`testcafe/testcafe`), and can't reproduce the problem with new Chromium. Could you please share your image or Dockerfile?

**Comment by dawiddylowicz** [comment] 2018-08-08 13:04
Dockerfile:

```
FROM node:8.11.2-alpine

# https://github.com/facebook/flow/issues/3649
RUN apk --no-cache add ca-certificates wget && \
  wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub && \
  wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-2.27-r0.apk && \
  apk add glibc-2.27-r0.apk

# install latest Chromium for UI tests
RUN apk add chromium --update-cache --repository http://nl.alpinelinux.org/alpine/edge/community && \
  rm -rf /var/cache/apk/*

COPY --chown=node:node package.json yarn.lock /usr/src/app/
WORKDIR /usr/src/app
USER node

RUN yarn install --frozen-lockfile
COPY --chown=node:node . .

# Vanilla node doesn't contain all locales, but we can provide them at runtime.
# https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime
ENV NODE_ICU_DATA=/usr/src/app/node_modules/full-icu
ENV NODE_ENV=production

RUN yarn build
EXPOSE 8080

CMD ["yarn", "start:prod"]
```

**Comment by AndreyBelym** [comment] 2018-08-08 13:57
I've found that the `node:8.11.2-alpine` image is based on the `alpine:3.6` image: [Dockerfile](https://github.com/nodejs/docker-node/blob/master/8/alpine/Dockerfile#L1). I don't think that it's possbile to mix packages from `edge` and `3.6` in a single installation.

I 've tried to modify first two steps of your Dockerfile to be:
```
FROM alpine:edge

# https://github.com/facebook/flow/issues/3649
RUN \
  addgroup -g 1000 node && \
  adduser -u 1000 -G node -s /bin/sh -D node && \ 
  apk --no-cache add ca-certificates wget && \
  wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub && \
  wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-2.27-r0.apk && \
  apk add glibc-2.27-r0.apk && \
  apk add nodejs nodejs-npm && \
  npm i -g yarn
```
and it fixed the issue for me.

**Comment by dawiddylowicz** [comment] 2018-08-08 14:54
Thanks for investigating @AndreyBelym. I tried updating Dockerfile as suggested and it magically started working.

Re:
> I don't think that it's possbile to mix packages from edge and 3.6 in a single installation.

technically you can as per this command:

`RUN apk add chromium --update-cache --repository http://nl.alpinelinux.org/alpine/edge/community && \
  rm -rf /var/cache/apk/*`

but possibly there's some dependency mismatch that caused the issue. Nevertheless, it works now!

**Comment by AndreyBelym** [comment] 2018-08-08 14:55
So closing this as resolved.

**Closed by AndreyBelym** 2018-08-08 14:55 UTC
Labels: To be reproduced
