### ISSUE TITLE
Does testcafe support chrome to save session

### ISSUE THREAD

**Issue by haoshasha** [DevExpress/testcafe#1716] opened 2017-08-18 04:00 UTC
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AlexanderMoskovkin** [comment] 2017-08-18 05:55
duplicate of #1677

**Closed by AlexanderMoskovkin** 2017-08-18 05:55 UTC
Labels: REASON: duplicate
