### ISSUE TITLE
Inaccessibility Issues with Sites using Cloudflare Turnstile (e.g., chat.openai.com, kick.com)

### ISSUE THREAD

**Issue by SurfSkip-AI** [DevExpress/testcafe#7890] opened 2023-07-14 20:41 UTC
### What is your Scenario?

We're using testcafe-hammerhead as a core part of our testing infrastructure. Our project involves interacting with various websites during testing, some of which use Cloudflare Turnstile for verification purposes (e.g., https://chat.openai.com/ and https://kick.com/). We've been encountering issues accessing these sites.

### What is the Current behavior?

Currently, when we attempt to interact with sites that use Cloudflare Turnstile, we're unable to gain access despite successful verification. Upon clicking on the verification, a 'Success' message is displayed, but the site remains inaccessible and does not proceed beyond the verification page.

### What is the Expected behavior?

The expected behavior after clicking on the verification and receiving a 'Success' message would be to gain access to the site and proceed beyond the verification page. TestCafe Hammerhead should seamlessly handle the interaction with the Cloudflare Turnstile verification process.

### What is your public website URL? (or attach your complete example)

We're encountering this issue across multiple sites, but for reproducibility, we're using a local setup at localhost:1400.

### What is your TestCafe test code?

Latest Source 

### Steps to Reproduce

1.Setup TestCafe Hammerhead and run it
2.Navigate to a site that uses Cloudflare Turnstile, such as popular sites like https://chat.openai.com/ or https://kick.com/.
3.Attempt to verify and access the site.
4. Observe that despite receiving a 'Success' message, the site does not proceed beyond the verification page.

### TestCafe version

Latest

### Command-line arguments

node node_modules/gulp/bin/gulp http-playground

**Comment by miherlosev** [comment] 2023-07-20 01:13
Hi @RichiRossi,

Thank you for the shared information. I've reproduced the issue.

For the team
![image](https://github.com/DevExpress/testcafe/assets/4133518/f9d0d5fb-816f-4d59-bcdb-3fe6bc653ebc)

**Comment by RichiRossi** [comment] 2023-07-20 07:14
> miherlosev

Thanks for taking the time to reproduce the issue. You're the best! 🙌

By the way, while we're on the topic, do you happen to have any insights into what might be causing the Cloudflare Turnstile issue specifically on our favorite tech website, [chat.openai.com](url)? 

Thanks again for your help, my friend! 🤗

**Comment by SurfSkip** [comment] 2023-07-26 09:56
> > miherlosev
> 
> Thanks for taking the time to reproduce the issue. You're the best! 🙌
> 
> By the way, while we're on the topic, do you happen to have any insights into what might be causing the Cloudflare Turnstile issue specifically on our favorite tech website, [chat.openai.com](url)?
> 
> Thanks again for your help, my friend! 🤗

Do we have some progress or updates on this? @miherlosev @Artem-Babich

**Comment by Artem-Babich** [comment] 2023-07-26 13:16
Hi,

> > miherlosev
> 
> Thanks for taking the time to reproduce the issue. You're the best!
> 
> By the way, while we're on the topic, do you happen to have any insights into what might be causing the Cloudflare Turnstile issue specifically on our favorite tech website, [chat.openai.com](url)?
> 
> Thanks again for your help, my friend! hugs

@RichiRossi, We don't have any information about this now since the issue requires research.


> Do we have some progress or updates on this? @miherlosev @Artem-Babich

@SurfSkip, There are no updates on this issue. We are still researching it and cannot give you any ETA.

**Comment by SurfSkip** [comment] 2023-10-04 08:56
Hey @Artem-Babich and @Aleksey28, do we have any more information regarding the Cloudflare Turnstile issue? 

> Hi @RichiRossi,
> 
> Thank you for the shared information. I've reproduced the issue.
> 
> For the team ![image](https://user-images.githubusercontent.com/4133518/254744939-f9d0d5fb-816f-4d59-bcdb-3fe6bc653ebc.png)

**Comment by PavelMor25** [comment] 2023-12-01 07:05
Hello,

`testcafe-hammerhead` is a proxy designed for use with `TestCafe`. Using it separately is not considered a target use case. Since the issue is not reproducible in TestCafe's [Native Automation mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode), the priority for this task is low. We do not plan to solve this problem and are closing the ticket.

However, you are always welcome to create a pull request (PR) regarding this issue. We will review it.

**Closed by PavelMor25** 2023-12-01 07:05 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, FREQUENCY: level 1
