### ISSUE TITLE
v1.10.0+ intermittently hangs in child window

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#5910] opened 2021-02-02 22:02 UTC
### What is your Test Scenario?

I'd like to be able to consistently run through test scenarios which utilise child windows. 
Using `^1.10.0-rc.4` my tests run to completion (_for the majority of the time_), whereas upgrading to `1.10.0` (and beyond), it seems that my tests hang after opening the Twitter child window... even if the test runs to completion, the result isn't reported back to the console.

We have 3 scenarios: Share a petition as a Guest; Authenticated user; session expired user.

### What is the Current behavior?

The Share via Twitter tests will intermittently hang, for any of the user states (usually a different test each time). 
 
### What is the Expected behavior?

Like `1.10.0-rc.4`, the tests shouldn't hang
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

I copied/pasted the test, to have 15 in total. It tends to hang at test ~8, but has happened as early as the first run.

 
```js
 /* global window */
import { ClientFunction, Selector } from 'testcafe';

const baseUrl = 'https://www.change.org';
const petitionSlug = 'change-org-to-test-a-small-petition';

const getDomainName = () => {
  return baseUrl.replace(/^https?:\/\//, '');
};

const getCurrentUrl = ClientFunction(() => window.location.href);

fixture('Share with Twitter').page(baseUrl);

test('Share Twitter 1', async t => {
  await t.navigateTo(`p/${petitionSlug}/psf/share?share=1`);

  const petitionPageRegex = new RegExp(`${getDomainName()}/p/${petitionSlug}`);;
  const twitterUrlRegex = new RegExp(`twitter.com/intent/tweet.*${getDomainName()}%2Fp%2F${petitionSlug}`);

  const twitterButton = Selector('.js-twitter-share-button');
  const href = await twitterButton.getAttribute('href');

  await t
    .expect(href)
    .match(petitionPageRegex)
    .click(twitterButton)
    .expect(getCurrentUrl())
    .match(twitterUrlRegex);
  console.log('Done');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "browsers": ["chrome:headless:emulation:device=iPhone X"],
  "src": "./tests/**/*.js",
  "clientScripts":[
    {
      "module":"axe-core/axe.min.js"
    }
  ],

  "assertionTimeout": 15000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots"
  }
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```
The "src" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 88.0.4324.96 / macOS 10.15.7 (Emulating iPhone X)

 Share with Twitter
Done

---

The "src" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 88.0.4324.96 / macOS 10.15.7 (Emulating iPhone X)

 Share with Twitter
Done
 ✓ Share Twitter 1
Done
```
</details>

<details>
<summary>Screenshots:</summary>

This is just a screenshot of the console... as you can see, the last step completes but the test hangs before a result is written back to the console.

```
![Screenshot 2021-02-02 at 1 51 25 PM](https://user-images.githubusercontent.com/37812673/106667501-d8e23780-655d-11eb-8ed5-177d64ecb043.png)

```
</details>

### Steps to Reproduce:

1. Go to my website ...
2. Execute this test...
3. Re-run if suite/fixture completes (but in my experience, it has never ran to completion)...
 
### Your Environment details:
 
* testcafe version: 1.10.0+                   
* node.js version: ~12.14.1                   
* command-line arguments:  testcafe "chrome:headless:emulation:device=iPhone X" 
* browser name and version: 
* platform and version:          
* other:

**Comment by AlexKamaev** [comment] 2021-02-03 08:57
@rob4629
Thank you for your detailed description. I managed to reproduce the issue without `chrome:headless:emulation` mode.
I cloned your test 15 times and I can confirm that your tests hang in v1.10.0 and later versions.
At the moment, I can't say with certainty what the cause of the issue is. I found that the browser opens two child `twitter` windows instead of one in problematic cases. I believe that this may be the cause.
I'll research this issue further.

**Comment by rob4629** [comment] 2021-02-03 17:30
I noticed this happening in `1.10.0-rc.6` (or `rc.7`...), so the issue was introduced somewhere between `rc.4` and `rc.6/7`.

Hope that might help in the investigation 🤷🏻‍♂️

**Comment by Farfurix** [comment] 2021-02-09 14:22
Closed in https://github.com/DevExpress/testcafe-hammerhead/pull/2582

**Closed by Farfurix** 2021-02-09 14:22 UTC
Labels: FREQUENCY: level 2, SYSTEM: window management, TYPE: bug

**Comment by kojoru** [comment] 2021-02-09 14:59
@AlexKamaev is there a version of TestCafe with the fix that we can test this with?

**Comment by AlexKamaev** [comment] 2021-02-10 07:23
@kojoru we are going to publish a new `1.11.0-rc.1` version in the near future. Please check the [https://www.npmjs.com/package/testcafe](https://www.npmjs.com/package/testcafe) page to get updates.
Please note that this issue is specific to the scenario of @rob4629, so if your issue still exists after the fix, you can share your example with us and we will check it as well.

**Comment by rob4629** [comment] 2021-02-10 15:27
I've tested the change locally, and it resolves my issue. Thanks @AlexKamaev
