### ISSUE TITLE
Problem when starting chrome 

### ISSUE THREAD

**Issue by Turkirafaa** [DevExpress/testcafe#2577] opened 2018-07-02 07:28 UTC
### Are you requesting a feature or reporting a bug?
Yes 

### What is the current behavior?
When i am testing with chrome Have problem with graphic 
see the attach file 

### How would you reproduce the current behavior (if this is a bug)?
![skarmavbild 2018-07-02 kl 09 24 41](https://user-images.githubusercontent.com/32999333/42150439-2b28a27c-7dda-11e8-9566-dffe50c023a3.png)
![skarmavbild 2018-07-02 kl 09 24 59](https://user-images.githubusercontent.com/32999333/42150445-32d2e136-7dda-11e8-9639-ab48819b0d3c.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Mac 
* testcafe version: 0.19.1-dev20180305
* node.js version: 6.1.0

**Comment by AndreyBelym** [comment] 2018-07-02 07:44
Hi @Turkirafaa, please update your TestCafe installation to v0.20.4. What Chrome and macOS versions do you use? Which command do you use to start TestCafe? Could you please try to specify `chrome:userProfile` as a browser?

**Comment by Turkirafaa** [comment] 2018-07-02 08:05
Hi i am using chrome Version 67.0.3396.99 (Officiell version) (64 bitar) and macOS version 10.13.4
tastcafe chrome ****.js -ne . Can you please give me the command to install the new version 
Thank you so much for your help.

**Comment by AndreyBelym** [comment] 2018-07-02 08:30
`npm install -g testcafe@latest` or `npm install testcafe@latest` if you've added TestCafe into your project's `package.json`.

**Comment by Turkirafaa** [comment] 2018-07-02 08:42
Hi @AndreyBelym  please your advice because still i have the same problem.

**Comment by AndreyBelym** [comment] 2018-07-02 08:52
Do you have this artifacts when running Chrome without TestCafe? Have you tried to specify `chrome:userProfile` as a browser?

**Comment by Turkirafaa** [comment] 2018-07-02 08:54
No it's only showing when i  run TestCafe

**Comment by ferencbeutel4711** [comment] 2018-07-04 21:49
I have the same problem (and a coworker too)
latest testcafe, latest chrome, osx 10.13.2
It only happens when started via testcafe and was not happening some time ago. Ive tried it with an old testcafe version and it still happens so i guess a chrome update introduced the error

**Comment by AndreyBelym** [comment] 2018-07-05 06:30
Hi @ferencbeutel4711, @Turkirafaa, thank you for investigation! `chrome:userProfile` starts the browser with the default Chrome profile that you use for regular browsing. It means test URLs will be recorded in your browsing history, and installed extensions can have unexpected and unpredictable impact on the testing environment. Also, due to technical limitations you can't use concurrency mode together with `userProfile` mode, because each browser instance needs a separate profile.

**Comment by miherlosev** [comment] 2018-08-07 08:33
We cannot reproduce the issue, but there is a workaround. So, I will close the issue.
Feel free to reopen the issue if the problem persists and you can provide an example to reproduce it.

**Closed by miherlosev** 2018-08-07 08:33 UTC
Labels: To be reproduced
