### ISSUE TITLE
TS: provide better types with generics

### ISSUE THREAD

**Issue by Hotell** [DevExpress/testcafe#2248] opened 2018-03-23 15:32 UTC
### Are you requesting a feature or reporting a bug?
feature(typescript)

### What is the current behavior?
lot's of types use `any` which mitigates the point of using types and forces users to write lot of boilerplate with type casting. There is a better solution with default generics, which will also not introduce breaking change to existing type definitions. win win

### What is the expected behavior?

make following types Generic:
- `ClientFunction`
- `Selector`
- `SelectorAPI`

I can submit PR with better type definitions if you're ok with that 👍 

### Specify your

* operating system: 10.13.3
* testcafe version: 0.19.1
* node.js version: 9.10

**Comment by AndreyBelym** [comment] 2018-10-15 16:11
I think it can be considered as a duplicate of #1529

**Closed by AndreyBelym** 2018-10-15 16:11 UTC
Labels: AREA: repo/workflow, SYSTEM: API, TYPE: enhancement
