### ISSUE TITLE
Allow extending test controller instance with custom methods (server-only actions)

### ISSUE THREAD

**Issue by beyondcompute** [DevExpress/testcafe#2765] opened 2018-08-23 11:29 UTC
### Are you requesting a feature or reporting a bug?

I am requesting a feature: allow custom (server-only) test controller instance methods for more fluent APIs.

### What is the current behavior?

Currently I have to break my nice fluent API chain to implement some checks. Example:

```js
  // somewhere in a test
  await t
    .typeText(someInput)
    .click(submitButton);

  const consoleMessages = await t.getBrowserConsoleMessages();
  if (consoleMessages.error.length) {
    // handle console error messages
  }

  await t
    .click(logoutButton); // continue test
```

There are other scenarios like checking if there’s the first-time user tutorial and skipping it, etc.

### What is the expected behavior?

```js
// set up
import { t } from 'testcafe';

t.extendApi('checkConsole', () => {
  const consoleMessages = await t.getBrowserConsoleMessages();
  if (consoleMessages.error.length) {
    // handle console error messages
  }
});

  // later in a test
  await t
    .typeText(someInput)
    .click(submitButton)
    .checkConsole()
    .click(logoutButton);
```

Some simpler API is even possible:
```js
  await t
    .typeText(someInput)
    .click(submitButton)
    .executeCustom(checkConsole, param1, param2)
    .click(logoutButton);
```

Again those methods should not be fully-fledged _actions_ (supported on Hammerhead side, etc.) but rather just syntactic sugar for making tests more concise and maintainable.

As always with great appreciation for DevExpress’ team work 🥇, thank you!

**Comment by miherlosev** [comment] 2018-08-27 10:57
It's a duplicate of https://github.com/DevExpress/testcafe/issues/1535

**Closed by miherlosev** 2018-08-27 10:57 UTC
