### ISSUE TITLE
chrome:emulation:device=iphone X t.click() produces t.rightClick() shortcut menu

### ISSUE THREAD

**Issue by philga7** [DevExpress/testcafe#8134] opened 2024-01-30 16:03 UTC
### What is your Scenario?

With the latest version of TC (3.5) and using Node 20.10.0, while all non-emulated tests are running without issue, when we go to use emulation mode (and for just about any mobile emulated device; we happen to use 'iphone X'), when a test executes a t.click() method call, that call instead produces a t.rightClick() result. At this point, the right-mouse-button shortcut menu appears on-screen and the test hangs (must be Ctrl-C out).

For background, this behavior seems to have been occurring for us since TC v3.0 (when the switch was made to the CDP execution engine). We've been holding off on upgrading since then, wondering if these (and other now-fixed bugs) wouldn't get resolved over time.

### What is the Current behavior?

Only under emulation mode, when the t.click() method is invoked, TC produces a t.rightClick() result instead. A potential work-around has been to use t.doubleClick() -- interestingly enough, t.doubleClick() appears to only produce a t.click()!

### What is the Expected behavior?

Under emulation mode, the t.click() method should result in a single left click instead of a t.rightClick() call.

### What is the public URL of the test page? (attach your complete example)

The particular URL doesn't seem to matter. Instead, invoke a given test under `testcafe 'chrome:emulation:device=iphone x' <test_case>.

### What is your TestCafe test code?

await t
    .expect(home.searchBar.visible)
    .ok('Failed to locate Search Bar on Home Page.')
    .click(home.searchBar)
    .typeText(home.searchBar, 'Yak', { replace: true })
  await t
    .expect(home.firstSuggestion.visible)
    .ok('Failed to locate First Suggestion on Home Page.')
    .click(home.firstSuggestion)

We use separate page object files to import Selectors. If those details are needed, let me know.

### Your complete configuration file

const brand = process.env.BRAND
const size = process.env.SIZE

if (!brand) {
  throw new Error('BRAND environment variable is required')
}

if (!size) {
  throw new Error('SIZE environment variable is required')
}

/**
 * @type { import('testcafe') & RunOptions & TestCafeConfigurationOptions }
 */
module.exports = {
  clientScripts: [
    './node_modules/@testing-library/dom/dist/@testing-library/dom.umd.js',
    './node_modules/@rentpath/testcafe-utils/testcafe-client-runtime-config.js',
  ],
  quarantineMode: process.env.CI
    ? { successThreshold: 1, attemptLimit: 3 }
    : undefined,
  // src: ['e2e/common/tests', `e2e/${process.env.BRAND}/tests`],
  skipJsErrors: true,
  reporter: [
    { name: 'spec' },
    { name: 'json', output: `artifacts/reports/${size}/json_report.json` },
  ],
  disableHttp2: true,
  browserInitTimeout: 180000,
  pageLoadTimeout: 180000,
  selectorTimeout: 8000,
  assertionTimeout: 8000,
  disableMultipleWindows: true,
  screenshots: {
    takeOnFails: true,
    path: 'artifacts/screenshots',
    pathPattern: `${size}/` + '${DATE}_${TIME}/${USERAGENT}/${RUN_ID}-${TEST}',
    thumbnails: false,
  },
  videoPath: 'artifacts/videos',
  videoOptions: {
    failedOnly: true,
    pathPattern:
      `${size}/` + '${DATE}_${TIME}/${USERAGENT}/${RUN_ID}-${TEST}.mp4',
  },
  compilerOptions: {
    typescript: {
      options: {
        esModuleInterop: true,
        resolveJsonModule: true,
      },
    },
  },
  userVariables: {
    axeReportPath: 'artifacts/accessibility/' + size,
    zipFolderLocation: 'artifacts/accessibilityZip/' + size,
  },
  hooks: {
    testRun: {
      before: async function () {
        await removeReportDir()
      },
    },
    reporter: {
      onBeforeWrite: {
        spec: function (writeInfo) {
          if (writeInfo.initiator === 'reportTestDone') {
            const { testRunInfo } = writeInfo.data || {}
            if (testRunInfo.hasOwnProperty('durationMs')) {
              writeInfo.formattedText =
                writeInfo.formattedText + ' (' + testRunInfo.durationMs + 'ms)'
            }
          }
        },
      },
    },
  },
}

async function removeReportDir(reports = 'e2e/reports') {
  const fsp = require('fs').promises
  if (
    await fsp
      .access(reports)
      .then(() => true)
      .catch(() => false)
  ) {
    // delete directory recursively
    await fsp.rmdir(reports, { recursive: true, force: true })
    console.log(`${reports} was deleted!`)
  }
}

### Steps to Reproduce

1. Execute script via package.json script: testcafe 'chrome:emulation:device=iphone X --disable-dev-shm-usage'
2. Test successfully runs until first t.click() is encountered
3. On t.click(), the right-mouse-button shortcut menu is produced
4. Test hangs and never finishes

### TestCafe version

3.5.0

### Node.js version

v20.10.0

### Command-line arguments

"SIZE=small METADATA='breakpointSmall=true' testcafe 'chrome:emulation:device=iphone X --disable-dev-shm-usage' --fixture-meta breakpointSmall=true" <test_case(s)>

### Browser name(s) and version(s)

Chrome 121.0.0.0

### Platform(s) and version(s)

MacOS Sonoma 14.3

**Comment by PavelMor25** [comment] 2024-02-02 11:21
Hello @philga7 , 

I can't reproduce the issue (Chrome 120.0.0/Node 20/macOS 14.2). Were you able to reproduce the issue on the Windows OS? We would appreciate it if you could share [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue). At present, we can't determine the cause of this issue.

**Comment by philga7** [comment] 2024-02-02 17:20
@PavelMor25 : I'm working on seeing about an alternative environment (such as Windows). Also, at present, the example site is not reproducing this issue (and probably a good place to check in the future!).

**Comment by PavelMor25** [comment] 2024-02-05 09:55
If there are currently no problems, I will close the issue. However, if this behavior occurs again, we will reopen it.

**Closed by PavelMor25** 2024-02-05 09:55 UTC
Labels: TYPE: bug, STATE: Need response
