### ISSUE TITLE
Seeing slow static asset loading

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#2934] opened 2018-10-04 23:53 UTC
I am having an issue running my tests and I'm just wondering if anyone has any advice on what might be wrong. 

When my test loads, the browser seems to load static assets very slowly (much more slowly than if I just run my app in the browser normally). Very small assets (like a few kb) are taking up to 5 seconds to load, and it is causing my tests to timeout. The assets are loaded from a local dev server, so it should be very fast. The slowness is causing my assertions to time out and fail.

I'm not convinced the content of my app matters, because it happens even when loading index.html (which is 1.7 kb), and that is the first thing that would be loaded.

It does not happen to my coworkers with the same code, and I've tried to match their versions of testcafe, node, nvm, yarn, chrome. os x, and everything else I can think of. We are in the same office with the same internet speeds, using similar computers. It happens on firefox and safari also.

It sounds more like an issue with my machine than a bug, but I'm not really sure what might be wrong. Is this something anyone has seen before? Or is there any advice anyone has on where I should look for things that might be wrong or causing the slowness?

### Specify your

* operating system: OS X High Sierra
* testcafe version: 0.21.1 (also 0.18 and 0.22) 
* node.js version: 9.11.1 (also 8 and 10)

**Comment by miherlosev** [comment] 2018-10-05 08:20
Hi @bdwain 

Would you please provide a screenshot of the 'Network' panel of the Firefox DevTools and mark slow asserts on it?

![image](https://user-images.githubusercontent.com/4133518/46523959-ffa9d980-c88f-11e8-843d-ad0b982e34d4.png)

**Comment by bdwain** [comment] 2018-10-05 09:04
Sure. If you look there, the very first request takes over 5 seconds and it's just a 5 kb html file from localhost. gfr-orders-e8856f00b.css and gfr-orders-e8856f00b.js are also very slow, as are a bunch of static assets towards the bottom.

<img width="1649" alt="screen shot 2018-10-05 at 3 58 46 am" src="https://user-images.githubusercontent.com/3982094/46526151-1120c080-c853-11e8-94a8-ea937f0487e0.png">

**Comment by LavrovArtem** [comment] 2018-10-08 15:30
Could you please capture a screenshot and show response headers for slow requests?

**Comment by bdwain** [comment] 2018-10-08 16:05
Sure (one thing to note is that index.html is not so slow anymore. but the rest of the static assets are)

![screen shot 2018-10-08 at 10 56 05 am](https://user-images.githubusercontent.com/3982094/46620035-3f1f3280-cae9-11e8-917d-7e4c85e2e4b0.png)

This one had a 304 after the app refreshed in the test (but it was slow with a 200 the first time)
![screen shot 2018-10-08 at 10 57 22 am](https://user-images.githubusercontent.com/3982094/46620036-3f1f3280-cae9-11e8-9f81-2cc10c2964ff.png)

The browser itself just shows my app's loader 

![screen shot 2018-10-08 at 11 01 33 am](https://user-images.githubusercontent.com/3982094/46620264-e56b3800-cae9-11e8-97ce-ce9ce7c26ed4.png)

(there's also the black testcafe bar below that with my test description and browser info, Chrome 69, Mac OS X 10.13.6)

**Comment by LavrovArtem** [comment] 2018-10-09 07:49
Thanks for the provided information about response headers. However, the information is currently insufficient to determine the cause of the issue and find a precise solution. Please clarify the steps to replicate the issue so that we will be able to provide you with any solution.

**Comment by bdwain** [comment] 2018-10-09 16:08
after further inspection, it seems the worst offender for me is a json file that i request with window.fetch, not a javascript file. That file is tiny (240 bytes). It seems different in the devtools because that file has an initiator of hammerhead.js in the devtools network tab, rather than my code.

The problem seems to be when the response is a 304 (not 200) after refresh, and not so much on initial load. It seems to behave differently compared to when I hit my local site directly in the browser, as if testcafe's local server is slowing things down somehow.

I ran `node ./node_modules/.bin/testcafe chrome --debug-on-fail ./foo.js` and this is foo.js

```js
fixture('foo')
test('is slow', async t => {
  await t.navigateTo('http://localhost:5101');
  await t.wait(15000);
  //here i look at the network tab and toggles.json loaded very quickly (like 200 ms)
  await t.eval(() => {
    window.location.reload();
  });
  await t.wait(150000);
  //here i look at the network tab and toggles.json loaded slowly (like 3.5 seconds)
});
```

Here is the request and response headers for the initial fast request

![screen shot 2018-10-09 at 11 02 22 am](https://user-images.githubusercontent.com/3982094/46682476-414dc380-cbb3-11e8-91b5-1bd34dfc69d1.png)

and here are the ones for the slow request,

![screen shot 2018-10-09 at 11 02 35 am](https://user-images.githubusercontent.com/3982094/46682523-64787300-cbb3-11e8-9af6-16baf8d07ae2.png)

If i just run my site normally on my local server, on refresh, when toggles.json returns a 304, it is still fast (like 10 ms). So it seems like testcafe is slowing down the 304 response somehow.

**Comment by LavrovArtem** [comment] 2018-10-10 11:37
It looks like it is the `0.18` version and the described issue was already fixed in higher versions. Could you please specify a version of `testcafe` that was used in the previous comment?

**Comment by LavrovArtem** [comment] 2018-10-11 14:52
Thank you for the provided information. No, it is just my supposition. TestCafe can be installed locally and globally at the same time. To check the exact version that is used for running tests, you can verify your version by running this command:
```cmd
testcafe --version
```
We would need a sample to reproduce this behavior and thoroughly research it.

**Comment by bdwain** [comment] 2018-10-11 15:11
what was the issue in 0.18? Maybe it would help diagnose my issue?

**Comment by LavrovArtem** [comment] 2018-10-12 09:37
Until we have a clear reproduction sample where we can see the issue in action, we are not able to find a solution.
 
You can learn more about the issue in the previous version in [this PR](https://github.com/DevExpress/testcafe-hammerhead/pull/1638).

**Comment by miherlosev** [comment] 2018-10-19 07:53
I will close the issue because no activity has been encountered for a long time.
Feel free to reopen the issue if the problem persists and you can provide an example to reproduce it.

**Closed by miherlosev** 2018-10-19 07:53 UTC
Labels: STATE: Need clarification

**Comment by Bakanych** [comment] 2020-04-27 07:07
It's happening now for the latest version too (1.8.4).

**Comment by alexey-lin** [comment] 2020-04-28 14:58
Sorry to hear that. But we cannot find the cause of the issue without reproducing it on our side.
