### ISSUE TITLE
Mac OS browser sessions not closed

### ISSUE THREAD

**Issue by pcieslak** [DevExpress/testcafe#2926] opened 2018-10-03 13:00 UTC
https://github.com/DevExpress/testcafe/blob/59c69eb4e6e464c4870790ae48eb3ea353a23edf/src/utils/kill-browser-process.js#L46

Can we update mentioned line to be smth like:
const processOptions = { arguments: browserId, psargs: process.platform === 'darwin' ? 'aux'  : '-ef'};

This way Mac OS will be closing browsers upon ending execution.
For reference https://nodejs.org/api/process.html#process_process_platform

**Comment by AndreyBelym** [comment] 2018-10-10 07:13
It's a duplicate of #2860.

**Closed by AndreyBelym** 2018-10-10 07:14 UTC
Labels: Need clarification
