### ISSUE TITLE
Docker :latest image is missing 'browser/provider/pool'

### ISSUE THREAD

**Issue by kruckenb** [DevExpress/testcafe#3037] opened 2018-10-26 05:00 UTC
Running `docker run testcafe/testcafe` with the testcafe/testcafe:latest container updated 12 hours ago fails with:

```
module.js:549
    throw err;
    ^

Error: Cannot find module '../browser/provider/pool'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/testcafe/lib/cli/cli.js:87:13)
```

Inspecting the container shows that in fact `browser/provider/pool` is not there:

```
# $ docker run -it --entrypoint "/bin/ash" testcafe/testcafe
/ $ ls -l /opt/testcafe/lib
total 68
drwxr-xr-x    2 root     root          4096 Oct 25 16:24 api
drwxr-xr-x    2 root     root          4096 Oct 25 16:24 assertions
drwxr-xr-x    2 root     root          4096 Oct 25 16:24 cli
drwxr-xr-x    8 root     root          4096 Oct 25 16:24 client
drwxr-xr-x    2 root     root          4096 Oct 25 16:24 client-functions
drwxr-xr-x    2 root     root          4096 Oct 25 16:24 compiler
-rwxr-xr-x    1 root     root          5110 Oct 25 16:24 embedding-utils.js
drwxr-xr-x    2 root     root          4096 Oct 25 16:24 errors
-rwxr-xr-x    1 root     root          8263 Oct 25 16:24 index.js
drwxr-xr-x    2 root     root          4096 Oct 25 16:24 notifications
-rwxr-xr-x    1 root     root         14690 Oct 25 16:24 testcafe.js
```
This is Docker Version 2.0.0.0-beta1-mac75 on MacOS 10.13.6

**Comment by AndreyBelym** [comment] 2018-10-26 07:13
I've reproduced the problem, and already rebuilt and republished the image. Please, check it on your side.

I don't have any clues about what happened yesterday, because `docker-build` and `docker-publish` tasks didn't report any errors. I will investigate it in the context of #3026, and close this issue because I've published the fix to the Docker Hub.

**Closed by AndreyBelym** 2018-10-26 07:13 UTC
Labels: !IMPORTANT!, AREA: docker, TYPE: bug
