### ISSUE TITLE
take screenshot breaks with firefox 63.0

### ISSUE THREAD

**Issue by joma74** [DevExpress/testcafe#3027] opened 2018-10-24 22:49 UTC
### What is your Test Scenario?
taking screenshot
 
### What is the Current behavior?
Was unable to take a screenshot due to an error.
 
### What is the Expected behavior?
a screenshot
 
### What is your web application and your TestCafe test code?
https://github.com/joma74/angular-ultimate-pro.git
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js

// @ts-ignore
import { AngularSelector, waitForAngular } from "testcafe-angular-selectors"
var Mustache = require("mustache")

const fixtureName = "Index_Page_Test"

fixture(fixtureName)
  .page("http://localhost:4001/index.html")
  .beforeEach(async () => {
    await waitForAngular()
  })

const testName = "dom_has_critical_elements"

test(testName, async (t) => {
  // await t.debug()
  await t.takeScreenshot()
  await checkHeading(t)

  const imageAngularFirst = await AngularSelector().find(
    "img[data-desc='angular-first']",
  )
  await t.expect(imageAngularFirst.visible).ok()

  const imageAngularSecond = await AngularSelector().find(
    "img[data-desc='angular-second']",
  )
  await t.expect(imageAngularSecond.visible).ok()
})

/**
 *
 * @param {TestController} t
 */
async function checkHeading(t) {
  const heading = AngularSelector().find("h1[data-desc='heading']")
  const headingText = await heading.innerText
  const expected = Mustache.render(
    "{{ title }} from Angular App with Webpack {{ major }}.{{ minor }}.{{ patch }}",
    {
      major: "3",
      minor: "12",
      patch: "0",
      title: "Hello",
    },
  )
  await t.expect(headingText).eql(expected)
}
```
      
</details>

<details>
<summary>Your complete test report:</summary>
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite name="TestCafe Tests: Firefox 63.0.0 / Ubuntu 0.0.0, HeadlessChrome 70.0.3538 / Linux 0.0.0" tests="1" failures="0" skipped="0" errors="0" time="8.215" timestamp="Wed, 24 Oct 2018 22:25:57 GMT" >
  <testcase classname="Index_Page_Test" name="console_has_messages (screenshots: /home/joma/entwicklung/nodews/angular-ultimate-pro/target/reports/screenshots/actual/2018-10-25_00-25-48/test-1)" time="8.181">
  </testcase>
  <system-out>
  <![CDATA[
    Warnings (1):
    --
      Was unable to take a screenshot due to an error.

      TypeError: Cannot read property 'takeScreenshot' of null
          at takeScreenshot
      (/home/joma/entwicklung/nodews/angular-ultimate-pro/node_modules/testcafe/src/browser/provider/built-in/firefox/index.js:71:32)
          at Generator.next (<anonymous>)
          at step
      (/home/joma/entwicklung/nodews/angular-ultimate-pro/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
          at
      /home/joma/entwicklung/nodews/angular-ultimate-pro/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
          at new Promise (<anonymous>)
          at new F
      (/home/joma/entwicklung/nodews/angular-ultimate-pro/node_modules/core-js/library/modules/_export.js:36:28)
          at
      /home/joma/entwicklung/nodews/angular-ultimate-pro/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
          at BrowserProviderPluginHost.takeScreenshot
      (/home/joma/entwicklung/nodews/angular-ultimate-pro/node_modules/testcafe/src/browser/provider/built-in/firefox/index.js:68:44)
          at takeScreenshot
      (/home/joma/entwicklung/nodews/angular-ultimate-pro/node_modules/testcafe/src/browser/provider/index.js:294:27)
          at Generator.next (<anonymous>)
  ]]>
  </system-out>
</testsuite>
</details>
```

### Steps to Reproduce:
1. git clone https://github.com/joma74/angular-ultimate-pro.git
2. yarn ci
 
### Your Environment details:
 
* testcafe version:                   0.22.0
* node.js version:                   v8.12.0
* command-line arguments:  `testcafe 'firefox:headless,chrome:headless --no-sandbox --disable-gpu' -S -s $npm_package_config_screenshots -p $npm_package_config_screenshot_path_pattern -r spec,xunit:$npm_package_config_reports/report.xml src/tests/index-test.js`
* browser name and version: Firefox 63.0, HeadlessChrome 70.0.3538
* platform and version:           Linux Ubuntu 16.04
* other:

**Comment by joma74** [comment] 2018-10-24 22:56
See also [report.xml.txt](https://github.com/DevExpress/testcafe/files/2512617/report.xml.txt) instead of 'Your complete test report'; which can not display xml properly

**Comment by AndreyBelym** [comment] 2018-10-25 07:20
Fixed in [testcafe@0.23.0-alpha.1](https://github.com/DevExpress/testcafe/commit/fcacaa30323fafbf80a7d5a74d8da3bbdf2b2193#diff-299dacc91efcf41a3a246ff4143268c0R172).

**Closed by AndreyBelym** 2018-10-25 07:20 UTC

**Comment by joma74** [comment] 2018-10-25 11:03
@AndreyBelym  Unfortunately with testcafe@0.23.0-alpha.1 using google-chrome-stable 70.0.3538.77-1 and 64.0.3282.140-1 my test never finishes. Output stays put at
```
:~/entwicklung/nodews/angular-ultimate-pro$ cd /home/joerg/entwicklung/nodews/angular-ultimate-pro ; /home/joerg/bin/node --inspect-brk=42171 node_modules/testcafe/bin/testcafe.js chrome -S -s target/reports/screenshots/actual -p '${FIXTURE}/${TEST}/${USERAGENT}/${FILE_INDEX}.png' /home/joerg/entwicklung/nodews/angular-ultimate-pro/src/tests/index-test.js
Debugger listening on ws://127.0.0.1:42171/b04e3adf-e538-4120-bd1d-e4f34d96ff41
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
 Running tests in:
 - Chrome 70.0.3538 / Linux 0.0.0

 Index_Page_Test
```
with opened browser and screenshots taken. Pausing the debugger does not stop anywhere!? Otherwise doing some manual reload pushes in the browser seems to cancel "that" sometimes and gives success
```
 Index_Page_Test
 ✓ dom_has_critical_elements (screenshots:
 /home/joerg/entwicklung/nodews/angular-ultimate-pro/target/reports/screenshots/actual/Index_Page_Test/dom_has_critical_elements/Chrome_70.0.3538_Linux_0.0.0/1.png)


 1 passed (4m 15s)
Waiting for the debugger to disconnect...
Killed
```
_P.S. What normally takes 10 seconds something._

Test with firefox 63.0 works again though.

**Comment by joma74** [comment] 2018-10-25 20:07
Withdraw. As Travis shows, occurs 50% with firefox 63.0

**Comment by AndreyBelym** [comment] 2018-10-31 08:29
I can't reproduce the issue with Chrome, in versions 69 and 70, with and without an attached debugger. Please, open a new issue and provide an example, which can be used to reproduce the issue.

Please, provide a full test report if you still experience problems with Firefox 63.0. If you can provide a link to the problematic TravisCI build, or build log, it will be event better.

Travis is in process of migration from the container-based infrastructure to the VM-based one, and performance of Travis VMs is significantly lower that performance of Travis containers. Currently I can say that new VMs don't have enough performance to run both Chrome and Firefox in a single build. Try to split your test task to run tests separately in Chrome and Firefox.
