### ISSUE TITLE
testcafe not stop when close chrome

### ISSUE THREAD

**Issue by bhj-patrik** [DevExpress/testcafe#4695] opened 2020-01-24 09:47 UTC
### What is your Test Scenario?
run testcafe script
 
### What is the Current behavior?
when I closse chrome the process not dead and chrome run again and run the test 
 
### What is the Expected behavior?
when I closse chrome testcafe test stop 
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    v12.14.1
* command-line arguments:  
* browser name and version: chrome 79
* platform and version:          windows 10

**Comment by AlexSkorkin** [comment] 2020-01-27 07:31
This behavior is by design. If a browser stops responding or is unexpectedly closed while it executes tests, TestCafe restarts the browser and reruns the current test in a new browser instance. If the same problem occurs with this test two more times, the test run finishes and an error is thrown. Instead of closing a browser instance, you can stop the running testcafe instance.

**Closed by AlexSkorkin** 2020-01-27 07:31 UTC
Labels: STATE: Need response
