### ISSUE TITLE
inspect values while debugging

### ISSUE THREAD

**Issue by lucidtech** [DevExpress/testcafe#2665] opened 2018-07-25 20:56 UTC
### Are you requesting a feature or reporting a bug?

asking a question

### What is the current behavior?

unable to inspect values and properties when in a breakpoint - probably because I don't understand how to read the values or inspect the elements the selector returns - the properties of the components in the debugger are all functions that eventually return something

### What is the expected behavior?

I would like to understand how to inspect values before proceeding to the next line in a test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: OSX
* testcafe version: 0.19.2, react-selectors: 2.1.0
* node.js version: 7.4.0

**Comment by AndreyBelym** [comment] 2018-07-30 08:31
Hi @lucidtech, I think it's a duplicate of https://github.com/DevExpress/testcafe/issues/2677 if you need to inspect Selectors and corresponding Snapshots. Otherwise you can [attach a Node Inspector](https://nodejs.org/en/docs/guides/debugging-getting-started/) or any compatible third-party JS debugger to the TestCafe process to inspect any variable in your code.

**Closed by AndreyBelym** 2018-07-30 08:31 UTC
