### ISSUE TITLE
Testcafe tests run in docker image locally but not in docker image on github actions

### ISSUE THREAD

**Issue by roosnic1** [DevExpress/testcafe#6613] opened 2021-10-13 22:50 UTC
### What is your Test Scenario?
In our open source project we build and deploy branches once a pull request is created. We build docker containers and then deploy them into a kubernetes cluster. Once there we'd like to run our testcafe tests on the deployed instance. We do our building and deploying with github actions. We'd like to run the testcafe tests also on github actions.
 
### What is the Current behavior?
The testcafe tests work locally on multiple machines with our app running on localhost or on kubernetes. First i tried to run the tests on github actions with [TestCafe GitHub Action](https://github.com/DevExpress/testcafe-action) but always had errors like `The specified selector does not match any element in the DOM tree.` that didn't occur locally. Afterwards i tried to just use a node action and install testcafe myself. This resulted in the same behavior. Then on my machine i pulled the docker image `testcafe/testcafe` and run the tests locally inside the image with the following command:

```
docker run -v /home/koki/Development/wepublish/wepublish/tests:/tests --network="host" -it testcafe/testcafe chromium:headless /tests/e2e.ts --assertion-timeout 10000
```
Those tests run successfully against the app running locally and on kubernetes. Afterwards i updated my github actions to use the same docker image and run the tests inside. I have the following github actions setup:
```
  e2eTest:
    needs: deployment
    name: Runs e2e Test on Feature instance
    runs-on: ubuntu-latest
    container:
      image: testcafe/testcafe
      options: --user root
      #options: -v /__w/wepublish/wepublish:/wepublish/:rw
    env:
      BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Sleep for 300s
        uses: juliangruber/sleep-action@v1
        with:
          time: 300s
      - name: run tests
        if: always()
        run: /opt/testcafe/docker/testcafe-docker.sh chromium:headless tests/e2e.ts --assertion-timeout 10000
```
 but the tests fail again with the same error: `The specified selector does not match any element in the DOM tree.`. I checked the deployed application on kubernetes was reachable before the testcafe tests started.

### What is the Expected behavior?
I expect the tests to run the same way on github actions as local.
 
### What is your web application and your TestCafe test code?
This is the [PR](https://github.com/wepublish/wepublish/pull/83) in which i'm trying to setup the testcafe test.
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
Editor URL: https://editor.ftestingin.wepublish.dev/
Website URL: https://www.ftestingin.wepublish.dev/ (the 404 page is normal)
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```ts
import { ClientFunction, Role, Selector, t } from "testcafe"

const loginName = Selector('input.username')
const loginPassword = Selector('input.password')
const createArticle = Selector('a').withAttribute('href', '/article/create')
const metadataButton = Selector('button').child('i.rs-icon-newspaper-o')
const createButton = Selector('button').child('i.rs-icon-save')
const publishButton = Selector('button').child('i.rs-icon-cloud-upload')

const closeButton = Selector('.rs-drawer-footer').child('button.rs-btn-primary')
const confirmButton = Selector('.rs-modal-footer').child('button.rs-btn-primary')
const metaPreTitleInput = Selector('input.preTitle')
const metaTitleInput = Selector('input.title')
const metaLeadInput = Selector('textarea.lead')

const articleTitleInput = Selector('textarea').withAttribute('placeholder', 'Title')
const articleLeadInput = Selector('textarea').withAttribute('placeholder', 'Lead Text ')

const EDITOR_URL = 'https://editor.ftestingin.wepublish.dev'
const WEBSITE_URL = 'https://www.ftestingin.wepublish.dev'

// const EDITOR_URL = 'http://127.0.0.1:3000'
// const WEBSITE_URL = 'http://127.0.0.1:5000'

export default async function consoleOut() {
  const { error } = await t.getBrowserConsoleMessages();
  console.log('error', error)
  //await t.expect(error[0]).notOk();
}

const admin = Role(`${EDITOR_URL}/login`, async t => {
  console.log('body looks like:',await Selector('body').innerText)
  console.log('NEW LINE')
  await t
    .navigateTo(`${EDITOR_URL}/logout`)
    .typeText(loginName, 'dev@wepublish.ch')
    .typeText(loginPassword, '123')
    .click('form > button')
});

const getPath = ClientFunction(() => {
  return document.location.pathname
});

fixture `Create and publish an article`
  .disablePageCaching
  .beforeEach(async t => {
    await t.useRole(admin)
  })
  .page`${EDITOR_URL}`
  .afterEach(() => consoleOut())


let articleID = ''

test('Check Front site', async t => {
  await t
    .navigateTo(`${WEBSITE_URL}`)
    .expect(Selector('a').withAttribute('href', 'https://www.facebook.com/wepublish').getAttribute('target')).eql('_blank')
})


test('Create an article', async t => {
  await t.navigateTo(EDITOR_URL)

  await t
    .click(createArticle)

  await t
    .expect(await getPath()).contains('/article/create')

  await t
    .typeText(articleTitleInput, 'This is the article Title')
    .typeText(articleLeadInput, 'This is the article lead')
    .click(createButton);

  const path = await getPath()
  articleID = path.substr(path.lastIndexOf('/') + 1)
  console.log('articleID', articleID)
  await t.expect(path).contains('/article/edit')

  await t
    .click(metadataButton)
    .expect(metaTitleInput.value).contains('This is the article Title')
    .expect(metaLeadInput.value).contains('This is the article lead')
    .typeText(metaPreTitleInput, 'This is a Pre-title')
    .click(closeButton)

  /* await t
    .click(lastAddButton)
    .click(richTextButton)
    .typeText(richTextBox, 'This is some random text') */


});

test('Test Website', async t => {
    await t
      .navigateTo(`${WEBSITE_URL}/a/${articleID}`)
      .expect(Selector('h1').innerText).eql('404')
  })

test('Publish article', async t => {
  await t.navigateTo(EDITOR_URL).useRole(admin)

  await t
    .click(Selector('a').withAttribute('href',`/article/edit/${articleID}`))
    .click(publishButton)
    .click(confirmButton)
    .expect(Selector('div.rs-alert-container').exists).ok()
    .click(Selector('div.rs-alert-item-close'))

  await t
    .click(metadataButton)
    .click(Selector('button').child('i.rs-icon-magic'))
    .click(closeButton)
    .click(publishButton)
    .click(confirmButton)
    .expect(Selector('div.rs-tag-default').child('span.rs-tag-text').innerText).contains('Article published')
})

test('Test Website', async t => {
    const h1Title = Selector('h1')

    await t
      .navigateTo(`${WEBSITE_URL}/a/${articleID}`)
      .expect(h1Title.innerText).eql('This is the article Title')
  })
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

Run /opt/testcafe/docker/testcafe-docker.sh chromium:headless tests/e2e.ts --dev --assertion-timeout 10000
Editor URL https://editor.ftestingin.wepublish.dev
Website URL https://www.ftestingin.wepublish.dev
 Running tests in:
 - Chrome 93.0.4577.82 / Linux 0.0

 Create and publish an article
body looks like: Create and publish an article - Check Front site
Chrome 93.0.4577.82 / Linux 0.0
NEW LINE
 ✖ Check Front site

   1) - Error in Role initializer -
      The specified selector does not match any element in the DOM tree.

       > | Selector('input.username')

      Browser: Chrome 93.0.4577.82 / Linux 0.0

         51 |const admin = Role(`${EDITOR_URL}/login`, async t => {
         52 |  console.log('body looks like:',await
      Selector('body').innerText)
         53 |  console.log('NEW LINE')
         54 |  await t
         55 |    .navigateTo(`${EDITOR_URL}/logout`)
       > 56 |    .typeText(loginName, 'dev@wepublish.ch')
         57 |    .typeText(loginPassword, '123')
         58 |    .click('form > button')
         59 |});
         60 |
         61 |const getPath = ClientFunction(() => {

         at <anonymous> (/__w/wepublish/wepublish/tests/e2e.ts:56:6)
         at fulfilled (/__w/wepublish/wepublish/tests/e2e.ts:5:58)

 ✖ Create an article

   1) - Error in Role initializer -
      The specified selector does not match any element in the DOM tree.

       > | Selector('input.username')

      Browser: Chrome 93.0.4577.82 / Linux 0.0

         51 |const admin = Role(`${EDITOR_URL}/login`, async t => {
         52 |  console.log('body looks like:',await
      Selector('body').innerText)
         53 |  console.log('NEW LINE')
         54 |  await t
         55 |    .navigateTo(`${EDITOR_URL}/logout`)
       > 56 |    .typeText(loginName, 'dev@wepublish.ch')
         57 |    .typeText(loginPassword, '123')
         58 |    .click('form > button')
         59 |});
         60 |
         61 |const getPath = ClientFunction(() => {

         at <anonymous> (/__w/wepublish/wepublish/tests/e2e.ts:56:6)
         at fulfilled (/__w/wepublish/wepublish/tests/e2e.ts:5:58)

 ✖ Test Website

   1) - Error in Role initializer -
      The specified selector does not match any element in the DOM tree.

       > | Selector('input.username')

      Browser: Chrome 93.0.4577.82 / Linux 0.0

         51 |const admin = Role(`${EDITOR_URL}/login`, async t => {
         52 |  console.log('body looks like:',await
      Selector('body').innerText)
         53 |  console.log('NEW LINE')
         54 |  await t
         55 |    .navigateTo(`${EDITOR_URL}/logout`)
       > 56 |    .typeText(loginName, 'dev@wepublish.ch')
         57 |    .typeText(loginPassword, '123')
         58 |    .click('form > button')
         59 |});
         60 |
         61 |const getPath = ClientFunction(() => {

         at <anonymous> (/__w/wepublish/wepublish/tests/e2e.ts:56:6)
         at fulfilled (/__w/wepublish/wepublish/tests/e2e.ts:5:58)

 ✖ Publish article

   1) - Error in Role initializer -
      The specified selector does not match any element in the DOM tree.

       > | Selector('input.username')

      Browser: Chrome 93.0.4577.82 / Linux 0.0

         51 |const admin = Role(`${EDITOR_URL}/login`, async t => {
         52 |  console.log('body looks like:',await
      Selector('body').innerText)
         53 |  console.log('NEW LINE')
         54 |  await t
         55 |    .navigateTo(`${EDITOR_URL}/logout`)
       > 56 |    .typeText(loginName, 'dev@wepublish.ch')
         57 |    .typeText(loginPassword, '123')
         58 |    .click('form > button')
         59 |});
         60 |
         61 |const getPath = ClientFunction(() => {

         at <anonymous> (/__w/wepublish/wepublish/tests/e2e.ts:56:6)
         at fulfilled (/__w/wepublish/wepublish/tests/e2e.ts:5:58)

 ✖ Test Website

   1) - Error in Role initializer -
      The specified selector does not match any element in the DOM tree.

       > | Selector('input.username')

      Browser: Chrome 93.0.4577.82 / Linux 0.0

         51 |const admin = Role(`${EDITOR_URL}/login`, async t => {
         52 |  console.log('body looks like:',await
      Selector('body').innerText)
         53 |  console.log('NEW LINE')
         54 |  await t
         55 |    .navigateTo(`${EDITOR_URL}/logout`)
       > 56 |    .typeText(loginName, 'dev@wepublish.ch')
         57 |    .typeText(loginPassword, '123')
         58 |    .click('form > button')
         59 |});
         60 |
         61 |const getPath = ClientFunction(() => {

         at <anonymous> (/__w/wepublish/wepublish/tests/e2e.ts:56:6)
         at fulfilled (/__w/wepublish/wepublish/tests/e2e.ts:5:58)

 5/5 failed (25s)
```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. run the tests locally and it should work
2. run the tests on github actions and the should fail
 
### Your Environment details:
 
* testcafe version:                   the latest docker image testcafe/testcafe
* node.js version:                    the latest docker image testcafe/testcafe
* command-line arguments:  chromium:headless tests/e2e.ts --dev --assertion-timeout 10000
* browser name and version: Chrome 93.0.4577.82 / Linux 0.0
* platform and version:          github actions => ubuntu-latest
* other:

**Comment by pavsenin** [comment] 2021-11-01 12:11
Hello,
I tried to reproduce the issue from another region (not Chile because I have no VPN for Chile) with the same results as in my previous comment.
You have a complex environment, and it is hard to adjust it on my side.
Unfortunately, we cannot research and fix this issue without reproducing it.
I will close this issue for now. If you manage to create a simple example in which the problem is reproduced, please reopen the issue.

**Closed by pavsenin** 2021-11-01 12:11 UTC
Labels: STATE: Need response
