### ISSUE TITLE
Facebook button unreachable in testcafe

### ISSUE THREAD

**Issue by neilmatillano** [DevExpress/testcafe#1999] opened 2017-12-13 10:21 UTC
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
After entering facebook login details and pressing login, and then a continue as "Profile_Name" page will show and then another page to confirm allow app to access facebook details.
And the issue is that the button to confirm is in the bottom of the page, testcafe is not able to click confirm this button because of the hammerhead bar that is being overlayed.

<img width="657" alt="screen shot 2017-12-13 at 11 14 45" src="https://user-images.githubusercontent.com/4159492/33933984-d97529e4-dff7-11e7-9822-a501543968e0.png">

### What is the expected behavior?
testcafe should be able to click the button

### How would you reproduce the current behavior (if this is a bug)?
go to an app or site that uses facebook login and you have to register as first time user.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: mac os sierra v 10.13.1
* testcafe version: 0.18.6-dev20171211
* node.js version: v8.9.1

**Comment by LavrovArtem** [comment] 2017-12-13 15:06
Hi @neilmatillano,
As far as I understood, you are trying to log in to your site via a Facebook account. This authentication creates a new browser window for its own purposes. Unfortunately, we do not support testing in multiple browser windows. 
This issue is a duplicate of https://github.com/DevExpress/testcafe/issues/912.

**Closed by LavrovArtem** 2017-12-13 15:06 UTC

**Comment by LavrovArtem** [comment] 2017-12-14 09:19
Hi @neilmatillano,
With TestCafe, page just loads a new window URL into the current tab instead of opening a new browser window. Unfortunately, the Facebook authentication works only with multiple windows. For example, without Testcafe, try to click the `LOG IN WITH FACEBOOK` button and close the tab with your site. In the new authentication window, you will encounter the same problems.

**Comment by neilmatillano** [comment] 2017-12-15 15:14
@LavrovArtem : Noted on this , do you have a timeline for this fix? Thanks!

**Comment by LavrovArtem** [comment] 2017-12-18 07:30
@neilmatillano 
This is in our plans for the next releases but not we can't provide you with estimates. We let you know when we have any results.

**Comment by neilmatillano** [comment] 2017-12-18 08:45
@LavrovArtem : thanks for the reply. But is there a workaround I can do? Like remember my login in facebook prior to running the tests so I can just go directly to the main page? With or withour logging in?

**Comment by LavrovArtem** [comment] 2017-12-20 13:08
Hi @neilmatillano,
I've tried to find a workaround but it didn’t exist. The result of searching is https://github.com/DevExpress/testcafe-hammerhead/issues/1428.
