### ISSUE TITLE
Test execution randomly aborted by an issue originated in the request-pipeline of Hammerhead

### ISSUE THREAD

**Issue by raven-rwho** [DevExpress/testcafe#6734] opened 2021-11-26 13:51 UTC
### What is your Scenario?

We are running a quite comprehensive testsuite (some hunderds of test) with the goal to make sure that our tracking implemantation works as expected. We are executing this tests via CI 4x a day. Since a few weeks we have random test aborts, which are unfortunately extremely hard to track and reproduce.

### What is the Current behavior?

`Errors: Unhandled promise rejection:

Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed 

at new NodeError (node:internal/errors:371:5) 

at ClientHttp2Session.request (node:internal/http2/core:1702:13)
 at DestinationRequest._sendRealThroughHttp2 (/home/ec2-user/actions-runner/_work/ds_cerberus/ds_cerberus/node_modules/testcafe-hammerhead/lib/request-pipeline/destination-request/index.js:51:32)
 at DestinationRequest._send (/home/ec2-user/actions-runner/_work/ds_cerberus/ds_cerberus/node_modules/testcafe-hammerhead/lib/request-pipeline/destination-request/index.js:110:18)
 at runMicrotasks (<anonymous>:null:null) 

at processTicksAndRejections (node:internal/process/task_queues:96:5)`

This is the stacktrace if the tests are aborted. Unfortunately this means that the execution of all tests is aborted and does not only affect a single test, which renders the whole suite for us pretty useless...

### What is the Expected behavior?

Ideally there should no 

### What is your public website URL? (or attach your complete example)

unfortunately there is nothing that I could share, because this is a private product

> 

> 

### What is your TestCafe test code?

unfortunately there is nothing that I could share, because this is a private product

### Steps to Reproduce

There seems to be more aborts if the tests are executed in the suite and not solely - but even there it is quite hard to identify a pattern.

### TestCafe version

"testcafe": "^1.17.1",

### Node.js version

node-version: '16.x'

### Command-line arguments

testcafe --config-file .testcaferc-dev.json tests

**Comment by pavsenin** [comment] 2021-11-29 08:15
Hello,

The issue may be related to HTTP/2 requests. So, you can disable it using the following option: [disableHttp2](https://testcafe.io/documentation/402638/reference/configuration-file#disablehttp2). Check if the issue is reproduced after that.

You can also try to increase timeouts, e.g. [ajaxRequestTimeout](https://testcafe.io/documentation/402638/reference/configuration-file#ajaxrequesttimeout) and [testExecutionTimeout](https://testcafe.io/documentation/402638/reference/configuration-file#testexecutiontimeout).

If this does not help, please create a simple project where the issue is reproducible and share it here. We will research it on our side.

**Comment by raven-rwho** [comment] 2021-11-29 08:25
We will try it and let you know - thanks!

**Comment by qrush** [comment] 2021-12-20 20:35
@raven-rwho did any of those configuration values help? We are starting to see the same issue in GitHub Actions. 

```
   1) Uncaught exception:

      Error: The session has been destroyed
      at new NodeError (node:internal/errors:371:5)
      at ClientHttp2Session.ping (node:internal/http2/core:1342:13)
      at ClientHttp2Session.<anonymous>

   (/home/runner/work/../node_modules/testcafe-hammerhead/lib/request-pipeline/destination-request/http2.js:52:21)
      at Object.onceWrapper (node:events:510:26)
      at ClientHttp2Session.emit (node:events:390:28)
      at ClientHttp2Session.emit (node:domain:475:12)
      at emit (node:internal/http2/core:328:3)
      at processTicksAndRejections
      (node:internal/process/task_queues:85:21)

      Browser: Chrome 96.0.4664.110 / Linux 0.0
```

**Comment by pavsenin** [comment] 2021-12-23 07:33
@qrush,
Could you clarify if you tried the suggestions described above with http2 and timeouts?
If you did, could you share your results here?

**Comment by raven-rwho** [comment] 2021-12-23 08:01
Hi - sorry for the late response. Yes we disabled the http2 flag and indeed this improved the situation. Since then we don't have interruptions anymore. 
I need to ask the responsible developer if there was more changes, but I'll need until beginning of January for it.

**Comment by qrush** [comment] 2021-12-23 14:18
@pavsenin We've tried the suggestion with the `disableHttp2` flag. We had a few timeouts in place already.

Here's the main config we use for our main TestCafé suite on GitHub Actions in case this helps future readers of this thread. We run in a [matrix strategy](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) with ~7 independent jobs and recently limited that to [`max-parallel: 3`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) to reduce some load on our servers.

```json
{
  "browsers": "chrome:headless:emulation:width=1024;height=768",
  "concurrency": 4,
  "disableHttp2": true,
  "assertionTimeout": 6000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 20000,
  "quarantineMode": {
    "successThreshold": 1,
    "attemptLimit": 3
  },
  "reporter": [
    {
      "name": "spec"
    },
    {
      "name": "json",
      "output": "testcafe/output/results/report.json"
    },
    {
      "name": "xunit",
      "output": "testcafe/output/results/report.xml"
    }
  ],
  "screenshots": {
    "path": "testcafe/output/screenshots",
    "pathPattern": "${FIXTURE}/${TEST_INDEX}/${FILE_INDEX}.png",
    "takeOnFails": true
  },
  "videoPath": "testcafe/output/videos",
  "videoOptions": {
    "singleFile": false,
    "failedOnly": true,
    "pathPattern": "${FIXTURE}/${TEST}_${FILE_INDEX}.mp4"
  }
}
```

**Comment by pavsenin** [comment] 2021-12-29 10:49
Hello @qrush and @raven-rwho,

If I understand it correctly, the disableHttp2 option helps eliminate the issue, so I will close it.
You can reopen it if you have any additional information.

**Closed by pavsenin** 2021-12-29 10:49 UTC
Labels: STATE: Need response
