### ISSUE TITLE
Is there any way to add some kind of @Tags in testcafe tests, and we can use these tags to run different combination of tests. it will help in maintain different suite 

### ISSUE THREAD

**Issue by vivekpant28** [DevExpress/testcafe#2806] opened 2018-09-03 17:02 UTC
### Are you requesting a feature or reporting a bug?
Feature

### What is the expected behavior?
some kind of tags can be added in test meta section, which can categories test while creating , later we can use these tags to run different combination of tests, like smoke, regression etc.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment] 2018-09-03 17:04
Hi @vivekpant28, currently TestCafe doesn't have such feature, but there is a feature request for it: https://github.com/DevExpress/testcafe/issues/2527. So I close this issue as a duplicate of https://github.com/DevExpress/testcafe/issues/2527.

**Closed by AndreyBelym** 2018-09-03 17:04 UTC
