### ISSUE TITLE
Incorrect callsite line in error report on node v0.10.41

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#599] opened 2016-06-16 11:08 UTC
If we try to run this test on node v0.10.41 and on any stable version (i had node v5.7.0), we will get error reports with different callsite lines.
```js
fixture `Test`
    .page `http://example.com`;

test('test', async t => {
    await t
        .navigateTo('http://example.com')
        .click('#btn');

    const actual = true;
});
```

[node v0.10.41](http://screencast.com/t/SZmMMPrB2Kv) - line 9
[node v5.7.0](http://screencast.com/t/P8suNx2rIwW)   - line 7

If run this test, error reports will be same.

```js
fixture `Test`
    .page `http://example.com`;

test('test', async t => {
    await t
        .navigateTo('http://example.com')
        .click('#btn');
});
```
[node v0.10.41](http://screencast.com/t/92lp85Irbg) - line 7
[node v5.7.0](http://screencast.com/t/ktee0soe0e)   - line 7

I started investigation and found, that compiled code on node v0.10.41 after defining `actual` const variable changes next way:
node v0.10 from [this](https://gist.github.com/georgiy-abbasov/020a158d6aec100d21fdcbb7e531c915) to [this](https://gist.github.com/georgiy-abbasov/3ea0574e5fa9f3bbd05c2908b1e220b3)
node v5.7.0 from [this](https://gist.github.com/georgiy-abbasov/b926261b734b92d3148ee7af5b283e0b) to [this](https://gist.github.com/georgiy-abbasov/1d0036d4a41a183b77a0460073fff084)

As we can see, in node v5.7.0 changes are minimal

**Comment by inikulin** [comment] 2016-06-16 11:34
The problem is that `source-map-support` package can't produce correct callsites for the compiled code. Here is what we can do:

- [ ] First of all create **server** regression test to check that our changes works

### The good
- [ ] Try update Babel
- [ ] Try update `source-map-support`
- [ ] Submit bug to babel and/or `source-map-support`
- [ ] Try disable `retainLines` but we will have issue with `use strict` which added by Babel (may be fixed by Babel update)
     - [ ] Try to workaround `use strict` by testing original source and removing if it was not present in original file
     - [ ] Submit bug to Babel

### The bad
- [ ] Declare support only for Node 4+

### The ugly
- [ ] Disable callsite rendering for Node 10 (keep only stacks) or render frames without actual line pointer. Add this to known issues.

**Comment by georgiy-abbasov** [comment] 2016-06-17 10:54
I've opened task with this issue on the Babel tracker
https://phabricator.babeljs.io/T7436

**Comment by georgiy-abbasov** [comment] 2016-06-22 15:04
I've opened PR with workaround to discuss this problem in Babel repository.
https://github.com/babel/babel/pull/3545

**Closed** 2016-07-27 09:24 UTC
Labels: !IMPORTANT!, AREA: server, SYSTEM: reporting, TYPE: bug
