### ISSUE TITLE
Unable to locate elements with aws-amplify library

### ISSUE THREAD

**Issue by automation9006** [DevExpress/testcafe#5580] opened 2020-09-24 10:23 UTC
### What is your Test Scenario?
Trying to identify elements and execute a test case.
 
### What is the current behavior?
 testcafe unable to identify the elements.
 
### What is the Expected behavior?
testcafe should identify the elements.
 
### What is your web application and your TestCafe test code?
It's a react app for UI our dev team has used the aws-amplify library to auto-generate the code for ids etc.

https://aws-amplify.github.io/amplify-js/api/#aws-amplify-is-a-javascript-library-for-frontend-and-mobile-developers-building-cloud-enabled-applications
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
N/A

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
test.(`Home Page validations`, async t =>{
    await t
    .typeText(Selector('#username'),'testadmin')
    .typeText(Selector('#password'),'password123')
    .click(Selector('button.button'))
})
```

</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Home Page Tests
 × Home Page validations

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('#username')

      Browser: Chrome 85.0.4183.102 / Windows 10

         12 |
         13 |})
         14 |
         15 |test.only(`Home Page validations`, async t =>{
         16 |    await t
       > 17 |    .typeText(Selector('#username'),'testadmin')
         18 |    .typeText(Selector('#password'),'password123')
         19 |    .click(Selector('button.button'))
         20 |})
         21 |
         22 |test('Page should load and display the "sign in" button',
      async t => {

         at <anonymous>

```

</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/17795630/94132802-b7f33280-fe57-11ea-9c14-b2c596becb71.png)

</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:       6.14.4            
* node.js version:        12.16.3            
* command-line arguments:  npm run testcafe chrome tenv=qaEnv tests/ 
* browser name and version:  chrome latest 
* platform and version:     win 10     
* other:

**Comment by arubtsov** [comment] 2020-09-25 07:45
Hello @automation9006,

As I can see from the screenshot, the element you need to select is inside shadow DOM, so I will close this issue as a duplicate of this [feature request](https://github.com/DevExpress/testcafe/issues/2172). Please refer to it to find examples of how such elements can be selected.

**Closed by arubtsov** 2020-09-25 07:45 UTC
Labels: STATE: Need response
