### ISSUE TITLE
Opening new tab gets `Uncaght Error: Cannot send to a closed connection`

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#2610] opened 2018-07-09 19:40 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Our app has widgets, that when clicked, open the widget in an editor in a new tab/window. When performing this action in Testcafe, the app throws an `Uncaught Error: Cannot send to a closed connection`. It looks like sharejs is trying to access a connection that perhaps Testcafe closes, due to how y'all handle multiple tabs? 

I'm mostly curious if y'all have seen anything like this, and if there's a workaround? 

### What is the expected behavior?
Shouldn't crash :) This works fine manually and using Protractor/webdriver. 

### Specify your

* operating system: mac
* testcafe version: latest
* node.js version: latest lts

**Comment by AndreyBelym** [comment] 2018-07-09 21:34
Hello @qualityshepherd, unfortunaly you can't test a site if it opens additional tabs/windows. You can subscribe to the issue https://github.com/DevExpress/testcafe/issues/912 for getting notifications about this feature. So I close this issue because it's a duplicate of #912.

**Closed by AndreyBelym** 2018-07-09 21:34 UTC
