### ISSUE TITLE
Not able to redirect to login page the page gets freezed

### ISSUE THREAD

**Issue by arvindarun** [DevExpress/testcafe#6743] opened 2021-11-30 17:42 UTC
### What is your Scenario?

On opening the URL in ie it page is getting freeze. The error message is been shown in the console.

### What is the Current behavior?

On opening the URL page is getting freeze

### What is the Expected behavior?

Should redirect to the proper page

### What is your public website URL? (or attach your complete example)

Not able to get an open example

### What is your TestCafe test code?

Not able to get an open example

### Screenshots

![image](https://user-images.githubusercontent.com/54062330/144099718-011ee965-cb27-4b4c-bce3-27135a90e79b.png)

### Steps to Reproduce

1. Initialize URL inside .page() method
2.Run the test with IE browser

### TestCafe version

1.17.2-alpha.2

### Command-line arguments

npx testcafe ie src/tests --skip-js-errors

**Comment by Farfurix** [comment] 2021-12-01 12:37
@arvindarun 

Hello,

We cannot find the cause of this behavior without a reproducible example. So I'll close this issue. Feel free to share a [reproducible example](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue) here or in a new bug report.

**Closed** 2021-12-01 12:37 UTC
Labels: TYPE: bug
