### ISSUE TITLE
Navigating back in history throws error in Safari

### ISSUE THREAD

**Issue by Nikolaj1010** [DevExpress/testcafe#5260] opened 2020-06-29 13:52 UTC
### What is your Test Scenario?
Using Client Function goBack = ClientFunction(() => window.history.back()); breaks the DOM queries in Safari. I am using the same code as in the issue which was already reported (https://github.com/DevExpress/testcafe/issues/4395) but it is closed now.
 
### What is the Current behavior?
1) TypeError: Cannot read property '0' of null

      Browser: Safari 13.1.1 / Mac OS X 10.15.5

         491 |    const element = Selector('#developer-name');
         492 |    await t.navigateTo(`http://google.com`)
         493 |
         494 |    await ToolkitHelper.goBack();
         495 |
       > 496 |    await t.expect(element.exists).ok();
         497 |});
         498 |
 
### What is the Expected behavior?
It should work even after navigating in history.
 
### Steps to Reproduce:
```
fixture`History testing`
    .page(`https://devexpress.github.io/testcafe/example/`)

test.('Should navigate forth and back and check element', async t => {
    const element = Selector('#developer-name');
    const goBack = ClientFunction(() => window.history.back());
    await t.navigateTo(`http://google.com`)
   
    await goBack();

    await t.expect(element.exists).ok();
});
```

### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                    13.7.1
* command-line arguments:  testcafe remote --qr-code
* browser name and version: Safari 13.1.1
* platform and version:          macOS 10.15.5

**Comment by Ogurecher** [comment] 2020-06-30 12:56
Hello,
 
Thank you for your report. I've managed to reproduce the issue on macOS 10.15.4 with TestCafe 1.8.7 and Safari 13.1.
Our team will investigate this issue and let you know once it's fixed.

**Comment by HabaneroSalsa** [comment] 2021-04-29 22:27
I am encountering the same problem with TestCafe v1.14.0
Will this issue be addressed any time soon?

**Comment by lerhum** [comment] 2022-10-05 05:39
fwi I experience the same error on 2.0.0

**Comment by miherlosev** [comment] 2023-05-31 06:36
Duplicate of https://github.com/DevExpress/testcafe/issues/7707

**Closed by miherlosev** 2023-05-31 06:36 UTC
Labels: TYPE: bug, AREA: client, FREQUENCY: level 2
