### ISSUE TITLE
Show different error messages for ECONNRESET and ENOTFOUND

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1606] opened 2017-07-11 11:13 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
We show the following error text even for an ECONNRESET error:
```
 Failed to find a DNS-record for the resource at
```
which is wrong and misleading, because ECONNRESET means 'DNS was resolved, but connection failed'.

### What is the expected behavior?
Show a descriptive error message for ECONNRESET. E.g.
```
Failed to connect to the server at
```

### Specify your

* testcafe version: 0.17.0-alpha2

**Comment by moffsugita** [comment] 2018-10-15 06:53
```
yarn --version
1.5.1
```
`Failed to find a DNS-record for the resource at "http://localhost:3000/favicon.ico".`

**Comment by miherlosev** [comment] 2018-10-15 11:30
@moffsugita 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by yegorski** [comment] 2019-04-15 16:04
Sorry in advance for not providing details on my issue but my question is rather generic: is there a way to specify a timeout when TestCafe encounters `ECONNRESET`?

We're seeing TestCafe hang for around 10 minutes. What I can see is that our app routes the TestCafe request into an infinite redirect loop. I can reproduce the fault with our app in a browser and with curl:

```bash
curl -I https://<server_ip>

HTTP/1.1 302 Found
...
location /login?next=%2F
...
```

Is there a way to kill the test run if such a redirect condition occurs? Or is there a timeout? Timeouts grabbed from the documentation don't seem to work for this use case. The command this happens on:

```bash
testcafe "chromium --headless --no-sandbox --ignore-certificate-errors" --selector-timeout 1000 --assertion-timeout 1000 --page-load-timeout 1000 *.js
```

**Comment by AlexKamaev** [comment] 2019-04-16 11:15
@yegorski 
According to your description I guess you found an issue with request processing. It's a very complex part of TestCafe and generally it's difficult to say something definite without an example that reproduces the issue. At present, you cannot specify the timeout for 'ECONNRESET'. Try using the quarantine mode to fix the problem. If it does not help you, then please provide us a full example demonstrating the issue (application, test code, command line arguments).

**Comment by yegorski** [comment] 2019-04-16 15:44
Quarantine mode sounds great, I like having the retry logic built-in like that. That's what I'll do since the test suite that interacts with this app behaves differently on each run (sometimes it fails right away, other times it never responds). But the burden of fixing this behavior is on the app, not the test suite.

**Comment by AlexKamaev** [comment] 2019-04-16 15:59
Of course, the issue should be fixed. I recommend you using the quarantine mode only as a workaround.
However, to fix the issue we need to have full information about it, that's why I asked you to provide a full example. Without having such an example, we cannot examine the issue to find a precise solution. See if you can provide one. Thank you in advance.

**Comment by yegorski** [comment] 2019-04-17 20:18
Understood.

Sadly reproducibility is not easy in this case. The infinite redirect issue that I experienced involves standing up an app that we at https://www.enigma.com wrote which implements SSO using https://github.com/cloudfoundry/uaa. Some misconfiguration in the App -> UAA -> LDAP -> Nginx -> App flow cause the auth request to redirect, causing TestCafe to hang when loading the app's URL.

**Comment by AlexKamaev** [comment] 2023-08-04 12:44
We decided to close the issue since we do not have an example that reproduces the issue persistently. Moreover, TestCafe now uses new [Native Automation approach](%5Bhttps://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode%5D(https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode)). This possibly fixes the initial issue. If you still encounter this issue in NA mode or NA mode does not meet your requirements, please create a new issue, share a reproducible example, and describe your use case.

**Closed by AlexKamaev** 2023-08-04 12:44 UTC
Labels: TYPE: enhancement, SYSTEM: runner, AREA: server, FREQUENCY: level 1
