### ISSUE TITLE
Launching angular 4 application using TestCafe raises an exception, 'Error: Uncaught (in promise): TypeError: e.toString is not a function'.

### ISSUE THREAD

**Issue by NaukhaizAhmad** [DevExpress/testcafe#1560] opened 2017-06-23 11:14 UTC
### Are you requesting a feature or reporting a bug?

seems to be an issue.

### What is the current behavior?

client/application isn't launching, if opened through the TestCafe (recorder).
blank screen would be displayed with exceptions i.e. Unhandled Promise rejection: e.toString is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: e.toString is not a function.

browser console + screen shot attached.

[ss01-nbk-035-1498214131834.txt](https://github.com/DevExpress/testcafe/files/1097521/ss01-nbk-035-1498214131834.txt)
![image 50](https://user-images.githubusercontent.com/29655292/27478757-7aec6dba-582a-11e7-9bcd-b976e279390d.png)

**Comment by miherlosev** [comment] 2017-06-23 14:27
Hi NaukhaizAhmad,
I tried to open the Angular 4 sample app - 'Tour of Heroes' (https://angular.io/tutorial) with the recorder, and it all works fine for me.
Please see this video - https://www.screencast.com/t/HqakqCOnpr.
TestCafe version - 15.1.3
Angular version - 4.2.4.

Could you specify versions of TestCafe and Angular you are using?
In addition, provide a simple example to illustrate the issue or share your app with me.

**Comment by NaukhaizAhmad** [comment] 2017-07-03 06:06
Hi @miherlosev,
Thanks for your prompt response.

**Required information:**
TestCafe version - 15.1.3
Angular version - 4.1.2

**Additional informtaion**
I have attached a file containing "dependencies" and "devDependencies" , also attached yarn.lock file.
please find the attached files.
I hope you might be able to debug/investigate/reproduce this issue now.
Please let me know in case you need further information. Your prompt response would be highly appreciated.

[TestCafeIssue.zip](https://github.com/DevExpress/testcafe/files/1118522/TestCafeIssue.zip)

**Comment by miherlosev** [comment] 2017-07-03 09:57
Unfortunately, I cannot reproduce the issue using your attachments.
I need a simple example that I could run on my side.

**Comment by NaukhaizAhmad** [comment] 2017-07-13 10:45
Thanks for your response. 
Attached is the link for sample application as per your requirement, please find the link below.
I hope you might be able to reproduce this issue now.
Please let me know in case you need further information. Your prompt response would be highly appreciated.

https://drive.google.com/file/d/0B4BaQZP8yhWNcER1OTB0bDhGTlE/view?usp=sharing

**Comment by MarinaRukavitsyna** [comment] 2017-07-14 11:56
Hi @NaukhaizAhmad,
 
From what I gather, you are using a paid TestCafe version while this github resource is intended for an open source version. We provide support for paid versions here: https://www.devexpress.com/Support/Center/Search/List/1
So, I have created a new CS report where we provided a hot fix for this issue: 

https://www.devexpress.com/Support/Center/Question/Details/T535831/launching-angular-4-application-using-testcafe-raises-the-error-uncaught-in-promise

Please also take a look at the following thread that describes the difference between paid and open-source versions:
 
https://testcafe-discuss.devexpress.com/t/what-is-the-difference-between-the-open-source-version-and-the-paid-version-of-the-testcafe/253/4

**Closed** 2017-07-14 13:18 UTC
Labels: SYSTEM: hammerhead, To be reproduced, TYPE: bug
