### ISSUE TITLE
TestCafé hangs when PayPal button is pressed 

### ISSUE THREAD

**Issue by thomas-qa** [DevExpress/testcafe#5962] opened 2021-02-16 16:54 UTC
### What is your Test Scenario?
On our [web app](https://www.musement.com/us/), we want to select the PayPal payment method and click the PayPal button. 
Performing the test manually, what happens is that when the PayPal button is pressed a new tab opens where to enter the PayPal data and proceed to payment.
 
### What is the Current behavior?
- The new tab is not opened
- Testcafé hangs
 
### What is the Expected behavior?
- Open a new tab on paypal.com
- Testcafé makes the test pass (or fail) and does not hang
 
### What is your web application and your TestCafe test code?
You can find our public repo here:
https://github.com/musement/qa-test-cafe/tree/issue_paypal_payment
The issue is available in the `issue_paypal_payment`branch!
 
The test that generates this error is 
https://github.com/musement/qa-test-cafe/blob/issue_paypal_payment/tests/paypal_issue/fixtures/pay_with_paypal.js

### Your Environment details:
 
* testcafe version:                   `1.11.0` (reproduced also on `1.10.0` and `1.9.0` and `1.8.3`)
* node.js version:                    `12.0.0`
* command-line arguments:  `--domain=paypal_issue --is-browser-stack=false --headless=false`
* browser name and version:  Firefox `85.0` / Chrome `88.0.4324.150`
* platform and version:           macOS `10.15.7`
* other:                                    The project is a containerized version of TestCafé 

### To run the test outside the Docker container

Clone the  [repo](https://github.com/musement/qa-test-cafe/tree/issue_paypal_payment) and with a `bash` shell execute the following:
```shell
npm install
TEST_CAFE_BROWSERS_LIST=chrome,firefox
export TEST_CAFE_BROWSERS_LIST
TEST_CAFE_SPEED=1
export TEST_CAFE_SPEED
TEST_CAFE_REPORTER=list
export TEST_CAFE_REPORTER
TEST_CAFE_SKIPJSERRORS=true
export TEST_CAFE_SKIPJSERRORS
node index.js --domain=paypal_issue --is-browser-stack=false --headless=false
```

**Comment by felis2803** [comment] 2021-02-18 07:34
We reproduced the issue. Unfortunately, at the moment we cannot offer a complete solution. However, you can run the project by changing the `--headless` value from `false` to `true`.
We will let you know if we find a better solution.

**Comment by thomas-qa** [comment] 2021-02-19 08:24
@felis2803 I need to complete the payment, do you have any suggestions on how to write the rest of the test?
Also i wanted to know if you have any idea how long it may take to fix this bug. 
Thanks!

**Comment by felis2803** [comment] 2021-02-19 09:51
The problem is caused because Chrome cannot open new windows since it's restricted by default. TestCafe runs local browsers with a custom profile. It allows you to avoid the restriction with opening new windows. The 'Pay Pal' website requires the multi-window mode that is not allowed for the 'remote' browser. The recommended solution is to run your tests in local browsers.

I run your tests with the `testcafe chrome tests\paypal_issue\fixtures\pay_with_paypal.js` command, and everything works correctly.

Also, since we cannot fix this behavior due to the features of the 'remote' browser, I will close this issue.

**Closed by felis2803** 2021-02-19 09:51 UTC
Labels: STATE: Need response, TYPE: bug
