### ISSUE TITLE
Testcafe fails to load page

### ISSUE THREAD

**Issue by mariyanbitsov-af** [DevExpress/testcafe#7807] opened 2023-06-15 13:30 UTC
### What is your Scenario?

Hi, we are currently using testcafe for our end-to-end tests that we run on Jira cloud instances.

We have a Jira Cloud app and we use Testcafe for its end-to-end tests. Until recently there were no problems, but a couple of days ago it started having problems rendering Jira's issue view page correctly on some cloud instances.

Recently, testcafe started to cause an exception when loading the page where we want to test. The exception states that it cannot run querrySelectorAll on 'Document'. This happens when the page is opened (on navigateTo() method).

`DOMException: SyntaxError: Failed to execute 'querySelectorAll' on 'Document':`

We've tried upgrading the testcafe version. running it in native automation mode, but nothing worked.

### What is the Current behavior?

When navigating to a page, testcafe throws an exception and removes almost all elements from the Dom tree

### What is the Expected behavior?

Navigating to a page without throwing an exception. 

### What is your public website URL? (or attach your complete example)

https://botron-dev-imc-5.atlassian.net/browse/TP-1

### What is your TestCafe test code?

test('Reproduce test', async (t) => {
  await t.navigateTo(`https://botron-dev-imc-5.atlassian.net/browse/TP-1`);
  const summaryOfIssue = await Selector(`h1`).innerText;
  await t.expect(summaryOfIssue).eql('Simple story');
});

### Your complete configuration file

{
  "screenshots": {
    "takeOnFails": true,
    "path": "artifacts/screenshots",
    "pathPattern": "${DATE}_${TIME}/${TEST_ID}/${FIXTURE}_${TEST}_${RUN_ID}.png",
    "fullPage": true
  },
  "skipJsErrors": true,
  "browsers": ["firefox"],
  "clientScripts": ["./tests/setup/mocks/AP.js"],
  "assertionTimeout": 4000,
  // allows longer default assertions, needed for loading states when there is content but it is not correct
  "compilerOptions": {
    "typescript": {
      "configPath": "./testcafe_tsconfig.json"
    }
  },
  "quarantineMode": {
    "successThreshold": 1,
    "attemptLimit": 5
  }
}

### Your complete test report

There is nothing, since everything disappears

### Screenshots

Video with the test failing: https://streamable.com/n8if06

### Steps to Reproduce

Run the code block I attached.

you can open the URL without testcafe and assert that everything is working correctly and is visible.

### TestCafe version

2.4.0

### Node.js version

16.9.0

### Command-line arguments

chrome

### Browser name(s) and version(s)

Chrome 114.0.0.0

### Platform(s) and version(s)

mac OS 10.15.7

### Other

This happens only when testcafe runs, if you open the page in the browser there is no problem.

Also on some other Jira cloud instances, this problem is not present yet. Maybe something on the jira cloud html Dom elements causes testcafe to throw an error, just a thought 🤷

**Comment by AlexKamaev** [comment] 2023-06-19 07:33
Thank you for reaching out to us. I reproduced the issue. We'll research it and update the thread once we have news to share.

**Comment by mariyanbitsov-af** [comment] 2023-06-19 13:45
Hi, we did some investigating on our own

And this is the line in hammerhead.js that breaks the test:
`var elementsWithTarget = nativeMethods.querySelectorAll.call(this.document, "*[target=\"".concat(escapedIframeName, "\"]")); on line 17351
`

And this is the escpaedIframeName: `"{\"extension_id\":\"com.botronsoft.jira.issuematrix__view-issue-lists-5249574024409749412__192cbc4e\",\"api\":{\"_globals\":{\"request\":{\"args\":[\"t\",\"n\"],\"returnsPromise\":false}},\"messages\":{\"clear\":{\"args\":[\"e\"],\"returnsPromise\":false},\"onClose\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"generic\":{\"constructor\":{\"args\":[\"t\",\"n\",\"o\",\"i\"],\"returnsPromise\":false}},\"error\":{\"constructor\":{\"args\":[\"t\",\"n\",\"o\",\"i\"],\"returnsPromise\":false}},\"warning\":{\"constructor\":{\"args\":[\"t\",\"n\",\"o\",\"i\"],\"returnsPromise\":false}},\"success\":{\"constructor\":{\"args\":[\"t\",\"n\",\"o\",\"i\"],\"returnsPromise\":false}},\"info\":{\"constructor\":{\"args\":[\"t\",\"n\",\"o\",\"i\"],\"returnsPromise\":false}},\"hint\":{\"constructor\":{\"args\":[\"t\",\"n\",\"o\",\"i\"],\"returnsPromise\":false}}},\"flag\":{\"create\":{\"constructor\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"close\":{\"args\":[],\"returnsPromise\":false}}},\"dialog\":{\"create\":{\"constructor\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false}},\"close\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"getCustomData\":{\"args\":[\"e\"],\"returnsPromise\":false},\"getButton\":{\"constructor\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"enable\":{\"args\":[],\"returnsPromise\":false},\"disable\":{\"args\":[],\"returnsPromise\":false},\"toggle\":{\"args\":[],\"returnsPromise\":false},\"isEnabled\":{\"args\":[\"e\"],\"returnsPromise\":false},\"trigger\":{\"args\":[\"e\"],\"returnsPromise\":false},\"hide\":{\"args\":[],\"returnsPromise\":false},\"show\":{\"args\":[],\"returnsPromise\":false},\"isHidden\":{\"args\":[\"e\"],\"returnsPromise\":false}},\"createButton\":{\"constructor\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false}}},\"inlineDialog\":{\"hide\":{\"args\":[\"e\"],\"returnsPromise\":false}},\"env\":{\"getLocation\":{\"args\":[\"e\"],\"returnsPromise\":false},\"resize\":{\"args\":[\"e\",\"t\",\"n\"],\"returnsPromise\":false},\"sizeToParent\":{\"args\":[],\"returnsPromise\":false},\"hideFooter\":{\"args\":[\"e\"],\"returnsPromise\":false}},\"events\":{\"emit\":{\"args\":[\"e\"],\"returnsPromise\":false},\"emitPublic\":{\"args\":[\"e\"],\"returnsPromise\":false},\"emitToDataProvider\":{\"args\":[],\"returnsPromise\":false}},\"_analytics\":{\"trackDeprecatedMethodUsed\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"trackIframePerformanceMetrics\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false}},\"scrollPosition\":{\"getPosition\":{\"args\":[\"e\"],\"returnsPromise\":false},\"setVerticalPosition\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false}},\"dropdown\":{\"create\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"showAt\":{\"args\":[\"e\",\"t\",\"n\",\"o\"],\"returnsPromise\":false},\"hide\":{\"args\":[\"e\"],\"returnsPromise\":false},\"itemDisable\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"itemEnable\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false}},\"host\":{\"focus\":{\"args\":[],\"returnsPromise\":false},\"getSelectedText\":{\"args\":[],\"returnsPromise\":false}},\"theming\":{\"initializeTheming\":{\"args\":[],\"returnsPromise\":false}},\"cookie\":{\"save\":{\"args\":[\"e\",\"t\",\"n\"],\"returnsPromise\":false},\"read\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"erase\":{\"args\":[\"e\"],\"returnsPromise\":false}},\"history\":{\"_registerWindowListeners\":{\"args\":[],\"returnsPromise\":false},\"back\":{\"args\":[\"e\"],\"returnsPromise\":false},\"forward\":{\"args\":[\"e\"],\"returnsPromise\":false},\"go\":{\"args\":[\"e\"],\"returnsPromise\":false},\"getState\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"pushState\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false},\"replaceState\":{\"args\":[\"e\",\"t\"],\"returnsPromise\":false}},\"navigator\":{\"_shouldThrottle\":{\"args\":[\"(window.localStorage.getItem(\\"lastReloadTimestamp\\"\"],\"returnsPromise\":false},\"go\":{\"args\":[\"(\"],\"returnsPromise\":false},\"reload\":{\"args\":[\"(12e4\",\"5\"],\"returnsPromise\":false}},\"user\":{\"getCurrentUser\":{\"args\":[\"{atlassianAccountId:Object(o(\\"ZyuQ\\"\"],\"returnsPromise\":false},\"getLocale\":{\"args\":[\"Object(o(\\"ZyuQ\\"\"],\"returnsPromise\":false},\"getTimeZone\":{\"args\":[\"e._context.extension.options.user.timeZone\"],\"returnsPromise\":false},\"getUser\":{\"args\":[\"{fullName:void\",\"0===t.uid&&void\",\"0===t.ukey?null:Object(o(\\"ZyuQ\\"\"],\"returnsPromise\":false}},\"context\":{\"getToken\":{\"args\":[\"(n\",\"o\"],\"returnsPromise\":true},\"getContext\":{\"args\":[\"(n\",\"o\"],\"returnsPromise\":true}},\"jira\":{\"refreshIssuePage\":{\"args\":[\"(\\"legacy_refreshIssuePage\\"\"],\"returnsPromise\":false},\"updateIssueGlance\":{\"args\":[\"(\\"legacy_updateIssueGlance\\"\",\"{detail:[null\",\"{addonKey:t._context.extension.addon_key\",\"moduleKey:t._context.extension.key\",\"data:e}]}\"],\"returnsPromise\":false},\"getWorkflowConfiguration\":{\"args\":[\"\\"function\\"!=typeof\",\"e\"],\"returnsPromise\":false},\"_submitWorkflowConfigurationResponse\":{\"args\":[\"e\"],\"returnsPromise\":false},\"isDashboardItemEditable\":{\"args\":[\"window.dashboardSpaBridge\"],\"returnsPromise\":false},\"setDashboardItemTitle\":{\"args\":[\"(window.dashboardSpaBridge\"],\"returnsPromise\":false},\"openCreateIssueDialog\":{\"args\":[\"(o(\\"sOZ8\\"\"],\"returnsPromise\":false},\"openIssueDialog\":{\"args\":[\"(o(\\"sOZ8\\"\"],\"returnsPromise\":false},\"openDatePicker\":{\"args\":[\"((e\",\"t\"],\"returnsPromise\":false},\"initJQLEditor\":{\"args\":[\"()=>{}\"],\"returnsPromise\":false},\"showJQLEditor\":{\"args\":[\"(\\"div\\"\"],\"returnsPromise\":false},\"isNativeApp\":{\"args\":[\"t\"],\"returnsPromise\":false}},\"_featureFlag\":{\"getBooleanFeatureFlag\":{\"args\":[\"e\"],\"returnsPromise\":true}}},\"origin\":\"https://botron-dev-imc-3.atlassian.net/\",\"options\":{\"history\":{\"state\":\"\"},\"uniqueKey\":\"com.botronsoft.jira.issuematrix__view-issue-lists-5249574024409749412\",\"origin\":\"https://4040-77-85-31-87.ngrok-free.app/\",\"hostOrigin\":\"https://botron-dev-imc-3.atlassian.net/\",\"moduleType\":\"webPanels\",\"moduleLocation\":\"jira.issue.content.webpanel\",\"isFullPage\":false,\"autoresize\":true,\"user\":{\"timeZone\":\"Africa/Algiers\"},\"productContext\":{\"project.key\":\"IMCSOFT\",\"project.id\":\"10006\",\"issue.id\":\"10084\",\"issue.key\":\"IMCSOFT-1\",\"issuetype.id\":\"10000\"},\"structuredContext\":{\"jira\":{\"issue\":{\"issuetype\":{\"id\":\"10000\"},\"key\":\"IMCSOFT-1\",\"id\":\"10084\"},\"project\":{\"key\":\"IMCSOFT\",\"id\":\"10006\"}}},\"contextJwt\":\"CONTEXT_JWT_TOKEN\",\"contextPath\":\"\",\"sandbox\":\"allow-downloads allow-forms allow-modals allow-popups allow-scripts allow-same-origin allow-top-navigation-by-user-activation allow-storage-access-by-user-activation\",\"pearApp\":\"true\",\"targets\":{\"env\":{\"resize\":\"both\"}},\"contentClassifier\":\"\",\"_contextualOperations\":{},\"noDom\":true,\"globalOptions\":{\"0\":\"c\",\"1\":\"r\",\"2\":\"e\",\"3\":\"v\"}}}"`

Plesae we need this resolved ASAP, since this is a major blocker for our CI ❗

**Comment by AlexKamaev** [comment] 2023-06-20 08:19
Thank you for the research. We cannot fix this issue ASAP, since we already have planned our tasks for the following working sprint. You can create a PR in the `testcafe-hammerhead` repository. We'll review and accept it if everything is OK.

**Comment by mariyanbitsov-af** [comment] 2023-06-20 08:35
I don't have access to publish in the testcafe-hammerhead repo 😄

**Comment by BehaminBakhshaie** [comment] 2023-07-18 06:58
+1

**Comment by AlexKamaev** [comment] 2023-11-28 07:28
I did not manage to reproduce the issue on the latest TestCafe version (3.4.0), so I'll close it. If the issue persists, please feel free to create a separate issue using the following link: [https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&projects=&template=bug_report.yaml](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&projects=&template=bug_report.yaml).

**Closed by AlexKamaev** 2023-11-28 07:28 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, FREQUENCY: level 1
