### ISSUE TITLE
Testcafe fails on auth based on okta/msal

### ISSUE THREAD

**Issue by maximkoev** [DevExpress/testcafe#4929] opened 2020-03-30 12:37 UTC
### What is your Test Scenario?
I try sign in using testcafe. Tried use Role and without (preserveUrl true/false, disable cash, so all tips from official sources)
 
### What is the Current behavior?
When testcafe click "sign in" button i got an errors in console and redirect to start page.
We are using okta/msal auth flow., so when click sing in in okta form happens redirect, in the link present an token. Seems the problem is unable parse token cause of unexpected symbols before original url "http://localhost:**"
 
### What is the Expected behavior?
I expected success authentication 
 
### What is your web application and your TestCafe test code?
Unfortunatelly I have no rights to provide url due to NDA 

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 const role = Role(
      config.uri_BO, async t => {
        await t
          .click('button') // there is only one button on page. "Sign in via okta"
          .typeText(username, mail, { paste: true })
          .typeText(password, pass, { paste: true })
          .click(signin)
  }, { preserveUrl: true })
    await this.t.useRole(role)
```
<summary>Screenshots:</summary>

</details>

### Your Environment details:
 
* testcafe version:                1.8.3
* node.js version:              v10.16.3
* command-line arguments:  ts-node  ./testCafeRunner.ts
* browser name and version: Chrome Version 79.0.3945.130 (Official Build) (64-bit)
* platform and version:          Ubuntu 18.04.3 LTS, GNOME: 3.28.2
* other:                                 related issue on react-aad  https://github.com/syncweek-react-aad/react-aad/issues/218
![logs](https://user-images.githubusercontent.com/15101695/77913303-b1b33d80-729c-11ea-9a61-96afdd835f49.png)

**Comment by miherlosev** [comment] 2020-03-30 15:03
Hi @maximkoev 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a complete example so that we can reproduce it on our side?

**Comment by maximkoev** [comment] 2020-03-31 08:16
Hi @miherlosev, I sent such request to our developers

**Comment by kerosan** [comment] 2020-03-31 09:05
@miherlosev  there is example but you need azure credentials https://codesandbox.io/s/interesting-roentgen-7vntv

**Comment by aleks-pro** [comment] 2020-04-02 16:23
Hello @kerosan ,

The example doesn't work on my side. A click on the login button redirects to login.microsoft.com and the following error appears: `AADSTS900144: The request body must contain the following parameter: 'client_id'.` Does it work on your side?

**Comment by kerosan** [comment] 2020-04-03 09:22
@aleks-pro  as I said "you need azure credentials" now our team working on test application to reproduce this bug

**Comment by maximkoev** [comment] 2020-04-03 11:55
Hello @aleks-pro

**Comment by aleks-pro** [comment] 2020-04-06 15:02
Hello,

Since this issue is similar to the bug described in the [#4834](https://github.com/DevExpress/testcafe/issues/4834) thread, I will close this thread as a duplicate.
You can follow the [#4834](https://github.com/DevExpress/testcafe/issues/4834) thread to be aware of our results regarding this case.

**Closed by aleks-pro** 2020-04-06 15:02 UTC
Labels: STATE: Need response
