### ISSUE TITLE
Testcafe fails to run example tests on S5 Android 6.0.1

### ISSUE THREAD

**Issue by lixualinta** [DevExpress/testcafe#2338] opened 2018-04-23 00:04 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When you attempt to run "testcafe remote test.js" from the example repository, the testcafe browser window starts, the page loads, but nothing happens. 
Example Repo: https://github.com/AlintaEnergy/AndroidTestcafeBug

We've reproduced on Android 6.0.1 on an S5, however an S8 with Android 8 is working fine (albeit with one test failing). 

### What is the expected behavior?
The test runs as per normal, and completes

### How would you reproduce the current behavior (if this is a bug)?
Clone https://github.com/AlintaEnergy/AndroidTestcafeBug
npm install testcafe
run "testcafe remote test.js"
Open browser and load testcafe URL as shown in commandline. 

#### Provide the test code and the tested page URL (if applicable)
https://github.com/AlintaEnergy/AndroidTestcafeBug

Tested page URL:

Test code

```test.js

```

### Specify your

* operating system: Android 6.0.1 
* testcafe version: 0.19.2
* node.js version:  8.9.3

**Comment by AndreyBelym** [comment] 2018-04-23 11:52
Hi @lixualinta, I've reproduced the issue with the Samsung Browser on Galaxy S7 with Android 6 and Galaxy S8 with Android 7. It looks like a bug. We need some time to find the reason of the problem.

**Comment by bsmithb2** [comment] 2018-04-24 01:58
Bug appears to be introduced in 0.19.2-alpha1 release. If we install v0.19.2-dev20180323 the problem goes away

**Comment by bsmithb2** [comment] 2018-04-30 22:09
@AndreyBelym Hi Andrey - any update on the cause of the issue and its likely resolution? 
Thanks - awesome work BTW we love testcafe.

**Comment by miherlosev** [comment] 2018-05-04 11:09
Hi @lixualinta and @bsmithb2

@AndreyBelym reproduced the problem using Samsung Internet Browser on Galaxy S7. He used a browser from the [BrowserStack.com](https://www.browserstack.com) infrastructure.
Samsung Internet Browser installed on this device has a very old version - `4.0.01-89`. This version was released in early 2016 (see https://en.wikipedia.org/wiki/Samsung_Internet_for_Android#History).
It means that the browser has an old script engine that does not support modern script engine possibilities.
This is why `TestCafe` does not work with it.

You wrote that  - 'Bug appears to be introduced in 0.19.2-alpha1 release. If we install v0.19.2-dev20180323 the problem goes away'.
This can happen. We constantly refactor our code to provide a faster and bugless product that should work with modern browsers. See [TestCafe's browser support](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#officially-supported-browsers).

If you need to run tests in Samsung Internet Browser try to use the previous testcafe version (0.19.1) or upgrade Samsung Internet browser to the latest version.

**Comment by bsmithb2** [comment] 2018-05-04 12:33
Hi Mikhael,

No. We tested it on an S5, in Chrome. Not testing Samsung browser at all. 

Same Chrome version as an S7 in the same fleet on physical hardware not Browserstack. We have about 10% of Australian mobile Android users using S5s with locked to Android 6, but up to date Chrome. To not support Android 6 is a deal breaker. 

Please reopen?

Thanks

Bradley

**Comment by AndreyBelym** [comment] 2018-05-04 13:35
Hi @bsmithb2, could you please provide the Chrome version information that is printed when Chrome on Samsung S5 connects to TestCafe?

**Comment by bsmithb2** [comment] 2018-05-04 20:41
All of these devices were working less than a month ago in testcafe. All are Australian retail devices unboxed this February that we run in a test rack as a customer would ie without any corporate changes. The S8 passes. The S5 and Optus phones do not but they comprise significant market share. 
Android 7 is 51% of our three monthly user base of Android Devices
Android 8 is 10 %
Android 6 and below is the remaining 49% 6.0 and 6.0.1 is collectively higher than Android 8 (about 15% of total)
Chrome 66 is about 3% of our market share. Most devices by our customers are 63-65 (90%) but about 7-8% are below that. 
Supporting only the most recent devices and versions of software for mobile in Australia is difficult because telephony vendors lock their systems down and don’t allow or delay upgrades on some devices. I suspect the problem however would be significantly worse for vendors trying to use your software to automate for the African and South American markets however. Even large portions of Asia are likely to be on older, slower device types. Why discriminate?

The exact device versions are below. 

Thanks

Bradley 
[Run on S8] - Chrome Mobile 65.0.3325 / Android 8.0.0
This is an Optus $149 Prepaid in Aus - Chrome Mobile 55.0.2883 / Android 6.0.0
S5 - Chrome Mobile 55.0.2883 / Android 6.0.1

**Comment by AndreyBelym** [comment] 2018-05-08 07:36
@bsmithb2, Chrome version on Galaxy S5 is outdated:
```
S5 - Chrome Mobile 55.0.2883 / Android 6.0.1
```
It's not Chrome 65, but Chrome **55**. It can be easily upgraded to a more recent Chrome version through Play Market, and it doesn't matter what Android version is installed on the phone. As you've said, Chrome versions older than 63 have about 7% of market share. JFYI, I personally have an Android 6 phone with the latest Chrome version installed.

**Comment by psi-4ward** [comment] 2018-05-18 11:45
Same here: Galaxy S7, Stock browser

```
CONNECTED Samsung Internet 6.4.0 / Android 7.0.0
 Running tests in:
 - Samsung Internet 6.4.0 / Android 7.0.0

 Use build-in assertions
  testcafe:test-run:Samsung Internet 6.4.0 / Android 7.0.0:command
  testcafe:test-run:Samsung Internet 6.4.0 / Android 7.0.0:command     {
  testcafe:test-run:Samsung Internet 6.4.0 / Android 7.0.0:command       "type": "test-done"
  testcafe:test-run:Samsung Internet 6.4.0 / Android 7.0.0:command     }
  testcafe:test-run:Samsung Internet 6.4.0 / Android 7.0.0:command  +0ms
ERROR The Samsung Internet 6.4.0 / Android 7.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```

**Comment by miherlosev** [comment] 2018-05-21 09:40
@lixualinta @bsmithb2

We support and run our tests only on the [latest desktop Chrome](https://github.com/DevExpress/testcafe/blob/master/Gulpfile.js#L76) and on the [Chrome Mobile 64](https://github.com/DevExpress/testcafe/blob/master/Gulpfile.js#L119) provided by [Saucelabs](https://saucelabs.com/). 
`Chrome Mobile 55` is a very outdated browser and we will not support it.

@psi-4ward
`Samsung Internet 6.4.0` is a Chromium-based browser with an old script engine that equivalents Chrome 56. We will not support it.
![image](https://user-images.githubusercontent.com/4133518/40300777-e4cadc76-5cf2-11e8-920b-124e6779bb8d.png)

**Closed by miherlosev** 2018-05-21 09:40 UTC
Labels: AREA: client, SYSTEM: hammerhead, TYPE: bug

**Comment by psi-4ward** [comment] 2018-05-21 15:21
Okay so it's a bit difficult to know whichs browsers are supported, especially for those embedded ones. What about a testcafe.com/supported-browser page which tells you if your current browser is supported?

**Comment by miherlosev** [comment] 2018-05-21 15:28
Such page exists - https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#officially-supported-browsers.
We will think about adding link to this page for new issue template.

**Comment by psi-4ward** [comment] 2018-05-21 15:30
Of course I know the docs but I thought about adding a page which parses the User-Agent header and tells you if the browser is supported. I thought the embedded android browser is not as old as you said.

**Comment by miherlosev** [comment] 2018-05-22 09:27
@psi-4ward 

> and tells you if the browser is supported

I've created a separate issue for this task - https://github.com/DevExpress/testcafe/issues/2446
