### ISSUE TITLE
The page under test is not loading when I run my tests 

### ISSUE THREAD

**Issue by Victoryyyyy** [DevExpress/testcafe#3439] opened 2019-02-13 13:34 UTC
### What is your Test Scenario?
I am trying to proceed to the success page after I paid for a product.  
 
### What is the Current behavior?
Success page is not loading 
 
### What is the Expected behavior?
We should see the success page with customers details 

 
### What is your web application and your TestCafe test code?

Your website URL (or attach your complete example):
Since the web site is not publicly available yet I can't provide a link
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```test('After success payment success page displayed with customer detail', async t => {
  await proceedToCheckout(t)
  await checkoutPage.proceedToPayment(t)
  await t.expect(checkoutPage.cybersourceWrapper.visible).ok()
  await t.switchToIframe(checkoutPage.cybersourceIframe)
  const card = await checkoutPage.randomCard()
  await checkoutPage.payWithCard(card)
  await t.switchToMainWindow()
  await t
    .expect(checkoutPage.orderConfirmation.innerText)
    .eql('Your order is being processed')
})
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.0.0  
* node.js version:                    10.4.1 
* command-line arguments:  testcafe chrome packages/tests/integration/src/**/*.test.js -e 
* browser name and version: Chrome 72.0.3626.109
* platform and version:          macOS 10.13.1
* other:                                   I tryied testcafe: 0.22.0, 0.23.3 same results
<img width="641" alt="screen shot 2019-02-14 at 10 23 57" src="https://user-images.githubusercontent.com/36386410/52780703-bb4ef700-3042-11e9-89b4-97dfbc8ee039.png">

**Comment by LavrovArtem** [comment] 2019-02-13 14:54
The information you provided is insufficient for me to determine the cause of the issue and find a precise solution. Please make sure to fill in all the fields with requested information.

**Comment by Victoryyyyy** [comment] 2019-02-14 11:01
Hi Lavrov Artem, I did update the fields. All I can provide.

**Comment by LavrovArtem** [comment] 2019-02-14 16:10
Thank you for the screenshot. It looks like it's a duplicate of DevExpress/testcafe-hammerhead#1731.

**Closed by LavrovArtem** 2019-02-14 16:10 UTC
Labels: STATE: Need response
