### ISSUE TITLE
Official Testcafe Docker image fails to install FFMpeg

### ISSUE THREAD

**Issue by bessey** [DevExpress/testcafe#6920] opened 2022-03-10 16:16 UTC
### What is your Scenario?

Per [the recommendation elsewhere](https://github.com/DevExpress/testcafe/issues/6330#issuecomment-867440545) we add FFMpeg to the official docker image to record videos in CI. 

As of yesterday - 2022-09-03 it looks like the Alpine package repository updated to FFMpeg 5, and it fails to install. I've included the output below. EDIT: [Matching Alpine issue now exist](https://gitlab.alpinelinux.org/alpine/aports/-/issues/13585).

I think you could reasonably argue this is an Alpine problem to be honest, but thought since I had debugged I should report here anyway. I was going to suggest reverting to a non-edge Alpine release but that would send the browser versions into the dark ages

### What is the Current behavior?

```
 ---> 2e95e2227c1a00:14
Step 3/9 : RUN apk update && apk add ffmpeg00:15
 ---> Running in 3edf85c13fdb00:15
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz00:15
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz00:15
v3.15.0-8092-g02f30e0d45 [https://dl-cdn.alpinelinux.org/alpine/edge/main]00:15
v3.15.0-8094-gfdc07f09e7 [https://dl-cdn.alpinelinux.org/alpine/edge/community]00:15
OK: 16517 distinct packages available00:15
(1/6) Upgrading libvpx (1.10.0-r1 -> 1.11.0-r0)00:15
(2/6) Installing ffmpeg4-libs (4.4.1-r0)00:15
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavcodec.so.58 owned by ffmpeg-libs-4.4.1-r3.00:15
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavcodec.so.58.134.100 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavdevice.so.58 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavdevice.so.58.13.100 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavfilter.so.7 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavfilter.so.7.110.100 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavformat.so.58 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavformat.so.58.76.100 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavresample.so.4 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavresample.so.4.0.0 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavutil.so.56 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libavutil.so.56.70.100 owned by ffmpeg-libs-4.4.1-r3.00:16
 00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libpostproc.so.55.9.100 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libswresample.so.3 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libswresample.so.3.9.100 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libswscale.so.5 owned by ffmpeg-libs-4.4.1-r3.00:16
ERROR: ffmpeg4-libs-4.4.1-r0: trying to overwrite usr/lib/libswscale.so.5.9.100 owned by ffmpeg-libs-4.4.1-r3.00:16
(3/6) Upgrading ffmpeg-libs (4.4.1-r3 -> 5.0-r0)00:16
(4/6) Installing ffmpeg (5.0-r0)00:16
(5/6) Upgrading icu-libs (69.1-r1 -> 70.1-r0)00:16
(6/6) Upgrading firefox (95.0.1-r0 -> 98.0-r1)00:17
Executing busybox-1.35.0-r1.trigger00:17
Executing gtk-update-icon-cache-2.24.33-r0.trigger00:17
1 error; 637 MiB in 189 packages
```

### What is the Expected behavior?

```
 ---> b752fe8c434b00:12
Step 3/9 : RUN apk add ffmpeg00:12
 ---> Running in 2008c9b46cd400:12
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz00:12
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz00:12
(1/1) Installing ffmpeg (4.4.1-r5)00:12
Executing busybox-1.35.0-r1.trigger00:12
OK: 613 MiB in 188 packages00:13
Removing intermediate container 2008c9b46cd400:13
 ---> a268b22274e3
```

### What is your public website URL? (or attach your complete example)

Irrelevant

### What is your TestCafe test code?

Irrelevant

### Steps to Reproduce

Try and build a Dockerfile with this contents
```Dockerfile
# Same is true for :latest
FROM testcafe/testcafe:1.18.3

USER root
RUN apk update && apk add ffmpeg
```

### TestCafe version

1.18.3

### Command-line arguments

irrelevant

**Comment by AlexKamaev** [comment] 2022-03-11 10:36
I cannot reproduce the issue. I research the thread you mentioned. Developers report that the issue is fixed in the following commit: [https://gitlab.alpinelinux.org/alpine/aports/-/commit/13f96ae3ec1c38dec5762e613cfff3e5dd03ed35](https://gitlab.alpinelinux.org/alpine/aports/-/commit/13f96ae3ec1c38dec5762e613cfff3e5dd03ed35)
Please try to create your image once again and share the results with us.

**Closed** 2022-03-18 08:43 UTC
Labels: TYPE: bug, STATE: Need response
