### ISSUE TITLE
Testcafe 3.5.0 don't support EcmaScript 2022 syntax 

### ISSUE THREAD

**Issue by bhassane73** [DevExpress/testcafe#8128] opened 2024-01-23 14:21 UTC
### What is your Scenario?

HI I installed the latest Testcafe version 3.5.0 but our test automation is no longer working. This is the analysis of out IT department:

_From the stacktrace, I would assume that this is an issue with the thirdparty component (testcafe-)hammerhead.js that is used in your test execution context. It seems that the version in use does not support EcmaScript 2022 syntax, especially not private fields (which are now used in UI5 code)._

This the command line I use to run the test testcafe -e chrome <my test> --disable-native-automation
I added the param --disable-native-automation in order to disable SSO.

Can you please assist?

### What is the Current behavior?

Blank page displayed

### What is the Expected behavior?

Application components displayed

### What is the public URL of the test page? (attach your complete example)

Cannot provide

### What is your TestCafe test code?

Command line testcafe -e chrome <my test> --disable-native-automation

### Your complete configuration file

...
  "dependencies": {
        "moment-timezone": "^0.5.34",
        "testcafe": "^3.5.0",
        "testcafe-browser-provider-puppeteer": "^1.5.2",
        "testcafe-browser-provider-saucelabs": "^1.9.0",
        "testcafe-browser-provider-selenium": "^1.2.0",
        "testcafe-reporter-html": "^1.4.6",
        "testcafe-reporter-xray-jira": "^1.1.2-unstable"
    },
    "sauceConnectLauncher": {
        "scVersion": "latest"
    }

### Steps to Reproduce

1.NA
2.
3.

### TestCafe version

3.5.0

### Command-line arguments

--disable-native-automation

**Comment by bhassane73** [comment] 2024-01-24 11:09
Hi, Thank you for your answer, However, I still get a blank page even when I add the option.

This is what I see in the browser console --experimental-multiple-windows. So the issue is not resolved.

 cdm.js:10 Uncaught ModuleError: Failed to resolve dependencies of 'sap/ushell/bootstrap/cdm/cdm-def.js'
 -> 'sap/ushell/bootstrap/cdm/cdm.boot.task.js'
  -> 'sap/ushell/bootstrap/common/common.configure.ui5language.js'
   -> 'sap/ui/core/Configuration.js': failed to execute module factory for ''sap/ui/core/Configuration.js'': Cannot read property 'change' of undefined
    at we (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:6975)
    at ge.failWith (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:4945)
    at http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:17441
    at Oe (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:15907)
    at De (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:17395)
    at Object.Me [as define] (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:18476)
    at sap/ushell/bootstrap/cdm/cdm-def.js (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:533:8)
    at Ie (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:14476)
    at qe (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:12420)
    at Object.Se [as requireSync] (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:19838)
Caused by: ModuleError: failed to execute module factory for ''sap/ui/core/Configuration.js'': Cannot read property 'change' of undefined
    at we (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:6975)
    at ge.failWith (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:4945)
    at c (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:17082)
    at Oe (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:15924)
    at De (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:17395)
    at Object.Me [as define] (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:18476)
    at sap/ui/core/Configuration.js (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:345:8)
    at Ie (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:14476)
    at qe (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:12420)
    at Oe (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:15801)
Caused by: Error: Cannot read property 'change' of undefined
    at PropertyAccessorsInstrumentation._error (http://10.124.133.205:52735/hammerhead.js:20803:16)
    at PropertyAccessorsInstrumentation._propertyGetter (http://10.124.133.205:52735/hammerhead.js:20843:47)
    at e.attachEvent (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:52:281)
    at Object.attachChange (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:108:1789)
    at http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:345:7302
    at c (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:16914)
    at Oe (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:15924)
    at De (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:17395)
    at Object.Me [as define] (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:10:18476)
    at sap/ui/core/Configuration.js (http://10.124.133.205:52735/qLI4JrfBq*dkJYqwNYb!s!utf-8/https://sapui5.hana.ondemand.com/1.120.4/resources/sap/ushell/bootstrap/cdm.js:345:8) 
``` `

**Comment by bhassane73** [comment] 2024-02-01 12:04
Hi, Please see the attached ZIP file where you n
[Sample UI App.zip](https://github.com/DevExpress/testcafe/files/14125042/Sample.UI.App.zip)
can find a sample application, the READ.me file contains instructions to install the app. The you can create a test file containing
```
 fixture`Test `
    .page`http://localhost:3000/flp-sandbox.html#Shell-home`
test(`Test`, async t => {
    await t.wait(10000)
}) 
```

**Comment by Bayheck** [comment] 2024-02-05 08:50
Hello, 
I couldn't reproduce the issue with your example.
However, we already fixed the issue with private fields in testcafe-hammerhead. This fix has not been released yet for TestCafe. We plan to add it in the next release. Please stay tuned for updates.

**Comment by Bayheck** [comment] 2024-02-06 14:05
We'll close the issue for now since it's already fixed. If the issue persists after the update, we'll reopen it.

**Closed** 2024-02-06 14:05 UTC
Labels: TYPE: bug, STATE: Need response
