### ISSUE TITLE
Hammerhead request hangs on button click

### ISSUE THREAD

**Issue by kacy-weakley** [DevExpress/testcafe#6309] opened 2021-06-15 15:14 UTC
### What is your Test Scenario?
User is directed to multi-channel design styles after edit design with Creative Assistant.

### What is the Current behavior?
The hammerhead request stays pending and the page never redirects after clicking `Select Sizes` button on the design edit page.

### What is the Expected behavior?
Clicking `Select Sizes` button should redirect to the multichannel sizes page. 

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

https://mailchimp.com/
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector, t } from "testcafe";

export default new class LoginPage {
  constructor() {
    this.username = Selector("#username");
    this.password = Selector("#password");
    this.btnLogin = Selector("button[value='log in']");
  }

  async login(user, pwd) {
    await t
      .click(this.username)
      .typeText(this.username, user)
      .typeText(this.password, pwd)
      .click(this.btnLogin);
  }
}

```
```js
import { Selector, t } from "testcafe";

export default new class ContentStudioPage {
  constructor() {
    this.loadingFrame = Selector("[class *= 'frame'] [class *= 'loading']");
    this.fallback = Selector("#fallback:not([title *='Loading'])").with({
      visibilityCheck: true,
      timeout: 30000
    });
    this.urlField = Selector("input")
        .withAttribute("name", "siteUrl")
        .with({visibilityCheck: true, timeout: 10000});
    this.showMeDesign = Selector("button")
        .withText("Show Me Designs")
        .with({visibilityCheck: true, timeout: 20000});
    this.designHeading = Selector("h2")
        .withAttribute("class", /heading/)
        .with({visibilityCheck: true, timeout: 90000});
    this.designSkeleton = Selector("div")
        .withAttribute("class", /designSkeletonContainer/)
        .with({visibilityCheck: true, timeout: 90000});
    this.editDesignButton = Selector("button")
        .withText("Edit Design")
        .with({timeout: 20000, visibilityCheck: true});
    this.designAssetAdTweaker = Selector("ad-tweaker")
        .withAttribute("class", "hydrated")
        .with({visibilityCheck: true});
    this.selectSizesButton = Selector("button").withExactText("Select Sizes");
    this.designCaption = Selector(
        "[data-dojo-attach-point='autoDesigner'] [class *= 'design'] label"
    );
    this.fullWidthCheckbox = Selector("div")
        .withExactText("Full Width")
        .child("input[type = 'checkbox']")
        .with({timeout: 15000});
  }

  async enterFallbackIframe() {
    await t
        .expect(this.loadingFrame.classNames)
        .notMatch(/active/, "container loading frame active", {timeout: 60000})
        .switchToIframe(this.fallback);
  }

  async createDesignFrom(url) {
    await this.enterFallbackIframe();
    await t.typeText(this.urlField, url);
    await t.click(this.showMeDesign);
  }

  async waitForDesignLoad() {
    await this.designHeading();
    await this.designSkeleton();
    await t
        .expect(this.designSkeleton.exists)
        .notOk("Designs finished loading", {timeout: 90000});
  }

  async selectEditDesign() {
    await this.editDesignButton();
    await t.click(this.editDesignButton);
    await this.designAssetAdTweaker();
  }

  async clickSelectSizes() {
    await t.click(this.selectSizesButton);
    await t.debug();
  }
}
```

```js
import { Selector } from "testcafe";
import loginPage from "../../models/page_model/LoginPage";
import contentStudioPage from "../../models/page_model/ContentStudio";

fixture `Mailchimp`
  .page('https://mailchimp.com/login')
  .beforeEach(async t => {
    await t.maximizeWindow();
    await loginPage.login('******', '******'); // Supply own credentials
    await t.click(Selector("li a").withAttribute("href", "/content"));
  });

test("User is directed to multi-channel design styles after edit design with Creative Assistant", async () => {
  await contentStudioPage.createDesignFrom("https://mailchi.mp/43743693146d/landing-page-for-creative-assistant");
  await contentStudioPage.waitForDesignLoad();
  await contentStudioPage.selectEditDesign();
  await contentStudioPage.clickSelectSizes(); // Button continues to show it's loading hangs and hammerhead request remains pending indefinitely
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>
```
```
</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/42981008/122077960-3454e980-cdca-11eb-9518-e569642dafc0.png)

</details>

### Steps to Reproduce:

1. Go to mailchimp.com
2. Log in
3. Navigate to Content Studio
4. Enter a url and click "Show Me Designs"
5. Select "Edit Design" button on one of the four designs
6. Click "Select Style" button
 
### Your Environment details:
 
* testcafe version:                   1.14.2
* node.js version:                    10.16.3
* command-line arguments:  `testcafe chrome ./test.js`
* browser name and version: `Chrome 91.0.4472.77`
* platform and version:           `macOS 10.15.7`

**Comment by Farfurix** [comment] 2021-06-17 08:18
@kacy-weakley 

Hello,

I reproduced this issue in Windows 10 and Chrome 91. The issue looks like a duplicate of https://github.com/DevExpress/testcafe/issues/6008. So, I'll close this thread. We will examine your case in the context of the following issue: https://github.com/DevExpress/testcafe/issues/6008.

**Closed by Farfurix** 2021-06-17 08:18 UTC
Labels: STATE: Need response
