### ISSUE TITLE
ClientFunction not working for returning large object/array

### ISSUE THREAD

**Issue by thecodejack** [DevExpress/testcafe#1110] opened 2017-01-04 07:29 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
TestCafe keeps waiting at ClientFunction when returning object/array which is very large for following code.

```
const getFirstGridTotalRows = ClientFunction(() => {
    return window.gridRef[0].filteredRows();
});
const gridData = await getFirstGridTotalRows();
```
gridData is expected to have around 99k objects in an array. But while running tests, tests are not going forward. It is not even throwing any error. it just waits.

### What is the expected behavior?
Should either throw error of memory limit or return the data.

### How would you reproduce the current behavior (if this is a bug)?
Take any very large dataset and return it from application url through ClientFunction.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
const getFirstGridTotalRows = ClientFunction(() => {
    return window.gridRef[0].filteredRows();
});
const gridData = await getFirstGridTotalRows();
```

### Specify your

* operating system: Windows 7
* testcafe version: 0.11.1
* node.js version: 6.9.1

**Comment by inikulin** [comment] 2017-01-09 10:33
Hi @thecodejack,

I've tried to reproduce the issue on my side using the following code:
*index.html*
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    window.rows = [];

    for (var i = 0; i < 100000; i++)
        window.rows.push({ name: 'row' + i, payload: 'Hey42' });
</script>
</body>
</html>
```

*test.js*
```js
import { ClientFunction } from 'testcafe';

fixture `gh1110`
    .page `http://localhost:8080`;

const getRows = ClientFunction(() => window.rows);

test('Count rows', async t => {
    const rows = await getRows();

    await t.expect(rows.length).eql(100000);
});
```

While test run takes some noticeable time, it's completed successfully. Is there something what I'm missing?

**Comment by thecodejack** [comment] 2017-01-09 14:29
This makes it failing in my PC:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    window.rows = [];

    for (var i = 0; i < 100000; i++) {
        var obj = {};
        for (var j=0; j< 100; j++) {
            obj['Super'+ j] = 'Check if object loaded' + j;
        }
        rows.push(obj);
    }
        
</script>
</body>
</html>
```

**Comment by inikulin** [comment] 2017-01-10 09:58
I was able to reproduce the issue. The cause of the problem is that browser runs out of memory when we try to serialize enormously large object. I guess the best option here will be a limit for the returned object size, let's just throw an error with some descriptive message.

**Comment by AndreyBelym** [comment] 2018-07-12 12:57
Closing this issue in favor of https://github.com/DevExpress/testcafe/issues/2618.

**Closed by AndreyBelym** 2018-07-12 12:57 UTC
Labels: AREA: client, SYSTEM: API, TYPE: bug

**Comment by dlangerenken** [comment] 2019-02-16 18:48
@AndreyBelym is there another way for returning very large objects? #2618 is not sufficient since I need to transfer objects of that size. I do code-coverage analysis using istanbul-instrumenter. The coverage is logged in window.__coverage__ and I need to access this after a successful test-run.

**Comment by dlangerenken** [comment] 2019-02-16 19:11
Since I can stringify my object, I wrote a helper function that checks the size first, and then I call multiple times into the browser and copy the data I need:

```typescript
const maximumObjectSize = 1024 * 1024 * 4.0; // 4 mb - to be sure
export const codeCoverageSize = ClientFunction(() => {
  const json = JSON.stringify((window as any).__coverage__);
  (window as any).__coverage_json__ = json;
  return JSON.stringify((window as any).__coverage__).length;
});

export const codeCoverage = ClientFunction((start: number, end: number) => {
  return (window as any).__coverage_json__.substring(start, end);
});

export const collectCodeCoverage = async (fileName = randomNotebookTag()) => {
  const size = await codeCoverageSize();
  const splits = Math.ceil(size / maximumObjectSize);
  let coverageJson = '';
  for (let i = 0; i < splits; i++) {
    const start = i * maximumObjectSize;
    coverageJson += await codeCoverage(start, start + maximumObjectSize);
  }
  console.log(coverageJson);
};
```
