### ISSUE TITLE
pressKey('right') doesn't work => KeyboardEvent.code is missing

### ISSUE THREAD

**Issue by pierrotest** [DevExpress/testcafe#4710] opened 2020-01-31 10:31 UTC
# What is your Test Scenario?
I use pressKey('right') to navigate in website but nothing happens

In my code, i detect keyboardEvent using [KeyboardEvent.code](https://developer.mozilla.org/fr/docs/Web/API/KeyboardEvent/code ) 

I log keyboardEvents (key, code and keyCode)

### What is the Current behavior?
During tests, pressKey("right") doesn't work when i expect KeyboardEvent.code
When I log keyboardEvents I can see : 
- key ==> ArrowRight
- keyCode ==> 39
- code ==> 

When i use manually keyboard right arrow, I can navigate normaly 

### What is the Expected behavior?
pressKey("right") works
When I log keyboardEvents I expect : 
- key ==> ArrowRight
- keyCode ==> 39
- code ==> ArrowRight

### Environment details:
 
* testcafe version:                   1.8.1
* browser name and version: Chrome, Chromium, Firefox (I did not try IE or Edge)

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

**Comment by JSteunou** [comment] 2020-01-31 13:42
`keyCode` is deprecated even if well supported by browser vendors, so I understand the support, but `code` is present in spec, modern browsers, and there is a strong advice on its usage, so adding its support in testcafe should be essential.

**Comment by arubtsov** [comment] 2020-02-03 11:44
Hello,

Thank you for your inquiry. This is a duplicate of https://github.com/DevExpress/testcafe/issues/3146. Please vote for it and track our progress there.

**Closed by arubtsov** 2020-02-03 11:44 UTC
Labels: STATE: Need response
