### ISSUE TITLE
More verbose output about actions and assertions

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4001] opened 2019-07-08 14:03 UTC
https://stackoverflow.com/questions/56932508/how-to-be-more-verbose-on-tests
https://stackoverflow.com/questions/56980542/testcafe-display-steps-while-running-tests

It will be useful if TestCafe provides more info about executed steps. Example:
```js
-------------------------------------------------------------------------
VISIT: http://example.com
TYPE: 'username' in #UserName
CLICK: 'submit' button
-------------------------------------------------------------------------
```

**Comment by joywave** [comment] 2020-01-02 17:32
This would be nice to have

**Comment by Raynos** [comment] 2020-02-25 10:08
I'd love this too, especially with timing information.

**Comment by eugene-tkachenko** [comment] 2020-03-04 16:03
Can confirm that it would relieve lives of developers for sure.

**Comment by leob** [comment] 2020-06-16 19:36
This is not just "nice", this would be an absolute lifesaver, which would (in many scenarios) make all the difference. Is there really not an option already which does just this? So, indeed, simply the ability to have the executed steps printed to the terminal (console). That would make it like a dozen times easier to know what's going, on and to troubleshoot things.

**Comment by Raynos** [comment] 2020-06-17 12:30
```sh
npm i testcafe-reporter-spec-time -D
./node_modules/.bin/testcafe -r spec-time chrome:headless ./tests
```

This gives you timing granularity.

Alternatively there's a `DEBUG` flag you can set to get testcafe to output everything

```sh
DEBUG=testcafe:* testcafe
```

This will give you all the messages it sends between main process and browser process.

**Comment by leob** [comment] 2020-06-17 12:41
Thanks! I knew about `DEBUG=*` which however gives a huge amount of details, but I'll check `DEBUG=testcafe:*` and the `spec-time` reporter ...

**Comment by Raynos** [comment] 2020-06-18 08:12
I'd like to see a shortened version of `DEBUG=testcafe:*` as well with what actions took place, what selectors / assertions took place and an option to show more or less.

**Comment by byrne-greg** [comment] 2021-02-10 10:39
Just to add, for automated testing environments where sporadic failures can occur at integration level, `DEBUG=testcafe:*` is so verbose for some build providers that they truncate the logs. This means I can't see debug text reports for when things go awry. A shortened version of `DEBUG=testcafe:*` would really help here

**Comment by fHYeemRLTX** [comment] 2021-04-24 19:49
This would help a lot. Perhaps a verbose option can be created.

So for example this code:
<pre>import { Selector } from 'testcafe';
fixture `Example` 
    .page `http://devexpress.github.io/testcafe/example`;
test('Example test', async t => {
    await t
        .resizeWindow(1920, 1080)
        .typeText('#developer-name', 'John Smith')
        .expect(Selector('#remote-testing').checked).notOk()
        .expect(Selector('#reusing-js-code').checked).notOk()
        .click('#background-parallel-testing')
        .expect(Selector('#background-parallel-testing').checked).ok()
        .click('#continuous-integration-embedding')
        .expect(Selector('#continuous-integration-embedding').checked).ok()
        .expect(Selector('#traffic-markup-analysis').checked).notOk()
        .click('#preferred-interface')
        .click(Selector('#preferred-interface').child(2))
        .click('#windows')
        .click('#tried-test-cafe')
        .typeText('#comments', 'test')
        .takeScreenshot('testA.png', 1)
        .click('#submit-button')
        .takeScreenshot('testB.png', 1)
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});</pre>

With output
<pre> Example
 √ Example test (screenshots: ...\screenshots)</pre>

Could be shown as something similar to the output of this code if the ``--verbose`` option is used:
<pre>import { Selector } from 'testcafe';
fixture `Example` 
    .page `http://devexpress.github.io/testcafe/example`;
test(".resizeWindow(1920, 1080)", async t => { await t.resizeWindow(1920, 1080); });
test(".typeText('#developer-name', 'John Smith')", async t => { await t.typeText('#developer-name', 'John Smith'); });
test(".expect(Selector('#remote-testing').checked).notOk()", async t => { await t.expect(Selector('#remote-testing').checked).notOk(); });
test(".expect(Selector('#reusing-js-code').checked).notOk()", async t => { await t.expect(Selector('#reusing-js-code').checked).notOk(); });
test(".click('#background-parallel-testing')", async t => { await t.click('#background-parallel-testing'); });
test(".expect(Selector('#background-parallel-testing').checked).ok()", async t => { await t.click('#background-parallel-testing').expect(Selector('#background-parallel-testing').checked).ok(); });
test(".click('#continuous-integration-embedding')", async t => { await t.click('#continuous-integration-embedding'); });
test(".expect(Selector('#continuous-integration-embedding').checked).ok()", async t => { await t.click('#continuous-integration-embedding').expect(Selector('#continuous-integration-embedding').checked).ok(); });
test(".expect(Selector('#traffic-markup-analysis').checked).notOk()", async t => { await t.expect(Selector('#traffic-markup-analysis').checked).notOk(); });
test(".click('#preferred-interface')", async t => { await t.click('#preferred-interface'); });
test(".click(Selector('#preferred-interface').child(2))", async t => { await t.click('#preferred-interface').click(Selector('#preferred-interface').child(2)); });
test(".click('#windows')", async t => { await t.click('#windows'); });
test(".click('#tried-test-cafe')", async t => { await t.click('#tried-test-cafe'); });
test(".typeText('#comments', 'test')", async t => { await t.typeText('#comments', 'test'); });
test(".takeScreenshot('testA.png', 1)", async t => { await t.takeScreenshot('testA.png', 1); });
test(".click('#submit-button')", async t => { await t.click('#submit-button'); });
test(".takeScreenshot('testB.png', 1)", async t => { await t.takeScreenshot('testB.png', 1); });
test(".expect(Selector('#article-header').innerText).eql('Thank you, John Smith!')", async t => { await t.typeText('#developer-name', 'John Smith').click('#submit-button').expect(Selector('#article-header').innerText).eql('Thank you, John Smith!'); });</pre>

Output
<pre>Example
 √ .resizeWindow(1920, 1080)
 √ .typeText('#developer-name', 'John Smith')
 √ .expect(Selector('#remote-testing').checked).notOk()
 √ .expect(Selector('#reusing-js-code').checked).notOk()
 √ .click('#background-parallel-testing')
 √ .expect(Selector('#background-parallel-testing').checked).ok()
 √ .click('#continuous-integration-embedding')
 √ .expect(Selector('#continuous-integration-embedding').checked).ok()
 √ .expect(Selector('#traffic-markup-analysis').checked).notOk()
 √ .click('#preferred-interface')
 √ .click(Selector('#preferred-interface').child(2))
 √ .click('#windows')
 √ .click('#tried-test-cafe')
 √ .typeText('#comments', 'test')
 √ .takeScreenshot('testA.png', 1) (screenshots: ...\screenshots\testA.png)
 √ .click('#submit-button')
 √ .takeScreenshot('testB.png', 1) (screenshots: ...\screenshots\testB.png)
 √ .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!')</pre>

Breaking the code up in different tests like I did in the example here is counterproductive, since the test changes to elements on the page are cleared between each test.

**Comment by gooddaytoday** [comment] 2021-04-30 09:02
I think that 

```
Example
 √ .resizeWindow(1920, 1080)
 √ .typeText('#developer-name', 'John Smith')
 √ .expect(Selector('#remote-testing').checked).notOk()
```
this is will be good, but not enough. It'll be more clear if output contain whole line as it is, so you could add comment: `√ .resizeWindow(1920, 1080) // Click to add new User in app`

**Comment by gooddaytoday** [comment] 2021-08-16 10:12
It seems that `t.log(...args)` approach, described in [#3584#issuecomment-515414619](https://github.com/DevExpress/testcafe/issues/3584#issuecomment-515414619) is common with this Issue if you need in human-readable actions logging. 

```typescript
test('Example test', async t => {
    await t
        .resizeWindow(1920, 1080)
        .log('Enter developer name John Smith')
        .typeText('#developer-name', 'John Smith')
        .expect(Selector('#remote-testing').checked).notOk()
        .expect(Selector('#reusing-js-code').checked).notOk()
        .log('Launching background testing')
        .click('#background-parallel-testing')
        .expect(Selector('#background-parallel-testing').checked).ok()
        .log('Launching CI server embedding')
        .click('#continuous-integration-embedding')
        .expect(Selector('#continuous-integration-embedding').checked).ok()
        .expect(Selector('#traffic-markup-analysis').checked).notOk()
        .log('Open modal window to choose interface')
        .click('#preferred-interface')
        .log('Selecting dark-color interface')
        .click(Selector('#preferred-interface').child(2))
        .log('selecting modal windows-like interface')
        .click('#windows')
```

In such way it overlaps with this issue and solves a little bit another problem - not only just echo every command, but give human-readable steps to reproduce.

I think that it will be helpful for these purposes:

1. Help developers to understand steps fastly from report in GitHub/GitLab test failure report
2. Simplify test's debugging in cases that don't need to launch debug mode (just to fix some small stuff). 
3. Reduce time for catching steps of flaky errors and point the exact place in test, so you can easy repeat just part of test to catch flaky error (especially in case of using a lot of helpers -> look at 5. item).
4. Allow to avoid `//comments` in code and transform them into readable actions: `.click(Selector('#preferred-interface').child(2)) // Selecting dark-color interface ` transforms to `.log('Selecting dark-color interface').click(Selector('#preferred-interface').child(2))`
5. If you use [such helpers](https://github.com/DevExpress/testcafe-examples/blob/master/examples/extract-code-to-helpers/index.js), it enable to clarify test logic on failure and reuse clarifying: 

```typescript
test('Fill form', async t => {
    const name = 'John Heart';
    await enterName(name);
    await typeComment('Here is what I think...');
    await submitForm();
    await t.expect(Selector('#article-header').textContent).contains(name);
});

export async function typeComment (text, commentType) {
    await t
        .log('Typing comment ' + text + ' with comment type' + commentTypeString(commentType))
        .click('#some_unreadable_selector').child(commentTypeSelector)
        .typeText('#comments', text);
}
```

So, what do you think? I could try to implement it in PR if such solution suits.

**Comment by gooddaytoday** [comment] 2021-08-16 10:32
Also, my proposal will help to solve problem #3245 in more concise way if steps will be outputing to log in case of failure:

```
AssertionError: There is error message in app: "Couldn't enable such action"

Actions:

1. Open solution (/lib/main.ts)
2. Open Workflow (/workflow/mix.ts)
3. Launch calculations (/calc/actions.ts)
4. Open cacl settings (/calc/actions.ts)

```

**Comment by aleks-pro** [comment] 2021-08-18 08:21
Hello @gooddaytoday ,

Thank you for your feedback. We will take it in to account.
As @AndreyBelym mentioned [here](https://github.com/DevExpress/testcafe/issues/3584#issuecomment-515414619), this feature is very complex. Of course, you are free to implement it and create a pull request. However, in this case, it will require significant time and resources for review and modification, which may not be available at the moment.

**Comment by elemental1313** [comment] 2023-06-15 12:39
Just came across this looking for some sort of assistance when looking into issues that testcafe has found.  Sometimes its hard to know when watching a video of a failure for example what step testcafe is currently on as I try to figure out the failure.  It could speed up my process immensely if the testcafe status bar at the bottom would let me know what step I am currently on when watching the playback, or if I could tell it what to display each step (similar to the .log suggestion above). Just wanted to throw in my 2 cents.

**Comment by leob** [comment] 2023-06-15 13:43
@elemental1313 yes I agree ... this issue was raised in 2019, we're in 2023 now, there's still no solution? I guess someone should just volunteer to do a PR ...

**Comment by AlexKamaev** [comment] 2023-08-07 07:57
In order do keep our backlog in actual state, we decided to close the issue. However, TestCafe has not-documented `reportTestActionStart` and `reportTestActionDone` methods.
As a workaround, you can create your own reporter or modify the existing reporter by implementing these methods.
Here is the places in code where these methods are called:
[https://github.com/DevExpress/testcafe/blob/77836876fd4396d0249bc0a772125727ea6798c9/src/reporter/index.ts#L637](https://github.com/DevExpress/testcafe/blob/77836876fd4396d0249bc0a772125727ea6798c9/src/reporter/index.ts#L637)
[https://github.com/DevExpress/testcafe/blob/77836876fd4396d0249bc0a772125727ea6798c9/src/reporter/index.ts#L656](https://github.com/DevExpress/testcafe/blob/77836876fd4396d0249bc0a772125727ea6798c9/src/reporter/index.ts#L656)

**Closed by AlexKamaev** 2023-08-07 07:57 UTC
Labels: TYPE: enhancement, FREQUENCY: level 2
