### ISSUE TITLE
Client side validation on excel file is failing in testcafe

### ISSUE THREAD

**Issue by rajeshshettysrs** [DevExpress/testcafe#5733] opened 2020-11-23 06:12 UTC
Our website is developed on react,after uploading excel,excel validation is happening in front end using third party library[sheet JS].Manually its working but testcafe automation is failing.Automation is hanging while client side validation in progress.

**Comment by Ogurecher** [comment] 2020-11-24 07:21
@rajeshshettysrs, Thank you for your report. Please share the TestCafe test code and your page URL or an example page that we could use to reproduce the issue.

**Comment by rajeshshettysrs** [comment] 2020-11-30 03:58
Sorry sir,our product is in alpha stage,as per company policy we cant share URL and code.Issue is "client side related validation is failing in testcafe[hammerhead server] and its hanging in that particular test case".Please guide me how to debug these type of issues.

**Comment by Ogurecher** [comment] 2020-12-01 07:45
I'm afraid I need more information to determine the cause of the issue. It looks like a TestCafe bug, and if it is, it will be difficult to give any advice on how to debug the issue. We'll need to deal with it on our side.

**Comment by rajeshshettysrs** [comment] 2020-12-01 14:04
Sir getting below error in console:

testcafe-driver.js:1 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'testcafe|driver|KirFXDE0T|YZFc7AXLz' exceeded the quota.
    at Vi.save (http://192.168.1.3:64685/testcafe-driver.js:1:27156)
    at Vi.setItem (http://192.168.1.3:64685/testcafe-driver.js:1:27261)
    at ra.set (http://192.168.1.3:64685/testcafe-driver.js:1:54073)
    at ra._onConsoleMessage (http://192.168.1.3:64685/testcafe-driver.js:1:56700)
    at t.<anonymous> (http://192.168.1.3:64685/testcafe-driver.js:1:83384)
    at t.emit (http://192.168.1.3:64685/hammerhead.js:15:6957)
    at console.window.console.<computed> [as log] (http://192.168.1.3:64685/hammerhead.js:6:17322)
    at FileReader.Ee.r.onload (http://192.168.1.3:64685/KirFXDE0T*YZFc7AXLz!s!utf-8/https://devgst.saral.pro/static/js/4.2df25844.chunk.js:2:67047)
Vi.save @ testcafe-driver.js:1
Vi.setItem @ testcafe-driver.js:1
set @ testcafe-driver.js:1
ra._onConsoleMessage @ testcafe-driver.js:1
(anonymous) @ testcafe-driver.js:1
t.emit @ hammerhead.js:15
window.console.<computed> @ hammerhead.js:6
Ee.r.onload @ 4.2df25844.chunk.js:2
81.ogg:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUTtestcafe-driver.js:1 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'testcafe|driver|KirFXDE0T|YZFc7AXLz' exceeded the quota.
    at Vi.save (http://192.168.1.3:64685/testcafe-driver.js:1:27156)
    at Vi.setItem (http://192.168.1.3:64685/testcafe-driver.js:1:27261)
    at ra.set (http://192.168.1.3:64685/testcafe-driver.js:1:54073)
    at ra._onConsoleMessage (http://192.168.1.3:64685/testcafe-driver.js:1:56700)
    at t.<anonymous> (http://192.168.1.3:64685/testcafe-driver.js:1:83384)
    at t.emit (http://192.168.1.3:64685/hammerhead.js:15:6957)
    at console.window.console.<computed> [as log] (http://192.168.1.3:64685/hammerhead.js:6:17322)
    at FileReader.Ee.r.onload (http://192.168.1.3:64685/KirFXDE0T*YZFc7AXLz!s!utf-8/https://devgst.saral.pro/static/js/4.2df25844.chunk.js:2:67047)
Vi.save @ testcafe-driver.js:1
Vi.setItem @ testcafe-driver.js:1
set @ testcafe-driver.js:1
ra._onConsoleMessage @ testcafe-driver.js:1
(anonymous) @ testcafe-driver.js:1
t.emit @ hammerhead.js:15
window.console.<computed> @ hammerhead.js:6
Ee.r.onload @ 4.2df25844.chunk.js:2
81.ogg:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by Ogurecher** [comment] 2020-12-02 07:53
Based on the error message you shared, I'd say this issue looks similar to [https://github.com/DevExpress/testcafe/issues/2895](https://github.com/DevExpress/testcafe/issues/2895).
Please use the workaround described in [this thread](https://github.com/DevExpress/testcafe/issues/2942).

**Comment by Ogurecher** [comment] 2020-12-02 07:54
Duplicate of https://github.com/DevExpress/testcafe/issues/2942.

**Closed by Ogurecher** 2020-12-02 07:54 UTC
Labels: STATE: Duplicate
