### ISSUE TITLE
Failed to load the web page on all testcafe versions 

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe#7632] opened 2023-04-16 06:12 UTC
### What is your Scenario?

Looks like testcafe tool not working for one of web page  and throwing error says “Failed to load the page”

Failed to load the page at "".
      Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option, or use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".
      
      Error details:
      TypeError: ExprGen[itemType] is not a function

### What is the Current behavior?

about:error empty screen loading instead of actual web page

### What is the Expected behavior?

Web page should load on any browsers with any node version with testcafe tool

### What is your public website URL? (or attach your complete example)

none

### What is your TestCafe test code?

I’ve send sample POC code to your email: [support@devexpress.com](mailto:support@devexpress.com) , Kindly check and fix as soon as possible

### Screenshots

<img width="1049" alt="Screen Shot 2023-04-15 at 10 49 35 PM" src="https://user-images.githubusercontent.com/8210719/232275178-473a8f1a-2239-4977-9c4a-b6238c67cbff.png">

### Steps to Reproduce

1. git clone {GIT_URL} repo which sent it to your  email: [support@devexpress.com](mailto:support@devexpress.com)
2. cd testcafe-poc
3. npm install
4. npm run test

### TestCafe version

Version: 1.19.0

### Node.js version

v14.17.0

### Command-line arguments

NONE

### Browser name(s) and version(s)

Chrome Version 96.0.4664.110

### Platform(s) and version(s)

macOS Mojave Version 10.14.6

**Comment by patrickathompson** [comment] 2023-04-16 19:38
I am having the same issue. This is really strange because nothing was changed to my knowledge. On April 12th between 11:00a and 11:30a cdt, I started noticing the issue. In the following 2 days it propagated to all ci/cd runs. I have tried upgrading from 1.20.1 on multiple versions and the issue still exists. The only way to get around the issue that I have found is to enable nativeAutomation which is not an acceptable solution because Browserstack is not supported and we are also experiencing different rendering behavior which deems some important button containers un-clickable. My team will have no choice but to move to playwright if these issues are not resolved within a timely manner. Please let me know how I can help. Thanks!

**Comment by shyedhu** [comment] 2023-04-16 20:17
Thanks, @patrickathompson , I am disappointed that testcafe stopped working starting April 12th for only some web pages. My question to [support@devexpress.com](mailto:support@devexpress.com) do we have any updates for the fix.. I'm sure upgrading the testcafe version will not going to help anymore .. I think testcafe's dependencies causing that issue **TypeError: ExprGen[itemType]** starting April 12th. I can't switch to other automation tools for now since using testcafe for a very long time .. Hopefully, the dev express support team will provide a temporary workaround or fix that problem very soon.

**Comment by felis2803** [comment] 2023-04-17 07:49
Hi @shyedhu

Thanks for your example. I was able to reproduce this problem. It seems that it is the same as in issue #7275. We will investigate this issue.

**Comment by aarav-chegg** [comment] 2023-04-17 08:04
Any updates on this? We are also suddenly experiencing a similar issue.

**Comment by fadious** [comment] 2023-04-17 13:23
I'm facing the same issue, it's blocking some of our deployment pipelines, I would really appreciate it if it gets prioritized.

**Comment by tgrisley** [comment] 2023-04-17 13:50
Any update?

**Comment by Jgrabenbauer** [comment] 2023-04-17 16:39
> 

@byslavik is there any other way of doing that but with npm?

**Comment by Jgrabenbauer** [comment] 2023-04-17 16:39
> Seems like it is failing because of missing PropertyDefinition and PrivateIdentifier thingies from this PRs https://github.com/DevExpress/esotope-hammerhead/pull/22/files https://github.com/DevExpress/esotope-hammerhead/pull/21/files I checked the value of itemType at the moment of error <img alt="image" width="197" src="https://user-images.githubusercontent.com/15650311/232438274-79ae4282-452b-463c-9133-3f486f92ffd6.png">
> 
> Applying those changes using yarn patch has helped me to unblock the pipeline.
> 
> Can such kind of issues be avoided in future? I didn't update anything, so I did not expect something to brake

@byslavik is there any other way of doing that but with npm?

**Comment by ayemelyanenko-chegg** [comment] 2023-04-17 16:51
@Jgrabenbauer Try this
https://www.npmjs.com/package/patch-package

**Comment by ayemelyanenko-chegg** [comment] 2023-04-17 20:51
Is it possible to get the below 2 PRs merged in as they appear to fix the issue?
https://github.com/DevExpress/esotope-hammerhead/pull/22/files
https://github.com/DevExpress/esotope-hammerhead/pull/21/files

**Comment by aarav-chegg** [comment] 2023-04-18 04:23
yes please merge these 2 PRs, they will fix the issue
https://github.com/DevExpress/esotope-hammerhead/pull/22/files
https://github.com/DevExpress/esotope-hammerhead/pull/21/files

**Comment by felis2803** [comment] 2023-04-18 07:09
Hello guys,

Thank you for your contribution. We are working on the problem. We will check the pull requests and release a new TestCafe version once we fix the issue.

**Comment by sorin-davidoi** [comment] 2023-04-18 07:12
@felis2803 I'll open a PR soon with the testcases for those two PRs in `testcafe-hammerhead` (per feedback).

**Comment by vinayvennela** [comment] 2023-04-18 08:53
> Hello guys,
> 
> Thank you for your contribution. We are working on the problem. We will check the pull requests and release a new TestCafe version once we fix the issue.

@felis2803 Does this also include fix for older versions or we need to use the latest version only? Cause I am still using an older version (2.2.0) and seeing the issue there as well.

**Comment by aleks-pro** [comment] 2023-04-20 06:39
Hello everyone,

We plan to add the fix to testcafe v2.5.1. While we are preparing it, you can use the release candidate version 2.5.1-rc.1, which includes the fix.

Thanks to @sorin-davidoi for the help.

**Comment by felis2803** [comment] 2023-04-20 06:40
We have released TestCafe@2.5.1-rc.1. It includes a fix for this issue.

@shyedhu I'm sorry, I have to correct you: the fix won't work for older versions.

@vinayvennela We only maintain one branch where we add all the changes.

**Comment by sorin-davidoi** [comment] 2023-04-20 07:22
> Then how come the issue started appearing in older versions all of a sudden?

Probably the website being tested changed - for us it popped up when we changed the transpilation configuration to drop support for some older browser versions (before this private fields were transpiled away).

**Closed** 2023-04-27 08:23 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, Support Center, FREQUENCY: critical

**Comment by kkapur5** [comment] 2024-10-22 18:17
I am having similar issue. Suddenly, I am unable to execute my scripts using chrome and edge. I am getting the following error. I have tried increasing timeout time but made no difference.

Failed to load the page at {url}.
Open the Run Configuration dialog to increase the value of the "pageRequestTimeout" option, or quarantine the problematic test. Additionally, you can enable the "retryTestPages" flag in the Preferences/Settings dialog.
You can find troubleshooting information for this issue at https://docs.devexpress.com/TestCafeStudio/400610/faq#request-failed.

Error details:
Failed to perform a request to the resource at {url} because of an error.
Error: connect ETIMEDOUT {IP}

Browser: Chrome 130.0.0.0 / Windows 10

**Comment by Bayheck** [comment] 2024-10-23 12:02
Hello, I believe I answered to your issue in https://github.com/DevExpress/testcafe/issues/8311
