### ISSUE TITLE
Text not entered in to Stripe iFrame with Safari

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#4793] opened 2020-02-19 23:19 UTC
### What is your Test Scenario?

 I'm trying to run our test code on multiple browsers, specifically entering in CreditCard details on our payment pages.

### What is the Current behavior?

It looks like text isn't being properly entered in to the Stripe payment iframes, on Safari. The same steps are successful in Chrome, Firefox and Edge.

The main concern here is that TestCafe continues on, believing it has actually entered text in to these iframes.
 
### What is the Expected behavior?

 Text should be entered in to Stripe iFrames, regardless of browser. OR, at the least, if TestCafe is unable to locate/interact with the iFrame... it should fail at that point instead of continuing on.

### What is your web application and your TestCafe test code?

<details>
<summary>Your website URL (or attach your complete example): </summary>

You can target our live site, since the issue relates to being unable to enter data in the payment forms:
https://www.change.org/
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { t, Selector } from 'testcafe';

fixture('Join Membership with credit card').page('https://www.change.org/');

test('Guest user clicks contribute directly', async () => {
  await t
    .navigateTo('s/member')
    .expect(Selector('[data-testid="member_landing_page_inline_contribute_button"]').visible)
    .ok();

  await t
    .click(Selector('[data-testid="member_landing_page_inline_contribute_button"]'), { speed: 0.3 })
    .expect(Selector('[data-testid="member_payment_form"]').visible)
    .ok();

  await t
    .click(Selector('[data-testid="payment-option-button-creditCard'))
    .expect(Selector('.iframe-form-element').visible)
    .ok();

  const emailAddressInput = Selector('[data-testid="input_email"]').filterVisible();
  const confirmationEmailInput = Selector('[data-testid="input_confirmation_email"]').filterVisible();
  const firstNameInput = Selector('[data-testid="input_first_name"]');
  const lastNameInput = Selector('[data-testid="input_last_name"]');

  await t
    .typeText(emailAddressInput, 'email@email.com')
    .typeText(confirmationEmailInput, 'email@email.com')
    .typeText(firstNameInput, 'Your')
    .typeText(lastNameInput, 'Name');

  await t
    .switchToIframe(Selector('[data-testid="credit-card-number"] iframe'))
    .typeText(Selector('input[name="cardnumber"]'), '1234123412341234', { replace: true })
    .expect(Selector('input[name="cardnumber"]').value)
    .eql('1234 1234 1234 1234')
    .switchToMainWindow();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
N/A
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Guest user clicks contribute directly

   1) AssertionError: expected '' to deeply equal '1234 1234 1234 1234'

      Browser: Safari 13.0.5 / macOS 10.15.3

         31 |
         32 |  await t
         33 |    .switchToIframe(Selector('[data-testid="credit-card-number"] iframe'))
         34 |    .typeText(Selector('input[name="cardnumber"]'), '1234123412341234', { replace: true
      })
         35 |    .expect(Selector('input[name="cardnumber"]').value)
       > 36 |    .eql('1234 1234 1234 1234')
         37 |    .switchToMainWindow();
         38 |});
         39 |

         at <anonymous>
      (/Users/rcooper/work/github.com/change/regression-qaa/tests/users/demo.js:36:6)



 1/1 failed (23s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
N/A
```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.8.2                 
* node.js version: 12.14.1                   
* command-line arguments: testcafe safari 
* browser name and version: Safari 13.0.5 
* platform and version: macOS 10.15.3

**Comment by AlexSkorkin** [comment] 2020-02-24 11:53
I've tried running your test case in several browsers (Chrome, Firefox, Safari) and it fails at line 14 with the same reason. Are there any additional actions or configuration steps I need to perform in order to run your test case, so it does not fail?

```
 Running tests in:
 - Chrome 80.0.3987.116 / macOS 10.15.2

 Join Membership with credit card
 ✖ Guest user clicks contribute directly

   1) AssertionError: expected false to be truthy

      Browser: Chrome 80.0.3987.116 / macOS 10.15.2

          9 |    .ok();
         10 |
         11 |  await t
         12 |    .click(Selector('[data-testid="member_landing_page_inline_contribute_button"]'), { speed: 0.3 })
         13 |    .expect(Selector('[data-testid="member_payment_form"]').visible)
       > 14 |    .ok();
         15 |
         16 |  await t
         17 |    .click(Selector('[data-testid="payment-option-button-creditCard'))
         18 |    .expect(Selector('.iframe-form-element').visible)
         19 |    .ok();

         at <anonymous> (/Users/testuser/Desktop/skorkin/4793.js:14:6)



 1/1 failed (19s)

--

  Running tests in:
 - Safari 13.0.4 / macOS 10.15.2

 Join Membership with credit card
 ✖ Guest user clicks contribute directly

   1) AssertionError: expected false to be truthy

      Browser: Safari 13.0.4 / macOS 10.15.2

          9 |    .ok();
         10 |
         11 |  await t
         12 |    .click(Selector('[data-testid="member_landing_page_inline_contribute_button"]'), { speed: 0.3 })
         13 |    .expect(Selector('[data-testid="member_payment_form"]').visible)
       > 14 |    .ok();
         15 |
         16 |  await t
         17 |    .click(Selector('[data-testid="payment-option-button-creditCard'))
         18 |    .expect(Selector('.iframe-form-element').visible)
         19 |    .ok();

         at <anonymous> (/Users/testuser/Desktop/skorkin/4793.js:14:6)



 1/1 failed (16s)

 --

 Running tests in:
 - Firefox 73.0 / macOS 10.15

 Join Membership with credit card
 ✖ Guest user clicks contribute directly

   1) AssertionError: expected false to be truthy

      Browser: Firefox 73.0 / macOS 10.15

          9 |    .ok();
         10 |
         11 |  await t
         12 |    .click(Selector('[data-testid="member_landing_page_inline_contribute_button"]'), { speed: 0.3 })
         13 |    .expect(Selector('[data-testid="member_payment_form"]').visible)
       > 14 |    .ok();
         15 |
         16 |  await t
         17 |    .click(Selector('[data-testid="payment-option-button-creditCard'))
         18 |    .expect(Selector('.iframe-form-element').visible)
         19 |    .ok();

         at <anonymous> (/Users/testuser/Desktop/skorkin/4793.js:14:6)



 1/1 failed (21s)
```

**Comment by rob4629** [comment] 2020-02-27 15:36
Hey, can you try again please? We had some issues with that page at the start of the week, which have now been resolved.

(I've just re-ran the tests and confirmed it runs to completion, with no setup steps required)

**Comment by rob4629** [comment] 2020-02-27 16:25
If that still isn't working, you could try to use this instead

```
await t
    .navigateTo('s/member?country_code=US&lang=en-US')
...
```

**Comment by Farfurix** [comment] 2020-03-02 07:49
@rob4629 

Hello,

I was able to reproduce it. There is no `t.typeText(Selector('input[name="cardnumber"]'), '1234123412341234', { replace: true })` action result in the `input` element (Safari browser). We will examine it and check for a suitable solution.

**For the team.**
Test:
```js
import { t, Selector } from 'testcafe';

fixture('Join Membership with credit card').page('https://www.change.org/');

test('Guest user clicks contribute directly', async () => {
    await t
        .navigateTo('s/member?country_code=US&lang=en-US')
        .expect(Selector('[data-testid="member_landing_page_inline_contribute_button"]').visible)
        .ok();

    await t
        .click(Selector('[data-testid="member_landing_page_inline_contribute_button"]'), { speed: 0.3 })
        .expect(Selector('[data-testid="member_payment_form"]').visible)
        .ok();

    await t
        .click(Selector('[data-testid="payment-option-button-creditCard'))
        .expect(Selector('.iframe-form-element').visible)
        .ok();

    const emailAddressInput = Selector('[data-testid="input_email"]').filterVisible();
    const confirmationEmailInput = Selector('[data-testid="input_confirmation_email"]').filterVisible();
    const firstNameInput = Selector('[data-testid="input_first_name"]');
    const lastNameInput = Selector('[data-testid="input_last_name"]');

    await t
        .typeText(emailAddressInput, 'email@email.com')
        .typeText(confirmationEmailInput, 'email@email.com')
        .typeText(firstNameInput, 'Your')
        .typeText(lastNameInput, 'Name');

    await t
        .switchToIframe(Selector('[data-testid="credit-card-number"] iframe'))
        .typeText(Selector('input[name="cardnumber"]'), '1234123412341234', { replace: true })
        .expect(Selector('input[name="cardnumber"]').value)
        .eql('1234 1234 1234 1234')
        .switchToMainWindow();
});

```

Command:
```
testcafe remote test.js --hostname XXX.XX.XX.XXX --ports 1337,1338 -e
```
Result:
```
Connecting 1 remote browser(s)...
Navigate to the following URL from each remote browser.
Connect URL: http://172.22.14.134:1337/browser/connect
CONNECTED Safari 13.0.4 / macOS 10.15.2
 Running tests in:
 - Safari 13.0.4 / macOS 10.15.2

 Join Membership with credit card
 × Guest user clicks contribute directly

   1) AssertionError: expected '' to deeply equal '1234 1234 1234 1234'

      Browser: Safari 13.0.4 / macOS 10.15.2

         31 |
         32 |    await t
         33 |        .switchToIframe(Selector('[data-testid="credit-card-number"] iframe'))
         34 |        .typeText(Selector('input[name="cardnumber"]'), '1234123412341234', { replace: true })
         35 |        .expect(Selector('input[name="cardnumber"]').value)
       > 36 |        .eql('1234 1234 1234 1234')
         37 |        .switchToMainWindow();
         38 |});
         39 |

         at <anonymous> (d:\tst\i4793\test.js:36:10)



 1/1 failed (20s)
```

**Comment by rob4629** [comment] 2020-03-20 17:43
Just wondering if [this bug](https://github.com/DevExpress/testcafe/issues/4851) is a duplicate, or whether the work will be carried out under it

**Comment by AlexanderMoiseev** [comment] 2020-03-23 12:37
You are right, we've marked it as a duplicate. Please continue to follow this issue to stay tuned

**Comment by TamerNabil** [comment] 2020-04-23 09:39
any updates regarding this issue ?

**Comment by SergeyShurygin** [comment] 2020-04-23 14:52
No updates yet. Once we get any results, we will post them here.

**Comment by wjcheng1** [comment] 2020-04-25 06:08
i've also encountered this issue, but using safari 12 seems to work fine.

**Comment by Dmitry-Ostashev** [comment] 2020-04-27 13:33
@wjcheng1 Thank you for clarification.

**Comment by rob4629** [comment] 2020-04-30 18:42
Using 12.1 also resolved the issue for me, however it would still be nice to be able to test the latest version as part of our regression runs

**Comment by Mmallineni** [comment] 2020-07-15 21:52
SendKeys (Selenium) to thirdparty iframe works fine in Safari 12.1 on Mac but doesn't work on Iphone, iOS 13.2. Can someone help me on this ?

**Comment by alexey-lin** [comment] 2020-07-17 14:45
@Mmallineni, as I've just answered you in another thread, no, we cannot help with Selenium.

**Comment by shyedhu** [comment] 2020-07-20 21:50
Hi, I'm also facing same issue on safari browser v13.1.1 in macOS. Do we have further updates or temporary solutions for this issue?

My Environment details:
testcafe version: 1.8.8
node.js version: 10.17.0
browser name and version: Safari 13.1.1 
platform and version: macOS 10.14.5

**Comment by AlexKamaev** [comment] 2020-07-21 08:51
No updates yet. Once we get any results, we will share them here. Currently, there is no workaround except for using v12.1 of Safari.

**Comment by shyedhu** [comment] 2020-08-11 17:28
@AlexKamaev I found temporary solution on safari v13.1.1 in local machine only. In fact it was working fine if we try below the steps manually 

Just enable the developer menu from Preferences >> Advanced, and select "Disable Cross-Origin Restrictions" from the develop menu.

**Comment by shyedhu** [comment] 2020-08-11 17:30
@AlexKamaev is there any way to set up "Disable Cross-Origin Restrictions" on safari browser through testcafe ?

**Comment by AndreyBelym** [comment] 2020-08-12 08:18
It is a Safari security option, so it cannot be enabled or disabled with automation tools, including TestCafe.

**Comment by puneetpunj** [comment] 2020-08-26 04:48
> @AlexKamaev I found temporary solution on safari v13.1.1 in local machine only. In fact it was working fine if we try below the steps manually
> 
> Just enable the developer menu from Preferences >> Advanced, and select "Disable Cross-Origin Restrictions" from the develop menu.

This option didn't work for me, I am on safari 13.1.2. Any update on this issue? I need to decide between testcafe and other tool based on this issue's resolution.

**Comment by miherlosev** [comment] 2020-08-26 08:12
Guys
 
We will work on it in one of the nearest sprints. At present, the problem is not fixed yet.

**Comment by shyedhu** [comment] 2020-08-26 18:57
Hi @miherlosev Thank you for the update !  we are also blocked few E2E automation tests on safari v13.1.1  browser only via testcafe. Please help us to push the fix as soon as possible . Thanks again for your good support !

**Comment by Ogurecher** [comment] 2020-09-04 13:08
Thank you all for your patience. We've found a workaround you can apply to fix this issue while we're working on it.
You can focus the iframe by clicking it or by inserting the following code before calling `switchToIframe()`:

```js
const iframe = Selector('[data-testid="credit-card-number"] iframe');
await t.eval(() => iframe().focus(), {dependencies: { iframe }});
```

**Comment by puneetpunj** [comment] 2020-09-06 23:05
Thanks @Ogurecher. For me, t.click(iframe) worked.

**Comment by norhak** [comment] 2020-09-07 06:27
Thanks for the update. To click in the iframe solved it.

Regards
Håkan

Den mån 7 sep. 2020 kl 01:05 skrev Puneet Punj <notifications@github.com>:

**Comment by shyedhu** [comment] 2020-09-07 15:45
Thank You @Ogurecher , It works good on safari v13.1.1 and later version also after I inserted the following code before calling switchToIframe(). Thanks again for your good support on this issue !!!

```
const iframe = Selector('iframe_locator');
await t.eval(() => iframe().focus(), {dependencies: { iframe }});
```

**Closed** 2020-10-05 08:42 UTC
Labels: BROWSER: Safari, FREQUENCY: level 2, SYSTEM: automations, TYPE: bug
