### ISSUE TITLE
Testcafe crashes with a js error when testing an app with a web worker implemented as a module

### ISSUE THREAD

**Issue by JasonRammoray** [DevExpress/testcafe#6836] opened 2022-01-25 20:43 UTC
### What is your Scenario?

Testcafe should work without crashes when testing an app which uses a web worker as a module.
A simplest example to that would be creating a worker (of module type) in the application's main module.
See steps below for more details.

### What is the Current behavior?

Testcafe crashes with the following JavaScript error:
```
1) A JavaScript error occurred on "http://localhost:3000/".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set
      the "skipJsErrors" configuration file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new
      issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module
      scripts don't support importScripts().
          No stack trace available
```

### What is the Expected behavior?

A test comes up green, and TestCafe doesn't crash

### What is your public website URL? (or attach your complete example)

[testcafe_module_worker_issue-1.0.0.zip](https://github.com/DevExpress/testcafe/files/7936999/testcafe_module_worker_issue-1.0.0.zip)

### What is your TestCafe test code?
```typescript
import {Selector} from 'testcafe';

fixture('Test')
.beforeEach(t => t.navigateTo('http://localhost:3000/'));

test('module web worker should be supported', async t => {
  const text = await Selector('body p').textContent;
  await t.expect(text).eql('Some content which is irrelevant for the purpose of this demo');
});
```

### Your complete configuration file

No configuration file has been used in the attached demo.

### Your complete test report

 Running tests in:
 - Chrome 97.0.4692.99 / macOS 10.15.7

 Test
 ✖ module web worker should be supported

   1) A JavaScript error occurred on "http://localhost:3000/".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set
      the "skipJsErrors" configuration file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new
      issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module
      scripts don't support importScripts().
          No stack trace available

      Browser: Chrome 97.0.4692.99 / macOS 10.15.7

 1/1 failed (0s)

### Steps to Reproduce

1. Unzip the attached demo (`testcafe_module_worker_issue-1.0.0.tgz`)
2. Install the packages (`npm i`)
3. Run a web server (`npm run start-server`)
4. Run a sample e2e test (`npm run e2e`)

### TestCafe version

1.18.2

### Node.js version

v14.16.1

### Command-line arguments

testcafe chrome main.ts

### Browser name(s) and version(s)

Chrome 97.0.4692.99

### Platform(s) and version(s)

macOS 12.1 (21C52)

**Comment by AlexKamaev** [comment] 2022-01-27 08:13
Thank you for sharing the example with us. I was able to reproduce the issue. Please follow this ticket to track our progress.

**Comment by val1984** [comment] 2022-05-03 11:25
I had the same issue with an app using a webworker with Vite.js.
The working solution is as follows:
```typescript
import MyWorker from './Workers/index.js?worker&inline';
const worker = new MyWorker({ type: 'classic' });
```
The worker wasn't working with testcafe until `&inline` was added to the import and the worker is not imported as a module nor as a different file as a result but it works.

**Comment by miherlosev** [comment] 2022-05-05 06:13
Hi @val1984 

Thank you for the shared information.

**Comment by GlacialBoy** [comment] 2022-05-23 09:16
Hello, news on this Ticket? 
I have this issue with Vite.js but in my I case putting the worker inline is not really a viable option, thanks!

**Comment by Artem-Babich** [comment] 2023-04-13 06:29
We will close this issue since it is fixed in the [Native Automation mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode). Please try the native automation mode in your tests.
Feel free to reopen the issue if you need a fix for the other browsers or you cannot use Native Automation for some reason.

**Comment by aleks-pro** [comment] 2023-05-11 06:14
Hello Imexo ,

> Native automation mode seems to slow down the tests that much, that the most of them fail due to timeouts (Using Chrome in WSL2).

This sounds strange. In most cases, the Native automation mode should improve test speed execution. Could you please create a separate issue with a project sample using which we can reproduce the described behavior? It will help us improve the Native automation mode

> Additionally it does only support chromium browsers, but I also need to test WebKit and FF. So that is not viable solution to me

I'll reopen the issue. We will process it in a regular manner.

**Closed** 2023-06-04 08:10 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, BROWSER: Firefox, BROWSER: iOS/Safari, STATE: Need clarification, FREQUENCY: level 1, STATE: possibly fixed in native automation
