### ISSUE TITLE
TestCafe freezes after launching page with long URL

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3679] opened 2019-04-12 02:15 UTC
### What is your Test Scenario?

Try to launch this long page URL using TestCafe
`http://chart.apis.google.com/chart?chs=500x500&chma=0,0,100,100&cht=p&chco=FF0000%2CFFFF00%7CFF8000%2C00FF00%7C00FF00%2C0000FF&chd=t%3A122%2C42%2C17%2C10%2C8%2C7%2C7%2C7%2C7%2C6%2C6%2C6%2C6%2C5%2C5&chl=122%7C42%7C17%7C10%7C8%7C7%7C7%7C7%7C7%7C6%7C6%7C6%7C6%7C5%7C5&chdl=android%7Cjava%7Cstack-trace%7Cbroadcastreceiver%7Candroid-ndk%7Cuser-agent%7Candroid-webview%7Cwebview%7Cbackground%7Cmultithreading%7Candroid-source%7Csms%7Cadb%7Csollections%7Cactivity|Chart'`
 
### What is the Current behavior?

TestCafe freezes after launching long page URL
 
### What is the Expected behavior?

TestCafe should not freeze
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `Long URL`
	.page `http://chart.apis.google.com/chart?chs=500x500&chma=0,0,100,100&cht=p&chco=FF0000%2CFFFF00%7CFF8000%2C00FF00%7C00FF00%2C0000FF&chd=t%3A122%2C42%2C17%2C10%2C8%2C7%2C7%2C7%2C7%2C6%2C6%2C6%2C6%2C5%2C5&chl=122%7C42%7C17%7C10%7C8%7C7%7C7%7C7%7C7%7C6%7C6%7C6%7C6%7C5%7C5&chdl=android%7Cjava%7Cstack-trace%7Cbroadcastreceiver%7Candroid-ndk%7Cuser-agent%7Candroid-webview%7Cwebview%7Cbackground%7Cmultithreading%7Candroid-source%7Csms%7Cadb%7Csollections%7Cactivity|Chart`;

test('My first test', async t => {
	await t.navigateTo('https://www.google.com');
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Run the provided sample test code
 
### Your Environment details:
 
* testcafe version:                    1.1.2 (latest)
* node.js version:                     v8.11.1
* command-line arguments:   testcafe chrome test.js
* browser name and version:  Chrome 73.0.3683
* platform and version:           Mac OS X 10.14.2
* other:

**Comment by Farfurix** [comment] 2019-04-12 12:42
@sijosyn 

Hello.

I've reproduced it under Windows 10 / Chrome 73.0.3683, Firefox 66.0.0 / testcafe@1.1.2. Our team will research it and check for a suitable solution.

**Comment by miherlosev** [comment] 2019-04-12 13:30
@sijosyn

It's duplicate of the #1471
At present, TestCafe cannot operate with non-HTML pages.

**Closed by miherlosev** 2019-04-12 13:30 UTC
Labels: TYPE: bug
