### ISSUE TITLE
Pass optional base URL to cli instead of fixing page URL in fixtures

### ISSUE THREAD

**Issue by ciarancourtney** [DevExpress/testcafe#2976] opened 2018-10-16 09:47 UTC
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Page URL is hardcoded in fixtures

### What is the expected behavior?

Pass in a `url` parameter to CLI

    testcafe chrome my-tests/**/*.js --url=http://localhost:4200

So a dev can set `localhost:4200`, CI can use `staging.mycomp.lan/app/` and so on

And explicit overrides in fixtures would take precedent, others would be treated as relative

```js
fixture `Login`
  .page `/login`;
```

**Comment by AndreyBelym** [comment] 2018-10-16 09:52
Please note that relative paths are used to specify test pages in the file system: [Specifying the Start Webpage](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-the-start-webpage).

Except using resolving relative URLs using the global one, this proposal is a duplicate of https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-the-start-webpage

**Closed by AndreyBelym** 2018-10-16 09:52 UTC
