### ISSUE TITLE
Configuration passed to run() not being used

### ISSUE THREAD

**Issue by naldertown** [DevExpress/testcafe#6383] opened 2021-07-14 13:56 UTC
### What is your Test Scenario?
When passing configuration values such as debugOnFail or quarantineMode to runner.run() the config does not appear to be applied. This was working previous to upgrading to version 1.15.0.
 
### What is the Current behavior?
The config is not used in the test run - however it is used if specified in .testcaferc.json. We cannot use this file for all config however as we have varying requirements for each group of test fixtures we run.
 
### What is the Expected behavior?
The config is applied to the test run as per the documentation here: https://testcafe.io/documentation/402655/reference/testcafe-api/runner/run
 
### What is your web application and your TestCafe test code?
I cannot share a link - but the application is built using React (16).
 
Example of a runner below...

The config properties are all defined in a central config file depending on the specific test run we are using. e.g. quarantineMode and debugOnFail.

```
await runner
            .src(`./testcafe/fixtures/${src}/**/*.js`)
            .startApp(startApp)
            .browsers(browsers)
            .concurrency(concurrency)
            .reporter([
                {
                    name: 'spec',
                },
                {
                    name: 'json',
                    output: `testcafe/reports/${getSourceSlug(src)}.json`,
                },
            ])
            .run({
                quarantineMode,
                debugOnFail,
            });

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "appInitDelay": 5000,
    "assertionTimeout": 20000,
    "selectorTimeout": 20000,
    "browserInitTimeout": 180000,
    "skipJsErrors": true,
    "skipUncaughtErrors": true,
    "color": true,
    "screenshots": {
        "takeOnFails": true,
        "path": "testcafe/reports/screenshots"
    },
    "clientScripts": [
        {
            "module": "@testing-library/dom/dist/@testing-library/dom.umd.js"
        }
    ]
}
```
</details>

### Steps to Reproduce:

1. Create a runner using the JavaScript API
3. Execute the runner with config at the API level
4. See that the config is not applied during the test run
 
### Your Environment details:
 
* testcafe version:                  1.15.0
* node.js version:                   12.21.0
* command-line arguments:  n/a
* browser name and version: Chrome 91
* platform and version:          Linux/Mac
* other:                                   Same effect when run locally or in CI

**Comment by Farfurix** [comment] 2021-07-15 08:44
@naldertown 

Hello,

I tried to reproduce this issue, but the usage scenario works as expected (run options enable `quarantineMode` and `debugOnFail`). My setup was macOS Big Sur, Node.js 12.21.0, TestCafe v1.15.0. Could you please modify my runner code to reproduce the issue?

index.js
```js
const createTestCafe = require('testcafe');

(async () => {
    const testcafe = await createTestCafe('localhost', 1337, 1338);

    const quarantineMode = true;
    const debugOnFail    = true;

    try {
        const runner = testcafe.createRunner();

        const failedCount = await runner
            .src(['test.js'])
            .browsers(['safari'])
            .run({
                quarantineMode,
                debugOnFail
            });

        console.log('Tests failed: ' + failedCount);
    }
    finally {
        await testcafe.close();
    }
})();
```
test.js
```js
fixture `Fixture`
    .page('https://google.com');

test('test', async t => {
    await t.expect(false).ok();
});
```

**Comment by naldertown** [comment] 2021-07-15 11:35
@Farfurix Odd. I have just run the exact test runner that you have here (substituting chrome for safari) and I get the same result on my machine:
```
Running tests in:
 - Chrome 91.0.4472.114 / Linux 0.0

 Fixture
 ✖ test (screenshots:
 /media/naldertown/f4235172-7e2c-461e-adbe-bfe01276f79e/Development/reassure-portal-web-app/testcafe/reports/screenshots/2021-07-15_12-31-42/test-1/Chrome_91.0.4472.114_Linux_0.0/errors/1.png)

   1) AssertionError: expected false to be truthy

      Browser: Chrome 91.0.4472.114 / Linux 0.0
      Screenshot:

   /media/naldertown/f4235172-7e2c-461e-adbe-bfe01276f79e/Development/reassure-portal-web-app/testcafe/reports/screenshots/2021-07-15_12-31-42/test-1/Chrome_91.0.4472.114_Linux_0.0/errors/1.png

         1 |fixture `Fixture`
         2 |    .page('https://google.com');
         3 |
         4 |test('test', async t => {
       > 5 |    await t.expect(false).ok();
         6 |});

         at <anonymous>

   (/media/naldertown/f4235172-7e2c-461e-adbe-bfe01276f79e/Development/reassure-portal-web-app/testcafe/test-runner/test.js:5:27)
         at asyncGeneratorStep

   (/media/naldertown/f4235172-7e2c-461e-adbe-bfe01276f79e/Development/reassure-portal-web-app/testcafe/test-runner/test.js:1:114)
         at _next

   (/media/naldertown/f4235172-7e2c-461e-adbe-bfe01276f79e/Development/reassure-portal-web-app/testcafe/test-runner/test.js:1:452)
         at <anonymous>

   (/media/naldertown/f4235172-7e2c-461e-adbe-bfe01276f79e/Development/reassure-portal-web-app/testcafe/test-runner/test.js:1:617)
         at <anonymous>

   (/media/naldertown/f4235172-7e2c-461e-adbe-bfe01276f79e/Development/reassure-portal-web-app/testcafe/test-runner/test.js:1:358)
         at <anonymous>
      (/media/naldertown/f4235172-7e2c-461e-adbe-bfe01276f79e/Development/reassure-portal-web-app/testcafe/test-runner/test.js:4:5)



 1/1 failed (2s)
Tests failed: 1
```

Here's the runner:

```
const createTestCafe = require('testcafe');

(async () => {
    const testcafe = await createTestCafe('localhost', 1337, 1338);

    const quarantineMode = true;
    const debugOnFail    = true;

    try {
        const runner = testcafe.createRunner();

        const failedCount = await runner
            .src(['./testcafe/test-runner/test.js'])
            .browsers(['chrome'])
            .run({
                quarantineMode,
                debugOnFail
            });

        console.log('Tests failed: ' + failedCount);
    }
    finally {
        await testcafe.close();
    }
})();
```
After it fails the browser closes - no quarantine mode and no debug on fail.

**Comment by Farfurix** [comment] 2021-07-16 08:09
@naldertown 

Hello,

Try to run my usage scenario with a new project (install the latest TestCafe version locally).
**index.html**:
```js
const createTestCafe = require('testcafe');

(async () => {
    const testcafe = await createTestCafe('localhost', 1337, 1338);

    const quarantineMode = true;
    const debugOnFail    = true;

    try {
        const runner = testcafe.createRunner();

        const failedCount = await runner
            .src(['test.js'])
            .browsers(['firefox']) // or another installed browser
            .run({
                quarantineMode,
                debugOnFail
            });

        console.log('Tests failed: ' + failedCount);
    }
    finally {
        await testcafe.close();
    }
})();
```
**test.js**:
```js
fixture `Fixture`
    .page('https://google.com');

test('test', async t => {
    await t.expect(false).ok();
});
```

In this example, TestCafe stops on an assertion failure (`debugOnFail`) and tries to run a test three times (`quarantineMode`). You should get the same result:
https://user-images.githubusercontent.com/30019338/125910204-7e8b9d97-1cc7-4733-b108-4be92c24bbf6.mp4

**Comment by naldertown** [comment] 2021-07-16 08:17
@Farfurix I have just tried the test again after downgrading to 1.14.0 and the tests run as expected - debugging on fail and with quarantine mode. Upgrading back to 1.15.0 and re-running the tests reproduces the issues for me.

**Comment by VasilyStrelyaev** [comment] 2021-07-19 14:28
As we are unable to reproduce the problematic behavior with the samples we have so far, I'm closing this issue. Feel free to reopen it if you can prepare an example that precisely replicates your setup details.

**Closed by VasilyStrelyaev** 2021-07-19 14:28 UTC
Labels: STATE: Need response
