### ISSUE TITLE
Elements beneath div with position: fixed aren't found

### ISSUE THREAD

**Issue by Woppe** [DevExpress/testcafe#2040] opened 2018-01-11 10:51 UTC
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
Elements beneath (further down on page than) div with position: fixed aren't found

### What is the expected behavior?
Elements beneath that div should be found just like any other element

### How would you reproduce the current behavior (if this is a bug)?
Attach a div to bottom of window with position: fixed and let contents on on page exceeds the height of the window. Select an element in the DOM with testscafe that is outside the viewport such that the page needs to be scrolled to bring element into view.

#### Provide the test code and the tested page URL (if applicable)
Bug found while testing internal webpage, cannot provide URL

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.5
* node.js version: v8.9.1

**Comment by AndreyBelym** [comment] 2018-01-12 09:24
Hello @Woppe! Than you for the feedback, but it looks like a duplicate of https://github.com/DevExpress/testcafe/issues/1057, so I'm closing this issue in favor of #1057. Feel free to reopen it, it you think that it is different from #1057.

**Closed by AndreyBelym** 2018-01-12 09:24 UTC
