### ISSUE TITLE
Startup time performance decreases when having a large number of suites and tests

### ISSUE THREAD

**Issue by sikamikanico** [DevExpress/testcafe#5844] opened 2020-12-30 16:00 UTC
### What is your Test Scenario?
Currently handling a testcafe project with approximately 1100 tests and the startup time is getting worse as we continue to add more tests. At the time of this report it is taking around 15 minutes for the execution to start. Once the tests start the execution is fluent and has not changed with the amount of tests we add.

**Some findings:**

- If we use test meta to filter and run just one test with the other 1100 on the repo it takes around 15 minutes for the execution to start. We have to manually modify the _node_modules/testcafe/lib/runner/browser-set.js_ timeouts otherwise we always get a failure.
- If we remove half of the suite from the source code and we run just one test using test meta, the starting time is around 6 minutes.
- If we remove almost all the tests and leave just 8 of them it takes around 7 seconds for the execution to start. We have tried multiple variations using the fastest tests (around 45 seconds) and the longest ones (4 minutes), same result. The amount of time it takes for the execution to start is always less than 10 seconds.
- We are using POM so the classes storing the locators and methods are not inside the test code. During the analysis we only removed the tests, the POM classes were not touched neither modified.
- Same result happens on Electron (8.3.3) and Chrome

Is there a way we can debug the testcafe startup process to identify where we are experiencing the performance hit? Have you experienced something similar?

### What is the Current behavior?
As we increase the amount of tests, it takes longer for the execution to start.

### What is the Expected behavior?
Not sure :(

```
### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    12.18.2
* command-line arguments:  "testcafe electron tests/common/**/*.ts  --test-meta suite=awsomeMeta --reporter-app-name='%npm_package_name%' --reporter-app-version='%npm_package_version%'"
* browser name and version: Electron, Chrome
* platform and version:          Windows 10
* electron-provider:               "testcafe-browser-provider-electron": "0.0.16",

**Comment by wentwrong** [comment] 2020-12-31 08:59
Thank you for such an extensive report.

I assume this happens due to long compilation of the test suite that TestCafe performs at the start. We worked on enhancing the error message so that it provides more information and helps identify such performance hits in the context of this thread: [Improve the message shown by "Unable to establish connection" error](https://github.com/DevExpress/testcafe/pull/5720). This PR adds information about the exact time of compilation if it takes too long and allows you to specify the browser initialization timeout using the "--browser-init-timeout" flag (the same timeout that you were forced to modify manually). Although the pull request hasn't been merged yet and the timeout is still not reflected in the documentation, you can try the debug build of TestCafe I created for you. Install it by running the following command:
```
npm install https://git.io/JLQ2k
```

After that, run your tests. The information in the error message will let you understand if the long compilation time is the performance hit you are experiencing.

Also, the cause could be that tests are organized inefficiently (especially if huge page object models are involved). Please navigate to the following thread: [Error on executing more than 150 testcases in a suite](https://github.com/DevExpress/testcafe/issues/4054). It contains some pieces of advice on how to organize your tests. These recommendation can help you optimize test execution time.

If it doesn't work for you, could you please share your tests with us? You can send them to support@devexpress.com.

**Comment by sikamikanico** [comment] 2021-01-05 15:38
Thanks @wentwrong for your quick response and the debug build. We will be testing it this week and I will let you know the results. The MR looks like a great addition, we have faced that exception before and to be honest, I never would have guessed it happened because of compilation time.

**Comment by AlexSkorkin** [comment] 2021-01-06 07:26
We look forward to hearing from you.

**Closed** 2021-01-16 08:11 UTC
Labels: STATE: Need clarification
