### ISSUE TITLE
allow to run test in user's default browser

### ISSUE THREAD

**Issue by milahu** [DevExpress/testcafe#5510] opened 2020-09-07 18:11 UTC
its hard to get the name of the default browser ([55 KB](https://bundlephobia.com/result?p=default-browser@2.0.1))
but its much easier to just open the default browser ([2.4 KB](https://bundlephobia.com/result?p=open@7.2.1))

so there should be a way to tell testcafe
'run this test in user his default browser'

im suggesting the special browser names
`default` and `default:headless`

when the default browser cant do headless
then run without headless = headmore : P

**Comment by miherlosev** [comment] 2020-09-08 05:43
Duplicate of https://github.com/DevExpress/testcafe/issues/2518.

**Closed by miherlosev** 2020-09-08 05:43 UTC
Labels: STATE: Need response

**Comment by milahu** [comment] 2020-09-09 21:30
> its hard to get the name of the default browser ([55 KB](https://bundlephobia.com/result?p=default-browser@2.0.1))

good news, on darwin/mac/apple this can be done in 400 bytes of code

```js
// darwin os: get default browser name
// use the `plutil` tool https://www.manpagez.com/man/1/plutil/
const child_process = require('child_process');
const getDefaultBrowserOnDarwin = () => (
	JSON.parse(child_process.execSync(
		"plutil -convert json -o - ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist",
		{maxBuffer: 1/0, encoding: "utf-8"}
	)).LSHandlers.filter(h => h.LSHandlerURLScheme == "http")
	.map(h => h.LSHandlerRoleAll).filter(Boolean)[0]
	|| 'com.apple.Safari'
);
```
tested by two apple users - im running linux

so we can have a lightweight browser-guessing-logic like

1. if the user's default browser is compatible with testcafe, use it
2. if not, fall back to one of supported and installed browsers
3. if no browser was found, throw error

**Comment by wentwrong** [comment] 2020-09-10 08:39
Thank you for sharing your findings, we'll take them into account. This feature is not easy to implement correctly as it deals with many edge cases. And even harder to make it cross-platform compatible.

**Comment by milahu** [comment] 2020-09-10 09:35
here is the full version

```js
// get-default-browser-name.js
// size is 1337 bytes
// license is CC0-1.0

// usage
// const g = require('./get-default-browser-name.js');
// const b = g();
// const r = g({raw:1});

const
c=require('child_process'),
s=require('os'),
x={maxBuffer:1/0, encoding:'utf-8'};

module.exports=(a)=>([[
[/(linux|freebsd)/,()=>(
	[c.execSync('xdg-mime query default text/html',x)]
	.map(r=>a.raw?r:r.match(/^.*?-(.*)-.*?/)[1])[0])],
[/darwin/,()=>(
	JSON.parse(c.execSync('plutil -convert json -o - '+
		'~/Library/Preferences/com.apple.LaunchServices/'+
		'com.apple.launchservices.secure.plist',x))
	.LSHandlers.filter(h => h.LSHandlerURLScheme == 'http')
	.map(h => h.LSHandlerRoleAll).filter(Boolean)[0]
	|| 'com.apple.Safari')],
[/win32/,()=>(
	[s.release().slice(0,3)=='10.'
	? ['HKEY_CURRENT_USER/SOFTWARE/Microsoft/Windows/Shell/'+
		'Associations/URLAssociations/http/UserChoice',
		'ProgId',/.* {4}(.*?)\r/,/^(.*)(\.HTTP|URL|HTML)/,'edge']
	: ['HKCU/Software/Clients/StartMenuInternet',
		'REG_SZ',/REG_SZ  "(.*?)"/,/.*\\(.*)\..*?$/,'ie']
	].map(([p,k,e,f,d])=>c.execSync(
		`reg query ${p.replace(/\//g,'\\')} `+
		// TODO remove findstr?
		`| findstr ${k}`,x).match(e)).map(r=>r?r[1]:'')
	.map(r=>a.raw?r:[r.match(f)].map(r=>r?r[1]:d)[0])[0])],
].find(x=>s.platform().match(x[0]))
[1]().trim()].map(r=>a.raw?r:r.toLowerCase())[0]
)
```
tested only on linux so far
the darwin code should work too
the windows code is ported from [jakub-g/x-default-browser](https://github.com/jakub-g/x-default-browser)

x-default-browser does the same job in a 500 KB bundle
so thats a 99.76% decrease in bundle size : D

**Comment by AndreyBelym** [comment] 2020-09-11 08:06
Thank you for your research and your npm module. I think it's a good base for a new browser provider. You can try to implement a browser provider plugin as it is described here: [Browser Provider Plugin](https://devexpress.github.io/testcafe/documentation/guides/extend-testcafe/browser-provider-plugin.html). When it's done, we can add it to [https://github.com/DevExpress/testcafe#plugins](https://github.com/DevExpress/testcafe#plugins). If it gets popular, we can consider adding it to pre-installed browser providers.
