### ISSUE TITLE
Getting `error Command failed with exit code 1.` in random while executing the tests.

### ISSUE THREAD

**Issue by naresh-hopin** [DevExpress/testcafe#6804] opened 2021-12-27 15:02 UTC
### What is your Scenario?

I am running a set of tests within a folder. These tests contain,
* UI clicks
* UI navigation
* File upload scenario
* Assertions

No other special scenarios tested in this suite. 

### What is the Current behavior?

All the tests are getting passed but then I am getting the error as `error Command failed with exit code 1.`

```
testcafe -q attemptLimit=2,successThreshold=1 --test-meta QUARANTINED=false src/tests/ -r spec,allure-extended,junit:reports/tc-report.xml -c 2
The "src", "reporter", and "filter" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 96.0.4664.45 / Linux 0.0

..
..
..

 5 passed (5m 08s)
 Warnings (1):
 --
  The "src", "reporter", and "filter" options from the configuration file
  will be ignored.
Error: 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

We are not getting a failure report or error log trace to fix our code, just the error code. The main problem is this is not happening on every execution. We are getting this in random.

### What is the Expected behavior?

If there is a failure, we are expecting it to throw what is the failure along with an error trace, so that we can take a look at how to fix the issue.

### What is your public website URL? (or attach your complete example)

As I mentioned earlier, since it's happening at random, we could not get a solid code or public URL to replicate the same. It would be great if we could get a debug build as we got https://github.com/DevExpress/testcafe/issues/4665#issuecomment-579138984 in this issue so that we could use that in our runs and report when we could get this issue in random. 

### What is your TestCafe test code?

Here we are running multiple tests across multiple files. Also If we run the tests individually we couldn't get this issue. So I couldn't decide on which test code to actually put here.

### Your complete configuration file

```
{
  "src": "./src/tests/**/*.js",
  "browsers": [
    "chrome:headless:emulation:width=1366;height=800; --test-type --disable-accelerated-video --disable-accelerated-plugins --disable-accelerated-layers --disable-accelerated-compositing --disable-accelerated-2d-canvas --disable-web-security --allow-running-insecure-content --dev --allow-insecure-localhost --ignore-certificate-errors --disable-dev-shm-usage --disable-gpu --autoplay-policy=no-user-gesture-required --disable-infobars --use-fake-ui-for-media-stream --allow-running-insecure-content --use-fake-device-for-media-stream --use-file-for-fake-video-capture=$PWD/src/support/fixtures/files/jellyfish.y4m --use-file-for-fake-audio-capture=$PWD/src/support/fixtures/files/noise_16.wav"
  ],
  "quarantineMode": {
    "successThreshold": 1,
    "attemptLimit": 2
  },
  "concurrency": 2,
  "ajax-request-timeout": 90000,
  "page-request-timeout": 90000,
  "page-load-timeout": 90000,
  "selectorTimeout": 60000,
  "selector-timeout": 60000,
  "browser-init-timeout": 60000,
  "assertionTimeout": 60000,
  "speed": 0.8,
  "skipJsErrors": true,
  "skipUncaughtErrors": true,
  "hostname": "localhost",
  "screenshots": {
    "path": "./artifacts/screenshots/",
    "takeOnFails": true,
    "pathPattern": "${DATE}/${TEST}_${RUN_ID}.png",
    "fullPage": false
  },
  "reporter": [
    {
      "name": "spec"
    },
    {
      "name": "allure-extended"
    },
    {
      "name": "junit",
      "output": "reports/report.xml"
    }
  ]
}
```

### Steps to Reproduce

* As I mentioned earlier since it's happening at random, we could not get a solid code or public URL to replicate the same. 
* It would be great if we could get a debug build as we got https://github.com/DevExpress/testcafe/issues/4665#issuecomment-579138984 in this issue so that we could use that in our runs and report when we could get this issue in random. 

### TestCafe version

1.17.1

### Node.js version

v14.17.5

### Command-line arguments

testcafe -q attemptLimit=2,successThreshold=1 --test-meta QUARANTINED=false src/tests/ -r spec,allure-extended,junit:reports/tc-report.xml -c 2

### Browser name(s) and version(s)

Chrome 96.0.4664.45

### Platform(s) and version(s)

 Linux 0.0

**Comment by naresh-hopin** [comment] 2021-12-28 07:41
Thanks for the update, we will try and update and then will respond to this thread. 👍

**Comment by naresh-hopin** [comment] 2021-12-28 11:58
Hey Team,

I have updated the version and even then we are seeing this issue happening.  Our recent logs are,

```
 5 passed (5m 31s)
 Warnings (1):
 --
  The "src", "reporter", and "filter" options from the configuration file
  will be ignored.
Error: 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thanks :)

**Comment by naresh-hopin** [comment] 2021-12-28 13:51
A small update, I am getting the following EPIPE error sometimes,

```
 5 passed (7m 03s)
 Warnings (1):
 --
  The "src", "reporter", and "filter" options from the configuration file
  will be ignored.
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:798:11)
    at Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.ondata (internal/streams/readable.js:731:22)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:537:15)
    at addChunk (internal/streams/readable.js:293:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bbutel** [comment] 2021-12-28 16:29
+1 on my side. It happens ramdomly and I don't have a specific use case. 
In my context, runs are done in a docker component.

**Comment by miherlosev** [comment] 2021-12-30 07:32
@naresh-hopin @bbutel 

We still don't have an example that we can run locally. Please, try to prepare it using instructions from this article: [Create a Minimal Working Example When You Submit an Issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue).

**Comment by naresh-hopin** [comment] 2021-12-30 07:40
@miherlosev I am trying to run the tests in debug mode as mentioned on the same website and get the logs. As of now, it's not failing. Will keep this thread updated.

**Comment by naresh-hopin** [comment] 2022-01-07 08:05
A small update: 

After adding `DEBUG=hammerhead:*,testcafe:*` to our scripts we are not seeing this same error so far. We are still monitoring those jobs. Not sure how that could fix the issue apart from capturing the logs.

**Comment by miherlosev** [comment] 2022-01-07 10:53
Hi @naresh-hopin 

Collecting logs sometimes can help find the cause of the issue. In your case, unfortunately, it didn't. 
I will close the issue because we still don't have a simple example that we can run locally. Feel free to reopen this issue if you can share such an example.

**Closed by miherlosev** 2022-01-07 10:53 UTC
Labels: STATE: Need response
