### ISSUE TITLE
Browser hangs when multiple fixtures in one file

### ISSUE THREAD

**Issue by marques-p44** [DevExpress/testcafe#3611] opened 2019-03-27 12:15 UTC
### What is your Test Scenario?

I'm trying to show a demo, and have two fixtures in a single file, with tests that are very basic (expect true to be true).

 
### What is the Current behavior?

 The first fixture runs the tests, then when the 2nd fixture starts, the browser just  hangs and those tests never run. TestCafe eventually just closes.

### What is the Expected behavior?

Both fixtures run successfully.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture('Landing Page - Header').page('https://google.com');
test('should display a Getting Started button in the header', async t => {
  await t.expect(true).ok();
});
test('2', async t => {
  await t.expect(true).ok();
});
test('3', async t => {
  await t.expect(true).ok();
});

fixture('Landing Page - Content').page('https://google.com');
test('should have ...', async t => {
  await t.expect(true).ok();
});
test('should have ...', async t => {
  await t.expect(true).ok();
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Landing Page - Header
 ✓ should display a Getting Started button in the header
 ✓ 2
 ✓ 3

 Landing Page - Content
ERROR The HeadlessChrome 73.0.3683 / Mac OS X 10.14.2 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Create a test file with 2 fixtures
3. run `testcafe chrome:headless `test file name`
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.1.0
* node.js version:   10.15.0
* command-line arguments: testcafe chrome:headless ./my-first-test.spec.ts
* browser name and version: Chrome v73 Headless (or not headless, error happens in both)
* platform and version:  macOS 10.14.2

**Comment by miherlosev** [comment] 2019-03-27 15:23
Hi @marques-p44 

I cannot reproduce the described behavior (see [video](https://www.screencast.com/t/GMJuohXL]).

Please, try to add the `import { Selector } from 'testcafe';` statement in your test file and run the tests again.

**Comment by marques-p44** [comment] 2019-03-28 01:36
Hmm can you try this code:
```js
import { Selector } from 'testcafe';

fixture('Landing Page - Header')
  .page('https://pluralsight.com')
  .before(async ctx => console.log('fixture - before'))
  .beforeEach(async t => {
    console.log('fixture - beforeEach');
  })
  .afterEach(async t => {
    console.log('fixture - afterEach');
  })
  .after(async ctx => console.log('fixture - after'));
test('should display a Getting Started button in the header', async t => {
  await t.expect(true).ok();
})
  .before(async t => console.log('test - before'))
  .after(async t => console.log('test - after'));
test('2', async t => {
  await t.expect(true).ok();
});
test('3', async t => {
  await t.expect(true).ok();
});

fixture('Landing Page - Content').page('https://pluralsight.com');
test('should have ...', async t => {
  await t.expect(true).ok();
});
test('should have ...', async t => {
  await t.expect(true).ok();
});

```
Going from `import 'testcafe'` -> `import {Selector} from 'testcafe'` seems give the same result (test hangs). Does anything in the above code look like it'd cause this error?

**Comment by miherlosev** [comment] 2019-03-28 08:56
I cannot reproduce the problem again.
![image](https://user-images.githubusercontent.com/4133518/55143495-e7848a00-514f-11e9-9428-0cafc0a8d7b3.png)

Could you please share your test file and capture a video how the browser hangs during the test execution?
You can use the [Jing](https://www.techsmith.com/jing-tool.html) tool.

**Comment by marques-p44** [comment] 2019-03-28 11:16
Here's a video of it: https://www.screencast.com/t/fyYnyGVsyKT

**Comment by miherlosev** [comment] 2019-03-28 11:50
Try to put the browser name parameter in quotes. I don't know which type of quotes (single or double) should be used in the `zsh` terminal. So, try both variants.
 
```js
testcafe 'chrome:headless' ./my-first-test.spec.ts
```

**Comment by marques-p44** [comment] 2019-03-28 12:20
Ok I switched the page from pluralsight to `https://google.com`, and it's working fine. I tried switching back to pluralsight URL, and it hangs. I also tried with twitter.com as the page for both fixtures, works fine. Any idea what could be causing that? I tried to run the command with development mode, but don't seen any new output.
```
testcafe 'chrome:headless' ./my-first-test.spec.ts --dev
```

**Comment by AlexKamaev** [comment] 2019-03-29 08:22
I was able to reproduce the issue at `pluralsight`. It seems that the cause of this issue is https://github.com/DevExpress/testcafe-hammerhead/issues/1885. It's already fixed in the `testcafe-hammerhead` repository, however it's not published in the `testcafe` repository yet.
While the fix is not published, please refer to the following discussion https://github.com/DevExpress/testcafe/issues/3438 to see possible workarounds.
In addition, I want to mention that the `testcafe-hammerhead` module with the fix is already published, so you can change its version in your `package.json`.

**Closed by AlexKamaev** 2019-03-29 08:22 UTC
Labels: STATE: Need response

**Comment by marques-p44** [comment] 2019-03-29 14:02
Cool, Thanks @AlexKamaev
