### ISSUE TITLE
TestCafe creates two cursors

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#4220] opened 2019-08-31 07:31 UTC
Hammerhead shadow root is now created for all iframes on the page and it leads to showing two cursor (or maybe more) at the same time.
![image](https://user-images.githubusercontent.com/12034551/64060764-d3025d00-cbd9-11e9-8385-18062b9225c1.png)
To reproduce this behavior use a page with two embedded iframes or use the following test
```js
import { Selector } from 'testcafe';

fixture`local`
    .page`http://dikareva-w10/site`;

test('iframes', async t => {
    await t
        .switchToIframe(Selector('body').find('iframe').nth(1))
        .click(Selector('body').find('input'), {
            caretPos: 21
        })
        .switchToIframe(Selector('body').find('iframe'))
        .click(Selector('body').find('input'), {
            caretPos: 14
        })
        .debug();
});

```
In Studio we hide TestCafe cursor after tests playback finishes and sometimes one of them stays which may confused users during recording (see [the issue](https://github.com/DevExpress/testcafe-studio/issues/2679) for details)

**Comment by miherlosev** [comment] 2019-09-04 10:09
Duplicate of https://github.com/DevExpress/testcafe/issues/3852

**Closed by miherlosev** 2019-09-04 10:09 UTC
Labels: AREA: client, SYSTEM: UI, TYPE: bug
