### ISSUE TITLE
Upgrading to v0.21 broke browserstack

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#2732] opened 2018-08-14 20:26 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When I try to run a test with browserstack I get an error

>  Running tests in:
> - Chrome 55.0.2883 / Mac OS X 10.12.6

> My tests tests
>{ Error: The Chrome 55.0.2883 / Mac OS X 10.12.6 (https://automate.browserstack.com/builds/BUILD_ID) browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
>    at Timeout.heartbeatTimeout.setTimeout [as _onTimeout] (/my-project/node_modules/testcafe/lib/browser/connection/index.js:150:32)
 >  at ontimeout (timers.js:466:11)
 >   at tryOnTimeout (timers.js:304:5)
 >   at Timer.listOnTimeout (timers.js:267:5) constructor: [Function: GeneralError] }

### What is the expected behavior?
I should be able to run tests in browserstack like normal

### How would you reproduce the current behavior (if this is a bug)?
Point testcafe to browserstack with chrome 55 or chrome 30

### Specify your

* operating system: OS X High Sierra
* testcafe version: 0.21.1
* node.js version: 0.9.11

**Comment by AndreyBelym** [comment] 2018-08-15 10:33
Hi @bdwain, we officially support only the latest versions of Google Chrome: [Browser Support](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#officially-supported-browsers). We can't guarantee backward compatibility with outdated browsers in next TestCafe releases. Could you please tell me why you need to support Chrome 55?

**Comment by bdwain** [comment] 2018-08-15 10:46
I have users running on tablets with older versions of chrome (back to 30, not just 55). The tablets cannot be updated to the latest version. 

I understand testcafe can’t directly support all old browsers. That’s why I am using the browserstack plugin to test on old browsers. Browserstack is meant for testing specific browser versions, so I don’t think I’m doing anything out of the ordinary for it. And testcafe has a supported browserstack plugin. BUt the upgrade from testcafe 0.18-0.21 seems to have broken it.

**Comment by AndreyBelym** [comment] 2018-08-15 11:04
TestCafe injects its scripts to tested pages, and these scripts limits browser versions that can be used for testing with TestCafe. It doesn't matter how a browser is started - locally on your machine, or in the Browserstack cloud. TestCafe version requirements stay the same. Browserstack just provides a convenient way to test you site in different browsers without installing them on your machine. It's especially useful in Continuous Integration systems that run tests on Linux servers even with no GUI subsystem installed.

**Comment by bdwain** [comment] 2018-08-15 11:09
I see. Did something related to this change in version 21? Because before that I was able to run tests all the way chrome 30.

**Comment by olingern** [comment] 2018-08-22 04:42
> ERROR The Chrome 69.0.3497 / Windows 10.0.0 (https://saucelabs.com/tests/8f118694cfe843da810b4030fd8e0606) browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

I'm seeing the same issue following the [instructions from the test setup from sauce labs](http://devexpress.github.io/testcafe/documentation/recipes/running-tests-using-travis-ci-and-sauce-labs.html).

The tests run fine, but after the last test -- the test suite fails to close.

I should note that I'm running testcafe from a child node process.

**Comment by bdwain** [comment] 2018-08-23 16:30
Either way, this is a bug. The entire point of browserstack is to run on different browsers. There's no need for it if you're only going to run on the latest version of everything because that's what testcafe does by default.

I can't control what browsers my users visit my site in. It's unreasonable to expect that mobile users will always have the latest versions of their browsers. Some tablets do not allow you to upgrade. That's why I use browserstack. If testcafe advertises support for browserstack, it should work on any browser that browserstack provides. 

I'm happy to help provide any info I can to help diagnose and fix the issue, though I think all you really need to do to reproduce it is to run any test against an older browser in browserstack.

**Comment by bdwain** [comment] 2018-09-17 22:17
@AndreyBelym any update on this? The browserstack plugin is currently useless because it only supports browsers that are already on your computer. I really would like to be able to run e2es against other browser versions, and testcafe's browserstack support was one of the major reasons why i chose it.

**Comment by miherlosev** [comment] 2018-09-27 14:50
Google Chrome automatically updates on customer computers.
It means that the most customers have the latest Google Chrome version on their computers.
This is why, TestCafe supports only the latest version of Google Chrome.
During TestCafe development, we test this tool only in [modern browsers](https://github.com/DevExpress/testcafe/blob/master/Gulpfile.js#L82).
If you need support of outdated browsers, try to use the TestCafe versions that will be released when outdated browsers will be released.

**Closed** 2018-09-27 14:50 UTC
Labels: TYPE: question

**Comment by bdwain** [comment] 2018-09-27 14:56
@miherlosev you forgot about tablets. I want to test on old versions of chrome because my users are on tablets that do not auto upgrade. That is what browserstack is supposed to help with, so if I can't use browserstack with testcafe on older browsers, testcafe does not support browserstack and should not claim they do.

**Comment by miherlosev** [comment] 2018-09-27 15:04
You can use the older `TestCafe` versions with browserstack (0.17.0 and older).

**Comment by bdwain** [comment] 2018-09-27 15:07
That's disappointing. as browserstack support was a key reason for me using testcafe. The documentation should be updated to mention that browserstack support was dropped

**Comment by AndreyBelym** [comment] 2018-09-27 15:27
@bdwain I understand your frustration and dissatisfaction about this problem, but BrowserStack support doesn't mean that we support all browsers available on the platform, You can say that you have Chinese customers with Windows XP and IE6, so TestCafe must support IE6 for declaring BrowserStack support. As I said, in our opinion BrowserStack is a cloud provider for Continuous Integration services and headless machines.

Maintaining backward compatibility is hard, and we've discussed a lot about what we will support and what we won't.

I can see at least two ways to resolve this problem:

1) Most obvious, try to upgrade browsers on your devices. Which Android version do you have on you devices? With Android 6 & newer, you can just install Chrome from the Google Play market. For older Android version, you can try to install Firefox.

2) You can help us fix the issue. I've discovered an issue in `testcafe-hammerhead` that caused the problem: in the older Chrome browser: https://github.com/DevExpress/testcafe/issues/2732, you can fix it and create a Pull Request to the `testcafe-hammerhead` repository.

**Comment by bdwain** [comment] 2018-09-27 15:34
Thank you for taking the time to explain. Unfortunately, the tablets we've given out to our restaurants are on an android version that locked the version of chrome, and we have no easy of of updating all of their devices to be a new android version. 

I would be happy to make a PR to fix the issue. I think you posted the wrong issue link though. #2732 is this issue. I can look into the testcafe hammerhead issue if you point me in the right direction.

**Comment by AndreyBelym** [comment] 2018-09-27 15:52
I've got Chrome 55 working during the debugging session with the following changes:

1) Due to different property descriptors structure in older Chrome browsers, the following code in the [src/client/sandbox/native-methods.js:515](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/native-methods.js#L515) file is invalid:
```js
this.winLocalStorageGetter   = win.Object.getOwnPropertyDescriptor(storagesPropsOwner, 'localStorage').get;
        this.winSessionStorageGetter = win.Object.getOwnPropertyDescriptor(storagesPropsOwner, 'sessionStorage').get;
```

In Chrome 55, `win.Object.getOwnPropertyDescriptor(...)` doesn't return an object with the `get` and `set` properties, the returned object has the `value` and `writable` properties instead. You need to emulate getter e.g. by using an arrow function that returns descriptor's `value` property:
```js
this.winSessionStorageGetter = () => win.Object.getOwnPropertyDescriptor(storagesPropsOwner, 'sessionStorage').value
```
2) Due to the same reason, the code from the [src/client/utils/property-overriding.js#L17](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/property-overriding.js#L17) doesn't work:
```js
const descriptor = nativeMethods.objectGetOwnPropertyDescriptor.call(window.Object, obj, prop);

    if (getter !== null)
        replaceNativeAccessor(descriptor, 'get', getter);
```

You can't mix `get`/`set` and `value`/`writable` structure in the same descriptor, so when the `createOverriddenDescriptor` works in an older browser which returns `value`/`writable` descriptors, creating the `get` property generates an error. The easiest way to tackle the problem is removing the `value` and `writable` properties from descriptors before adding getters and setters to them.

**Comment by bdwain** [comment] 2018-09-27 16:19
Thanks! I will try to look at that when I get a chance.
