### ISSUE TITLE
Remote browser stops on the last page of the test run once task is finished

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#162] opened 2015-11-05 11:40 UTC
If you use remote browser for the testrun via `testcafe remote some-test.js` then test is completed remote just frozes on the last page of the test run. I suppose this happens because we terminate process before remote goes to the idle page. However, I think we should wait till remote rich the idle page and shown disconnection status there.

**Comment by AndreyBelym** [comment] 2015-11-10 13:18
I'm working on it.

**Comment by AndreyBelym** [comment] 2015-11-27 13:52
The issue has become a duplicate of #131.

**Closed by AndreyBelym** 2015-11-27 13:52 UTC
Labels: AREA: client, AREA: server, SYSTEM: browser connection, SYSTEM: UI, TYPE: bug
