### ISSUE TITLE
Native automation mode hangs when visiting certain areas of web app 

### ISSUE THREAD

**Issue by tgrisley** [DevExpress/testcafe#7695] opened 2023-05-11 21:04 UTC
### What is your Scenario?

I am currently investigating the potential enablement of Native Automation mode for my teams suite of tests to increase their speed.  Have come across a blocker on certain parts of the web application when using native mode, attached is a snippet that replicates the issue.

### What is the Current behavior?

It seems that when visiting certain parts of the application (in this case login) with native automation mode enabled TestCafe hangs, eventually throwing an error.

### What is the Expected behavior?
 
TestCafe to continue running and tests to pass as normal. (Our suite runs fine with native automation disabled) 

### What is your public website URL? (or attach your complete example)

https://www.economist.com/

### What is your TestCafe test code?

```
import { Selector } from 'testcafe';

const logIntoYourAccount = Selector('div').withText('Log into your account').nth(2);

fixture`Example`
    .page`https://www.economist.com/`;

test('go to login page', async t => {
    await t.navigateTo('https://myaccount.economist.com/s/login/')
    await t.expect(logIntoYourAccount.exists).ok();
});
```

### Screenshots

<img width="487" alt="Screenshot 2023-05-11 at 21 42 01" src="https://github.com/DevExpress/testcafe/assets/126177701/a682eebe-550d-4ac6-b20d-8325a3e3bc67">

### Steps to Reproduce

1. `testcafe chrome test.js --native-automation`
2. notice that page hangs and test fails
3. `testcafe chrome test.js`
2. notice that test passes with native automation not running

### TestCafe version

2.5.1-rc.1

### Node.js version

v16.20.0

### Command-line arguments

`testcafe chrome test.js --native-automation`
`testcafe chrome test.js `

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

macOS

**Comment by miherlosev** [comment] 2023-05-15 06:33
Hi @tgrisley 

Thank you for the shared example. I've reproduced the issue.

**Comment by miherlosev** [comment] 2023-05-16 03:40
Duplicate of https://github.com/DevExpress/testcafe/issues/7664

**Closed by miherlosev** 2023-05-16 03:40 UTC
Labels: TYPE: bug, SYSTEM: native automation
