### ISSUE TITLE
Client side exception error with latest TestCafe version when running in native automation mode

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#7921] opened 2023-08-03 02:51 UTC
### What is your Scenario?

Would like to load pages without running into a client side exception using version 3.1.0 and native automation

### What is the Current behavior?

Nearly all tests run into the client side exception when using version 3.1.0 and native automation

### What is the Expected behavior?

Tests run without running into a client side exception when using version 3.1.0 and native automation

### What is your public website URL? (or attach your complete example)

www.chegg.com

### What is your TestCafe test code?

```
import { t, Selector } from "testcafe";
const loginUrl = `https://trunk.live.test.cheggnet.com/auth?action=login`;
const emailForSignIn = Selector('input[id*="email"]');
const passForSignin = Selector('input[type="password"]');
const signInButton = Selector("button").withText("Sign in");
const closeButton = Selector('*[aria-label="Cancel"]');

// user log in/log out methods
async function userLogInWithCredentials(
  email: string,
  password: string
): Promise<void> {
  await t.navigateTo(loginUrl);
  await t
    .typeText(emailForSignIn, email, { paste: true })
    .typeText(passForSignin, password, { paste: true })
    .click(signInButton)
    .wait(6000);
  console.log(`Logged in as user: ${email}`);
}

fixture`Script test`
  .meta({
    fixtureID: "f-0001",
  })
  .beforeEach(async (t) => {
    await userLogInWithCredentials(
      "sample_script_user@chegg.com",
      "Password@123@123"
    );
  });

// this test doesn't hang after a sign in attempt
test("My test 2", async (t) => {
  console.log(
    "user able to log in"
  );
  await t.expect(closeButton.visible).ok();
});
```

### Screenshots

<img width="651" alt="Screenshot 2023-08-02 at 6 53 26 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/329f3ce8-6860-4019-91db-4e2819d01d55">

Browser console output: 
```
hammerhead.js:43305 TypeError: Cannot read properties of undefined (reading 'parent')
    at getTopSameDomainWindow (hammerhead.js:3491:33)
    at get (hammerhead.js:19457:32)
    at UploadSandbox._getCurrentInfoManager (hammerhead.js:19489:17)
    at UploadSandbox.getUploadElementValue (hammerhead.js:19535:31)
    at HTMLInputElement.getter [as value] (hammerhead.js:20816:43)
    at react-dom.production.min.js:32:112
    at X (react-dom.production.min.js:33:70)
    at ii (react-dom.production.min.js:208:487)
    at Tu (react-dom.production.min.js:251:81)
    at Lu (react-dom.production.min.js:250:408)
error @ hammerhead.js:43305
ci @ react-dom.production.min.js:216
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
ha @ react-dom.production.min.js:131
yi @ react-dom.production.min.js:220
Fu @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ql @ react-dom.production.min.js:122
Ou @ react-dom.production.min.js:252
bu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ql @ react-dom.production.min.js:122
Yl @ react-dom.production.min.js:123
Kl @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:244
os @ react-dom.production.min.js:289
t.hydrate @ react-dom.production.min.js:295
v.default.createElement.callbacks @ index.js:349
ie @ index.js:488
(anonymous) @ index.js:506
s @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ _async_to_generator.js:23
u @ _async_to_generator.js:12
(anonymous) @ _async_to_generator.js:17
nrWrapper @ ?force-exp-sihp_topics_test_1=control&force-exp-unlimited_paq_test=control:103
r @ ?force-exp-sihp_topics_test_1=control&force-exp-unlimited_paq_test=control:103
(anonymous) @ _async_to_generator.js:9
ce @ index.js:524
ue @ index.js:497
(anonymous) @ index.js:635
s @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ _async_to_generator.js:23
u @ _async_to_generator.js:12
nrWrapper @ ?force-exp-sihp_topics_test_1=control&force-exp-unlimited_paq_test=control:103

hammerhead.js:43305 TypeError: Cannot read properties of undefined (reading 'parent')
    at getTopSameDomainWindow (hammerhead.js:3491:33)
    at get (hammerhead.js:19457:32)
    at UploadSandbox._getCurrentInfoManager (hammerhead.js:19489:17)
    at UploadSandbox.getUploadElementValue (hammerhead.js:19535:31)
    at HTMLInputElement.getter [as value] (hammerhead.js:20816:43)
    at react-dom.production.min.js:32:112
    at X (react-dom.production.min.js:33:70)
    at ii (react-dom.production.min.js:208:487)
    at Tu (react-dom.production.min.js:251:81)
    at Lu (react-dom.production.min.js:250:408)
error @ hammerhead.js:43305
J @ index.js:234
fn @ index.js:191
value @ index.js:54
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
ha @ react-dom.production.min.js:131
yi @ react-dom.production.min.js:220
Fu @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ql @ react-dom.production.min.js:122
Ou @ react-dom.production.min.js:252
bu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ql @ react-dom.production.min.js:122
Yl @ react-dom.production.min.js:123
Kl @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:244
os @ react-dom.production.min.js:289
t.hydrate @ react-dom.production.min.js:295
v.default.createElement.callbacks @ index.js:349
ie @ index.js:488
(anonymous) @ index.js:506
s @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ _async_to_generator.js:23
u @ _async_to_generator.js:12
(anonymous) @ _async_to_generator.js:17
nrWrapper @ ?force-exp-sihp_topics_test_1=control&force-exp-unlimited_paq_test=control:103
r @ ?force-exp-sihp_topics_test_1=control&force-exp-unlimited_paq_test=control:103
(anonymous) @ _async_to_generator.js:9
ce @ index.js:524
ue @ index.js:497
(anonymous) @ index.js:635
s @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ _async_to_generator.js:23
u @ _async_to_generator.js:12
nrWrapper @ ?force-exp-sihp_topics_test_1=control&force-exp-unlimited_paq_test=control:103

hammerhead.js:43305 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

### Steps to Reproduce

This is reproducible on an internal website so can't provide an example yet but did get the testcafe log and browser console messages from the run that might help identify the issue

https://upload.disroot.org/r/1x3h34w8#bdMOCO33y7ltfgPrMsgsN9EyQcDBqSfc2pBzA6FApbk=

**Also, when running the same test(s) without using native automation mode, this is not an issue and tests pass**

### TestCafe version

3.1.0

### Node.js version

18.16.0

### Command-line arguments

yarn testcafe 'chrome --ignore-certificate-errors --no-sandbox --disable-dev-shm-usage' sampleTest.ts

### Browser name(s) and version(s)

Chrome 115.0.5790.114

### Other

NextJS version is 12.3.0

**Comment by tandreys** [comment] 2023-08-03 16:29
got same issue on a click displaying a popup div

**Comment by ayemelyanenko-chegg** [comment] 2023-08-03 16:33
@tandreys are you able to provide an example that reproduces on a non internal website?

**Comment by miherlosev** [comment] 2023-08-04 00:09
Duplicate of https://github.com/DevExpress/testcafe/issues/7886

**Closed by miherlosev** 2023-08-04 00:09 UTC
Labels: TYPE: bug, STATE: Need response
