### ISSUE TITLE
Unable to import ESM-only modules in a test

### ISSUE THREAD

**Issue by mkochel-shell** [DevExpress/testcafe#6853] opened 2022-02-07 13:07 UTC
### What is your Scenario?

Importing ESM-only modules in a test throws ERR_REQUIRE_ESM error.

### What is the Current behavior?

An error is thrown:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules\node-fetch\src\index.js
require() of ES modules is not supported.
require() of node_modules\node-fetch\src\index.js from test.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules\node-fetch\package.json.

    at Object.<anonymous> (test.js:3:1)
```

### What is the Expected behavior?

Test executes correctly.

### What is your public website URL? (or attach your complete example)

Please see the isolated test code below.

### What is your TestCafe test code?

```js
// Make sure node-fetch 3.2.0 is installed.
// It is an ESM-only module.
import fetch from 'node-fetch' // The test will fail at this line.

fixture`ESM-only module import error`

test('Will not run', () => {
  console.log('This code will not run')
})
```

### Your complete configuration file

No specific configuration file.

### Your complete test report

Please refer to the error message above.

### Screenshots

Not applicable.

### Steps to Reproduce

Please install node-fetch 3.2.0 and run the attached test code.

### TestCafe version

1.18.3

### Node.js version

14.17.1

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

chrome

### Platform(s) and version(s)

Windows 11

### Other

The test code runs with node-fetch 2.6.7, which supports `require()`. It seems that import statements are transpiled to require calls, which fails for all ESM-only modules.

**Comment by AlexKamaev** [comment] 2022-02-08 07:58
> The test code runs with node-fetch 2.6.7, which supports require(). It seems that import statements are transpiled to require calls, which fails for all ESM-only modules.

You are right. TestCafe transpiles `imports` to `require` calls and this leads to the issue. Thank you for reporting this.

**Comment by puneetpunj** [comment] 2022-04-06 02:40
Any update on this issue? this is happening with @percy/testcafe package as well.

**Comment by thelazurite-cell** [comment] 2022-04-12 19:45
Created bug reproduction project:
[tc-esm.zip](https://github.com/DevExpress/testcafe/files/8476069/tc-esm.zip)

**Comment by Aleksey28** [comment] 2022-04-13 06:58
Thank you for the example. We do not have news on this. We will update this thread once we have any progress.

**Comment by mineshh** [comment] 2022-04-13 07:49
I've recently witnessed the same. Although I think this was working for me before...

**Comment by smellai** [comment] 2022-05-24 07:51
I also have this issue

**Comment by bvklingeren** [comment] 2022-06-24 12:04
We are experiencing this issue as well. I have just upgraded our Angular project from 12 to 13 and we are using the Angular Material Harness functionality in our e2e tests, so we would directly use the Material library in ESM format, which is not possible now.

I understand fixing this issue might take a considerable amount of time, therefore I would like to know it the issue is currently being investigated/developed or not, so I can make a decision on how to go forward..

**Comment by AlexKamaev** [comment] 2022-06-27 07:11
@bvklingeren,
You are right, a fix for this issue might take significant time. We did not look into it yet. We have plans to research it, but I cannot give time estimates right now, unfortunately.

**Closed** 2023-01-13 07:59 UTC
Labels: TYPE: enhancement, FREQUENCY: level 2, STATE: No updates
