### ISSUE TITLE
TestController.hover() doesn't scroll elements other than the body unless the window is focused, hangs indefinitely

### ISSUE THREAD

**Issue by GrahamLea** [DevExpress/testcafe#5681] opened 2020-11-04 07:08 UTC
### What is your Test Scenario?
On a page with an element that scrolls (not the body), I want to scroll to an item that's not in the element's view port. [This blog](https://devexpress.github.io/testcafe/media/team-blog/how-to-scroll-web-pages-using-testcafe.html#scroll-to-a-rendered-dom-element) suggests that `.hover(element)` should do the trick.
 
### What is the Current behavior?
When the `hover()` is awaited, the test hangs indefinitely, until the browser window is brought to the foreground, at which time the scroll happens and the test proceeds. It would be my guess that in a headless environment, the scroll would never happen.
 
### What is the Expected behavior?
The scrollable element should scroll to the hovered element without the window needing focus.
 
### What is your web application and your TestCafe test code?

<details>
<summary>Sample Application:</summary>
https://jsfiddle.net/3vce7o4b/3/
</details>

<details>
<summary>TestCafe Test</summary>

NOTE: Though the JSFiddle example necessitates switching to an iframe, I have the same problem in my application without an iframe involved.
```typescript
import { Selector } from "testcafe";

fixture("Test")
  .page("https://jsfiddle.net/3vce7o4b/3/")
;

test("Scroll internal element using hover", async tc => {
  await tc.switchToIframe(Selector("[name='result']"));
  await tc.expect(Selector("main").scrollTop).eql(0);
  await tc.hover(Selector("button"));
  await tc.expect(Selector("main").scrollTop).notEql(0);
}); 
```
</details>

<details>
<summary>Your complete test report:</summary>

NOTE: The test passes, but only if the test browser window is focused.

```
Make changes to the source files or press Ctrl+R to restart the test run.

A test run is starting...
 Running tests in:
 - Chrome 86.0.4240.183 / macOS 10.14.6

 Test
 ✓ Scroll internal element using hover


 1 passed (20s)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:
1. Run the above TC test from a terminal.
2. When the browser window appears, quickly switch back to the terminal.
3. If the test passes, run the test again in live mode and make sure the browser window isn't focused.
 
### Your Environment details:
 
* testcafe version: 1.9.4
* node.js version: v13.13.0
* command-line arguments: `npx testcafe --live chrome <testfile>`
* browser name and version: Chrome 86.0.4240.183 (Official Build) (x86_64)
* platform and version: MacOS 10.14.6

**Comment by GrahamLea** [comment] 2020-11-04 10:20
If I'm honest, what I really want is to just be able to do `t.scrollIntoView(Selector(...))`.

This workaround does what I want for the moment:
```typescript
      return this._tc.eval(() => {
        document.getElementById(...)?.scrollIntoView();
      });
```

**Comment by AndreyBelym** [comment] 2020-11-05 12:44
Thank you for your report. This looks like some kind of Chrome rendering optimization. I see this behavior only when a background window is fully covered by some other window. If even a small part of the window is visible, everything works fine for me (even if the window is still in the background). Also, everything works fine in Chrome Headless and Firefox (both GUI and Headless). I also noticed that t.takeScreenshot doesn't work under the same conditions. I tried adding the `--disable-renderer-backgrounding` flag, but it doesn't help. I need some more time to research this issue.

**Comment by AlexKamaev** [comment] 2023-08-10 09:36
I tried to reproduce the issue in Chrome in the latest TestCafe version. It works as expected, so I'll close the issue. If the issue still persists in your case in the latest TestCafe version, please feel free to create a separate issue or add a comment here.

**Closed by AlexKamaev** 2023-08-10 09:36 UTC
Labels: TYPE: bug, OS: Mac, SYSTEM: automations, FREQUENCY: level 1, STATE: possibly fixed in native automation
