### ISSUE TITLE
Unexpected native alert message during test execution

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#1336] opened 2017-03-21 12:27 UTC
**Moved from from gh-1210**

### Are you requesting a feature or reporting a bug?

bug
![Screenshot](https://content.screencast.com/users/GeorgeZA/folders/Jing/media/4cee9059-8ef4-433c-b1a4-d85963f6cb75/2017-03-21_1458.png)

### What is the current behavior?

Native alert message appears during test execution

### What is the expected behavior?

should be no alert message

### How would you reproduce the current behavior (if this is a bug)?

Run test. It fails very rarely, so recommended to run it multiple times as in example below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://genomemedicine.biomedcentral.com/

Test code

```js
fixture `gh-1336`

const pageUrl = ClientFunction(() => window.location.href);

import { ClientFunction } from 'testcafe';

for (let i = 0; i < 100; i++) {
	test.page('http://genomemedicine.biomedcentral.com/')('Submit Manuscript button', async t => {
	    await t.click('.journal-identity__submit');
	    await t.wait(1000);
	    const expectedUrl = 'http://www.editorialmanager.com/gmed/default.aspx';
	    const currentUrl = await pageUrl();
	    await t.expect(currentUrl).eql(expectedUrl);
	});
}

```

### Specify your

* operating system: Win10 x64
* testcafe version: 0.13.0
* node.js version: 5.4.1

**Comment by AlexanderMoskovkin** [comment] 2017-04-25 09:58
duplicate of #1210

**Closed by AlexanderMoskovkin** 2017-04-25 09:58 UTC
Labels: AREA: client, REASON: duplicate, TYPE: bug
