### ISSUE TITLE
Docker image not working with Yarn PnP - cannot find module

### ISSUE THREAD

**Issue by aboe026** [DevExpress/testcafe#7419] opened 2022-12-14 06:18 UTC
### What is your Scenario?

I would like to run my repo set up with Yarn PnP through the testcafe docker image

### What is the Current behavior?

When I attempt to run `docker run --rm -v D:\path\to\testcafe-docker-yarn-pnp:/app -w /app -it testcafe/testcafe:2.1.0 chromium build/tests --config-file=.testcaferc.json` I get the following error:

```sh
ERROR Cannot prepare tests due to the following error:

    Error: Cannot find module 'node-fetch'
    Require stack:
    - /app/build/tests/lifecycle.test.js
    - /usr/lib/node_modules/testcafe/lib/compiler/test-file/formats/es-next/compiler.js
    - /usr/lib/node_modules/testcafe/lib/compiler/compilers.js
    - /usr/lib/node_modules/testcafe/lib/compiler/index.js
    - /usr/lib/node_modules/testcafe/lib/runner/bootstrapper.js
    - /usr/lib/node_modules/testcafe/lib/runner/index.js
    - /usr/lib/node_modules/testcafe/lib/testcafe.js
    - /usr/lib/node_modules/testcafe/lib/index.js
    - /usr/lib/node_modules/testcafe/lib/cli/cli.js
    - /usr/lib/node_modules/testcafe/lib/cli/index.js
        at Object.<anonymous> (/app/tests/lifecycle.test.ts:2:1)

    Type "testcafe -h" for help.
```

### What is the Expected behavior?

The tests should run without any errors around dependencies

### What is your public website URL? (or attach your complete example)

https://github.com/aboe026/testcafe-docker-yarn-pnp

### What is your TestCafe test code?

```js
import { Selector } from 'testcafe'
import fetch from 'node-fetch'

fixture('Lifecycle').page('https://google.com')

test('Search bar exists', async (t) => {
  const result = await fetch('https://swapi.dev/api/people/1')
  const text = await result.text()
  let json
  try {
    json = JSON.parse(text)
  } catch (err) {
    throw Error(`Invalid JSON response '${text}': '${err}'`)
  }
  await t.expect(json.name).eql('Luke Skywalker')
  await t.expect(Selector('input[title="Search"]').exists).ok()
})

```

### Your complete configuration file

```json
{
  "browsers": ["edge"],
  "screenshots": {
    "path": "screenshots",
    "takeOnFails": true
  },
  "src": "build/tests"
}

```

### Steps to Reproduce

Please see https://github.com/aboe026/testcafe-docker-yarn-pnp#steps-to-reproduce

### TestCafe version

2.1.0

### Node.js version

v16.13.2

### Command-line arguments

docker run --rm -v D:\path\to\testcafe-docker-yarn-pnp:/app -w /app -it testcafe/testcafe:2.1.0 chromium build/tests --config-file=.testcaferc.json

### Browser name(s) and version(s)

chromium

### Platform(s) and version(s)

Windows 11

**Comment by aboe026** [comment] 2022-12-14 23:54
I think I found a workaround: https://github.com/aboe026/testcafe-docker-yarn-pnp#workaround

Needed to alter the docker image like so:

```dockerfile
FROM testcafe/testcafe

USER root

RUN npm install -g yarn && \
    sed --in-place --regexp-extended "s/^node /yarn node /" /opt/testcafe/docker/testcafe-docker.sh

USER user
```

**Comment by miherlosev** [comment] 2022-12-22 09:04
Hi @aboe026

> I think I found a workaround: [https://github.com/aboe026/testcafe-docker-yarn-pnp#workaround](https://github.com/aboe026/testcafe-docker-yarn-pnp#workaround)

I am happy to hear that.

We will consider supporting Yarn PnP since it has its own module resolution mechanism that is not fully compatible with the standard way used in `npm`.

**Comment by miherlosev** [comment] 2023-05-18 03:28
Duplicate of https://github.com/DevExpress/testcafe/issues/7710

**Closed by miherlosev** 2023-05-18 03:28 UTC
Labels: TYPE: enhancement, AREA: docker
