### ISSUE TITLE
Local storage is not saved correctly after Role is initialized

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#2475] opened 2018-05-30 14:28 UTC
### Are you requesting a feature or reporting a bug?
a bug
### What is the current behavior?
local storage is not saved
### What is the expected behavior?
local storage should work
#### Provide the test code and the tested page URL (if applicable)
see https://github.com/DevExpress/testcafe/issues/2142 comments of @TestAndunR

**Comment by TestAndunR** [comment] 2018-06-04 03:53
Hi @AlexKamaev, thank you for the reply. Yes this workaround work for me. Thank you

**Comment by darina-techery** [comment] 2018-08-30 14:42
This workaround didn't work for me.
In my tests user can only be authenticated via localStorage. It requires a special 'token' property. 
I try to authenticate user by running POST /login request and inserting the result into localStorage:

```js
const roles = {
  asMainUser: Role(baseUrl, async () => {
    const loginResponse = await usersApi.login(mainUser.email, mainUser.password);
    const appState = JSON.stringify({
      session: loginResponse,
      settings: {}
    });
    console.log("Set app_state: "+appState);
    await client.localStorageSet("app_state", appState);

    console.log("Wait until app_state is found in localStorage");
    await t.expect(client.localStorageGet("app_state")).ok();

    console.log("app_state is found: "+await client.localStorageGet("app_state"));
    await t.wait(5000);
    console.log("Waited for 5 seconds");
  }, { preserveUrl : true })
};
export default roles;
```

All the checks say that localStorage is populated ok, and I even wait for 5 additional seconds, as suggested in a workaround.
In 50% cases the localStorage is empty after the role is applied, and the test fails.

I also tried removing `preserveUrl` and navigating to the page explicitly. No luck either.

**Comment by konqi** [comment] 2018-09-16 10:36
If I read the code correctly from the [hammerhead repo](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/session/index.js), persisting storages is simply not implemented. 
So, at the moment, persistence and rehydration of the stores must be done manually.

**Comment by AlexKamaev** [comment] 2018-09-17 08:05
Hi @konki
The roles mechanism is supposed to work with both cookies and storage. The storage persistence is supported, so it is not required to do it manually. The cause of @darina-techery's issue was in overriding storage by some client script. Please refer #2782 to see details.

**Comment by konqi** [comment] 2018-09-17 08:51
@AlexKamaev Nice! Can you point me to the right place where storage persistence is implemented, because it is not working for me and I'd like to debug it.

**Comment by AlexKamaev** [comment] 2018-09-17 09:52
@konqi 
In the testcafe repo, TestCafe sends a command to the browser to return storages: 
 
https://github.com/DevExpress/testcafe/blob/158695b099dce51a0495b2c269449a72eb701672/src/test-run/index.js#L588
 
In the hammerhead repo, a browser returns the storages to the server to save them in the role: 
 
https://github.com/DevExpress/testcafe-hammerhead/blob/9ee5ebb2e90563b8ab82cc70f608888370e6b475/src/client/sandbox/storages/index.js#L107
 
When a new page is requested, the hammerhead injects a special script to restore the storages from the role on the page:
 
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/processing/resources/page.js#L118

**Comment by hitautodestruct** [comment] 2019-04-22 11:49
I'm running tests on a vue single page app and I'm getting the same issue.
After multiple logins using `useRole` the localStorage does not persist.

I created a class which manually logs me in on every test, which is what the Roles was technically meant to help avoid.

This might help someone if @AlexKamaev workaround does not work for you. (it didn't for me)

```
// Auto.js

import { selectorTag } from './TestTag'
import VueSelector from 'testcafe-vue-selectors'

import { t } from 'testcafe'

export default class Auto {
  constructor() {
    const loginComponent = VueSelector('Login')
    this.userTextInput = loginComponent.find(`.input["username"]`)
    this.passTextInput = loginComponent.find(`.input["password"]`)
  }
  async login(user = 'user', password = 'pass') {
    await t
      .typeText(this.userTextInput, user)
      .typeText(this.passTextInput, password)
      .pressKey('enter')
  }
  async userLogin() {
    await this.login()
  }
  async user2Login() {
    await this.login('user2', 'pass2')
  }
}

// sanity.test.js
import Auto from './utility/Auto.js'
import VueSelector from 'testcafe-vue-selectors'

const AutoPage = new Auto()

test('User1: Buttons are NOT visible', async t => {
  // programatically login
  await AutoPage.userLogin()

  const menuComponent = VueSelector('Menu')
  const buttons = menuComponent.find(`.buttons`)

  await t.expect(buttons.exists).notOk('Buttons are visible')
})
```

**Comment by dbschwartz** [comment] 2019-04-26 19:06
I think this is related to the problem I'm still having that was closed: https://github.com/DevExpress/testcafe/issues/3580

**Comment by dbschwartz** [comment] 2019-04-26 19:12
Yes I just tried the same thing I've been having a problem with without using a role and the localStorage was preserved.

**Comment by AlexKamaev** [comment] 2019-04-29 09:22
@dbschwartz Thank you for your cooperation. We would really appreciate it if you prepare an example and provide it to us.

**Comment by dbschwartz** [comment] 2019-04-29 20:30
Yes @AlexKamaev, I was able to finally reproduce the problem into a demo!

I will post it as soon as I have some time

**Comment by dbschwartz** [comment] 2019-04-30 03:44
Here is the repo: https://github.com/dbschwartz/test-cafe-local-storage

You can download, npm install and run the tests with npm test.  It runs against the GH Pages repo I made.

There are two fixtures in the test.

The first without a role and will be able to click the hyperlink on the new page (the URL comes from localStorage)

The second with a role where localStorage doesn't work, so there won't be a hyperlink and the test will fail.

It seems the problem occurs during the event STORAGE_CHANGED in role where localStorage is supposed to go from hammerhead temporary localStorage to a wrapper.

In the role for some reason the localStorage data gets lost in the process.  Please let me know if you have any questions.  Thank you so much guys!

**Comment by Farfurix** [comment] 2019-04-30 09:41
@dbschwartz 

Hello,

Thank you for your project. I've reproduced the issue under Chrome 74 / Windows 10. Our team will research it and check for a suitable solution.

**Comment by dbschwartz** [comment] 2019-04-30 19:15
Thanks @Farfurix, really appreciate i

**Comment by dbschwartz** [comment] 2019-05-06 14:31
Just wanted to note my problem is a bug, not an enhancement.  Should I open it as a different issue?

**Comment by AndreyBelym** [comment] 2019-05-07 12:18
@dbschwartz try updating your TestCafe version to 1.1.4. It contains a fix that improves handling of cookies and storages in Roles. If the issue still persists in the new version, please create a new bug report.

**Comment by dbschwartz** [comment] 2019-05-09 12:41
Thanks @AndreyBelym .  I tried the test with testcafe@1.1.4, but unfortunately the issue still persists.  I opened a new bug report.  It can be viewed here: https://github.com/DevExpress/testcafe/issues/3780

**Comment by Evilweed** [comment] 2019-06-07 13:19
@AndreyBelym I think I have similar/the same issue.

**None of those things helped:**

- updating test cafe to `1.2.0` , 
- adding `CustomRequestHook` with `event.requestOptions.headers['cache-control'] = 'no-store';` 
- adding `--disk-cache-size=1` to chrome flags

**Comment by Farfurix** [comment] 2019-06-10 10:45
@Evilweed 

Hello,

Since the `disk-cache-size`/`CustomRequestHook` workaround doesn't help you, your issue is probably not related to the above issues in this thread.

Please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) with your test code and a sample project (or use some public URL) so that we can reproduce your issue and find its cause.

**Comment by AndreyBelym** [comment] 2019-07-01 10:58
Looks like all comments in this thread are related to the problem that Roles can't restore cookies and storages due to browser network cache. This problem is covered by issue https://github.com/DevExpress/testcafe/issues/3780. Due to that, I close this issue as a duplicate.

**Closed by AndreyBelym** 2019-07-01 10:58 UTC
Labels: SYSTEM: driver, TYPE: enhancement
