### ISSUE TITLE
Test Executions are Freezing While Using CircleCI

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#6711] opened 2021-11-19 18:39 UTC
### What is your Scenario?

We have a CircleCI project that runs jobs after merges to master and after dev repo deployments.

### What is the Current behavior?

The majority of our executions timeout due to 'no output' from TestCafe when running in the CircleCI Docker image using CircleCI.

### What is the Expected behavior?

Entire test execution to complete without TestCafe freezing.

### What is your public website URL? (or attach your complete example)

Sent an email with our project. 

### What is your TestCafe test code?

Please use the project emailed to support@devexpress.com

### Screenshots

![Screen Shot 2021-11-19 at 1 37 03 PM](https://user-images.githubusercontent.com/87319403/142681571-75c0f674-2bd1-4a3d-9d4a-421159fc0b6d.png)
![Screen Shot 2021-11-19 at 1 49 37 PM](https://user-images.githubusercontent.com/87319403/142683237-0cde3d01-e5f2-49b0-8780-5ea1529d9f68.png)

### Steps to Reproduce

1. Trigger a job in CircleCI using the CURL request
2. If/when the execution times out, view the 'npm run' step
3. See in the Spec results that a test started, but it never finished. This usually happens later in the execution, around the ~50th+ script.

### TestCafe version

1.15.2

### Node.js version

16.10.0

### Command-line arguments

curl --request POST \   --url https://circleci.com/api/v2/project/github/clickfunnels2/cf2-test-cafe-poc/pipeline \   --header 'Circle-Token: d68aa3a0af567357adc5c3aa6eb4e8d66d550149' \   --header 'content-type: application/json' \   --data '{"parameters":{"run_sanity":false, "run_full_suite":true}}'

### Browser name(s) and version(s)

Chrome 96.0

### Platform(s) and version(s)

macOS 11.6.1

**Comment by miherlosev** [comment] 2021-11-23 08:51
Hi @jbradenclickfunnels

Thank you for the example. Please try to run your tests with the latest TestCafe version (`1.17.1`). If the issue still exists, please simplify the test project, add instructions on how to run it on a local machine, and send it via email again.

**Comment by jbradenclickfunnels** [comment] 2021-11-23 14:29
@miherlosev 

The project is built according to the TestCafe documentation, so I don't know what you mean by making it simpler. 

We cannot upgrade to anything higher than 1.15.2 because the newer versions have broken the configuration file output. Until that's fixed, we need to remain on 1.15.2. If that regression has been fixed, to work with testcaferc.json again, please let me know. 

How to run the project in CircleCI is provided in the CURL command, so unsure what you need locally. We don't see the freezing locally, only when using CircleCI, again, the config was built based on the documentation provided by DevExpress. 

We run our project locally with the command 'ENV=staging testcafe', but you won't see the freezing we see from CircleCI.

**Comment by jbradenclickfunnels** [comment] 2021-11-24 15:12
![Screen Shot 2021-11-24 at 9 11 45 AM](https://user-images.githubusercontent.com/87319403/143264147-86f74f02-3a67-4601-8bc7-ba2d432ab584.png)

Another occurrence in last night's run

**Comment by aleks-pro** [comment] 2021-11-26 07:39
Hello @jbradenclickfunnels,

> We cannot upgrade to anything higher than 1.15.2 because the newer versions have broken the configuration file output.

We fixed the issue with broken output in TestCafe v1.17.1: https://github.com/DevExpress/testcafe/issues/6665. Please use this version and let us know about your results.

**Comment by jbradenclickfunnels** [comment] 2021-11-29 15:24
We're beginning our work to update to TestCafe 1.17.1 and will watch our runs for a week and report back if any of them freeze during execution in CircleCI.

Thanks!

**Comment by jbradenclickfunnels** [comment] 2021-11-30 15:42
While using 1.17.1, we had another timeout. It seems to be happening more consistently after skipping a test using test.skip.

![Screen Shot 2021-11-30 at 9 40 47 AM](https://user-images.githubusercontent.com/87319403/144079002-f0236606-4424-4a4d-b202-7d7e94989554.png)

**Comment by jbradenclickfunnels** [comment] 2021-12-01 19:12
We've now tried an inverse filtering option in the testcaferc.json file, but since negative lookup provides 0 matches, TestCafe kills the run with "No tests match your filter."

Our final solution at this point is to comment out tests we were skipping. We'd really like to see these skipped tests reported on, so please let us know when a true solution is in place.

Thanks,

**Comment by jbradenclickfunnels** [comment] 2021-12-02 15:11
We went ahead and just commented out all our skipped tests to see if that would help with timeouts, but when I logged in this morning, we had another run that froze. 
![Screen Shot 2021-12-02 at 9 10 17 AM](https://user-images.githubusercontent.com/87319403/144448817-7b02ec7e-d279-450d-87d2-878961b0c5a4.png)

**Comment by miherlosev** [comment] 2021-12-03 13:52
Hi @jbradenclickfunnels 

For complex filtering rules, it's better to configure TestCafe with a programmatic interface - [Runner.filter](https://testcafe.io/documentation/402657/reference/testcafe-api/runner/filter) or the [JavaScript configuration file](https://testcafe.io/documentation/402638/reference/configuration-file#javascript).


The shared screenshots don't contain TestCafe errors. So, it's difficult to determine the cause of the issue without a simple example.

> please simplify the test project, add instructions on how to run it on a local machine
> The project is built according to the TestCafe documentation, so I don't know what you mean by making it simpler.

We should be able to run a test project locally. It should contain a minimal number of tests to reproduce the issue, and have instructions on how to run it. Ideally, it should run with one command in the terminal. See more information about creating a minimal working example [here](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue).

**Comment by jbradenclickfunnels** [comment] 2021-12-03 16:33
@miherlosev 

Thanks for your reply. We'll have to look into the runner or new js config files at another point in time. I don't want to get us hung up on that compared to the issue at hand here. 

There are no errors because TestCafe is freezing. The run gets terminated by CircleCI after the timeout occurs. You can see the timeout message at the end of each screenshot. The variables we can go off of right now are: TestCafe freezing, tests being skipped, a docker image, and CircleCI. 

As mentioned before, running locally doesn't cause freezing, only when running in CircleCI. So a 'simpler' project wouldn't be able to replicate the issue we are having. 

After reading the document from your last link, I have found these statements:

> My tests only fail when I run them on Docker.
> 
> Containers and virtual machines have limited resources. TestCafe tests may fail if TestCafe, the browser, or the application does not have enough resources to run smoothly. Try to increase the amount of resources allocated to the Docker image or increase the timeout values for Selectors and assertions. If you are sure that issue is with Docker, send us the complete Docker image and its sources.
> 
> My tests run well on the local machine, but fail as unstable on CI.
> 
> It is difficult to determine why your tests fail on CI because your tests’ performance depends on your CI settings (environment settings, memory configuration, and so on). To begin troubleshooting, increase timeout values and make sure your web server correctly processes requests. If you’re stuck, send the copy of the complete TestCafe debug log to support@devexpress.com.
> 
> set DEBUG=testcafe:*,hammerhead:*
> testcafe chrome index.js 2> testcafe.log

We are using a provided image of cimg/node:lts-browsers from the TestCafe documentation

We upped our CircleCI server from medium to large as we did notice the RAM usage spiking at times. Large keeps the RAM at a max of 75% usage now, but still we see the timeouts. This leads me to believe it's the Docker Image or TestCafe causing the freezing to happen. 

Is there a better Docker image to use that TestCafe recommends compared to the one provided in the documentation?

Again, I'd love to be able to provide a 'simpler' project for you to run, but this issue ONLY happens when running the full suite, while executing a build through CircleCI, and usually occurs after skipping a test, but that is not 100% the case as evident from the screenshots above.

If we need to set up a call, I'd be more than happy to accommodate so we can move forward with root cause and a fix.

**Comment by miherlosev** [comment] 2021-12-06 09:43
> The run gets terminated by CircleCI after the timeout occurs. You can see the timeout message at the end of each screenshot.

Try to measure the free memory by adding the 'console.log(Math.round(os.freemem() / 1024 /1024))' statement at the end of each test.

> We are using a provided image of cimg/node:lts-browsers from the TestCafe documentation

Please share a link to the documentation page where we recommended using this image.

> Again, I'd love to be able to provide a 'simpler' project for you to run, but this issue ONLY happens when running the full suite, while executing a build through CircleCI, and usually occurs after skipping a test, but that is not 100% the case as evident from the screenshots above.

We still need step-by-step instructions on how to run your example on CircleCI. Please share these instructions by email.

**Comment by jbradenclickfunnels** [comment] 2021-12-06 16:50
@miherlosev,

We'll look into the memory situation and report back. I know that CircleCI's memory usage with our project hits around 75% max based on their resources chart.

Documentation for CircleCI [here](https://testcafe.io/documentation/402819/guides/continuous-integration/circleci) 

I'll send a step by step email on how to view the runs in CircleCI via the CURL request provided.

**Comment by miherlosev** [comment] 2021-12-08 09:08
Thank you. We will await your memory usage report and step-by-step instructions on how to run your test suite on Circle CI.

**Comment by jbradenclickfunnels** [comment] 2021-12-16 15:48
This morning, I was able to witness a situation where a test never failed and closed, causing the suite to not continue onto the next tests. This would be a cause for a timeout in CircleCI. I'm not 100% it's the only reason for 'freezing' or timing out, but I think it's one culprit.

How can we make a test fail and close after attempting to interact with an element, but can't? It looks like TestCafe is able to find an element it needs, but can't interact with it because of a notification box that's over the top of it.

If there's a solution on how to clean that up, we may have less timeouts in our runs. We are working on a way to close those notification boxes dynamically. If you have any insight on how to do that, that would be great too!

https://user-images.githubusercontent.com/87319403/146402877-d0a07642-ca44-49f7-bd84-9f421ae95129.mov

**Comment by miherlosev** [comment] 2021-12-20 08:22
> It looks like TestCafe is able to find an element it needs, but can't interact with it because of a notification box that's over the top of it.

If you know when the notification box is opened, just close it. If you don't (it's very strange), create a wrapper for action and use it.

```js
async safeAction (action, selector, options) {
    if (await popup.visible)
        t.click(popup.DismissLink)
     
    await action(selector, options);
}

test('test', async t => {
    await safeAction(t.click, '#some-element');
});
```

We are trying to keep only bugs and enhancements in this repository. I will close this issue, because it's not a bug or enhancement.

**Closed by miherlosev** 2021-12-20 08:22 UTC
Labels: STATE: Need response

**Comment by jbradenclickfunnels** [comment] 2021-12-20 14:57
We shouldn't close this issue based on the last observation. We still have timeouts outside of what I mentioned last. 

The issue at hand are timeouts in general, due to no output.

**Comment by jbradenclickfunnels** [comment] 2021-12-20 14:59
> > It looks like TestCafe is able to find an element it needs, but can't interact with it because of a notification box that's over the top of it.
> 
> If you know when the notification box is opened, just close it. If you don't (it's very strange), create a wrapper for action and use it.
> 
> ```js
> async safeAction (action, selector, options) {
>     if (await popup.visible)
>         t.click(popup.DismissLink)
>      
>     await action(selector, options);
> }
> 
> test('test', async t => {
>     await safeAction(t.click, '#some-element');
> });
> ```

We don't know when the box is going to display because it's dynamically being opened from other tests running during concurrency. 

We can try your code snippet and see if that helps with the dynamic opening of the notification box.

**Comment by hyunil-shin** [comment] 2022-10-26 07:11
Is there any hint to solve this issue?
I have almost the same issue, in kubernetes.
At some point, test execution was freezing without output.

**Comment by miherlosev** [comment] 2022-10-31 07:36
Hi @hyunil-shin,

Please make sure that the test machine has sufficient system resources (memory and CPU) during test execution. Node.js caches the executed test files since they are the modules. Thus, memory usage is increased during test execution.
