### ISSUE TITLE
Site works wrong during test execution

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3938] opened 2019-06-26 12:05 UTC
https://stackoverflow.com/questions/56637067/testcafe-cli-doesnt-logout-successfully-on-website-using-auth0?sem=2

Logout is not occurred during test execution.
See code and credentials in this [private issue](https://isc.devexpress.com/Thread/WorkplaceDetails/T753030).

**Comment by AndreyBelym** [comment] 2019-07-01 11:15
Looks like a duplicate of #3780. The test works if I disable the network cache in DevTools or add an additional test that disables the network cache via DevTools protocol:
```js
test
    .page('about:blank')
    ('Disable cache', t => t.testRun.browserConnection.provider.plugin.openedBrowsers[t.testRun.browserConnection.id].client.Network.setCacheDisabled({ cacheDisabled: true }))
```

**Closed by AndreyBelym** 2019-07-01 11:15 UTC
Labels: STATE: Need research, TYPE: bug
