### ISSUE TITLE
CDP: disableMultipleWindows is ignored

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#7849] opened 2023-06-30 12:45 UTC
### What is your Scenario?

links with `target="_blank" ` opens on new tab and ignores `disableMultipleWindows = true` setting

### What is the Current behavior?

links with `target="_blank" ` opens on new tab and ignores `disableMultipleWindows = true` setting

### What is the Expected behavior?

should not ignore

### What is your public website URL? (or attach your complete example)

doesn't matter

### What is your TestCafe test code?

just a simple click on a with `target="_blank"`  attribute

### Steps to Reproduce

perform a click on element with `target="_blank"`  attribute

### TestCafe version

3.0.1

### Node.js version

v16.19.0

### Command-line arguments

npx testcafe chrome

**Comment by vasilyevi** [comment] 2023-06-30 14:19
Try to play around with booking com as an example. It opens hotel in new tab and does not switch to it. If I remove disableMultipleWindows the test is failed due to `The Native Automation mode does not support the use of multiple browser windows. Use the "disable native automation" option to continue.`

**Comment by vasilyevi** [comment] 2023-06-30 14:52
as an workaround trying to remove `target` attribute from `a`, but getting randomly following issue
`
   1) Unhandled promise rejection:
      
      Error: Session with given id not found.
      at /Users/i/Documents/monorepo/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:94:35
      at Chrome._handleMessage (/Users/i/Documents/monorepo/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:272:17)
      at WebSocket.<anonymous> (/Users/i/Documents/monorepo/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:240:22)
      at WebSocket.emit (node:events:513:28)
      at WebSocket.emit (node:domain:489:12)
      at Receiver.receiverOnMessage (/Users/i/Documents/monorepo/src/js/tests/node_modules/ws/lib/websocket.js:1068:20)
      at Receiver.emit (node:events:513:28)
      at Receiver.emit (node:domain:489:12)
      at Receiver.dataMessage (/Users/i/Documents/monorepo/src/js/tests/node_modules/ws/lib/receiver.js:517:14)
      at Receiver.getData (/Users/i/Documents/monorepo/src/js/tests/node_modules/ws/lib/receiver.js:435:17)

      Browser: Chrome 114.0.0.0 / Ventura 13`

**Comment by Aleksey28** [comment] 2023-07-03 07:51
https://github.com/DevExpress/testcafe/issues/7849
 
Hi @vasilyevi,

We are actively working on the Native Automation mode. However, `disableMultipleWindows `  isn't supported for native automation mode yet.  At present, we cannot give you any precise estimates on when this will be implemented in Native Automation. I will close this issue in favor of https://github.com/DevExpress/testcafe/issues/7661

I recommend that separate your TestCafe tasks into two:

- use Native Automation for general purposes, including this issue
- do not use Native Automation for specific tests that use multiple windows

**Closed by Aleksey28** 2023-07-03 07:51 UTC
Labels: TYPE: bug, STATE: Need response

**Comment by esbarila** [comment] 2023-07-04 01:57
@Aleksey28 any way to ignore @vasilyevi's error (Session with given id not found)?

**Comment by Aleksey28** [comment] 2023-07-05 08:40
Hi @esbarila,

I didn't manage to reproduce this error. If you see the same error, please create a separate issue with a simple example, because this issue was initially related to the multiple windows mode.

**Comment by esbarila** [comment] 2023-07-05 15:20
@Aleksey28 I'm getting it consistenly in my challenge repo here. Should be pretty straightforward, just clone it and run the test script. No other deps are needed
https://github.com/esbarila/AutoFi-Zygmus-challenge

**Comment by Aleksey28** [comment] 2023-07-06 08:22
Please, let's stick to the order. It would be more efficient if you create a new issue. We will continue researching there.
