### ISSUE TITLE
Screenshots does not work in docker if resized window

### ISSUE THREAD

**Issue by FredrikSeidl** [DevExpress/testcafe#1918] opened 2017-10-26 13:46 UTC
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
Screenshots fail when trying to take screenshot after a test has resized the window. This only applies to the docker image.

The error thrown is
```
 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Command failed:
  /opt/testcafe/node_modules/testcafe-browser-tools/bin/linux/musl-64/screenshot
  800001
  /tests/screenshot/2017-10-26_01-43-12/test-1/Chrome_59.0.3071_Linux_0.0.0/1.png
  X Error of failed request:  BadMatch (invalid parameter attributes)
    Major opcode of failed request:  73 (X_GetImage)
    Serial number of failed request:  13
    Current serial number in output stream:  13
```
### What is the expected behavior?
A screenshot should be generated

### How would you reproduce the current behavior (if this is a bug)?
Run the code below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.google.com

Test code

```js
fixture `Reproduce bug`
	.page `https://www.google.com`;

test('Will fail', async t => {
	await t.resizeWindow(1280,800)
	await t.takeScreenshot()
});
```

### Specify your

* operating system: Mac OS X 10.11.5
* testcafe version: v0.18.1
* node.js version:  v6.10.3

**Comment by AndreyBelym** [comment] 2017-10-26 14:27
Hello @FredrikSeidl!

I've reproduced the bug, need some time to investigate it, thank you for the feedback, I'm trying to find a workaround now.

**Comment by AndreyBelym** [comment] 2017-11-14 16:51
I have found that it happens when Chrome window resized to be bigger that virtual screen size. I can't figure out why but looks like that Chrome doesn't works well with Xvfb in this case. The problem can't be reproduced on a real X11 server. 

As a workaround, you can set bigger virtual screen size by passing environment variables `SCREEN_WIDTH` and `SCREEN_HEIGHT` to container, e.g.:
```
docker run -it -e "SCREEN_WIDTH=3840" -e "SCREEN_HEIGHT=2160" -v ~/tests:/tests testcafe/testcafe -s /tests/screenshots 'chromium --no-sandbox' /tests
```

I think we need to increase default screen size to `1920x1080` and emit descriptive warning or error on resizing if the specified size is bigger than the screen size.

**Comment by morph027** [comment] 2018-01-31 06:21
Encountering similar problem while running in Docker within Gitlab CI and already set Xvfb to higher resolution. Still the same errors.

**Comment by shaikatz** [comment] 2018-02-04 09:22
For me it fails with the same error even that I never use the resizeWindow command.

**Comment by morph027** [comment] 2018-02-04 09:32
Like already mentioned in #1913 , switching to headless mode also resolved this issue. Not sure if it's really related to this, but now it works.

**Comment by neilmatillano** [comment] 2018-02-08 10:54
Also getting same error 
**_Error of failed request:  BadMatch (invalid parameter attributes)_**

For failed tests for page with widgets.

**Comment by AndreyBelym** [comment] 2018-02-08 14:52
Hi @shaikatz @neilmatillano, could you try to increase Xvfb screen size, and use headless mode?
```
docker run -it -e "SCREEN_WIDTH=3840" -e "SCREEN_HEIGHT=2160" -v ~/tests:/tests testcafe/testcafe -s /tests/screenshots 'chromium:headless --no-sandbox' /tests
```

**Comment by hauptrolle** [comment] 2018-03-20 12:14
Hi, I get the same error message as mentioned in the first post.
Increasing the screen size, and using headless mode doesn't help.

**Comment by AndreyBelym** [comment] 2018-06-18 08:52
This issue must be fixed by https://github.com/DevExpress/testcafe/pull/2492. I'll notify you when a build with the fix will be published on NPM. Feel free to try the fixed build and reopen the issue if the problem isn't solved in your environment.

**Closed by AndreyBelym** 2018-06-18 08:52 UTC
Labels: AREA: docker, AREA: server, OS: Linux, SYSTEM: browser natives, TYPE: bug
