### ISSUE TITLE
TestCafe cannot run test after upgrading - CLI args not overwriting config file values

### ISSUE THREAD

**Issue by marktmere** [DevExpress/testcafe#6702] opened 2021-11-17 22:23 UTC
### What is your Test Scenario?

I am attempting to upgrade to the latest version of TestCafe from 1.9.1. After I rebuild and attempt to run a test, I am unable to override the config file browsers setting via CLI arguments. It seems that it first validates the browsers setting is valid, before overriding. For my teams local development, we run tests on locally but for our production application, we run them remotely which has the default .testcaferc browser. This wasn't an issue before.

### What is the Current behavior?

After upgrading, I am unable to run tests due to `ERROR Cannot find the browser. "<hidden path>" is neither a known browser alias, nor a path to an executable file.` 

Note - i hid the path for privacy reasons.

### What is the Expected behavior?

The test should see the CLI args and not attempt to validate the browsers value before overriding them.

### How would you reproduce the current behavior (if this is a bug)?

I would put an invalid path in the .testcaferc file for browsers, then try to override it via CLI args.

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                    previously "^1.9.1", have tried "1.14.0", "1.15.0", and @latest
* node.js version:                     v14.17.0
* command-line arguments:   `bb testcafe firefox tests/home -q attemptLimit=3,successThreshold=2 -- --localhost=<host>:8443`
* browser name and version:  firefox
* platform and version:           Mac Catalina 10.15.7
* other:

**Comment by AlexKamaev** [comment] 2021-11-19 07:18
duplicate of https://github.com/DevExpress/testcafe/issues/6618

**Closed by AlexKamaev** 2021-11-19 07:18 UTC
Labels: STATE: Need response
