### ISSUE TITLE
Test hangs after a form submitting

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe#4553] opened 2019-12-06 11:34 UTC
### What is your Test Scenario?
1. Switch to a same-domain iframe
1. Submit a form to the current iframe
1. Redirect to a cross-domain url
 
### What is the Current behavior?
Test hangs.
 
### What is your web application and your TestCafe test code?

<details>
<summary>Test server:</summary>

```js
const http = require('http');

http
    .createServer((req, res) => {
        if (req.url === '/') {
            res.writeHead(200, { 'content-type': 'text/html' });
            res.end('<iframe src="/iframe"></iframe>');
        } else if (req.url === '/iframe') {
            res.writeHead(200, { 'content-type': 'text/html' });
            res.end(`
                <h1>Same-domain iframe</h1>
                <form action="/cross-domain-redirect">
                    <input type="submit" value="Submit">
                </form>
            `);
        } else if (req.url === '/cross-domain-redirect?') {
            res.writeHead(302, { 'location': 'http://localhost:2020/cross-domain-iframe' });
            res.end();
        } else
            res.end();
    })
    .listen(2019, () => console.log('http://localhost:2019/'));


http
    .createServer((req, res) => {
        if (req.url === '/cross-domain-iframe') {
            res.writeHead(200, { 'content-type': 'text/html' });
            res.end('<h1>Cross-domain iframe</h1>');
        } else
            res.end();
    })
    .listen(2020); 
```
</details>

<details>
<summary>Test code:</summary>

```js
fixture`Cross-domain form action`
    .page`http://localhost:2019/`;

test('Switch and submit', async t => {
    await t
        .switchToIframe('iframe')
        .click('input');
});
```
</details>

<details>
<summary>Test with workaround:</summary>

```js
import { ClientFunction } from 'testcafe';

fixture`Cross-domain form action`
    .page`http://localhost:2019/`;

test('Switch and submit', async t => {
    await t.switchToIframe('iframe');
    await ClientFunction(() => document.querySelector('input').click());
});
```
</details>

**Comment by LavrovArtem** [comment] 2019-12-06 11:56
SC ticket:  https://supportcenter.devexpress.com/internal/ticket/details/T815222

**Comment by AndreyBelym** [comment] 2020-05-27 06:36
Duplicate of #4232.

**Closed by AndreyBelym** 2020-05-27 06:36 UTC
Labels: AREA: client, FREQUENCY: level 2, SYSTEM: driver, TYPE: bug, support center
