### ISSUE TITLE
Element Interaction Issues with TestCafe RC1 3.7.0 and Chrome 130

### ISSUE THREAD

**Issue by RafaelBeltranClip** [DevExpress/testcafe#8308] opened 2024-10-21 17:02 UTC
### What is your Scenario?

I have seen multiple tickets related to errors caused by the latest stable version of Chrome (130), which I am also experiencing with TestCafe 3.6.2. In response, I upgraded to TestCafe RC1 3.7.0, which is supposed to address these issues.

However, it appears that Google Chrome is unable to interact with elements—specifically, it cannot type into or click on any elements. In contrast, switching to Firefox allows the tests to run without any issues.

Previously, everything was functioning correctly with TestCafe 3.6.2 and the earlier version of Chrome.

**Note:**
The selectors may change depending on the language used in your machine.

### What is the Current behavior?

Chrome is unable to interact with elements

### What is the Expected behavior?

I should be able to interact with elements.

### What is the public URL of the test page? (attach your complete example)

https://www.google.com/

### What is your TestCafe test code?

```
import { Selector } from 'testcafe';


fixture `Bug Report: Form Submission Issue`
    .page `https://www.google.com/`; 

test('Search anything test', async t => {

    // Example selectors
    const searchInput = Selector('textarea[title="Buscar"]');
    const firstRecommendation = Selector('ul li').nth(0);

    await t
        .typeText(searchInput, 'find anything')
        .click(firstRecommendation);
});
```

### Your complete test report

```
{
  "devDependencies": {
    "testcafe": "^3.7.0-rc.1"
  },
  "scripts": {
    "chrome": "testcafe chrome testcafe.js",
    "chrome:headless": "testcafe chrome:headless testcafe.js",
    "firefox": "testcafe firefox testcafe.js"
  }
}
```

### Steps to Reproduce

1. npm run firefox
2. npm run chrome

see that firefox runs fine and chrome fails.
using the scripts in the package.json

### TestCafe version

3.7.0 rc1

### Command-line arguments

npm run chrome

### Browser name(s) and version(s)

Chrome 130

**Comment by thomas-jakemeyn** [comment] 2024-10-22 09:10
I am facing the same problem when running my tests locally. Nothing happens when clicking on checkboxes, buttons, etc.

- Chrome 130
- TestCafe 3.7.0-rc.1
- MacOS Sonoma 14.6.1

**Comment by ManuelRauber** [comment] 2024-10-22 09:32
Same issue here. As soon as our build agents got a new image containing Chrome 130, all tests starting to fail. 

* Chrome 130
* TestCafe 3.6.2
* Ubuntu 22.04.5

**Comment by thomas-jakemeyn** [comment] 2024-10-22 12:14
Note that the problem does not seem to affect Edge 130 (which is also Chromium-based).

**Comment by yasinkocak** [comment] 2024-10-22 13:47
Same issue with Chrome 130, we move to Edge as workaround, but our application is built for Chrome
Chrome 130
TestCafe 3.7.0-rc.1
MacOS Sonoma 14.7

**Comment by kkapur5** [comment] 2024-10-23 14:56
The new release you have pushed out is that for TestCafe Studio or open source?
Where can I download new version of the Testcafe Studio? Thanks.

**Comment by csw1701** [comment] 2024-10-23 15:47
I can confirm the above behaviour, however there is a workaround to get tests running again for 3.7.0-rc.1. 

- Disable native automation
- Disable Screenshots and Video capture (I just commented them out in testcaferc.json). However if you use `t.takeScreenshot()` anywhere it will still fail, so I had to add `disableScreenshots: true` to testcaferc.json

**Comment by kkapur5** [comment] 2024-10-23 15:57
[csw1701](https://github.com/csw1701) - are you using studio or open source test cafe?

**Comment by csw1701** [comment] 2024-10-23 15:58
> [csw1701](https://github.com/csw1701) - are you using studio or open source test cafe?

I'm using open source testcafe

**Comment by rupesh1395** [comment] 2024-10-24 06:08
I am getting also same issue with Testcafe version 3.5.0 and tried with latest version 3.7.0.  I am stuck to run our daily automated test case. Could you provide any solution?
![image](https://github.com/user-attachments/assets/cf19ff10-0f24-4928-abad-739df80e9b30)

**Comment by Bayheck** [comment] 2024-10-25 08:28
Hello,

We have released TestCafe 3.7.0-rc.2, which addresses this issue. Please try it and let us know if the issue is gone.

**Comment by rupesh1395** [comment] 2024-10-25 09:41
> `3.7.0-rc.2` fixes this issue for my Test Cafe use cases. The element interactions seem to behave the same as with `3.6.2`.

Thank you @Bayheck 

> `3.7.0-rc.2` fixes this issue for my Test Cafe use cases. The element interactions seem to behave the same as with `3.6.2`.

Thank you, It worked for me

**Comment by thomas-jakemeyn** [comment] 2024-10-25 10:04
`3.7.0-rc.2` fixes the element interaction problem for me as well.

Thank you TestCafe team!

**Comment by RafaelBeltranClip** [comment] 2024-10-25 16:56
The fix seems to be working fine. However, I'm currently facing a dependency issue where certain packages require TestCafe to be a version "<1.0.0", and since RC2 is "3.7.0-rc.2", they are failing. Do we have an estimated release date for the official 3.7.0?

**Comment by Bayheck** [comment] 2024-10-29 12:43
I will close this issue as it was fixed in the PR: https://github.com/DevExpress/testcafe/pull/8315

**Closed by Bayheck** 2024-10-29 12:43 UTC
Labels: TYPE: bug
