### ISSUE TITLE
Disabled button with span inside triggers click event

### ISSUE THREAD

**Issue by Bamyan** [DevExpress/testcafe#2902] opened 2018-09-26 14:38 UTC
### Are you requesting a feature or reporting a bug?

Bug.

### What is the current behavior?

When you have disabled native button with `span` element inside, the click event is triggered in IE and Edge browsers.

### What is the expected behavior?

Click event should not be triggered when a button is disabled.

### How would you reproduce the current behavior (if this is a bug)?

1. Create a disabled button with span element inside. Bind to the click event.
2. Try to click it in IE/Edge browser.

#### Provide the test code and the tested page URL (if applicable)

```
<button disabled onclick="myFunction()">Click me</button>

<p id="demo"></p>

<script>
function myFunction() {
  document.getElementById("demo").innerHTML = "Hello World";
}
</script>
```

### Specify your

* operating system: Win7 - IE, Win10 - Edge
* testcafe version: `0.20.1`
* node.js version: `8.9.4`

**Comment by AlexKamaev** [comment] 2018-09-27 08:44
I was able to reproduce the issue in Edge

**Comment by AlexKamaev** [comment] 2018-12-21 08:32
fixed in https://github.com/DevExpress/testcafe-hammerhead/issues/1880

**Comment by palpatine1991** [comment] 2019-02-15 15:07
@AlexKamaev I am not sure if this fix is correct. Let me show you the example:

In the very simple case your fix is correct. No console log is called when the button is clicked (and it behaves the same in TestCafe):

```
<div onclick="console.log('div')">
	<button disabled onclick="console.log('button')">
    	   Click me
  	</button>
</div>
```

On the other hand, when the disabled button contains any other element, the click events are called (but not in TestCafe!):

```
<!-- Logs "span" "div" -->
<div onclick="console.log('div')">
	<button  onclick="console.log('button')">
    	<span onclick="console.log('span')">Click me</span>
  	</button>
</div>
```

This is a problem in many cases. A good example might be for example the Angular Material library. You can look at disabled example here: https://material.angular.io/components/select/examples. When you manually click on the dropdown's disabled item, the dropdown menu is closed. When you do the same via TestCafe, it stays opened

**Comment by AlexKamaev** [comment] 2019-02-18 08:59
@palpatine1991
Thanks for the information. I see the inconsistency in this behavior. I'll reopen the issue.

**Comment by AlexKamaev** [comment] 2019-04-16 13:22
I'll mark this issue as a duplicate since we have similar issue in the `testcafe-hammerhead` repository: https://github.com/DevExpress/testcafe-hammerhead/issues/1931.

**Closed by AlexKamaev** 2019-04-16 13:22 UTC
Labels: AREA: client, SYSTEM: automations, TYPE: bug
