### ISSUE TITLE
Unable to click on footer menu in mobile browser

### ISSUE THREAD

**Issue by Arthy000** [DevExpress/testcafe#3515] opened 2019-03-01 14:51 UTC
### What is your Test Scenario?

Testing a website in mobile browsers.
The button I'm trying to click on is in a footer, meaning that scrolling is useless, but the footer from TestCafe is preventing the click from working.

### What is the Current behavior?

- The element is visible (checked with an expect())
- The element cannot be clicked because "The element that matches the specified selector is not visible." even though the click() action directly follows the expect() action

Full logs in the details

I slowed down the test to see what was happening:

- Our application's footer is mostly hidden by TestCafe's footer
- TestCafe tries to scroll to get the element into view (but in vain, as the footer stays at the bottom of the page, as it should)
- Our footer is set to disappear if the user scrolls down, so it does
- As the footer is still not visible, TestCafe keeps scrolling
- If I manually interfere with the test by scrolling up repeatedly the click works (with the short code included)

### What is the Expected behavior?

The element is visible so it can be clicked
(not sure if it is because TestCafe's footer is hiding it or because of something else)
I'd be happy with disabling the auto-scrolling of the click action, but haven't found a way to do that

### What is your web application and your TestCafe test code?

Here is a short TestCafe test code that shows the issue occurring (/!\ on mobile only /!\):

```javascript
import { Selector } from "testcafe";

fixture`POC`.page`https://m.circus.be/en/casino/casino-home`;

test("Open Submenu", async t => {
  await t
    //closing a popup that appears on mobile only and may interfere with the test
    .expect(Selector('div[class*="ath-container"]').exists)
    .ok({ timeout: 50000 })
    .expect(Selector('div[class*="ath-container"]').visible)
    .ok({ timeout: 10000 })
    .wait(3000)
    .click(Selector('div[class*="ath-container"]'))
    //done

    .expect(Selector("li.GamingHomeB.icon-and-text.g1-icon-dices").exists) // this is the Dice submenu
    .ok()
    .expect(Selector("li.GamingHomeB.icon-and-text.g1-icon-dices").visible)
    .ok()
    .wait(5000)
    .click(Selector("li.GamingHomeB.icon-and-text.g1-icon-dices"), {
      offsetX: 1,
      offsetY: 1
    });
});
```

<details>

<summary>Your complete test report:</summary>

```
× Feature: demo cucumber + testcafe - Scenario: The user opens the Gaming
 Menu

   1) The element that matches the specified selector is not visible.

      Browser: Chrome Mobile 72.0.3626 / Android 0.0.0

         171 |    .expect(page.gameMenu.othersSubmenu.exists)
         172 |    .ok()
         173 |    .expect(page.gameMenu.othersSubmenu.visible)
         174 |    .ok()
         175 |    .wait(30000)
       > 176 |    .click(page.gameMenu.othersSubmenu, { offsetX: 1,
      offsetY: 1 })
         177 |    .expect(page.gameMenu.jackpotSubmenu.self.exists)
         178 |    .ok()
         179 |    .expect(page.gameMenu.jackpotSubmenu.self.visible)
         180 |    .ok()
         181 |    .expect(page.gameMenu.winnersSubmenu.self.exists)

         at Then
      (.....\CucumberDemo\steps\mobile.js:176:6)
         at GherkinTestcafeCompiler._runStep

   (.....\CucumberDemo\node_modules\gherkin-testcafe\src\compiler.js:126:12)
         at GherkinTestcafeCompiler._resolveAndRunStepDefinition

   (.....\CucumberDemo\node_modules\gherkin-testcafe\src\compiler.js:114:21)
         at test
      (.....\CucumberDemo\node_modules\gherkin-testcafe\src\compiler.js:64:26)
```

</details>

### Steps to Reproduce:

1. Navigate to website
2. All submenus are displayed in the footer (that's how it is, I'm just testing, not dev)
3. Expecting existence of one of the elements in the footer
4. Expecting visibility of that element
5. Clicking on that element

### Your Environment details:

- testcafe version: 1.1.0 and 1.0.1 (there are no version of gherkin-testcafe compatible with 1.1.0 yet so I tried both, but had to keep 1.0.1)
- node.js version: v10.15.2
- command-line arguments: testcafe remote ./v3/testv2.js -t "Open Submenu"
- browser name and version: Chrome Mobile 72.0.3626
- platform and version: Android 9.0 (OnePlus 6T)

**Comment by AndreyBelym** [comment] 2019-03-04 15:42
The `li.GamingHomeB.icon-and-text.g1-icon-dices` element doesn't exist in my version of your site. The test runs fine after I've replaced it with the `li.DiceGamesGaming` element. Could you please apply this modification and run the test with your device?

Have you tried to run the test on a different device or in [Chrome Device Emulator](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html)? If you can, please visit https://www.mydevice.io from your device and share the device metrics reported by the site. It will help me reproduce the issue.

**Comment by Arthy000** [comment] 2019-03-05 09:40
Sorry, my mistake, wrong version of the website indeed. I corrected my initial message (the website, not the selector)

I can't reproduce it with Browserstack devices (sorry I didn't think of trying that earlier) or with Chrome Device Emulator. 
I still have the issue on my physical device though.

![screenshot_20190305-102004](https://user-images.githubusercontent.com/1800622/53794652-b3db8900-3f30-11e9-9545-f9bcd0ef052c.jpg)

**Comment by AlexKamaev** [comment] 2019-03-05 14:45
@Arthy000 
Thank you for providing additional information.
I checked the test on several real Android devices, on several devices on the BrowserStack. Also, I checked it on Chrome emulator with different [options](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html#emulator-parameters) based on your information.
However, I was not able to reproduce the issue. I would appreciate it you try to reproduce in on the emulator or on one of devices which are supported by the BrowserStack (https://www.browserstack.com/list-of-browsers-and-platforms/app_live).
In this case, we'll be able to debug the problem.

**Comment by Arthy000** [comment] 2019-03-05 16:31
I also tried different options for the chrome emulator to no avail. As I said I also tested most devices on Browserstack and didn't get the issue either.

So it looks like it is linked to my model :(

I'm not sure if there is anything else I can do to maybe figure out what is happening.

**Comment by AlexKamaev** [comment] 2019-03-11 12:21
@Arthy000 
I'll close this issue since none of us could reproduce it. If you are able to reproduce it on the BrowserStack or emulator, please feel free to open a new one.

**Closed by AlexKamaev** 2019-03-11 12:21 UTC
Labels: STATE: Need response
