### ISSUE TITLE
Question: Test Cafe freezing on page return application/json content-type

### ISSUE THREAD

**Issue by tiny-dancer** [DevExpress/testcafe#2855] opened 2018-09-13 06:31 UTC
### Are you requesting a feature or reporting a bug?

Question, potential bug

### What is the current behavior?

Clicking a link that navigates to another page freezes test cafe.  The only resolution to this is manually clicking the back button in the test browser.  The page being frozen on returns `application/json` content 

### What is the expected behavior?

If content-type is the cause, avoid freezing and allow browser level operations, such as `navigateTo`.

### How would you reproduce the current behavior (if this is a bug)?

Follow below sample code to a page return `application/json`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
 	await t.navigateTo(config.emailUrl);

    await t.click(await unreadEmailLink)
      .switchToIframe('#preview-html')
      .click(await Selector("a").withText("Approve"));
    
      // this code never gets hit
    await t
      .switchToMainWindow()
      .navigateTo(config.emailUrl);
```

### Specify your

* operating system: mac
* testcafe version: 0.22.1-alpha1 and 0.22.0
* node.js version: v10.10.0

**Comment by AndreyBelym** [comment] 2018-09-13 07:50
Hi @tiny-dancer! I think it's a duplicate of https://github.com/DevExpress/testcafe/issues/1471, TestCafe can't hadle page navigation to a non-HTML page.

**Closed by AndreyBelym** 2018-09-13 07:50 UTC
Labels: TYPE: question
