### ISSUE TITLE
Error in Hammerhead.js - New Contacts in Salesforce Lighting Experience '22

### ISSUE THREAD

**Issue by AndrewYoungQA** [DevExpress/testcafe#7168] opened 2022-06-17 18:43 UTC
### What is your Scenario?

Issue: When User logs into Salesforce, selects new Contact button, they are met with the following hammerhead.js error.

`Uncaught Error in $A.getCallback() [Maximum call stack size exceeded]
throws at http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:90:31. Caused by: Error in $A.getCallback() [Maximum call stack size exceeded]
{anonymous}()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:25015
eval()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
lt.passthruSetTrap [as set]()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
PropertyAccessorsInstrumentation._propertySetter()@hammerhead.js:20915:33`

### What is the Current behavior?

After selecting Contacts tab, or New Contact Button, the following error message is being returned.

`Uncaught Error in $A.getCallback() [Maximum call stack size exceeded]
throws at http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:90:31. Caused by: Error in $A.getCallback() [Maximum call stack size exceeded]
{anonymous}()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:25015
eval()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
lt.passthruSetTrap [as set]()@http://localhost:1401/MQtFtre6I!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
PropertyAccessorsInstrumentation._propertySetter()@hammerhead.js:20915:33`

### What is the Expected behavior?

After Selecting the Contact tab, or new Contact button, the user should be presented with a contact modal that allows users to input contact data.

### What is your public website URL? (or attach your complete example)

For our website there is no public URL, however you will be able to reproduce the error using the Trailhead Lightning Demo Site.
https://trailblazer.me/trailblazerlogin
https://resilient-shark-wlmrgy-dev-ed.lightning.force.com/lightning/o/Contact/list?filterName=Recent

### What is your TestCafe test code?

This is being recreated using the testcafe-hammerhead project and is reproducible through selections in the Trailhead site.

### Steps to Reproduce

1. Setup free Trailhead User at: https://trailblazer.me/trailblazerlogin , using email.
2. Installed the 'testcafe-hammerhead' project
3. Run Command Line : node node_modules/gulp/bin/gulp http-playground
4. In the field on the localhost:1400 page, we enter: https://trailhead.salesforce.com/en/content/learn/modules/accounts_contacts_lightning_experience/accounts-and-contacts-lightning
5. Select 'Proxy!' button
6. Select 'Log In' on salesforce / trailhead site.
7. Select 'Email' icon
8. Enter Email for account set up in 'Step 1'
9. Select 'Log in' Button.
10. Retrieve your Single use code from email sent to email address used in 'Step 1 / Step 8'
11. Select 'Continue' Button
12. Select 'Skip for Now' link
13. Confirm Page: https://trailhead.salesforce.com/en/content/learn/modules/accounts_contacts_lightning_experience/accounts-and-contacts-lightning loads successfully
14. Scroll to the bottom of the page and select the 'Launch' Button (note. On the initial run this step took a while for the launch button to become active, it eventually did however and was able to proceed)
15. Wait for Salesforce Lightning Env to load: https://resilient-shark-wlmrgy-dev-ed.lightning.force.com/lightning/page/home
16. *At this point you may hit the error. If not { Select the dot grid in the top left, then select 'Sales' from the ddl. If Sales is not visible search 'Sales' in the 'Search apps and items...' field.
![image](https://user-images.githubusercontent.com/40370410/174357206-7dff73e2-b906-460f-8e0e-90f041c45c02.png)
17. Once Sales Dashboard is loaded Select the 'Contacts' tab.
18. *At this point you will see the error message, if not select 'New' Contact button.
![image](https://user-images.githubusercontent.com/40370410/174357462-b252683d-b323-43c8-a64a-5fefa13558d3.png)
`Uncaught Error in $A.getCallback() [Maximum call stack size exceeded]
throws at http://localhost:1401/fQA1lRrUK!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:90:31. Caused by: Error in $A.getCallback() [Maximum call stack size exceeded]
{anonymous}()@http://localhost:1401/fQA1lRrUK!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:25015
eval()@http://localhost:1401/fQA1lRrUK!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
lt.passthruSetTrap [as set]()@http://localhost:1401/fQA1lRrUK!s!utf-8/https://static.lightning.force.com/usa59.sfdc-lywfpd/auraFW/javascript/m-U-Tf8BNfJufA5XwOVDIQ/aura_prod.js:62:29308
PropertyAccessorsInstrumentation._propertySetter()@hammerhead.js:20915:33`

### TestCafe version

1.19.0

### Node.js version

v16.15.1

### Command-line arguments

node node_modules/gulp/bin/gulp http-playground

### Browser name(s) and version(s)

Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by AndrewYoungQA** [comment] 2022-07-27 20:14
Using locally installed version of TestCafe.
1.20.0

**Comment by miherlosev** [comment] 2022-08-01 09:20
Hi @AndrewYoungQA,

We have not yet found the cause of this issue. We will update this thread once we have any news.

**Comment by aozomaro** [comment] 2022-08-31 13:37
Is there a plan to resolve this issue anytime soon?

**Comment by Asuza** [comment] 2022-10-05 14:57
Would it be reasonable for any of us to learn how to understand the issue and patch Hammerhead, or do you feel that this issue would be far too complex for a Hammerhead novice?

**Comment by miherlosev** [comment] 2022-10-10 07:39
Hi @Asuza,

If the issue is connected to the `with` statement, it's too complex for the outer contributor. You can try debugging the tested application to determine the cause of the issue.

**Comment by Aleksey28** [comment] 2023-04-04 06:25
Hi @kandl,

Thank you for the workaround.

**Comment by miherlosev** [comment] 2023-07-03 07:09
Hi

Starting from the 3.0.0 version, TestCafe introduced the new test run mode - [NativeAutomation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode). All described issues should be fixed in it. Try running the tests with the latest TestCafe version (`3.0.1`) and let us know your results.

**Closed** 2023-07-13 07:10 UTC
Labels: TYPE: bug, STATE: Need clarification, FREQUENCY: level 1
