### ISSUE TITLE
Gitlab CI tests failing

### ISSUE THREAD

**Issue by Meemaw** [DevExpress/testcafe#3273] opened 2019-01-01 11:30 UTC
### What is your Test Scenario?

Testing my login form.
 
### What is the Current behavior?

Tests pass locally but fails in Gitlab CI with error:
`Fatal server error:
(EE) Server is already active for display 99
	If this server is no longer running, remove /tmp/.X99-lock
	and start again.
(EE) `
 
### What is the Expected behavior?

Tests pass on gitlab CI

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

__pages__/LoginPage
```ts
import { Selector } from 'testcafe';

const testPassword = process.env['LOGIN_PASS'];
const testUser = process.env['LOGIN_USER'];

if (!testPassword) {
  throw new Error('Test password cannot be undefined. Set it through LOGIN_PASS env variable');
}

if (!testUser) {
  throw new Error('Test user cannot be undefined. Set it through LOGIN_USER env variable');
}

class LoginPage {
  emailInputSelector = 'input[name="email"]';
  passwordInputSelector = 'input[name="password"]';
  loginButtonSelector = 'button[type="submit"]';

  recoverLinkSelector = '[data-testid="recover"]';
  registerLinkSelector = '[data-testid="register"]';

  emailInput = Selector(this.emailInputSelector);
  passwordInput = Selector(this.passwordInputSelector);
  loginButton = Selector(this.loginButtonSelector);

  testUser = testUser as string;
  testPassword = testPassword as string;
}

export default LoginPage;
```

Test code
```ts
import LoginPage from '../../__pages__/LoginPage';

const { emailInput, loginButton, passwordInput, testPassword, testUser } = new LoginPage();

const baseUrl = 'http://localhost:3000/';

fixture('<Login />').page(baseUrl);

test('Logs in with correct credentials', async t => {
  await t
    .typeText(emailInput, testUser)
    .typeText(passwordInput, testPassword)
    .click(loginButton);
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
[0KRunning with gitlab-runner 11.5.0 (3afdaba6)
[0;m[0K  on docker-auto-scale fa6cab46
[0;m[0KUsing Docker executor with image circleci/node:10.14-browsers ...
[0;m[0KPulling docker image circleci/node:10.14-browsers ...
[0;m[0KUsing docker image sha256:b00e93f4b6c3f4ee151ccfe9f13eb5a5aad5b9d2280e5780734e17921ff33a9a for circleci/node:10.14-browsers ...
[0;msection_start:1546932983:prepare_script
[0KRunning on runner-fa6cab46-project-10227775-concurrent-0 via runner-fa6cab46-srm-1546932809-29fc24f3...
section_end:1546932984:prepare_script
[0Ksection_start:1546932984:get_sources
[0K[32;1mCloning repository...[0;m
Cloning into '/builds/Meemaw/meshwatch'...
[32;1mChecking out fb9f9353 as master...[0;m
[32;1mSkipping Git submodules setup[0;m
section_end:1546932986:get_sources
[0Ksection_start:1546932986:restore_cache
[0Ksection_end:1546932987:restore_cache
[0Ksection_start:1546932987:download_artifacts
[0K[32;1mDownloading artifacts for fe:install_packages_run_linters (142740351)...[0;m
Downloading artifacts from coordinator... ok      [0;m  id[0;m=142740351 responseStatus[0;m=200 OK token[0;m=rHVqvdWe
section_end:1546932999:download_artifacts
[0Ksection_start:1546932999:build_script
[0K[32;1m$ cd frontend[0;m
[32;1m$ node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js e2e[0;m
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[07:36:41] Using gulpfile /builds/Meemaw/meshwatch/frontend/gulpfile.js
[07:36:41] Starting 'e2e'...
[07:36:41] Starting 'clean'...
[07:36:41] Finished 'clean' after 13 ms
[07:36:41] Starting 'sete2e'...
[07:36:41] Finished 'sete2e' after 17 ms
[07:36:41] Finished 'e2e' after 33 ms
[32;1m$ echo $(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)[0;m
172.17.0.3
[32;1m$ LOGIN_USER="$E2ETEST_LOGIN_USER" LOGIN_PASS="$E2ETEST_LOGIN_PASS" yarn test:e2e:headless[0;m
yarn run v1.12.3
$ testcafe chrome:headless src/test/e2e --hostname 127.0.0.1 --app "yarn start && wait-on http://localhost:3000"
 Running tests in:
 - HeadlessChrome 71.0.3578 / Linux 0.0.0

 <Login />
 ✖ Logs in with correct credentials

   1) Failed to complete a request to "http://localhost:3000/" within the
      timeout period. The problem may be related to local machine's
      network or firewall settings, server outage, or network problems
      that make the server inaccessible.

      Browser: HeadlessChrome 71.0.3578 / Linux 0.0.0

          7 |
          8 |fixture('<Login />').page(baseUrl);
          9 |
         10 |test('Logs in with correct credentials', async t => {
         11 |  await t
       > 12 |    .typeText(emailInput, testUser)
         13 |    .typeText(passwordInput, testPassword)
         14 |    .click(loginButton);
         15 |});
         16 |

         at Object.<anonymous>

   (/builds/Meemaw/meshwatch/frontend/src/test/e2e/Login/Login.e2e.ts:12:6)
         at <anonymous>

   (/builds/Meemaw/meshwatch/frontend/src/test/e2e/Login/Login.e2e.ts:7:71)
         at __awaiter

   (/builds/Meemaw/meshwatch/frontend/src/test/e2e/Login/Login.e2e.ts:3:12)
         at test

   (/builds/Meemaw/meshwatch/frontend/src/test/e2e/Login/Login.e2e.ts:10:52)
         at markeredfn

   (/builds/Meemaw/meshwatch/frontend/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>

   (/builds/Meemaw/meshwatch/frontend/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn

   (/builds/Meemaw/meshwatch/frontend/node_modules/testcafe/src/test-run/index.js:239:19)
         at TestRun._executeTestFn

   (/builds/Meemaw/meshwatch/frontend/node_modules/testcafe/src/test-run/index.js:235:38)
         at _executeTestFn
      (/builds/Meemaw/meshwatch/frontend/node_modules/testcafe/src/test-run/index.js:284:24)



 1/1 failed (27s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
section_end:1546933042:build_script
[0Ksection_start:1546933042:after_script
[0K(EE) 
Fatal server error:
(EE) Server is already active for display 99
	If this server is no longer running, remove /tmp/.X99-lock
	and start again.
(EE) 
section_end:1546933043:after_script
[0Ksection_start:1546933043:upload_artifacts_on_failure
[0Ksection_end:1546933045:upload_artifacts_on_failure
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>
 
### Your Environment details:
 
* testcafe version:                   0.23.3
* node.js version:                    10.14
* command-line arguments:  "testcafe chrome:headless src/test/e2e --hostname 127.0.0.1 --app \"yarn start && wait-on http://localhost:3000\""
* browser name and version: Browser: HeadlessChrome 71.0.3578 / Linux 0.0.0

**Comment by AlexSkorkin** [comment] 2019-01-04 10:54
Thank you for reaching out to us and submitting this issue. 
 
However, I get the AccessDenied code when accessing your URL:

![image](https://user-images.githubusercontent.com/995726/50684916-4d1d1a80-1028-11e9-8a7c-73bf3c231756.png)

Are there any special steps I need to perform in order to access it? Does your application have restrictions by the country?
 
In addition, please provide your page model and helpers:
 
import LoginPage from '../../__pages__/LoginPage';
import { getLocation } from '../__helpers__/client';

**Comment by Meemaw** [comment] 2019-01-04 11:22
@AlexSkorkin Hey Alex, The link seems to expire on gitlab CI. I have updated it with a new one. I have also added the code you asked for.

**Comment by AndreyBelym** [comment] 2019-01-07 13:45
Thank you for the provided information! I think that the problem can be caused by some incorrect configuration in your CI image or build steps. 

Could you please provide your GitLab CI YML configuration files and a Dockerfile of your CI image if it is customized?

**Comment by Meemaw** [comment] 2019-01-08 07:43
Hey @AndreyBelym ,

```
test:e2e:
  image: circleci/node:10.14-browsers
  before_script:
    - cd frontend
    - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js e2e
  script:
    - LOGIN_USER="$E2ETEST_LOGIN_USER" LOGIN_PASS="$E2ETEST_LOGIN_PASS" yarn test:e2e:headless
  dependencies:
    - fe:install_packages_run_linters
```

Commands in before_script are not important (setting up env). `Dependencies` are just node_modules from previous job. I used `image: circleci/node:10.14-browsers` as written in your docs and it worked at first but then suddenly stopped working for every pipeline.

```
"test:e2e:headless": "testcafe chrome:headless src/test/e2e --hostname 127.0.0.1 --app \"yarn start && wait-on http://localhost:3000\""
```

**Comment by Meemaw** [comment] 2019-01-14 17:19
@AndreyBelym, I have invited you as the developr to the project.

**Comment by AndreyBelym** [comment] 2019-01-15 09:40
Thank you for the invitation to your project. I guess I've found the cause of the problem but can't currently completely understand why it occurs.
 
In particular, it is unclear why `wait-on` doesn't wait until the server starts and can respond to a browser. I've created a fork example of your repository and invited you as a maintainer. Check job #145857823 for the build log that illustrates the problem. I added the `curl http://localhost:3000` to check how the server handles browser requests. `curl` waited for a minute until the server responded. After that the test passed.

You can remove my fork when you are done with examining the build. 
 
Thus, I'll close this issue because it seems to be related to `wait-on` but not to TestCafe. You can create an issue about this problem in the [jeffbski/wait-on](https://github.com/jeffbski/wait-on) repository instead.

**Closed by AndreyBelym** 2019-01-15 09:40 UTC
Labels: STATE: Need clarification
