### ISSUE TITLE
TypeError: Cannot read property 'destUrl' of null

### ISSUE THREAD

**Issue by kevin-inrupt** [DevExpress/testcafe#5555] opened 2020-09-17 16:45 UTC
### What is your Test Scenario?
I have developed a suite of tests against https://podbrowser.inrupt.com. These tests execute correctly.

Due to issues selecting page elements, I am attempting to integrate `@testing-library/testcafe` library. After including a reference to @testing-library/dom/dist/@testing-library/dom.umd.js in .`testcaferc.json` as per https://testing-library.com/docs/testcafe-testing-library/intro (no other changes to the test code were made), the same tests now fail with error:

```
Error in fixture.beforeEach hook -
An error occurred in the '@testing-library/dom/dist/@testing-library/dom.umd.js' module injected into the tested page. Make sure that this module can be executed in the browser environment.

Error details:
TypeError: Cannot read property 'destUrl' of null
```
 
### What is the Current behavior?
When executing `testcafe edge ./tests/login.js`, an error is displayed:
```
Error in fixture.beforeEach hook -
An error occurred in the '@testing-library/dom/dist/@testing-library/dom.umd.js' module injected into the tested page. Make sure that this module can be executed in the browser environment.

Error details:
TypeError: Cannot read property 'destUrl' of null

/// Login/Logout workflow
fixture('Login/Logout')
    .beforeEach( async t => {
        await t
            .useRole(nssUser);
    });

/// Login & Logout
test
    ("Log user into & out of PodBrowser", async t => {

at <anonymous> (C:\Projects\GitHub\destURL\tests\login.js:11:14) // This is the `.useRole(nssUser);` line
at <anonymous> (C:\Projects\GitHub\destURL\tests\login.js:8:1)
```
 
### What is the Expected behavior?
The tests execute correctly as was the case prior to the change.
 
### What is your web application and your TestCafe test code?
Attached is a stripped down test that illustrates the error.
[destURL.zip](https://github.com/DevExpress/testcafe/files/5240634/destURL.zip)

<details>
<summary>login.js (test code):</summary>

 
The `login.js` test code is shown below:
```
// Page Models
import navigationPage from '../page-models/navigationPage.js';

// Roles
import { nssUser } from '../roles/roles.js';

/// Login/Logout workflow
fixture('Login/Logout')
    .beforeEach( async t => {
        await t
            .useRole(nssUser);
    });

/// Login & Logout
test
    ("Log user into & out of PodBrowser", async t => {

    // Login
    await t
        .expect(navigationPage.breadcrumbs.nth(-1).textContent).contains("All files", "Breadcrumbs read 'All files'");
    });
```
</details>

<details>
<summary>roles.js (User Role)</summary>

```
import { Role } from 'testcafe';
import loginPage from '../page-models/loginPage.js';

// NSS User
export const nssUser = Role('https://podbrowser.inrupt.com', async t => {

    await t.typeText(loginPage.identityCombobox, 'https://dev.inrupt.net')

    }, { preserveUrl: true });
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Using locally installed version of TestCafe.
 Running tests in:
 - Microsoft Edge 85.0.564.51 / Windows 10

 Login/Logout

----
Microsoft Edge 85.0.564.51 / Windows 10
DEBUGGER PAUSE ON FAILED TEST:
- Error in fixture.beforeEach hook -
An error occurred in the '@testing-library/dom/dist/@testing-library/dom.umd.js' module injected into the tested page. Make sure that this module can be executed in the browser environment.

Error details:
TypeError: Cannot read property 'destUrl' of null

Browser: Microsoft Edge 85.0.564.51 / Windows 10

6 |
7 |/// Login/Logout workflow
8 |fixture('Login/Logout')
9 |    .beforeEach( async t => {
10 |        await t
> 11 |            .useRole(nssUser);
12 |    });
13 |
14 |/// Login & Logout
15 |test
16 |    ("Log user into & out of PodBrowser", async t => {

at <anonymous> (C:\GitHub\destURL\tests\login.js:11:14)
at <anonymous> (C:\GitHub\destURL\tests\login.js:8:1)
----
```
</details>

### Steps to Reproduce:

1. Extract the code from the attached zipfile.
2. If necessary, install [TestCafe Testing Library](https://testing-library.com/docs/testcafe-testing-library/intro#install)
3. Execute `> testcafe edge ./tests/login.js`.
4. Error is displayed.
 
### Your Environment details:
 
* testcafe version: 1.9.2                  
* node.js version: v12.18.3                   
* command-line arguments: testcafe edge ./tests/login.js
* browser name and version: MS Edge Version 85.0.564.51 (Official build) (64-bit)
* platform and version:  Windows 10 64-bit
* other:                                   

## Notes
Speaking with support at testing-library, they identified the source of the error was the setting of the browser URL as part of the Role rather than an explicit `.page(...)` in the fixture.

If you add a line `.page('https://podbrowser.inrupt.com')` to the `fixture`, the test executes without the error.

While this works, it does mean the page is loaded twice.

**Comment by benmonro** [comment] 2020-09-17 17:41
To add on to @kevin-inrupt excellent description of the problem.  There problem here is the general use of client scripts on a fixture that doesn't set .page

**Comment by AndreyBelym** [comment] 2020-09-18 07:48
Thank you for your report. I reproduced the issue. It looks like it's similar to the case discussed here: [https://github.com/DevExpress/testcafe-hammerhead/issues/2399](https://github.com/DevExpress/testcafe-hammerhead/issues/2399). So, I changed the frequency level of DevExpress/testcafe-hammerhead#2399, and I'll close this issue as a duplicate. As a workaround, you can add ``.page `example.com` `` to your fixture or test declarations.

**Closed** 2020-09-21 07:48 UTC
