### ISSUE TITLE
Unable to complete checkout while using venmo

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#7716] opened 2023-05-23 01:41 UTC
### What is your Scenario?

After the user enters the username/password for venmo in the popup, the user should get redirected back to the checkout page and venmo information should be saved

### What is the Current behavior?

After the user enters the username/password for venmo in the popup, the user gets redirected back to the checkout page **but venmo information is not carried over. Sometimes there's an error that says Cannot switch to the window.**

### What is the Expected behavior?

After the user enters the username/password for venmo in the popup, the user should get redirected back to the checkout page and venmo information should be saved as per this screenshot

<img width="572" alt="Screenshot 2023-05-22 at 4 45 08 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/ecd3d1cc-885d-4e66-b5f7-e955559b149f">

### What is your public website URL? (or attach your complete example)

https://www.chegg.com

### What is your TestCafe test code?

```
import {t, ClientFunction, Selector} from 'testcafe';
import { addQueryStringParamToUrl} from './shared';
const loginUrl = `https://www.chegg.com/auth?action=login`;
const emailForSignIn = Selector('input[id*="email"]');
const passForSignin = Selector('input[type="password"]');
const signInButton = Selector('button').withText('Sign in');
const seeAnswer = Selector('span').withText('See Answer');
const studyPack = Selector('button[data-test="product-CSP-button"]');
const startVenmo = Selector('*[aria-label="Start Venmo"]');
const VenmoNextBtn = Selector('*[data-testid="button-next"]');
const VenmoEnterPassCTA = Selector(
  '[data-testid="loginWithPasswordInstead"]'
);
const VenmoCardLogo = Selector('[data-test="VENMO_CARD_LOGO"]');
const enteryourvenmoemail:string;
const enteryourvenmopass:string;

const forceControlExperimentQueryParams =
  '?force-exp-unlimited_paq_test=control' +
  '&force-exp-paq_framing_experiments_test=control';
const expertQnAUrl =
  `https://trunk.live.test.cheggnet.com/` +
  'homework-help/questions-and-answers/question-13-q53369801' +
  forceControlExperimentQueryParams;


// user log in/log out methods
async function userLogInWithCredentials(
  email: string,
  password: string
): Promise<void> {
  await t.navigateTo(loginUrl);
  await t
    .typeText(emailForSignIn, email, { paste: true })
    .typeText(passForSignin, password, { paste: true })
    .click(signInButton)
    .wait(6000);
  console.log(`Logged in as user: ${email}`);
}

fixture`User log in`
  .meta({ fixtureID: 'f-0001', author: 'GROWTH', app: '' })
  .beforeEach(async (t) => {});

test.meta({
  testID: 't-0001',
})(
  'Sign in',
  async (t) => {
    await userLogInWithCredentials('sample_venmo_user@chegg.com', 'Password@123@123');
    await t.navigateTo(
      addQueryStringParamToUrl(
        expertQnAUrl,
        `setCountry=US`
      )
    );
    await t.click(seeAnswer);
    await t.click(studyPack);
    const getURL = await ClientFunction(() => window.location.href)();
    const newUrl = getURL + '&force-exp-venmo_payment_method_test=test';
    await t.navigateTo(newUrl);
    await t.navigateTo(newUrl);
    // the below doesn't always work on first click, clicking twice as workaround
    await t.click(startVenmo);
    await t.click(startVenmo);
    await t.wait(5000);
    await t.typeText('#email', enteryourvenmoemail).pressKey('enter');
    await t.click(VenmoEnterPassCTA);
    await t
      .typeText('[data-testid="text-input-password"]', enteryourvenmopass)
      .pressKey('enter')
      .wait(7000);
    await t.expect(VenmoCardLogo.visible).ok();
 });
```

### Screenshots

**Expected page after completing the checkout flow with the venmo information saved and the venmo card logo visible**

<img width="572" alt="Screenshot 2023-05-22 at 4 45 08 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/bcbbe5a6-0712-4a6e-84cc-527001094fdb">

**Occasional error Cannot switch to the window**

<img width="482" alt="Screenshot 2023-05-22 at 8 08 50 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/d2b1b679-a74c-4c15-906c-6d1a134d5618">

### Steps to Reproduce

1. Create a venmo account 
2. Attach a payment method to the account
3. Plug in the venmo email/password into the variables in the code
4. Run the test
5. In the step after entering the venmo password, user should be redirected back to the checkout page and the venmo information should be there ( the venmo card logo should be visible). **In this case, the user gets redirected to the checkout page but the venmo information is not there (the venmo card logo is not visible)**

### TestCafe version

2.5.1-rc.1

### Node.js version

18.16.0

### Command-line arguments

npx testcafe chrome tests/sampleVenmoTest.ts

### Browser name(s) and version(s)

Chrome 113.0

### Platform(s) and version(s)

MacOs Ventura

### Other

As this involves venmo and payment methods, I cannot provide a working example with an actual username/password because those accounts needs to actually have some payment information attached to them. If possible, it would involve creating a venmo account, attaching payment to that account and then running the sample code to see the issue.

I am also attaching a HAR file and a TestCafe log in hopes that this perhaps might shed some light as to what is going on if the above is not possible.

HAR file:
https://upload.disroot.org/r/JfyD2NNp#nORD+mcKTVUJFAbyMLH8wWyrlePfDSNlkRe5ELMP5ek=

TestCafe log:
https://upload.disroot.org/r/ECQP6vuw#VKuXA0cWrLSmraSfmX61hGS2i/EmIe7zBeyOrAnTnOY=

**Comment by Aleksey28** [comment] 2023-05-24 07:28
Hi @ayemelyanenko-chegg,

I would be happy to assist you and diagnose this issue. However, we need a reproducible example without any extra effort. Please share your access data for the Venmo test to [support@devexpress.com](mailto:support@devexpress.com) and I'll continue researching this issue.

**Comment by ayemelyanenko-chegg** [comment] 2023-06-06 23:19
@Aleksey28 I tried running with --disable-http2 option and the result was the same.

I actually tried setting up a paypal/venmo sandbox locally where the end result would be doing a mock payment and then seeing a native dialog with the text that the venmo transaction was complete.

<img width="1088" alt="Screenshot 2023-06-06 at 3 43 00 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/4daf40c8-400c-4da7-ba18-54e5c9b3bc5b">

When running the same test with TestCafe, the native dialog never shows up so I think this could be the same issue that I described originally? 

If you wish to try to reproduce locally, here are the steps:

Clone https://github.com/ayemelyanenko-chegg/js-sdk-venmo-sandbox
CD into js-sdk-venmo-sandbox
In terminal, export NODE_OPTIONS=--openssl-legacy-provider
npm install
npm start
The app should load on localhost:3000
npx testcafe chrome sampleVenmoTest.ts -L -e
After the test run, the native dialog should show up as seen in screenshot above but it never does. Sometimes, there's an error about the native dialog not being handled but it's not seen after the test

<img width="1198" alt="Screenshot 2023-06-06 at 4 18 11 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/e81b7a0d-a7b0-477e-a141-e415f2f03f48">

Test code:
```
import { t, Selector } from "testcafe";
const venmoCheckbox = Selector('*[name="enableVenmo"]');
const venmoButton = Selector('*[aria-label="venmo"]');
const frame = Selector('*[name*="__paypal_buttons"]');
const payWithPayPal = Selector('*[aria-label="Pay with PayPal"]');
const email = Selector('#email');
const password = Selector('#password');
const next = Selector('#btnNext');
const logIn = Selector('#btnLogin');
const submitPay = Selector('#payment-submit-btn');

fixture`Sample test`
  .meta({
    fixtureID: 'f-0001',
    author: 'GDG',
    app: '',
  })
  .beforeEach(async (t) => {
    await t.navigateTo(
      'http://localhost:3000');
  });

test.meta({
  testID: 't-0001',
  testType: 'Smoke',
  testRailCaseId: '277066',
  priority: 'p1',
})('Sample test', async (t) => {
  await t.click(venmoCheckbox);
  await t.switchToIframe(frame);
  await t.click(venmoButton);
  await t.switchToMainWindow();
  await t.click(payWithPayPal);
  await t.typeText(email, 'sampleApp154154@hotmail.com');
  await t.click(next);
  await t.typeText(password, '!Venmo10');
  await t.click(logIn);
  await t.click(submitPay);
  await t.wait(5000);
  // at this point, the native dialog with the ok button should be visible but it's not
});
```

**Comment by Artem-Babich** [comment] 2023-06-09 06:53
Hi @ayemelyanenko-chegg,

I just tried to run your sample and I'm getting other errors:

```
GET https://localhost:8443/sdk/js?client-id=alc_client1&enable-funding=venmo net::ERR_CONNECTION_REFUSED
Failed to load the PayPal JS SDK script. TypeError: Failed to fetch
```

As a result, the button that should be clicked in the test is not visible on the page at all:
![](https://github.com/DevExpress/testcafe/assets/51639399/90a6daa7-5833-45cc-b0ff-2741984dbd1c)

It looks like some part of your sample doesn't work as expected. Please update your sample so that I can run it and reproduce the problematic behavior.

**Comment by ayemelyanenko-chegg** [comment] 2023-06-09 17:26
@Artem-Babich Hi, thanks for trying to reproduce. It still works fine on my machine. I deleted the repo and then cloned it again.

https://recordit.co/vFnBz6kdPI

I wonder, what is the node version that you're using? I'm on 18.16.0, maybe you're using a different node version? Could you also please try to delete the node_modules and package.json after cloning the repo and then running npm install?

Just in case it might help, I got a log file as well

https://upload.disroot.org/r/qHNnaw8H#y9IyoqszbgoWBa0jcsPEUUcK3kQdsJ3tAbgz6wRufCQ= 

The below is what I get from the console when running with debug mode:

```
hammerhead:service-message Service message {"cmd":"ready","status":{"id":"22603.89999999106","isCommandResult":true,"executionError":null,"pageError":{"code":"E45","isTestCafeError":true,"callsite":null,"dialogType":"alert","pageUrl":"http://localhost:3000/","id":"sDwAKXv"},"resent":false,"result":null,"consoleMessages":{"CT5n4TMU0":{"log":[],"info":[],"warn":["rest_api_v2_checkout_orders_capture_error [object Object]","capture_order_call_rest_api_error [object Object]"],"error":[]}},"isPendingWindowSwitching":false,"isObservingFileDownloadingInNewWindow":false,"isFirstRequestAfterWindowSwitching":true,"debug":"","warnings":null},"disableResending":true,"allowRejecting":true,"sessionId":"eFis3UV9M"}, result {"type":"unlock-page"} +9s
```

**Comment by Artem-Babich** [comment] 2023-06-13 06:41
Thank you for your reply. We will close the issue for now. Feel free to update this thread if you reproduce it.

**Closed by Artem-Babich** 2023-06-13 06:41 UTC
Labels: TYPE: bug, STATE: Need response
