### ISSUE TITLE
Enters a loop when using Azure AD for authentication when running tests in chrome (both headless and browser)

### ISSUE THREAD

**Issue by zsid** [DevExpress/testcafe#4024] opened 2019-07-12 08:37 UTC
### What is your Test Scenario?
Authenticate in our app using Azure AD.
 
### What is the Current behavior?
When we run our tests in `chrome` both `headless` and in the `browser`, the first test always enters a loop which results in the tests failing. Login works for every other test afterwards.
 
### What is the Expected behavior?
Authenticate successfully in all tests without entering the loop. It works if you pass the test and manually submit your authentication details. It also works in `safari` without entering the loop.

### What is your web application and your TestCafe test code?
I have created a [repo](https://github.com/zsid/testcafe-azure-ad) with test code. There are instructions on how to set up an Azure AD instance (takes 5min to do that).

**Comment by zsid** [comment] 2019-07-15 08:45
Let me know if you are having troubles with starting up the app with Azure. Happy to help

**Comment by VasilyStrelyaev** [comment] 2019-07-15 15:39
Thank you for the detailed instructions. I have reproduced this behavior.
 
We need time to research it and determine its cause. We will update this issue once we find a solution.

**Comment by zsid** [comment] 2019-07-16 10:16
Great, thanks. I am looking forward to your fix 😄

**Comment by zsid** [comment] 2019-08-06 10:02
Hey @VasilyStrelyaev, do you know when you would be looking into this?

**Comment by aleks-pro** [comment] 2019-08-06 14:24
Hello @zsid ,

We are going to look into this issue this week. We will update this thread as soon as we have any news.

**Comment by zsid** [comment] 2019-08-07 15:58
I am not sure if this is going to help but the infinite loop is happening only the first time and it looks like similar to (this is all speculations 😄):
```
Infinite acquire token loops and AADSTS50058 error. When an application running on Microsoft Edge tries to acquire a token for a resource, the application may get stuck in an infinite loop of the acquire token call along with the following error from AAD in your network trace:

Error :login_required; Error description:AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com)
```

That could be a good starting point. You can read more about it in [microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-known-issues-ie-edge-browsers)

**Comment by Farfurix** [comment] 2019-08-13 10:10
@zsid 

Hello,

While we are working on it, I suggest you use the following "[`preserveUrl`](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#optionspreserveurl)" workaround:

```ts
import { Role, Selector } from "testcafe";
import config from "../config";

export async function loginAzureAD(t: any) {
  await t
    .typeText(
      Selector("input").withAttribute("type", "email"),
      config.azureAdUsername
    )
    .click(Selector("input").withAttribute("type", "submit"))
    .typeText(
      Selector("input").withAttribute("type", "password"),
      config.azureAdPassword
    )
    .click(Selector('#idSIButton9'))
    .click(Selector('#idBtn_Back'));
}

export const azureAdUser = Role(`${config.baseUrl}`, loginAzureAD, { preserveUrl: true }); // "preserveUrl" workaround

export default {
  azureAdUser
};
```

Result:
```
>yarn test:e2e:chrome
yarn run v1.13.0
$ testcafe chrome testcafe/**/*.test.ts --speed 0.7
 Running tests in:
 - Chrome 76.0.3809 / Windows 10.0.0

 HomePage Navigation
 √ Navigation exists on the home page with two links
 √ Clicking the first link takes you to the orders list page
 √ Clicking the second link takes you to the snacks page


 3 passed (19s)
Done in 37.88s.

```

**Comment by Farfurix** [comment] 2020-02-13 12:02
https://github.com/DevExpress/testcafe/issues/4754#issuecomment-585722502

**Comment by niba** [comment] 2020-05-20 06:16
Hey
I have the same problem with [portal.azure.com](portal.azure.com). Tests can stuck in the auth loop. The loop doesn't occur 100% times, sometimes tests pass but more likely they will stuck

I saw some comments that this is resolved with a new version of msal library but I don't think that it's applicable to portal.azure

The `preserveUrl` option doesn't work for this case

**Comment by Farfurix** [comment] 2020-05-21 10:37
@niba 

Thank you. We'll take this into account.

**Comment by aviita** [comment] 2020-10-05 16:36
I am also having issues with authentication and mentioned some of my details with issue #4834. I cannot see how that above `preserveUrl` would work with my use case as I am using MSAL.js and Azure AD B2C that uses our Azure AD B2C that at the end of the flow passes the JWT token to the web app with redirect URL.

**Comment by AlexKamaev** [comment] 2020-12-07 09:51
I reproduced the issue from the first post and researched it. I tried to use the `--disable-page-caching` flag and it solved the issue. Please refer to the following article for details: [Test Actions Fail After Authentication](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/authentication.html#test-actions-fail-after-authentication)

I'll close this ticket since the issue is solved. If you still face a similar problem please create a separate issue and prepare an example that reproduces the issue.

**Closed by AlexKamaev** 2020-12-07 09:51 UTC
Labels: FREQUENCY: level 2, STATE: Need research
