### ISSUE TITLE
The typeText action doesn't work in third-party iframe in Safari

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#4851] opened 2020-03-10 13:49 UTC
https://stackoverflow.com/questions/60510264/testcafe-typetext-on-ios-devices-does-not-work-on-third-party-iframe

### What is your Test Scenario?
Type text into the input element placed insite a third-party iframe.
 
### What is the Current behavior?
The t.typeText action doesn't enter any character in Safari
 
### What is the Expected behavior?
It should work as it works in other browsers.
 
### What is your web application and your TestCafe test code?
https://github.com/norhak/norhak.git

### Steps to Reproduce:

1. Clone the repository mentioned above
2. Call npm i
3. Run tests in Safari:
`testcafe safari ./spec`
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    12.16.1
* command-line arguments:  testcafe safari ./spec
* browser name and version: Safari
* platform and version:          MacOS Catalina

**Comment by AlexanderMoiseev** [comment] 2020-03-23 11:39
is duplicate of https://github.com/DevExpress/testcafe/issues/4793

**Closed** 2020-03-23 11:39 UTC
Labels: BROWSER: Safari, BROWSER: iOS/Safari, OS: Mac, STATE: Duplicate, TYPE: bug
