### ISSUE TITLE
ClientFunction(() => document.title) does not work on version 1.9.3

### ISSUE THREAD

**Issue by Meemaw** [DevExpress/testcafe#5561] opened 2020-09-20 10:59 UTC
We have a helper function defined as follows:

```javascript
export const getTitle = ClientFunction(() => document.title);
```

In the test we do an assertion like this:

```js
  await t
    .expect(getTitle())
    .eql('Insight | Login')
```

This code works on 1.9.2 but does not work on 1.9.3

Context: it's a NextJS application which "changes" title on page navigation.

**Comment by miherlosev** [comment] 2020-09-21 07:47
Hi @Meemaw 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a small example so that we can reproduce it on our side?

**Comment by Meemaw** [comment] 2020-09-21 12:04
Reproducer:

```js
import { ClientFunction } from 'testcafe';

fixture('reproducer').page('https://app.dev.snuderls.eu');

const getTitle = ClientFunction(() => document.title);

test('Should work', async (t) => {
  await t.expect(getTitle()).eql('Insight | Login');
});
```

**Comment by miherlosev** [comment] 2020-09-21 12:40
Thank you for the detailed description. I've reproduced the problem.

**Comment by miherlosev** [comment] 2020-09-22 05:23
Duplicate of https://github.com/DevExpress/testcafe/issues/5559

**Closed by miherlosev** 2020-09-22 05:23 UTC
Labels: FREQUENCY: level 2, TYPE: bug
