### ISSUE TITLE
User actions (moving and/or resizing browser windows) impact test results

### ISSUE THREAD

**Issue by titerman** [DevExpress/testcafe#5355] opened 2020-07-23 14:05 UTC
### Setup:
testcafe -v `1.9.0-alpha.2`
node -v `v12.16.1`

The test:
```JavaScript

import { Selector, ClientFunction } from 'testcafe';

fixture `Devexpress`
    .page('https://www.devexpress.com');

test('Switch to the previous window', async t => {
    const testcafe = await t.openWindow('http://devexpress.github.io/testcafe')
          .switchToPreviousWindow()
          .openWindow('http://devexpress.github.io/testcafe/documentation/');
});
```
### Current behavior:

Sometimes (not always!) and, seemingly, only when the browser window is resized or moved during the test, the `Cannot find the previous window` error is thrown. I do not know if this behavior is related to the newly implemented window management functionality, or if it can be reproduced in earlier versions of testcafe.

The following screen recording shows two consecutive launches of the same test with two different results (**BANDWIDTH WARNING: 5MB GIF**):

![screencast](https://user.fm/files/v2-c03e938a1026444eed08c3fcd158b5b7/screencast.gif)

### Expected behavior: 

Consistent test results

**Comment by AlexKamaev** [comment] 2021-01-19 10:42
It looks like the cause of the issue is the problem with FF, which was fixed in https://github.com/DevExpress/testcafe/pull/5867
I was able to reproduce the issue on the TestCafe 1.10.1 version, but I cannot reproduce it on the 1.10.2-alpha.1 version.

**Closed by AlexKamaev** 2021-01-19 10:42 UTC
Labels: SYSTEM: window management, TYPE: bug
