### ISSUE TITLE
Tests fail to run on Edge Insiders Preview

### ISSUE THREAD

**Issue by trodrigues** [DevExpress/testcafe#2598] opened 2018-07-05 17:22 UTC
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

When I try to run tests on Edge's Insider Preview version, the cursor moves very very slowly and the test just seemingly times out before anything can ever happen.

I've made a video of the current behavior with my phone (unfortunately I couldn't get an OBS window capture working, assuming Insider Preview shenaningans as well): https://photos.app.goo.gl/XfQnk5jxoBQSStmY8

### What is the expected behavior?

The cursor moves normally and the tests run. The same tests run fine on the latest stable Edge build on Browserstack.

### How would you reproduce the current behavior (if this is a bug)?

Install Windows Insider Preview with the following options:
- What kind of content would you like to receive: The next version of Windows
- What pace do you want to get new builds: Slow

This means it's not essentially the latest and greatest but it's still some of the new stuff that isn't on stable builds yet.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://web.laterpay.net/dialog/entry

Test code

```js
import { Selector } from "testcafe";

fixture `Login`;

test
  .page("https://web.laterpay.net/dialog/entry")
  (`Check a box`, async t => {
    await t
      .click("#privacyPolicyChk")
  });
```

### Specify your

* operating system: Windows 10 Home Insider Preview, 1803, build 17692.1004
* testcafe version: 0.20.4
* node.js version: 10.6.0

**Comment by AndreyBelym** [comment] 2018-08-07 08:42
Hi @trodrigues, do you experience the problem on newer WIndows builds?

**Comment by trodrigues** [comment] 2018-08-07 13:00
Hi @AndreyBelym! I haven't tried it yet, but I noticed the RS5 update came out last week so I'll try and find some time to give it another go.

**Comment by trodrigues** [comment] 2018-08-08 17:37
I just tried this on Windows build 17713.1002 with Edge's 43.17713.1000.0 and with Testcafe's 0.21.1 and the problem still persists.

**Comment by b1tzer0** [comment] 2018-10-25 18:21
I am having the same issue when attempting to do a click event with Microsoft Edge
Windows 10 Pro
Version 1809
Build 17763.55

Edge: 44.17763.1.0
EdgeHTML: 18.17763

TestCafe Studio: 0.3.0

**Comment by AndreyBelym** [comment] 2019-02-07 14:42
I close the issue because I can't reproduce it with Edge 18.17763, Windows 1809 and TestCafe 1.0.0. Feel free to reopen the issue if you can provide additional details that can be used to reproduce the problem.

**Closed by AndreyBelym** 2019-02-07 14:42 UTC
Labels: TYPE: research
