### ISSUE TITLE
Native Automation seems not working for `.checked`, `ctrl+a` in pressKey(), `stringifyRequestBody: true` in `RequestLogger`, service worker

### ISSUE THREAD

**Issue by daenamkim** [DevExpress/testcafe#7667] opened 2023-04-27 09:57 UTC
### What is your Scenario?

In order to use some packages using [private](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) in test, I have been testing from [--experimental-proxyless](https://testcafe.io/404236/release-notes/framework/2022-12-29-testcafe-v2-2-0-released#experimental-proxyless-mode) to [native automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) mode for quite amount of time.

### What is the Current behavior?

I found some issues that I could not resolve.

- `.checked` of Selector is always `false` no matter click
- `ctrl+a` does not work for `pressKey()`
- `stringifyRequestBody: true` returns broken string
- service worker is not working at all

This attached file is for a demo what I have tried to confirm on my side:

[testcafe-typescript-vue-report.zip](https://github.com/DevExpress/testcafe/files/11342154/testcafe-typescript-vue-report.zip)

### What is the Expected behavior?

All should be working as in normal mode which is no `--native-automation`

### What is your public website URL? (or attach your complete example)

Please see `testcafe-typescript-vue-report.zip` file above

### What is your TestCafe test code?

Please see `testcafe-typescript-vue-report.zip` file above

### Steps to Reproduce

(See `README.md`)

```
yarn install
yarn serve
```

Open another terminal and run:

```
yarn test:na
```

### TestCafe version

2.5.0

### Node.js version

18.14.0

### Command-line arguments

(See package.json) npx testcafe chrome --native-automation

**Comment by AlexKamaev** [comment] 2023-04-28 07:36
Hello.
Thank you for sharing your test cases. I got the following results:
>.checked of Selector is always false no matter click

I did not manage to reproduce this issue:
>ctrl+a does not work for pressKey()

I did not manage to reproduce the issue. It works for me.
>stringifyRequestBody: true returns broken string

I could reproduce the issue with version 2.5.0. However, it has been fixed in master but has not been published yet.
>service worker is not working at all

I reproduced the issue. Thank you. For some reason, this test fails even without `native automation` mode on.

**Comment by daenamkim** [comment] 2023-04-28 08:00
@AlexKamaev Hi, thanks for clarifying this. Did you try to run  the attached file ([testcafe-typescript-vue-report.zip](https://github.com/DevExpress/testcafe/files/11342154/testcafe-typescript-vue-report.zip)) above? Except for `.checkbox`, all happens in my local env.

Here is my recorded video:
https://user-images.githubusercontent.com/16159767/235088694-d130aeaf-4294-42a8-8b77-16d48afb6807.mp4

For `.checkbox`, is there any possible case that TestCafe cannot read the value properly? e.g. Web compile setting
Since I have tried to make almost same env with our project from scratch but it happens in our project only. FYI, without `native automation` mode it works well.

**Comment by daenamkim** [comment] 2023-05-01 09:25
@AlexKamaev Hi, any update or suggestion for this? :bow:

**Comment by AlexKamaev** [comment] 2023-05-02 09:05
@daenamkim
We did not have a chance to research your usage scenario in greater detail. The fix with the post request will be published in the next TestCafe release. Regarding your other usage scenarios, we'll check them again once we start working on the issue.

**Comment by AlexKamaev** [comment] 2023-05-23 09:40
Hi @daenamkim,

Please try to run your test suite using the latest TestCafe master branch. You can get it from here: [https://github.com/AlexKamaev/issues/raw/master/testcafe-2.6.1.tgz](https://github.com/AlexKamaev/issues/raw/master/testcafe-2.6.1.tgz).

Let us know your results.

**Comment by AlexKamaev** [comment] 2023-05-24 07:07
@daenamkim

I'm happy to hear that the issue with serviceWorker is solved. As for the `ctrl+a` issue, the test passes in my case as well. Did you make some modifications in your test or in you app? If you can share your latest example version or prepare another one (perhaps witout Vue) we would love to continue the research of described problem.

**Comment by daenamkim** [comment] 2023-05-26 05:34
@AlexKamaev Thanks for testing again for me. I have tested again I can see the error consistently. I have attached a test code to see the error. It would be glad to know that I did something wrong.

**Operating system**

13.3.1 (a) (22E772610a

**Chrome:**

Version 113.0.5672.126 (Official Build) (arm64)

**Node:**

```sh
node --version                                                                                                                                                                                                               
v18.14.0
```

**TestCafe**

```sh
yarn install
npx testcafe -v                                                                                                                                                                                                                
2.6.1
```

**Steps to reproduce**

Download [testcafe-typescript-vue-report.zip](https://github.com/DevExpress/testcafe/files/11571807/testcafe-typescript-vue-report.zip)

```sh
yarn install
yarn test:na
```

**Comment by AlexKamaev** [comment] 2023-05-26 08:42
@daenamkim We reproduced the issue. It looks like it is specific to MacOS for some reason. Thank you for your cooperation.

**Comment by aleks-pro** [comment] 2023-06-13 09:23
Release [v3.0.0-rc.1](https://github.com/DevExpress/testcafe/releases/tag/v3.0.0-rc.1) addresses this.

**Closed by aleks-pro** 2023-06-13 09:23 UTC
Labels: TYPE: bug, SYSTEM: native automation

**Comment by daenamkim** [comment] 2023-06-13 10:21
> Release [v3.0.0-rc.1](https://github.com/DevExpress/testcafe/releases/tag/v3.0.0-rc.1) addresses this.

It is so beautiful! Thanks!
