### ISSUE TITLE
Unable to run regression suite in headless mode with -c 5

### ISSUE THREAD

**Issue by usmanm16** [DevExpress/testcafe#6872] opened 2022-02-14 16:03 UTC
### What is your Scenario?

I would like to run my entire regression suite and see the test results in the POMReports.html

### What is the Current behavior?

It stops in middle and throws this error. I tried both firefox and chrome.
`The "src" and "reporter" options from the configuration file will be ignored.
ERROR The Chrome 98.0.4758.80 / macOS 10.15.7 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.`

### What is the Expected behavior?

Run the entire regression suite and generate report

### What is your public website URL? (or attach your complete example)

https://www.clinicalkey.com/student

### What is your TestCafe test code?

import LoginPage from '../../page-objects/pages/common/LoginPage';
import HomePage from '../../page-objects/pages/common/HomePage.js';
import BasePage from '../../page-objects/pages/common/BasePage.js';
import { username, password } from '../../env';

// const dataSet = require('../../data/commonData/testData.json');

const signinPage = new LoginPage();
const homePage = new HomePage();
const basePage = new BasePage();
const dataSet = require('../../data/commonData/testData.json');
const users = dataSet.studentUsers;

fixture`Search Bar In The Header `
  .page(basePage.setURL() + 'login');

test
  .meta({testID: 'COMMON-0001', ticket: 'CKST-2480'})
  .meta({smoke: 'true', regression: 'true'})('Validate search icon bar on the nav bar', async t => {
    await t.maximizeWindow();
    await signinPage.login(username, password);
    await t.click(signinPage.chooseOrg.withText('English Package'));
    await t.click(signinPage.continueButton);
    await homePage.validateSerachIconOnTheNavBar();
  });

users.forEach(data => {
  test
    .meta({testID: 'COMMON-0002', ticket: 'CKST-2542, 2622, 2623, 2624, 2625, 2626'})
    .meta({smoke: 'true', regression: 'true'})(`Validate auto suggest display appropriate suggestions all packages, '${data.package}'`, async t => {
      await t.maximizeWindow();
      await homePage.validateAutoSuggestListForAllPackages(data.user, data.package);
    });
});

### Your complete configuration file

{
  "src": "testcafe/tests",
  "skipJsErrors": true,
  "screenshots": {
    "path": "testcafe/screenshots",
    "pathPattern": "${DATE}_${TEST}.png",
    "takeOnFails": true
  },
  "reporter": {
    "name": "html",
    "output": "testcafe/reports/htmlReports/POMReports.html"
  }
}

### Your complete test report

It doesn't generate test report. 

### Screenshots

Error message screenshot:
![Screen Shot 2022-02-14 at 10 20 30 AM](https://user-images.githubusercontent.com/88503374/153899429-15ea7fae-c5db-45f7-ae5d-48b472f3f529.png)

Screenshot taken on test failure:
![blank page](https://user-images.githubusercontent.com/88503374/153899401-ac375c11-0cc4-48fa-805c-05e8daaa88b5.png)

### Steps to Reproduce

1. I run this command locally `testcafe -c 5 chrome:headless --skip-js-errors --reporter html:testcafe/reports/htmlReports/POMReports.html`
I have about 85 test cases and unable to execute the entire regression suite.
2. It fails and stop in the middle
3. White blank screenshot taken for test failures and report is not generated.

### TestCafe version

1.16.1

### Node.js version

v16.11.0

### Command-line arguments

testcafe -c 5 chrome:headless --skip-js-errors --reporter html:testcafe/reports/htmlReports/POMReports.html

**Comment by viktoria2506** [comment] 2022-02-15 09:11
This issue is a duplicate of https://github.com/DevExpress/testcafe/issues/6873.

**Closed by viktoria2506** 2022-02-15 09:11 UTC
Labels: TYPE: bug, STATE: Duplicate, STATE: Need response
