### ISSUE TITLE
broken page rendering when using Tescafe

### ISSUE THREAD

**Issue by fabytta** [DevExpress/testcafe#5454] opened 2020-08-25 11:35 UTC
### What is your Test Scenario?

 open a page and see the display looks like the ordinary one (the one I find in a normal browser)
### What is the Current behavior?
 the page rendering is broken

![image](https://user-images.githubusercontent.com/4931915/91169379-2913be80-e6cf-11ea-9437-e0e1f73b27f6.png)

### What is the Expected behavior?
the display should looks like the one we found while opening manually a a browser
 
![image](https://user-images.githubusercontent.com/4931915/91169148-b9053880-e6ce-11ea-88bc-384d63f1e540.png)

### What is your web application and your TestCafe test code?

 the application is not publicly accessible  :

the issue is observed in chrome, firefox and edge,

* testcafe version:                    1.8.7
* node.js version:                    12.16.1
* command-line arguments:   testcafe ie,chrome -e test.js
* browser name and version:  chrome (no version specified)
* platform and version:           Windows

**Comment by AndreyBelym** [comment] 2020-08-26 07:59
Thank you for your report.  You can update your TestCafe version to v1.9.1 to check if the problem can be reproduced with the latest TestCafe version. If it still can be reproduced with the latest version, we will need an example that can be used to debug and fix the issue. 

You can send your private details to support@devexpress.com and attach a written confirmation that permits DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by fabytta** [comment] 2020-08-29 11:45
updating TestCafe to version  v1.9.1 does not help, the weird think is that the issue got resolved by itself the day after, which makes understanding it and fixing it very problematic

**Comment by miherlosev** [comment] 2020-09-01 09:51
Hi @fabytta

I will close this issue since the problem is not reproduced. Feel free to reopen this issue if it occurs again and you can share with us a simple example to reproduce it.

**Closed by miherlosev** 2020-09-01 09:51 UTC
