### ISSUE TITLE
Browser crashing when trying to execute a recorded script

### ISSUE THREAD

**Issue by kkapur5** [DevExpress/testcafe#8311] opened 2024-10-22 18:14 UTC
### What is your Scenario?

Using testcafe studio 2.0, I am trying to execute previously developed script. 

### What is the Current behavior?

Failed to load the page at {url}.
Open the Run Configuration dialog to increase the value of the "pageRequestTimeout" option, or quarantine the problematic test. Additionally, you can enable the "retryTestPages" flag in the Preferences/Settings dialog.
You can find troubleshooting information for this issue at https://docs.devexpress.com/TestCafeStudio/400610/faq#request-failed.

Error details:
Failed to perform a request to the resource at {url} because of an error.
Error: connect ETIMEDOUT {IP}

Browser: Chrome 130.0.0.0 / Windows 10

### What is the Expected behavior?

I am expecting page to load as it has been until couple of days ago.

### What is the public URL of the test page? (attach your complete example)

Failed to load the page at {url}.
Open the Run Configuration dialog to increase the value of the "pageRequestTimeout" option, or quarantine the problematic test. Additionally, you can enable the "retryTestPages" flag in the Preferences/Settings dialog.
You can find troubleshooting information for this issue at https://docs.devexpress.com/TestCafeStudio/400610/faq#request-failed.

Error details:
Failed to perform a request to the resource at {url} because of an error.
Error: connect ETIMEDOUT {IP}

Browser: Chrome 130.0.0.0 / Windows 10

### What is your TestCafe test code?

Failed to load the page at {url}.
Open the Run Configuration dialog to increase the value of the "pageRequestTimeout" option, or quarantine the problematic test. Additionally, you can enable the "retryTestPages" flag in the Preferences/Settings dialog.
You can find troubleshooting information for this issue at https://docs.devexpress.com/TestCafeStudio/400610/faq#request-failed.

Error details:
Failed to perform a request to the resource at {url} because of an error.
Error: connect ETIMEDOUT {IP}

Browser: Chrome 130.0.0.0 / Windows 10

### Steps to Reproduce

1. Open testcafe studio
2. set the configuration to run the script using chrome or edge

### TestCafe version

Testcafe Studio 2.0

### Command-line arguments

Using Testcafe Studio

### Other

c

**Comment by Bayheck** [comment] 2024-10-23 12:02
Hello,

We have released testcafe 3.7.0-rc.1, which addresses this issue.

I will close this issue as a duplicate of [https://github.com/DevExpress/testcafe/issues/8300.](https://github.com/DevExpress/testcafe/issues/8300.)

However, you might encounter a new issue described here: [https://github.com/DevExpress/testcafe/issues/8308](https://github.com/DevExpress/testcafe/issues/8308)

Please take a look and let us know your results.

**Closed by Bayheck** 2024-10-23 12:02 UTC
Labels: TYPE: bug, STATE: Need response

**Comment by Bayheck** [comment] 2024-10-24 11:21
Hello, 

The 3.7.0-rc.1 release is for the TestCafe open source.

The latest version of TestCafe Studio is 2.0.

Once we fix all the issues in TestCafe open source, we will update TestCafe Studio as well. 

Please stay tuned.
