### ISSUE TITLE
Add capability to import esm modules in test

### ISSUE THREAD

**Issue by bbutel** [DevExpress/testcafe#6372] opened 2021-07-10 16:46 UTC
Following this discussion on stakoverflow: https://stackoverflow.com/questions/68253518/testcafe-seems-to-not-be-compatible-with-last-version-of-logsymbol/

It seems testcafe is not compatible with pure esm modules.

If we want to enhance our framework to use others pure esm modules, we cannot.

It will be great if testcafe will be a pure esm itself in order to follow future evolve of node and ES.

**Comment by AndreyBelym** [comment] 2022-07-07 14:33
It's a duplicate of #6853. Let's continue the discussion there.

**Closed by AndreyBelym** 2022-07-07 14:33 UTC
Labels: STATE: Duplicate, TYPE: enhancement, SYSTEM: compiler
