### ISSUE TITLE
testcafe-live does not reflect changes 

### ISSUE THREAD

**Issue by hdorgeval** [DevExpress/testcafe#2115] opened 2018-02-08 21:28 UTC
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
When changing code outside the test file, testcafe-live restarts the test but saved modifications seems to be ignored.

### What is the expected behavior?
testcafe-live should reflect the most recent save

### How would you reproduce the current behavior (if this is a bug)?
Clone the github repo testcafe-starter
rename the file "testcafe-sample-page.spec.ts" to "testcafe-sample-page.live.ts"
Set .only to the test "Scenario: can send feedback with my name only"
run the command npm run test:live 
Open the file "i-enter-my-name.ts"
Comment the line ".typeText(...."
Save the file

=> testcafe-live restart the test, but text is still typed in the field

#### Provide the test code and the tested page URL (if applicable)
https://github.com/hdorgeval/testcafe-starter

Tested page URL:

Test code

```js

```

### Specify your

* operating system: windows 10 & MacOSX
* testcafe version: 0.18.6
* node.js version: 9.2.0

**Comment by AlexanderMoskovkin** [comment] 2018-02-09 16:22
Hi @hdorgeval,

Thanks for your report. I've reproduced the issue and will investigate this. I've created an issue in the `testcafel-live` repo (see https://github.com/DevExpress/testcafe-live/issues/5) and close this one. The issue is related to the `testcafe-live` only so it'd be better to track it there.

**Closed by AlexanderMoskovkin** 2018-02-09 16:22 UTC

**Comment by AlexanderMoskovkin** [comment] 2018-02-10 13:20
fixed in `testcafe-live@0.1.2`

**Comment by AlexanderMoskovkin** [comment] 2018-02-11 20:46
@hdorgeval Your words make us happy! Thanks for you feedback! Hope you'll have the best experience with TestCafe.
