### ISSUE TITLE
Exception thrown when page URL contains hash

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe#2596] opened 2018-07-05 15:14 UTC
### Are you requesting a feature or reporting a bug?

Reporting a bug.

### What is the current behavior?

Test hangs (TestCafe exists with `[...] browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.)`) and exception is thrown in the browser.

<img width="640" alt="screen shot 2018-07-05 at 17 08 38" src="https://user-images.githubusercontent.com/2109702/42331606-24c6ddf6-8076-11e8-9570-dd1cf62123b1.png">

### What is the expected behavior?

Test executes and no exception is thrown.

### How would you reproduce the current behavior (if this is a bug)?

Running the attached test.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Irelevant

Test code

```js
import 'testcafe';

fixture('F').page(`${process.env.e}/#/t`);

test('t', async t => { });
```

Removing `/#/t` from the page URL makes the test fail (which is expected).

### Specify your

* operating system: macOS High Sierra (10.13.4)
* testcafe version: 0.20.4
* node.js version: v8.11.3

**Comment by AndreyBelym** [comment] 2018-07-05 15:38
Hi @sorin-davidoi, this issue looks as a duplicate of https://github.com/DevExpress/testcafe/issues/2371. Please, check the #2371 to be notified when the issue is fixed, and then feel free to reopen the issue if a provided solution doesn't fix your problem.

**Closed by AndreyBelym** 2018-07-05 15:38 UTC
Labels: To be reproduced
