### ISSUE TITLE
Failed to find a DNS-record for the resource

### ISSUE THREAD

**Issue by pablorivera** [DevExpress/testcafe#1802] opened 2017-09-20 18:50 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Tests randomly fails with the following error message:
```Failed to find a DNS-record for the resource at "https://develop-i.quid.com/".``` I have seen similar errors reported at https://github.com/DevExpress/testcafe/issues/1135 and https://github.com/DevExpress/testcafe/issues/1601

### What is the expected behavior?
Tests doesn't fail with this random error.

### Specify your

* operating system: MacOs Sierra 10.12.6
* testcafe version: 0.17.2
* node.js version: v8.1.2

**Comment by inikulin** [comment] 2017-09-20 19:22
@pablorivera But website is indeed unreachable:
```sh
❯ ping develop-i.quid.com 
PING develop-i.quid.com (10.4.0.222): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
^C
--- develop-i.quid.com ping statistics ---
7 packets transmitted, 0 packets received, 100.0% packet los
```
I guess the problem here is that we report incorrect network error message here. But as far as I remember we use error provided by Node, so it may be a problem on Node side as well.

**Comment by AndreyBelym** [comment] 2017-09-21 10:44
Currently this error means that TestCafe was unable to reach the specified website. It is not related only to DNS resolving issues, because it is displayed on any network error: #1606. Likely it's a problem with network connection or with the server. You can use the [curl](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/curl.1.html) utility to check it: run several times `curl http://develop-i.quid.com -o /dev/null`. it should not report errors if network connection is working stable.

**Comment by thecodejack** [comment] 2017-09-22 09:21
won't it be better to ignore this kind of errors or warn them rather stopping test execution completely. I am still having this issue even after #1216 got resolved.

**Comment by AndreyBelym** [comment] 2017-09-22 10:39
We can't ignore this error, because it means 'TestCafe cannot access the test page, there is no network connection or webserver is not responding'. The only option here is to retry to fetch page several times and hopefully some attempt will be successfull.

#1216 is not related to this, or you mean you're getting those errors even when you specify a test page with `file:///` protocol?

**Comment by pablorivera** [comment] 2017-09-22 17:51
Thanks @AndreyBelym. I run it multiple times and always get something like this:
```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2423    0  2423    0     0   2286      0 --:--:--  0:00:01 --:--:--  2288
```
Seems to be ok. Do you think there could be another problem?

**Comment by thecodejack** [comment] 2017-09-25 07:17
@AndreyBelym I agree if its the page that's failing. But for me its some script/css from page which is failing which may not be important for the test executions.

**Comment by cgcote** [comment] 2017-09-28 09:07
I am having similar issues. I deploy a React app as a static website on AWS S3 and I get every now and then (5% of the builds):

```
   1) - Error while restoring configuration after Role switch -
      Failed to find a DNS-record for the resource at
      "http://mybucketname.s3-website-eu-west-1.amazonaws.com".
```

**Comment by vampolo** [comment] 2017-10-02 21:46
Speaking on behalf of @pablorivera to which i work with.

The `develop-i.quid.com` is a vpn protected address. Of course it is not accessible from outside. Apologies about that.

I've been digging on this problem a bit, let me add some context:
1. our app does various `window.location.href="http://otherdomain` during a single test
2. the problem is intermittent

By digging into [hammerhead code](https://github.com/DevExpress/testcafe-hammerhead/blob/67618b251aa3fcf9958870b9fd0419804203c9d8/src/request-pipeline/destination-request/index.js#L103) found that the generic error about DNS resolution is trigger for a bigger set of connection problems about connection refused, or connection reset.

With the architecture of having browser -> hammerhead -> testcafe and browser being redirected with `window.location.href` i guess that when the browser closes an existing in filght ajax due to a js triggered redirect, hammerheads gets upset and fails the test.

This issue is very similar to #1135 and the failure rate gets lower if we increase the time in `t.wait()` calls before the application switches to another page with a `window.location.href` call.

Let me know if this helps understanding the problem.

**Comment by AndreyBelym** [comment] 2017-10-03 08:57
Thanks for you for your investigation @vampolo, the problem definitely relates to `hammerhead`, but AFAIK this code should not affect XHR requests. Anyway we will look at this part closely, thank you!

**Comment by miherlosev** [comment] 2018-05-03 15:04
Hi @pablorivera

Try the latest `TestCafe` version (`testcafe@0.19.2`) and let us know your results.
If there is a possibility to hold a remote session using `Skype` or `TeamViewer` to access your app, we would be happy to do this.

**Closed by miherlosev** 2018-05-03 15:04 UTC
Labels: To be reproduced

**Comment by aphofstede** [comment] 2018-11-06 20:55
Is there a way to change the retry count / number of retries TestCafé does behind the scenes?

**Comment by AndreyBelym** [comment] 2018-11-08 17:18
@aphofstede, could you please share more details about your problem? What are your operating system and Node.js versions? Does it happen sporadic or in every build, in a specific test or a random one? Can you provide a complete test report or an example that can be used to reproduce the problem?

TestCafe doesn't retry any requests by default, but you can try to enable the undocumented [pageRetryMode](https://github.com/DevExpress/testcafe/blob/master/src/index.js#L49) mode. When this mode is enabled. TestCafe retries failed requests to test pages up to 5 attempts with 300 milliseconds delay between each failed attempt. There are no options to configure the maximum attempts count or the delay between failed attempts.

Currently, you can't enable this mode from the command line interface; you should supply the `true` Boolean value as the 5th argument of the [createTestCafe](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/createtestcafe.html) function to enable this mode. You also can configure your web server to send the [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) header with a big expiration time (e.g., `max-age=3600`) to get maximum effect from this mode.

**Comment by Esteban26** [comment] 2019-01-17 22:58
Hi, currently we're facing this issue too. Our behavior is similar than @jmullo and @cgcote, the issue is displayed in 5% of our builds and is triggered randomly.

We're running testcafé in a  EC2 machine and sometimes the issue is triggered for some test cases.

We're using 0.22.0 and 0.23.3-alpha.4 versions (The last one to avoid an issue you fixed for mobile devices).

` 1) - Error in fixture.beforeEach hook -
 Failed to find a DNS-record for the resource at
"http://localhost:5000/".
Browser: Chrome 70.0.3538 / Windows 10.0.0
` 
Another example

`   1) Failed to find a DNS-record for the resource at
"http://localhost:5000/".

Browser: Firefox 62.0.0 / Windows 10.0.0
`

**Comment by kel30a** [comment] 2019-02-26 00:01
Have you tried --quarantine-mode ?

I've added my experience/suggestion to here: https://github.com/DevExpress/testcafe/issues/3304

**Comment by miherlosev** [comment] 2019-02-26 11:39
@kel30a @Esteban26 and everyone
 
The problem does not relate to TestCafe.
There are numerous reasons a web page cannot be loaded: a virtual amazon machine is not available, a DNS resolving problem or something else).
 
You can run your tests in [quarantine mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#quarantine-mode).

**Comment by pwaller** [comment] 2019-02-26 11:43
I just hit this - the error message is unhelpful since it suggests a DNS problem, when actually it is a connectivity issue. I changed my host to `127.0.0.1` and it still said there was a DNS problem.

**Comment by AndreyBelym** [comment] 2019-03-06 13:31
@pwaller yes, there is just one message for all types for network problems. We plan to change the situation in the context of #3492.

**Comment by bbonczek** [comment] 2021-04-01 11:13
I'm wondering it this issue should really be closed - it occurs to us with every testcafe version we were using so far. We're hosting our app using npm package 'http-server' on localhost, so there is no way it's DNS or connectivity issue.

**Comment by alexphilin** [comment] 2022-03-02 14:02
Hi @maksnester

The test servers can work unstably under heavy load. If it's possible, use production-ready servers to host tested apps.

However, if you can share an example to reproduce the issue, we are ready to research it.
