### ISSUE TITLE
Runner.aftereach and Runner.beforeach required to ignore all Fixtures

### ISSUE THREAD

**Issue by AutomationTester143** [DevExpress/testcafe#5194] opened 2020-06-11 07:00 UTC
### What is your Test Scenario?
I want to execute Testrail test cases after each test. 
I know t.aftereach() test is supported in Fixture and t.aftereach () is working fine for a single fixture.

But If I have 5 fixtures and each fixture is in a single file then I have to apply  t.aftereach (// testrail execution code ) on each file for each fixture. So this is kind of code redundancy of  (t.aftereach ()) in each fixture. 

runner.aftereach() should be supported so that some operations can be done after each test irrespective of the fixture.
 
### What is the Current behavior?
t.aftereach() is supported for a single fixture.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by arubtsov** [comment] 2020-06-11 13:15
Hello @AutomationTester143

Thank you for submitting this issue. It looks like a duplicate of https://github.com/DevExpress/testcafe/issues/745. Feel free to join the discussion there.

**Closed by arubtsov** 2020-06-11 13:15 UTC
Labels: STATE: Need response
