### ISSUE TITLE
Error: WebSocket connection closed in Chrome 130.xx.x.x

### ISSUE THREAD

**Issue by hjokwon** [DevExpress/testcafe#8326] opened 2024-10-30 11:25 UTC
### What is your Scenario?

```
Fixture`hello`
  .beforeEach(async t => {
    const [a] = await create("testQA-");
    t.ctx.id = a;

  })
  .afterEach(async t => {
    await delete(t.ctx.id);
  });


  test('create something', async t => {
    const name = "AutoQA" + rs({ length: 3 })
    await checkName(name);
  }
  )
```

### What is the Current behavior?

Chrome browser don't open as soon as excute with below errors.
```
Error: WebSocket connection closed
    at node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleConnectionClose (/node_modules/chrome-remote-interface/lib/chrome.js:256:13)
    at WebSocket.<anonymous> (/node_modules/chrome-remote-interface/lib/chrome.js:243:22)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.emitClose (/node_modules/ws/lib/websocket.js:246:10)
    at Socket.socketOnClose (/node_modules/ws/lib/websocket.js:1150:15)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:337:12)
```

### What is the Expected behavior?

Chrome browser has to be opened

### What is the public URL of the test page? (attach your complete example)

don't comment

### What is your TestCafe test code?

```
testcafe chrome -t 'test'
```

### Steps to Reproduce

1. testcafe excute (it's all)

### TestCafe version

3.6.0

### Command-line arguments

testcafe chrome -t 'test'

### Other

Didn't work whell when I try `--disable-search-engine-choice-screen`options or `--disable-native-automation`(r.f #8240 ) but works whell when I downgrade chrome 129.

**Comment by PavelMor25** [comment] 2024-10-31 13:04
Hello @hjokwon,

We have released testcafe 3.7.0-rc.3. It addresses this issue.

Please try it and let us know your results.

I will close this issue as a duplicate of [https://github.com/DevExpress/testcafe/issues/8300](https://github.com/DevExpress/testcafe/issues/8300).

**Closed** 2024-10-31 13:05 UTC
Labels: TYPE: bug, STATE: Duplicate
