### ISSUE TITLE
--env option

### ISSUE THREAD

**Issue by ambeecher** [DevExpress/testcafe#6427] opened 2021-07-28 15:41 UTC
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:   1.15.1  
* node.js version:    12.10.0 
* command-line arguments:  "test-ebp": "testcafe 'chrome:headless --no-sandbox' projects/test.ts --screenshots ./screenshots --env=dev" 
* browser name and version:  Chrome version differ a bit from environment to environment.
* platform and version:          
* other:

**Comment by felis2803** [comment] 2021-07-29 08:37
Duplicate of https://github.com/DevExpress/testcafe/issues/6426

**Closed by felis2803** 2021-07-29 08:37 UTC
Labels: STATE: Duplicate

**Comment by felis2803** [comment] 2021-07-29 13:17
Please follow the progress of fixing this bug on the issue https://github.com/DevExpress/testcafe/issues/6426.
