### ISSUE TITLE
The test fails because of a native alert on the page despite the exposed handler

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#5997] opened 2021-03-01 09:56 UTC
### What is your Test Scenario?
A simple test cafe on the site after fix the problem from SC https://github.com/DevExpress/testcafe-hammerhead/issues/2573 
```js
fixture `bug3`
     .page `https://qa.xreach.app/`;

test('New Test', async t => {
    await t
        .setNativeDialogHandler(() => {})
        .debug();
});
```
 
### What is the Current behavior?

![image](https://user-images.githubusercontent.com/12034551/109480126-35b50d00-7a8c-11eb-83e1-ae447dc7abcf.png)

The test has a handler for native dialogs , but the test fails. An alert for a dialog doesn't even appears on the site.

### What is the Expected behavior?
Test should pass.
 
### What is your web application and your TestCafe test code?
https://qa.xreach.app/
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

https://qa.xreach.app/
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `bug3`
     .page `https://qa.xreach.app/`;

test('New Test', async t => {
    await t
        .setNativeDialogHandler(() => {})
        .debug();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

![image](https://user-images.githubusercontent.com/12034551/109480608-c7247f00-7a8c-11eb-8442-ce63f4d82b61.png)

</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

`testcafe chrome test.js`
 
### Your Environment details:
 
* testcafe version:                   1.11.0
* node.js version:                    14.15.0
* command-line arguments:  `testcafe chrome test.js`
* browser name and version: Google Chrome Version 88.0.4324.190 (Official Build) (64-bit)
* platform and version:          Windows 10
* other:

**Comment by miherlosev** [comment] 2021-03-09 05:59
The `acorn-hammerhead` parser crashes on parsing the elvis operator:
Resource - https://mozilla.github.io/pdf.js/build/pdf.js
Line - `annotationStorage: annotationStorage?.serializable || null`.

**Comment by LavrovArtem** [comment] 2021-03-18 07:28
The issue with the parser is fixed. And now, I see an alert dialog after each page reload.
![image](https://user-images.githubusercontent.com/5373460/111588244-5394a880-87d4-11eb-865f-c970e97ca2b5.png)

**Comment by LavrovArtem** [comment] 2021-03-23 09:29
The provided site uses the following feature detection:

**Comment by LavrovArtem** [comment] 2021-03-23 12:14
This site uses the following feature detection:

```js
// origin of the pasted code https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser
    function isFirefoxOrChrome() {
      // Firefox 1.0+
      var isFirefox = typeof InstallTrigger !== 'undefined';
      // Chrome 1+
      var isChrome = !!window.chrome && (!!window.chrome.webstore || !!window.chrome.runtime);

      if (isChrome) {
        window.ClientType = 'Chrome';
      } else if (isFirefox) {
        window.ClientType = 'Firefox';
      }

      return isFirefox || isChrome;
    }

    if (!isFirefoxOrChrome()) {
      alert('Please use a Firefox or Chrome browser.\nThe XReach supported browsers are Firefox and Chrome browsers.');
    }
```

Pay attention to the following line:

```js
var isChrome = !!window.chrome && (!!window.chrome.webstore || !!window.chrome.runtime);
```
`window.chrome.webstore` is `undefined` as on the original site.
`window.chrome.runtime` is `undefined` because our proxy works through `http`. We can advise using the [--ssl-options](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--ssl-options).

**Comment by LavrovArtem** [comment] 2021-03-23 12:21
duplicate of https://github.com/DevExpress/testcafe/issues/3342

**Closed by LavrovArtem** 2021-03-23 12:21 UTC
Labels: TYPE: bug, support center
