### ISSUE TITLE
Testcafe is  not click a button in IE 11.

### ISSUE THREAD

**Issue by guptaakhil** [DevExpress/testcafe#3240] opened 2018-12-19 02:34 UTC
I just want to click in button based on its visibility. it's perfectly run in chrome, safari, and firefox but not in IE 11 with the combination OS window 7 and Window 10
 
Tried with the command:   testcafe ie test.js --hostname 127.0.0.1 

What is the Current behavior :::
Browser Window is hung after few minutes provide browser unreachable exception.
 
Environment details :::
 
* test cafe  version:                 0.23.1    
* node.js version:                    v10.9.0
* command-line arguments:  test cafe ie scriptsname.js
* browser name and version:  IE 11
* platform and version:          Window 7 or window 10 
* other:                                    I have tried with the different version of test cafe and another version in ie >9.0

**Comment by AlexSkorkin** [comment] 2018-12-19 15:33
Hello, 
This issue is unknown to us. Would you please clarify how you set the button visibility? What CSS properties are you using? It would be great if you also provide us with your scriptsname.js test file so we can examine the issue. If this is not possible, please create a simple sample similar to your scenario so we can check it out. Thank you in advance.

**Comment by AlexSkorkin** [comment] 2018-12-21 14:47
Thank you for your clarification. However, the information you provided is insufficient for me to determine the cause of the issue and find a precise solution. To help us research it, please provide us with a complete test sample and public website URL where you encountered these problems.

**Comment by guptaakhil** [comment] 2018-12-21 16:45
Here find below the scripts as of now we don't have the public url, kindly look into this issue.

import { Selector } from 'testcafe';

fixture('Application install testcafe')
  .page('URL');

test('test cafe Solution', async (t) => {
  

const  ageGateWindow = Selector('.age-gate');
const  pageContainser=Selector('div#app')
 
  const  yesAgePopUp = Selector('[data-auid="age-gate-primary"]');
  
  if (await ageGateWindow.exists) {
      await t.click(yesAgePopUp);
  }

});

**Comment by AlexSkorkin** [comment] 2018-12-21 17:17
Please create a simple sample based on your markup, so we can examine the issue.

**Comment by guptaakhil** [comment] 2018-12-21 20:22
I have attached a mock page in a site, now you can reproduce the issue in IE -11, updated the above comment with code. kindly look into that. if it's working please do let me know the changes done

**Comment by guptaakhil** [comment] 2018-12-22 07:40
Any update on issue...

**Comment by AndreyBelym** [comment] 2018-12-24 08:54
I can't reproduce the problem with `testcafe@0.23.3`. Please note, there are a lot of JS errors on your website that can be reproduced without TestCafe:
![image](https://user-images.githubusercontent.com/4479386/50394928-ee2aec00-0771-11e9-9dd3-b27b8cc23542.png)

However the test runs fine when I add the `-e` switch:
```
> testcafe ie -e test.js
Using locally installed version of TestCafe.
 Running tests in:
 - IE 11.0.0 / Windows 10.0.0

  testcafe ie issue
 √ testcafe ie issue


 1 passed (18s)
```

**Comment by guptaakhil** [comment] 2018-12-24 17:19
Hi, 
 
I just cross-checked, again and again, there is no JS Error in the browser, getting below the screen. please look below.

<img width="1586" alt="screen shot 2018-12-24 at 12 12 05 pm" src="https://user-images.githubusercontent.com/18642620/50404441-eec58180-0775-11e9-8027-a6fa814f17f2.png">


Although i used the option testcafe ie -e test.js , still getting same issue.

**Comment by AndreyBelym** [comment] 2018-12-25 10:59
The errors can be reproduced with the original test page, see https://www1.shoppersdrugmart.ca/en/home. Your screenshot shows a page that opens after clicking the banner on the original page.

Also, the browser on your screenshot is Microsoft Edge, not Internet Explorer. Could you please specify which browser can be used to reproduce the problem? Please attach a screenshot with the information about the browser:
 * IE - open the settings menu (⚙️) and click the "About Internet Explorer` item
 * Edge -  open the settings menu (⚫️ ⚫️ ⚫️ ), click the "Settings" item and scroll the sidebar down to the "About this app" section. 

I can't reproduce the issue either in Internet Explorer 11 or Microsoft Edge. Please use the latest TestCafe version (`0.23.3`) and provide the following  screenshots:
1. Screenshot of the  `testcafe -v && testcafe ie --dev -e test.js` command output  
2. Screenshot of the Console and Network tabs from the browser's Developer Tools window during the test session.

**Comment by guptaakhil** [comment] 2019-01-04 16:16
@AlexSkorkin  and @AndreyBelym: Any update related to this issue.  kindly share the video and package.json snapshot if it's not reproducible at your end.

**Comment by guptaakhil** [comment] 2019-01-09 19:17
@AndreyBelym  : the site is live now : https://cannabis.shoppersdrugmart.ca/en_CA, we can launch this  now, there is access to everyone now,  I just change the code as below, runin chrome and FF but not in IE..

import { Selector } from 'testcafe';

fixture('Application install testcafe')
  .page('https://cannabis.shoppersdrugmart.ca/');

test('test cafe Solution', async (t) => {
const  ageGatePopUp = Selector('.age-gate');
const  pageContainser=Selector('div#app')
const  yesAgePopUp = Selector('[data-auid="age-gate-primary"]');
  if (await ageGatePopUp.exists) {
    
      await t.click(yesAgePopUp);
  }
});

**Comment by guptaakhil** [comment] 2019-01-10 16:01
@AlexSkorkin  and @AndreyBelym :   it's accessible now anywhere, kindly delete the cookies and run, it's running. For,  Age gate pop-up occurs first time, once it confirms your age save in cookies.

![image](https://user-images.githubusercontent.com/18642620/50980561-00718d80-14c7-11e9-905f-fdf7df1e3b12.png)

**Comment by AlexSkorkin** [comment] 2019-01-10 16:10
It is still not accessible even from Opera with enabled VPN:

![image](https://user-images.githubusercontent.com/995726/50981163-6b44b800-150b-11e9-837b-0ccbf2f30fce.png)

**Comment by guptaakhil** [comment] 2019-01-10 16:43
@AlexSkorkin: This site live in Canada and India only, can you use Canada tunnel or proxy server to access this.  I believe it will run.

**Comment by LavrovArtem** [comment] 2019-01-11 09:16
@guptaakhil, Thank you for the details. We've reproduced the problem and it is really a duplicate of the DevExpress/testcafe-hammerhead#1890 issue. We will fix it in the current sprint. Feel free to reopen this issue if you encounter any problem with that.

**Closed by LavrovArtem** 2019-01-11 09:16 UTC

**Comment by guptaakhil** [comment] 2019-01-14 17:03
@Farfurix and @LavrovArtem:  it's still not working with the latest version 0.23.3, I believe the latest code will be available in coming releases. please notify us when it's available in the stable version of Testcafe.

Thanks in advance !!
