### ISSUE TITLE
Testcafe never exits after successful tests using browserstack in docker

### ISSUE THREAD

**Issue by ljowen** [DevExpress/testcafe#4899] opened 2020-03-24 02:43 UTC
### What is your Test Scenario?
Asserting true on google.com using browserstack (any browser) in container using node:12.16.1-buster image
 
### What is the Current behavior?
After tests complete the process never exits
 
### What is the Expected behavior?
Testcafe finishes after successful tests
 
### What is your web application and your TestCafe test code?

<details>
<summary>[Your website URL (or attach your complete example):](www.google.com)</summary>
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
import { t } from 'testcafe';
fixture('google').page('www.google.com');

test.only('example', async () => {
  await t.expect(true).ok();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
BROWSERSTACK_NO_LOCAL=1
BROWSERSTACK_USERNAME=<username>
BROWSERSTACK_ACCESS_KEY=<password>
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Safari 13.0.3 / iOS 13.2
 (https://automate.browserstack.com/builds/...)

 google
 ✓ example


 1 passed (16s)

--- process never exits after this point ---
```
</details>

### Steps to Reproduce:

1. Execute `docker run -v $PWD:/tests -w /tests -it node:12.16.1-buster npm run testcafe -- "browserstack:iPhone 11 Pro Max" "src/tests/smokeTest.js" "-q"`
2. Skipping the only test also results in the process never exiting
3. If I add process.exit(0) inside the test, it exits correctly

### Your Environment details:
 
* testcafe version: 1.8.3
* node.js version: 12.16.1
* command-line arguments:  "browserstack:iPhone 11 Pro Max" "src/tests/smokeTest.js" "-q"
* browser name and version: Safari 13.0.3 / iOS 13.2
* platform and version: macOS Mojave v10.14.6 (also seeing the issue on our bamboo agent)
* other
- Issue only appeared after upgrading testcafe from version "0.23.2" to "1.8.3"

**Comment by ljowen** [comment] 2020-03-24 05:26
If I add `process.exit(0)` inside the test, it exits correctly

**Comment by AlexKamaev** [comment] 2020-03-26 12:31
I was able to reproduce the issue only when the `BROWSERSTACK_NO_LOCAL` variable was set to 1. Could you please run the test without this setting?
Please also specify the version of testcafe-browser-provider-browserstack you use with testcafe@0.23.2.

**Comment by ljowen** [comment] 2020-03-27 02:16
I am still getting the issue without `BROWSERSTACK_NO_LOCAL` set on my end
`testcafe-browser-provider-browserstack` was previously at version `1.8.0`

**Comment by miherlosev** [comment] 2020-03-30 14:17
Like @AlexKamaev, I was able to reproduce the issue only when the BROWSERSTACK_NO_LOCAL variable was set to 1.
Could you please run the following commands in your terminal?

```js
echo %BROWSERSTACK_NO_LOCAL%
testcafe "browserstack:iPhone 11 Pro Max" test.js
set BROWSERSTACK_NO_LOCAL=1
echo %BROWSERSTACK_NO_LOCAL%
testcafe "browserstack:iPhone 11 Pro Max" test.js
```

and share the screenshot of the terminal after the commands are executed.

**Comment by ljowen** [comment] 2020-03-30 23:46
Hi @miherlosev 

Adapting the above for bash:
```
echo "$BROWSERSTACK_NO_LOCAL"

testcafe "browserstack:iPhone 11 Pro Max" src/tests/sample.js
Using locally installed version of TestCafe.
 Running tests in:
 - Safari 13.0.3 / iOS 13.2.3
 (https://automate.browserstack.com/builds/<buildid>)

 google
 ✓ example


 1 passed (13s)
```

```
BROWSERSTACK_NO_LOCAL=1

echo "$BROWSERSTACK_NO_LOCAL"
1

testcafe "browserstack:iPhone 11 Pro Max" src/tests/sample.js
Using locally installed version of TestCafe.
 Running tests in:
 - Safari 13.0.3 / iOS 13.2.3
 (https://automate.browserstack.com/builds/<buildid>)

 google
 ✓ example


 1 passed (11s)
```

However as per my question if I do the above via a Docker container I still see the process fail to exit

**Comment by aleks-pro** [comment] 2020-04-02 15:10
Hello @ljowen,

Could you please send us your project (at least, the `package.json` file) so that we can research it on our side? Also, please make sure that you have updated the `testcafe-browser-provider-browserstack` version to the latest build.

**Comment by ljowen** [comment] 2020-04-06 01:25
Here is my package.json:
`{
  "name": "e2e-tests",
  "version": "1.4.0",
  "private": true,
  "description": "",
  "main": "index.js",
  "engines": {
    "node": ">=12.14.0",
    "npm": ">=6.13.4"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "glob": "7.1.3",
    "pretty": "2.0.0",
    "request-promise": "4.2.2",
    "testcafe": "1.8.3",
    "testcafe-browser-provider-browserstack": "1.12.0",
    "testcafe-browser-tools": "2.0.10"
  },
  "devDependencies": {
    "axe-testcafe": "1.1.0",
    "babel-cli": "6.26.0",
    "babel-eslint": "10.0.1",
    "babel-preset-flow": "6.23.0",
    "browserstack-local": "1.3.6",
    "dotenv": "6.0.0"
  }
}`

The sample project I've created just consists of the test file included above and this package.json.

Do you mean the `v1.13.0-alpha.1` or is `1.12.0` fine for the browserstack provider?

**Comment by Dmitry-Ostashev** [comment] 2020-04-07 17:06
Thank you for your package.json file. However, I was unable to reproduce the issue. Please give us additional time to research it.

**Comment by ljowen** [comment] 2020-04-09 01:47
Update on my end, the tests all pass fine if I use the automate api. `BROWSERSTACK_USE_AUTOMATE=1` I switched to the JS api as we were experiencing a lot of sessions hanging and using the JS api seemed to improve that. I've contacted browserstack to see if they've made any changes / deprecated the JS api.

**Comment by AlexKamaev** [comment] 2020-04-09 12:26
@ljowen
I ran tests on "browserstack:iPhone 11 Pro" (and other iPhones) - they are not executed with `BROWSERSTACK_USE_AUTOMATE=0`. I can reproduce the issue even without a docker.

It looks like Browserstack introduced some changes that caused hanging. So, I will close this issue since it doesn't occur on our side.

If you have any further questions, feel free to contact us. We will reopen the issue if some modifications are required on our side.

**Closed by AlexKamaev** 2020-04-09 12:26 UTC
Labels: STATE: Need response
