### ISSUE TITLE
Content of the iframe in which the test is currently operating did not load

### ISSUE THREAD

**Issue by MariaRyadchikova** [DevExpress/testcafe#2406] opened 2018-05-14 21:49 UTC
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?
All the test cases which are switching to a frame fail with the error: "Content of the iframe in which the test is currently operating did not load"

**Tested page URL:**  https://elk.co/

**Minimum code to reproduce the issue:**

import { Selector } from 'testcafe';
import utils 		from '../utils.js';

fixture `To test frame load failiares`
	.page('https://elk.co?loglevel=debug');
	
test('Valid user credentials creation', async (t) => {
	await t
		.click(Selector('.loggedOut > a:nth-child(1)'))
		.expect(Selector('.username')).ok({ timeout: 5000 })
		.typeText(Selector('.username'), 'smoke-' + utils.timestamp)
		.typeText(Selector('.email'), 'test@test.com')
		.typeText(Selector('.password'), 'T9e5s1t7P')
		.expect(Selector('.continueBtn').exists).ok({ timeout: 5000 })
		.click(Selector('.continueBtn'))
		.expect(Selector('#Content')).ok({ timeout: 6000 })
		.switchToIframe(Selector('#Content'), { timeout: 7000 })
		.setPageLoadTimeout(45000)
		.expect(Selector('.tooltip-wrapper').exists).ok({ timeout: 15000 });
});

### Specify your

* operating system: MacOS High Sierra version 10.13.4
* testcafe version: 19.2
* node.js version: any

**Notes:** Visually while test cases are executed I can see that the content of the frames is actually loaded, but it fails all the time with the error indicated above. Also no timeouts or waits will help, I tried to set a very long timeouts and it fails anyway with the same error.

**Comment by AndreyBelym** [comment] 2018-05-15 09:04
Duplicate of https://github.com/DevExpress/testcafe/issues/2387

**Closed by AndreyBelym** 2018-05-15 09:04 UTC

**Comment by miherlosev** [comment] 2018-10-11 10:20
The problem does not relate to iframes.
We don't correctly check a same-origin policy for second-level domains `web.elk.co` and `app.elk.co`.
It's a general restriction of our [web-proxy](https://github.com/DevExpress/testcafe-hammerhead). I've created a separate issue in its repository - https://github.com/DevExpress/testcafe-hammerhead/issues/1787.

As a temporary workaround, try to run Google Chrome with the `--disable-web-security` flag.
