### ISSUE TITLE
Proxy Issues?

### ISSUE THREAD

**Issue by leegee** [DevExpress/testcafe#2137] opened 2018-02-19 14:37 UTC
Latest testcafe, latest Chrome, Node v6.12.3

I think I have run into proxy problems, as my working fails with this

`http://10.22.2.16:57400/HJXflD_DG/http://localhost:8080/onewssi/user/v1/?filter=businessUnit(XXXX%20XXXXXXX)`

The URL `http://localhost:8080/onewssi/user/v1/?filter=businessUnit(XXXX%20XXXXXXX)` is up and running.

Do I need to configure the Testcafe proxy?

**Comment by AlexanderMoskovkin** [comment] 2018-02-20 15:48
Hi @leegee,

How does it look? The test fails with some error? Or it can't just open a page? Do you use a system proxy on your machine?

**Comment by leegee** [comment] 2018-02-20 17:32
In this particular setup, several proxies — it's horrible and not my doing — but the mistake here was mine, with a misconfigured mock. Thanks for your time — loving the TestCafe experience!

**Comment by AlexanderMoskovkin** [comment] 2018-02-20 17:34
Glad to hear this! =) I close this since the issue is resolved

**Closed by AlexanderMoskovkin** 2018-02-20 17:34 UTC
