### ISSUE TITLE
document.addEventListener for click events not working

### ISSUE THREAD

**Issue by timostark** [DevExpress/testcafe#5621] opened 2020-10-09 19:03 UTC
### Test-Scenario
Very simple website, having nothing but a href. The click of the href is canceled using preventDefault. Therefore the link shouldn't be followed. Unfortunately since version 1.9.0 the click event handler is not even called.
Instead the popup window opens directly. Testcafe is working correctly with 1.9.0-alpha.2.

### What is the Current behavior?
Popup window is opened. The click handler is not even called!

### What is the Expected behavior?
Click handler is called. preventDefault is respected.
 
### What is your web application and your TestCafe test code?
Web-Application is uploaded to https://lemokla.de/test.html. Source Code of test:

```
fixture('Startseite')
  .page("https://lemokla.de/test.html");

test('Test-new-one', async t => {
    await t.click("#test");
    await t.debug();
});
```

Source-Code of Webapp:
```
<!DOCTYPE html> <html> <body>
    <a href="http://www.google.de" id="test" target="_blank">test123</a>
<script>
    document.addEventListener("click", function(e) {
        e.preventDefault();
    });
</script> 
```

Demo-GIF (Right Side: Open normally with chrome. Click event is called. Left side: opening with testcafe and unlock page --> click event not called, opening with chrome, left side using testcafe)

![testcafe](https://user-images.githubusercontent.com/19237828/95621819-a1152880-0a72-11eb-9239-567d16ef9796.gif)

**Comment by Ogurecher** [comment] 2020-10-12 08:03
@timostark, Thank you for your report. I've reproduced this issue. It's related to the [Multiple Browser Windows](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html) feature, which is currently in the beta state.
You can turn it off by adding the [--disable-multiple-windows](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--disable-multiple-windows) flag when running TestCafe. You can use this flag while we're looking for a solution. We'll update this thread once the issue is fixed.

**Comment by timostark** [comment] 2020-10-13 20:49
Just to confirm:the flag is working fine for me. Thanks for the help.

**Comment by timostark** [comment] 2021-01-09 09:04
Did you already had a look here? Otherwise I would analyse and hopefully come up with a pr, as I'd really like to use the multi window feature (while this bug is blocking me from using it).

**Comment by AlexKamaev** [comment] 2021-01-12 09:23
@timostark
Hello, we didn't have a chance to look at the issue yet. As I see, you did a great research, so now we know the cause of the issue. Many thanks for this. From my point of view, the suggested solution may cause side effects, and it may be not very solid. At this moment, I cannot suggest a more stable fix. We need time to research the issue.
As for PRs, we accept them, so you can create a PR in the TestCafe repository with a test that fails. Once we research the issue, we'll update the `testcafe-hammerhead` repository to make your test successful.

**Comment by timostark** [comment] 2021-02-22 21:17
I guess this can be closed with https://github.com/DevExpress/testcafe-hammerhead/pull/2582 correct?

**Comment by AlexKamaev** [comment] 2021-02-24 08:31
This issue is partially fixed. Everything works as expected when the `preventDefault` method is called at the level of the specific element:

```JS
document.getElementById("test").addEventListener("click", function(e) {
    e.preventDefault();
});
```
However, the issue when the event is prevented at the document level still exists:


```JS
document.addEventListener("click", function(e) {
    e.preventDefault();
});
```

**Comment by AlexKamaev** [comment] 2021-06-16 12:36
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2648

**Closed by AlexKamaev** 2021-06-16 12:36 UTC
Labels: AREA: client, FREQUENCY: level 2, TYPE: bug
