### ISSUE TITLE
Cannot run tests on Saucelabs when configuring with Sierra or HighSierra

### ISSUE THREAD

**Issue by amidongarrett** [DevExpress/testcafe#2513] opened 2018-06-13 21:52 UTC
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Cannot run test on Saucelabs tests with Sierra or HighSierra and any browser

### What is the expected behavior?

Successfully start a test on Saucelabs with Sierra/High Sierra as the OS

### How would you reproduce the current behavior (if this is a bug)?

When attempting to run the command:

`testcafe "saucelabs:Chrome@57.0:macOS Sierra" test.js`

I receive the error:

`Error: [init({"name":"Testcafe tests","build":"123","tunnelIdentifier":1528924592581,"idleTimeout":1000,"browserName":"chrome","version":"57.0","platform":"macos sierra"})] The environment you requested was unavailable`

When looking at the Saucelabs metadata of the failed test above, I see this:
![screen shot 2018-06-13 at 2 27 37 pm](https://user-images.githubusercontent.com/10519190/41379121-0361721e-6f16-11e8-8254-2092756ee8e7.png)

When creating this environment with manual tests the metadata shows this:
![screen shot 2018-06-13 at 2 32 54 pm](https://user-images.githubusercontent.com/10519190/41379394-ba5d1a22-6f16-11e8-92fa-f8bd21889025.png)

It seems like all you need to change is the command from what was above to:

`testcafe "saucelabs:Chrome@57.0:mac 10.12" test.js`

and Saucelabs might be okay with it?

*Note: I attempted to run this command and received another error saying:
`ERROR Unable to find the browser. "saucelabs:Chrome@57.0:mac 10.12" is not a browser alias or path to an executable file.` 

Sorry if this is a duplicate from [testcafe-browser-provider-saucelabs](https://github.com/DevExpress/testcafe-browser-provider-saucelabs/issues/21), it doesn't look like anyone has been active in the repo for a few months and wanted to make sure it was seen 😃 
### Specify your

* operating system: macOS High Sierra (10.13.4)
* testcafe version: 0.20.3
* node.js version: 10.4.0

**Comment by miherlosev** [comment] 2018-06-14 09:45
> Sorry if this is a duplicate from testcafe-browser-provider-saucelabs, it doesn't look like anyone has been active in the repo for a few months and wanted to make sure it was seen

Yes, it's a duplicate of the https://github.com/DevExpress/testcafe-browser-provider-saucelabs/issues/21.
I will close this issue.

**Closed by miherlosev** 2018-06-14 09:45 UTC
