### ISSUE TITLE
Tescafe run infinite loading

### ISSUE THREAD

**Issue by ssg127** [DevExpress/testcafe#6274] opened 2021-06-02 06:30 UTC
For a few days, when executing my tests I have not been able, it keeps loading infinitely and never opens the browser. I have tried chrome, firefox and ie.

I execute:
`testcafe chrome login.spec.ts`

Until a few days ago, it was running correctly. The only thing I have updated has been chrome and the version of npm in case it solves it. It never fails, it stays charging indefinitely. I don't know where to look at logs or what to do.
 
### Your Environment details:
 
* testcafe version:                   1.14.2
* node.js version:                    v15.3.0
* command-line arguments:  `testcafe chrome login.spec.ts`
* browser name and version: Chrome Versión 91.0.4472.77
* platform and version:          Windows 10

**Comment by AlexKamaev** [comment] 2021-06-03 07:49
As far as I understand, all your browsers (chrome, ff, ie) do not even start. Besides, you do not have any error/warning message in the console. Is this correct?

If so, it can be due to some error that occurs during your tests' compilation or something else.

Please perform the following steps to help us find the cause of the issue:

* ensure that your tests hang with the latest (1.14.2) version. Run the `testcafe -v` command to make sure that you are using the latest version;
* try to run your tests with some previous TestCafe versions. Does the issue persist?
* try to run your tests on some other machine with a similar configuration;
* do you have Windows Defender or some other antivirus software? Please try to turn it off before starting TestCafe;
* run your tests on a remote browser using the `testcafe remote login.spec.ts` and navigate to the generated url;
* share your project and your set of tests with us so that we can reproduce the issue on our side.


If you cannot share your project/tests here, you can send them to support@devexpress.com

Please note that our policy prevents us from accessing internal resources without prior written approval from a site owner. As we need to access non-public parts of your website or pass through authorization pages, please ask the website owner to send us (support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing and debugging purposes.

**Comment by ssg127** [comment] 2021-06-03 09:04
It's a problem with windows 10, I have executed exactly the same thing on a MAC and it returns the available browsers and executes the tests correctly. Is there any incompatibility with new versions of windows? I have `Windows: 19043.1023.`

**Comment by AlexKamaev** [comment] 2021-06-04 07:19
No, there are no incompatibilities.
Please use the following steps and share your results:

* Do you use Windows Defender or some other antivirus software? Please turn it off before starting TestCafe.
* Use the testcafe remote login.spec.ts to run your tests on a remote browser and navigate to the generated URL.

**Comment by ssg127** [comment] 2021-06-07 15:42
I've followed all your previous steps and here has the results:

1. - ensure that your tests hang with the latest (1.14.2) version. Run the testcafe -v command to make sure that you are using the latest version; -> Yes, I've tried version 1.14.2 and 1.10.1.
2. - try to run your tests with some previous TestCafe versions. Does the issue persist? -> Yes, I've tried also version 1.10.1.
3. - try to run your tests on some other machine with a similar configuration; -> I've tried it on another colleague's computer.
4. - do you have Windows Defender or some other antivirus software? Please try to turn it off before starting TestCafe; -> Done and I still can't execute.
5. - run your tests on a remote browser using the testcafe remote login.spec.ts and navigate to the generated url; This works.

So, It's a problem with Windows for sure. Few weeks ago I can execute it propertly.

**Comment by AlexKamaev** [comment] 2021-06-08 08:15
I updated my Windows to the `19043.1023` version, but I still cannot reproduce the issue. Please try to update your TestCafe version to `1.15.0-rc.1`.
If it does not help, please install TestCafe from the following package: [https://github.com/AlexKamaev/issues/raw/master/testcafe-1.15.0-rc.1.tgz](https://github.com/AlexKamaev/issues/raw/master/testcafe-1.15.0-rc.1.tgz)
I added some console.log statements, which should help find the cause of the issue. Please share your results with us.

**Comment by ssg127** [comment] 2021-06-09 09:00
I've used your versión, but I can't see any logs.
![image](https://user-images.githubusercontent.com/36885861/121325447-e6476e00-c911-11eb-915b-1e24b95b9565.png)

**Comment by AlexKamaev** [comment] 2021-06-10 09:14
It is unexpected that you do not see any logs. It seems that for some reason TestCafe fails/hangs before even starting the browsers.
I modified my package and added more logs. I hope it will help us find the cause of the issue. Please try it again
([https://github.com/AlexKamaev/issues/raw/master/testcafe-1.15.0-rc.1.tgz](https://github.com/AlexKamaev/issues/raw/master/testcafe-1.15.0-rc.1.tgz)) and share your results with us.

**Comment by ssg127** [comment] 2021-06-10 09:26
I'm getting this output:
![image](https://user-images.githubusercontent.com/36885861/121500532-ae5a2c80-c9de-11eb-9c6c-ef35d79cb697.png)

**Comment by AlexKamaev** [comment] 2021-06-11 09:38
It looks like TestCafe hangs on the following line: [https://github.com/DevExpress/testcafe/blob/61f3703d50ef8cc64331d09659837c52a9aae862/src/runner/bootstrapper.ts#L425](https://github.com/DevExpress/testcafe/blob/61f3703d50ef8cc64331d09659837c52a9aae862/src/runner/bootstrapper.ts#L425) For some reason, TestCafe cannot obtain information about browsers.

I created another build with more detailed logs. Please try it again and share your results: [https://github.com/AlexKamaev/issues/raw/master/testcafe-1.15.0-rc.1.tgz](https://github.com/AlexKamaev/issues/raw/master/testcafe-1.15.0-rc.1.tgz).

Please also try the following command with this build: `testcafe -b` and share the command output with us.

Since it's difficult to find the problematic code in this case, we would appreciate it if you try to debug this code on your side. You can add some `debugger` statements directly to my built module or you can get TestCafe source code and build it with some `debugger` statements.

If you want to modify my module, you can find it at `node_modules/testcafe/lib`. Run `npx testcafe --inspect-brk` to debug it.

If you want to build TestCafe, you can clone this repository: [https://github.com/DevExpress/testcafe.git](https://github.com/DevExpress/testcafe.git). Then, follow these steps:

* run `npm install` in the terminal;
* add some debugger statements inside the `this._getBrowserInfo();` method;
* run `gulp fast-build` in the terminal;
* run `node --inspect-brk bin/testcafe chrome your-test-path.js`;


Then, you can debug TestCafe in debugging tools, i.e. Chrome Dev Tools: [https://testcafe.io/documentation/402801/recipes/debugging/chrome-dev-tools](https://testcafe.io/documentation/402801/recipes/debugging/chrome-dev-tools).

**Comment by pubkey** [comment] 2021-06-13 06:50
I have the same problem on linux ubuntu-18-04.
I am pretty sure it happens because of the updated chrome `91.0.4472.77`, I had no problem with `90.0.4430.0`.

**Comment by miherlosev** [comment] 2021-06-14 07:32
Hi @pubkey 

Thank for the idea about the browser update. We will investigate it. Since this issue looks similar to #6298, I will close it.
Please track #6298 to be informed about progress.

**Closed by miherlosev** 2021-06-14 07:32 UTC
Labels: STATE: Need clarification, STATE: Need response
