### ISSUE TITLE
After some tests complete successfully testcafe hangs with an ERROR The browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

### ISSUE THREAD

**Issue by jcreek** [DevExpress/testcafe#3544] opened 2019-03-08 14:02 UTC
### What is your Test Scenario?
I run a suite of tests on our [website](https://www.rapidonline.com) for simple things like clicking on buttons and checking that certain text or elements are displayed when expected. I open cmd in the folder where I store my tests and run `npm test` and off it goes. This was working fantastically for several months. Several weeks ago it started to exhibit the current behaviour below. There were no changes to our nodejs version, or our testcafe version. 
 
### What is the Current behavior?
Hangs partway through a test after successfully completing some tests, before eventually crashing and logging the following in the console: 
> `ERROR The Chrome 72.0.3626 / Windows 10.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`
 
### What is the Expected behavior?
The tests should run as normal. 
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): The base site url is https://www.rapidonline.com

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
fixture `Layout tests`
    .page(baseSiteUrl)
    .beforeEach(async t => {
        await t.maximizeWindow();
    });

test('Layout-001 - Check specific elements are in the page source.', async t => {
    //await t.setTestSpeed(0.5);
    await dismissCookieConsent(t);

    // Check that the specified elements are present (assertion with timeout)
    await t.expect(Selector('title').withExactText('Electronic Components from Rapid - the Electronic Parts Specialist | Rapid Online').exists).ok({ timeout: 5000 });
    await t.expect(Selector('link').withAttribute('rel', 'canonical').getAttribute('href')).eql('https://www.rapidonline.com/');
    await t.expect(Selector('meta').withAttribute('name', 'keywords').getAttribute('content')).eql('electronic components, electronic parts');
    await t.expect(Selector('meta').withAttribute('name', 'description').getAttribute('content')).eql('Order electronic components, parts, cables, connectors and tools today from Rapid, leading UK supplier of electronic parts. Fast delivery, bulk order discounts.');
});

test
.page(baseSiteUrl + 'Education')
('Layout-002A - Check landing on Education site type homepage directly sets site type.', async t => {
    //await t.setTestSpeed(0.5);

    // Check that the site type popup is not present (assertion with timeout)
    await t.expect(Selector('#popupTypeSelectButtonIndustry').exists).notOk({ timeout: 5000 });

    // Check that 'Schools' is selected at top left (assertion with timeout)
    await t.expect(Selector('.activeST').textContent).eql('Schools', 'activeST class not applied to \'Schools\' within 5 seconds', { timeout: 5000 });
});

test
.page(baseSiteUrl + 'Universities')
('Layout-002B - Check landing on FE/HE site type homepage directly sets site type.', async t => {
    //await t.setTestSpeed(0.5);

    // Check that the site type popup is not present (assertion with timeout)
    await t.expect(Selector('#popupTypeSelectButtonIndustry').exists).notOk({ timeout: 5000 });

    // Check that 'FE/HE' is selected at top left (assertion with timeout)
    await t.expect(Selector('.activeST').textContent).eql('FE/HE', 'activeST class not applied to \'FE/HE\' within 5 seconds', { timeout: 5000 });
});

test
.page `https://www.rapidonline.com/Education`
('Layout-003 - Check re-landing retains the previously selected site type.', async t => {
    //await t.setTestSpeed(0.5);

    // Check that the site type popup is not present (assertion with timeout)
    await t.expect(Selector('#popupTypeSelectButtonIndustry').exists).notOk({ timeout: 5000 });

    // Check that 'Schools' is selected at top left (assertion with timeout)
    await t.expect(Selector('.activeST').textContent).eql('Schools', 'activeST class not applied to \'Schools\' within 5 seconds', { timeout: 5000 });

    // Return to the site homepage 
    await t.navigateTo('baseSiteUrl/')

    // Check that 'Schools' is still selected at top left (assertion with timeout)
    await t.expect(Selector('.activeST').textContent).eql('Schools', 'activeST class not applied to \'Schools\' within 5 seconds', { timeout: 5000 });
});

test('Layout-004 - Check a guest user cannot access /Administration and is redirected to sign in page.', async t => {
    //await t.setTestSpeed(0.5);
    await dismissCookieConsent(t);

    // Navigate to the admin page 
    await t.navigateTo(baseSiteUrl + '/Administration')

    // Check redirected to baseSiteUrl + /SignIn?ReturnUrl=%2FAdministration%2F
    const getLocation = ClientFunction(() => document.location.href);

    await t.expect(getLocation()).contains(baseSiteUrl + '/SignIn?ReturnUrl=%2FAdministration');
});
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```
ERROR The Chrome 72.0.3626 / Windows 10.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
npm ERR! Test failed.  See above for more details.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Run any tests and this occurs after a few tests, the exact number varies between 2 and 8 before it crashes. 
 
### Your Environment details:
 
* testcafe version:                   originally 1.0.0, now tried 1.1.0 with the same result
* node.js version:                    originally 8.15, now tried 10 and 11.11.0 with the same result
* command-line arguments:  npm test
* browser name and version: tried with chrome, firefox, internet explorer and edge
* platform and version:          all tried on the latest version of Windows 10 Professional
* other:                                   This was working flawlessly, the versions of node and testcafe were not changed, nor did the code for these tests change. I am flummoxed.

**Comment by insanesvk** [comment] 2019-03-08 15:01
Having the same issue using https://github.com/DevExpress/testcafe-browser-provider-browserstack

**Comment by benjclark** [comment] 2019-03-11 09:17
As mentioned in https://github.com/DevExpress/testcafe/issues/3524 we're having the same issue, and so are others. We use `HeadlessChrome 74.0.3723 / Linux 0.0.0` which always ends up hanging but have found that `HeadlessChrome 74.0.3723 / Mac OS X 10.11.5` works. FYI we also use `testcafe-browser-provider-puppeteer`.

**Comment by AlexKamaev** [comment] 2019-03-11 16:07
Thank you for your enquiries. I checked the @jcreek's test and it's very likely that the cause of the error is in https://github.com/DevExpress/testcafe-hammerhead/issues/1885
Please track the progress in that ticket.

Please also refer to this [comment](https://github.com/DevExpress/testcafe/issues/3438#issuecomment-466368768) to see the possible workaround for Node >= 10.15

I'll close this issue as a duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1885
However, if the workaround does not work for you, feel free to write here, I'll reopen it.

**Closed by AlexKamaev** 2019-03-11 16:07 UTC
Labels: STATE: Need response
