### ISSUE TITLE
Add capability to specify test hooks on test run level

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5224] opened 2020-06-18 14:07 UTC
```js
  Runner.beforeEachFixture(async t => {});
  Runner.afterEachFixture(async t => {});
  Runner.beforeEachTest(async t => {});
  Runner.afterEachTest(async t => {});
```

We have similar API for the client scripts - [Runner.clientScripts](https://devexpress.github.io/testcafe/documentation/reference/testcafe-api/runner/clientscripts.html).

**Comment by benmonro** [comment] 2020-06-18 14:28
@miherlosev Thank you for moving this here.  One question though:

Would this runner approach still work with the normal CLI or only w/ the API runner?  would be nice to perhaps have a config option for 'globalSetup' similar to how JEST has `setupAfterEnv`

it could perhaps look something like this:

in .testcaferc
```json
{ "globalSetup":"path/to/setup.js"}
```

in setup.js
```js
export default function setup(runner) {
  runner.beforeEachFixture(async t => {})
}
```

**Comment by AlexanderMoiseev** [comment] 2020-06-19 14:07
Hello,

The final API is still under consideration - we will update it once we start implementing it. Please follow this thread to stay tuned.

**Comment by AndreyBelym** [comment] 2020-09-01 07:26
It is a duplicate of #4323.

**Closed by AndreyBelym** 2020-09-01 07:26 UTC
Labels: AREA: server, SYSTEM: API, TYPE: enhancement
