### ISSUE TITLE
Selectors using div with withText or withAttribute are not working

### ISSUE THREAD

**Issue by vicus-hopin** [DevExpress/testcafe#6221] opened 2021-05-12 12:13 UTC
When using selectors based on `div` combined with `withText` or `withAttribute`, tests are failing with
```
 1) Function that specifies a selector can only return a DOM node, an array of nodes, NodeList, HTMLCollection, null or undefined.
      Use ClientFunction to return other values.
```

This is not happening with other tags.

### What is your Test Scenario?
Using 2 selectors, based on `div` tag:
```
const nameDiv = Selector('div').withText('Vicus');
const tabsDiv = Selector('div').withAttribute('data-testid', 'tabs-wrapper');
```
 
### What is the Current behavior?
Test fails with:
```
 1) Function that specifies a selector can only return a DOM node, an array of nodes, NodeList, HTMLCollection, null or undefined.
      Use ClientFunction to return other values.
```
 
### What is the Expected behavior?
Test should fail because element might not exist, not because selector has wrong type
 
### What is your web application and your TestCafe test code?
Test sample for reproducing the issue. I was unable to reproduce it using a simple HTML file.

https://github.com/vicus-hopin/testcafe-issues/blob/main/src/tests/selectorIssues.js

 
```js
 const { Selector } = require("testcafe");

const user = Selector('#user_email');
const password = Selector('#user_password');
const loginButton = Selector('button.button');

fixture`Div with text`
    .page`https://hopin.com/sign_in`
    .beforeEach(async (t) => {
        await t
            .typeText(user, 'vasile.pop+666@gmail.com')
            .typeText(password, 'password123')
            .click(loginButton);
    });

test('Div with attribute', async t => {
    const navLink = Selector('a').withAttribute('data-testid', 'nav-link');
    const nameSpan = Selector('span').withText('Vicus');
    const nameDiv = Selector('div').withText('Vicus');
    const tabsDiv = Selector('div').withAttribute('data-testid', 'tabs-wrapper');

    await t
        // selector based on anchor element works fine
        .expect(navLink.visible).ok()
        // selector based on span element works fine
        .expect(nameSpan.exists).ok()
        // selector based on div throws "Function that specifies a selector can only return a DOM node"
        .expect(nameDiv.exists).ok()
        .click(nameDiv)
        .expect(tabsDiv.visible).ok();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "src": "./src/tests/**/*.js",
  "browsers": "chrome --window-size='1920,1080' --allow-running-insecure-content",
  "selectorTimeout": 10000,
  "skipJsErrors": true,
  "skipUncaughtErrors": true,
  "hostname": "localhost",
  "quarantineMode": false,
  "ajax-request-timeout": 10000,
  "page-request-timeout": 10000,
  "selector-timeout": 10000,
  "screenshots": {
    "path": "./artifacts/screenshots/",
    "takeOnFails": true,
    "pathPattern": "${TEST}/${FILE_INDEX}.png"
  },
  "reporter": [
    {
      "name": "spec"
    }
  ]
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Using locally installed version of TestCafe.
The "browsers" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 90.0.4430.93 / macOS 10.15.7

 Div with text
 ✖ Div with attribute (screenshots: /Users/vicus/Hopin/testcafe-issues/artifacts/screenshots/Div with attribute/errors/1.png)

   1) Function that specifies a selector can only return a DOM node, an array of nodes, NodeList, HTMLCollection, null or undefined.
      Use ClientFunction to return other values.

      Browser: Chrome 90.0.4430.93 / macOS 10.15.7
      Screenshot: /Users/vicus/Hopin/testcafe-issues/artifacts/screenshots/Div with attribute/errors/1.png

         23 |        // selector based on anchor element works fine
         24 |        .expect(navLink.visible).ok()
         25 |        // selector based on span element works fine
         26 |        .expect(nameSpan.exists).ok()
         27 |        // selector based on div throws "Function that specifies a selector can only return a DOM node"
       > 28 |        .expect(nameDiv.exists).ok()
         29 |        .click(nameDiv)
         30 |        .expect(tabsDiv.visible).ok();
         31 |});

         at <anonymous> (/Users/vicus/Hopin/testcafe-issues/src/tests/selectorIssues.js:28:33)
         at asyncGeneratorStep (/Users/vicus/Hopin/testcafe-issues/src/tests/selectorIssues.js:1:114)
         at _next (/Users/vicus/Hopin/testcafe-issues/src/tests/selectorIssues.js:1:452)
         at <anonymous> (/Users/vicus/Hopin/testcafe-issues/src/tests/selectorIssues.js:1:617)
         at <anonymous> (/Users/vicus/Hopin/testcafe-issues/src/tests/selectorIssues.js:1:358)
         at <anonymous> (/Users/vicus/Hopin/testcafe-issues/src/tests/selectorIssues.js:16:5)



 1/1 failed (27s)
```
</details>

### Steps to Reproduce:
Run the test above
 
### Your Environment details:
 
* testcafe version:                   1.14.0, 1.12.0, 1.9.0
* node.js version:                    14.15.0
* command-line arguments:  "test cafe chrome"
* browser name and version: Chrome 90.0.4430.93
* platform and version:          "macOS 10.15.7"

**Comment by viktoria2506** [comment] 2021-05-13 09:54
Hi,

I could not reproduce the error in your example. Could you please send us a sample application (for example, an http page)? Make sure the nameDiv element exists on your page.

In the example below, no error occurs:

![image](https://user-images.githubusercontent.com/32044161/118109108-6cdb5f00-b3e9-11eb-9ce8-51f76d168149.png)

**Comment by vicus-hopin** [comment] 2021-05-13 10:52
As mentioned, I was not able to reproduce it with a simple HTML page, but I included a full test which is reproducing every time, in a public web app.

**Comment by vicus-hopin** [comment] 2021-05-13 10:54
As mentioned in the bug description, I cannot reproduce it with a simple
HTML page (there is already a functional test in TestCafe testing that),
but I can reproduce it every time on a web app which is publicly available.
Please look at the test I added in the bug.

**Comment by viktoria2506** [comment] 2021-05-13 10:55
Hi,

I managed to reproduce the problem. We need time to figure out how to fix it.

**Comment by miherlosev** [comment] 2021-12-15 09:35
Hi @vicus-hopin 

The markup of the tested site changed. So, the test failed on this assertion.
![image](https://user-images.githubusercontent.com/4133518/146153185-7e98484a-1994-4480-8020-d2904b7ff65d.png)

I believe the issue is fixed in the latest TestCafe version (`testcafe@1.17.2-rc.2`). Try running your tests with this version and share the updated example if the issue still exists.

**Closed** 2021-12-25 10:25 UTC
Labels: STATE: Need clarification

**Comment by Jgrabenbauer** [comment] 2022-01-26 17:37
I am still running into this same issue on `1.18.1`.

**Comment by AlexKamaev** [comment] 2022-01-28 07:55
@Jgrabenbauer this issue is specific for the shared example. Your issue may have a different cause, so please create a separate issue and shared a sample to reproduce it: [https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)
