### ISSUE TITLE
Problem on CLICK action

### ISSUE THREAD

**Issue by alessandro-candon** [DevExpress/testcafe#4146] opened 2019-08-13 13:48 UTC
### What is your Test Scenario?
I want to perform a "CLICK" on a button.
 
### What is the Current behavior?
The Button is visible but the CLICK action is not performed
 
### What is the Expected behavior?
If the click is correctly submitted the behavior is the page change
 
### What is your web application and your TestCafe test code?
https://rent.decathlon.it/

 
main.js

```js
export const startPage = (uri) => {
  fixture `Getting Started from ${uri}`
    .page `https://rent.decathlon.net${uri}`;
};
```

selectors.js
```js
import { Selector } from 'testcafe';

let selectorByDay = {};
for(let i = 1; i < 34; i++) {
  selectorByDay[i] = Selector(`.days:nth-child(${i+3}) p`)
}

export const home = {
  accept_cookies: Selector('#content > app-startup > ion-content > div > app-footer > div > app-cookie-law-policy-banner > ion-toolbar > ion-grid > ion-row > ion-col:nth-child(2) > ion-button'),
  main_title: Selector('.sc-ion-label-md-h:nth-child(1) > h2'),
  place_open_modal: Selector('.ng-pristine > .native-input'),
  place_modal: {
    input: Selector('.searchbar-input'),
    first: Selector('.list > .in-list:nth-child(1) h2')
  },
  sport_open_modal: Selector('.hydrated:nth-child(2) > .item-lines-none .native-input'),
  sport_modal: {
    first: Selector('.in-list.item.ion-focusable.item-label.hydrated').nth(8).find('.sc-ion-label-md-h.sc-ion-label-md-s.hydrated')
  },
  date_open_modal: Selector('.hydrated:nth-child(3) .native-input'),
  date_modal: {
    days: selectorByDay
  },
  submit: Selector('#content > app-startup > ion-content > div > div > div > ion-grid > ion-row > ion-col:nth-child(4) > ion-button')
};

export const stores = {
  navigation_place: Selector('.info-item:nth-child(1)')
};
```
home-compile-form.e2e.spec.js
```js

import {startPage} from "../main";
import {home, stores} from "../selectors";
import {Selector} from "testcafe";

startPage('/');

test('Home test', async t => {
  await t
  // Use the assertion to check if the actual header text is equal to the expected one
    .expect(home.main_title.innerText).contains('Rent')
    .click(home.accept_cookies)
    .click(home.place_open_modal)
    .click(home.place_modal.input)
    .wait(500)
    .typeText(home.place_modal.input, 'Milano')
    .click(home.place_modal.first)
    .click(home.sport_open_modal)
    .wait(500)
    .click(home.sport_modal.first)
    .click(home.date_open_modal)
    .click(home.date_modal.days[30])
    .click(home.date_modal.days[30])
    .wait(1500)
    .expect(home.submit.exists).ok()
    .click(Selector('#content > app-startup > ion-content > div > div > div > ion-grid > ion-row > ion-col:nth-child(4) > ion-button'))
    .wait(500)
    .expect(stores.navigation_place.innerText).contains('MI');
});

```

</details>

<details>
<summary>Your complete configuration file (if any):</summary>
No configuration is used, only the command to run the test.
</details>

<details>
<summary>Your complete test report:</summary>

```
 1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

       > | Selector('.info-item:nth-child(1)')

      Browser: Chrome 76.0.3809 / Mac OS X 10.14.5

         22 |    .click(home.date_modal.days[30])
         23 |    .wait(1500)
         24 |    .expect(home.submit.exists).ok()
         25 |    .click(Selector('#content > app-startup > ion-content > div > div > div > ion-grid > ion-row > ion-col:nth-child(4) > ion-button'))
         26 |    .wait(500)
       > 27 |    .expect(stores.navigation_place.innerText).contains('MI');
         28 |});
         29 |

         at contains (/Users/acando14/Sites/dktrent-front-customer/e2e/home/home-compile-form.e2e.spec.js:27:48)
         at test (/Users/acando14/Sites/dktrent-front-customer/e2e/home/home-compile-form.e2e.spec.js:7:1)
         at <anonymous> (/Users/acando14/Sites/dktrent-front-customer/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (/Users/acando14/Sites/dktrent-front-customer/node_modules/testcafe/src/test-run/index.js:288:19)
         at TestRun.start (/Users/acando14/Sites/dktrent-front-customer/node_modules/testcafe/src/test-run/index.js:337:24)

```
</details>

### Steps to Reproduce:

1. Create the test-suite as the snippet reported
3. Execute this command to run testcafe ` testcafe chrome e2e `
4. See that the second page is not charged, so the click action is not performed.
 
### Your Environment details:
 
* testcafe version:                   1.4.0
* node.js version:                    v10.15.2
* command-line arguments:  chrome
* browser name and version:  76.0.3809.100/Google Chrome
* platform and version: 10.14.5
* other:  I also use the TestCafe IDE but it also fail.

Thank you, regards

**Comment by Farfurix** [comment] 2019-08-14 11:59
@alessandro-candon 

Hello,
 
Thank you for your detailed description. I've reproduced the issue under Windows 10 / Chrome 76.
Our team will research it and check for a suitable solution.
 
While we are working on it, I suggest you use the following `ClientFunction` workaround:
```js
const clickSubmit = ClientFunction(() => {
    document.querySelector('#content > app-startup > ion-content > div > div > div > ion-grid > ion-row > ion-col:nth-child(4) > ion-button').click();
});
```
```diff
- await t.click(Selector('#content > app-startup > ion-content > div > div > div > ion-grid > ion-row > ion-col:nth-child(4) > ion-button'));
+ await clickSubmit();
```

For team:
See the `element` value in the `_ensureElement` function: **src/client/automation/playback/visible-element-automation.js**.

**Comment by alessandro-candon** [comment] 2019-08-26 14:23
Hello @Farfurix,

thank you for your response. I also tested the code that you send to me but it doesnt' work... Is it also for you?

**Comment by alessandro-candon** [comment] 2019-08-26 14:25
Thank you!
Your workaround works well!

Regards

**Comment by rob4629** [comment] 2019-09-13 17:19
Hey 👋. Not sure if this is the correct issue to raise this on... but I'm having an issue where TestCafé _thinks_ it has clicked a button, but looking at the screenshots/failure video, it appears not to have clicked it:

```js
  async checkForMobile() {
    // const clickSubmit = ClientFunction(() => {
    //   document.querySelector('.mobile-action-button-container .btn-action').click();
    // });

    const mobileMode = (await this.mobileSignPetitionButton.exists) && (await this.mobileSignPetitionButton.visible);
    if (mobileMode) {
      await t.click(this.mobileSignPetitionButton);  // This doesn't appear to work, possible bug
      // await clickSubmit();
    }
  }
```

As you can see, I also tried the workaround, but it resulted in the same behaviour. This `checkForMobile` step passes, and my tests fail on the next step (entering in user info).

**Comment by VasilyStrelyaev** [comment] 2019-09-16 14:22
I've also noticed a similar problem with the click action when I tried to reproduce a different mobile emulation issue ([#4273](https://github.com/DevExpress/testcafe/issues/4273)).
 
I have created a separate issue for this case: https://github.com/DevExpress/testcafe/issues/4283
 
Please see if my example matches your scenario and feel free to follow up with more details.

**Comment by sjt003** [comment] 2020-04-16 20:52
can confirm. any movement on making this less flakey?

**Comment by alexey-lin** [comment] 2020-04-17 12:29
Please stay tuned. We'll update this thread once we have any news.

**Comment by girija-aul** [comment] 2020-05-22 22:36
@alexey-lin : I am also running into this issue. With mobile emulation or even with remote testing on actual iOS device, click is not working for a drop down control. The workaround of using ClientFunction is not working.
Can you share any tentative date by which we can expect the fix?

**Comment by gforepsly** [comment] 2021-08-03 14:34
I can confirm I also have the same issue. I just can't click with t.click() on some elements, but using ClientFunction works. First I had the issue when the element is not visible, but present in the DOM, now it's present and visible and same issue ocurrs. 
I hope this will be fixed soon, it's getting very anoying.

**Comment by viktoria2506** [comment] 2021-08-04 07:52
Thank you for your interest in TestCafe. We'll update this thread once we have any news. Please stay tuned.

**Comment by gforepsly** [comment] 2021-08-04 08:00
Let me also link my issue:
https://github.com/DevExpress/testcafe/issues/6208

What is the time estimate for fixing those t.click issues? This is getting really anoying, I can't just do workarounds for random UI components on which this event doesn't work. Can issues like this be prioritized? It's like basic and most important part of this framework, click is most used common action.

**Comment by saipraveenbellary** [comment] 2022-04-14 05:24
I've faced simillar issues and i've tried the below approach and it worked for me.
//first scroll to that element
await t
.scroll(element)
//first normal click on it
.click(element)
//then perform double click on it
.doubleClick(element);

Tried on two different buttons on which normal click was not working before, after trying in the above approach it is working fine.

**Comment by felis2803** [comment] 2022-04-15 06:21
@saipraveenbellary thanks, this really works.

**Comment by bogdan-calapod** [comment] 2022-10-19 09:58
Hello - any update on this ?

**Comment by rob4629** [comment] 2022-10-19 15:23
I wonder if this PR is related: #7330

**Comment by rob4629** [comment] 2022-10-21 23:10
Well, this error is where we attempt to click on a button, but it isn't performed properly. I was wondering if the PR (click enhancement) might help resolve this issue.

**Comment by Aleksey28** [comment] 2022-10-24 07:28
Do you mean the issue described here [https://github.com/DevExpress/testcafe/issues/4283](https://github.com/DevExpress/testcafe/issues/4283)? I researched it and found that this behavior is expected. The issue occurs because for the `Selector('div').withText('Start a petition')`, `testcafe` performs three steps:

1. Gets all `div` elements with the method `querySelectorAll`;
2. Filters all elements from the first step by text `Start a petition`;
3. Returns the first element from filtered elements.

The order of elements depends on the browser and a more restrictive selector should be specified. For example:
```js
Selector('div[data-qa="page-content"] a').withText('Start a petition')
```

**Comment by rob4629** [comment] 2022-10-24 20:55
> Do you mean the issue described here https://github.com/DevExpress/testcafe/issues/4283?

I wasn't referring to that particular issue, but we do have a button which is only visible in Mobile mode, that isn't always clicked properly. We get round this with a simple retry

**Comment by Aleksey28** [comment] 2022-10-25 06:24
Please share a simple sample showing your use case or a link to the issue if it already exists.

**Comment by miherlosev** [comment] 2023-02-06 04:05
Hi @alessandro-candon,

The tested website (`https://rent.decathlon.it/`) was changed, and the shared test example failed with the `Selector not found error`. Could you please fix the example?

**Comment by alessandro-candon** [comment] 2023-02-06 08:17
> Hi @alessandro-candon,
> 
> The tested website (`https://rent.decathlon.it/`) was changed, and the shared test example failed with the `Selector not found error`. Could you please fix the example?

Hi, I'm sorry but the website is not the same as before because we evolve it, the BUG was opened in 2019, 4 years ago...

**Comment by miherlosev** [comment] 2023-02-07 07:12
Thank you for your clarification. If the issue remains, please update the example so we can continue working on it.

**Closed** 2023-02-17 08:10 UTC
Labels: TYPE: bug, SYSTEM: automations, STATE: Need clarification, FREQUENCY: level 1, HAS WORKAROUND
