### ISSUE TITLE
Firefox - TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by gelyar67** [DevExpress/testcafe#2674] opened 2018-07-27 21:07 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When I run my test with Firefox I get the below error.  However I have no issue running the same test on Edge and Chrome browsers

C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\header-transforms.js:202
        return ctx.contentInfo.requireProcessing ? ctx.destResBody.length : src;
                                                                   ^

TypeError: Cannot read property 'length' of null
    at contentLength (C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\header-transforms.js:202:68)
    at applyTransform (C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\header-transforms.js:242:32)
    at C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\header-transforms.js:248:16
    at Array.forEach (<anonymous>)
    at transformHeaders (C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\header-transforms.js:247:29)
    at Object.forResponse (C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\header-transforms.js:264:12)
    at respondOnWebSocket (C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\websocket.js:63:36)
    at Object.decideOnProcessingStrategy (C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:141:47)
    at next (C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:374:38)
    at Object.checkSameOriginPolicyCompliance (C:\Users\nmusa\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:134:9)
PS C:\Users\nmusa\AppData\Roaming\npm>

### What is the expected behavior?
The test should run  in Firefox with no error

### Specify your

* operating system: Windows 10.0.0
* browser version : Firefox 61.0.0 
* testcafe version: 0.20.4
* node.js version: v8.11.3

**Comment by LavrovArtem** [comment] 2018-08-07 14:05
Hi @gelyar67,
It's a duplicate of #2438, that was fixed in the latest version - `0.20.5`. Could you please try updating to this version?

**Closed by LavrovArtem** 2018-08-07 14:05 UTC
Labels: To be reproduced

**Comment by gelyar67** [comment] 2018-08-07 19:30
Thanks @LavrovArtem.  My issue is fixed after updating testcafe to version 0.21.0
