### ISSUE TITLE
Testcafe stopped running with latest chrome update 

### ISSUE THREAD

**Issue by jwhitmore-fleetresponse** [DevExpress/testcafe#8314] opened 2024-10-23 20:04 UTC
### What is your Scenario?

Running test suite pointed to chrome browser after upgrading to Version 130.0.6723.70 (Official Build) (64-bit)

### What is the Current behavior?

An error is displayed in the console

Error: WebSocket connection closed
    at C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\chrome-remote-interface\lib\chrome.js:94:35
    at Chrome._handleConnectionClose (C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\chrome-remote-interface\lib\chrome.js:256:13)
    at WebSocket.<anonymous> (C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\chrome-remote-interface\lib\chrome.js:243:22)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.emitClose (C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\ws\lib\websocket.js:246:10)    
    at Receiver.receiverOnFinish (C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\ws\lib\websocket.js:1060:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.emit (node:domain:488:12)
    at finish (node:internal/streams/writable:953:10)

### What is the Expected behavior?

Tests should run as before

### What is the public URL of the test page? (attach your complete example)

There is no public URL, I just have all my tests suites as before and when I execute I get the following error above

### What is your TestCafe test code?

Never gets to test code errors out running cli

testcafe ./tests/**

### Your complete configuration file

{
    "browsers": "chrome",
    "concurrency": 1,
    "hostname": "localhost",
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "e2eReport.xml"
        }
    ],
    "selectorTimeout": 20000,
    "assertionTimeout": 20000,
    "pageLoadTimeout": 120000,
    "pageRequestTimeout": 120000,
    "speed": 0.8,
    "screenshots": {
        "takeOnFails": true,
        "pathPattern": "${BROWSER}/${FIXTURE}/${TEST}.png"
    }
}

### Your complete test report

ERROR Unable to open the "chrome:" browser due to the following error:

Error: WebSocket connection closed
    at C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\chrome-remote-interface\lib\chrome.js:94:35
    at Chrome._handleConnectionClose (C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\chrome-remote-interface\lib\chrome.js:256:13)
    at WebSocket.<anonymous> (C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\chrome-remote-interface\lib\chrome.js:243:22)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.emitClose (C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\ws\lib\websocket.js:246:10)    
    at Receiver.receiverOnFinish (C:\Users\jwhitmore\AppData\Roaming\npm\node_modules\testcafe\node_modules\ws\lib\websocket.js:1060:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.emit (node:domain:488:12)
    at finish (node:internal/streams/writable:953:10)

### Steps to Reproduce

1. Execute cli with chrome set as the browser
2.
3.

### TestCafe version

3.6.2

### Node.js version

20.16.0

### Command-line arguments

testcafe ./tests/**

### Browser name(s) and version(s)

Chrome Version 130.0.6723.70 (Official Build) (64-bit)

### Platform(s) and version(s)

Windows 11 Enterprise v 10.0.26100 buiild 26100

### Other

Worked fine the version before updating..129

**Comment by luoluomo** [comment] 2024-10-24 02:34
I've encountered a similar issue.

**Comment by SerbinY** [comment] 2024-10-24 16:43
> @jwhitmore-fleetresponse you can try testcafe v3.7.0-rc.1 to resolve websocket issue

I have the same issue.
Unfortunately it didn't help.

**Comment by ayemelyanenko-chegg** [comment] 2024-10-24 22:10
As a workaround, if you have Microsoft Edge installed, you can use that for your tests as Edge is Chromium based

**Comment by Bayheck** [comment] 2024-10-25 08:27
Hello,

We have released TestCafe 3.7.0-rc.2, which addresses this issue. Please try it and let us know if the issue is gone.

I will close this issue as a duplicate of
[#8300](https://github.com/DevExpress/testcafe/issues/8300)

**Closed by Bayheck** 2024-10-25 08:27 UTC
Labels: TYPE: bug, STATE: Need response

**Comment by SerbinY** [comment] 2024-10-25 10:16
> Hello,
> 
> We have released TestCafe 3.7.0-rc.2, which addresses this issue. Please try it and let us know if the issue is gone.
> 
> I will close this issue as a duplicate of [#8300](https://github.com/DevExpress/testcafe/issues/8300)

Yes, thank you! This solved the issue
