### ISSUE TITLE
v0.21.0 - Execution hangs on first command execution/jQuery not defined

### ISSUE THREAD

**Issue by maeriens** [DevExpress/testcafe#2707] opened 2018-08-08 03:10 UTC
### What is the current behavior?
Page opens, but the _Waiting for page to load_ message does not appear. Console hangs after printing the test title.

### Solution
I downgraded to v0.19.2 (Not sure why, I have been struggling with this for the past 5 hours and tried everything) and it... works. 

### How I found out something was wrong
After a few tries, I opened the console and found out that the console show a few errors, in the likes of `jQuery is not defined`, `$ is not defined`, `Cannot set property 'display' of undefined`, etc.

![image](https://user-images.githubusercontent.com/5074186/43813915-2ef56ada-9a9e-11e8-80a2-955e66467ff9.png)

Tested page URL: http://the-internet.herokuapp.com/abtest

Test code:
```js
import { Selector } from 'testcafe';

fixture`AB TESTING`
  .page`the-internet.herokuapp.com/abtest`;

test('Print out header', async t => {
  const articleHeader = Selector('#main-form .main-content h1');
  await t
    .expect(articleHeader.innerText).eql('Thank you, Peter Parker!')
}); // I know it will fail, it is the idea.
```

* operating system: Linux Mint 18.3 - Cinnamon desktop
* testcafe version: 0.21.0 and 0.19.2
* node.js version: 10.5.0
* browsers: Chrome@latest and Firefox@latest

**Comment by AndreyBelym** [comment] 2018-08-08 07:38
Hi @maeriens, I've reproduced the issue. Looks like a regression in the `testcafe-hammerhead` package.

**Comment by AndreyBelym** [comment] 2018-08-08 07:40
@LavrovArtem, it can be reproduced with the latest master ([55c3d75](https://github.com/DevExpress/testcafe-hammerhead/commit/55c3d75353a0afab07f06691f879878730e9bdd5)) in hammerhead's playground

**Comment by miherlosev** [comment] 2018-08-24 08:37
Fixed in https://github.com/DevExpress/testcafe/pull/2743

**Closed by miherlosev** 2018-08-24 08:37 UTC
Labels: SYSTEM: hammerhead, TYPE: bug
