### ISSUE TITLE
Firefox cannot read 'text-decoration' css property

### ISSUE THREAD

**Issue by amirzhan-alimov** [DevExpress/testcafe#7515] opened 2023-02-14 10:28 UTC
### What is your Scenario?

I need to read 'text-decoration' property from Selector item.

See example below.

### What is the Current behavior?

 t.expect(span.getStyleProperty('text-decoration')) returns undefined

### What is the Expected behavior?

 t.expect(span.getStyleProperty('text-decoration')) returns 'underline solid rgb(74, 74, 74)'

### What is your public website URL? (or attach your complete example)

[testcafe.zip](https://github.com/DevExpress/testcafe/files/10731515/testcafe.zip)

### What is your TestCafe test code?

```
import { Selector } from 'testcafe';

fixture('Getting Started')
    .page('https://webref.ru/css/text-decoration');

test('My first test', async t => {
    const span = Selector('#w-main > dl > dd:nth-child(8) > span')
    await t.expect(span.getStyleProperty('text-decoration')).eql('underline solid rgb(74, 74, 74)')
})
```

### Screenshots

Firefox
![image](https://user-images.githubusercontent.com/115990300/218707671-4ef87a12-8f15-4e56-8878-5a5706473e8d.png)

Chrome
![image](https://user-images.githubusercontent.com/115990300/218707717-f1b2c153-4121-4e2c-ab48-1c8df8c0639f.png)

### Steps to Reproduce

1. Run script from 'TestCafe test code' section

### TestCafe version

2.3.1

### Node.js version

v16.16.0

### Command-line arguments

npx testcafe firefox getting-started.js

### Browser name(s) and version(s)

109.0.1

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment] 2023-02-15 09:29
Thank you for the example. I managed to reproduce the issue. Until it's fixed, please use the following workaround:

```JS
test('My first test', async t => {
    const span = await Selector('#w-main > dl > dd:nth-child(8) > span')();
    await t.expect(span.getStyleProperty('text-decoration-style')).eql('solid');
    await t.expect(span.getStyleProperty('text-decoration-line')).eql('underline');
    await t.expect(span.getStyleProperty('text-decoration-color')).eql('rgb(74, 74, 74)');
});
```

For the team:
The issue is in replicator

**Comment by miherlosev** [comment] 2023-07-06 04:54
Duplicate of https://github.com/DevExpress/testcafe/issues/7800

**Closed by miherlosev** 2023-07-06 04:54 UTC
Labels: TYPE: bug, SYSTEM: automations, FREQUENCY: level 1
