### ISSUE TITLE
Error raises during switching to Iframe in IE

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#2399] opened 2018-05-14 11:06 UTC
There is no error on page without TestCafe
```js
import { Selector } from 'testcafe';

fixture `fix`
    .page `https://demos.devexpress.com/MVCxHTMLEditorDemos/Features/Features`;

test('t', async t => {
    await t
        .switchToIframe('#Html_DesignIFrame')
        .selectText(Selector('table').find('div').find('p'));
});
```

**Comment by LavrovArtem** [comment] 2018-05-23 11:27
[Issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1325) in `testcafe-hammerhead`

**Comment by AndreyBelym** [comment] 2018-08-31 15:10
I close the issue because it is a duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1325. Use https://github.com/DevExpress/testcafe-hammerhead/issues/1325 to track progress in resolving the issue.

**Closed by AndreyBelym** 2018-08-31 15:10 UTC
Labels: AREA: client, BROWSER: IE11, SYSTEM: hammerhead, TYPE: bug
