### ISSUE TITLE
iFrame loads with "failed to find a dns record", test indefinitely hangs

### ISSUE THREAD

**Issue by dgieselaar** [DevExpress/testcafe#2460] opened 2018-05-26 06:48 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
We have a test which loads an iframe with a page that's on our domain, but out our control (long story). The test is ran against a IP-protected environment. For Browserstack, we use httpAuth to connect to the environment. When we run it locally, on the VPN, everything works fine. However, when we run it on Jenkins, from an IP that is not whitelisted, or locally, when we're not on the VPN, the iframe test sometimes fails (hangs). When I open the video from Browserstack I see the following state:

![image](https://user-images.githubusercontent.com/352732/40573408-7b151670-60c1-11e8-99d3-53d704fdda2c.png)

... and the test hangs. It doesn't timeout or give an error.

I've also seen situations where we navigate to a page that generates an error in the window.onload handler, and the test hangs there as well. Maybe related?

### What is the expected behavior?

The test should either always fail or always pass. Presumably the latter, but I'm not sure *why* this message is shown.

### How would you reproduce the current behavior (if this is a bug)?

I'm not sure, I can reproduce it locally (but not always) against our private repo.

### Specify your

* operating system: Windows/Ubuntu
* testcafe version: 0.2.0
* node.js version: 8.9.0

**Comment by AndreyBelym** [comment] 2018-05-28 07:56
Hi @dgieselaar, this message is shown when browser can't find a find a resource specified by URL. It can be caused by a number of reasons. Only live session can help to figure out what's going wrong. Because you've said that you don't have problems when using VPN, I think it's a network overload or topology problem. You can use VPN for manual tests, but for Browserstack you likely have to change your server location to a place which has better connection with the BrowserStack infrastructure.

**Comment by dgieselaar** [comment] 2018-05-28 08:13
@AndreyBelym it's probably indeed an issue with our network, but what is worrying me is that the test hangs instead of failing. The test should fail no?

**Comment by miherlosev** [comment] 2018-06-25 11:42
@dgieselaar 

The test run will fail only if the page specified in `page` of `fixture` causes the `Failed to find DNS record..`.
I will close the issue until the remote session will be provided.

@dgieselaar
The test run will fail only if the page specified in the `page` or `fixture` directives causes the `Failed to find DNS record...` error. If the error is caused by other resources, the test run will not fail.

I will close the issue until we arrange a remote session.

**Closed by miherlosev** 2018-06-25 11:42 UTC
Labels: To be reproduced
