### ISSUE TITLE
Blocks second file dowloading in chrome

### ISSUE THREAD

**Issue by eugeniybalaban** [DevExpress/testcafe#1386] opened 2017-04-10 11:23 UTC
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

TestCafe blocks downloading second file in Chrome. Shows native dialog:
![image](https://cloud.githubusercontent.com/assets/27207608/24859180/25f12272-1df8-11e7-82c0-41ce85dc6567.png)

### How would you reproduce the current behavior (if this is a bug)? 

Place two file links on the page, try to click them in test.

#### Provide the test code and the tested page URL (if applicable)

Page

```html
<html>
<head>
    <title></title>
</head>
<body>
    <form id="form1">
            <a id="link1" href="file1.aaa">link1</a>
            <a id="link2" href="file2.aaa">link2</a>
    </form>
</body>
</html>
```

Test code

```js
test('DownloadTest', async t => {
    const link1 = Selector("#link1");
    const link2 = Selector("#link2");

    await t
        .click(link1)
        .click(link2);    
});
```

### Specify your

* operating system: win 8
* testcafe version: 0.14.0-alpha6
* node.js version: 7.4.0

**Comment by miherlosev** [comment] 2018-05-07 15:10
Duplicate of the https://github.com/DevExpress/testcafe/issues/2017.
Fixed in https://github.com/DevExpress/testcafe/commit/f45f4a0dc73429a6e16ae427c1fd5bd353f228b1

**Closed by miherlosev** 2018-05-07 15:10 UTC
Labels: BROWSER: Chrome, TYPE: bug
