### ISSUE TITLE
setting skipJsErrors on a lower level than configurationfile.

### ISSUE THREAD

**Issue by JWvP** [DevExpress/testcafe#3740] opened 2019-04-24 07:29 UTC
### What is your Test Scenario?
In our application we use some external packages, like PdfJs.
However, it seems the developers have written some code in a way that testcafe perceives this as javascript errors. And thus, when that package is loaded in chrome, it fails the test because they have for example an undefined 'require' implementation.
At the time of writing the only way around this for us seems to be to use the 'skipJsErrors' flag to run said scenario's successfully, however, the only place we can set this is either  the commandline, or in the configuration.

### What are you suggesting?
We'd like to be able to set these kind of flags either directly in the fixture file, or even better, at scenario level.
This way we'd be able to keep the configuration simpler, and only ignore javascript errors when absolutely needed at test level. Instead of on a test suite level.

### What alternatives have you considered?
Not testing the parts that load the package, however this is not viable as it's an integral part of our application.
Waiting for the owner of said package to update the implemenation of 'require' so that it is not undefined. However, since not sure when and even if this will ever happen, also not an option.
Using some other testing framework.

**Comment by miherlosev** [comment] 2019-04-24 09:52
Hi @JWvP 

You suggestion is a duplicate of the https://github.com/DevExpress/testcafe/issues/2775 issue.
Track the #2775 issue to be aware about our progress.

**Closed by miherlosev** 2019-04-24 09:52 UTC
