### ISSUE TITLE
Running Chrome Device Emulation w/ Tablets not able to perform left clicks anymore

### ISSUE THREAD

**Issue by sam-yh** [DevExpress/testcafe#8150] opened 2024-02-27 13:51 UTC
### What is your Scenario?

Using Chrome device emulation with a "tablet device" (iPad, Kindle), suddenly left clicks are not performed anymore, instead it seems they are "turned into" right clicks

### What is the Current behavior?

When using Chrome browser emulation with a tablet device, left click commands behave like right click commands

### What is the Expected behavior?

Left clicks should be executed as left clicks, always, including when running with Chrome's device emulation mode for tablets.

### What is the public URL of the test page? (attach your complete example)

https://testcafe.io/

### What is your TestCafe test code?

```
import { Selector } from 'testcafe'

fixture`Repro`.page`${'https://testcafe.io/'}`
test('Repro', async (t) => {
  await t.click(Selector('.burger')).wait(50000)
})
```

Run this with e.g.: `testcafe chrome:emulation:device=iPad path/to/file.js`

### Your complete configuration file

```
module.exports = { 
    disableMultipleWindows: true,
    }
```

### Steps to Reproduce

1. Create a test file with the given code snippet
2. Run the with the given command-line arguments
3. Observe what happens on the click action

### TestCafe version

3.5.0

### Node.js version

20.11.1

### Command-line arguments

testcafe chrome:emulation:device=iPad

### Browser name(s) and version(s)

Chrome 122.0.6261.69

### Platform(s) and version(s)

Ubuntu 22.04.3

### Other

I assume this is probably not a Testcafe bug. But posting this just for the off-chance there is some connection to the Testcafe codebase or the case that maybe someone else runs into this issue and can point out the actual causes.

**Comment by PavelMor25** [comment] 2024-02-29 07:41
Hello @sam-yh,

I can't reproduce the issue on my machine (Chrome 122.0.6261.69 / Ubuntu 22.04 / nodeJS 20.11.1)
Maybe you can specify the details that can help us reproduce the problematic behavior.

**Comment by sam-yh** [comment] 2024-03-04 11:43
Thanks for your reply!
I found out that it depends on [this configuration file option](https://testcafe.io/documentation/402638/reference/configuration-file#disablemultiplewindows) being set to `true`
As soon as I comment this option out, the issue is not reproducible anymore. Can you please retry with `"disableMultipleWindows": true` in your .testcaferc.js?
Updating my post above.

**Comment by Bayheck** [comment] 2024-03-15 11:22
Hello,
We found that the issue was already fixed by the following merged PR:

[https://github.com/DevExpress/testcafe/pull/8135/files](https://github.com/DevExpress/testcafe/pull/8135/files)

 

The fix will be available in the next TestCafe release.

**Closed by Bayheck** 2024-03-15 11:22 UTC
Labels: TYPE: bug
