### ISSUE TITLE
Click is registered but checkbox isn't marked

### ISSUE THREAD

**Issue by ampc** [DevExpress/testcafe#3482] opened 2019-02-22 17:56 UTC
Hi, I created this question on SO https://stackoverflow.com/questions/54687585/clicking-on-checkbox-item-doesnt-mark-element-as-checked … but for further analysis I would need to give access to our project in test environment. I've already created an account for TestCafe but I wouldn't like to share it on GitHub. Do you have any procedure on how we should do this? Thank you :)

**Comment by AlexKamaev** [comment] 2019-02-25 08:57
You can send the details at [support@devexpress.com](mailto:support@devexpress.com).

**Comment by ampc** [comment] 2019-02-25 10:40
I've sent the details :+1:

**Comment by miherlosev** [comment] 2019-02-26 12:58
We've received the credentials. However, the 'Invalid username or password.' error message is displayed when I logged in.
Please check them or resend the new credentials to us.

**Comment by ampc** [comment] 2019-02-27 11:19
I've resent the credentials to support@devexpress.com.

**Comment by Farfurix** [comment] 2019-02-28 09:47
@ampc 

Hello, thank you for providing additional information.
I've reproduced it on Windows 10 / Chrome.
I suppose this issue is related to [the following code](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/focus-blur.ts#L164):
```js
this.eventSimulator[bubblesEventType](el, relatedTarget); // bubblesEventType === 'focusout'
```
Our team will research it and check for a suitable solution.

**Comment by ampc** [comment] 2019-04-09 09:20
any updates on this? :+1:

**Comment by Farfurix** [comment] 2019-04-22 12:29
@ampc 

Hello.
Last time I could not create **a small example** to reproduce the issue. Unfortunately, the credentials and URL you provided are no longer valid. Could you please renew the access to your project with old credentials, or send us a new one?

**Comment by ampc** [comment] 2019-04-30 13:45
@Farfurix resent credentials to support@devexpress.com

**Comment by miherlosev** [comment] 2019-05-02 09:50
@ampc 

We need some time to research the problem. Please, do not restrict access to your web site until we find the cause of the problem.

**Comment by ampc** [comment] 2019-05-02 10:52
@miherlosev It may be environment instability. I didn't change any control access settings. :+1:

**Comment by AlexKamaev** [comment] 2019-05-13 12:51
fixed in https://github.com/DevExpress/testcafe/commit/c1f090932ec4b88473af552fcb4f31afaedb6a6b

**Closed by AlexKamaev** 2019-05-13 12:51 UTC
Labels: STATE: Need research, TYPE: bug
