### ISSUE TITLE
Some input events aren't fired when a button is clicked right after typing text in an input in Firefox

### ISSUE THREAD

**Issue by romanresh** [DevExpress/testcafe#1094] opened 2016-12-23 11:00 UTC
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
Some input events don't fire when a button is clicked right after typing text in an input

### What is the expected behavior?
After typing text in the second input test clicks on the button and the second input clears itself. If before button click make click to any other element inside a page and then click on the button everything works as expected (as in IE and Chrome).

### How would you reproduce the current behavior (if this is a bug)?
Run test in FF

#### Provide the test code and the tested page URL (if applicable)
```js
test('TEST', async t => {
        await t
            .click(Selector("#Content_ctl00_GridView1_col0 span[data-action='filter']"))
            .typeText(Selector("#Content_ctl00_GridView1_HFFDE_I"), "1/1/1997")
            .typeText(Selector("#Content_ctl00_GridView1_HFTDE_I"), "12/31/1997") // second input, which clears itself after button click
            .click(Selector("#Content_ctl00_GridView1_DXHFP_O")); // button

        await t.expect(Selector("#Content_ctl00_GridView1_DXDataRow0").child("td").nth(0).innerText).eql("10/3/1997");
    });
```

Tested page URL:
https://demos.devexpress.com/bootstrap/GridView/Filtering.aspx

**Comment by AlexKamaev** [comment] 2018-10-18 12:36
I've modified your test with actual selectors (it looks like the selectors on your page have changed since the bug was created).
```JS
import { Selector } from 'testcafe';

fixture `GH-1994 - The element that matches the specified selector is not visible`
    .page `https://demos.devexpress.com/bootstrap/GridView/Filtering.aspx`;

test('TEST', async t => {
    await t
        .click(Selector("#Content_GridViewHeaderFilter button"))
        .typeText(Selector("#Content_GridViewHeaderFilter_HFFDE0_I"), "7/8/2014")
        .typeText(Selector("#Content_GridViewHeaderFilter_HFTDE0_I"), "7/9/2014") // second input, which clears itself after button click
        .click(Selector("#Content_GridViewHeaderFilter_DXHFP_TPCFCm1_P button")); // button

    await t.expect(Selector("#Content_GridViewHeaderFilter_DXDataRow0").child("td").nth(0).innerText).eql("7/8/2014");
});
```
I cannot reproduce the issue now, and I'll close it. If the issue still occurs, feel free to reopen it.

**Closed by AlexKamaev** 2018-10-18 12:36 UTC
Labels: AREA: client, BROWSER: Firefox, SYSTEM: automations, TYPE: bug
