### ISSUE TITLE
Issues with t.takeElementScreenshot

### ISSUE THREAD

**Issue by Arawnh** [DevExpress/testcafe#2402] opened 2018-05-14 14:17 UTC
### Are you requesting a feature or reporting a bug?

a potential bug

### What is the current behavior?

When using await t.takeElementScreenshot, whether I use ReactSelector or regular Selector - it always takes screenshot of whole page. I click on the element beforehand to see if selector is correct and it works. But no luck getting elementscreenshot function to work so far.

### Specify your

* operating system: win 10
* testcafe version: latest
* node.js version: 9

**Comment by AndreyBelym** [comment] 2018-05-15 09:29
@kkowalczuk, could you please specify your OS version?

Also, @Arawnh, @kkowalczuk could you please try to run the following test and report result to me?
```
fixture `Test DPR`
    .page `example.com`;

test(`get DPR`, async t => {
    console.log(await t.eval(() => window.devicePixelRatio));
});
```

> I noticed that the problem occurs when the browser window opened on testcafe does not fit into the screen resolution - when parts of the browser are cropped or split into multiple screens.

It's very hard to make screenshot in this situation, because a browser window is logically tied to specific screen, and it's really tough to find remaining pieces of a window on other screens. I think you can make correct screenshot in this situation only for Chrome or Firefox through debugging protocols. If you need a window bigger than your screen, you can use Chrome emulation mode. https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html

**Comment by kkowalczuk** [comment] 2018-05-15 11:04
@AndreyBelym Win10, 65.0.3325.181.

> It's very hard to make screenshot in this situation, because a browser window is logically tied to specific screen, and it's really tough to find remaining pieces of a window on other screens.

Frankly speaking - I don't believe it is a problem, without those changes in mark generation mentioned above, the screenshots were handled correctly. Also, when `t.takeElementScreenshot` gives up, the screenshot of the whole page is being created (as @Arawnh reported in the first post) - the problem might be with cropping logic rather than in the capturing mechanism.

For the time being I don't have enough time to dig deeper...

**Comment by AndreyBelym** [comment] 2018-05-15 13:17
I can reproduce the issue by setting scaling in Windows display settings to fractional values, like 125% or 150%.

**Comment by AndreyBelym** [comment] 2018-06-18 08:47
This issue must be fixed by https://github.com/DevExpress/testcafe/pull/2492. I'll notify you when a build with the fix will be published on NPM. Feel free to try the fixed build and reopen the issue if the problem isn't solved in your environment.

**Closed by AndreyBelym** 2018-06-18 08:47 UTC
Labels: AREA: server, SYSTEM: browser natives, TYPE: bug
