### ISSUE TITLE
Need log support on each action to track the testcafe navigation on elements

### ISSUE THREAD

**Issue by AutomationTester143** [DevExpress/testcafe#5163] opened 2020-06-03 06:00 UTC
### What is your Test Scenario?
I want to print each selector element on logs with actions like click and type. Right now we can print the logs using console.log() but using this option one has to write log code for each line which is very time-consuming.

For example:
Typing on "Username"
Clicking on "buttonID"
........................

Logs will help us for tracking and debug during off time

### What are you suggesting?
Required console logs for each action performing on web page.

this should be control from testcaferc.json or through runner.

"PrintlogsforActions": true

**Comment by miherlosev** [comment] 2020-06-03 13:47
Duplicate of https://github.com/DevExpress/testcafe/issues/4001

**Closed by miherlosev** 2020-06-03 13:47 UTC
Labels: STATE: Need response
