### ISSUE TITLE
Ensure that "headless" and "userProfile" browser modes are not used together

### ISSUE THREAD

**Issue by salmansrabon** [DevExpress/testcafe#5221] opened 2020-06-18 03:35 UTC
Test Scenario:
A very simple test scenario runs in firefox and chrome:userProfile headless mode
It hangs!

Error is: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

**Comment by Farfurix** [comment] 2020-06-18 12:36
@salmansrabon 

Hello,

I've reproduced the issue under Windows 10. Our team will examine it and look for a solution.

In the meantime, I suggest you use the following order of arguments (`:headless:userProfile`):
**Make sure you do not have running browser instances**.
```
testcafe chrome:headless:userProfile test.js
testcafe firefox:headless:userProfile test.js
```
Result:
![Capture](https://user-images.githubusercontent.com/30019338/85017671-8d1c8280-b174-11ea-8c41-8b1d0daa669d.PNG)

For the team.
Scenarios where the problem is reproduced:
1.`testcafe chrome:userProfile:headless test.js`
![Capture](https://user-images.githubusercontent.com/30019338/85016098-bab3fc80-b171-11ea-90f7-ce3f7b9f53cc.PNG)
2. Use `testcafe firefox:userProfile:headless` twice. After the first execution, the Firefox process **is still present** in Task Manager.
![Capture](https://user-images.githubusercontent.com/30019338/85015767-382b3d00-b171-11ea-954a-da5e5f059e1e.PNG)

**Comment by salmansrabon** [comment] 2020-06-18 12:57
Great work! Thanks a lot. It's working now.

**Comment by salmansrabon** [comment] 2020-06-18 13:11
Still I found another error, that is when chrome run in headless with userProfile mode, then actually userProfile mode is not working at all. It cleans all user configuration while starting the automation.
But ok for firefox browser.

cmd:> testcafe chrome:headless:userProfile test.js

**Comment by Farfurix** [comment] 2020-06-18 13:20
@salmansrabon 

Thank you for your update. We'll take it into account.

**Comment by AlexKamaev** [comment] 2023-08-10 08:46
I did not manage to reproduce the issue, so I'll close it. If the issue persists in your case, please feel free to create a separate issue with a reproducible example and a detailed description of your usage scenario.

**Closed by AlexKamaev** 2023-08-10 08:46 UTC
Labels: TYPE: enhancement
