### ISSUE TITLE
Support option to prevent useRole from redirecting

### ISSUE THREAD

**Issue by viveleroi** [DevExpress/testcafe#3491] opened 2019-02-26 01:31 UTC
### What is your Test Scenario?

I'm noticing that I need to call `useRole` for every fixture and that every time it's called, the browser redirects to the "original url" (stuff preserveUrl applies to).

Problem is, that route change is unnecessary in almost all of my cases. I want to auth a user, and hit 100 different pages to test them. I don't also want 100 extra route changes back to this user page.

### What are you suggesting?

Maybe an option to `useRole` or maybe on the `RoleOptions` object. Something that disables redirect when called.

### What alternatives have you considered?

I've looked for ways to avoid calling `useRole` every fixture but it doesn't seem possible. I did a very basic test by running a login test and a regular test in that order, the second never has the auth state unless I call `useRole` a second time.

**Comment by AndreyBelym** [comment] 2019-02-26 06:17
This seems to be a duplicate of #2195. Currently, TestCafe can't use a Role without reloading or triggering page navigation. I am closing this ticket.

**Closed by AndreyBelym** 2019-02-26 06:17 UTC

**Comment by viveleroi** [comment] 2019-02-26 17:32
Am I correct then that `useRole` needs to be called once in every `test` function? I was hoping I only needed to call it when switching roles but that appears incorrect.

**Comment by AndreyBelym** [comment] 2019-02-27 07:04
You can call `useRole` in a [beforeEach hook](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#initialization-and-clean-up) to avoid calling it in each test.

**Comment by viveleroi** [comment] 2019-02-27 18:09
Thanks, I forgot that was an option. It keeps the code cleaner but I dislike the redirect every useRole call, it's an unnecessary http load and definitely affects the time taken.

**Comment by viveleroi** [comment] 2019-02-28 00:42
That isn't working for me.

```
fixture `test`
.beforeEach(async t => {
     await t.useRole(regularUser);
 });
```

When my test actually begins it kicks me back to the login page (which happens when not authenticated), yet using `useRole` inside the actual test works fine. Did I miss something?

**Comment by AndreyBelym** [comment] 2019-03-01 08:10
I see that you've created a separate issue that looks very similar to your question: https://github.com/DevExpress/testcafe/issues/3511. Thus I will answer it in issue #3511.

**Comment by viveleroi** [comment] 2019-03-01 15:14
I did, primarily because this was a separate issue but maybe it was only happening as a result of my "incorrect" use (aka not using the workaround in #3511) of useRole.

Originally I was seeing the browser navigate back to the app dashboard and I misread the docs, it sounded like useRole intentionally navigated away from my test page. 

I've since realized that "navigate away" was due to how useRole works, and is the basis for #3511

**Comment by AndreyBelym** [comment] 2019-03-06 13:47
Thank you for clarifying the problem.
