### ISSUE TITLE
If url = not localhost in useRole, not logout when i try switch role

### ISSUE THREAD

**Issue by abnorman23** [DevExpress/testcafe#3559] opened 2019-03-13 11:54 UTC
### What is your Test Scenario?
1. Login as user1
2. Send message
3. Login as user2
4. Read message
 
### What is the Current behavior?
If url in userRole = http://localhost:3000:
.useRole(user1) =>
1. Login as user1
2. Send message
.useRole(user2) =>
1. Automatic logout from user1
2. Login as user2
3. Expect message

If url in userRole = not http://localhost:3000 (example = https://dev.webchat.com):
.useRole(user1) =>
1. Login as user1
2. Send message
.useRole(user2) =>
1. DONT automatic logout from user1
2. Try login as user2 => did not found selector from 1 step in useRole(user2) = .typeText(input, validLogin2) because user1 is login.

### What is the Expected behavior?
If url in userRole = http://localhost:3000:
.useRole(user1) =>
1. Login as user1
2. Send message
.useRole(user2) =>
1. Automatic logout from user1
2. Login as user2
3. Expect message

If url in userRole = not http://localhost:3000 (example = https://dev.webchat.com):
.useRole(user1) =>
1. Login as user1
2. Send message
.useRole(user2) =>
1. Automatic logout from user1
2. Login as user2
3. Expect message
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
Sorry, it is not possible and i think it not really need.
We use local Storage for userID and token.
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
 File "userRole.js":
```js
import { Role } from 'testcafe';

export const user1 = Role(url, async t => {
    await t
        .typeText(input, validLogin)
        .typeText(password, validPassword)
        .click(loginButton);
}, { preserveUrl: true });

export const user2 = Role(url, async t => {
    await t
        .typeText(input, validLogin2)
        .typeText(password, validPassword2)
        .click(loginButton);
}, { preserveUrl: true });
```
 
File "chat.ts":
```js
import { user1, user2 } from '../../userRole';

fixture `Chat [chat.ts]`;
test('1. Send message and read message', async t => {
  await t
    .useRole(user1)
    .click(dialog.withText('user2'))
    .typeText(inputMessage, message)
    .click(sendButton)
    .useRole(user2)
    .click(dialog.withText('user1'))
    .expect(lastMessage.innerText).eql(message, 'Not found last message');
}); 
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 ✖ 1. Send message and read message

   1) - Error in Role initializer -
      The specified selector does not match any element in the DOM tree.

         | Selector('input')
       > |   .withAttribute('id', 'phone')
```
</details>

<details>
<summary>Screenshots:</summary>

```
Won't help
```
</details>

### Steps to Reproduce:

1. Try to switch user use useRole on not localhost url

 
### Your Environment details:
 
* testcafe version: 0.23.3                  
* node.js version: v10.15.0                   
* command-line arguments:   testcafe chrome tests/chat.ts 
* browser name and version: Chrome 72.0.3626 
* platform and version: Linux Fedora release 29          
* other:

**Comment by miherlosev** [comment] 2019-03-14 14:13
@abnorman23 

I am afraid this information is not sufficient to find the cause of the issue. 
Could you please provide a public link to your site or small web application that imitates the site behavior? 
We also need the full test code that performs all test action described above.

**Comment by abnorman23** [comment] 2019-03-15 05:44
You can find it at "Your complete test code (or attach your test files):"

**Comment by abnorman23** [comment] 2019-03-15 05:45
I think the reason is the difference between http and https.

**Comment by miherlosev** [comment] 2019-03-15 11:33
> You can find it at "Your complete test code (or attach your test files):"

Thank you for the provided information.
To find the cause of the problem, I also need a web application for which I will run the provided tests.
Could you please provide a public link to your site or small web application that imitates the site behavior?

**Comment by AlexKamaev** [comment] 2019-04-30 11:54
I closed this issue because we haven't received any response on our request for more information

**Closed by AlexKamaev** 2019-04-30 11:54 UTC

**Comment by abnorman23** [comment] 2019-04-30 18:20
Очень удобно

**Comment by AlexSkorkin** [comment] 2019-05-01 12:32
@abnorman23,
We examined the test code you provided in the "Your complete test code (or attach your test files)" section. However, this information is insufficient for us to determine the cause of the issue. We will be happy to debug the issue, however, we need your public accessible website URL or a simple sample that we can execute locally on our side. The 'https://dev.webchat.com/' URL you mentioned is not reachable and we're unable to debug the problem.
