### ISSUE TITLE
Initial t.navigateTo() hangs when it's called after ~15s

### ISSUE THREAD

**Issue by reneses** [DevExpress/testcafe#3118] opened 2018-11-14 17:34 UTC
### What is your Test Scenario?
The fixture code takes more than 15s to set up the initial state. Same thing happens if the init code is moved within the `test()` function (but before the `t.navigateTo()`).
 
### What is the Current behaviour?
While doing `t.navigate(..)`, TestCafe hangs and the browser stays in the blank page (e.g. `http://X.X.X.X:58341/s_CyoU6ih/about:blank`). If you manually click "back" in the browser, it navigates and the test continues.
 
### What is the Expected behavior?
TestCafe should redirect, even if the fixture takes more than 15s (or at least fail the test).
 
### What is your web application and your TestCafe test code?
It can be reproduced in any fixture/test. I've attached a minimal version.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture`Test 1`.beforeEach(
  async (t) => {
    console.log('a');
    await new Promise(resolve => setTimeout(resolve, 15000)); // 14 is fine, 15 isn't
    console.log('b');
  }
);

test('test 1', async (t) => {
  console.log('c');
  await t.navigateTo('http://www.google.com');
  console.log('d');
});

fixture`Test 2`.beforeEach(
  async (t) => {
    console.log('a');
  }
);

test('test 2', async (t) => {
  console.log('b');
  await new Promise(resolve => setTimeout(resolve, 15000)); // 14 is fine, 15 isn't
  console.log('c');
  await t.navigateTo('http://www.google.com');    
  console.log('d');
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
$ testcafe chrome test.js
 Running tests in:
 - Chrome 70.0.3538 / Mac OS X 10.11.6

 Test 1
a
b
c
```
</details>

### Steps to Reproduce:

In any fixture/test:

1. Before `t.navigateTo()`, do any code that takes more than 15 seconds. We originally discovered this doing API calls, but it can also be reproduced with an artificial `await new Promise(resolve => setTimeout(resolve, 15000));`

2. `t.navigateTo()` will do nothing, and the test will hang.

From the attached code ([testcafe-bug.zip](https://github.com/DevExpress/testcafe/files/2584841/testcafe-bug.zip)):

1. `yarn`
2. `yarn testcafe chrome test.js` (same with firefox)

Funny thing, if I pull & build `testcafe` manually into my `node_modules` folder, it works. The issue is only present when using `testcafe` as a dependency.

### Your Environment details:
 
* testcafe version: 0.23.2 (also reproduced in 0.23.1, 0.23.0; 0.22.x works fine)
* node.js version: v8.9.4
* command-line arguments:  yarn testcafe chrome test.js 
* browser name and version: Chrome 70.0.3538.102, Mozilla Firefox 60.2.2
* platform and version:          macOS 10.11.6

**Comment by AndreyBelym** [comment] 2018-11-15 11:54
This thread appears to be a duplicate of #3070. Please use the original thread to get notifications about our progress with resolving this problem. We take such issues seriously and will get to the bottom of it.

**Closed by AndreyBelym** 2018-11-15 11:54 UTC
