### ISSUE TITLE
Add a separate property for the reporter factory function

### ISSUE THREAD

**Issue by mokone91** [DevExpress/testcafe#6286] opened 2021-06-07 15:53 UTC
Seems it's not possible to use local reporter using config file now.
Its can be wery useful feature, especially as is possible with js interface.
```

{
    reporter: [
        {
            'name/path': 'test/reporter.ts',
            'output': './e2e_report.xml'
        }
}
```

**Comment by mokone91** [comment] 2021-11-24 10:58
Hi! seems js configuration already implemented, is there any guide which shows how can i use my local reporter?

**Comment by Dmitry-Ostashev** [comment] 2021-11-26 11:42
Hi @mokone91,

You can specify your local reporter in the JS configuration file in the following way:

.testcaferc.js

```
const reporter = require('./reporter');

module.exports = {
    reporter,
    browsers: 'chrome',
    src: ['test.js']
}
```

**Comment by mokone91** [comment] 2021-11-26 14:28
Hi! 
So i have implemented it using next snippet: 

`const customReporter = require('./customReporter');

module.exports = {
  ...
  reporter: [
    {
      name: 'spec'
    },
    {
      name: customReporter,
      output: './reports/e2e_report.xml'
    }
  ],
}
`

and seems it works as expected, the only point here - I passing reporter as name

**Comment by miherlosev** [comment] 2021-11-29 09:25
@mokone91 

It occurred due to the parsing reporting parameters algorithm. It's not part of a public API and can be changed at any time. Please, use the approach from the https://github.com/DevExpress/testcafe/issues/6286#issuecomment-979916850.

**Comment by mokone91** [comment] 2021-11-29 09:53
> @mokone91
> 
> It occurred due to the parsing reporting parameters algorithm. It's not part of a public API and can be changed at any time. Please, use the approach from the [#6286 (comment)](https://github.com/DevExpress/testcafe/issues/6286#issuecomment-979916850).

Hi @miherlosev

But how then I can select multiple reporters and configure outputPath for custom?

**Comment by miherlosev** [comment] 2021-12-01 09:04
https://github.com/DevExpress/testcafe/issues/6286

Hi @mokone91 

We discussed this with @AndreyBelym one more time and decided the following:
1. We should make a separate property for a reporter if it's specified as a factory function.
```js
const customReporter = require('./customReporter');

module.exports = {
  ...
  reporter: [
    {
      name: customReporter,
      output: './reports/e2e_report.xml'
    }
  ],
}
```

2. The `name` property should accept only the `string` name of a reporter. We should raise a warning if the value of the another type is accepted.
3. We recommend using the `name` property until the new property is implemented.

**Comment by AlexKamaev** [comment] 2023-08-10 08:05
Since there is a workaround (using the `name` property) and the issue is not popular among TestCafe users, we decided to close it.

**Closed by AlexKamaev** 2023-08-10 08:05 UTC
Labels: TYPE: enhancement
