### ISSUE TITLE
Unable to Login to Guidewire application

### ISSUE THREAD

**Issue by Subhasish14** [DevExpress/testcafe#7091] opened 2022-06-15 14:48 UTC
### What is your Scenario?

Hello ,

I am trying to automate a Guidewire Application using testCafe. But I am facing navigation issue. I am unable to login with username password and navigate to the home page . The script is entering username and password values in respective fields then clicking on login. But it is not navigating to next page .

Can you please give any idea what i should do to resolve this issue ?

### What is the Current behavior?

The script is not navigating to next page after clicking on login button in login page.

### What is the Expected behavior?

The script should navigate to next page after clicking on login button .

### What is your public website URL? (or attach your complete example)

http://su:gw@demoqa.cbt-dev.net:8180/pc/PolicyCenter.do

### What is your TestCafe test code?

import {Selector, ClientFunction, fixture} from 'testcafe'

fixture `test`
.page `http://44.241.32.245:8280/ab/ContactManager.do`

test ('PC login test', async t=>{

    await t.maximizeWindow();

    const username = Selector('input').withAttribute('name', 'Login-LoginScreen-LoginDV-username');
    const password = Selector('input').withAttribute('name', 'Login-LoginScreen-LoginDV-password');
    const login = Selector('div').withText('Log In');

    await t.typeText(username,'su')
    await t.typeText(password,'gw')
    await t.setNativeDialogHandler(() => true).click(login)
   

  

   await t.expect(Selector('#TabBar-LogoutTabBarLink').innerText).contains('Log Out Super User')
})

### Steps to Reproduce

1.Open the application login page
2.give login credential
3.velidate that home page is displayed

### TestCafe version

1.18.6

### Node.js version

17

### Command-line arguments

npm run test

**Comment by Dmitry-Ostashev** [comment] 2022-06-16 07:31
Hello,

Thank you for your report. We would love to assist you and diagnose this issue. However, our policy prevents us from accessing internal resources without a prior written approval from a site owner. If you'd like us to research the issue further directly on your side, please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by Subhasish14** [comment] 2022-06-16 15:00
Provided access to the website.
Please refer below image for clarity - 
![image](https://user-images.githubusercontent.com/93317608/174099768-9960d6fd-d139-4f00-a8d3-62e08fa03e04.png)

**Comment by Dmitry-Ostashev** [comment] 2022-06-17 13:59
Thank you for the approval. I was able to reproduce the issue.
For the Team: you can see the problem also when opening the website via the testcafe-hammerhead playground.

**Comment by Subhasish14** [comment] 2022-06-27 12:23
@Dmitry-Ostashev 
Hello , any update on this issue ?

**Comment by Subhasish14** [comment] 2022-07-21 12:47
@Dmitry-Ostashev 
Hello , any update on this issue ?

**Comment by Artem-Babich** [comment] 2023-04-13 06:52
We will close this issue since it is fixed in the [Native Automation mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode). Please try the native automation mode in your tests.
Feel free to reopen the issue if you need a fix for the other browsers or you cannot use Native Automation for some reason.

**Closed by Artem-Babich** 2023-04-13 06:52 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, STATE: possibly fixed in native automation

**Comment by PavelMor25** [comment] 2024-01-10 08:21
Hello @Jagadesh770,

TestCafe v3.0.0 and newer enable `native automation mode` out of the box. 
Please refer to the following help topic to learn more about [Native Automation.](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode)

**Comment by Jagadesh770** [comment] 2024-01-10 10:32
**I upgraded my testcafe version to above 3.0.0v. but now I am facing an issue**

"TypeError: Cannot destructure property 'baseUrl' of 'undefined' as it is undefined.
    at new APIBasedTestFileCompilerBase (C:\Users\JagadeshKoduru\gt-framework-2022.9.0\gt-framework\gt-ui\node_modules\testcafe\src\compiler\test-file\api-based.js:40:20)"

<img width="682" alt="Screenshot 2024-01-10 155915" src="https://github.com/DevExpress/testcafe/assets/111558721/f12bef71-4ad0-4118-aad6-1bac9dda4d6f">

**Comment by PavelMor25** [comment] 2024-01-11 07:28
This ticket is closed. Please create a separate ticket using this [template](
https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)  and add a [Minimal Working Example](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue) without Cucumber, as officially, we do not support it in TestCafe.
