### ISSUE TITLE
XMLHttpRequest fails on withCredentials line - undefined object

### ISSUE THREAD

**Issue by pliekhus** [DevExpress/testcafe#6854] opened 2022-02-07 13:45 UTC
### What is your Scenario?

When trying to call a lazy loaded JavaScript XMLHttpRequest call to load additional page data, hammerhead.js is throwing an error on the .withCredentials line

![XHRWithCredentials](https://user-images.githubusercontent.com/4270185/152798390-88a3e449-0ccd-4fff-baf4-863d11b1d908.PNG)

![XHRWithCredentialsConsole](https://user-images.githubusercontent.com/4270185/152798809-45935a72-3cbf-48dd-b64b-b5b97d03aa7e.PNG)

### What is the Current behavior?

XMLHttp call fails in attached screenshots

### What is the Expected behavior?

The XMLHttp request should be allowed to complete successfully.  Page works outside the testing script.

### What is your public website URL? (or attach your complete example)

https://www.rsaconference.com/experts

### What is your TestCafe test code?

 await t
        .click(Selector('main a').withText('AGENDA'))    
        .click(Selector('main a').withText('FULL AGENDA'))

### Steps to Reproduce

1. Open the Experts page using the Coveo search mechanism
2. Error is thrown and page does not load - shows blank boxes
3. Viewing the console shows the error being thrown by hammerhead

### TestCafe version

1.18.3

### Node.js version

14.5.0

### Command-line arguments

testcafe \"chrome\" mobile-tests/**/* --reporter spec,xunit:report.xml --skip-js-errors --proxy-bypass *.coveo.com

**Comment by Dmitry-Ostashev** [comment] 2022-02-08 08:44
Thank you for your report. I reproduced the issue with the testcafe-hammerhead module and the `gulp https-playground --dev` command.

**Comment by miherlosev** [comment] 2022-02-11 11:36
Duplicate of https://github.com/devexpress/testcafe-hammerhead/issues/2634

**Closed by miherlosev** 2022-02-11 11:36 UTC
Labels: TYPE: bug, SYSTEM: hammerhead
