### ISSUE TITLE
Typing text with testcafe is slow in our app for a particular page, dropdown actions in that page are executing fast

### ISSUE THREAD

**Issue by Vooha-QualiTlabs** [DevExpress/testcafe#6614] opened 2021-10-14 08:11 UTC
### What is your Test Scenario?
Typing text in a text field (**Attached code as Zip File)**
 
### What is the Current behavior?
Taking long time to enter the text for a specific page elements(pls check the video, it is happening with few fields only)
 
### What is the Expected behavior?
It should enter the text right away
 
### What is your web application and your TestCafe test code?

![Screen Recording 10-14-2021 at 1 34 PM](https://user-images.githubusercontent.com/91185844/137277364-d8716774-8230-485d-a36d-64c3409e3481.gif) 

https://user-images.githubusercontent.com/91185844/146340823-854082da-948b-4890-94dd-99bafcbcaae7.mp4

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
[code.zip](https://github.com/DevExpress/testcafe/files/7726690/code.zip)

</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/91185844/137277605-9c964560-7ddb-4bad-a7a3-c750ab267c9b.png)

```

```
</details>

### Steps to Reproduce:

1. Go to my website  [xeniapp.com](https://xeniapp.com/)
2. Book a hotel/Car
3. Go to the checkout page
4. Enter the details in the text fields
5. It is observed that for test cafe, it is taking more time to enter the text
 
### Your Environment details:
 
* testcafe version:      1.16.0              
* node.js version:         v 14.17.4           
* command-line arguments:  
* browser name and version: Chrome 94.0.4606.81  
* platform and version:   Windows 10       
* other:

**Comment by Vooha-QualiTlabs** [comment] 2021-12-16 09:06
@AlexKamaev @rybesh @Mehul Please look into this issue once, could you let me know if this can be fixed? thank you

**Comment by Dmitry-Ostashev** [comment] 2021-12-17 08:38
@Vooha-QualiTlabs Could you please attach a simple test script that illustrates the issue?

If the testing flow requires the login process on your website, please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes. Our policy prevents us from accessing internal resources without a prior written approval from a site owner.

**Comment by Vooha-QualiTlabs** [comment] 2021-12-17 09:06
Thank you for looking into this. @Dmitry-Ostashev. Pls find code from the attached below

[code.zip](https://github.com/DevExpress/testcafe/files/7733847/code.zip)

**Comment by Dmitry-Ostashev** [comment] 2021-12-20 11:53
Thank you for the code example. I reproduced this behavior with my own credentials. We will research it and update this thread once we have any news.

**Comment by Vooha-QualiTlabs** [comment] 2021-12-20 12:00
Great news, thank you @Dmitry-Ostashev

**Comment by Vooha-QualiTlabs** [comment] 2022-01-05 08:11
@Dmitry-Ostashev Any update on this? thank you

**Comment by Vooha-QualiTlabs** [comment] 2022-03-28 11:25
@Dmitry-Ostashev Any update on this by chance? thanks.

**Comment by Aleksey28** [comment] 2022-03-29 06:59
Hi @Vooha-QualiTlabs

We still don't have any updates. Once we get any results, we will post them in this thread.

**Comment by Vooha-QualiTlabs** [comment] 2022-04-15 13:08
@Dmitry-Ostashev Do you think that we have any alternative for sending text to prevent this issue? 

Because of this issue, our test scripts taking too much time to execute. This is really not avoidable. Please help me. Thank you.

**Comment by miherlosev** [comment] 2022-04-20 08:24
Hi @Vooha-QualiTlabs,

Try to use the [paste](https://testcafe.io/documentation/402674/reference/test-api/testcontroller/typetext#options) option to speed up text entering.

**Comment by Vooha-QualiTlabs** [comment] 2022-04-20 09:51
Hello @miherlosev , It is the same case with the paste option as well, this issue is still reproducing. Thanks.

**Comment by Artem-Babich** [comment] 2022-04-21 13:54
Hi @Vooha-QualiTlabs !

I have tried to reproduce the issue again, but the URL domain you shared above is no longer available. Also, according to the following issue, you now have a custom mechanism that does not allow you to run tests without some code modifications: [6803](https://github.com/DevExpress/testcafe/issues/6803).
Could you please update the code sample and share instructions on how to reproduce the issue so that I can reproduce and research it in detail?

**Comment by Vooha-QualiTlabs** [comment] 2022-04-21 14:13
@Artem-Babich  Could you let me know from which country are you accessing the app?

**Comment by Artem-Babich** [comment] 2022-04-22 07:55
I tried to access your app from Armenia. Also, it would be great if you share a simplified version of the web page you are testing. In this case, I will be able to reproduce the issue locally and determine its exact cause.

**Comment by Vooha-QualiTlabs** [comment] 2022-04-22 10:28
@Artem-Babich  

Here is the sample code for it:
[code.zip](https://github.com/DevExpress/testcafe/files/8539965/code.zip)

Please let me know if you need more details. Thanks.

**Comment by Artem-Babich** [comment] 2022-04-25 16:27
Thank you for the code samples. With some code modifications I was able to run the second sample and reproduced the issue. It may take additional time to determine cause of this issue. We will update this thread once we have any news.

**Comment by yadimon** [comment] 2022-04-25 21:27
have same problem, dont know how to debug it to find out why is the "typeText" is so slow. Same effect with flashes as by @Vooha-QualiTlabs

**Comment by Artem-Babich** [comment] 2022-04-26 10:43
Hi again!
This issue seems to be related to the fact that your editors have two labels, one of which is invisible. Please try to remove the invisible label and reproduce the issue again. 

Also, as a workaround, you can specify a timeout for the selectors of these editors:
 ```
async setGuestsNames (guestsData, Selector) {
   ...
```
```
test.only('Add and Verify Guest details', async () => {
   ...
   const selector = (sel) => Selector(sel, { timeout: 100 });
   await hotelPage.setGuestsNames(guestsData,selector);
```

I look forward to your results.

**Comment by Artem-Babich** [comment] 2022-04-26 11:05
Hi again!
This behavior is unexpected. This issue seems to be related to the fact that your editors have two labels, one of which is invisible. Please try to remove the invisible label and reproduce the issue again.

Also, as a workaround, you can specify a timeout for the selectors of these editors:
```
async setGuestsNames (guestsData, Selector) {
   ...
```
```
test.only('Add and Verify Guest details', async () => {
   ...
   const selector = (sel) => Selector(sel, { timeout: 100 });
   await hotelPage.setGuestsNames(guestsData,selector);
```
I look forward to your results.

**Comment by Vooha-QualiTlabs** [comment] 2022-05-02 06:54
@Artem-Babich  Yes, with the selector timeout, the typing text works super fast now. Thanks for the workaround.

**Comment by Artem-Babich** [comment] 2022-05-04 12:26
Hi @Vooha-QualiTlabs,

I just tried to investigate this issue further, however, I noticed that you changed your application. I no longer have access to the problematic page.
Would you please share more details about your application? For example, let us know if you are using some client-side library or framework (e.g. React, Angular, Vue). If so, please share the source code of these editor components.
Also, please open the problematic page with DevTools (F12) and copy the resulting markup block with your editors and share it with us.
I look forward to your reply.

**Comment by Vooha-QualiTlabs** [comment] 2022-05-04 13:28
Hello @Artem-Babich , 

Yeah, it seems like the env is changed pretty much. Our application is React based. Here is one of the problematic element's html 
![image](https://user-images.githubusercontent.com/91185844/166683775-085f7310-2dec-4bc2-84b6-f5a61f96be70.png)

**Comment by Artem-Babich** [comment] 2022-05-05 09:54
I tried to reproduce this issue but failed. Could you share the CSS styles of all the elements located in the form-field_control div and the styles of the div itself?

**Comment by Vooha-QualiTlabs** [comment] 2022-05-06 06:31
@Artem-Babich  Please check this doc, if you need more info let me know:
https://docs.google.com/document/d/12-Tj7q6SHVOjdWz_iBdDJf_TCCcSdu5TE4b0RH3j32A/

**Comment by Artem-Babich** [comment] 2022-10-04 11:33
We still cannot reproduce this issue locally. To further research this issue, we need a simple runnable project that illustrates it. We are currently closing this ticket. You can try updating to the latest version or use the workaround with a timeout.

**Closed by Artem-Babich** 2022-10-04 11:33 UTC
Labels: TYPE: bug, FREQUENCY: level 1
