### ISSUE TITLE
Test from external module.

### ISSUE THREAD

**Issue by Lupiano** [DevExpress/testcafe#2833] opened 2018-09-07 15:27 UTC
### Are you requesting a feature or reporting a bug?
Reporting a bug and requesting a feature.

### What is the current behavior?
We have the following configuration of a file:

fixture`Example Fixture`
	.page('example.com')
	.requestHooks(logger)
	.before(async ctx => {
		//something here. 
	})
	.after(async ctx => {
		//something here. 
	})
	.beforeEach(async t => {
		//something here. 
	})
	.afterEach(async t => {
		//something here. 		
	});

loadTests('Test 1', async t => {
//execution of test.
});

This loadTests function is taken from another module and it executes a test according to some other verifications. The thing here is that TestCafé only "reads" loadTests function if I add one test('name', async t => { //something }); directly inside the fixture file, if not I receive the message "ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive".

### What is the expected behavior?
It should go through all the code without having to define one test directly from the fixture. Is this possible?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment] 2018-09-10 09:51
Hi @Lupiano! It's a duplicate of https://github.com/DevExpress/testcafe/issues/2074, so I close the issue. As a workaround, you can a comment like this:
```js
/*
fixture
test
*/
``` 
to your files.

**Closed** 2018-09-10 12:44 UTC
