### ISSUE TITLE
Same tests look different ones on different executions when using Test Result Analyzer in Jenkins

### ISSUE THREAD

**Issue by perefm** [DevExpress/testcafe#3568] opened 2019-03-14 18:43 UTC
Hi!
I am launching some tests in Jenkins and I use Test Result Analyzer for comparing results across executions.
I have seen that, due to the output format in the XML reporter, each execution is treated as a different test because of the screenshots path.
Due to that, it makes almost impossible to compare results.
It would be great if you could disable the "screenshot" message from the XML reporter with a command or something like this.

### What is your Test Scenario?
testcafe@1.1.0

### What alternatives have you considered?
I have a workaround, wich is removing in the screenshot pattern the Date and Time, but that's an ugly workaround, because then I loose traceability about when the screenshot was made.

![image](https://user-images.githubusercontent.com/4341888/54382959-557d7b80-4691-11e9-874a-7cddbb62e54f.png)

**Comment by LavrovArtem** [comment] 2019-03-15 09:29
Thank you for the report. We are aware of this behavior and working on it. It is a duplicate of DevExpress/testcafe-reporter-xunit#2.

**Closed by LavrovArtem** 2019-03-15 09:29 UTC
Labels: STATE: Need response
