### ISSUE TITLE
TeamCity: ERROR The Chrome 73.0.3683 / Linux 0.0.0 browser disconnected

### ISSUE THREAD

**Issue by apoluian** [DevExpress/testcafe#3759] opened 2019-04-29 18:35 UTC
### What is your Test Scenario?
I'm running TestCafe tests in TeamCity, no concurrency/no quarantine mode. 
Few tests are running one by one. 

The issue was not reproduced locally.  
Some other tests are running along with Test Cafe, but the load is too small to cause resource draining or application issues.

### What is the Current behavior?
Tests started randomly fail last week with "ERROR The Chrome 73.0.3683 / Linux 0.0.0 browser disconnected"

No tests hanging, no browser sessions hanging. Sometimes run fails even before the first test. TeamCity agents restart fixes problem for a few runs. 
 
### What is the Expected behavior?
The browser should be opened for each test.
 
### Your Environment details:
 
* testcafe version:   1.1.0               
* node.js version: v8.14.0                 
* testcafe chrome --no-sandbox --reporter teamcity --screenshots ./screenshots --screenshots-on-fails --video ./videos -e 
* browser name and version: Chrome 73.0.3683 
* platform and version:          Linux
* other:                                   Runnin in TeamCity

Please advise on ways to troubleshoot it or minimize occurrences.

**Comment by AlexKamaev** [comment] 2019-04-30 09:21
We already had some reports about issues with Chrome and we are working on it (see https://github.com/DevExpress/testcafe/issues/3671). Since it's very difficult to reproduce and debug this issue I cannot give you any estimate on when it will be fixed. However, of course, we hope to provide the fix in the near future. I'll close this issue, follow our progress in https://github.com/DevExpress/testcafe/issues/3671
In the meantime, try updating your Chrome version and check how it works.

**Closed by AlexKamaev** 2019-04-30 09:21 UTC
Labels: STATE: Need response

**Comment by apoluian** [comment] 2019-04-30 18:44
@AlexKamaev we changed our run to "chrome:headless --no-sandbox" and updated agents configuration. It's more stable now. Hope it helps.

**Comment by AlexSkorkin** [comment] 2019-05-01 11:00
@apoluian, thank you for the update. We will take it into account when examining this behavior.
