### ISSUE TITLE
Delaying mocked responses

### ISSUE THREAD

**Issue by erykpiast** [DevExpress/testcafe#2425] opened 2018-05-17 07:04 UTC
### Are you requesting a feature or reporting a bug?

I'm requesting a feature.

### What is the current behavior?

There is no method to delay mocked response for particular request.

### What is the expected behavior?

It is possible to delay mocked response of given time, possibly different amount for each request.

I'd be useful for testing how the app handles race conditions.

### How would you reproduce the current behavior (if this is a bug)?

--

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: -

Test code:

```js

const mock = RequestMock()
    .onRequestTo(/*...*/)
    .respond((req, res) => {
        res.setBody(JSON.stringify('some fake content'));
        res.setDelay(2000); // something like this would be enough for me
    });

```

### Specify your

* operating system: MacOS 10.13.4
* testcafe version: 0.20.0
* node.js version: 8.9.1

**Comment by bbowes-ae** [comment] 2020-05-05 07:47
I know this is an old issue, but did you try this @erykpiast ?

```
const mock = RequestMock()
    .onRequestTo(/*...*/)
    .respond(async (req, res) => {
        // Delay response for 2 seconds
        await new Promise((r) => setTimeout(r, 2000));

        res.setBody(JSON.stringify('some fake content'));
    });
```

**Comment by Klaster1** [comment] 2020-05-05 07:51
@bbowes-ae what you suggest used not to work as expected due to how TestCafe handled requests. If it works now - that's great.

**Comment by sorin-davidoi** [comment] 2020-09-03 12:26
I think this can be closed as fixed, passing an `async` function to `respond` works.

**Comment by miherlosev** [comment] 2020-09-04 07:47
Guys

```js
const mock = RequestMock()
    .onRequestTo(/*...*/)
    .respond(async (req, res) => {
        // Delay response for 2 seconds
        await new Promise((r) => setTimeout(r, 2000));

        res.setBody(JSON.stringify('some fake content'));
    });
```

This example doesn't delay sending a response. It delays construction of the response mock.
You can check this by running this [example](https://github.com/DevExpress/testcafe/files/5173062/delyed_response.zip). 

We will keep this suggestion in mind when planning the next iteration of our [Roadmap](https://devexpress.github.io/testcafe/roadmap/).

**Comment by haishengwu-okta** [comment] 2021-03-26 17:39
`.respond(responseMockFn)`
The `responseMockFn` can be a async function than ultimate resolve with `res`. 
Here is what I found from the `testcafe-hammerhead` `request-pipeline/request-hooks/response-mock.ts`
```
else if (typeof this.body === 'function') {
    response.setBody = value => {
        response._body = value;
    };

    response = Object.assign(response, await this.body(this.requestOptions, response));

    delete response.setBody;
}
```

Therefore we could delay the response like

```
  .respond((req, res) => {
    return new Promise((resolve) => setTimeout(function() {
      res.setBody(...);
      resolve(res);
    }, 5000));
  });

```

**Comment by wentwrong** [comment] 2021-03-30 09:02
@haishengwu-okta Thank you for sharing the workaround. I can confirm that the following code works too:
```js
const mock = RequestMock()
    .onRequestTo(/request/)
    .respond(async (req, res) => {
        await new Promise((r) => setTimeout(r, 10000));
 
        res.setBody('some fake content');
    });
```
I slightly modified @miherlosev's example and managed to actually delay a response using the workaround above: https://github.com/wentwrong/mocked-delayed-response

**Comment by AndreyBelym** [comment] 2021-06-07 13:43
For now, the recommended way is using an `async` response function and some Promise-based function like [delay](https://www.npmjs.com/package/delay) or [timers.promises.setTimeout](https://nodejs.org/api/timers.html#timers_timerspromises_settimeout_delay_value_options) to delay a response. Check @wentwrong's example: https://github.com/DevExpress/testcafe-examples/tree/master/examples/delay-mocked-response

**Closed by AndreyBelym** 2021-06-07 13:43 UTC
Labels: AREA: server, HAS WORKAROUND, TYPE: bug
