### ISSUE TITLE
testcafe 1.17.0 failed to open new window on multiple scenarios

### ISSUE THREAD

**Issue by mypchas6fans** [DevExpress/testcafe#6680] opened 2021-11-09 09:10 UTC
### What is your Scenario?

Click on certain web link to open a new tab/window

### What is the Current behavior?

New window opened and closed immediately.
testcafe 1.16.1 works fine.
I'm trying to find more samples and you may try any popup as you wish.

### What is the Expected behavior?

New window should be opened and continue execution

### What is your public website URL? (or attach your complete example)

www.jd.com

### What is your TestCafe test code?

import { Selector } from 'testcafe';

fixture('test')
    .page('https://www.jd.com')

test
    ('tab', async t => {
    await t.click(Selector('div.slider_list'));
    await t.debug();
});

### Steps to Reproduce

1. open a website;
2. click a link to open new tab/window
3. see if new window opens and persists.

### TestCafe version

1.17.0

### Node.js version

14.17.3 windows10; 16.13.0 ubuntu 20.04

### Command-line arguments

testcafe chrome -e test.js; testcafe firefox -e test.js

### Browser name(s) and version(s)

chrome 95 ubuntu 20.04; chrome 95 windows 10; firefox 94.0.1 windows 10

### Platform(s) and version(s)

windows 10; ubuntu 20.04

**Comment by mypchas6fans** [comment] 2021-11-09 09:14
Another example from ikea.cn:

`import { Selector } from 'testcafe';

fixture('test')
    .page('https://www.ikea.cn/cn/en/cat/kitchen-taps-sinks-24261/')

test
    ('tab', async t => {
    await t.click(Selector('div.withprice-item-img-wrapper').nth(0));
    await t.debug();
});`

**Comment by mypchas6fans** [comment] 2021-11-09 09:30
Another example from ads.google.com. I believe this would be a general issue which deserves more attention.

import { Selector } from 'testcafe';

fixture('test')
    .page('https://ads.google.com/intl/en_zz/home/')

test
    ('tab', async t => {
    await t.click(Selector('a.gt-header-butterbar-link'));
    await t.debug();
});

**Comment by AlexKamaev** [comment] 2021-11-10 07:22
I managed to reproduce the issue only with the third example (with google). Anyway, I confirm that the issue exists. We'll research it.

**Comment by maldzi** [comment] 2021-11-18 09:34
I am getting the same, wait for fix. Quite urgent for me.

**Comment by apolonskiy** [comment] 2021-11-18 09:36
Same on my side, waiting for new version. Thanks for looking into it!

**Comment by AlexKamaev** [comment] 2021-11-18 09:42
@mypchas6fans @maldzi @apolonskiy
Please try to check your usage scenarios with the [https://www.npmjs.com/package/testcafe/v/1.17.2-alpha.1](https://www.npmjs.com/package/testcafe/v/1.17.2-alpha.1) version.

**Comment by maldzi** [comment] 2021-11-18 09:53
Thanks for a hint but it didn’t work for me.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by AlexKamaev** [comment] 2021-11-18 10:09
@maldzi
I apologize for the mistake. The 1.17.2-alpha.1 does not contain the fix. Currently, I'm working on the alpha.2 version, which will contain it.

**Comment by AlexKamaev** [comment] 2021-11-18 11:52
Please try to check https://www.npmjs.com/package/testcafe/v/1.17.2-alpha.2

**Comment by apolonskiy** [comment] 2021-11-18 12:01
@AlexKamaev  works for my case.

**Comment by mypchas6fans** [comment] 2021-11-19 02:23
work for my case #2. Thanks.

**Comment by maldzi** [comment] 2021-11-19 06:42
Works for me as well, thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by AlexKamaev** [comment] 2021-11-19 08:40
Thank you for your feedback. I'm happy to hear that the problem is solved. The fix will be included in the next official TestCafe release.

**Closed by AlexKamaev** 2021-11-19 08:40 UTC
Labels: TYPE: bug, FREQUENCY: level 2, SYSTEM: window management

**Comment by jbradenclickfunnels** [comment] 2021-11-29 22:09
Just updated to 1.17.1 in an attempt to solve another issue we're having with TC. Just wanted to drop a line saying 1.17.2-alpha.2 also fixed the regression of our windows being closed as well. Hoping for a release of 1.17.2 soon.
