### ISSUE TITLE
Logging in to Gmail results in a JS error, halts rest of the test

### ISSUE THREAD

**Issue by di5ko** [DevExpress/testcafe#4857] opened 2020-03-11 13:55 UTC
As part of a 'forgot password functionality' test, I want to login go Gmail and fetch the latest e-mail. The Google/Gmail login interface renders a JS error with Testcafe.

### What is your Test Scenario?
1. Navigate to mail.google.com
2. Fill in email field
3. Click next button
4. Attempt to fill in password field (and login)

### What is the Current behavior?
Step 3 renders a JS error, and step 4 will not work (the `.typeText` function will not do anything to insert text in the password field).

```
$ npx testcafe firefox gmail.test.js 
 Running tests in:
 - Firefox 73.0 / Linux 0.0

 Gmail login test
 ✖ Trigger JS error when logging in to Gmail

   1) A JavaScript error occurred on

   "https://accounts.google.com/signin/v2/sl/pwd?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1<mpl=default<mplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin&cid=1&navigationDirection=forward".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      ResizeObserver loop completed with undelivered notifications.:
          No stack trace available
```

### What is the Expected behavior?
Being able to continue to populate the password field with `.typeText`.

### How would you reproduce the current behavior?

Test code: 

```js
import { Selector } from "testcafe";

// Constants
const gmailEmailInput       = Selector("#identifierId");
const gmailNextButton       = Selector(".CwaK9");
const gmailPasswordInput    = Selector("input[type='password']");

fixture("Gmail login test");

test("Trigger JS error when logging in to Gmail", async testController => {

    await testController
        .navigateTo("https://mail.google.com")
        .typeText(gmailEmailInput, "someuser@gmail.com")
        .click(gmailNextButton) // triggers JS error
        .typeText(gmailPasswordInput, "password") // does not work

});
```

### Environment details
 
* testcafe version:                  1.8.2
* node.js version:                   v12.16.1
* command-line arguments:  `testcafe firefox gmail.test.js`
* browser name and version:  Firefox 73.0
* platform and version:           Linux Ubuntu 18.04.4 LTS

**Comment by miherlosev** [comment] 2020-03-12 09:22
Hi @di5ko 

At present, the 'login via Google' functionality is not supported. It will be available after the [Add the capability to perform testing in multiple browser windows](https://github.com/DevExpress/testcafe/issues/912) feature is implemented. Track the #912 issue to be notified about our progress.

**Comment by miherlosev** [comment] 2020-03-12 11:45
I re-test the scenario and confirm that the problem with 'ResizeObserver' is reproduced with Firefox 73.0.1.

**Comment by AndreyBelym** [comment] 2020-03-12 16:27
Can be reproduced with https://mdn.github.io/dom-examples/resize-observer/resize-observer-text.html

**Comment by wentwrong** [comment] 2020-03-13 15:21
As far as I understand, this error occurs when `ResizeObserver` cannot deliver all observations within a single animation frame. A person who claims to be the author of the `ResizeObserver` specification assures that it can be safely ignored: [ResizeObserver loop limit exceeded](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded#comment86691361_49384120)

Chrome and Firefox even doesn't display it by default. You can only catch it when you set up an explicit `onerror` handler:

```js
window.onerror = e => console.log(e);
```

Actually, you can see that this error can be reproduced on the Google Sign In page without TestCafe. I've added an `onerror` handler to the page and got `ResizeObserver loop completed with undelivered notifications.` in Firefox and `ResizeObserver loop limit exceeded` in Chrome.

As a workaround you can specify the `--skip-js-errors` flag when starting TestCafe. It's not a best approach since you will suppress all Javascript errors on a tested page.

A more precise way is adding a global window error handler explicitly in your tests via using [client scripts](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/inject-scripts-into-tested-pages.html):

```js
import { Selector, t } from 'testcafe';

// Constants
const gmailEmailInput       = Selector("#identifierId");
const gmailNextButton       = Selector(".CwaK9");
const gmailPasswordInput    = Selector("input[type='password']");

const explicitErrorHandler = () => {
    window.addEventListener('error', e => {
        if(e.message === 'ResizeObserver loop completed with undelivered notifications.' || 
            e.message === 'ResizeObserver loop limit exceeded') {
            e.stopImmediatePropagation();
        }
    })
}

fixture("Gmail login test")
    .clientScripts({ content: `(${explicitErrorHandler.toString()})()` });

test("Not trigger JS error when logging in to Gmail", async testController => {
    await testController
        .navigateTo("https://mail.google.com")
        .typeText(gmailEmailInput, "someuser@gmail.com")
        .click(gmailNextButton)
        .typeText(gmailPasswordInput, "password")
});
```

**Comment by di5ko** [comment] 2020-03-17 09:56
Many thanks for diving into this and the extensive reply. I created the bug report because I wanted to prevent having to run my tests with `--skip-js-errors`. I will try to use the client script approach.

**Comment by miherlosev** [comment] 2021-02-10 08:01
This issue does not relate to TestCafe, so I will close it. You can see a detailed explanation at [https://github.com/DevExpress/testcafe/issues/4857#issuecomment-598775956](https://github.com/DevExpress/testcafe/issues/4857#issuecomment-598775956).

**Closed by miherlosev** 2021-02-10 08:01 UTC
Labels: AREA: client, FREQUENCY: level 1, SYSTEM: driver, TYPE: bug

**Comment by DRiewaldt** [comment] 2022-01-06 17:36
I'm getting this as well, however it only started when i added this line to my config file: "browsers": ["chrome --window-size=1284,722"]

Removing this fixes it. But, I need this so I don't need to have the line of code in every test. Any idea's? I don't have a way to share or duplicate our site.

But it seems related to resizing of the window using testcafe's resize option.
