### ISSUE TITLE
 Some use of optional chaining triggers an hammerhead error - part II

### ISSUE THREAD

**Issue by JSteunou** [DevExpress/testcafe#7424] opened 2022-12-16 14:55 UTC
### What is your Scenario?

testing an app that can contains optional chaining of this sort

```js
const ghost = undefined

function getValue(key) {
  return ghost?.prop[key] ?? key
}

const test = getValue('café')
```

Notice the access to a property of property though `[key]`. This is important for what is upcoming.

### What is the Current behavior?

The test cannot go through and we can see this error in devtool

```
Uncaught Error: Cannot read property 'café' of undefined
    at t._error (hammerhead.js:13:10727)
    at t._propertyGetter (hammerhead.js:13:11470)
    at getValue (index.js:5:11)
    at HTMLButtonElement.toggle (index.js:10:16)
    at HTMLButtonElement.dispatchEvent (hammerhead.js:14:8675)
    at e._raiseDispatchEvent (hammerhead.js:14:24162)
    at e._dispatchMouseEvent (hammerhead.js:14:22545)
    at e._dispatchMouseRelatedEvents (hammerhead.js:14:21274)
    at a (hammerhead.js:14:15978)
    at e._simulateEvent (hammerhead.js:14:16413)
```

This is due to testcafe code transformation which change code from

```js
  return ghost?.prop[key] ?? key
```

to

```js
  return  __get$(ghost?.prop, key)  ?? key
```

plus having this `__get$` function not checking if there is an optional chaining on the chain of objects but throwing immediately if we try to access a property from `undefined`

see hammerhead.js:20897

```js
	    PropertyAccessorsInstrumentation._propertyGetter = function (owner, propName, optional) {
	        if (optional === void 0) { optional = false; }
	        if (isNullOrUndefined(owner) && !optional)
	            PropertyAccessorsInstrumentation._error("Cannot read property '" + propName + "' of " + inaccessibleTypeToStr(owner));
	        if (typeof propName === 'string' && shouldInstrumentProperty(propName)) {
	            if (optional && isNullOrUndefined(owner))
	                return void 0;
	            else if (!WindowSandbox.isProxyObject(owner) && PropertyAccessorsInstrumentation._ACCESSORS[propName].condition(owner))
	                return PropertyAccessorsInstrumentation._ACCESSORS[propName].get(owner);
	        }
	        if (optional && isNullOrUndefined(owner))
	            return void 0;
	        return owner[propName];
	    };
```

The `optional` information is lost on consecutive access. In our case it is `false` and an error is thrown, whereas it should return `undefined`

### What is the Expected behavior?

All should be fine

### What is your public website URL? (or attach your complete example)

https://vanilla-testcafe-issue-optional-chaining-getter.vercel.app/

### What is your TestCafe test code?

```js
import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`https://vanilla-testcafe-issue-optional-chaining-getter.vercel.app/`

    test('My test', async t => {
        // Test code
        await t
            .expect(Selector('h1').textContent).eql('Hello!')
            .wait(10000)
            // Next click will generate the JS error
            .click(Selector('#action'))
    });
```

### Your complete configuration file

none

### Your complete test report

```
 Running tests in:
 - Chrome 108.0.0.0 / Linux 0.0

 Getting Started
 ✖ My test

   1) A JavaScript error occurred on "https://vanilla-testcafe-issue-optional-chaining-getter.vercel.app/".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      Error: Cannot read property 'café' of undefined
          at t._error (http://192.168.1.23:39013/hammerhead.js:13:10727)
          at t._propertyGetter (http://192.168.1.23:39013/hammerhead.js:13:11470)
          at getValue (https://vanilla-testcafe-issue-optional-chaining-getter.vercel.app/index.js:5:11)
          at HTMLButtonElement.toggle (https://vanilla-testcafe-issue-optional-chaining-getter.vercel.app/index.js:10:16)
          at HTMLButtonElement.dispatchEvent (http://192.168.1.23:39013/hammerhead.js:14:8675)
          at e._raiseDispatchEvent (http://192.168.1.23:39013/hammerhead.js:14:24162)
          at e._dispatchMouseEvent (http://192.168.1.23:39013/hammerhead.js:14:22545)
          at e._dispatchMouseRelatedEvents (http://192.168.1.23:39013/hammerhead.js:14:21274)
          at a (http://192.168.1.23:39013/hammerhead.js:14:15978)
          at e._simulateEvent (http://192.168.1.23:39013/hammerhead.js:14:16413)

      Browser: Chrome 108.0.0.0 / Linux 0.0

          7 |        // Test code
          8 |        await t
          9 |            .expect(Selector('h1').textContent).eql('Hello!')
         10 |            .wait(10000)
         11 |            // Next click will generate the JS error
       > 12 |            .click(Selector('#action'))
         13 |    });
         14 |

         at <anonymous> (/home/jsteunou/Git/testcafe/src/index.js:12:14)
         at asyncGeneratorStep (/home/jsteunou/Git/testcafe/src/index.js:1:37)
         at _next (/home/jsteunou/Git/testcafe/src/index.js:1:37)
         at <anonymous> (/home/jsteunou/Git/testcafe/src/index.js:1:37)
         at <anonymous> (/home/jsteunou/Git/testcafe/src/index.js:1:37)
         at <anonymous> (/home/jsteunou/Git/testcafe/src/index.js:13:6)



 1/1 failed (11s)
```

### Steps to Reproduce

1. write code with call on property of property of object that could be undefined with optional chaining on 1st access.
2. write test
3. launch test

### TestCafe version

2.1.0

### Node.js version

16.14.0

### Command-line arguments

yarn testcafe chromium testWithJSError.ts

### Browser name(s) and version(s)

Chromium 108

### Platform(s) and version(s)

Linux Ubuntu 22.04.1

### Other

related to #7387

**Comment by miherlosev** [comment] 2022-12-19 08:23
Hi @JSteunou,

It's a duplicate of #7387. These issues are related to the processing option operator in different cases. They will be investigated and fixed together.

**Closed by miherlosev** 2022-12-19 08:23 UTC
Labels: TYPE: bug, STATE: Need response

**Comment by JSteunou** [comment] 2022-12-19 08:30
I would prefer to open a separate issue because the root cause and the use case is not exactly the same. Some project manager do not like when adding new information on an existing ticket. But if it works for you like this it is ok.
