### ISSUE TITLE
Testcafe process does not close on successful runs in certain scenarios

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#2132] opened 2018-02-15 16:42 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When some of my tests run, testcafe's process does not exit after calling .`close()`, even though it does for others.

### What is the expected behavior?
The process should exit after calling `.close()`

### How would you reproduce the current behavior (if this is a bug)?
I can't share my website that I am testing, but here is my code to run the tests

```js

createTestCafe('localhost', 1337).then(tc => {
    testcafe = tc;
    const runner = testcafe.createRunner();

    runner
      .src(getTests(['file1.js'])
      .browsers(['chrome'])

    return runner.run();
  })
  .then(numFailed => {
   console.log('finished with ', numFailed, ' errors');
    testcafe.close(); //normally the process exits about 2 seconds after this. now we need process.exit(0)
    if(numFailed){
      process.exit(1);
    }
  }, err => {
    console.error(err);
    testcafe.close();
    process.exit(1);
  });
```

Here's how my e2e looks in general

```js
fixture('my fixture')
  .page(myUrl)
  .beforeEach(async (t) => {
    await t.useRole(myRole);
  });

test('should be able to do stuff', async (t) => {
  await doThing(t); //combination of clicks and expects

  await t
    .expect(someSelector.exists)
    .ok()
    .click(buttonSelector.withText('button'))
     //process exits successfully if i delete everything after this line
    .click(confirmButtonSelector.withText('confirm button'))
    .expect(successSelector.exists)
    .ok();
});

```

### Specify your
* operating system: OS X High Sierra
* testcafe version: 0.18.16
* node.js version: 9.5.0 (happens on v8 as well)

**Comment by AndreyBelym** [comment] 2018-02-16 14:31
Hi @bdwain! 

Does the browser window close when TestCafe process doesn't finish? Have you tried to run other browser besides Chrome?

Also, could you please enable debug printting by runnning
```
DEBUG=testcafe:* node runner.js
```
and send me the output?

**Comment by bdwain** [comment] 2018-02-18 18:29
Hi @AndreyBelym .

The browser window does close when it finishes. And the problem occurs in firefox and safari and headless chrome also.

The debug output is really long, but I looked through and it looks very similar to a case where things work correctly. The final entry is this

> Sat, 17 Feb 2018 19:37:01 GMT testcafe:test-run:Chrome 64.0.3282 / Mac OS X 10.13.3:command 
    {
      "type": "test-done"
    }

>Sat, 17 Feb 2018 19:37:01 GMT testcafe:test-run:Chrome 64.0.3282 / Mac OS X 10.13.3:driver-message 
    {
      "cmd": "ready",
      "status": {
        "id": "12479.900000005728",
        "isCommandResult": true,
        "executionError": null,
        "pageError": null,
        "resent": false,
        "result": null,
        "consoleMessages": {
          "log": [],
          "info": [],
          "warn": [],
          "error": []
        }
      },
      "disableResending": true,
      "sessionId": "HyY8EWUwM"
    }

and that's the same output as the successful runs have

> Sat, 17 Feb 2018 05:34:24 GMT testcafe:test-run:Chrome 64.0.3282 / Mac OS X 10.13.3:command 
    {
      "type": "test-done"
    }

> Sat, 17 Feb 2018 05:34:24 GMT testcafe:test-run:Chrome 64.0.3282 / Mac OS X 10.13.3:driver-message 
    {
      "cmd": "ready",
      "status": {
        "id": "16440.300000016578",
        "isCommandResult": true,
        "executionError": null,
        "pageError": null,
        "resent": false,
        "result": null,
        "consoleMessages": {
          "log": [],
          "info": [],
          "warn": [],
          "error": []
        }
      },
      "disableResending": true,
      "sessionId": "BJP0CESvG"
    }

I also noticed that all of that output happens before testcafe outputs to the console that the test was successful and the overall test results (1 passed (12s))

**Comment by miherlosev** [comment] 2018-05-11 12:26
Hi @bdwain 

This issue looks like a duplicate of https://github.com/DevExpress/testcafe/issues/2226.
Try the latest `TestCafe` alpha version (`testcafe@0.20.0-alpha.3`) let us know about your results.

**Comment by miherlosev** [comment] 2018-05-21 08:32
I will close the issue because no activity has been encountered for a long time.
Feel free to reopen the issue if the problem persists.

**Closed by miherlosev** 2018-05-21 08:32 UTC
Labels: To be reproduced

**Comment by keerthana07** [comment] 2018-07-05 17:16
Hello, is this issue resolved?

testcafe.close() doesn't seem to be executing in my code. I am using the exact code as here : http://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#filter

**Comment by keerthana07** [comment] 2018-07-05 20:15
It seems like the second then loop is an unreachable code

**Comment by AndreyBelym** [comment] 2018-07-06 06:11
Hi @keerthana07, I think you've posted a wrong link, could you please provide me your runner code and its console output?

**Comment by sherlinecalista** [comment] 2020-09-10 06:07
Hi, even I am facing the same issue. The browser window doesn't close after  both successful and unsuccessful execution of the test cases. testcafe.close() is not working.

**Comment by sherlinecalista** [comment] 2020-09-10 06:08
I am using the latest version of testcafe

**Comment by AndreyBelym** [comment] 2020-09-10 08:38
Could you please submit a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) and share details regarding your environment and your runner code in it?
