### ISSUE TITLE
Update stack-chain to 2.0.0

### ISSUE THREAD

**Issue by rquellh** [DevExpress/testcafe#2107] opened 2018-02-07 17:41 UTC
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

TestCafe uses an earlier version of stack-chain. When TestCafe is integrated with the latest version of CucumberJS (4.0.0) there is an error "Conflicting version of stack-chain found."

### What is the expected behavior?

Updated stack-chain to 2.0.0. I manually updated TestCafe to stack-chain version 2.0.0 and TestCafe seems to function normally, but there might be some outlying conditions that would cause errors. 

### How would you reproduce the current behavior (if this is a bug)?

See my [repo](https://github.com/rquellh/testcafe-cucumber) and just install; don't do the extra steps.

#### Provide the test code and the tested page URL (if applicable)

See my [repo](https://github.com/rquellh/testcafe-cucumber) and just install; don't do the extra steps.

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.6
* node.js version: 8.9.3

**Comment by AlexanderMoskovkin** [comment] 2018-02-08 12:25
Hi @rquellh,

Thanks for pointing this out, we'll check it soon!

**Comment by AlexanderMoskovkin** [comment] 2018-02-09 15:46
The issue is fixed in #2113. Will be included to the next release. I guess we can publish a `dev` build the next week

**Closed by AlexanderMoskovkin** 2018-02-09 15:46 UTC
Labels: TYPE: enhancement
