### ISSUE TITLE
Selector not finding DOM element

### ISSUE THREAD

**Issue by eugengaspar** [DevExpress/testcafe#3000] opened 2018-10-19 12:18 UTC
I'm doing a simple test here, but I've seen a lot of people stumbled into this problem, but unfortunately I wasn't able to find a solution, so, therefore, I'm asking for your opinion.

Now, I have this string object, inside a link:
`<div class="price">12,45&nbsp;€</div>`

I created this small test, to check the string value:
```
import { t, Selector } from 'testcafe';

fixture `OfferPage`.page `https://www.verivox.de/applications/broadband/#/offer?i=eyJmaWx0ZXIiOltudWxsLDE2MDAwLDEsbnVsbCwiMDIyMSIsMSwxLDEsbnVsbCwxLDEsbnVsbCwtMSxudWxsLG51bGwsInByaWNlLWFzYyIsMixudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsNl0sImRpYWxvZyI6W251bGxdLCJvZmZlckNyaXRlcmlhIjpbIjYxMzQ0NyIsIjE4MjkyIixudWxsLCIyNCIsMywyLCI1MDAwMCIsIjEwMDAwIixudWxsLG51bGwsMSxudWxsLG51bGwsbnVsbCwiMiIsMSxudWxsLCIwMjIxIixudWxsLG51bGwsbnVsbCxudWxsLG51bGwsMSw2LG51bGwsbnVsbCxudWxsXX0%3D`;
    test('1', async () => {
        const string = Selector('div.price');
        await t.expect(string.innerText).eql('12,45 €');
});
```
The error I get in terminal is this one:
`AssertionError: expected '12,45 €' to deeply equal '12,45 €'`

I tried also other options, like the ones below, but with no luck unfortunatelly:
```
let price = Selector('div').withAttribute('class', 'price');
const result = price.parent('div.centered-content effective-price-wrapper');
console.log(result);
await t.expect(result.innerText).eql('12,45 €');
```
err: 
`Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.`

another try:
```
const string = await Selector('div.price')();
let pret = await Selector(string).innerText;
const rgx = /&nbsp;/gi;
await t.expect(pret.replace(rgx, '')).eql('12,45 €'.replace(rgx, ''));
```
err
`AssertionError: expected '12,45 €' to deeply equal '12,45 €'`

I'm running put of ideas here :)

**Comment by LavrovArtem** [comment] 2018-10-19 14:12
It is a duplicate of [the issue on StackOverflow](https://stackoverflow.com/questions/52877344/assertion-always-return-err-expected-a-to-deeply-equal-a). I've already answered there.

**Closed by LavrovArtem** 2018-10-19 14:12 UTC
