### ISSUE TITLE
Screenshots with default docker container are black

### ISSUE THREAD

**Issue by Thomblin** [DevExpress/testcafe#1882] opened 2017-10-17 06:50 UTC
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

I use the default testcafe/testcafe container with entrypoint `["/opt/testcafe/docker/testcafe-docker.sh", "-c", "2", "-S", "-s", "/testcafe/screenshots", "firefox", "/testcafe/tests"]`

However all screenshots taken by chromium or firefox are black

### What is the expected behavior?

I would expect to see a browser snapshot of the current screen

### How would you reproduce the current behavior (if this is a bug)?

```
testcafe:
    image: testcafe/testcafe
    container_name: serp_testcafe
    environment:
      - NODE_PATH=/opt/testcafe/node_modules:/opt
    volumes:
      - ./src/testcafe:/testcafe
      - ./node_modules/testcafe-react-selectors:/opt/testcafe/node_modules/testcafe-react-selectors
    depends_on:
      - serp
    entrypoint: ["/opt/testcafe/docker/testcafe-docker.sh", "-c", "2", "-S", "-s", "/testcafe/screenshots", "firefox", "/testcafe/tests"]
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: docker container testcafe/testcafe 
* testcafe version: latest
* node.js version: as provided in docker container

**Comment by AndreyBelym** [comment] 2017-10-17 09:11
Hello @Thomblin !

I'm investigating the problem. Looks like screenshots do not work well when concurrency mode is enabled ( `..,"-c", "2",..`). Does it work better when concurrency is disabled?

**Comment by Thomblin** [comment] 2017-10-17 11:55
Hi @AndreyBelym 

Thank you for that quick response.

Removing the -c2 helped a bit. The screenshot does show the browser (firefox and chromium) now, however the screen is white and the browser appears to be still loading the page (the test was successful).
This is my test:

```
fixture`Getting Started`
  .page`http://serp.local:3000/`;

test("My first test", async t => {
  await t
    .expect(Selector("title").innerText)
    .eql("React App", "Title was not found")
    .takeScreenshot("test1.png");
});
```

Additionally, -S does not create a screenshot, when the test failed ... Maybe something else is wrong with my (default) docker configuration?

**Comment by AndreyBelym** [comment] 2018-06-18 08:51
This issue must be fixed by https://github.com/DevExpress/testcafe/pull/2492. I'll notify you when a build with the fix will be published on NPM. Also we have added a section in the docs about configuring Docker for testing heavy websites: [Using TestCafe Docker Image/Testing Heavy Websites]( https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md#testing-heavy-websites). Feel free to try the fixed build and reopen the issue if the problem isn't solved in your environment.

**Closed by AndreyBelym** 2018-06-18 08:51 UTC
Labels: AREA: docker, SYSTEM: browser natives, TYPE: bug
