### ISSUE TITLE
Unable to Run tests Headless (using Nightmare)

### ISSUE THREAD

**Issue by TheBeachMaster** [DevExpress/testcafe#2323] opened 2018-04-17 13:47 UTC
### Are you requesting a feature or reporting a bug?
 - Bug

### What is the current behavior?

- Windows 
  - Unable to connect to browser 
![testcafe2](https://user-images.githubusercontent.com/9129843/38873243-fc47edb2-425d-11e8-8e2f-0ffe3f1b1d64.PNG)

- Ubuntu  
  - Error Launching (Electron) App
![testcafe](https://user-images.githubusercontent.com/9129843/38873191-da9df18e-425d-11e8-96d5-1ae716f8a184.PNG)

### What is the expected behavior?
- Ubuntu : based on issues [1133](https://github.com/DevExpress/testcafe/issues/1133),[1493](https://github.com/DevExpress/testcafe/issues/1493), and [4](https://github.com/ryx/testcafe-browser-provider-nightmare/issues/4) and [usage](https://www.npmjs.com/package/testcafe-browser-provider-nightmare#usage), running the following commands  

```bash 
sudo xvfb-run -a --server-args='-ac -screen 0 1024x768x16' npm run test 
```   
should execute tests successfully with xvfb installed on Ubuntu.

 
- Windows : running `npm test` should execute the test command without errros

### How would you reproduce the current behavior (if this is a bug)?

- Run tests against `nightmare` on headless mode , e.g. on a Bitbucket pipelines environment with a default Ubuntu image. 

- Or, run any simple tests against Bash on Windows on Ubuntu with `xvfb` installed.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://bitbucket.org/augke/bitbucketaddon/src/master/

Test code

```js
import { Selector } from 'testcafe'
fixture `Dummy Test`
    .page `https://bitbucket.org/augke/bitbucketaddon/src/master/`

test("Dummy Test Stub", async t => {
    const i = 2;
    const j = 3;
    const res = 5;
    await t
        .expect(res == i + j).ok();
});
```

### Specify your

* operating system: [Windows 10.0.16299.371, Ubuntu 16.04.4 LTS]
* testcafe version: 0.19.2
* node.js version: [Ubuntu : 5.7.1, Windows: 5.8.0]

**Comment by AndreyBelym** [comment] 2018-04-18 14:56
Hi @TheBeachMaster!

I've reproduced your issue with a disconnected browser. Unfortunately, `testcafe-browser-provider-nightmare` is unusable, because conflict between Nightmare and our proxy, `testcafe-hammerhead`. 

So it's a problem in the provider, and I've created an issue in its repository: https://github.com/ryx/testcafe-browser-provider-nightmare/issues/14. 

You can use it to check the progress of resolving this problem.

Also there is another problem with 'Error launching app'. You've got it, because you had installed Linux version of Nightmare on Windows. Windows Subsystem for Linux a.k.a. Bash for Windows can't run Linux binaries of Electron apps such as Nightmare in its current state. You have to force `npm` to install Windows version:
```
export npm_config_platform=win32
npm install testcafe-browser-provider-nightmare
```

Check this thread for details: https://github.com/electron-userland/electron-prebuilt/issues/260#issuecomment-335149362

**Closed by AndreyBelym** 2018-04-18 14:56 UTC

**Comment by AndreyBelym** [comment] 2018-04-19 10:47
Also I've forgot to mention that you can use Firefox and Chrome in [headless mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/testing-in-headless-mode.html)! You even don't need things like `xvfb-run` for it. For Firefox, it's just enough to install it from Ubuntu's repositories (`sudo apt-get firefox`), however for Chrome you have to install some additional dependencies, check [this comment](https://github.com/Googlechrome/puppeteer/issues/290#issuecomment-360542685) for the command that will install them.

**Comment by TheBeachMaster** [comment] 2018-04-19 17:07
Awesome, let me try this
