### ISSUE TITLE
Problem with starting mp4 player

### ISSUE THREAD

**Issue by JakubMaz** [DevExpress/testcafe#8345] opened 2024-11-22 08:54 UTC
### What is your Scenario?

I would like to run a player on the site that downloads mp4

### What is the Current behavior?

Mp 4 downloads, but it takes a long time, much more than without testCafe. 
This has resulted in the fact that it cannot be tested.
Normally the request requires ~100ms. 
![2024-11-22_09h47_52](https://github.com/user-attachments/assets/1f33553c-e09c-48ff-9a25-ceefe1cf65ed)
With testcafe it takes ~25s.
![2024-11-22_09h45_59](https://github.com/user-attachments/assets/2a621186-84dc-45c3-bc4c-1b155f4a173c)

### What is the Expected behavior?

Downloading mp4 through the player takes a normal amount of time

### What is the public URL of the test page? (attach your complete example)

https://www.livereacting.com/tools/mp4-player

### What is your TestCafe test code?

```
import { RequestLogger, Selector, t } from "testcafe";

const loggerMp4 = RequestLogger({ url: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_30MB.mp4', method: 'get' }, {
    logResponseHeaders: true,
    logResponseBody: true,
    logRequestHeaders: true,
    logRequestBody: true,
});

fixture`test player mp4`
    .page('https://www.livereacting.com/tools/mp4-player');

test('load player', async () => {
    await t.addRequestHooks(loggerMp4);
    await t.click(Selector('#play-button'));
    await t.expect(loggerMp4.contains(record => record.response.statusCode === 200)).ok({ timeout: 10_000 });
});
```

### TestCafe version

3.7.0

### Command-line arguments

testcafe chrome tests/test.js --disable-native-automation

### Platform(s) and version(s)

chrome, edge

**Comment by PavelMor25** [comment] 2024-11-28 07:21
Hello @JakubMaz,

I couldn't reproduce the issue based on the scenario you described. The video takes slightly longer to load compared to running without TestCafe, but it's not as delayed as you mentioned.

Without Testcafe:
![image](https://github.com/user-attachments/assets/bdec0378-d401-44c3-af14-30e1d16b4da6)
Testcafe Native Automation mode:
![image](https://github.com/user-attachments/assets/be90dbb0-8e99-4a91-8c01-8afa990527d1)
Testcafe Proxy mode:
![image](https://github.com/user-attachments/assets/ce4a99d0-6abd-4193-867d-dd835a324285)

Could you please clarify if you have tried running it in [Native Automation mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode)? Additionally, could you share your operating system and Node.js version?

**Comment by JakubMaz** [comment] 2024-11-28 15:41
@PavelMor25 I'm runing testcafe with flag --disable-native-automation. On Native Automation mode it works.
My system: Windows 11 Pro 22H2.
My node: 20.18.0

**Comment by Bayheck** [comment] 2024-12-05 10:54
Hello,

Could you please clarify if there is a reason you do not use TestCafe with Native Automation enabled?

Also, we have tried running your example with Native Automation disabled yet we still got expected results.

 

Could the issue be related to your environment?

Please try running your example on a different machine and share your results with us.

**Comment by JakubMaz** [comment] 2024-12-09 12:23
Hey, I checked it on different machines and I still have a longer time when the player is run by testcafe (I created a new repository where testcafe is only one dependency).
Chrome + Win 10
![2024-12-09_13h06_43](https://github.com/user-attachments/assets/2695e492-b47c-4c75-98b2-d1cdcffd3e3e)
Chrome + macOS 14.5
<img width="643" alt="Screenshot 2024-12-09 at 13 11 38" src="https://github.com/user-attachments/assets/a94e4c5a-708c-45e6-800b-e50e931d77c4">

(I'm not using native automtion because I have to prepared my tests for it. For exaple I have to update my loggers because I manually decompress data with the zlib.brotliDecompressSync method. I have a task to change it but it's waiting in backlog)

**Comment by PavelMor25** [comment] 2024-12-16 10:23
Hello @JakubMaz ,

After we conducted a partial investigation, we couldn't reproduce the results you reported. Since the observed difference in loading time is not critical and this issue is not widely reported among users, we cannot prioritize it at this time. Additionally, you can use the native automation mode to resolve this issue.

Therefore, we will close this issue. We appreciate your understanding.

**Closed by PavelMor25** 2024-12-16 10:23 UTC
Labels: TYPE: bug, STATE: Need response
