### ISSUE TITLE
0.23.3 is not exiting after completing the tests

### ISSUE THREAD

**Issue by safm** [DevExpress/testcafe#3295] opened 2019-01-09 20:09 UTC
### What is your Test Scenario?
Running a test and generating a JSON report.
 
### What is the Current behavior?
In version 0.23.3, after running the tests the browser is closing but the CLI is hung. This only happens when "reporter" flag is specified.
 
### What is the Expected behavior?
It should also exit the CLI.
 
Your website URL (or attach your complete example): https://www.macys.com/shop/product/kitchenaid-ksm150ps-artisan-5-qt.-stand-mixer?ID=77589

<details>
<summary>Have a simple test, that is checking an element on the page. Clicking it and navigating to next page and checking if the element loaded.</summary>

 
```js
 //model.js
import { Selector } from 'testcafe';

export default class Pinterest {
  constructor(t) {
    this.t = t;
  }

  static pageSelector() {
    return '.pinterest-share';
  }

  static async create(t) {
    const model = new Pinterest(t);
    await Selector(this.pageSelector(), {
      timeout: duration,
      visibilityCheck: true,
    }).visible;
    await model.createRefs();
    return model;
  }

  async createRefs() {
    this.pinterestIcon = Selector('.pinterest-share');
  }

  async clickPinterestIcon() {
    console.info('Clicking Pinterest social icon. Page ref: Pinterest');

    await this.t
      .click(this.pinterestIcon);
  }

  async verifyPinterestPage() {
    console.info('Verifying Pinterest Page. Page ref: Pinterest');
    const modal = await Selector('div')
      .withAttribute('data-test-id', 'signup');

    await this.t
      .expect(modal.exists).ok();
  }
}


//test.js
import Pinterest from './model';

// eslint-disable-next-line no-undef
fixture('Member')
  .page(`https://www.macys.com/shop/product/kitchenaid-ksm150ps-artisan-5-qt.-stand-mixer?ID=77589`);

// eslint-disable-next-line no-undef
test
  .meta({
    id: `PINTEREST`,
  })('Verify Pinterest', async (t) => {
    const pinterest = await Pinterest.create(t);
    await pinterest.clickPinterestIcon();
    await pinterest.verifyPinterestPage();
  });
```

</details>

### Steps to Reproduce:

1. Make sure you have 0.23.3 installed
3. Execute the following command `node_modules/.bin/testcafe firefox tests/e2e -r json:dist/reports/report.json`
4. You will notice, after running the tests, the report is generated the CLI is hung.
 
### Your Environment details:
 
* testcafe version:  0.23.3                 
* node.js version:  8.12                  
* command-line arguments:  firefox tests/e2e -r json:dist/reports/report.json
* browser name and version: Firefox 64.0
* platform and version:  Mac 10.12
* other:

**Comment by safm** [comment] 2019-01-11 18:42
@AlexKamaev, I created a small repo here https://github.com/safm/test-cafe. I am loading google.com. I can consistently reproduce the issue. Please see the attached screenshot of my terminal

<img width="890" alt="screen shot 2019-01-11 at 10 36 33 am" src="https://user-images.githubusercontent.com/5912465/51053084-81935800-158d-11e9-956f-6a04c63c64ab.png">

**Comment by AlexKamaev** [comment] 2019-01-14 08:42
I reproduced the issue. It seems to be a duplicate of https://github.com/DevExpress/testcafe/issues/3209
That issue is already fixed but is not published. You can try to build the latest version from the repository and check if it works for you

**Closed by AlexKamaev** 2019-01-14 08:42 UTC
