### ISSUE TITLE
(Safari 15) ERROR Cannot establish one or more browser connections.

### ISSUE THREAD

**Issue by TravisBack** [DevExpress/testcafe#6583] opened 2021-10-01 05:42 UTC
### What is your Test Scenario?
This is just a simple Google search.
 
### What is the Current behavior?
Safari opens (sometimes it doesn't) and just sits there. Works in Firefox and Chrome.
 
### What is the Expected behavior?
Safari opens and runs the test
 
### What is your web application and your TestCafe test code?

```js
import { Selector } from 'testcafe';

const searchField = Selector('input[type="text"][name="q"]');

fixture `Google Test`
    .page `https://www.google.com`;

test('My Test', async t => {
    await t
        .typeText(searchField, 'TestCafe')
        .pressKey('enter')
        .wait(5000)

        .click(searchField)
        .pressKey('ctrl+a delete')
        .typeText(searchField, 'travisback.com')
        .pressKey('enter')
        .wait(5000);
});
```
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Chrome Run
 Running tests in:
 - Chrome 94.0.4606.71 / macOS 10.15.7

 Google Test
 ✓ My Test


 1 passed (18s)

Firefox Run
 Running tests in:
 - Firefox 92.0 / macOS 10.15

 Google Test
 ✓ My Test


 1 passed (18s)

Safari Run
ERROR Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:
- safari

Hints:
- Increase the value of the "browserInitTimeout" option if it is too low (currently: 2 minutes for local browsers and 6 minutes for remote browsers). This option determines how long TestCafe waits for browsers to be ready.
- The error can also be caused by network issues or remote device failure. Make sure that your network connection is stable and you can reach the remote device.

Type "testcafe -h" for help.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to Google.com
2. Input a search
3. Run a 2nd search on something else.
 
### Your Environment details:
 
* testcafe version:                   1.16.0
* node.js version:                    14.17.5
* command-line arguments:  testcafe safari google.js
* browser name and version: Safari 15.0 (16612.1.29.41.4, 16612) / Chrome 94.0.4606.71 (Official Build)(x86_64) / Firefox 92.01
* platform and version:          macOS 11.6
* other:

**Comment by Farfurix** [comment] 2021-10-01 07:19
@TravisBack 

Hello,

I reproduced this issue with the following command: `testcafe chrome,firefox,safari test.js`. This issue seems to be a duplicate of https://github.com/DevExpress/testcafe/issues/6546#issuecomment-927640352, so I'll close it. We'll discuss it in the context of this ticket.

**Closed by Farfurix** 2021-10-01 07:19 UTC
Labels: STATE: Need response
