### ISSUE TITLE
t.takeScreenshot is auto-cropping image in Chrome

### ISSUE THREAD

**Issue by byrne-greg** [DevExpress/testcafe#3590] opened 2019-03-20 14:39 UTC
### What is your Test Scenario?
Using `t.takeScreenshot( )` to take screenshots with Chrome
 
### What is the Current behavior?
When I navigate to a URL with TestCafe and try take a screenshot using the Chrome browser, I'm only getting the top-left corner of the page. This happens in both headless and non-headless mode and despite when in non-headless mode, I can see the entire page in the browser.

I can also assert for elements that is beyond the visual area of the screenshot, but aren't displayed in the screenshot.

I have tried `t.maximizeWindow( )` and `t.resizeWindow( )`. Maximising had no effect and resize, when given ridiculous sizes, would output more of the height, but instead of showming more of the right side of the page (the missing part), it instead went off to the left (showing more blankspace)

**This does not happen using Firefox 60**

Example of snapshotting the Google homepage with Chrome
![google_snapshot_20032019](https://user-images.githubusercontent.com/5464272/54691357-01541a80-4b1b-11e9-9168-d2422544ade8.png)

Code:
```
test('Google Snap!', async controller => {
  await controller.navigateTo(`https://www.google.com/`).takeScreenshot();
});
```

Example in chrome browser during test (before screenshot step)
![image](https://user-images.githubusercontent.com/5464272/54691742-aff85b00-4b1b-11e9-9ba2-6de18f53bafb.png)

 
### What is the Expected behavior?
I would expect the screenshot to be similar to the visual area of the browser (not concerned with those out of the visual area, such as scrollable content).
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 test('Google Snap!', async controller => {
  await controller.navigateTo(`https://www.google.com/`).takeScreenshot();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

Example of snapshotting the Google homepage
![google_snapshot_20032019](https://user-images.githubusercontent.com/5464272/54691357-01541a80-4b1b-11e9-9168-d2422544ade8.png)

Example in chrome browser during test (before screenshot step)
![image](https://user-images.githubusercontent.com/5464272/54691742-aff85b00-4b1b-11e9-9ba2-6de18f53bafb.png)
```

```
</details>

### Steps to Reproduce:

1. Execute the test code against the google homepage
2. Note the outputted picture does not match the entire expected visual area of the page
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v9.4.0
* command-line arguments:  `testcafe chrome:headless -s tests/screenshots`
* browser name and version: Chrome 72
* platform and version:          macOS 10.14
* other:                                   Does not occur in Firefox

**Comment by AndreyBelym** [comment] 2019-03-21 07:08
Thank you for your report. It's a duplicate of #3541. We will fix it in the current development sprint.

**Closed by AndreyBelym** 2019-03-21 07:08 UTC
Labels: STATE: Need response
