### ISSUE TITLE
Testcafe load an old version of the page, seems that the cache is not cleaned 

### ISSUE THREAD

**Issue by fabytta** [DevExpress/testcafe#5455] opened 2020-08-25 12:03 UTC
### What is your Test Scenario?
Trying to use the same old test with new attributs newly added by the dev team 
 
### What is the Current behavior?
the new added attribute is not present in the DOM, it seems that testcafe reload an old version of the site
 
![image](https://user-images.githubusercontent.com/4931915/91171916-40ed4180-e6d3-11ea-99d2-6378de5f6b3b.png)

### What is the Expected behavior?
I should find the new attribute since I can find it when I open the site manualy in the normal browser 
 
![image](https://user-images.githubusercontent.com/4931915/91171928-48144f80-e6d3-11ea-9b87-42a0acd52368.png)

### What is your web application and your TestCafe test code?
site not accessible publicly

testcafe version: 1.8.7
node.js version: 12.16.1
command-line arguments: testcafe ie,chrome -e test.js
browser name and version: chrome (no version specified)
platform and version: Windows

Note that this behavior appears with : https://github.com/DevExpress/testcafe/issues/5454

**Comment by AndreyBelym** [comment] 2020-08-26 08:08
Thank you for your report. TestCafe starts each test session with an empty browser profile, so it is quite unlikely that the page cache can be preserved between test sessions. Additionally, you can try the [--disable-page-caching](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--disable-page-caching) option to disable the page cache completely.

Also, you can update your TestCafe version to 1.9.1 to check if the problem can be reproduced with the latest TestCafe version.

It's quite hard to understand what's wrong since your screenshots show different parts of the DOM tree. However, even if we can detect the problem in a screenshot, we won't be able to debug and fix it without a live example. You can send your private details to support@devexpress.com and attach a written confirmation that permits DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by fabytta** [comment] 2020-08-29 11:46
updating TestCafe to version v1.9.1  and using --disable-page-caching didn't help, the weird think is that the issue got resolved by itself the day after, which makes understanding it and fixing it very problematic

**Comment by miherlosev** [comment] 2020-09-01 09:52
Hi @fabytta

I will close this issue since the problem is not reproduced. Feel free to reopen this issue if it occurs again and you can share with us a simple example to reproduce it.

**Closed by miherlosev** 2020-09-01 09:52 UTC
