### ISSUE TITLE
TestCafe cannot click a button in EDGE browser

### ISSUE THREAD

**Issue by AlexNaryzhny** [DevExpress/testcafe#3214] opened 2018-12-12 09:34 UTC
### What is your Test Scenario?
Open url and login to the app
 
### What is the Current behavior?
In Edge browser, not able to click on button on Login page.
Same test working on ie, firefox and chrome.
I'm created simple test code and also recordered same test steps using TestCafe Studio. Chrome, FF, IE working well, but Edge able to type username only. Then the pointer hovers in the upper left corner and slowly moves to the lower right until the timeout ends.
 
### What is the Expected behavior?
Should be able to click button in Edge browser

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

test('New Test', async t => {
await t
        .typeText(Selector('#username-login-type-discovery'), 'test')
        .click(Selector('#button-discovery-next'))
        .typeText(Selector('#password'), 'test')
        .click(Selector('#btnLoginSubmit'))
        .expect(Selector('.ca-query-results-placeholder').exists).ok()
});
</details>

<details>
<summary>Button code:</summary>

<"input type="submit" value="Next" id="button-discovery-next" name="button-discovery-next" class="button button-disabled" tabindex="2">
</details>

<details>
<summary>Your complete test report:</summary>

Uncaught object "[object Object]" was thrown. Throw Error instead.

Browser: Edge 18.17763.0 / Windows 10.0.0
</details>

<details>
<summary>Your screenshot:</summary>
<a href="https://i.imgur.com/7PJjVs9.png">screenshot</a>
</details>

 
### Your Environment details:
 
* testcafe version: 0.22.0                  
* node.js version: v8.12.0                   
* command-line arguments:  node testrunner.js 
* browser name and version: Edge 18.17763.0
* platform and version:  Windows 10

**Comment by AlexNaryzhny** [comment] 2018-12-13 10:19
Looks like the same code work in Edge 17

**Comment by willscripted** [comment] 2018-12-13 14:50
We're seeing a similar [?the same?] issue on Edge 18 / Windows 10, too. Looks like testcafe is timing out waiting for an element to appear on the page.

**Comment by miherlosev** [comment] 2018-12-14 12:34
Duplicate of the https://github.com/DevExpress/testcafe/issues/3189

**Closed by miherlosev** 2018-12-14 12:34 UTC
