### ISSUE TITLE
screenshotting webgl in firefox is broken

### ISSUE THREAD

**Issue by mixtur** [DevExpress/testcafe#5533] opened 2020-09-11 14:54 UTC
### What is your Test Scenario?
We are doing tests with screenshot diffing in a complex webgl application.
 
### What is the Current behavior?
In our case screenshots in Firefox (version 80.0.1) on win 10 have white rectangles where webgl canvas should be.
But everything is fine on Chrome (version 85.0.4138.102) also on Windows 10.
 
### What is the Expected behavior?
Actual contents of canvas on screenshots
 
### What is your web application and your TestCafe test code?

I can't share our code. But I believe any practical webgl application will allow to somewhat reproduce the issue.

You can use this example (first example in three.js home page)
```js
fixture('A')
  .page('https://cineshader.com/');

test('b', async t => {
  await t.wait(10000);
  await t.takeScreenshot('c.png');
  await t.wait(1000);
  await t.takeScreenshot('d.png');
});
```

The issue also visible on video captures
`testcafe firefox,chrome test-example -s screenshots --video video`

<details>
<summary>Screenshots:</summary>

Chrome-c
![Chrome-c](https://user-images.githubusercontent.com/2968077/92941303-dff69500-f458-11ea-8a97-6ab4d5e41c4b.png)

Chrome-d
![Chrome-d](https://user-images.githubusercontent.com/2968077/92941304-e127c200-f458-11ea-9b08-14becb3534e8.png)

Firefox-c
![Firefox-c](https://user-images.githubusercontent.com/2968077/92941305-e127c200-f458-11ea-9fca-c7465933afc4.png)

Firefox-d
![Firefox-d](https://user-images.githubusercontent.com/2968077/92941307-e1c05880-f458-11ea-9534-007fb1d6fdfd.png)

</details>
 
### Your Environment details:
 
* testcafe version:                   1.9.2
* node.js version:                    12.18.3
* command-line arguments:    testcafe firefox,chrome test-example -s screenshots --video video
* browser name and version: Firefox (version 80.0.1) Chrome (version 85.0.4138.102)
* platform and version:          Windows 10
* other:                                    I believe everything was fine in July. I am not sure what change caused the issue, it could be pretty much anything from operating system updates, to drivers (nvidia), to browser versions, to testcafe versions (A month ago we were using testcafe@1.8.1).

**Comment by wentwrong** [comment] 2020-09-14 08:27
I've tried to reproduce the issue with these environment settings, but haven't managed. It works as expected; screenshots and videos are nearly the same both in Chrome and Firefox. 

It is possible that the issue is caused by a broken Firefox installation. Do you have glitches when opening a WebGL app in Firefox without TestCafe? In case this problem occurs only when TestCafe is used, please open the WebGL app in [debug mode](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-d---debug-mode). This will help to determine whether the issue is caused by our screenshotting functionality.

**Comment by mixtur** [comment] 2020-09-14 09:05
> It is possible that the issue is caused by a broken Firefox installation

The issue shows itself both on my local machine and on our ci agent. I find it unlikely that both machines have broken firefox installations. What they do have in common though is Nvidia GPU.

> Do you have glitches when opening a WebGL app in Firefox without TestCafe? In case this problem occurs only when TestCafe is used, please open the WebGL app in debug mode.

Even when being run via testcafe everything looks fine. It is screenshots and videos that are broken, image on the display is fine.

**Comment by wentwrong** [comment] 2020-09-15 09:58
We reproduced the issue when we took a screenshot in Firefox using the [Firefox Screenshots](https://support.mozilla.org/en-US/kb/firefox-screenshots) feature:

![Screenshot_2020-09-15 CineShader](https://user-images.githubusercontent.com/26363017/93196316-ec2d6b80-f752-11ea-885f-ac722c30231e.png)

Does this apply to your case?

The issue is reproduced without TestCafe, so it looks like a bug in Firefox's screenshot functionality, but we couldn't find anything similar in [their bug tracker](https://bugzilla.mozilla.org/buglist.cgi?product=Firefox&component=Screenshots).

As a workaround, you can try running tests in your current user profile (see the [User Profile](https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#user-profiles) part of the Browsers guide to know more) and experiment with different settings of Firefox that may somehow affect rendering. In particular, you can turn off "Hardware Acceleration" as described [here](https://support.mozilla.org/en-US/kb/upgrade-graphics-drivers-use-hardware-acceleration#w_turning-off-hardware-acceleration).

**Comment by mixtur** [comment] 2020-09-15 10:43
If I take a screenshot in our project with Firefox's "Take screenshot" it is indeed broken the same way as in our tests.

And yes disabling hardware acceleration seems to work both in our project and in cineshader. Thank you. I think the issue still stands though.

**Comment by mixtur** [comment] 2020-09-16 10:00
A little more details. In our tests we actually use `takeElementScreenshot` and canvas only takes part of the page.

Also with firefox:userProfile and disabled hardware acceleration canvas part of the page is screenshooted ok, but takeElementScreenshot is not cropping anything. Even the browser's UI is there.

Also there is a warning emitted now

```
  Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at <path/to/screenshot.png>, because the page area mark with ID 2747641261 is not found in the screenshot.
```

**Comment by wentwrong** [comment] 2020-09-17 07:46
Thank you for the details. I should also note that this workaround doesn't allow you to capture a video of a test run in Firefox.

You are right, the issue is still there, but it's caused by a bug in Firefox. If possible, could you please submit an issue to the Mozilla [bug tracker](https://bugzilla.mozilla.org/home)? To take a screenshot of a page, we rely on APIs provided by Firefox, so I think it is some bug Firefox needs to fix on their side. I will close the issue for now.

**Closed by wentwrong** 2020-09-17 07:46 UTC
Labels: STATE: Need response

**Comment by mixtur** [comment] 2020-11-16 08:00
What hardware did you used when reproduced the issue? People from Mozilla can't reproduce it on their hardware (https://bugzilla.mozilla.org/show_bug.cgi?id=1665873)

**Comment by wentwrong** [comment] 2020-11-16 08:40
@mixtur, the screenshot posted above was made using Firefox v81 in the following environment:

```
NVIDIA GeForce GTX 1660 SUPER
Driver version: 26.21.14.4108
Driver date: 22.10.2019
DirectX version: 12 (FL 12.1)
```
