### ISSUE TITLE
takeScreenshotsOnFails: "unable to locate the page area" store sceenshot anyway.

### ISSUE THREAD

**Issue by htho** [DevExpress/testcafe#4231] opened 2019-09-03 05:49 UTC
Sometimes tests fail because there is an issue with the OS. I want to know what was visible on the screen when the test failed. Was the browser window even open?

### What is your Test Scenario?
I do mass tests distributed across unattended virtual machines. Especially the IE tends to fail. I am not always able to tell why, but I suspect that the IE simply shows another tab. Unless I see it, I can't tell for sure.

### What are you suggesting?
I enabled the [takeScreenshotOnFails](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#takescreenshotsonfails) option but I get the error, that the mark could not be found in the page area. Of course it couldnt - We dont know if the window is open.
Instead of throwing away the screenshot, TestCafe could store it anyway. This way I can see what is happening.

**Comment by Dmitry-Ostashev** [comment] 2019-09-03 10:23
Hello,
Thank you for your suggestion. We will take it into account. However, we cannot give any promises.

As a workaround, you can capture the whole screen in the afterEach hook using, for example, the third-party [screenshot-desktop](https://www.npmjs.com/package/screenshot-desktop) library.

**Comment by AndreyBelym** [comment] 2019-09-09 13:06
Actually, it is a duplicate of issue #3552. Please subscribe to it to be notified about our progress in resolving the issue.

**Closed by AndreyBelym** 2019-09-09 13:06 UTC
Labels: TYPE: enhancement
