### ISSUE TITLE
on click error

### ISSUE THREAD

**Issue by rvratner** [DevExpress/testcafe#1658] opened 2017-07-28 23:33 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When I run sample code I see it clicking on the element, as expected, then it throws a script error, but doesn't say what it is.

This worked a week ago, and recently upgraded.

### What is the expected behavior?
Click on nav and test will pass

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

import { Selector } from 'testcafe';

fixture `Test e2e Test`
    .page('http://localhost:9000/');

test('Clicking on map elements', async t => {
    const navUserDropdown = Selector('.nav');
    await t
        .click(navUserDropdown)
        .expect('ok').ok('this assertion will pass');
});

### Specify your

* operating system: Mac 10.12.5
* testcafe version: v 0.16.2
* node.js version: v6.10.0

**Comment by AlexanderMoskovkin** [comment] 2017-07-31 09:02
Hi @rvratner,

What the browser do you use? Could you please try to run tests with disabled browser extensions (for example you can use the `incognito` mode in Chrome via `testcafe "chrome --incognito" test.js`) and let us know does the test work?
Also please check in the browser's dev tools does your page contain js-errors when you perform click manually.

**Comment by rvratner** [comment] 2017-08-01 17:33
Hi,
Thanks for your follow up.
I'm using Chrome. There's no js errors in the console when I run the test manually, and when I run it in incognito mode, the test still fails. 

I see the page load, I see the pointer clicking on the desired object, and the desired action happens (in this case, a popup opens) and then it throws an unknown error.

Is there any way to get more detail on what the error is?

<img width="800" alt="screen shot 2017-08-01 at 10 30 51 am" src="https://user-images.githubusercontent.com/2257526/28838264-b8bb1efa-76a4-11e7-9e8a-499a45fb6f17.png">

**Comment by AlexanderMoskovkin** [comment] 2017-08-02 09:00
This error means that a javascript error with the text `Script error.` was appeared on the page after click.
There are two possible reasons:
1) Something wrong with scripts on your page
2) Something wrong with TestCafe scripts on your page.

Could you please share your application with us to reproduce the problem on our side. If it's not possible we can try to identify the cause of the problem but it'll require some additional actions on your side.

As a temporary workaround you can try to run tests with the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag.

**Comment by rvratner** [comment] 2017-08-18 17:01
Thanks
I can't share the application's because it's under a NDA. When I run --skip-js-errors, I still get the same errors. It runs each test, which right now, just tries to find an element and click on it. Clicks on the element, and then shows the same error (on, what seems to be the click event). There's no JS errors in the console when manually running that scrip. What other actions can I take to help identify?

![screen shot 2017-08-18 at 10 00 24 am](https://user-images.githubusercontent.com/2257526/29469200-175ac3ac-83fc-11e7-8491-6c6b73174c88.png)

thanks for your help,

Rachel

**Comment by AlexanderMoskovkin** [comment] 2017-08-21 11:40
@rvratner Could you please perform the following steps to help us to find the cause of the problem:
1) clone the `testcafe-hammerhead` repo (https://github.com/DevExpress/testcafe-hammerhead);
2) call `npm install`;
3) install `gulp` globally (if it's not installed on your machine);
4) run `gulp playground --dev` (a new browser window will be opened);
5) open dev tools in the browser and enter your page url into the input;
6) see it there a `Script error.` error in dev tools. If yes then provide us with its stack

**Comment by Hendriksie** [comment] 2017-09-22 09:27
I just started using `testcafe` and I have encountered the exact same issue using `Chrome 61.0.3163 / Windows 10 0.0.0`.

A colleague of mine, using a Macbook, does not encounter the problem.

The problem seems to be with `hammerhead`, I ran `testcafe` remotely and by manually using the generated URL I visited the page using chrome and I encountered the following error:

![](https://puu.sh/xFZRe.png)

I've also tried it with a complete refresh on node_modules, and I have tried it using the dev version of `testcafe` but I still encounter this problem.

**Comment by AlexanderMoskovkin** [comment] 2017-09-22 12:58
Hi @Hendriksie,

I suppose some browser extension breaks TestCafe behavior (see [faq](https://devexpress.github.io/testcafe/faq/#when-i-run-a-testcafe-test-i-get-an-unexpected-error-what-can-cause-that)) in your case. Try to run tests in the `incognito` mode: `testcafe "chrome --incognito" test.js`.

Meanwhile we are going to run tests in a 'clean' browser since the testcafe `v0.18.0` by default (see #1623 ).

**Comment by AlexanderMoskovkin** [comment] 2017-10-11 13:57
#1623 is implemented so I close this

**Closed by AlexanderMoskovkin** 2017-10-11 13:57 UTC
Labels: To be reproduced, TYPE: bug
