### ISSUE TITLE
Unable to access iframe

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe#3323] opened 2019-01-20 22:21 UTC
### What is your Test Scenario?
Scenario is to test two iframes present in the main page. 
A form elements are rendered inside an iframe present inside the page as preview.
 Whenever I change the text in the form elements, it has to be rendered automatically and displayed in the iFrame with 2 secs delay.
### What is the Current behavior?
 I need to test this scenario using TestCafe but the iFrame elements are neither getting recognised by  Selector nor by ReactSelector 
 
### What is the Expected behavior?
When I switch to the iframe, TestCafe should identify the iFrame elements either using Selector or ReactSelector
 
### What is your web application and your TestCafe test code?
Unfortunately, this is internal app and cant share the link but I can share the test code

 
```ts
 
Then(/^I should see the heading section in the first iframe$/, async () => {
    await testController.expect(contenteditoroverylaypage.getEmailCaptureIFrame().visible).ok();
    await testController.switchToIframe(contenteditoroverylaypage.getEmailCaptureIFrame());
    await testController.switchToIframe(await Selector('#PreviewRenderer').nth(0).with({ boundTestRun: testController }));
    await testController.switchToMainWindow();
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
✖ Then the Overlay Template Textarea count should be 4 # features/step_definitions/contentEditorOverylayStep.js:167
       Error: { type: 'uncaughtErrorInClientFunctionCode',
         isTestCafeError: true,
         callsite:
          CallsiteRecord {
            filename: '/home/vijay_vedachalam/Vijay/crow/crow-ui-acceptance-tests/features/step_definitions/contentEditorOverylayStep.ts',
            lineNum: 82,
            callsiteFrameIdx: 6,
            stackFrames:
             [ [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite] ],
            isV8Frames: true },
         errMsg: 'TypeError: this.each is not a function',
         instantiationCallsiteName: 'Selector' }


   1) - Error in test.after hook -
      An error occurred in Selector code:

      TypeError: this.each is not a function


```
</details>

<details>
<summary>Screenshots:</summary>

![screenshot from 2019-01-20 22-10-41](https://user-images.githubusercontent.com/7630355/51445754-99db4380-1d00-11e9-9427-d5a2501c5bb0.png)

```

```
</details>

### Your Environment details:
 
* testcafe version:   Tried in both 0.20.5 and v1.0.0-alpha.1               
* node.js version:     10.1.0               
* command-line arguments:  BASE_URL=URL yarn test --tags @iframe 
* platform and version:   Ubuntu 18.04.1      
* other:

**Comment by Farfurix** [comment] 2019-01-21 11:00
Hello, @vvedachalam.
Unfortunately, this information is not sufficient to find the cause of the issue. There can be many causes, and therefore we can't give you any advice without analyzing your page or code. 
 
I suggest that you first install the latest alpha version: `npm install testcafe@1.0.0-alpha.2` and try to pass your tests. If this does not help, there are two options to help us determine what is going wrong:
1. Modify the below example to reproduce this issue.
2. [Debug your test scenario](https://devexpress.github.io/testcafe/documentation/test-api/debugging.html) and provide more additional information from the DevTools console.

Example:
```html
<html>
<head></head>
<body>
<iframe id="iframe1"></iframe>
<script>
    function testIframe () {
        var iframe = document.getElementById('iframe1');
        var contentDocument = iframe.contentDocument;
 
        contentDocument.open();
        contentDocument.write('<div id="div1"><a id="a1">anchor</a></div>');
        contentDocument.close();
    }
 
    setTimeout(testIframe, 2000);
 
</script>
</body>
</html>
```
```js
import { Selector } from 'testcafe';
 
fixture `Fixture`
    .page('http://localhost:8080/');
 
test('click', async t => {
    await t
        .switchToIframe('#iframe1')
        .click('#a1');
});
```

**Comment by vvedachalam** [comment] 2019-01-21 18:42
@Farfurix I have even tried with 1.0.0 alpha 2 
But still i am getting the same error. 

NOTE: I am using cucumber BDD framework developed by @helen-dikareva 
So please use that framework as baseline and let me know.
There is another ticket raised by someone else for the same issue https://github.com/DevExpress/testcafe/issues/3324

My apologies for unable to provide you some code base for testing

**Comment by vvedachalam** [comment] 2019-01-21 18:46
I tried to get the location after switching to iFrame and the location it is printing as origin page (not the main window location but the page from which we started the app. The app is partially behaving as Single page Application). Will this be a problem?

**Comment by vvedachalam** [comment] 2019-01-21 22:14
@Farfurix found a iframe site to demo you

```````
test.feature
Feature: Verifying iFrame
@read
Scenario: iframe check
Given i am in the homepage
Then I should see the iframe

````````````

````test.ts
Given (/^i am in the homepage$/, async () => {
await testController.navigateTo('https://jsfiddle.net/westonruter/6mSuK/');
} );

Then(/^I should see the iframe$/, async () => {
    let getLocation1:any = ClientFunction(() => document.location.href).with({ boundTestRun: testController });
    console.log('loc1',await getLocation1());    
    await testController.expect(await Selector('#login').with({boundTestRun:testController}).visible).ok();
    // await testController.switchToIframe(await Selector('iframe[name=result]').with({boundTestRun:testController}));
    await testController.switchToIframe('iframe[name=result]');
    console.log('loc2',await getLocation1());    
// await testController.click('#pt-anontalk > a');
    await testController.click(await Selector('#pt-anontalk > a').with({ boundTestRun: testController }));
// console.log(Selector('head > title').with({boundTestRun:testController}).textContent);

});
````
It is switching to the right frame but it is not identifying the iframe element.

If I use === > await testController.click('#pt-anontalk > a');
I am getting the following error
````
    Given i am in the homepage
    Then I should see the iframe
loc1 https://jsfiddle.net/westonruter/6mSuK/
loc2 https://fiddle.jshell.net/westonruter/6mSuK/show/
    ✖ failed
      Error: { type: 'actionElementNotFoundError',
        isTestCafeError: true,
        callsite:
         CallsiteRecord {
           filename: '/test.ts',
           lineNum: 259,
           callsiteFrameIdx: 6,
           stackFrames:
           isV8Frames: true },
        apiFnChain: [ 'Selector(\'#pt-anontalk > a\')' ],
        apiFnIndex: 0,
        isRejectedDriverTask: true }
````````
If i use ==>     await testController.click(await Selector('#pt-anontalk > a').with({ boundTestRun: testController }));
I am getting this error
`````
Feature:
    Given i am in the homepage
    Then I should see the iframe
loc1 https://jsfiddle.net/westonruter/6mSuK/
loc2 https://fiddle.jshell.net/westonruter/6mSuK/show/
    ✖ failed
      Error: { type: 'actionElementNotFoundError',
        isTestCafeError: true,
        callsite:
         CallsiteRecord {
           filename: 'test.ts',
           lineNum: 259,
           callsiteFrameIdx: 6,
           stackFrames:
            [ [CallSite],
              [CallSite],
              [CallSite],
              [CallSite],
              [CallSite],
              [CallSite],
              [CallSite],
              [CallSite],
              [CallSite],
              [CallSite] ],
           isV8Frames: true },
        apiFnChain:
         [ 'Selector(\'#pt-anontalk > a\')',
           'Selector(\'#pt-anontalk > a\')' ],
        apiFnIndex: 1,
        isRejectedDriverTask: true }


   1) - Error in test.after hook -
      The specified selector does not match any element in the DOM tree.

         | Selector('#pt-anontalk > a')
       > |   Selector('#pt-anontalk > a')

```````

**Comment by AndreyBelym** [comment] 2019-01-23 10:43
I wish to warn you that  [helen-dikareva/testcafe-cucumber-demo](https://github.com/helen-dikareva/testcafe-cucumber-demo) was not updated for more than a year and is created for demonstration purposes only. If you use this demo example, I recommend that you consider some of the following projects as a better alternative:

 * https://github.com/hdorgeval/testcafe-starter
 * https://github.com/kiwigrid/gherkin-testcafe
 * https://github.com/rquellh/testcafe-cucumber

I've checked the example from [your comment](https://github.com/DevExpress/testcafe/issues/3323#issuecomment-456212322) and noticed a problem in the logic of the example. The `iframe[name=result]` contains an another `iframe`, into which it is  necessary to seitch in order to access the `#pt-anontalk > a` element. Check the screenshot of the page's DOM and the corrected test file:
![image](https://user-images.githubusercontent.com/4479386/51593398-25242700-1f03-11e9-8117-fd8ba6e91892.png)

```js
import { ClientFunction, Selector } from "testcafe";

fixture `Iframe`;

test(`iframe`, async testController => {
    await testController.navigateTo('https://jsfiddle.net/westonruter/6mSuK/');

    let getLocation1 = ClientFunction(() => document.location.href).with({boundTestRun: testController});
    console.log('loc1', await getLocation1());
    await testController.expect(await Selector('#login').with({boundTestRun: testController}).visible).ok();
    // await testController.switchToIframe(await Selector('iframe[name=result]').with({boundTestRun:testController}));
    await testController.switchToIframe('iframe[name=result]');
    await testController.switchToIframe('iframe');
    console.log('loc2', await getLocation1());
// await testController.click('#pt-anontalk > a');
    await testController.click(await Selector('#pt-anontalk > a').with({boundTestRun: testController}));
// console.log(Selector('head > title').with({boundTestRun:testController}).textContent);
});
```

The error described in your original post has the following error message:
```
An error occurred in Selector code:

      TypeError: this.each is not a function
```

I searched for the usage of the `each` method in our code and could not find anything that could lead to this error. Thus I guess that the error can occur in your `getEmailCaptureIFrame` method, and the wrong source line was highlighted as the error source due to the poor Cucumber integration. 

To help you, I need an example that can be used to reproduce the problem with the `"An error occurred in Selector code: TypeError: this.each is not a function"` error. If you can't create an example, at least try to add the [debug](https://devexpress.github.io/testcafe/documentation/test-api/debugging.html#client-side-debugging) action before actions that lead to a problem, open Chrome Developer Tools, click the `Pause on exceptions` button and the `Pause on caught exceptions` checkbox in the `Sources tab` in Developer Tools. Then, click the `Resume` button on the page and wait until Developer Tools pauses on an exception
with the `"TypeError: this.each is not a function"` message, take a screenshot of Developer Tools and share it with me. 

Check the screenshot below to see how the Develeper Tools window looks when it pauses on the right exception:
![image](https://user-images.githubusercontent.com/4479386/51594931-9c0eef00-1f06-11e9-8d50-ee45c42eff7e.png)

**Comment by vvedachalam** [comment] 2019-01-23 22:50
Thanks, actually i have already updated my framework with 
https://github.com/rquellh/testcafe-cucumber 
Since he has mentioned @helen-dikareva name in his project as the origin, I thought of mentioning her name.
Coming back to the original issue, I will give the debug screenshot soon. 
Meanwhile, I found that using srcdoc attribute inside iframe is causing the issue. I  tried an iframe with src attribute and its all working fine. Could you please try with **srcdoc** and see?

```
const doc = `
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
   <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
   <head>
     <script type="text/javascript" src="/gpsa/js/jquery-1.10.2.min.js"></script>	        
     <script type="text/javascript" src="/gpsa/js/login.js"></script>
     <link href="https://platform.cloud-iq.com//css/global_styles/styles.css?v=63" media="all" rel="stylesheet" type="text/css"></link>
     <link href="https://platform.cloud-iq.com//css/global_styles/fonts.css?v=63" media="all" rel="stylesheet" type="text/css"></link>
     <link href="/gpsa/css/style.css" 
     <title>
     </title>
   </head>
   <body>
     
       
     <div id="login_container">
       <div id="login_inner_form">
        <div id="container_spacer"></div>
        
        <div id="container_0" class="webclient_container">
              <section>
            <div class="container">
              <div class="login-box">
                <div id="unsupported_browser" class="error-message" style="display:none;">
                  Sorry, this browser version is not supported. Please upgrade to a later version.
                </div>
                <form class="form" id="login_form" method="post" action="">
                  <p class="error-message" style="display:none">This field is required</p>
                  <label for="email">Email Address*</label>
                  <div id="message_panel" style="display:none">
                    <div id="message"></div>
                  </div>
                  <input type="text" id="username" name="username" />
                  <p class="error-message" style="display:none">This field is required</p>
                  <label for="password">Password*</label>
                  <input type="password" id="password"  name="password" value class="pink_validation" />
                  <div id="reminder_link_container" class="has-margin">						
                    <span class="login-link" id="reminder_link">Forgot password?</span>
                  </div>
          
                  <div class="submit-form" id="submit-signup" onClick="login_user()"><span id="login_control" class="button bg-black">Sign in</span></div>
                  
                </form>
              </div>
              
              <div id="verification_form" style="display:none">
                <div id="verification_message" style="display:none">
                  You have not yet verified your email. <span class="login-link" id="verification_link">Click here</span> to send the verification email.
                </div>
                <div id="verification_sent" style="display:none">
                  An email has been sent to you.
                </div>
              </div>
              
            </div>
            <input type="hidden" name="logged_in" id="logged_in" value="false">
        </section>
    
        </div>
        
        <div class="clear"></div>
        
      </div>
       
       <div id="login_inner_redirect" style="display:none;"	>
    
    
      
        
        <div id="container_spacer"></div>
        
        <div id="container_0" class="webclient_container redirect_msg" >
          <div id="redirect_msg">
          <p>You are already logged in, you will be redirected shortly... </p>
          </div>
        </div>
        
        <div class="clear"></div>
        
      </div>
     </div>
     
      
       
     <div id="hidden_login_form_container">
     
       <form id="hidden_login_form">
        <input type="hidden" id="redirect_username" name="username" value="">
        <input type="hidden" id="redirect_password" name="password" value="">
        <input type="hidden" name="do" value="auth">
       </form>
       <form id="hidden_token_form">
        <input type="hidden" id="api_id" name="id" value="">
        <input type="hidden" id="api_token" name="token" value="">
        <input type="hidden" name="remote_auth" value="true"> 
        <input type="hidden" name="do" value="auth">
       </form>
     </div>
     
     </body>
   </html>`;

          <iframe id="iframe1" src="https://platform.cloud-iq.com/login" width="100%" height="350px" marginwidth="0" marginheight="0" scrolling="no"></iframe>
          <iframe id="iframe2" srcdoc={doc} width="100%" height="350px" marginwidth="0" marginheight="0" scrolling="no"></iframe>

```

**Comment by vvedachalam** [comment] 2019-01-24 00:40
@AndreyBelym plz find the attached screenshot as you have requested
![screenshot from 2019-01-24 00-35-31](https://user-images.githubusercontent.com/7630355/51646496-a5cd3c80-1f70-11e9-9d2a-d043a9aab547.png)
![screenshot from 2019-01-24 00-24-37](https://user-images.githubusercontent.com/7630355/51646497-a665d300-1f70-11e9-98c9-e67a89b97355.png)

**Comment by AndreyBelym** [comment] 2019-01-24 11:00
Our proxy doesn't support the `srcdoc` attribute: https://github.com/DevExpress/testcafe-hammerhead/issues/1237. I will notify when we implement it, or you can ask @miherlosev or @LavrovArtem for help if you can make a PR.

**Comment by vvedachalam** [comment] 2019-01-25 09:20
@AndreyBelym Thanks for the update. Will it be implemented any soon? 
@miherlosev @LavrovArtem Please do let me know what should I do for PR. Also I need this issue to be sorted out at the earliest. So could you please consider this for your current or next sprint?

**Comment by LavrovArtem** [comment] 2019-01-25 14:19
@vvedachalam,
I'm unable to provide you with any time frame as any personal estimate may be misleading. We need time to investigate this problem. Once we get any results, I assure you that we will notify you.

**Comment by vvedachalam** [comment] 2019-01-25 17:49
@LavrovArtem Thanks.

**Comment by cvoege** [comment] 2019-09-19 15:18
Is there any update on this?

**Comment by miherlosev** [comment] 2019-09-20 08:52
I will close this issue because the origin problem was already described in DevExpress/testcafe-hammerhead#1237. Track DevExpress/testcafe-hammerhead#1237 to be informed about our progress.

**Closed by miherlosev** 2019-09-20 08:52 UTC
Labels: AREA: client, STATE: Need improvement, STATE: Need response, SYSTEM: hammerhead
