### ISSUE TITLE
Run testcafe with https protocol

### ISSUE THREAD

**Issue by edoardocavazza** [DevExpress/testcafe#1985] opened 2017-12-06 09:24 UTC
### Are you requesting a feature or reporting a bug?

Requesting a feature (maybe)

### What is the current behavior?

I am unable to start testcafe using https protocol

### What is the expected behavior?

Testcafe should run with ssl certificate (if provided)

### Specify your

* operating system: MacOS 10.13.1
* testcafe version: 0.18.3
* node.js version: 8.7.0

**Comment by AndreyBelym** [comment] 2017-12-06 13:06
Hello @edoardocavazza!

It's a useful feature, because some browser API's (e.g. Apple Pay) are available on HTTPS pages, and TestCafe HTTP end-point prevents access to them.

Right now, you can configure [stunnel](https://www.stunnel.org) to encrypt traffic from TestCafe to browser. You can check "TLS front-end to a web server" on https://www.stunnel.org/config_windows.html for an example configuration.

**Comment by AndreyBelym** [comment] 2017-12-25 12:57
Example page: https://andreybelym.github.io/test-pages/gh-1985.html
Test:
```
fixture `ApplePay`.page`https://andreybelym.github.io/test-pages/gh-1985.html`;

test(`test`, t => t.wait(10000));
```

**Comment by miherlosev** [comment] 2017-12-25 14:25
Reproduced in Safari 11.0.2.
With `TestCafe` browser is raised an error:
```js
InvalidAccessError (DOM Exception 15): Trying to call an ApplePaySession API from an insecure document.
```

**Comment by awithy** [comment] 2018-04-17 20:32
+1

**Comment by intermike** [comment] 2018-04-26 14:43
@AndreyBelym, could you please review the pull requests and help me with tests and documentation. Thank you.

https://github.com/DevExpress/testcafe/pull/2359
https://github.com/DevExpress/testcafe-hammerhead/pull/1590
https://github.com/DevExpress/testcafe-live/pull/19

This changes works properly for me. Tests and documentation are needed to be designed.

**Comment by AndreyBelym** [comment] 2018-04-26 15:09
Hi @intermike, thanks for contributing. Let's focus first on `testcafe-hammerhead` part, then when it's merged, we will discuss end-user API and CLI switches in TestCafe. I need some time to look at your work, but at first glance it's mostly fine, except a one strange expression at https://github.com/DevExpress/testcafe-hammerhead/pull/1590/files#diff-f17475e116c70c73c37dd369b8d12b6bR30 and absence of tests.

**Comment by awithy** [comment] 2018-04-26 17:59
I'm not sure I 100% understand this issue, or the proposed changes.  Will these changes allow TestCafe to run locally against a remote https endpoint?  This use case was the one I was struggling with: to enable smoke testing from our build server against our Integration and UAT environments.

**Comment by intermike** [comment] 2018-04-26 20:46
Hi @AndreyBelym 

#### Lint error
/testcafe-hammerhead/src/client/utils/url.js
  30:61  error  'protocol' is restricted from being used. Please use getters and setters for anchor element from native methods instead  no-restricted-properties

#### Lint rule
Rule is described in https://github.com/LavrovArtem/eslint-plugin-hammerhead/blob/master/lib/index.js

Please advise what should I do with `location.protocol`.

**Comment by AndreyBelym** [comment] 2018-04-27 07:04
@awithy, what do you mean by 

> run locally against a remote https endpoint*? 

You can test websites served over HTTPS as easy as websites served over HTTP, since our proxy accepts both HTTPS and HTTP as input. However all websites regardless their original protocol are served over HTTP in testing session, because our proxy supports only HTTP output. The proposed changes enable HTTPS output for proxy, so connection during testsing session will be encrypted.

**Comment by AndreyBelym** [comment] 2018-04-27 07:08
@intermike, I think it's ok to disable this check here with
```
/*eslint-disable no-restricted-properties*/
protocol = ...
/*eslint-enable no-restricted-properties*/
```

**Comment by intermike** [comment] 2018-04-27 11:36
@AndreyBelym Thanks for the guide. Pushed into PR.

**Comment by kirovboris** [comment] 2018-05-08 11:48
I believe `key` and `cert` are path to files, why should it be `<Buffer>`?

**Comment by miherlosev** [comment] 2018-05-08 12:10
> It works this way in nodejs, but it's not quite usable. Why should we choose this approach?

Nodejs api is polymorphically for this option. It takes `string`, `Buffer` and `Object` (see [createsecurecontext_options](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options)).
Eventually, all of this will transformed to `Buffer`.

In my opinion, `Buffer` is the best way to specify ssl keys in programming interface.
Also, in [https example](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) from the nodejs documentation used this way.

```js
const https = require('https');
const fs = require('fs');

const options = {
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};

https.createServer(options, (req, res) => {
  res.writeHead(200);
  res.end('hello world\n');
}).listen(8000);
```

**Comment by intermike** [comment] 2018-05-09 09:39
@miherlosev 
I suppose the approach `runner.ssl(key,  cert)` does not fit the initialization order of testcafe

```js
createTestCafe('localhost', 1337, 1338) // We need to pass certificates here
    .then(tc => {
        testcafe     = tc;
        const runner = testcafe.createRunner(); // But runner is created only here

        return runner
            .src(['tests/fixture1.js', 'tests/func/fixture3.js'])
            .browsers(['chrome', 'safari'])
            .run();
    })
    .then(failedCount => {
        console.log('Tests failed: ' + failedCount);
        testcafe.close();
    });
```

**Comment by kirovboris** [comment] 2018-05-10 13:59
ping @AndreyBelym

**Comment by miherlosev** [comment] 2018-05-10 15:16
@intermike

Yes you are right.  `sslOptions` should be declared in a factory method. I've updated the https://github.com/DevExpress/testcafe/issues/1985#issuecomment-387341594

**Comment by AndreyBelym** [comment] 2018-05-14 08:38
1. I think we should also support [PFX certificates](https://en.wikipedia.org/wiki/PKCS_12) (because it's more convenient to use) and [rejectUnauthorized property](https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener) to enable self-signed certificates for testing purposes. @miherlosev's proposal for Runner API extension is already fine with this, but for CLI we should use more general approach like:
```
testcafe --ssl pfx=path/to/some.pfx;rejectUnauthorized=true;...
``` 
We already have such options syntax for [browser providers' options](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html#emulator-parameters).

2. I would argue that we should support only Buffers and threat strings as a kind of Buffer. Yes, Node.js API works this way, but it makes harder switching from CLI to custom runner. We went similar way with [globs and runner.src](https://github.com/DevExpress/testcafe/issues/980), and now this feature is in top 5 in the requested features list. IMHO our API must be as convenient as the CLI.

**Comment by miherlosev** [comment] 2018-05-16 11:41
After discussing with @AndreyBelym, we introduce the following API:

*Programming interface*

```js
createTestCafe (hostname, port1, port2, sslOptions)
```

`sslOptions` are [nodejs https options](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener)

*Command-line interface*

```js
testcafe --ssl pfx=path/to/some.pfx;rejectUnauthorized=true;...
```

`ssl` is a parameter that contains semicolon-separated options in the key-value format.

For the `key`, `cert` and `pfx` properties, the following processing algorithm is used:
if a property has a `string` type and its length is less that the `MAX_PATH` limit,
we interpret the value as a file path. Thus, we read the file content and replace the property value with this content.

@kirovboris Take a look please

**Comment by miherlosev** [comment] 2018-05-21 12:56
Hi @intermike 

We've updated the `testcafe-hammerhead` dependency with changes related to the `https support` feature.
You can continue to develop this feature on the `TestCafe` side.

See an API description in https://github.com/DevExpress/testcafe/issues/1985#issuecomment-389488983.
Let us know if you need any help about with our development workflow.

**Comment by intermike** [comment] 2018-05-22 09:30
Affirmative, @miherlosev.

**Closed** 2018-06-25 17:15 UTC
Labels: TYPE: proposal

**Comment by VasilyStrelyaev** [comment] 2018-07-06 15:05
Working on docs
