### ISSUE TITLE
can't load tests to runner

### ISSUE THREAD

**Issue by miecio1212** [DevExpress/testcafe#1618] opened 2017-07-17 10:31 UTC
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
Error: Cannot find a test source file at 

### What is the expected behavior?
I can't use glob or *.spec.js I have to write particular test name

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
const createTestCafe = require('testcafe')
let testcafe = null

createTestCafe('localhost', 1337, 1338)
  .then(tc => {
    testcafe = tc
    const runner = testcafe.createRunner()
    return runner
      .src(['tests/e2e/specs/test1.spec.js']) // I'd like to use tests/e2e/specs/*.spec.js
      .browsers(['chrome'])
      .run()
  })
  .then(failedCount => {
    console.log('Tests failed: ' + failedCount)
    testcafe.close()
  })

```

### Specify your

* operating system: windows 8.1
* testcafe version: "testcafe": "^0.16.2",
* node.js version: v6.9.3

**Comment by inikulin** [comment] 2017-07-17 12:04
Duplicate of https://github.com/DevExpress/testcafe/issues/980

**Closed by inikulin** 2017-07-17 12:04 UTC
Labels: REASON: duplicate
