### ISSUE TITLE
t.request() with proxyless returning 400

### ISSUE THREAD

**Issue by codambro** [DevExpress/testcafe#7609] opened 2023-04-03 14:54 UTC
### What is your Scenario?

Running API tests and trying to enable proxyless. Finding that the tests fail with 400 error in proxyless, but pass normally.

### What is the Current behavior?

API requests fail:
```
{
  status: 400,
  statusText: undefined,
  headers: {
    server: 'awselb/2.0',
    date: 'Mon, 03 Apr 2023 14:50:36 GMT',
    'content-type': 'text/html',
    'content-length': '122',
    [Symbol(nodejs.http2.sensitiveHeaders)]: []
  },
  body: '<html>\r\n' +
    '<head><title>400 Bad Request</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>400 Bad Request</h1></center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}
```

### What is the Expected behavior?

API request succeed

### What is your public website URL? (or attach your complete example)

See email

### What is your TestCafe test code?

```
const token = "TOKEN";
const url = "URL";

fixture('Proxyless API test');

test("API Test", async t => {
    const resp = await t.request({
        method: "get",
        url: url,
        headers: {
            'x-risk-token': token,
            'accept': '*/*',
        }
    });
    console.log(resp);
    await t.expect(resp.status).eql(200);
});
```

### Your complete configuration file

```
{
  "hostname": "localhost",
  "disablePageCaching": true,
  "skipUncaughtErrors": true,
  "skipJsErrors": true,
  "retryTestPages": true,
  "pageLoadTimeout": 60000,
  "pageRequestTimeout": 60000,
  "assertionTimeout": 90000,
  "proxyless": true
}
```

### Steps to Reproduce

1. Run test with t.request()

### TestCafe version

2.5.0-rc.1

### Command-line arguments

testcafe chrome --config-file conf.json proxylessTest.ts

**Comment by aleks-pro** [comment] 2023-04-05 12:48
Hello @codambro  ,

Thank you for reporting this issue. I reproduced it on my side. We will research it and update this thread once we have any results.

**Comment by yuwoonil** [comment] 2023-04-13 08:33
Hello @aleks-pro 
this issue fixed in 2.5?

**Comment by aleks-pro** [comment] 2023-04-14 07:21
Hello @yuwoonil ,

Not yet, we are working on this.

**Comment by Artem-Babich** [comment] 2023-04-14 08:46
Hi,

The cause of this issue is the "method" property value. It is not valid because of the lowercase. This behavior is incorrect, and we will fix it. To resolve the issue now, please specify the method property as follows: `method: 'GET'`.

**Closed** 2023-04-17 08:58 UTC
Labels: TYPE: bug, SYSTEM: native automation
