### ISSUE TITLE
Use delay in dragToElement

### ISSUE THREAD

**Issue by svego** [DevExpress/testcafe#4165] opened 2019-08-16 08:20 UTC
### Are you requesting a feature or reporting a bug?
Feature request.

### What is your Test Scenario?
I need to drag an element to another element. But between the mouse-down and drag i need a certain delay (100ms). This is used to get the item in a hovering state on the website

### What is the Current behavior?
Drag immediately starts after the mouse down

### What is the Expected behavior?
An api/option that specifies the delay for the drag option or a workaround to create this method myself

**Comment by Farfurix** [comment] 2019-08-16 11:44
@svego 

Hello,

Could you please provide us with your "handle a hovering state on a website" example and describe all the issues that you encountered in a test code. We will examine it and consider your feature suggestion.

I will close this issue as a duplicate of https://github.com/DevExpress/testcafe/issues/2803. We are waiting for your example. You can post it here or in the following thread: https://github.com/DevExpress/testcafe/issues/2803.

**Closed** 2019-08-16 11:45 UTC
