### ISSUE TITLE
cannot read property 'frames' of undefined hammerhead.js on loading webpage

### ISSUE THREAD

**Issue by ankush29** [DevExpress/testcafe#5164] opened 2020-06-03 07:29 UTC
#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by miherlosev** [comment] 2020-06-03 12:36
I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by ankush29** [comment] 2020-06-03 13:19
Hi
private _getWindowsForSync (initiator: Window, currentWindow: Window,
windows: Window[] = []): Window[] {
        if (currentWindow !== initiator && currentWindow !== this._win.top)
            windows.push(currentWindow);
            // @ts-ignore
            for (const frameWindow of currentWindow.frames) {
                this._getWindowsForSync(initiator, frameWindow, windows);
            }

        return windows;
    }

currentWindow gives me undefined inside for loop
file name: window-sync.ts

so i have tried with if condition and then working for me but it is not a
good solution
private _getWindowsForSync (initiator: Window, currentWindow: Window,
windows: Window[] = []): Window[] {
        if (currentWindow !== initiator && currentWindow !== this._win.top)
            windows.push(currentWindow);

        // @ts-ignore
        if(currentWindow) {
            // @ts-ignore
            for (const frameWindow of currentWindow.frames) {
                this._getWindowsForSync(initiator, frameWindow, windows);
            }
        } else {
            console.log("currentWindow=====",currentWindow)
        }


        return windows;
    }

**Comment by LavrovArtem** [comment] 2020-06-04 10:28
Hello @ankush29,
You indicated where the issue occurs, but this information is still not sufficient to find the cause of the issue. The `_getWindowsForSync` method is called in two places, and they both should not contain a non-window argument. The `this._win` property is our property that contains the current execution window, and `currentWindow.frames` should not contain undefined elements: [https://developer.mozilla.org/ru/docs/Web/API/Window/frames](https://developer.mozilla.org/ru/docs/Web/API/Window/frames).

**Comment by ankush29** [comment] 2020-06-04 12:58
please refer to this:
https://github.com/DevExpress/testcafe-hammerhead/issues/2339

**Comment by LavrovArtem** [comment] 2020-06-04 13:26
Thank you for the additional information. I'll close this issue. Let's continue our discussion in the DevExpress/testcafe-hammerhead#2339 thread.

**Closed** 2020-06-04 13:26 UTC
