### ISSUE TITLE
Function keys press with TestCafe

### ISSUE THREAD

**Issue by sophiecdd** [DevExpress/testcafe#3113] opened 2018-11-13 16:48 UTC
As the Function keys are not listed in the supported key type in the document, I assume this is not supported by .pressKey, if so, is there any work around?

**Comment by AndreyBelym** [comment] 2018-11-14 07:46
This thread appears to be a duplicate of #1887. Please use the original thread instead of this issue to get notifications about our progress with implementing this feature.

**Closed by AndreyBelym** 2018-11-14 07:46 UTC

**Comment by sophiecdd** [comment] 2018-11-14 14:40
Thanks Andrey for reply. Sorry I didn't get to read the feature enhancement board earlier, wondering do we have a timeline on the implementation of this feature, I see it was logged a year ago, any updates? If there any work around you would suggest?
