### ISSUE TITLE
Testcafe unable to load site properly

### ISSUE THREAD

**Issue by PrashantSingh5946** [DevExpress/testcafe#7312] opened 2022-09-28 16:41 UTC
### What is your Scenario?

We are testing an ecommerce site hosted at https://ring1tie.adventure-works.com, this site earlier worked fine with testcafe but since last couple of months testcafe is unable to load the page properly and many elements including the increase/ decrease button do not work and there is an error in console logs 
![console](https://user-images.githubusercontent.com/70136137/192831945-7f9d29c7-e154-4bbc-a1de-70b8544fc4b5.png)

https://user-images.githubusercontent.com/70136137/192834423-dd4d754f-6eb6-4aaf-9e52-c65b7320a2f1.mp4

### What is the Current behavior?

Increment/decrement and cart buttons are not working when opened on the testcafe server, they are otherwise working fine on normal browsers.

### What is the Expected behavior?

The buttons should work fine 

### What is your public website URL? (or attach your complete example)

https://user-images.githubusercontent.com/70136137/192836325-76d80687-ad51-4792-b414-4dff57a46332.mp4

URL: https://ring1tie.adventure-works.com/awbusiness/tegothar-women-s-coat/68719519893.p

### What is your TestCafe test code?

import { Selector } from "testcafe";

fixture`Checkout Page Tests`
  .page(
    "https://ring1tie.adventure-works.com/awbusiness/tegothar-women-s-coat/68719519893.p"
  )
  .beforeEach(async (testController) => {
    await testController.maximizeWindow();
  });

test("Validate checkout page", async (testController: TestController) => {
  await testController.wait(2000);
  if (await Selector('[aria-label="Accept cookies"]').exists) {
    await testController.click('[aria-label="Accept cookies"]');
  }
  await testController
    .hover("#ms-buybox__product-quantity-input button.increment")
    .wait(1000)
    .click("#ms-buybox__product-quantity-input button.increment");
  let currentCount = await Selector('[aria-label="quantity input"]').value;
  await testController
    .expect(currentCount)
    .eql("2", "Click element is not working")

    .hover("#ms-buybox__product-quantity-input button.decrement")
    .wait(1000)
    .click("#ms-buybox__product-quantity-input button.decrement");
  await testController.wait(5000);
  currentCount = await Selector('[aria-label="quantity input"]').value;
  await testController.expect(currentCount).eql("1");
});

### Screenshots

![console](https://user-images.githubusercontent.com/70136137/192838264-f408bacd-6181-422f-8d22-e3e0d1ed6172.png)

### Steps to Reproduce

1. Go to the following URL on testcafe  https://ring1tie.adventure-works.com/awbusiness/tegothar-women-s-coat/68719519893.p
2. Notice how the increment and decrement buttons are not working

### TestCafe version

2.0.0

### Node.js version

v16.13.0

### Command-line arguments

yarn testcafe test.js --skip-js-errors

### Browser name(s) and version(s)

Chrome latest

### Platform(s) and version(s)

Windows

**Comment by PrashantSingh5946** [comment] 2022-09-29 11:07
I have tried various testcafe versions till 1.10.0 and the bug reproduces on all of those versions. Everything seemed working fine until 30-06-2022, after this date almost all the tests started failing.

**Comment by AlexKamaev** [comment] 2022-09-30 08:28
I managed to reproduce the issue with previous Chrome versions as well.
The cause of the issue is still unclear, so we need time to research it.

**Comment by miherlosev** [comment] 2022-12-07 03:12
Hi @PrashantSingh5946 ,

TestCafe runs tests using the [URL-rewritten](https://github.com/devexpress/testcafe-hammerhead) proxy.
This approach is good. However, there is a way to improve the stability and speed of test execution - the native browser automation API.
We have a test execution mode uses native browser automation - we call it the `Proxyless` mode.
In `Proxyless` mode, a few issues are already fixed.
By the way, this issue was also fixed in `Proxyless` mode.
Try running your tests in `Proxyless` mode and let us know the results.
This option is available in all interfaces:

```js
// Command-line
testcafe chrome tests --experimental-proxyless

// Programmatic
testcafe
    .createRunner
	.src('tests')
	.browsers('chrome')
	.run({ experimentalProxyless: true });
	
// Configuration file
{
   "experimentalProxyless": "true"
}	
```

Note that at present it is an experimental mode.
Also, the `Proxyless` mode is implemented only in Google Chrome. It will not work correctly if you run tests in a non-Chrome browser or in a combination of other browsers.

**Comment by miherlosev** [comment] 2023-06-30 07:49
Hi @PrashantSingh5946,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.

**Closed by miherlosev** 2023-06-30 07:49 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, FREQUENCY: level 1, STATE: possibly fixed in native automation
