### ISSUE TITLE
Browser not closing after tests are run on Arch Linux

### ISSUE THREAD

**Issue by fiws** [DevExpress/testcafe#1670] opened 2017-08-04 10:23 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Any Browser stays open after the tests are run. (Show "Disconnected)

### What is the expected behavior?
The Browser window should close

### How would you reproduce the current behavior (if this is a bug)?
Just run any testcafe tests

### Specify your

* operating system: Arch Linux (Gnome Desktop on Wayland)
* testcafe version: 0.17.0
* node.js version: 8.2.1

Is there anyway I can debug this further?

**Comment by AndreyBelym** [comment] 2017-08-04 11:23
Hello @fiws, unfortunately we do not fully support Wayland now: https://github.com/DevExpress/testcafe-browser-tools/issues/123. We'll fix the problem in `testcafe-browser-tools` and then it will be fixed here. As a workaround, have you installed the [xorg-server-xwayland](https://www.archlinux.org/packages/?name=xorg-server-xwayland) package?

**Comment by fiws** [comment] 2017-08-04 12:54
Thanks for the fast feedback. Yep I got `xorg-server-xwayland` installed.

**Comment by AndreyBelym** [comment] 2017-08-10 11:21
Hello again, do you have `xorg-xwininfo` installed?

**Comment by fiws** [comment] 2017-08-10 15:57
Hi. No, but i just installed it and rebootet. Still the same result.

**Comment by watermelonjuice** [comment] 2017-08-13 13:24
I can confirm this problem exists in xorg and xvnc and is unrelated to wayland.

**Comment by AndreyBelym** [comment] 2017-08-14 07:17
Hello @watermelonjuice, can you provide the output of `pacman -Q` and note what window manager/desktop environment do you use? Currently we need `xwininfo` utility installed + EWMH-compatible window manager (https://en.wikipedia.org/wiki/Comparison_of_X_window_managers). Also I didn't get about headless chrome, it shouldn't have visible windows at all.

**Comment by AndreyBelym** [comment] 2017-08-14 07:21
Also as I see Gnome Shell on Wayland still lacks EWMH-support, so it may be the reason why it doesn't work. BTW, I found that installing `xorg-server-xwayland` is not enough, it should be enabled in Wayland config: https://wiki.archlinux.org/index.php/wayland#XWayland

**Comment by watermelonjuice** [comment] 2017-08-14 22:03
In headless chrome the process remains running. 

https://gist.github.com/watermelonjuice/bba06fb22848fd20cc92c52790803d89

**Comment by AndreyBelym** [comment] 2017-08-15 10:33
@watermelonjuice, please install `xorg-xwininfo` package. I've created a separate issue about headless Chrome: https://github.com/DevExpress/testcafe/issues/1700. If you don't mind, can you please try to terminate Chrome (`killall chrome`) and then run tests in Headless Chrome again, and check process existence (`ps aux|grep [Cc]hrome`).

**Comment by watermelonjuice** [comment] 2017-08-16 10:08
In headless chromium, the process stays alive even after installing xorg-xwininfo.

In regular chromium, the process stays alive even after installing xorg-xwininfo. Running xfce4 in xvnc.

Please note, I am using chromium not chrome in case that makes a difference.

**Comment by patrikmolsson** [comment] 2017-09-03 11:55
By installing xorg-xwininfo the issue was resolved for me. 

Using google-chrome (not chromium), i3 and xorg.

**Comment by watermelonjuice** [comment] 2017-09-03 12:36
btw, if SIGINT is sent to testcafe process the browser is also killed.

**Comment by varunkumar** [comment] 2017-09-05 07:46
I am facing the same problem in RedHat. Close, resize and screenshot functionalities are not working.

```bash
$uname -r 
3.10.0-514.26.2.el7.x86_64

$lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.3 (Maipo)
Release:        7.3
Codename:       Maipo
```

**Comment by AndreyBelym** [comment] 2017-09-05 08:08
@varunkumar, do you use Xvfb / X11 / Wayland? What Desktop Environment do you use?

**Comment by varunkumar** [comment] 2017-09-05 08:42
I use X11 forwarding with putty.

**Comment by AndreyBelym** [comment] 2017-09-05 09:12
X11 Forwarding is not supported, browsers and X11 server should be started on the same machine with TestCafe.

**Comment by varunkumar** [comment] 2017-09-05 09:18
Thanks, it was indeed an issue with X11 forwarding. Connected to the same machine and the browser got closed fine.

**Comment by roman-udka** [comment] 2017-12-06 00:04
I have got  same issue on Mac OS
![image](https://user-images.githubusercontent.com/5123370/33637452-bb2d495e-da29-11e7-9235-d39efe4af8c1.png)

**Comment by graeme-plangrid** [comment] 2018-03-21 23:47
Hi, checking in on this issue. It seems in my Mac OSX environment, all browser processes (chrome, firefox, safari) stay open after the tests are done running. Is this known, or is there something I'm missing? Thanks.

**Comment by AndreyBelym** [comment] 2018-05-15 12:38
Closed in favor of https://github.com/DevExpress/testcafe/issues/2415

**Closed by AndreyBelym** 2018-05-15 12:38 UTC
Labels: AREA: server, OS: Linux, SYSTEM: browser natives, TYPE: bug
