### ISSUE TITLE
There is no way to set "clipboard-write" permission in headless mode

### ISSUE THREAD

**Issue by serhiiminin** [DevExpress/testcafe#6982] opened 2022-04-15 10:36 UTC
### What is your Scenario?

When running a test scenario that includes a step with copying text to the clipboard in headless mode I get this error: "NotAllowedError: Write permission denied." error. 
The page that I am testing uses [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard)

There is no way to override permission for headless mode.

[This article](https://web.dev/async-clipboard/) may be useful

### What is the Current behavior?

I get an error that says the following
For **chrome:headless**  - "NotAllowedError: Write permission denied."
For **firefox:headless** - "NotAllowedError: Clipboard write was blocked due to lack of user activation."

### What is the Expected behavior?

Text is copied to the clipboard

### What is your public website URL? (or attach your complete example)

No url

### What is your TestCafe test code?

`testcafe chrome:headless`

### Steps to Reproduce

1. Run a test for a page with Clipboard API in the headless mode

### TestCafe version

1.18.1

### Node.js version

16.13.1

### Command-line arguments

testcafe chrome:headless

**Comment by felis2803** [comment] 2022-04-18 15:01
It seems to be a limitation of browsers in headless mode.
I found several mentions of a similar problem from puppeteers, selenium users, and browser extension developers:

* [https://stackoverflow.com/questions/70582863/firefox-extension-clipboard-on-headless-mode-not-working](https://stackoverflow.com/questions/70582863/firefox-extension-clipboard-on-headless-mode-not-working)
* [https://serveanswer.com/questions/headless-puppeteer-hangs-when-querying-navigator-clipboard](https://serveanswer.com/questions/headless-puppeteer-hangs-when-querying-navigator-clipboard)
* [https://localcoder.org/selenium-python-headless-chrome-not-copying-to-clipboard](https://localcoder.org/selenium-python-headless-chrome-not-copying-to-clipboard)
* [https://groups.google.com/g/selenium-users/c/-nxTX4eTbwA](https://groups.google.com/g/selenium-users/c/-nxTX4eTbwA)


In the future, we will think about how to work around this limitation.

**Comment by AndreyBelym** [comment] 2022-11-04 09:57
It's a duplicate of #2668

**Closed by AndreyBelym** 2022-11-04 09:57 UTC
Labels: TYPE: enhancement
