### ISSUE TITLE
File upload problem with Excel Files in Latest Version of Chrome 125 

### ISSUE THREAD

**Issue by ShamaGarg** [DevExpress/testcafe#8198] opened 2024-05-23 13:45 UTC
### What is your Scenario?

Started facing an issue with the end to end tests using Test Cafe. These tests check for cases where we have an upload button that accepts excel files sends it to server. We use setFilesToUpload to mimic this behavior in the test environment.

They used to work fine but with a recent update of [Chrome](https://developer.chrome.com/blog/new-in-chrome-125), these tests suddenly started failing. We have other tests that upload other file types (pdf, json) which are working perfectly fine.

Also, it's only problem with the e2e tests, when we normally check that functionality in the same version of chrome it works fine.

What we have noticed is file size is different when uploaded in test environment than in a real scenario.

### What is the Current behavior?

-

### What is the Expected behavior?

-

### What is the public URL of the test page? (attach your complete example)

-

### What is your TestCafe test code?

-

### Steps to Reproduce

1. -
2.-
3.-

### TestCafe version

3.3.0

### Node.js version

20.9.0

### Command-line arguments

-

### Browser name(s) and version(s)

Chrome 125

### Platform(s) and version(s)

Windows, Ubuntu

**Comment by Jisco** [comment] 2024-05-24 05:17
We have the same problem regardless of the file extension. The upload stream is cut off at 768kb.

**Comment by ShamaGarg** [comment] 2024-05-24 09:17
@ PavelMor25, It's a bit difficult to share working example due to privacy concerns. But as @Jisco also mentioned it looks like its a a normal upload test that is just making either the stream cut off in the latest version of chrome. Is it possible to check that first with a simple upload test with testcafe? Apart from that we are not doing any extra logic, it just takes the excel file and then sends the form data to the server. I have added a simple screenshot of File object that we receive in both cases. 

**Normal** 
![normal_browser_upload](https://github.com/DevExpress/testcafe/assets/135245346/57d67db6-991c-4887-9bed-933656ec9a18)

**TestCafe**
![testcafe_upload](https://github.com/DevExpress/testcafe/assets/135245346/ad19b7a9-e107-4ec6-8ca0-4dc6c206d911)

**Comment by karim-penny** [comment] 2024-05-26 10:58
I face the same issue and looks related to the recent update for chrome version. as issue is not exist in older versions of chrome or firefox

**Comment by karim-penny** [comment] 2024-05-26 11:03
as a work a round I found, you can disable native automation for now and it will work `disableNativeAutomation: true`

**Comment by PavelMor25** [comment] 2024-05-27 08:31
I tried to reproduce the described scenario and did not encounter any issues.

> It's a bit difficult to share a working example due to privacy concerns.

We understand that there are reasons why you cannot share an example. However, the [article](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue) describes how to create a minimal working example while avoiding the use of any private information that cannot be published. Additionally, if there is any information that can help us reproduce the issue, please share it.

My example:
```javascript
import { Selector, ClientFunction } from 'testcafe';
import fs from 'fs';

let fileSize = 0;

fs.stat('./upload/stats.xlsx', (err, stats) => {
    if (err) {
        console.error(err);
        return;
    }

    fileSize = stats.size;
});

const getSizeUploadFile = ClientFunction(() => document.querySelector('#file').files[0].size)

fixture `Upload`
    .page `./index.html`;

test('Upload the file', async t => {
    const finput = Selector('#file')
    
    await t.setFilesToUpload(finput,'stats.xlsx')

    const uploadSize = await getSizeUploadFile();

    await t.expect(uploadSize).eql(fileSize)
});
```

**Comment by Jisco** [comment] 2024-05-27 09:51
Sorry, but in our case it's a bit more complicated. 

We use a.Net 6 core server as a backend and to execute the tests we use the json files generated by TestCafe Studio. So we didn't write the test by hand, maybe that helps in any way.

**Comment by Gandhi11** [comment] 2024-05-27 20:23
Same problem on my side, all the upload tests are falling in Latest Version of Chrome 125 with native-automation.

When using `--disable-native-automation` it is working.

**Comment by PavelMor25** [comment] 2024-05-28 09:17
>So i could share the backend code with you, but as already said it works "in the real world" but not when executing the tests.

We need a complete application and test where this issue is reproduced so we can investigate it. If you can share the test or create a reproducible example, it will be very helpful.

>The file needs to be larger than 768kb to fail, was your test file large enough?!

My test file is 10MB.

Additionally, please specify the following information:

- Node.js version
- TestCafe version
- OS version
- Any other relevant information that might help us.

**Comment by ShamaGarg** [comment] 2024-05-28 09:28
> We need a complete application and test where this issue is reproduced so we can investigate it

@PavelMor25 Its not possible to do that, also we are close to our release so difficult for now to work on a shareable test/reproducible example for now.

> Additionally, please specify the following information:

Node.js version: **20.9.0**
TestCafe version: **3.3.0**
OS version: **Windows 10, but we also faced this on Ubuntu which we use on our CI/CD** 
Any other relevant information that might help us.: **What we could notice is something wrong with file data, it changes so better not only look for size but other properties that are being sent and try to see what changes when sent in normal browser vs test cafe.**

**Comment by Jisco** [comment] 2024-05-28 09:58
@PavelMor25 

> We need a complete application and test where this issue is reproduced so we can investigate it. If you can share the test or create a reproducible example, it will be very helpful.

This is our backend code. The first stream here has always 786kb, no matter how large the file is.
```
[HttpPost("api/BackupManagement/BackupFile/{name}")]
[RequestFormLimits(ValueLengthLimit = Int32.MaxValue, MultipartBodyLengthLimit = Int64.MaxValue, MemoryBufferThreshold = Int32.MaxValue)]
[RequestSizeLimit(100_000_000_000)]
[MultipartFormData]
[DisableFormValueModelBinding]
public async Task UploadAsync(String name, CancellationToken cancellationToken)
    {
        var fileIdentifier = Guid.NewGuid().ToString();

        try
        {
            var streams = Request
                .ReadSectionsAsync(ModelState, cancellationToken)
                .Select(x => x.Stream);

          using (var targetStream = File.Open(name, FileMode.Create, FileAccess.Write))
          {
              await foreach (var sourceStream in streams)
              {
                  await sourceStream.CopyToAsync(targetStream, cancellationToken);
              }

              targetStream.Close();
          }

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            return;
        }
        catch (Exception ex)
        {
            return BadRequest(ModelState);
        }
    }
```

In frontend we used TestCafe Studio to produce the test and in code we simply use the [angular devextreme file-uploader component](https://js.devexpress.com/Angular/Documentation/ApiReference/UI_Components/dxFileUploader/).

Node.js version: 18.18.2
TestCafe version: 3.4.0 we tried 3.6.0 but it makes no difference
OS version: Windows 11, Windows Server 2022

**Comment by PavelMor25** [comment] 2024-05-29 08:46
Since we haven't been able to reproduce the issue yet, we ask you to try this workaround. If it helps, it will assist us in addressing the issue.

Add a custom action to your configuration file:
```javascript
// .testcaferc.js
module.exports = {
    customActions: {
     async uploadFileNativeAutomation (selector, file) {
        const cdpClient  = await this.getCurrentCDPSession(); // for TestCafe version lower 3.6.0 use this.testRun.browserConnection.getNativeAutomation()._client
        const { root }   = await cdpClient.DOM.getDocument();
        const { nodeId } = await cdpClient.DOM.querySelector({
            nodeId: root.nodeId, 
            selector
        })

        await cdpClient.DOM.setFileInputFiles({
            files: [file], 
            nodeId
        })
      }, 
    }
};
``` 

Use this action in your test instead of the `setFilesToUpload` action:

```javascript
// test.js
import path from 'path';

fixture `Upload`
    .page `https://page.test`;

test('Upload the file', async t => {
// code
    await t.customActions.uploadFileNativeAutomation(
        '#file', 
        path.join(__dirname,'./file1.txt') // path to file must be absolute
    );
// code
});
``` 

Please let us know your results.

**Comment by Gandhi11** [comment] 2024-05-29 13:00
I just tried it out and the same problem occurred.

Here's the header of a WORKING file upload XHR request made via Chrome directly.
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 9667
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryBpjhnMLnFCMcjVgW
Cookie: REDACTED
Host: REDACTED
Origin: REDACTED
Referer: REDACTED
Sec-Ch-Ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
```

NOT WORKING file upload XHR request made via Chrome with testcafe.
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 5953
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarygufuFBG0T8nofzwb
Cookie: REDACTED
Host: REDACTED
Origin: REDACTED
Referer: REDACTED
Sec-Ch-Ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
```

The main difference as you can see is that the Content-Length get truncated to 5953.

**Comment by ShamaGarg** [comment] 2024-05-29 13:04
Hi @PavelMor25,

I tried with the above workaround and got this error, hope this might be helpful for you in investigating it further:

![image](https://github.com/DevExpress/testcafe/assets/135245346/c74f8792-db98-4838-b76c-35888ec41ba8)
![image](https://github.com/DevExpress/testcafe/assets/135245346/8fcb02e1-4fca-49f8-89be-af5f616c9c02)
![image](https://github.com/DevExpress/testcafe/assets/135245346/b608c165-c370-45cb-a22c-26b508ddd7e9)

**Comment by michailtsiropoulos** [comment] 2024-05-30 08:11
Hello, I am working on the same team with @ShamaGarg. Additionally, I would like to inform you that this issue can also be reproduced manually on the Chrome browser of testCafe after unlocking the browser when the test fails. This problem occurs only on the browser tab that the test runs, not if we open a new tab.

**Comment by PavelMor25** [comment] 2024-05-30 12:16
Unfortunately, we didn't manage to reproduce the issue. As soon as we receive a reproducible example, we will start working on it immediately. We understand the importance of this issue and are actively trying to find a way to replicate it so we can investigate and resolve it.

**Comment by Gandhi11** [comment] 2024-05-31 00:42
@PavelMor25 I was able to make a small repo to help you guys solving the problem. 

Please have look at https://github.com/Gandhi11/testcafe-test and let me know if you have any questions.

The `.env` file committed to help you with the configuration.

**Comment by Bayheck** [comment] 2024-06-04 09:57
Hello,

Thank you for sharing the sample.

For some reason, I get the following error after trying to run ./vendor/bin/sail migrate:

![image](https://github.com/DevExpress/testcafe/assets/67043367/ede995a8-10a6-43cb-a952-b8c4e48af010)

Could you please check it?

In addition, it will be easier for us to work on the issue if the sample setup is as simple as possible. This is because we need to reproduce the issue as well as investigate it.

**Comment by Gandhi11** [comment] 2024-06-04 12:01
Hi @Bayheck, I made a typo in the command. I am sorry for that. It should be `./vendor/bin/sail artisan migrate`.

I understand that a simple setup is the better, but in this case you guys need to have a backend to retrieve and store the uploaded file. That is why I provided you with a Laravel Sail setup. It may be possible to achieve the same result with a nodejs backend but I am not in the position to do so.

**Comment by Bayheck** [comment] 2024-06-19 08:48
Hello, we have created a fix for this issue. Could you please check your tests with this build?

[https://github.com/Bayheck/Builds/blob/main/testcafe-3.6.1.tgz](https://github.com/Bayheck/Builds/blob/main/testcafe-3.6.1.tgz)

I look forward to your results.

**Comment by gforepsly** [comment] 2024-06-21 07:34
> Hello, we have created a fix for this issue. Could you please check your tests with this build?
> 
> https://github.com/Bayheck/Builds/blob/main/testcafe-3.6.1.tgz
> 
> I look forward to your results.

I had the same exact issue, and now when I ran the test with this build - it seems ok! The upload worked, and my tests is green :) 
When can we expect this to be in the official version we can download using NPM/Yarn?

**Comment by michailtsiropoulos** [comment] 2024-06-24 09:40
> fix for this issue. Could you pleas

Hello, the fix is also working for our team. Thank you!

**Comment by Bayheck** [comment] 2024-06-24 10:08
Hello, 

Thank you for testing the build.

Unfortunately, we cannot give an ETA on when we will introduce this fix. If everything goes as planned, it will be in the next TestCafe release.

**Closed** 2024-06-27 06:14 UTC
Labels: TYPE: bug
