### ISSUE TITLE
Can't login using Role with keycloak

### ISSUE THREAD

**Issue by Juansasa** [DevExpress/testcafe#5684] opened 2020-11-05 19:58 UTC
### What is your Test Scenario?

 Use Role to login
### What is the Current behavior?

 Page wont load correctly
### What is the Expected behavior?

 Should redirect to login page and perform login
### What is your web application and your TestCafe test code?

<details>
<summary>Your website URL (or attach your complete example):</summary>
` https://dev.cloud.stakater.com
`</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

```
const powerUser = Role("https://dev.cloud.stakater.com", async (t) => {
  await t
    .typeText(Selector("input[name='realm']"), "stakater-test", { paste: true })
    .click(Selector("button").withExactText("LOGIN"))
    .typeText(Selector("input[name='username']"), "sro-readonly")
    .typeText(Selector("input[name='password']"), "test12")
    .click(Selector("input[type='submit']"));
});

fixture`Test`.beforeEach(async (t) => {
  await t.navigateTo("https://dev.cloud.stakater.com/#/clusters").useRole(powerUser);
});

test("should display existing clusters", async (t) => {
  const rows = Selector("tbody tr");

  await t.expect(rows.count).lt(1);
});

```

</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Ogurecher** [comment] 2020-11-06 07:59
@Juansasa, Thank you for your report. I reproduced the issue, we'll update this thread once it's fixed.

**Comment by wirk** [comment] 2021-03-17 13:06
I would like to follow in on this bug. Not sure if this refers to the same issue but we are also using keycloak with a Vue.js 2 application (with check-sso). It worked great as long as we didn't switch roles during a test. Now while refactoring some of the tests I tried to switch roles and kept getting a redirect loop after changing the role (the first one worked fine). Also, `preserveUrl: true` had never worked for us. I figured out that if the application was already loaded prior to switching roles, the redirect back to the previous page after login fails. It would redirect to `our.app/path/wherever-i-picked-off-before-role-switch`, and then the keycloak plugin would kick in and reload the page, but with a fragment identifier (#state=xxx&session_state=yyy...). For unknown reasons, this resulted in an endless loop of page reloads alternating between the versions with and without the fragment identifier. There were no errors in the console. 

What ended up working was to set the redirectUrl to 'about:blank' on the role object after it was initialized. That is fine for us because our tests already call `navigateTo()` after each role switch.


```js
function initializeRole(credentials) {
    let role = Role(getKeycloakUrl(), async t => {
        await t
            .expect(Selector('.page-title').textContent).contains('Anmelden', {timeout: 10000})
            .typeText('#username', credentials.username)
            .typeText('#password', credentials.password)
            .click('#kc-login')
    }, {preserveUrl: false})

    role.once('initialized', () => {
        // this is what fixed the redirect loop
        role.redirectUrl = 'about:blank'
    });

    return role
}


function getKeycloakUrl() {
    const params = new URLSearchParams({
        client_id: keyCloakConfig.clientId,
        redirect_uri: config.baseUrl,
        state: uuid(),
        nonce: uuid(),
        response_mode: 'fragment',
        response_type: 'code',
        scope: 'openid',
        kc_locale: 'de'
    })

    return `${(keyCloakConfig.url)}/realms/${(keyCloakConfig.realm)}/protocol/openid-connect/auth?${params.toString()}`
}
```

**Comment by arubtsov** [comment] 2021-03-18 08:26
@wirk, thank you for reaching out to us and sharing your workaround.

```
It worked great as long as we didn't switch roles during a test.
```

Could you please try using the [--disable-page-cashing](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--disable-page-caching) option?

```
Also, preserveUrl: true had never worked for us.
```

Could you please share a minimal example so we can research the issue?

**Comment by wirk** [comment] 2021-03-18 08:51
@arubtsov thank you for your help,  --disable-page-cashing  worked great! I also just verified it with `preserveUrl: true`, that also works with the flag, otherwise I would have ended up in a redirect loop after navigating. Now I can even switch back and forth to a rule that I used earlier in the same test, which did not work before with my workaround. 

Let me know if I can be of any more help.

**Comment by miherlosev** [comment] 2021-12-15 11:43
Hi @wirk 

I will close this issue because the combination of the `--disable-page-caching` and `preserveUrl: true` options helps fix it.

**Closed by miherlosev** 2021-12-15 11:43 UTC
Labels: TYPE: bug, FREQUENCY: level 1
