### ISSUE TITLE
Non Responsive Ui Button 

### ISSUE THREAD

**Issue by Devdatt-Joshi** [DevExpress/testcafe#8127] opened 2024-01-23 10:46 UTC
### What is your Scenario?

Verify weather user is able to Login To the Portal

### What is the Current behavior?

User is not Able to login to the portal because login button is not getting pressed

### What is the Expected behavior?

user is able to login and "Login" button got is clicked.

### What is the public URL of the test page? (attach your complete example)

I have written a test case in this test case we are logging to our portal but Login button is non responsive now.
Initially is was working but from last 5 days i am observing the same. I am Blocked with the further execution because initial stage itself is not working. even when we press this "Login" Button on screen displayed in test cafe screen its not working.
But this Button is working on my local on same browser having same version, only when i am running this test case from TestCafe Its failing.
URL : https://qa-rapidquoteui-appservice.azurewebsites.net/app/dashboard 

### What is your TestCafe test code?

await t.wait(10000);

await t.click(Selector('button[class="MuiButtonBase-root MuiButton-root MuiButton-contained jss40 MuiButton-containedPrimary"][type="submit"]'));
 
await t.wait(10000);
<img width="775" alt="image" src="https://github.com/DevExpress/testcafe/assets/157480794/259c0fd7-0b29-4160-a0a2-940b9a74c493">

### Screenshots

<img width="775" alt="image" src="https://github.com/DevExpress/testcafe/assets/157480794/4816cb58-6e90-47a5-83d8-af5033b6f21e">

### Steps to Reproduce

1.Open https://qa-rapidquoteui-appservice.azurewebsites.net/app/dashboard
2.Click on Login Button

### TestCafe version

3.3.0

### Node.js version

v20.10.0

### Command-line arguments

testcafe chrome .\App_Process.js

### Browser name(s) and version(s)

Chrome 120.0.0.0

### Platform(s) and version(s)

 Windows 11

### Other

the button is clickable manually but not clickable using Test cafe.

**Comment by PavelMor25** [comment] 2024-01-25 06:44
Hello @Devdatt-Joshi, I was able to reproduce the issue. 
Could you please elaborate on why you are running your test in proxy mode? Native automation resolves the issue.

**Comment by Devdatt-Joshi** [comment] 2024-01-31 12:25
i have changed the setting also tried with settings>>Bypass proxy for>> but not working getting same issue

**Comment by PavelMor25** [comment] 2024-02-02 06:46
Hello @Devdatt-Joshi,

The option to disable proxy mode is planned for the next TestCafe Studio update. Please stay tuned for updates. Unfortunately, there is currently no solution or workaround to the issue in TestCafe Studio.

Since this issue is reproducible only in TestCafe Studio, I'll close the issue as it works as expected in TestCafe with native automation mode.

**Closed by PavelMor25** 2024-02-02 06:46 UTC
Labels: TYPE: bug, STATE: Need response
