### ISSUE TITLE
SyntaxError on valid Javascript: `SyntaxError: Unexpected token ','` or `missing ) after for-loop control`

### ISSUE THREAD

**Issue by AndersCan** [DevExpress/testcafe#5459] opened 2020-08-26 09:43 UTC
### What is your Test Scenario?

HTML file that includes the following script:

```js
new Promise(() => {
  var s = [1];
  for (var i of (console.log(s), s)) {
  }
  for (var a of s) {
    var d = 'hello';
    this[d];
  }
});
```

### What is the Current behavior?

TestCafe fails with JS errors:

> Browser: Firefox 78.0 / Linux 0.0:
> JavaScript error details:
> missing ) after for-loop control

> Browser: Chrome 83.0.4103.116 / Linux 0.0
> JavaScript error details:
> SyntaxError: Unexpected token ','

### What is the Expected behavior?

Valid JS should not fail TestCafe

### What is your web application and your TestCafe test code?

[Minimal Repo](https://github.com/AndersCan/testcafe-bug)

<details>
<summary>Your website URL (or attach your complete example):</summary>

https://github.com/AndersCan/testcafe-bug

</details>

<details>

<summary>Your complete test code (or attach your test files):</summary>

```js
fixture`Will not fail`.page`http://localhost:7777/index-without-poison.html`;

test(`Should not fail before testrun with 'SyntaxError: Unexpected token ','`, async (t) => {
  await t.expect(true).eql(true);
});

fixture`Will fail with JavaScript/SyntaxError`
  .page`http://localhost:7777/index-with-poison.html`;

test(`Should not fail before testrun with 'SyntaxError: Unexpected token ','`, async (t) => {
  /**
   * Browser: Firefox 78.0 / Linux 0.0:
   * JavaScript error details:
   *   missing ) after for-loop control
   *
   * Browser: Chrome 83.0.4103.116 / Linux 0.0
   *  JavaScript error details:
   *  SyntaxError: Unexpected token ','
   */
  await t.expect(true).eql(true);
});
```

</details>

<details>

<summary>Your complete test report:</summary>

```
> testcafe-bug@1.0.0 test /home/anderscan/git/testcafe-bug
> testcafe all test.js

 Running tests in:
 - Firefox 78.0 / Linux 0.0
 - Chrome 83.0.4103.116 / Linux 0.0

 Will not fail
 ✓ Should not fail before testrun with 'SyntaxError: Unexpected token ','

 Will fail with JavaScript/SyntaxError
 ✖ Should not fail before testrun with 'SyntaxError: Unexpected token ','

   1) A JavaScript error occurred on "http://localhost:7777/index-with-poison.html".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable
      tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      SyntaxError: Unexpected token ','

      Browser: Chrome 83.0.4103.116 / Linux 0.0


   2) A JavaScript error occurred on "http://localhost:7777/index-with-poison.html".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable
      tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      missing ) after for-loop control
          No stack trace available

      Browser: Firefox 78.0 / Linux 0.0



 1/2 failed (1s)
```

</details>

### Steps to Reproduce:

1. Clone https://github.com/AndersCan/testcafe-bug
2. `npm i`
3. `npm run start`
4. `npm run test`
5. See the error

### Your Environment details:

- testcafe version: 1.9.1 
- node.js version: v12.16.1 
- command-line arguments: `npx testcafe all test.js` 
- browser name and version: Firefox 78.0, Chrome 83.0.4103.116 
- platform and version: Linux Pop!\_OS 20.04 LTS (basically Ubuntu 20.04)

**Comment by Ogurecher** [comment] 2020-08-27 07:30
@AndersCan, Thank you for your report. I've reproduced this issue using the repository you shared. We'll need time to investigate this issue. In the meantime, you can run TestCafe with `--skip-js-errors` to disable these errors.

**Comment by wentwrong** [comment] 2021-06-07 15:47
The problem isn't reproducible with the latest TestCafe release (`v1.14.2` for now), so I am closing the issue. Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2575.

**Closed by wentwrong** 2021-06-07 15:47 UTC
Labels: TYPE: bug
