### ISSUE TITLE
testcafe does not scroll to element if it is hidden by fixed

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#2391] opened 2018-05-11 06:08 UTC
### Are you requesting a feature or reporting a bug?
a bug
### What is the current behavior?
testcafe does not scroll to element if it is hidden by fixed
### What is the expected behavior?
should scroll until it element is visible

#### Provide the test code and the tested page URL (if applicable)

Tested page:
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <style>
        #fixed {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            height: 300px;
        }

        #fixed div {
            width: 100%;
            height: 100%;
            background-color: red;
        }

        button {
            margin-top: 500px;
        }
    </style>
</head>
<body>
    <div style="height: 9000px">
        <button onclick="onClick()">Click me</button>
        <div id="result"></div>
    </div>
    <div id="fixed">
        <div></div>
    </div>
    <script type="text/javascript">

        function onClick () {
            document.getElementById('result').innerHTML = 'success';
        }

        setTimeout(function () {
            window.scrollTo(0, 5000);
        });
    </script>
</body>
</html>

```
Test code

```js
test('test', async t => {
    await t
        .click('button')
        .expect(Selector('#result').innerText).eql('success');
});


```

**Comment by AndreyBelym** [comment] 2018-05-15 12:06
Duplicate of #1057

**Closed by AndreyBelym** 2018-05-15 12:06 UTC
Labels: SYSTEM: automations, TYPE: bug
