### ISSUE TITLE
TestCafe could not able to open the Browser

### ISSUE THREAD

**Issue by jalaiahcyg** [DevExpress/testcafe#7955] opened 2023-08-19 14:40 UTC
### What is your Scenario?

I am getting an error when I am trying to run the TestCafe code, but could not able to open the browser
**ERROR :** 
Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:
- chrome

Hints:
- Increase the Browser Initialization Timeout if its value is too low (currently: 2 minutes for local browsers and 6 minutes for remote browsers). The timeout determines how long TestCafe waits for browsers to be ready.
- The error can also be caused by network issues or remote device failure. Make sure that your network connection is stable and you can reach the remote device.

### What is the Current behavior?

TestCafe could not able to open the browser

### What is the Expected behavior?

TestCafe should open the browser and complete the tests

### What is your public website URL? (or attach your complete example)

I am thinking no URL is required for solving the browser issue

### What is your TestCafe test code?

I am thinking testcode is not required for resolving the browser issue

### Your complete configuration file

{
    "browsers":["chrome"],
    "skipJsErrors":true,
    "reporter":[
        {
            "name":"spec"
        },
        {
            "name":"jenkins",
            "output": "reports/jenkinsReport.xml"
        },
        {
            "name": "html",
            "output": "reports/report.html"
        }
    ],
    "concurrency":1,
    "selectorTimeout": 90000,
    "assertionTimeout": 30000,
    "pageLoadTimeout": 90000,
    "speed":1,
    "quarantineMode": false,
    "screenshots":{
        "path":"reports/screenshots",
        "takeOnFails": true,
        "fullPage": true
    },
    "videoPath": "reports/videos",
    "videoOptions": {
        "singleFile": false,
        "failedOnly": true
    }
}

### Screenshots

![image](https://github.com/DevExpress/testcafe/assets/71423479/658775bf-bf98-40a6-8a57-fbfca3c0ce39)

### Steps to Reproduce

1.With the versions of Node, testcafe and chrome, please try to reproduce the issue
2.
3.

### TestCafe version

3.2.0

### Node.js version

20.4.0

### Command-line arguments

npm run <Script name>

### Browser name(s) and version(s)

Chrome 104.0.5112.101

**Comment by AlexKamaev** [comment] 2023-08-21 08:29
Hi @jalaiahcyg,

Try changing the browser name to `"browsers":["chrome --no-sandbox"]` and let us know about your results (Google Chrome cannot be started normally under the `root` user due to security reasons).

**Comment by jalaiahcyg** [comment] 2023-08-24 18:07
Hi @AlexKamaev 

Thank you.
Tried by changing this "browsers":["chrome --no-sandbox"]. Now I could able to run the tests. 

One thing I observed is that, I could not able to view the browser window which will be opened while running the tests

Attached a small video showing the issue

[screen-capture (40).webm]

**Comment by AlexKamaev** [comment] 2023-08-25 08:05
Hello,
The video is not available. Please upload it again.

**Comment by jalaiahcyg** [comment] 2023-08-25 08:25
Uploading the video 
[screen-capture (40).webm](https://github.com/DevExpress/testcafe/assets/71423479/455e242e-b59f-4003-b7be-11dc2a7cf3c5)

Can you please check now

**Comment by AlexKamaev** [comment] 2023-08-28 08:12
I watched the video and found that you are using a custom runner: `test-jRunner`. Moreover, I noticed the following error:

![error](https://github.com/DevExpress/testcafe/assets/1678902/8dc92e03-3877-43f6-bb21-f7f9ce17582b)

So, I suppose that the cause of the issue is in that custom code, but not in TestCafe.
I'll close the issue. If you have any questions, feel free to ask them in this thread.

**Closed by AlexKamaev** 2023-08-28 08:12 UTC
Labels: TYPE: bug, STATE: Need response

**Comment by jalaiahcyg** [comment] 2023-08-30 16:42
Hi @AlexKamaev 

I resolved the issue with in my code, Browser is getting opened but I cant see the stuff that is running on the browser.
It is like kind of invisible.

Attached a video 
[screen-capture (42).webm](https://github.com/DevExpress/testcafe/assets/71423479/81400324-a088-4fb4-9d43-5159b8de0b5c)

**Comment by AlexKamaev** [comment] 2023-08-31 07:34
It is unclear from the video if the test passes or fails. Please clarify if you encounter any error because of this behavior.

**Comment by jalaiahcyg** [comment] 2023-08-31 09:09
Even I could not able to figure out whether the test cases are running or failing. 

I could not see any errors in the test cases, but for some reason the chrome browser could not able to show anything

Is there any solution that chrome browser show as normal during the execution of test case ?

**Comment by AlexKamaev** [comment] 2023-09-04 06:43
We never encountered such an issue. I can only assume that it occurs because you are not using the latest version of Chrome (according to your initial post). If so, please update your browser.

Also, run TestCafe with the Debug option to get a full log. Please refer to the following help topic for more details: [Related Questions](https://testcafe.io/documentation/402636/faq/general-info#related-questions).

See this example from our documentation:

```
set DEBUG=testcafe:*,hammerhead:*
testcafe chrome index.js 2> testcafe.log
```

Please note that ways to set environment variables may vary in different terminals.
