### ISSUE TITLE
Error on executing more than 150 testcases in a suite

### ISSUE THREAD

**Issue by dirasangtani** [DevExpress/testcafe#4054] opened 2019-07-22 13:57 UTC
### Are you requesting a feature or reporting a bug?

bug

### What is your Test Scenario?

I am planning to create a regression test suite using testcafe. I have created 3-4 test cases using page-object pattern. I created multiple copies of the test cases to have around 200 TC files. I am able to run the test cases individually. I am able to run the test cases(copies) when the count is 150. when the count increases to ~175, the error is thrown. I have allocated 8GB, 10GB, 12GB to the node application.

### What is the Current behavior?

Error is thrown as below:
`PS C:\javelin> node  --max-old-space-size=8192 .\test-runner.js
Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
    at BrowserSet._waitConnectionsOpened (C:\javelin\node_modules\testcafe\src\runner\browser-set.js:84:30)
    at pinkie_1.default.resolve.then (C:\javelin\node_modules\testcafe\src\runner\browser-set.js:107:35)
    at invokeCallback (C:\javelin\node_modules\pinkie\index.js:60:12)
    at Array.forEach (<anonymous>)
    at publish (C:\javelin\node_modules\pinkie\index.js:147:32)
    at Array.publishFulfillment (C:\javelin\node_modules\pinkie\index.js:152:2)
    at Immediate.asyncFlush (C:\javelin\node_modules\pinkie\index.js:17:19)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)`

### What is the Expected behavior?

Test cases should run smoothly

### How would you reproduce the current behavior (if this is a bug)?

Create any test case using page-object pattern, create 200 copies of that test case and execute.

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 testcafe - 1.2.1
node.js - 10.16.0
command - node testrunner.js [testrunner attached in txt form]
browser - chrome
platform : Windows 10

[test-runner.txt](https://github.com/DevExpress/testcafe/files/3417743/test-runner.txt)

* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Dmitry-Ostashev** [comment] 2019-07-23 10:23
Hello. I was unable to reproduce this issue. Could you please provide a sample test file with the page model? Also, please send us your test web page (or a public url to it) that illustrates this behavior.

**Comment by arubtsov** [comment] 2019-07-30 08:25
I was able to reproduce the issue with 300 copies of the test file (refer [T800277](https://supportcenter.devexpress.com/internal/ticket/details/T800277)). We will need additional time to research it in detail.

**Comment by AlexKamaev** [comment] 2019-08-08 09:50
@dirasangtani 
I researched your project and found that creating a page model object takes some time. Since you have more that 150 files and huge page model objects, it leads to the error.
I recommend you reorganize your code in the following manner:
- do not export the constructor of a page model, export a new instance;
- do not use the `new` keyword in your test files.

Please see the modified example:
- login-page.js
```JS
import { Selector } from 'testcafe';
import { t } from 'testcafe';

class LoginPage{
	constructor(){
		this.username = Selector('#ctl00_ctl00_RightContent_RightContent_usr');
		this.password = Selector('#ctl00_ctl00_RightContent_RightContent_pwd');
		this.submit = Selector('#ctl00_ctl00_RightContent_RightContent_login');
	}

	async sdLogin(name, pwd){
		await t
			.typeText(this.username, name)
			.typeText(this.password, pwd)
			.click(this.submit)
	}
}

export default new LoginPage();
```
- tc041.js
```JS
import loginPage from '../../main/page-objects/screening-direct/login-page.js'
// const loginPage = new LoginPage(); // NOTE: comment this line
```
Please modify all you page models in this manner. This should improve execution time significantly. 
If this approach is not suitable for you, let us know.

**Comment by dirasangtani** [comment] 2019-08-14 09:13
@AlexKamaev This code optimization worked well. Appreciate it.

**Comment by dirasangtani** [comment] 2019-08-21 12:30
@AlexKamaev  Do you recommend any optimal way for defining locators rather than inside a constructor?
There are like hundreds of them on a page.

**Comment by AndreyBelym** [comment] 2019-08-22 14:30
Instead of exporting a page object class (`export default class PageObject { ... }`), you can create an instance of the page object and export it instead:
```js
class PageObject {

}

export default new PageObject();
```

**Comment by josephmcasey** [comment] 2019-10-22 12:18
see https://github.com/DevExpress/testcafe/issues/4306

**Comment by wentwrong** [comment] 2021-06-22 08:08
We've decided to close this issue because the original problem was caused by creating a large number of huge page objects which now can be resolved by either optimizing test code following our recommendations or by increasing the timeout value. Check out the guide with these recommendations on how to optimize your Page Model: [Speed Up Test Execution](https://testcafe.io/documentation/402963/guides/advanced-guides/speed-up-test-execution).

Also, the generic error message when a browser couldn't establish a connection within the timeout was improved - in a case when tests compilation took too long it will show a note which recommends increasing the [browserInitTimeout](https://testcafe.io/documentation/402638/reference/configuration-file#browserinittimeout) value.

**Closed by wentwrong** 2021-06-22 08:08 UTC
Labels: AREA: server, FREQUENCY: level 2, HAS WORKAROUND, TYPE: enhancement, support center
