### ISSUE TITLE
Unable to take a screenshot due to some error

### ISSUE THREAD

**Issue by MargaritaLoseva** [DevExpress/testcafe#669] opened 2016-07-15 14:37 UTC
On Mac, when I run a test via CLI by using the command `testcafe safari tests.js -S -s screenshots`, the report displays the message  _[was unable to take a screenshot due to some error]_.

I don't understand what error occured. And I think, we should specify the exact error in the report (if it is possible).

The same command works correctly on Windows
![screen shot 2016-07-15 at 5 25 45 pm](https://cloud.githubusercontent.com/assets/12034505/16877794/8b3679bc-4ab2-11e6-9481-b151114a55b3.png)

**Comment by inikulin** [comment] 2016-07-15 14:40
We need to expose whole error message here: 
`[Unable to take a screenshot due to error: error message]`

**Comment by inikulin** [comment] 2016-07-15 14:56
I think we should get rid of inline messages. We will give warnings to stderr as suggested in #651. Meanwhile, if error occurs during screenshots saving we should throw test run error

**Comment by inikulin** [comment] 2016-07-15 14:58
Or, better solution: add warnings at the end of report

**Comment by inikulin** [comment] 2016-07-15 15:12
Closing in favor of #671

**Comment by inikulin** [comment] 2016-07-15 15:13
Reopening, since this ticket also above the actual error

**Comment by AndreyBelym** [comment] 2016-07-18 08:18
The actual error was fixed in #643.

**Comment by AndreyBelym** [comment] 2016-07-18 08:57
The error that caused this message was fixed in DevExpress/testcafe-browser-natives#80 and #643.

**Comment by inikulin** [comment] 2016-09-08 15:17
@AndreyBelym Is it fixed?

**Comment by AndreyBelym** [comment] 2016-09-08 15:30
Fixed in DevExpress/testcafe-browser-natives#80 and #643.

**Closed by AndreyBelym** 2016-09-08 15:30 UTC
Labels: AREA: server, OS: Mac, SYSTEM: CLI, SYSTEM: reporting, TYPE: bug

**Comment by moffsugita** [comment] 2018-10-11 02:38
what is `Unable to take a screenshot due to error: error message` message?
never mind?

**Comment by AndreyBelym** [comment] 2018-10-12 08:39
@moffsugita, could you please post the full test report here?

**Comment by AndreyBelym** [comment] 2019-03-28 08:48
This warning means that TestCafe can't remove the browser UI (the address bar, scrollbar) from a captured screenshots. You can ignore it if you don't plan to use the `t.takeElementScreenshot` action. 

It can happen if a browser or TestCafe doesn't support capturing screenshots with debug protocols and can be caused by a number of reasons, for example, unusual DPI settings (`1.5` or `1.75`) and notifications hiding a part of the browser window. 

Recent TestCafe releases can capture screenshots with debug protocols in the most popular browsers (Chrome and Firefox). This method is more robust and shouldn't produce this warning message. If you still can reproduce it with the latest TestCafe release, please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md).
