### ISSUE TITLE
Unexpected Behaviour when content is different to Html

### ISSUE THREAD

**Issue by ognif** [DevExpress/testcafe#4389] opened 2019-10-16 18:14 UTC
Tested on macOS with Chrome Browser

Started Testcafe with a common fixture that always work. In one case there is a backend error and the server will respond a XML instead of HTML.
This will cause Testcafe to work unexpected. NO other command is possible, also not to navigate back to the HTML page. The fixture will get closed after some time and Testcafe will restart this fixture in an infinity loop. 

I reduced the fixture to the lowest needs, to understand better.

````
import { Selector } from 'testcafe';
import fs from "fs";

fixture `SM Run 1`

test('Per Anhalter durch die Galaxies', async t => {

        await t
            .navigateTo("http://www.ifoerster.com/robots.txt")
        await t
            .wait(4000)
        await t
            .expect(fs.fileExistsSync('./downloads/saved.txt'))


        console.log("Fertig")

    });
````

Same with this picture, shows that Testcafe looks to crash internal.

````
import { Selector } from 'testcafe';
import fs from "fs";

fixture `SM Run 1`

test('Per Anhalter durch die Galaxies', async t => {

        await t
            .navigateTo("http://www.ifoerster.com/robots.txt")
            .wait(4000)
        await t
            .navigateTo("http://www.ifoerster.com")


        console.log("Fertig")

    });
````
I can reproduce the behaviour all the time. 
One issue confused me. In Stackoverflow I can find many answers and questions that are marked as solved but also NONE of this "solved" answers is working. It looks to me like a critical bug.

Tested on:
Linux Server
macOS Server
macOS localhost

node 11.14.0 macOS
Lastest Chrome and Safari Browser

**Comment by ognif** [comment] 2019-10-17 07:21
I have edited the issue now and reduced the fixture to reproduce the issue fast.

**Comment by Farfurix** [comment] 2019-10-17 11:07
@ognif 

Hello,

This issue is a duplicate of this one: https://github.com/DevExpress/testcafe/issues/1471. Please track our updates [there](https://github.com/DevExpress/testcafe/issues/1471).

**Closed by Farfurix** 2019-10-17 11:07 UTC
Labels: STATE: Need response
