### ISSUE TITLE
Safari: Uncaught object "[object Object]" was thrown. Throw Error instead.

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#6624] opened 2021-10-18 21:59 UTC
### What is your Test Scenario?

This error occurs on a number of tests... but the easiest one is navigating to a url that redirects. 
 
### What is the Current behavior?

Similar to #6593, I'm getting an uncaught object error in Safari. I'm suppressing JS errors and uncaught errors... but my tests are still failing.
 
### What is the Expected behavior?

I can navigate to the desired page, and no error is thrown once the page loads 

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture('Navigate to petition page, non-promoteable petition').page('https://www.change.org/');

test('Ensure promotion page does not show', async t => {
  await t
    .navigateTo('/p/united-nations-send-matt-damon-to-mars-to-retrieve-opportunity/sponsors/new')
    .expect(Selector('[data-testid="signform-submit-button"]').visible)
    .ok();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "src": "./tests/**/*.js",
  "clientScripts":[
    {
      "module":"axe-core/axe.min.js"
    }
  ],

  "assertionTimeout": 15000,
  "ajaxRequestTimeout": 40000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots",
    "thumbnails": false
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
   1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: Safari 15.0 / macOS 10.15.7
      Screenshot: /Users/rcooper/work/github.com/change/regression-qaa/artifacts/screenshots/test-1/_errors/1.png

```
</details>

<details>
<summary>Screenshots:</summary>

```
https://user-images.githubusercontent.com/37812673/137813141-419be9a1-af3c-4f8e-8bfa-0b7be28b96e8.png
```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:   `1.16.1`                
* node.js version:   `14.16.1`                 
* command-line arguments: `testcafe safari -u`   
* browser name and version: `Safari 15.0` 
* platform and version:  `macOS 10.15.7`       
* other:

**Comment by danieltroger** [comment] 2021-11-22 21:06
Hey,

It's 10pm and I'm still at work because I debugged, I think, this issue. Sorry for this message being bad and stuff I just want to go home.

I'm getting this error in safari: 

```
  1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: Safari 15.1 / macOS 10.15.7
```

I think it is the same issue?

I tracked it down during the last 3 hours:

The service worker on the site sends a payload to the "backend" looking like this

<img width="2160" alt="Screenshot 2021-11-22 at 20 14 10" src="https://user-images.githubusercontent.com/4047180/142933679-0ade132a-6cc2-4e0d-a28e-03d6a65f013f.png">

with `executionError` being an empty object (it's supposed to be null), that makes the backend throw an error.

In the backend, it has a very misleading stack trace pointing essentially to the test code file itself, but that's this one with the head cut off (I think):
<img width="2672" alt="Screenshot 2021-11-22 at 19 27 32" src="https://user-images.githubusercontent.com/4047180/142933721-2a887bf3-b3fc-4e56-b6b7-516fab28baaf.png">

This is because at this place the current place in the code is used if no callstack is recieved from the frontend:
<img width="2672" alt="Screenshot 2021-11-22 at 20 13 59" src="https://user-images.githubusercontent.com/4047180/142933817-dd044d19-3766-4533-a279-bf34fa839db6.png">


On the frontend, the message containing the `executionError` empty object is passed to the service worker by some code reading `sessionStorage`.

On the page load before the load where that is sent, an exception is thrown and written to the sessionStorage.
However, it is not properly serialized - only by `JSON.parse`, which just turns it into an empty object.

Proof:
<img width="508" alt="Screenshot 2021-11-22 at 21 58 19" src="https://user-images.githubusercontent.com/4047180/142934318-a3d9921b-e37f-4ea0-a97e-556bf9fb2283.png">

The actual error has the following  `.stack` property: 
<img width="413" alt="Screenshot 2021-11-22 at 21 58 52" src="https://user-images.githubusercontent.com/4047180/142934388-aa28b866-94da-40d4-9c26-a3427fbf56b6.png">

Reading that stack trace, the error is thrown here:
<img width="2160" alt="Screenshot 2021-11-22 at 21 59 29" src="https://user-images.githubusercontent.com/4047180/142934449-f5001707-9f25-4389-bd91-4f50e53319ae.png">

And originates from here (the call to `Nt`): 
<img width="2160" alt="Screenshot 2021-11-22 at 22 01 38" src="https://user-images.githubusercontent.com/4047180/142934701-f8a353e0-eb92-436c-be2f-84cf86993f3f.png">

Which is this part in the original, unminfied code (`Promise$3`):

<img width="2160" alt="Screenshot 2021-11-22 at 22 02 10" src="https://user-images.githubusercontent.com/4047180/142934766-9d3bdf08-4db3-494a-b933-c1af4e61fca1.png">


This shows us that it's probably a minification error. Something has stripped the `new` keyword, making the call to the `Promise` constructor fail. It's either a bug in the minifier that was used or a configuration mistake.

@Farfurix I would be grateful if you could:
1) Confirm that I have posted this in the correct issue
2) Tell me which minifier you're using and how I can reproduce the builds to try to fix it, alternatively fix it in a timely manner. I think it should be easy for you from now on :)
3) Make proper serialisation of errors going from the frontend to the backend so that nobody has to go through this debugging journey ever again

Thanks <3

**Comment by Farfurix** [comment] 2021-11-23 08:49
@danieltroger 

Hello,

Despite the fact that the error texts are the same, the causes may be different. You can create a new bug report with some [simple example](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue) and a link to this issue or wait for a version with a fix for this issue.

**Comment by danieltroger** [comment] 2021-11-23 12:06
@Farfurix I have ran @rob4629's reproduction case, which failed for me.

Then I have implemented the fix for the bug that I had (adding `new` to the call to the promise constructor (`Nt` in the minified code, see my second to last screenshot)) and the test has passed and works.

This means that it's the same issue.

Could you please reply to my points 2 and 3?

**Comment by danieltroger** [comment] 2021-11-23 13:48
I thought it was a minification issue, but it actually seems to be a mistake in the code here:

https://github.com/DevExpress/testcafe/blob/e4aa7529f3b4c164ce2bbac943a94d210c3c6ec3/src/client/core/barriers/page-unload-barrier.ts#L76

`Promise` should be `new Promise`, no?

**Comment by danieltroger** [comment] 2021-11-23 13:53
It seems to have been introduced by https://github.com/DevExpress/testcafe/pull/6565. @LavrovArtem Did you mean to write `new Promise`? I'd love to hear your thoughts about this :)

**Comment by danieltroger** [comment] 2021-11-23 14:50
I tried to prepare a pull request but I'm failing at creating a test case because it's impossible to install IE11 and I'm running macOS:
`Error: Cannot find the browser. "ie" is neither a known browser alias, nor a path to an executable file.`

But I made a patch instead that you can use to fix the error locally while we're waiting for testcafe @rob4629:

[testcafe_fix_6624.patch.zip](https://github.com/DevExpress/testcafe/files/7588888/testcafe_fix_6624.patch.zip)

Put this into your `package.json`:

```
"resolutions": {
    "testcafe": "patch:testcafe@latest#./patches/testcafe_fix_6624.patch"
  }
```
unzip the file and put it into a folder called `patches` relative to your package.json and run `yarn install`
You might have to replace `latest` in the resolution with whatever version you have pinned of `testcafe`.

Generated with https://yarnpkg.com/cli/patch and works with yarn 3.1.0

**Comment by rob4629** [comment] 2021-11-23 18:18
I'll see if I can create a pull request with your fix, thanks for investigating (and resolving)!

**Comment by Farfurix** [comment] 2021-11-24 07:38
@danieltroger

Hello,

Thank you for your research, we'll review @rob4629's [PR](https://github.com/DevExpress/testcafe/pull/6719).

**Comment by AndreyBelym** [comment] 2021-12-13 12:17
Should be closed by #6719

**Closed by AndreyBelym** 2021-12-13 12:17 UTC
Labels: TYPE: bug, FREQUENCY: level 1

**Comment by danieltroger** [comment] 2022-01-11 15:15
Hey @AndreyBelym, thank you for merging.

Could you also give me an update on this?

> On the page load before the load where that is sent, an exception is thrown and written to the sessionStorage.
However, it is not properly serialized - only by JSON.parse, which just turns it into an empty object.
> I would be grateful if you could:
> Make proper serialisation of errors going from the frontend to the backend so that nobody has to go through this debugging journey ever again

**Comment by miherlosev** [comment] 2022-01-13 08:22
Hi @danieltroger 

> Could you also give me an update on this?
> Make proper serialisation of errors going from the frontend to the backend so that nobody has to go through this debugging journey ever again

The cause of the issue is an internal error. This error was not found earlier due to issues with running TestCafe tests with Safari 15 using [saucelabs](https://saucelabs.com/). So, it's an edge case. If the same error occurs again, we will consider improving error serialization.

**Comment by danieltroger** [comment] 2022-01-13 09:05
Hi @miherlosev,

First off, this issue (missing `new` keyword) occurred when testing in normal Safari, without Saucelabs. How is running tests in safari 15, the most recent Safari version, an edge case?

Secondly, it is naive to assume that you are not going to have any further internal issues in the future. The error serialization issue impacts all browsers and makes debugging of "internal errors" nearly impossible.

**Comment by miherlosev** [comment] 2022-01-14 08:37
We run tests for a [lot of browsers](https://github.com/DevExpress/testcafe/blob/9d7f2f94539f3540f0d86c640ef2db2d1a53b6a1/gulp/constants/client-test-settings.js#L30) using [saucelabs](https://saucelabs.com/).
The edge case is that we cannot run tests in Safari 15 due to the Saucelabs issue. Customers encountered an issue with the missing `new` keyword. We assume that this will not happen again.
Improving error serialization isn't our priority task. So, if you have an idea of how to improve error serialization, the PR is greatly appreciated. See [instructions](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md) on how to contribute in TestCafe.
