### ISSUE TITLE
setNativeDialogHandler and getNativeDialogHistory don't work correctly

### ISSUE THREAD

**Issue by Ivan-Katovich** [DevExpress/testcafe#5994] opened 2021-02-26 14:09 UTC
### What is your Test Scenario?
1) Open any site with native dialogs
2) Handle a dialog with **t.setNativeDialogHandler**
3) Receive dialog history with **t.getNativeDialogHistory**
 
### What is the Current behavior?
1) Dialog is skipped by default 
2) Dialog is not handled by t.setNativeDialogHandler
3) Dialogue history is empty.
 
### What is the Expected behavior?
1) Dialog is shown if no handlers 
2) Dialog is not shown if any handler returns true
3) Dialog is present in the history (in results of t.getNativeDialogHistory) 
 

### Steps to Reproduce:
1) Open any site with native dialogs
2) Handle a dialog with **t.setNativeDialogHandler**
3) Receive dialog history with **t.getNativeDialogHistory**
 
### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    12.18.1
* browser name and version: firefox latest, chrome latest
* platform and version:          Windows 10 Enterprise
* platform and version:          
* other:

**Comment by Dmitry-Ostashev** [comment] 2021-03-01 11:38
I was unable to reproduce the issue by the described steps. My test above works fine:

```
fixture `Dialog`.page`https://devexpress.github.io/testcafe/example/`;

test('Test', async t => {
    await t
        .setNativeDialogHandler(() => true)
        .click('#populate')
        .debug();

    console.log(await t.getNativeDialogHistory());
});
```

Could you please attach your test snippet or give us a public url so that we will see the problem?

**Comment by Ivan-Katovich** [comment] 2021-03-02 08:16
Can you try do the same with alert which appears when a page is refreshed. For example any unsaved form with alert about "lost changes"

**Comment by Dmitry-Ostashev** [comment] 2021-03-03 08:32
I tried to reproduce it with the form example described in this answer: https://stackoverflow.com/a/7317311/10684943.

Here is my page, test, and console output:
```
<html>
<body>
    <script>
        var formSubmitting = false;
        var setFormSubmitting = function () { formSubmitting = true; };

        window.onload = function () {
            window.addEventListener("beforeunload", function (e) {
                if (formSubmitting) {
                    return undefined;
                }

                var confirmationMessage = 'It looks like you have been editing something. '
                    + 'If you leave before saving, your changes will be lost.';

                (e || window.event).returnValue = confirmationMessage; //Gecko + IE
                return confirmationMessage; //Gecko + Webkit, Safari, Chrome etc.
            });
        };
    </script>
    <form method="post" onsubmit="setFormSubmitting()">
        <input type="text">
        <button type=submit>Ok!</button>
    </form>
    <button type="button" onclick="window.location.reload()">Refresh!</button>
</body>
</html>
```

```
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `file:///E:/_TestCafe/confirm.html`;
    
test(`New Test`, async t => {
    await t
        .setNativeDialogHandler(() => true)
        .typeText('form input', 'wqeqweqw')    
        .click(Selector('button').withText('Refresh!'))

    console.log(await t.getNativeDialogHistory());
});
```

![image](https://user-images.githubusercontent.com/24777868/109774971-f3b5d380-7c11-11eb-88ce-0a9455b1164a.png)

Could you please send us your webpage example or modify mine to reproduce the issue?

**Comment by Ivan-Katovich** [comment] 2021-03-03 11:30
Unfortunately it is from secured web application.

**Comment by Farfurix** [comment] 2021-03-04 08:03
@Ivan-Katovich 

Hello,

It is impossible to determine the cause of the issue without a reproducible example. So, I'll close this issue. If you manage to create a public example, feel free to open a new bug report.

**Closed by Farfurix** 2021-03-04 08:03 UTC
Labels: STATE: Need response
