### ISSUE TITLE
Not getting window.performance.memory output through TestCafe which works in Chrome Console to get js memory stats

### ISSUE THREAD

**Issue by rakeshkumartripathy** [DevExpress/testcafe#5371] opened 2020-07-29 13:20 UTC
What is your Test Scenario?
I want to get window.performance.memory object with js memory data inside

What is the Current behavior?
Its empty
 
What is the Expected behavior?
Will be filled with the same data as i have inside the browser which I am able to get from Chrome Browser Console
 
![image](https://user-images.githubusercontent.com/68940011/88800000-0b813100-d1c5-11ea-87a8-277c5a0886cc.png)

What is your web application and your TestCafe test code?
test('memory works', async t => {
  const getMemory = ClientFunction(() => performance.memory);
  console.log(await getMemory());
});
 

Your website URL (or attach your complete example):
https://www.example.com

Steps to Reproduce:
Use example code above to see {} as a result instead of whats actually in the browser.

Your Environment details:
testcafe version: 1.8.0
node.js version: 13
browser name and version: chrome 83
platform and version: windows os 10

**Comment by Ogurecher** [comment] 2020-07-30 07:28
@rakeshkumartripathy, Thank you for your report. This issue is a duplicate of #3546. We'll update #3546 once the issue is fixed.

**Closed by Ogurecher** 2020-07-30 07:28 UTC
Labels: STATE: Duplicate, STATE: Need response
