### ISSUE TITLE
Document title selection broken in 1.8.5

### ISSUE THREAD

**Issue by aboe026** [DevExpress/testcafe#5115] opened 2020-05-22 01:57 UTC
### What is your Test Scenario?

Verifying my webapp has the proper document title (text shown in browser tab)
 
### What is the Current behavior?

when I try to check the text of `Selector('title')`, I get an error:
```
Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

 > | Selector('title')
```
I even put it on `debugOnFail` mode and inspected the source when the failure happened, and there was no title in the `<head>` like there should have been.
 
### What is the Expected behavior?

It should be able to read the document title
 
### What is your web application and your TestCafe test code?

 private repository, cannot share
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 await t
      .expect(tabTitle.title.innerText).eql('Login', 'Initial login page shows correct tab title')
```

where `tabTitle` has
```js
this.title = Selector('title')
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "appCommand": "cross-env DOTENV_CONFIG_PATH=../.test-browser.env node build/server_bundle.js",
  "appInitDelay": 5000,
  "assertionTimeout": 10000,
  "concurrency": 1,
  "debugOnFail": false,
  "pageLoadTimeout": 10000,
  "quarantineMode": true,
  "screenshots": {
    "path": "screenshots",
    "takeOnFails": true
  },
  "selectorTimeout": 10000,
  "skipJsErrors": true
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
adamb@ADAM-DESKTOP MINGW64 /d/Repos/<redacted> (master)
$ npm run test:browser:edge:concurrent

> <redacted>@1.0.0 test:browser:edge:concurrent D:\Repos\<redacted>
> cross-env MONGO_DB=<redacted>-browser-test SCREEN_SIZE=desktop testcafe edge test/browser/tests/concurrent

 Running tests in:
 - Microsoft Edge 81.0.416.77 / Windows 10

 Tab Titles
MailDev webapp running at http://127.0.0.1:1080
MailDev SMTP Server running at 127.0.0.1:1025

----
Microsoft Edge 81.0.416.77 / Windows 10
DEBUGGER PAUSE ON FAILED TEST:
Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

 > | Selector('title')

Browser: Microsoft Edge 81.0.416.77 / Windows 10
Screenshot: D:\Repos\<redacted>\screenshots\2020-05-21_17-34-28\test-1\Microsoft_Edge_81.0.416.77_Windows_10\errors\1.png

48 |
49 |test.only('Tab Titles Correct Across Application', async t => {
50 |  // create user
 × Tab Titles Correct Across Application (screenshots: D:\Repos\<redacted>\screenshots\2020-05-21_17-34-28\test-1\Microsoft_Edge_81.0.416.77_Windows_10\errors\1.png)

   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

       > | Selector('title')

      Browser: Microsoft Edge 81.0.416.77 / Windows 10
      Screenshot: D:\Repos\<redacted>\screenshots\2020-05-21_17-34-28\test-1\Microsoft_Edge_81.0.416.77_Windows_10\errors\1.png

         48 |
         49 |test.only('Tab Titles Correct Across Application', async t => {
         50 |  // create user
         51 |  const email = browserUtil.getUsername('tabTitles')
         52 |  await t
       > 53 |      .expect(tabTitle.title.innerText).eql('Login | <redacted>', 'Initial login page shows correct tab title')
         54 |      .click(loginPage.createUserTab)
         55 |      .expect(tabTitle.title.innerText).eql('Login | <redacted>', 'Login page shows correct tab title when on create user tab')
         56 |  await registrationForm.registerUser(email, VALID_PASSWORD)
         57 |  await t.expect(tabTitle.title.innerText).eql('Login | <redacted>', 'Login page shows correct tab title after user created')
         58 |  await webmailPage.activateUser(email)

         at <anonymous> (D:\Repos\<redacted>\test\browser\tests\concurrent\tabTitleTest.js:53:41)
         at <anonymous> (D:\Repos\<redacted>\test\browser\tests\concurrent\tabTitleTest.js:49:1)
         at <anonymous> (D:\Repos\<redacted>\node_modules\testcafe\src\api\wrap-test-function.js:17:28)
         at TestRun._executeTestFn (D:\Repos\<redacted>\node_modules\testcafe\src\test-run\index.js:295:19)
         at TestRun.start (D:\Repos\<redacted>\node_modules\testcafe\src\test-run\index.js:345:24)



 1/1 failed (21s)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! <redacted>@1.0.0 test:browser:edge:concurrent: `cross-env MONGO_DB=<redacted>-browser-test SCREEN_SIZE=desktop testcafe edge test/browser/tests/concurrent`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the <redacted>@1.0.0 test:browser:edge:concurrent script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adamb\AppData\Roaming\npm-cache\_logs\2020-05-21T21_34_51_384Z-debug.log
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Have a webapp that sets the document title.
2. Create a test to verify the document title.
3. Experience the error as recorded above.
 
### Your Environment details:
 
* testcafe version:                   1.8.5
* node.js version:                    v12.16.2
* command-line arguments:  
* browser name and version: Microsoft Edge 81.0.416.77
* platform and version:          Windows 10 18363.836
* other:                                   This works properly in 1.8.4. It seems something in 1.8.5 broke this.

**Comment by miherlosev** [comment] 2020-05-22 07:44
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/2328

**Closed by miherlosev** 2020-05-22 07:44 UTC
Labels: STATE: Need response

**Comment by aboe026** [comment] 2020-05-22 13:02
The duplicate issue linked does seem to be the same root cause, just wanted to add the nuance that I'm seeing the problem locally, when the duplicate issue is only for the docker image.

**Comment by AlexKamaev** [comment] 2020-05-25 10:03
@aboe026, thank you for the additional information. I confirm that the issue exists locally as well.
