### ISSUE TITLE
Bug: Command Line Interface --app doesn't work

### ISSUE THREAD

**Issue by AhnpGit** [DevExpress/testcafe#2073] opened 2018-01-25 13:16 UTC
### Are you requesting a feature or reporting a bug?
A bug

### What is the current behavior?
I run command `yarn testcafe chrome:headless e2e/**/**.spec.ts --app 'node server.js'` it can't launch the test and give me errors.

![image](https://user-images.githubusercontent.com/27772165/35390023-4328abd2-01da-11e8-898e-e128ab5c8aea.png)

### What is the expected behavior?
It should start the application and run the tests

### How would you reproduce the current behavior (if this is a bug)?
Install testcafe the latest version, setup a simple test and run the test with command `yarn testcafe chrome:headless e2e/**/**.spec.ts --app 'node server.js'`. Observe the command line and see the errors

#### Provide the test code and the tested page URL (if applicable)
N.A

### Specify your

* operating system: Windows 10 64bit
* testcafe version: 0.18.6
* node.js version: 8.9.4

**Comment by AlexanderMoskovkin** [comment] 2018-01-26 11:21
Hi @AhnpGit,

This works properly on my side. 
Could you please check is it possible to execute the `node server.js` command in your terminal. It possible Node is missing from the SYSTEM PATH (see [Node.js doesn't recognize system path?
](https://stackoverflow.com/questions/8768549/node-js-doesnt-recognize-system-path)).

**Comment by AhnpGit** [comment] 2018-01-26 11:42
Hi @AlexanderMoskovkin ,
I did try to check whether I can use node command by typing `node -v` and also `node server.js`. Both allow me to execute something. That's why I don't know why it doesn't work when I use with `--app`

Besides, is it possible to make testcafe to run `yarn start` with option `-app` ?

**Comment by AndreyBelym** [comment] 2018-01-26 15:34
Hello @AhnpGit, it looks like interpolation problem with quotation marks in the shell (note the `Command failed: 'node` & `''node' is ...` messages). I assume that it is the standard `cmd.exe` because you specified Windows in the original post. In `cmd.exe`, single quotation marks can't be used for specifying string argument, double quotation marks (`"`) should be used instead:
```
yarn testcafe chrome:headless e2e/**/**.spec.ts --app "node server.js"
```

**Comment by AhnpGit** [comment] 2018-01-26 18:33
Hi @AndreyBelym ,
Thank you for your suggestion. It works for me now. I wonder if it's better to make it run regardless the OS. Maybe the documentation needs to have some notes regarding to this issue.

**Comment by AlexanderMoskovkin** [comment] 2018-01-29 07:50
Hi @AhnpGit,

This relates not to the TestCafe behavior but to the way how the terminal handles arguments from your command. For example if you use Unix shells on Windows (like bash) you can use single quotes as well. 

I see we have an example for the [--app](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-a-command---app-command) options that works on Unix systems only. I guess it would be better to use double quotes there to make it workable on all systems. (it's the same for the `--app-init-delay` option) /cc @VasilyStrelyaev 

So, I close the issue since the problem is resolved. @VasilyStrelyaev please create a documentation issue for this or just PR this changes.

**Closed by AlexanderMoskovkin** 2018-01-29 07:50 UTC
Labels: To be reproduced

**Comment by AhnpGit** [comment] 2018-01-29 07:53
Thank you. I think using consistent double quotes for all systems is a good idea :)
