### ISSUE TITLE
Selector toString() should return the actual selector

### ISSUE THREAD

**Issue by dlangerenken** [DevExpress/testcafe#3578] opened 2019-03-18 19:39 UTC
In some of our test-cases, we'd like to know what the selector is actually selecting, e.g. to traverse the selection to discover issues using  `document.querySelector()`.
It might be possible already but if so, it is not clear to me.

E.g. `Selector('body').find('.foo').toString()` should return something like `body .foo`.

Right now, what we have to do in such scenarios is create the entire query 'raw' and then generate a selector out of it, which works fine but is quite a hassle.
I don't know about the internals of testcafe, but if you at some point translate the selector back to a string, maybe it's easy to expose this functionality to the user

**Comment by AndreyBelym** [comment] 2019-03-20 08:40
I close this issue since it is a duplicate of #2671. Generating a CSS selector from an arbitrary `Selector` object can be tricky because all filtering functions (`filter`, `find`, and so on) use JS functions to filter elements, and `Selectors` don't store any information about previous filtering stages.

**Closed by AndreyBelym** 2019-03-20 08:40 UTC
Labels: STATE: Need response
