### ISSUE TITLE
Roles do not work (show blank page between tests and fail) on M1 Airbook

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#6765] opened 2021-12-08 22:17 UTC
### What is your Scenario?

I'm attempting to run tests that use Roles on an M1 airbook; 2020; Big Sur 11.2 

### What is the Current behavior?

Tests login then get stuck on a blank page and fail further tests in the fixture. 

Occurs on latest chrome (96.0.4664.55 ) and safari (14.0.3 )
Does not occur on coworkers Windows machine, nor our linux pipeline

### What is the Expected behavior?

Should work. Running the same code without `Roles` work just fine. 

### What is your public website URL? (or attach your complete example)

See code...

### What is your TestCafe test code?

```
import { Role, Selector as $, t } from 'testcafe';

const user = Role('http://automationpractice.com/index.php?controller=authentication', async t => {
  await t
    .typeText($('#email'), 'roles@fail.test')
    .typeText($('#passwd'), 'test123')
    .click($('#SubmitLogin'))
});

fixture `MyFixture`
  .beforeEach(async t => {
    await t.useRole(user)
  })

test('Test1', async t => {
  await t
    .click($('.logout'))
    .expect($('.logout').exists).notOk()
})

test('Test2', async t => {
  await t
    .click($('.logout'))
    .expect($('.logout').exists).notOk()
})

```

### Screenshots

![boog](https://user-images.githubusercontent.com/3298906/145292606-d59eebae-7bd7-48ad-a1cc-132858c60b5e.gif)

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.17.1

### Node.js version

v14.17.4

### Command-line arguments

testcafe chrome test.js

**Comment by AlexanderMoiseev** [comment] 2021-12-09 07:29
Hi,

Thank you for your input. We have reproduced the problem. Please stay tuned.

**Comment by qualityshepherd** [comment] 2021-12-09 14:29
also, removed that unnecessary `navigateTo` that I had in there while regressing... woops!

**Comment by Mikoz93** [comment] 2021-12-12 19:09
I've had a similar problem when using the current LTS version of node (16.13.0). After the t.useRole code would finish executing, the browser would resfresh and lose all cookies stored during sign-in. This happend when using one of the latest versions of Chrome.

**Comment by AlexanderMoiseev** [comment] 2021-12-13 07:04
Hi, @Mikoz93

Thank you for pointing this out. Once we have any news, we will post them here. Please stay tuned.

**Comment by Mikoz93** [comment] 2022-01-13 23:43
@AlexanderMoiseev Any news on this?

**Comment by teebash** [comment] 2022-01-28 18:08
Just checking the status of this ticket, as this is also affecting.

**Comment by thecpdubguy** [comment] 2022-03-23 19:56
> I've had a similar problem when using the current LTS version of node (16.13.0). After the t.useRole code would finish executing, the browser would refresh and lose all cookies stored during sign-in. This happened when using one of the latest versions of Chrome. To solve this, I had to drop back to one of the 80+ versions of Chrome.

This is seemingly the exact same use case for me. Maybe some insight:

I was using version 1.15.2 and this was working fine. When updating to latest (1.18.4) this stopped working for me.

**Comment by VasilyStrelyaev** [comment] 2022-03-25 07:02
@thecpdubguy, thank you for pointing out that this issue is a regression.

@teebash, there are no updates regarding this issue yet. We will update this thread once we have any news.

**Comment by gg-kialo** [comment] 2022-11-21 14:36
FWIW, some people on my team are also affected by this. They've been adding additional `await`s in places that they aren't needed and it seems like they skirt around the issue. i.e. effectively `await t.useRole(await (async () => (await role))())`.

I don't have an M1 so can't reproduce these issues myself.

**Comment by VasilyStrelyaev** [comment] 2022-11-24 07:32
Thank you for sharing your workaround!

**Comment by qualityshepherd** [comment] 2023-06-02 20:59
Still no movement on this. I'm _really_ considering moving to another framework. 

Anyway, here's an updated example that shows the problem (original site was nuked). 

```
import { Role, Selector as $, t } from 'testcafe';

const user = Role('https://www.saucedemo.com/', async t => {
  await t
    .typeText($('#user-name'), 'standard_user')
    .typeText($('#password'), 'secret_sauce')
    .click($('#login-button'))
});

fixture `MyFixture`
  .beforeEach(async t => {
    await t.useRole(await user)
  })

test('Test1', async t => {
  await t
    .click($('#react-burger-menu-btn'))
    .click($('#logout_sidebar_link'))
    .expect($('#login-button').exists).ok()
})

test('Test2', async t => {
  await t
    .click($('#react-burger-menu-btn'))
    .click($('#logout_sidebar_link'))
    .expect($('#login-button').exists).ok()
})
```

**Comment by qualityshepherd** [comment] 2023-06-02 21:02
Also, I REALLY wish the fix for this is to bag, `Role`s; implement a `beforeAll` and let me roll my own Roles (see what I did there?).

**Comment by aleks-pro** [comment] 2023-06-05 09:19
Hello @qualityshepherd ,

Thank you for the updated example. We will revisit this issue priority.

**Comment by vileen** [comment] 2023-06-08 23:32
@qualityshepherd do you also get redirected to about:blank after logging in? I wonder if it's the exact same scenario for you
Workaround from @gg-kialo didn't produce any different outcome than simple `await role`, but it makes the test stay on about:blank a lot shorter before navigating further
But still, the refresh happens so my tests are broken, and they're running just fine on Windows...

**Comment by qualityshepherd** [comment] 2023-06-09 11:39
To be clear, [gg-kialo](https://github.com/gg-kialo)'s workaround does NOT fix this issue. My example still fails.

**Comment by Artem-Babich** [comment] 2023-06-12 14:10
Hi @qualityshepherd,

I just tested your example and found that you didn't specify the URL on which you wish to run tests. As a result, you are getting a blank page after calling the useRole method: [Activate Roles](https://testcafe.io/documentation/402845/guides/intermediate-guides/authentication#activate-roles).
Also, note that in your example, when going to the main page ([https://www.saucedemo.com](https://www.saucedemo.com)), even a logged user will not be redirected to inventory.html. Instead, you will be asked to log in again.

So, I had to change your test as follows:

```js
.beforeEach(async t => {
    await t.useRole(user)
    await t.navigateTo('https://www.saucedemo.com/inventory.html')
})
```

After this, I tried running this test on the following machines with Node 18.12:

1. macOS Ventura 13.4 - M1 chip, Chrome 114.0.5735.106, and Safari 16.5 (18615.2.9.11.4)
2. Ubuntu 22.04.2 LTS, Chrome 113.0.5672.126
3. Windows 11 Pro, Chrome 114.0.5735.110


The behavior is the same on all machines - all tests are passed.

Would you please apply the changes above and test the example on your machine again? If the issue is still reproducible, please share more details so we can reproduce it on our side.

**Comment by qualityshepherd** [comment] 2023-06-12 14:38
@Artem-Babich I think you're misunderstanding how [Role](https://testcafe.io/documentation/402845/guides/intermediate-guides/authentication#create-roles) works. This _is_ a bug... 

<img width="715" alt="image" src="https://github.com/DevExpress/testcafe/assets/3298906/82aba462-84c7-4ee1-98dd-da1eea5c085e">

**Comment by Artem-Babich** [comment] 2023-06-13 07:05
Hi @qualityshepherd,

Thank you for the reply. Would you please elaborate on how Roles should work in this case and why you think this behavior is incorrect?

Previously, I shared a link where the behavior you encountered is discussed: [Activate Roles](https://testcafe.io/documentation/402845/guides/intermediate-guides/authentication#activate-roles).
> The first time you activate a role, TestCafe navigates to the login page and executes login actions. **When the authentication is complete, TestCafe goes back to the page that was open before Role activation**. Use the [preserveUrl](https://testcafe.io/documentation/402760/reference/test-api/role/constructor#optionspreserveurl) option to disable this behavior.

So, when you logged in with a Role, the page is redirected back to about:blank. That is why I corrected your test's code. After this change, I was able to run it on all of the OS I mentioned above. If you see a different behavior, please share the following details:

1. TestCafe version.
2. NodeJS version.
3. OS version.
4. Browser and its version.
5. Command line arguments.
6. Exact test code.
7. A screencast illustrating the problematic behavior.


I look forward to your response.

**Comment by qualityshepherd** [comment] 2023-06-13 12:16
And sorry... what I mean is, I've written bugs against Testcafe... and they go nowhere. Testcafe would be the best  framework going if:
1. it had a real `beforeAll` (which would also allow us to NOT use `Roles` 
2. threaded tests at the _file_ level instead of the _test_ level

That's it. But it's not happened in years. I've been using Testcafe for _years_... but that's gonna change soon.

**Comment by Artem-Babich** [comment] 2023-06-14 11:39
Thank you for your feedback. We will take it into the account.

Since we identified the cause of the incorrect behavior in the example, we are closing this issue. However, if you still believe that you encounter a bug, feel free to reopen this issue and share an example with instructions on how to reproduce the problematic behavior.

**Closed by Artem-Babich** 2023-06-14 11:39 UTC
Labels: TYPE: bug, OS: Mac, STATE: Need response, FREQUENCY: level 2

**Comment by qualityshepherd** [comment] 2023-06-14 12:07
This is a bug but closing it anyway is what I've come to expect from Testcafe. I won't bother writing up future bugs...

**Comment by vileen** [comment] 2023-06-14 12:13
@qualityshepherd you digress, could you stick to the topic and explain the issue?
There is no point in being salty, it doesn't produce any value and you might be surprised if something comes out of this discussion.

**Comment by vileen** [comment] 2023-06-15 23:31
Thanks @aleks-pro, seems like you were right, I even made a repo to try and reproduce the issue
https://github.com/vileen/refresh-after-logging-in-reproduction

But seems like simply adding `preserveUrl: true` fixes the issue, now I have to figure out why my tests are not working as expected but I'm new to testcafe and probably missed something.
