### ISSUE TITLE
Test cases hanging due to odd html tag within UI.

### ISSUE THREAD

**Issue by christianpenrod7984** [DevExpress/testcafe#3299] opened 2019-01-11 20:58 UTC
![issue](https://user-images.githubusercontent.com/33991831/51059279-a30a3900-15b9-11e9-8855-79a3af2c0d33.PNG)

Before my tests execute, my browser (chrome) hangs on this screen for quite some time. This only happens at random meaning I won't always see this issue. A few results may happen when this occurs:

Simple refresh may start the test back up.
Have to wait 30+ seconds.
The test just terminates with no failure or success status.

P.S. I've tested to see if this was a browser specific issue within Chrome; however, it seems to reproduce the same issue in firefox, edge, and ie.

**Comment by christianpenrod7984** [comment] 2019-01-11 20:59
I'm unable to provide the source code or url for this issue.

**Comment by AlexKamaev** [comment] 2019-01-14 09:35
As my colleague mentioned at https://github.com/DevExpress/testcafe-hammerhead/issues/1888, this information is not sufficient to find the cause of the issue. We need to analyze your page and your test code. Since you cannot share the URL of your project, you can create a sample which demonstrates the issue.
I'll close this issue as a duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1888

**Closed by AlexKamaev** 2019-01-14 09:35 UTC
