### ISSUE TITLE
If an element is not found, browser hangs with version 1.10.0. Version 1.9.4 appears to work correctly.

### ISSUE THREAD

**Issue by mikeyjkmo** [DevExpress/testcafe#5821] opened 2020-12-22 09:54 UTC
This has been observed in the latest 1.10.0 testcafe docker image as well as my local installation of testcafe v1.10.0.

### What is your Test Scenario?

Basic test that tries to check for the existence of an element that contains some text. 
 
### What is the Current behavior?
Testcafe hangs. A while later, the following error occurs:

`ERROR The Chrome 80.0.3987.149 / Linux 0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`
 
### What is the Expected behavior?
Testcafe should fail expectedly when an element does not exist, instead of hanging.
 
### What is your web application and your TestCafe test code?

```
fixture('Wikipedia').page("https://en.wikipedia.org");

test('non existent element', async t => {
    await t.expect(Selector('#non-existent-thing').withText("blah").exists).ok();
});
```

### Steps to Reproduce:
Run the above test using testcafe 1.10.0.
 
### Your Environment details:
 
* testcafe version:                   1.10.0
* node.js version:                    12.3.0
* command-line arguments:  "testcafe chrome test.js"
* browser name and version:  Chrome 80
* platform and version:          Ubuntu 18.04 and Manjaro Latest

**Comment by AlexKamaev** [comment] 2020-12-23 09:59
I tried your scenario with the latest TestCafe version and the latest Chrome/Chromium browsers in Ubuntu and in the official Docker image. In both cases, the tests did not hang.
As far as I understand, you are using the Chrome 80 version, so please update your Chrome to the latest version and try again.
Please also clarify which docker image you are using as only the Chromium browser is available in the official docker image.

**Comment by mikeyjkmo** [comment] 2020-12-23 15:59
@AlexKamaev  The output of the docker container says:

```
ERROR The Chrome 85.0.4183.121 / Linux 0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```

The image is testcafe/testcafe:1.10.0.

We suspect it might be CPU/memory resource related, but no evidence yet... It only appears to be happening inside my VM and Kubernetes cluster.

**Comment by akost** [comment] 2020-12-23 22:41
I see the similar issue.
Running testcafe Docker image on GitLab.

**Comment by AlexKamaev** [comment] 2020-12-24 07:56
@mikeyjkmo @akost
This may be related to a lack of resources since I cannot reproduce the issue locally. At this moment, we are working on enhancing the error message when the browser is disconnected. Please track the following PR: [https://github.com/DevExpress/testcafe/pull/5720](https://github.com/DevExpress/testcafe/pull/5720)
Please try it with your example after the PR is merged.

**Comment by AlexKamaev** [comment] 2020-12-24 09:21
Please try to provide your VM with more resources and try again. Please ensure that your Chrome browser is updated to the latest version. Also, share the full test run output with us.

@mikeyjkmo

It can be related to a lack of CPU/Memory resources. However, it's unclear to me why the issue occurs only when the target element is not found. Could you please confirm that the other tests are passed as expected? Could you please check your scenario in Firefox as well? I would also ask you to try running your tests in v.1.10.0 release candidate versions:
[https://www.npmjs.com/package/testcafe/v/1.10.0-rc.8](https://www.npmjs.com/package/testcafe/v/1.10.0-rc.8)
[https://www.npmjs.com/package/testcafe/v/1.10.0-rc.7](https://www.npmjs.com/package/testcafe/v/1.10.0-rc.7)
[https://www.npmjs.com/package/testcafe/v/1.10.0-rc.6](https://www.npmjs.com/package/testcafe/v/1.10.0-rc.6)
[https://www.npmjs.com/package/testcafe/v/1.10.0-rc.5](https://www.npmjs.com/package/testcafe/v/1.10.0-rc.5)
[https://www.npmjs.com/package/testcafe/v/1.10.0-rc.4](https://www.npmjs.com/package/testcafe/v/1.10.0-rc.4)
[https://www.npmjs.com/package/testcafe/v/1.10.0-rc.3](https://www.npmjs.com/package/testcafe/v/1.10.0-rc.3)
[https://www.npmjs.com/package/testcafe/v/1.10.0-rc.2](https://www.npmjs.com/package/testcafe/v/1.10.0-rc.2)
[https://www.npmjs.com/package/testcafe/v/1.10.0-rc.1](https://www.npmjs.com/package/testcafe/v/1.10.0-rc.1)

@akost

Do you also have the issue only if the element is not found? Could you please share your example?

**Comment by akost** [comment] 2020-12-24 19:08
The original example with Wikipedia and non-existing element works fine for me on Windows with testcafe 1.10.0.

**Comment by akost** [comment] 2020-12-24 19:19
In my case:

My application (Angular) uses redirects to `/#!/signup`. It worked fine with testcafe for more than a year. Recently it stopped working.

Examples:
```
window.location.href = '/#!/signup';
...
window.location.replace('/#!/signup');
```



Expected behavior:
Redirect to `http://10.156.209.68:62757/vgA7qgJsG*dQqONrwHb/https://example.com/#!/signup`

Actual behavior:
Testcafe redirects to `http://10.156.209.68:62757/#!/signup`. Then it obviously fails to find an element, hangs there for a while, and then crashes with the browser disconnect.

It reproduces in 1.10.0, 1.9.4 and in 1.6.1

**Comment by Farfurix** [comment] 2020-12-25 07:31
@akost

Hello,

This information is not sufficient to determine the cause of the issue. We cannot say that this issue is related to the original one. Could you please open a new bug report using our template? Please fill it out and share a reproducible example. Also, you can try to provide your VM with more resources.

**Comment by mikeyjkmo** [comment] 2020-12-29 12:13
@AlexKamaev It appears that a completely fresh project with testcafe as its only dependency appears to work. Perhaps there is some sort of package dependency conflict in my main project.

**Comment by AlexKamaev** [comment] 2020-12-30 07:16
@mikeyjkmo I see. In this case, I'll close this issue. Feel free to create a new issue if you have any further questions.

**Closed by AlexKamaev** 2020-12-30 07:16 UTC
Labels: STATE: Need response
