### ISSUE TITLE
Selector's VisibilityCheck not working under these conditions

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe#4524] opened 2019-11-26 19:41 UTC
### What is your Test Scenario?

 I'm trying to assert if a certain element is visible or not. Im using this selector :

const element = Selector("[data-test-id='parameters-list-add-button']",{visibilityCheck:true});

As visible sometimes crashes if the element is not present , we switched to selectors with visibilityCheck to check if some elements are visible.
My assertion is :
await t.expect(element.exists).notOk("Element was visible")

## What is the Current behavior?

 This test doesn't pass even though the element is not visible because a parent element has display:none.

### What is the Expected behavior?

 Test should pass as the parent element is not visible.

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
```
<div data-test-id="hiddable-content-container" class="definitionFrame__hiddableContent--1936B" style="padding: 0px 10px 0px 0px; transition: height 300ms ease 0s; overflow: hidden; height: 0px; display: none;"><div data-test-id="hiddable-content-content"><div><div class="undefined definitionFrame__container--r_sKd" data-test-id="parameters-list"><div class="listPanel__addContainer--39amX"><div class="listPanel__addNewItem--3G_s9" data-test-id="parameters-list-add-button">Add Base URI Parameter</div></div></div></div></div></div>

```
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js

const element = Selector("[data-test-id='parameters-list-add-button']",{visibilityCheck:true});
await t.expect(element.exists).notOk("Element was visible")
 
```
</details>

### Your Environment details:
 
* testcafe version:   1.7.0                
* node.js version:     10.17.0               
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by franciscolosardo** [comment] 2019-11-26 19:57
.visible also fails on this one :(

**Comment by miherlosev** [comment] 2019-11-27 15:19
Duplicate of https://github.com/DevExpress/testcafe/issues/2386

**Closed by miherlosev** 2019-11-27 15:19 UTC
Labels: STATE: Need response
