### ISSUE TITLE
Cannot run testcafe tests against latest portable edge in headless mode

### ISSUE THREAD

**Issue by Makavelic** [DevExpress/testcafe#8200] opened 2024-05-28 14:14 UTC
### What is your Scenario?

It is not possible to run testcafe tests against a local version of edge.

### What is the Current behavior?

Edge cannot run

### What is the Expected behavior?

Edge should run without errors

### What is the public URL of the test page? (attach your complete example)

Any project will do, you can reproduce by pointing to a local version of edge:

`testcafe "path:d:\edgeportable\msedge.exe --headless" test.js`

Note: Even if you try running headless mode locally without testcafe you get an error.

If you try and force the new headless=new feature it does work manually but not in testcafe.

Ex: `testcafe "path:d:\edgeportable\msedge.exe --headless=new" test.js`

### What is your TestCafe test code?

None needed

### Steps to Reproduce

1. Run cli testcafe "path:d:\edgeportable\msedge.exe --headless" test.js
2. Notice Error
3. Run cli testcafe "path:d:\edgeportable\msedge.exe --headless=new" test.js
4. Notice how the tests stalls indefinitely (browser init never finishes)

Note: The following paths don't work either:

edge:d:\edgeportable\msedge.exe:headless (error)
edge:d:\edgeportable\msedge.exe:headless=new (runs without headless but doesn't work)

Note: this works on older versions of edge like 118.

### TestCafe version

3.6.0

### Node.js version

18.18.2

### Command-line arguments

testcafe "path:d:\edgeportable\msedge.exe --headless" test.js

### Browser name(s) and version(s)

Edge 125

### Platform(s) and version(s)

Windows 11

**Comment by PavelMor25** [comment] 2024-05-30 08:37
Hello @Makavelic,

Please clarify whether you used the following command to run tests:

```shell
testcafe "path:d:\edgeportable\msedge.exe --headless"  test.js
``` 

In your examples, the `--headless` and `--headless=new` options are outside the quotation marks. Therefore, they are parsed as TestCafe options rather than browser options.

**Comment by Makavelic** [comment] 2024-05-30 13:55
> Hello @Makavelic,
> 
> Please clarify whether you used the following command to run tests:
> 
> ```shell
> testcafe "path:d:\edgeportable\msedge.exe --headless"  test.js
> ```
> 
> In your examples, the `--headless` and `--headless=new` options are outside the quotation marks. Therefore, they are parsed as TestCafe options rather than browser options.

Sorry about that, I've edited my post with the correct syntax. It still has the same errors.

**Comment by Makavelic** [comment] 2024-06-04 20:26
Like I mentioned, the error is coming from edge itself not testcafe:

The application was unable to start correctly (0x0000022) Click OK to close the application. The same error happens when running it directly without testcafe.

The only way to get it to run properly without testcafe is to run with --headless=new. However, I have been unsuccessful forcing headless=new in testcafe for edge.

**Comment by Bayheck** [comment] 2024-06-05 14:07
Hello, try running your tests as follows:

npx testcafe "edge:d:\edgeportable\msedge.exe --headless=new" test.js

or 

npx testcafe "edge:d:\edgeportable\msedge.exe --headless" test.js

Note: to launch a custom headless browser, replace the `path`: prefix with the browser’s alias.

[https://testcafe.io/documentation/402828/guides/intermediate-guides/browsers#test-in-headless-mode](https://testcafe.io/documentation/402828/guides/intermediate-guides/browsers#test-in-headless-mode)

**Comment by Makavelic** [comment] 2024-06-05 20:00
I get the following error when I try your example:

ERROR Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:

**Comment by Bayheck** [comment] 2024-06-07 14:15
I was not able to reproduce this behavior with the local version of edge.

Perhaps the issue only occurs in your portable edge. Could you please share it with us?

Could you also execute your tests in the same manner in a different browser (such as Chrome)?

To help you further, we need a repository with an example that shows how you execute your tests (a simple sample is sufficient). Please share all the paths and script commands in the config. This way, we will be in a better position to assist you.

**Comment by Makavelic** [comment] 2024-07-02 18:38
Was able to find a workaround by adding --no-sandbox. Not sure why this is needed on newer versions of edge.

**Closed** 2024-07-04 11:17 UTC
Labels: TYPE: bug, HAS WORKAROUND
