### ISSUE TITLE
Failing tests `identifier 't' has already been declared` Jitsi

### ISSUE THREAD

**Issue by humanamburu** [DevExpress/testcafe#6797] opened 2021-12-23 13:33 UTC
### What is your Scenario?

Simple open [Jitsi](https://meet.jit.si/testcafe_error) call page test

### What is the Current behavior?

All the same, behavior as described [here](https://github.com/DevExpress/testcafe/issues/5659):

- `Identifier 't' has already been declared`
- page works when opened manually, no issues or errors were observed

### What is the Expected behavior?

TestCafe should be able to render the app independent of the host scripts

### What is your public website URL? (or attach your complete example)

https://meet.jit.si/testcafe_error

### What is your TestCafe test code?

```
await t.navigateTo('https://meet.jit.si/testcafe_error');
await t.wait(500000);
```

### Screenshots

Test:
<img width="1213" alt="Screenshot 2021-12-29 at 15 19 33" src="https://user-images.githubusercontent.com/14282222/147671571-224fa9e9-5033-4012-afe7-8330dc9f8820.png">

Manual (everything works fine):
<img width="1210" alt="Screenshot 2021-12-29 at 15 20 46" src="https://user-images.githubusercontent.com/14282222/147671687-103fe469-79ac-4f9f-ae2c-fbc8aaf53c24.png">

### Steps to Reproduce

1. https://meet.jit.si/testcafe_error
2. Open the call page using testcafe

### TestCafe version

1.18.1

### Node.js version

14.15.4

### Command-line arguments

testcafe --skip-js-errors --hostname localhost $NODE_DEBUG_OPTION "chrome --use-fake-ui-for-media-stream --use-fake-device-for-media-stream"

### Browser name(s) and version(s)

Chrome 96

### Platform(s) and version(s)

macOS 10.15.7

**Comment by AlexanderMoiseev** [comment] 2021-12-28 20:55
Hi, 

Your testing page has javascript errors. By default, TestCafe tests fail if a javascript error occur. Please fix your page errors first or ignore them by using [--skip-js-errors option ](https://testcafe.io/documentation/402639/reference/command-line-interface#-e---skip-js-errors) and let us know the result.

**Comment by humanamburu** [comment] 2021-12-29 14:26
Hello @AlexanderMoiseev, 

I retested with `--skip-js-errors` option and the issue is still blocking the testing flow, could you please reopen issue again? The issue is absolutely identical to the https://github.com/DevExpress/testcafe/issues/5659 that marked as fixed.

I've updated commands and screenshots sections.

Thank you in advance.

**Comment by AlexanderMoiseev** [comment] 2021-12-30 11:21
Hello,

Unfortunately, I could not reproduce this behavior - when I use --skip-js-errors option, the test passes for me.

Please send us a video to demonstrate how you reproduce the issue. Make sure that the callstack with the problem is also visible.

**Comment by humanamburu** [comment] 2022-01-03 13:39
@AlexanderMoiseev thank you for the quick response, I've added [the video](https://youtu.be/nM_bWC0xJLg), hope it will help!

**Comment by AlexanderMoiseev** [comment] 2022-01-05 13:15
Hi @humanamburu,

It looks like the video you added isn't publicly available - I cannot open it.

**Comment by humanamburu** [comment] 2022-01-06 10:29
@AlexanderMoiseev sorry for the inconvenience, updated to public.

**Comment by miherlosev** [comment] 2022-01-07 10:12
Hi @humanamburu 

Thank you for the shared video. I've reproduced the issue.

**Comment by RicardoMiguel** [comment] 2022-01-24 15:39
Hi,

I'm also being affected by this. Is there any estimation to when a fix will be released? Thanks!

**Comment by aal89** [comment] 2022-01-27 08:52
I'm having the same issue. Are there any updates on this?

**Comment by miherlosev** [comment] 2022-01-31 08:05
Hi @aal89 

Thank you for the detailed information. We will investigate it.

**Comment by aal89** [comment] 2022-06-14 11:32
Any updates on this?

**Comment by miherlosev** [comment] 2022-06-29 11:28
The simplest code to reproduce
```js
for (const [t,n] of []) {
    const {features: t={}} = n;
}
```

**Comment by miherlosev** [comment] 2022-12-16 06:24
Hi @humanamburu,

TestCafe runs tests using the [URL-rewritten](https://github.com/devexpress/testcafe-hammerhead) proxy.
This approach is good. However, there is a way to improve the stability and speed of test execution - the native browser automation API.
We have a test execution mode uses native browser automation - we call it the `Proxyless` mode.
In `Proxyless` mode, a few issues are already fixed.
By the way, this issue was also fixed in `Proxyless` mode.
This option is available in all interfaces:

```js
// Command-line
testcafe chrome tests --experimental-proxyless

// Programmatic
testcafe
    .createRunner
	.src('tests')
	.browsers('chrome')
	.run({ experimentalProxyless: true });
	
// Configuration file
{
   "experimentalProxyless": "true"
}	

```

Setup the `testcafe@2.1.1-alpha.3` version and try running your tests in `Proxyless` mode. I look forward to your results.
Note that at present it is an experimental mode.
Also, the `Proxyless` mode is implemented only in Google Chrome. It will not work correctly if you run tests in a non-Chrome browser or in a combination of other browsers.

**Comment by humanamburu** [comment] 2023-01-16 14:35
Thank you! @aal89 could you please take a look?

**Comment by aal89** [comment] 2023-01-20 19:15
I took a look at the experimental setting but it did not work (I also updated to TestCafe 2.2.0). I found another bug. It seems that testcafe-hammerhead still rewrites some headers even though I switched on the proxyless flag. It prepends this into the authorization header: `~~~TestCafe added this prefix to control the authorization flow~~~` but it never removes it anymore. So executing our testsuite now shows 401's all over the place.

But there's some good news too. I did do another test. I asserted in our auth checks for this particular string, when it finds it, it removes it. Just to check if proxyless, in theory, would work. And it works!

**Comment by miherlosev** [comment] 2023-01-23 07:55
Hi @aal89,

Thank you for sharing this information. We will investigate it.

**Comment by miherlosev** [comment] 2023-02-03 06:26
Hi @aal89,

The testcafe@2.3.1-alpha.1 version contains a fix connecting with handling the `401` HTTP status code.
Try to run the tests with this version and let us know the results.

**Comment by aal89** [comment] 2023-02-03 22:25
I will check asap, thank you @miherlosev !

**Comment by Artem-Babich** [comment] 2023-04-13 07:02
Hi @aal89

Could you clarify if the original issue is resolved, as well as the issue with the HTTP 401 status code? Please note that we renamed the proxyless option to [native-automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) in TestCafe v2.5.0.

**Closed** 2023-04-23 07:09 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, STATE: Need clarification, FREQUENCY: level 2, STATE: possibly fixed in native automation
