### ISSUE TITLE
Converting circular structure to JSON when Live mode enabled

### ISSUE THREAD

**Issue by agung-wete** [DevExpress/testcafe#6499] opened 2021-08-26 10:13 UTC
### What is your Test Scenario?

Command: `testcafe --config-file ./testcaferc.json src/**/*-test.js -L`
### What is the Current behavior?
Got error:

> Make changes to the source files or press Ctrl+R to restart the test run.
> TypeError: Converting circular structure to JSON
>     --> starting at object with constructor 'ChromeRuntimeInfo'
>     |     property 'browserClient' -> object with constructor 'BrowserClient'
>     --- property '_runtimeInfo' closes the circle
>     at JSON.stringify (<anonymous>)
>     at Object.getBrowserInfo (xxx\testcafe\node_modules\testcafe\src\browser\provider\pool.js:124:26)
>     at async Promise.all (index 0)
>     at TestCafeConfiguration._getBrowserInfo (xxx\testcafe\node_modules\testcafe\src\configuration\testcafe-configuration.ts:265:29)
>     at TestCafeConfiguration.asyncMergeOptions (xxx\testcafe\node_modules\testcafe\src\configuration\testcafe-configuration.ts:110:44)
>     at LiveModeRunner._applyOptions (xxx\testcafe\node_modules\testcafe\src\runner\index.js:538:9)
> 
> Stopping TestCafe live mode...
> 

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe'

fixture`Getting Started`
  .page`http://devexpress.github.io/testcafe/example`

test('My first test', async t => {
  await t
    .typeText('#developer-name', 'John Smith')
    .click('#submit-button')

  const articleHeader = await Selector('.result-content').find('h1')

  // Obtain the text of the article header
  const headerText = await articleHeader.innerText
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "hostname": "localhost",
    "browsers": ["chrome --dns-server=8.8.8.8"],
    "concurrency": 1
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Make changes to the source files or press Ctrl+R to restart the test run.
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ChromeRuntimeInfo'
    |     property 'browserClient' -> object with constructor 'BrowserClient'
    --- property '_runtimeInfo' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.getBrowserInfo (xxx\testcafe\node_modules\testcafe\src\browser\provider\pool.js:124:26)
    at async Promise.all (index 0)
    at TestCafeConfiguration._getBrowserInfo (xxx\testcafe\node_modules\testcafe\src\configuration\testcafe-configuration.ts:265:29)
    at TestCafeConfiguration.asyncMergeOptions (xxx\testcafe\node_modules\testcafe\src\configuration\testcafe-configuration.ts:110:44)
    at LiveModeRunner._applyOptions (xxx\testcafe\node_modules\testcafe\src\runner\index.js:538:9)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>
 
### Your Environment details:
 
* testcafe version:                   1.15.3
* node.js version:                    v14.17.0
* command-line arguments:  testcafe --config-file ./testcaferc.json src/**/*-test.js -L
* browser name and version: 
* platform and version:          Windows 10
* other:

**Comment by aeneasr** [comment] 2021-08-28 20:08
I also have this problem! Other modes work fine.

```
 node --version
v16.8.0
```

I played a bit around with the testcafe config and this appears to be working:

```
  "browsers": {
    "path": "firefox",
    "cmd": "--width 1920 --height 1280"
  },
```

while this does not:

```
  "browsers": "firefox --width 1920 --height 1280"
  },
```

**Comment by agung-wete** [comment] 2021-08-29 08:37
thank you @aeneasr for this. I also found it works:
```
"browsers": [
	{
		"path": "chrome",
		"cmd": "--dns-server=8.8.8.8"
	}
],
```

**Comment by AlexanderMoiseev** [comment] 2021-08-30 06:58
Hello,

Thank you for your example project. We’ve reproduced the issue and need some time to investigate it. We'll get back to you when we have any results.

**Comment by aafeltowicz** [comment] 2021-09-24 06:55
@Aleksey28 wouldn't it be more suitable to decouple BrowserClient and RuntimeInfo? It could be easily done by introducing additional "map" in base.js, let say browserClients and then populate and depopulate it using same browser id like it is being done for openedBrowsers "map"?

**Comment by Aleksey28** [comment] 2021-09-24 08:06
Hi @aafeltowicz,

Thank you for the suggestion, but this issue is about others. This bug will be fixed with my PR. If you have other suggestions, you can create another issue or new PR yourself.

**Comment by Aleksey28** [comment] 2021-09-24 08:20
Hi @aafeltowicz,

Thank you for the suggestion. However, your suggestion is not related to this issue. This bug will be fixed with my PR. If you have other suggestions, you can create another issue or new PR yourself.

**Comment by aafeltowicz** [comment] 2021-09-24 09:18
I would disagree, as provided error strictly points problem with the circular dependency between these two classes, and having circular dependency is a bad design.

This also solves the problem with any setup of browsers in the config file while using the live mode, as for some magic reason passing browser alias from the command line doesn't break live mode.

**Comment by Aleksey28** [comment] 2021-09-24 14:05
Okay, I understood what you mean. I agree, that there is some problem with circular dependency. However, the reason for the bug is creating an 'alias' from an object which already has an 'alias'. Please create a new issue with your suggestion.

**Comment by aafeltowicz** [comment] 2021-09-24 17:51
Ok, I get your point now. New issue #6570

**Comment by doudsnjoy** [comment] 2021-10-04 19:36
I'm also encountering this issue with a custom angular component. This affects a critical area of our site where testing coverage is imperative. Is there an estimated date as to when this will be fixed?

**Closed as completed** 2021-10-22 12:08 UTC
Labels: TYPE: bug, AREA: server, SYSTEM: live mode, FREQUENCY: level 2
