### ISSUE TITLE
Getting Browser disconnected issue while running the testcafe test suite,BDD integrated

### ISSUE THREAD

**Issue by shariqMohammed92** [DevExpress/testcafe#3549] opened 2019-03-11 12:09 UTC
### What is your Test Scenario?
Multiple test scenarios has been written in feature files.

For each scenario,a browser session is launched and an user is logged in to perform the test actions.
 
 
### What is the Current behavior?
Currently after the execution of of first scenario in first feature file, no browser session is launched to carry out the activity and so the suite fails.

The suite runs fine in - Mac-Safri and Firefox

The suites fails in -Mac-Chrome,Unix-Chrome and Firefox
 
### What is the Expected behavior?
Expecting that for each scenario a browser session is launched and the actions is carried out seamless.

### What is your web application and your TestCafe test code?
our web application is a portal ,where different level of users has got different functions to perform.

The test suite covers the user functionalities
 
www.portaldev.connect.cantiz.com

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Download the project dependencies using- npm install
2. Once the dependencies are downloaded, run the command- npm run test-{broswerName}
3.See the error after running the suites
[connect-ui-automation.zip](https://github.com/DevExpress/testcafe/files/2952049/connect-ui-automation.zip)

 
### Your Environment details:
 
* testcafe version:   0.20.5
* node.js version:   v10.10.0
* command-line arguments:  npm run test-{broswerName}
* browser name and version: Mac-Chrome,Unix-Firefox and Chrome
* platform and version:   Mac version-macOS High Seirra v10.10.0

**Comment by AlexKamaev** [comment] 2019-03-11 15:37
You are using an outdated TestCafe version. I recommend that you update your TestCafe version to the latest one, 1.1.0.
If this does not help, please simplify your project since now it looks quite complex to research. Also., try to reproduce the issue without the Cucumber and see how it works.

**Comment by shariqMohammed92** [comment] 2019-03-13 11:04
Tried out with the latest version of Test cafe.The issue is resolved while running locally.

But while trying to run in Linux Machine through jenkins, no browser is getting launched and suite fails.Getting the following error:

**F----------------F.{ Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
    at /home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/testcafe/src/runner/browser-set.js:84:30
    at Generator.next (<anonymous>)
    at step (/home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at BrowserSet._waitConnectionsOpened (/home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/testcafe/src/runner/browser-set.js:77:37)
    at _waitConnectionsOpened (/home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/testcafe/src/runner/browser-set.js:107:35)
    at invokeCallback (/home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/pinkie/index.js:60:12)
    at Array.forEach (<anonymous>)
    at publish (/home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/pinkie/index.js:147:32)
    at Array.publishFulfillment (/home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/pinkie/index.js:152:2)
    at Immediate.asyncFlush [as _onImmediate] (/home/admin01/jenkinsworkspace/workspace/Nucleus-Testing-Team/Connect-UI-Automation-TestCafe-UnixChrome/connect-ui-automation/node_modules/pinkie/index.js:17:19)
    at runCallback (timers.js:812:20)
    at tryOnImmediate (timers.js:768:5) code: 'E1004', data: [] }**

The jenkins was started as a service in the machine

**Comment by miherlosev** [comment] 2019-03-14 12:52
@shariqMohammed92 
 
Would you please try to measure the free operation memory right after TestCafe raises this error?

**Comment by AlexKamaev** [comment] 2019-04-30 11:55
I closed this issue because we haven't received any response on our request for more information

**Closed by AlexKamaev** 2019-04-30 11:55 UTC
