### ISSUE TITLE
testcafe all launch browsers with profiles

### ISSUE THREAD

**Issue by mixman68** [DevExpress/testcafe#3899] opened 2019-06-15 17:47 UTC
### What is your Test Scenario?
basic.js from this repo
 
### What is the Current behavior?
When i launch a testcafe campain with `all` option, browsers are loaded with user profiles
 
### What is the Expected behavior?
When i launch a testcafe campain with `all` option, browsers are loaded with empty profiles as if i call `testcafe chrome`for example.
 
### What is your web application and your TestCafe test code?
basic.js from this repo
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

</details>

<details>
<summary>Your complete configuration file (if any):</summary>
basic.js from this repo

</details>

<details>
<summary>Your complete test report:</summary>
N/A

</details>

<details>
<summary>Screenshots:</summary>

</details>

### Steps to Reproduce:
Launch `testcafe all examples/basic/test.js`,
You will see your profile with all your extensions on Chrome, Firefox, etc..
 
### Your Environment details:
 
* testcafe version:                   master
* node.js version:                   8.9.1
* command-line arguments:  `testcafe all examples/basic/test.js`
* browser name and version: Safari 12, Chrome 75, Firefox67
* platform and version:          macOS 10.14.5
* other:

**Comment by AlexKamaev** [comment] 2019-06-17 09:35
Thank you for your detailed description. I was able to reproduce the issue.

**Comment by AndreyBelym** [comment] 2020-12-25 08:26
I've researched the issue and it seems that the only way to resolve it is to use a browser-specific provider for the `all` alias. Since there is another issue that describes this task: #5801, I'm closing this issue because it's a duplicate.

**Closed by AndreyBelym** 2020-12-25 08:26 UTC
Labels: AREA: server, FREQUENCY: level 1, SYSTEM: browser connection, TYPE: bug
