### ISSUE TITLE
Automatically opening an issue on Github failes

### ISSUE THREAD

**Issue by Lukas-Kullmann** [DevExpress/testcafe#2317] opened 2018-04-13 13:57 UTC
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

When you use Testcafe to open an issue on Github, you can't because the "Submit new issue" button is disabled

### What is the expected behavior?

The button is enabled once you start typing text into the issue's title field

### How would you reproduce the current behavior (if this is a bug)?

Run testcode below (do not forget to provide values for `<github-user>`, `<repo>`, `<user>`, and `<password>`)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://github.com/DevExpress/testcafe/issues/new

Test code

```js
test.before(async t => {
        await t.navigateTo('https://github.com/<github-user>/<repo>/issues');

        await t.click('[href^="/login"]');

        await t.typeText('#login_field', '<user>');
        await t.typeText('#password', '<password>');
        await t.click('[type="submit"]');

        await t.click('.issues-listing [href$="/issues/new"]');
    })
    .only('test open issue on github', async t => {

        const issueTitle = 'My awesome issue title';

        await t.typeText('#issue_title', issueTitle);

        // the submit button should now be enabled

        await t.click('.form-actions .btn-primary');

        await t.expect(Selector('h1').innerText).contains(issueTitle);
    });
```

### Specify your

* operating system: any
* testcafe version: 0.19.2
* node.js version: 8.11.1

**Comment by LavrovArtem** [comment] 2018-04-13 15:57
Hi @Lukas-Kullmann,
I've reproduced the problem and I will investigate it.

**Comment by MarinaRukavitsyna** [comment] 2018-04-16 10:05
Hello @Lukas-Kullmann,
While we are researching this issue, as a workaround, you can use [GitHub API](https://developer.github.com/v3/issues/#create-an-issue) to create an issue .

**Comment by LavrovArtem** [comment] 2018-04-27 15:08
The "new issue" page has wrong markup:
```html
<form class="new_issue">
    <input>
    <div>
        <!-- '"` --><!-- </textarea></xmp> --></option></form>
      <form class="js-label-form">
          <input>
      </form>
    </div>
```
Browser interpret it as:
```html
<form class="new_issue">
    <input>
    <div>
        <!-- '"` --><!-- </textarea></xmp> -->
      <form class="js-label-form">
          <input>
      </form>
    </div>
</form>
```

Our proxy server html parser interpret it as:

```html
<form class="new_issue">
    <input>
    <div>
        <!-- '"` --><!-- </textarea></xmp> -->
          <input>
    </div>
</form>
```

This issue is duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1434.

**Closed by LavrovArtem** 2018-04-27 15:08 UTC
Labels: AREA: client, SYSTEM: hammerhead, TYPE: bug
