### ISSUE TITLE
Unable to find the browser. "edge" when run in Gitlab CI 

### ISSUE THREAD

**Issue by adminter3** [DevExpress/testcafe#4051] opened 2019-07-19 09:26 UTC
### What is your Test Scenario?
I'am trying to run the test from Gitlab CI through the gitlab-runner that is installed in a windows machine. The gitlab-runner is excuting the job by shell excuter.
 
### What is the Current behavior?
When running the test from gitlab-runner to test against "Edge", testcafe doesn't find the "edge" and getting the error log:
ERROR Unable to find the browser. "edge" is not a browser alias or path to an executable file.

![fail_edge](https://user-images.githubusercontent.com/29160941/61524570-fc469f80-aa16-11e9-83b4-aab60757de24.PNG)

However, testing with chrome and firefox is just working fine. 
![succ_chrome](https://user-images.githubusercontent.com/29160941/61524601-0a94bb80-aa17-11e9-90bf-347e9d20f9d1.PNG)

And it works with the all locally installed browsers (Chrome,Firefox,Edge and IE) when when excuting 
`gitlab-runner exec shell Build_test` 

### What is the Expected behavior?
Testcafe should not complaine about "edge" 
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
A very simple test
```js
 import { config } from "../../../testEnvironment/config";
import { logger } from "../../hosting/logger";
import { Selector } from "testcafe";

fixture(`Project`)
  .page(config.httpsUrl_DevEnv)
  .requestHooks(logger.simpleLogger)
  .beforeEach(async () => {
    // await initialize(logger.simpleLogger);
  });

test("First automation test", async t => {
  await t.click(Selector("input[type=checkbox]")).click(Selector("button"));
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

.testcaferc.json
```
{
  "browsers": "edge",
  "debugMode": false,
  "debugOnFail": false,
  "developmentMode": false,
  "hostname": "localhost",
  "port1": "5050",
  "port2": "5051",
  "proxy": "proxy",
  "screenshotPath": "C:/reports/screenshots",
  "takeScreenshotsOnFails": true,
  "selectorTimeout": 40000,
  "src": ["src/ui/project/*.test.ts"],
  "quarantineMode": false
}

```
.gitlab-ci.yml
```
stages:
  - test
Build_test:
  stage: test
  script:
    - call npm ci
    - npm test
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>
 
### Your Environment details:
 
* testcafe version: 1.3.3                  
* node.js version:  v10.16.0                  
* browser name and version: Edge 16.16299.0 
* platform and version:    Windows 10

**Comment by miherlosev** [comment] 2019-07-19 12:14
Hi @adminter3 

Make sure that the Microsoft Edge browser works correctly. To do that, run `start microsoft-edge:"http://example.com"` in your terminal. After that, the browser should start and open the `http://example.com` web site. If the browser is not started, it means there is some problem with it, and you should fix it.

If the browser is started correctly, you need to validate TestCafe' search browser mechanism.
TestCafe searches the Microsoft Edge location by the Windows registry.
Please run the `reg query HKCU\Software\Classes\ActivatableClasses /s /f  MicrosoftEdge /k` command in your terminal.
The result should be as follows:
![image](https://user-images.githubusercontent.com/4133518/61531244-f0ff6e00-aa2e-11e9-9e81-c8a498cfe34c.png)

If you get a different result, please open the `regedit` utility, find the `MicrosoftEdge` key location (Ctrl+F) and provide us with the search result.

**Comment by adminter3** [comment] 2019-07-19 12:47
@miherlosev Thanks for answering!
I run the req query and the result was different from yours, 
![edge_reg_query](https://user-images.githubusercontent.com/29160941/61533406-168b7800-aa2d-11e9-82db-e017a98777ef.PNG)

And that is my search result in the reqedit as you requested.
![edge_regedit](https://user-images.githubusercontent.com/29160941/61533451-3b7feb00-aa2d-11e9-9897-82d763f926e3.PNG)

BR

**Comment by aleks-pro** [comment] 2019-07-22 11:26
Hello @adminter3 ,

Thank you for this information. At first sight, everything looks ok on your machine. We have an assumption that TestCafe process has no enough rights to read from the Windows registry or to start the browser. To check this, we will create a development build that provides a corresponding error message. We will update this thread as soon as the build is ready.

**Comment by AndreyBelym** [comment] 2019-07-24 11:31
@adminter3, thank you for your patience, I prepared a debug 
TestCafe build: https://github.com/AndreyBelym/testcafe/releases/download/edge-error-1/testcafe-1.3.3.tgz

You can install it with
```
npm i https://github.com/AndreyBelym/testcafe/releases/download/edge-error-1/testcafe-1.3.3.tgz
```
or add to your `package.json` in the following way:
```json
{
    "devDependencies": {
        "testcafe": "https://github.com/AndreyBelym/testcafe/releases/download/edge-error-1/testcafe-1.3.3.tgz"
    }
}
```
Please, run the debug build and share the generated CLI output.

**Comment by adminter3** [comment] 2019-07-24 11:48
Thanks for you @AndreyBelym 
Here is the output 
```
> testcafe

stdout 
C:\Gitlab-runner\builds\T2ffLWHU\0\WebTools\Tools\site-designer-2-e2e-automation-test>(chcp 65001   & reg query HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet /s   & chcp  437 ) 
Active code page: 65001

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet
    (Default)    REG_SZ    IEXPLORE.EXE

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB
    (Default)    REG_SZ    Mozilla Firefox

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\Capabilities
    ApplicationDescription    REG_SZ    Firefox delivers safe, easy web browsing. A familiar user interface, enhanced security features including protection from online identity theft, and integrated search let you get the most out of the web.
    ApplicationIcon    REG_SZ    C:\Program Files\Mozilla Firefox\firefox.exe,0
    ApplicationName    REG_SZ    Firefox

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\Capabilities\FileAssociations
    .htm    REG_SZ    FirefoxHTML-308046B0AF4A39CB
    .html    REG_SZ    FirefoxHTML-308046B0AF4A39CB
    .shtml    REG_SZ    FirefoxHTML-308046B0AF4A39CB
    .xht    REG_SZ    FirefoxHTML-308046B0AF4A39CB
    .xhtml    REG_SZ    FirefoxHTML-308046B0AF4A39CB

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\Capabilities\StartMenu
    StartMenuInternet    REG_SZ    Firefox-308046B0AF4A39CB

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\Capabilities\URLAssociations
    ftp    REG_SZ    FirefoxURL-308046B0AF4A39CB
    http    REG_SZ    FirefoxURL-308046B0AF4A39CB
    https    REG_SZ    FirefoxURL-308046B0AF4A39CB

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\DefaultIcon
    (Default)    REG_SZ    C:\Program Files\Mozilla Firefox\firefox.exe,0

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\InstallInfo
    HideIconsCommand    REG_SZ    "C:\Program Files\Mozilla Firefox\uninstall\helper.exe" /HideShortcuts
    ShowIconsCommand    REG_SZ    "C:\Program Files\Mozilla Firefox\uninstall\helper.exe" /ShowShortcuts
    ReinstallCommand    REG_SZ    "C:\Program Files\Mozilla Firefox\uninstall\helper.exe" /SetAsDefaultAppGlobal
    IconsVisible    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\shell

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\shell\open

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\shell\open\command
    (Default)    REG_SZ    "C:\Program Files\Mozilla Firefox\firefox.exe"

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\shell\properties
    (Default)    REG_SZ    Firefox &Options

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\shell\properties\command
    (Default)    REG_SZ    "C:\Program Files\Mozilla Firefox\firefox.exe" -preferences

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\shell\safemode
    (Default)    REG_SZ    Firefox &Safe Mode

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\shell\safemode\command
    (Default)    REG_SZ    "C:\Program Files\Mozilla Firefox\firefox.exe" -safe-mode

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome
    (Default)    REG_SZ    Google Chrome

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\Capabilities
    ApplicationDescription    REG_SZ    Google Chrome är en webbläsare som kör webbsidor och program med ljusets hastighet. Den är snabb, stabil och lätt att använda. Surfa säkrare med Google Chrome, som har inbyggt skydd mot skadlig programvara och nätfiske.
    ApplicationIcon    REG_SZ    C:\Program Files (x86)\Google\Chrome\Application\chrome.exe,0
    ApplicationName    REG_SZ    Google Chrome

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\Capabilities\FileAssociations
    .htm    REG_SZ    ChromeHTML
    .html    REG_SZ    ChromeHTML
    .pdf    REG_SZ    ChromeHTML
    .shtml    REG_SZ    ChromeHTML
    .svg    REG_SZ    ChromeHTML
    .xht    REG_SZ    ChromeHTML
    .xhtml    REG_SZ    ChromeHTML
    .webp    REG_SZ    ChromeHTML

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\Capabilities\Startmenu
    StartMenuInternet    REG_SZ    Google Chrome

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\Capabilities\URLAssociations
    ftp    REG_SZ    ChromeHTML
    http    REG_SZ    ChromeHTML
    https    REG_SZ    ChromeHTML
    irc    REG_SZ    ChromeHTML
    mailto    REG_SZ    ChromeHTML
    mms    REG_SZ    ChromeHTML
    news    REG_SZ    ChromeHTML
    nntp    REG_SZ    ChromeHTML
    sms    REG_SZ    ChromeHTML
    smsto    REG_SZ    ChromeHTML
    tel    REG_SZ    ChromeHTML
    urn    REG_SZ    ChromeHTML
    webcal    REG_SZ    ChromeHTML

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\DefaultIcon
    (Default)    REG_SZ    C:\Program Files (x86)\Google\Chrome\Application\chrome.exe,0

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\InstallInfo
    ReinstallCommand    REG_SZ    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --make-default-browser
    HideIconsCommand    REG_SZ    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --hide-icons
    ShowIconsCommand    REG_SZ    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --show-icons
    IconsVisible    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\shell

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\shell\open

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\shell\open\command
    (Default)    REG_SZ    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE
    (Default)    REG_SZ    Internet Explorer
    LocalizedString    REG_SZ    @C:\Program Files\Internet Explorer\iexplore.exe,-702

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\DefaultIcon
    (Default)    REG_SZ    C:\Program Files\Internet Explorer\iexplore.exe,-9

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\InstallInfo
    IconsVisible    REG_DWORD    0x1
    HideIconsCommand    REG_SZ    "C:\Windows\System32\ie4uinit.exe" -hide
    ReinstallCommand    REG_SZ    "C:\Windows\System32\ie4uinit.exe" -reinstall
    ShowIconsCommand    REG_SZ    "C:\Windows\System32\ie4uinit.exe" -show

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\naom
    MUIVerb    REG_SZ    @C:\Windows\System32\ieframe.dll,-39229

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\naom\command
    (Default)    REG_SZ    "C:\Program Files\Internet Explorer\iexplore.exe" -extoff

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\open

HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\open\command
    (Default)    REG_SZ    C:\Program Files\Internet Explorer\iexplore.exe

Active code page: 437

stderr 
stdout 
C:\Gitlab-runner\builds\T2ffLWHU\0\WebTools\Tools\site-designer-2-e2e-automation-test>(chcp 65001   & reg query HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet /s   & chcp  437 ) 
Active code page: 65001
Active code page: 437

stderr ERROR: The system was unable to find the specified registry key or value.

stdout 
C:\Gitlab-runner\builds\T2ffLWHU\0\WebTools\Tools\site-designer-2-e2e-automation-test>(chcp 65001   & ) 
Active code page: 65001
FAIL 
Active code page: 437

stderr ERROR: The system was unable to find the specified registry key or value.

Edge is not found
ERROR Unable to find the browser. "edge" is not a browser alias or path to an executable file.

Type "testcafe -h" for help.
npm ERR! Test failed.  See above for more details.
section_end:1563968762:build_script
[0Ksection_start:1563968762:upload_artifacts_on_failure
[0Ksection_end:1563968763:upload_artifacts_on_failure
[0K[31;1mERROR: Job failed: exit status 1
[0;m
```
BR

**Comment by AndreyBelym** [comment] 2019-07-24 12:19
Thank you for providing this information. According to this article: [Install GitLab Runner on Windows](https://docs.gitlab.com/runner/install/windows.html), `gitlab-runner` can be configured to run under a build-in system account or a specific user account. If your `gitlab-runner` runs under a built-in system account, please reconfigure it to run under the user account that you used to execute the `reg query` command in [this comment](https://github.com/DevExpress/testcafe/issues/4051#issuecomment-513215644).

**Comment by adminter3** [comment] 2019-07-24 12:52
> Thank you for providing this information. According to the [Install GitLab Runner on Windows](https://docs.gitlab.com/runner/install/windows.html) article, `gitlab-runner` can be configured to run under a build-in system account or a specific user account. If your `gitlab-runner` runs under a built-in system account, please reconfigure it to run under the user account that you used to execute the `reg query` command in [this comment](https://github.com/DevExpress/testcafe/issues/4051#issuecomment-513215644).

Yes, it worked when changed reconfigured the Runner to use the use account instead of the system account.
It was my bad to not figure this out ;)
BR

**Comment by AndreyBelym** [comment] 2019-07-24 12:56
I'm glad that the issue is resolved. It looks like Microsoft Edge can't be started under the `SYSTEM` account, so I close this issue.

**Closed by AndreyBelym** 2019-07-24 12:56 UTC
Labels: STATE: Need research, STATE: Need response
