### ISSUE TITLE
Browsers are not getting closed after test execution

### ISSUE THREAD

**Issue by vasantverma-LM** [DevExpress/testcafe#5274] opened 2020-07-01 09:08 UTC
Are you requesting a feature or reporting a bug?
Bug

What is the current behavior?
Browsers are not getting closed after the tests are run. (Show "Connected") and therefore data is not logged into reports.

What is the expected behavior?
Browsers should close after running tests.
![Screenshot (37)](https://user-images.githubusercontent.com/66365851/86225766-4da85a00-bba8-11ea-8d6b-c314ae5e4e62.png)
![Screenshot (36)](https://user-images.githubusercontent.com/66365851/86225771-4ed98700-bba8-11ea-8371-131b44325262.png)

How would you reproduce the current behavior (if this is a bug)?
testcafe chrome,edge,firefox ./tests/filename.js -s takeOnFails=true -e --reporter cucumber-json:reports/report.json

Specify your
operating system: Windows 10
testcafe version: v1.8.6
node.js version: v12.18.0
testcafe-reporter-cucumber-json": v5.1.0

**Comment by AlexKamaev** [comment] 2020-07-02 07:29
I was not able to reproduce the issue.
I executed the following tests:

```JS
fixture `f`
    .page `http://example.com`;

test('1', async t => {
    await t.click('h1');
});

test('2', async t => {
    await t.click('h1');
});

test('3', async t => {
    await t.click('h1');
});
```

with the following command line arguments: `testcafe chrome,ie,firefox test.js -s takeOnFails=true -e --reporter cucumber-json:reports/report.json --reporter-app-name='My app' --reporter-app-version='x.y.z'`

All tests passed as expected and browser were closed.
Please create a sample project or modify my test code to help us to reproduce the issue.

In addition, please check if the issue exists with testcafe default reporters. If it occurs only with `cucumber-json`, you can create a separate issue in the [https://github.com/hdorgeval/testcafe-reporter-cucumber-json](https://github.com/hdorgeval/testcafe-reporter-cucumber-json) repository.

**Comment by vasantverma-LM** [comment] 2020-07-03 11:30
Hi  @AlexKamaev the browser is not getting closed if I am using the cucumber-json:reports/report.json. If I am running the execution without the reporter, the browsers are getting closed.

**Comment by Ogurecher** [comment] 2020-07-03 14:38
@vasantverma-LM, This issue is likely related to testcafe-reporter-cucumber-json. Please create a separate issue in [this project's repository](https://github.com/hdorgeval/testcafe-reporter-cucumber-json/issues). It's a custom reporter and we are not maintaining this repository. I'll close this issue now.

**Closed by Ogurecher** 2020-07-03 14:38 UTC
Labels: STATE: Need response
