### ISSUE TITLE
"reportFixtureStart" hook is not called correctly when testcafe is running with multiple thread

### ISSUE THREAD

**Issue by IssacH** [DevExpress/testcafe#6052] opened 2021-03-16 09:04 UTC
### What is your Test Scenario?
1. I have one test.js, which contains case a in fixture A, case b in fixture B
2. I was trying to run the test with multiple thread
testcafe chrome -c 2 ./tests/firstTest.js --skip-js-errors

 
### What is the Current behavior?
"reportFixtureStart" hook is not called correctly
 Current order:
reportFixtureStart - reportTestStart - reportTestStart - reportFixtureStart 
### What is the Expected behavior?
 "reportFixtureStart" hook should be called correctly
Expected order:
reportFixtureStart - reportTestStart - reportFixtureStart - reportTestStart 

### What is your web application and your TestCafe test code?

 
* testcafe version:  1.12.0
* node.js version:    v10.23.0
[firstTest.txt](https://github.com/DevExpress/testcafe/files/6147444/firstTest.txt)

**Comment by Farfurix** [comment] 2021-03-17 07:19
@IssacH 

Hello,

This issue is a duplicate of https://github.com/DevExpress/testcafe/issues/4951. So, I'll close it.

**Closed by Farfurix** 2021-03-17 07:19 UTC
Labels: STATE: Need response
