### ISSUE TITLE
xunit reporting does not work with version 1.16.1 of testcafe

### ISSUE THREAD

**Issue by bbutel** [DevExpress/testcafe#6664] opened 2021-10-29 15:46 UTC
### What is your Test Scenario?
I use gherkin-testcafe with testcafe to run test.
I configure xunit reporting in .testcaferc.json as well:
"""
    "reporter": [
        {
            "name": "list"
        },
        {
            "name": "xunit",
            "output": "results/results.xml"
        }
    ],
"""

When I run my test with testcafe version 1.16.0, it does work and a folder results with a file is created at the start of test and file results.xml is filled at the end of the run.
 
### What is the Current behavior?
BUT with version 1.16.1, it does not work.
No folder and no file are created at the beginning of run.
 
### What is the Expected behavior?
at the end of test, I expect my results.xml filled with appropriate running information.
 
### What is your web application and your TestCafe test code?
N/A
 
### Steps to Reproduce:

See above
 
### Your Environment details:
 
* testcafe version:                    1.16.1
* node.js version:                   12.22.7
* command-line arguments:  gherkin-testcafe my_features_folder my_step_def_folder 
* browser name and version: Chrome 95.0.4638.54 / Linux 0.0
* platform and version:           42~20.04.1-Ubuntu

**Comment by miherlosev** [comment] 2021-11-01 08:01
Duplicate of https://github.com/DevExpress/testcafe/issues/6594

**Closed by miherlosev** 2021-11-01 08:01 UTC
Labels: STATE: Need response
