### ISSUE TITLE
TestCafe Salesforce Automation - hammerhead Error "This page has an error. You might need to refresh it"

### ISSUE THREAD

**Issue by ArunjaiAcc** [DevExpress/testcafe#6459] opened 2021-08-12 09:06 UTC
### What is your Test Scenario?
Via automation tried to navigate to create firm/ create contact layout
 
### What is the Current behavior?
*Error on opening the page via test cafe*

[Cannot read property 'hammerhead|event|internal-blur' of null]
_	cancelInternalEvents()@http://192.168.0.9:52557/hammerhead.js:13:27910
{anonymous}()@http://192.168.0.9:52557/hammerhead.js:12:6
HTMLElement.dispatchEvent()@http://192.168.0.9:52557/hammerhead.js:13:27061
me.handleBlur()@https://preqin--uat.lightning.force.com/components/lightning/input.js:1:35128
 
### What is the Expected behavior?
The page should load successfully and the user able to add the details
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>https://preqin--uat.lightning.force.com/</summary>
Debug Logs:
[Cannot read property 'hammerhead|event|internal-blur' of null]
_	cancelInternalEvents()@http://192.168.0.9:52557/hammerhead.js:13:27910
{anonymous}()@http://192.168.0.9:52557/hammerhead.js:12:6
HTMLElement.dispatchEvent()@http://192.168.0.9:52557/hammerhead.js:13:27061
me.handleBlur()@https://preqin--uat.lightning.force.com/components/lightning/input.js:1:35128

</details>

<details>
<summary>
</summary>

 
```js
 
```
</details>

<details>
<summary>import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `Env Url`;
    
test('New Test', async (t: TestController) => {
    await t
        .click('#username')
        .typeText('#username', '******')
        .click('#password')
        .typeText('#password', '*****')
        .click('#Login')
        .click(Selector('button').withText('Show Navigation Menu'))
        .click(Selector('#navMenuList span').withText('Firms').nth(1))
        .click(Selector('#brandBand_1 div').withText('New').nth(7))
        .click(Selector('#brandBand_2 span').withText('Next'))
        .wait(8000);
});
</summary>

```

```
</details>

<details>
<summary></summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Navigate to FIrm/Contact page
4. Click on new
5. See the error (Viewed only via automation)
 
### Your Environment details:
 
* testcafe version:                   <1.15.2>
* node.js version:                    <v12.18.2>
* command-line arguments:  
* browser name and version: <Version 92.0.4515.131>
* platform and version:          < Windows>
* other:

**Comment by Farfurix** [comment] 2021-08-16 08:08
@ArunjaiAcc 

Hello,

We would love to assist you and diagnose this issue. However, since your website requires authentication, I will not be able to access it. Our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource. If you want us to research the problem further, we’ll need access to the server/web resource and your account using your credentials. Please send us ([support@devexpress.com](mailto:support@devexpress.com)) written confirmation. It must permit DevExpress personnel to remotely access your website account and its internal resources for research/testing/and debugging purposes.

Could you please send the complete test code with credentials and the written confirmation to our mailbox: support@devexpress.com?

**Comment by ArunjaiAcc** [comment] 2021-08-20 05:16
Sure, I will share the same @Farfurix

**Comment by aleks-pro** [comment] 2021-08-23 08:04
@ArunjaiAcc , please leave a comment here after you send the confirmation to support@devexpress.com.

**Comment by ArunjaiAcc** [comment] 2021-08-24 04:22
I have shared the detail with support@devexpress.com. Please check into this @aleks-pro

**Comment by Farfurix** [comment] 2021-08-25 07:33
@ArunjaiAcc 

Hello,
We couldn't find your Email. Would you please re-send it? How do we identify it?

**Comment by ArunjaiAcc** [comment] 2021-08-25 08:22
Hi Team,

Please find the attached source code for automation.

Regards,
Arunkumar

**Comment by ArunjaiAcc** [comment] 2021-08-30 12:10
Hello @Farfurix  I re-sended it

**Comment by ArunjaiAcc** [comment] 2021-08-30 12:14
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `Env Url`;
    
test('New Test', async (t: TestController) => {
    await t
        .click('#username')
        .typeText('#username', '******')
        .click('#password')
        .typeText('#password', '*****')
        .click('#Login')
        .click(Selector('button').withText('Show Navigation Menu'))
        .click(Selector('#navMenuList span').withText('Firms').nth(1))
        .click(Selector('#brandBand_1 div').withText('New').nth(7))
        .click(Selector('#brandBand_2 span').withText('Next'))
        .wait(8000);
});

**Comment by Farfurix** [comment] 2021-09-01 08:32
@ArunjaiAcc 

Hello,

I reproduced this issue by clicking the following drop-down menu:
![Capture](https://user-images.githubusercontent.com/30019338/131634838-92009ef6-5727-410f-ad2b-7b48985de82e.PNG)
We will update this thread once we have any news.

As a workaround, you can use another way to reach the "New Firms" page, without clicking a drop-down menu:
1. Click the "Firms" tab
2. Click the "New" button

**Comment by ArunjaiAcc** [comment] 2021-09-01 12:29
Thanks, I'll check it out.

**Comment by aozomaro** [comment] 2022-08-31 13:37
Hi that work around doesn’t work. I have the same issue only I browse directly to the page and it still fails. This has been broken since June, is there a plan to resolve this issue?

**Comment by Aleksey28** [comment] 2022-09-02 09:41
Hi @aozomaro,

Please share your example for further research. There must be another issue.

**Comment by Artem-Babich** [comment] 2023-02-06 14:06
Hello @ArunjaiAcc, 

I've just tried to reproduce this issue with testcafe@2.3.1-alpha-1. However, the testing URL you shared is no longer available. 
Could you try running your test with testcafe@2.3.1-alpha-1 with the [experimental-proxyless option](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode) enabled? This option enables native browser automation. In Proxyless mode, a few issues are already fixed. This issue might also be fixed in Proxyless mode.
This option is available in all interfaces:
```js
// Command-line
testcafe chrome tests --experimental-proxyless   

// Programmatic
const testcafe = await createTestCafe({ experimentalProxyless: true });

// Configuration file
{
"experimentalProxyless": "true"
} 
```
Please keep in mind that this mode is experimental. Also, the Proxyless mode is implemented only in Google Chrome. It will not work correctly if you run tests in a non-Chrome browser or in a combination of other browsers.

**Comment by ArunjaiAcc** [comment] 2023-02-06 18:36
Hi,
Sure, I will check and let you know.

Regards,
Arunkumar

**Closed** 2023-02-23 09:10 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, STATE: Need clarification, FREQUENCY: level 1, HAS WORKAROUND
