### ISSUE TITLE
tests won't load on Windows 10 in chrome,edge

### ISSUE THREAD

**Issue by Hotell** [DevExpress/testcafe#1633] opened 2017-07-20 21:07 UTC
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
test page is never loaded and test will hang forever

![image](https://user-images.githubusercontent.com/1223799/28438562-e0f7c08a-6d9e-11e7-8427-a2657cae6fe1.png)

the same issue is with Chrome

![image](https://user-images.githubusercontent.com/1223799/28438682-45d54d7e-6d9f-11e7-8c9b-a9e52c7e2949.png)

```
yarn testcafe v0.24.6
$ "C:\Users\hoche\Documents\Devel\test\testcafe-example\node_modules\.bin\testcafe" chrome test.js
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

### What is the expected behavior?
working tests on windows 10

### How would you reproduce the current behavior (if this is a bug)?

```sh
mkdir bug-repro && cd $_ && 
yarn add -D testcafe && touch test.js 
```

paste source in `test.js`

run `yarn testcafe chrome test.js`
 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
import { Selector } from 'testcafe'

fixture`My first fixture`.page`https://devexpress.github.io/testcafe/example`

const articleHeader = Selector('#article-header')

test('My first test', async t => {
  await t
    .typeText('#developer-name', 'Peter Parker')
    .click('#submit-button')
    .expect(articleHeader.innerText)
    .eql('Thank you, Peter Parker!')
})

```

### Specify your

* operating system: Windows 10 Creators Update
* testcafe version:  0.16.2
* node.js version:  8.1.4

**Comment by kirovboris** [comment] 2017-07-21 12:21
Hi @Hotell,

Could you please check your firewall settings? You can specify custom ports
https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ports-port1port2

Also if you use proxy server to access the Internet, please specify your proxy settings
https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--proxy-host

**Comment by Hotell** [comment] 2017-07-21 16:44
HI @kirovboris doesn't work at all

turned off firewall, even when I'm testing it on [this repo example](https://github.com/DevExpress/testcafe/blob/master/examples/running-tests-in-firefox-and-chrome-using-travis-ci/) ( which is local ) it doesn't work 

any suggestions ?

thx

**Comment by kirovboris** [comment] 2017-07-22 06:19
Please try to specify `localhost` or `127.0.0.1` as hostname.
```batch
testcafe chrome test.js --hostname 127.0.0.1
```

**Comment by Hotell** [comment] 2017-07-22 06:25
bang! worked ! any ideas why the default IP doesn't work though? on mac it works with default settings

![image](https://user-images.githubusercontent.com/1223799/28488974-4925d408-6eb7-11e7-8a18-4230e0b90f45.png)

**Comment by kirovboris** [comment] 2017-07-22 06:53
It is a known issue, we plan to improve the hostname detection https://github.com/DevExpress/testcafe/issues/986

**Comment by Hotell** [comment] 2017-07-22 16:41
@kirovboris  cool would you accept a PR to docs which will mention this issue + how to fix it ? :) thx for help again! cheers

**Comment by kirovboris** [comment] 2017-07-24 09:06
Thank you for the idea, @Hotell. We're going to create a new section on our site that will describe known issues.

**Comment by AlexanderMoskovkin** [comment] 2017-07-31 09:43
I close it since the problem is resolved

**Closed by AlexanderMoskovkin** 2017-07-31 09:43 UTC
Labels: REASON: duplicate, TYPE: bug

**Comment by Hotell** [comment] 2017-07-31 10:29
sure thingy, thanks for help folks!
