### ISSUE TITLE
Proxy support for mixed-case Header names

### ISSUE THREAD

**Issue by brettveenstra** [DevExpress/testcafe#1422] opened 2017-04-18 19:33 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
We are using AureliaJS framework (with Fetch and Http libraries) where we can set HTTP request defaults so that `content-type` header is defined for each request (e.g. `application/json`).  We can capture traffic showing the Requests are setting a header `content-type: application/json` but when running under TestCafe the header does not get to the HTTP endpoint.  Suspecting there is either case sensitivity in the HTTP headers for the proxy or only a subset of headers are supported.

### What is the expected behavior?
Any header would be transferred for all HTTP traffic **and** header field names are case-insensitive per RFC 2616 ... common examples:

* `content-type` vs. `Content-Type`
* `accept` vs. `Accept`

### How would you reproduce the current behavior (if this is a bug)?
Specify a header named `content-type` and/or `accept` before making HTTP request against an endpoint that you control ... debug/output all the headers received from each request, note that lower-cased headers are not supplied in Requests.

### Specify your

* operating system: Windows
* testcafe version: 0.15.0.alpha-2
* node.js version: 6.3.0

**Comment by miherlosev** [comment] 2017-04-21 10:15
Yes. HTTP headers are case-insensitive. 
The `http` module lower-cases all incoming headers to make accessing them easier.
So, header lowercasing is not the reason why 
> note that lower-cased headers are not supplied in Requests.

Please provide an example which I could use to reproduce the problem.

**Comment by LavrovArtem** [comment] 2017-05-11 15:50
@brettveenstra
Your problem was reproduced. See DevExpress/testcafe-hammerhead#1116

**Comment by AlexanderMoskovkin** [comment] 2017-05-24 07:42
fixed in `testcafe@0.16.0-alpha3`

**Closed by AlexanderMoskovkin** 2017-05-24 07:42 UTC
Labels: SYSTEM: hammerhead, TYPE: bug
