### ISSUE TITLE
www-authenticate override causes not working log in with SSO Kerberos

### ISSUE THREAD

**Issue by jpleerdam** [DevExpress/testcafe#6742] opened 2021-11-30 13:37 UTC
### What is your Scenario?

Our system under test calls an authorization end point (kerberos) but 401 unauthorized is returned while the current user has sufficient rights.

### What is the Current behavior?

The parameter www-authenticate is overriden by testcafe with value: ~~~TestCafe added this prefix to hide the authentication dialog box~~~Negotiate

This causes the login mechanism to fail. We've tried to override this value by creating an custom request hook but value is still overwriten.

### What is the Expected behavior?

Testcafe shouldn't overwrite parameters of the request to the authorization endpoint. 

### What is your public website URL? (or attach your complete example)

internal application 

### What is your TestCafe test code?

import { RequestHook } from 'testcafe';

export class AuthenticationHook extends RequestHook {
    constructor () {
        super();
    }

    async onRequest (e) {
        e.requestOptions.headers.authorization = 'generate token here';
    }

    async onResponse (e) {
    }
}

import { App } from './app.page-objects';
import { AuthenticationHook }  from "./../../hooks/authenticationhook";

const app = new App();
const authenticationHook = new AuthenticationHook();

export class AppActions {
  async navigateTo(t: TestController) {
    await t.addRequestHooks(authenticationHook);
    await t.navigateTo("https://localhost:4200");
    await t.debug();
  }
}

### Your complete configuration file

{
  "browsers": ["chrome -allow-insecure-localhost"],
  "src": ["e2e/src/steps/*.ts", "e2e/src/pages/**/*.ts", "e2e/src/features/*.feature"],
  "reporter": {
    "name": "xunit",
    "output": "./e2e/src/reports/report.xml"
  },
  "screenshots": {
    "path": "./e2e/src/reports/screenshots/",
    "takeOnFails": true,
    "pathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
  },
  "port1": 12345,
  "port2": 54321,
  "hostname": "localhost",
  "ssl": {
    "pfx": "./certificate/localhost.pfx",
    "passphrase": "****",
    "rejectUnauthorized": true
  },
  "tsConfigPath": "./e2e/tsconfig.json"
}

### Steps to Reproduce

1 - Our application calls an authorization endpoint which has a security constraint (which triggers single sign on - kerberos)
2 - 401 unauthorized is returned by the endpoint while the logged in user has sufficient rights.
(same user - same domain works outside testcafe)

### TestCafe version

1.17.1

### Node.js version

v12.15.0

### Command-line arguments

testcafe chrome general.feature

### Browser name(s) and version(s)

Chrome 96

### Platform(s) and version(s)

Windows

**Comment by Farfurix** [comment] 2021-12-02 07:41
@jpleerdam 

Hello,

We shared some notes regarding the SSO Kerberos authentication issue here: https://github.com/DevExpress/testcafe/issues/3500#issuecomment-468674576. If it doesn't help you, please share a [reproducible example](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue), so that we can examine your case on our side.

Please note that if you want to share (via mailto:support@devexpress.com) your internal application with us, we'll need a written approval. Our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource/application. If you want us to research the problem further, we’ll need access to the server/web resource/application. Please ask the website/application owner to send us (mailto:support@devexpress.com) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by jpleerdam** [comment] 2021-12-03 14:16
Dear Farfux,

Thanks for your inquiry; The const AUTHENTICATE_PREFIX in testcafe-hammerhead causes the 401 (the original header www-authenticate is overwritten). It should be an option in testcafe to enable / disable the use of the authentication / authorization mechanism of testcafe.  If disabled then the original header shouldn't be changed.

The solution mentioned in #3500 is an server side solution. 

Thanks in advance.

**Comment by Farfurix** [comment] 2021-12-07 09:33
@jpleerdam 

Hello,

We still need [a reproducible example](https://github.com/DevExpress/testcafe/issues/6742#issuecomment-984367778) to examine this authentication issue. Could you please share it with us?

**Comment by jpleerdam** [comment] 2021-12-07 14:32
Dear Farfurix,

thanks to company policy / confidential information it's not possible to create an example.

Working version in dev environment:
![image](https://user-images.githubusercontent.com/3472214/145046579-4cbf5dc0-837f-4cf8-8b06-880f22ea2dc7.png)
![image](https://user-images.githubusercontent.com/3472214/145046872-8929a1ab-27b1-4b4e-9df0-08199452ba29.png)
![image](https://user-images.githubusercontent.com/3472214/145047440-c98da02a-3532-43df-b54d-7f388d0c0012.png)

Testcafe hammerhead version (proxy version of dev environment:
![image](https://user-images.githubusercontent.com/3472214/145047607-0aad2a33-aa70-483f-9d60-e2fbaab5dc07.png)
![image](https://user-images.githubusercontent.com/3472214/145047707-998b1392-43e4-42e5-ab28-848eb0d2f285.png)
![image](https://user-images.githubusercontent.com/3472214/145047888-12cb428e-b802-461f-881e-771d7e61b0ed.png)

Thanks in advance, kind regards.
Jate Leerdam

**Comment by Farfurix** [comment] 2021-12-08 08:41
@jpleerdam 

>The parameter www-authenticate is overriden by testcafe with value: ~~~TestCafe added this prefix to hide the authentication dialog box~~~Negotiate
>
>This causes the login mechanism to fail. We've tried to override this value by creating an custom request hook but value is still overwriten.

This behavior is expected. It was implemented to avoid showing the native browser dialog for HTTP authentication. However, the original web application server gets a request with clear headers (without any TestCafe prefix).
It looks like the issue is related to your Kerberos configuration (protocol version, client/server specification, etc.), so we cannot reproduce the issue without an example. As a workaround, you can try using [HTTP Authentication](https://testcafe.io/documentation/402845/guides/advanced-guides/authentication#http-authentication).
We will close this issue. Feel free to share some reproducible example here or in a new bug report.

**Closed by Farfurix** 2021-12-08 08:41 UTC
Labels: TYPE: bug, STATE: Need response
