### ISSUE TITLE
TestCafe fails to switch to new window opened from an iframe

### ISSUE THREAD

**Issue by ironmakh** [DevExpress/testcafe#5437] opened 2020-08-19 15:55 UTC
### What is your Test Scenario?
1. Navigate to embedding emulator, request a resource to be displayed in embedded site
2. Resource is displayed in embedded site(inside an iframe) - switch to iframe, click [ login ] button
3. Login screen opened in a new window - perform login
4. Close the window
5. Return to embedded site(back to same iframe)
 
### What is the Current behaviour?
TestCafe fails to switch to new window in step 3
 
### What is the Expected behaviour?
TestCafe switches to new window in step 3
 
### What is your web application and your TestCafe test code?
Unfortunately this is all built for internal staging environment and I'm terribly sorry, but I cannot share the URL 

 
I tried all possible approaches I could think of to get to login dialog in a newly opened window:

1. Trying to perform login actions directly:
```
await t
           
           //Navigating to emulator and requesting the resource, not relevant for the case here

            .switchToIframe(iframe)
            .click(embeddedLoginButton) // this opens login dialog in a new window
            .typeText(Selector(`#emailOrUsername`), username, {paste:true , replace:true})
            .typeText(Selector(`#password`), password, {paste:true , replace:true})
```
Error: The specified selector does not match any element in the DOM tree.
      
       > | Selector('#emailOrUsername')

2. Switching back to main window(in hope that it might switch focus to newly opened login window from there)
```
await t
           
           //Navigating to emulator and requesting the resource, not relevant for the case here

            .switchToIframe(iframe)
            .click(embeddedLoginButton) // this opens login dialog in a new window
            .switchToMainWindow()
            .typeText(Selector(`#emailOrUsername`), username, {paste:true , replace:true})
            .typeText(Selector(`#password`), password, {paste:true , replace:true})
```
Error: Identical to case 1.

3. t.switchToWindow()
```
await t
           
           //Navigating to emulator and requesting the resource, not relevant for the case here

            .switchToIframe(iframe)
            .click(embeddedLoginButton) // this opens login dialog in a new window
            .switchToMainWindow()    //also if you comment out switching to main window before that - doesn't affect the result
            .switchToWindow(w => w.pathname === "/login?closeOnLogin")  // also tried w.url.host and w.title
```
Error: Cannot find the window specified in the action parameters.

4. Trying to grab window coordinates first:
```
await t
           
           //Navigating to emulator and requesting the resource, not relevant for the case here

            .switchToIframe(iframe)
            .click(embeddedLoginButton) // this opens login dialog in a new window
 const currWindow = await t.getCurrentWindow()
          await t
            .switchToWindow(currWindow)
            .typeText(Selector(`#emailOrUsername`), username, {paste:true , replace:true})
            .typeText(Selector(`#password`), password, {paste:true , replace:true})
```
Error: Cannot switch to the window.

In debug mode this child window is not available in any manner either.
</details>

### Your Environment details:
 
* testcafe version:                   1.9.1
* node.js version:                    v12.16.0
* command-line arguments:  none. 
* browser name and version: Chrome 84.0.4147.125
* platform and version:          macOS 10.15.2

**Comment by AndreyBelym** [comment] 2020-08-20 08:05
Thank you for your report with the following setup:

##### index.html
```html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <iframe id="iframe" src="iframe.html">

        </iframe>
    </body>
</html>
```

##### iframe.html
```html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <a id="signin-link" href="login.html" target="_blank">Sing in</a>
    </body>
</html>
```

##### login.html
```html

<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <div>Login page</div>
        <div>
            <label>Username <input id="username"></label>
        </div>
        <div>
            <label>Password <input id="password"></label>
        </div>
        <div>
            <button id="signin">Sign in</button>
        </div>
    </body>
</html>
```

##### test.js
```js
fixture`Test login`
    .page`./index.html`;

test('Test iframe', async t => {
    await t
        .switchToIframe('#iframe')
        .click('#signin-link')
        .typeText('#username', 'username')
        .typeText('#password', 'password')
        .click('#signin')
});
```

It seems that the login window cannot finish some initialization step and waits forever until initialization is completed. We need some time to research this behavior. We will post here any results when we get something.

**Comment by KouraiBee** [comment] 2020-09-09 14:39
Hello ! 
I think I got the exact same issue ! 
My testcase is : 

1. Go to MS teams and Login -> OK
2. Click on a tab which load the app I'm actually testing -> OK ! 
Ms Teams actually load the app in an iframe here. 
3. Click on the google-login button from my app -> OK !
4. Popup (new windows) open with the google auth form -> OK !
5. Type login and password in the google windows -> KO :(

The google popup (the newest windows) is stuck on "Loading web page"
While the teams windows (the oldest one, with the iframe) is "waiting for an element to appear".
It should look for the element (`Selector('#identifierId');`) in the google windows instead. 

I try using chromium and firefox (both up to date)
I also try to get out of the iframe by using `.switchToMainWindow()` right before requesting the `Selector('#identifierId');` but none of it change anything.

if needed I can share my code, but in private, as I will need to set up new accounts on teams and the app I'm working on for it to work !

**Comment by wentwrong** [comment] 2020-09-10 08:30
Hi @KouraiBee,

Based on your description, this issue does look very similar to the cases described above. @AndreyBelym already posted a minimal example to reproduce it. So, I think we have all the information we need. We'll update this thread once the issue is fully resolved.

**Comment by gabriel-godoy** [comment] 2020-11-18 01:17
Hello, having the same issue here, trying to access a window opened by an iframe.
Any updates on this problem?
Thanks in advance!

**Comment by Farfurix** [comment] 2020-11-18 08:17
I'm closing this issue as a duplicate of https://github.com/DevExpress/testcafe/issues/5033. Related PR: https://github.com/DevExpress/testcafe/pull/5710.

**Closed by Farfurix** 2020-11-18 08:17 UTC
Labels: STATE: Need research, STATE: Need response, SYSTEM: window management, TYPE: bug
