### ISSUE TITLE
testcafe throws error when testing an autocomplete field on Chrome 69 or higher

### ISSUE THREAD

**Issue by lixualinta** [DevExpress/testcafe#3006] opened 2018-10-22 06:57 UTC
### What is your Test Scenario?

 I'd like to test an autoCompleted field (downshift library) on Chrome 69 or higher version on Android devices
### What is the Current behavior?

 When testcafe running on an android device with chrome 69 or higher, it throws an error when selecting an item from the autocomplete field even though the field actually works fine: 
Uncaught TypeError: Cannot read property 'clientX' of undefined
### What is the Expected behavior?

There should be no error and proceed successfully.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
https://material-ui.com/demos/autocomplete/#downshift
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `A set of examples that illustrate how to use TestCafe API`
    .page `https://material-ui.com/demos/autocomplete/#downshift`;

const inputField = Selector('#downshift-simple-input');
const firstItem = Selector('#downshift-simple-item-0');

test('test downshift', async t => {
  await t
    .wait(10000).typeText(inputField, 'a').click(firstItem);
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Run the test code provided
 
### Your Environment details:
 
* testcafe version:                   0.22.0
* node.js version:                    8.12.0
* command-line arguments:  testcafe remote test.js
* browser name and version: Chrome 69, Chrome 70
* platform and version:          Android 7, Android 8
* other:

**Comment by AlexKamaev** [comment] 2018-10-23 11:56
I'll close it as duplicate of https://github.com/DevExpress/testcafe/issues/2856

**Closed by AlexKamaev** 2018-10-23 11:56 UTC
Labels: SYSTEM: hammerhead, TYPE: bug
