### ISSUE TITLE
Travis test timeout

### ISSUE THREAD

**Issue by lzxb** [DevExpress/testcafe#1604] opened 2017-07-11 02:16 UTC
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
On MAC computers, local tests are normal, and tests are timed out on Travis

### What is the expected behavior?
The test does not timeout

### How would you reproduce the current behavior (if this is a bug)?
https://travis-ci.org/medatc/vuet/builds/252239607?utm_source=github_status&utm_medium=notification

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:https://github.com/medatc/vuet

Test code

```js

```

### Specify your

* operating system: Linux
* testcafe version:0.16.0
* node.js version:8

**Comment by AndreyBelym** [comment] 2017-07-11 09:48
Hello @lzxb  , due to new multiprocess rendering in Firefox 54, it has troubles with running on Travis with Xvfb. Please, try to use Firefox 53, you can specify version (`53.0`) [here](https://github.com/medatc/vuet/blob/master/.travis.yml#L11).

**Comment by lzxb** [comment] 2017-07-11 10:03
Thank you

**Comment by AlexanderMoskovkin** [comment] 2017-07-11 10:41
Meanwhile we'll investigate whether we can fix it on our side or we should wait some fix on the Travis-side

**Comment by lzxb** [comment] 2017-07-11 10:46
Can use

**Comment by AlexanderMoskovkin** [comment] 2017-08-02 11:16
duplicate of #1552

**Closed by AlexanderMoskovkin** 2017-08-02 11:16 UTC
Labels: REASON: duplicate, TYPE: bug

**Comment by AndreyBelym** [comment] 2017-08-10 12:06
Hello again, @lzxb! Looks like the issue was fixed in Firefox 55. Can you try to switch back to the `firefox: "latest"` in your `travis.yml`?

**Comment by AndreyBelym** [comment] 2017-08-10 12:16
I forked you repo and it works with Firefox 55: https://travis-ci.org/AndreyBelym/vuet/builds/263057293

**Comment by lzxb** [comment] 2017-08-10 13:30
Well, now the test is through
