### ISSUE TITLE
TestCafe tests fails while upgrading to v1.14.2

### ISSUE THREAD

**Issue by vrunda-s** [DevExpress/testcafe#6313] opened 2021-06-16 19:27 UTC
### What is your Test Scenario?
While trying to upgrade TestCafe dependency to the latest version `v1.14.2`, tests are **consistently** failing with `Too long with no output (exceeded 10m0s): context deadline exceeded`. 
Firstly, I tried to up the resource class for CI assuming it could be due CPU/memory allocation and later discovered that tests are failing on my local machine too with same timed-out issue. Tried further by upgrading to even newer version `v1.15.0-rc.1` and got same failing result. 🤷‍♀️ 

I can not find anything in the [release notes](https://github.com/DevExpress/testcafe/releases/tag/v1.14.2) that could make these tests fail. The only question is: why are they failing? Is there anything else I can try?

### What is the Current behavior?

- Tests fails with timeout-related issue.

 
### What is the Expected behavior?

- Tests should pass as they are in `v1.14.0`

 
### What is your web application and your TestCafe test code?

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
	"src": "tests/e2e/tests/*.tsx",
	"browsers": ["chrome:headless"],
	"disableMultipleWindows": true,
	"concurrency": 5,
	"skipJsErrors": true,
	"color": true,
	"pageLoadTimeout": 20000,
	"selectorTimeout": 20000,
	"assertionTimeout": 20000,
	"skipUncaughtErrors": true,
	"screenshots": {
		"takeOnFails": true,
		"fullPage": true,
		"path": "tests/e2e/screenshots",
		"pathPattern": "${DATE}/${TEST}.png"
	},
	"reporter": [
		"spec",
		{
			"name": "xunit",
			"output": "reports/testcafe/test-results.xml"
		}
	]
}

```
</details>

<details>
<summary>Screenshots:</summary>

![Screen Shot 2021-06-16 at 3 25 38 PM](https://user-images.githubusercontent.com/62349610/122280363-1ca75f00-ceb7-11eb-802f-ae64621fe7dc.png)
</details>
 
### Your Environment details:
 
* testcafe version:                   v1.14.2
* node.js version:                    v14.16.0
* command-line arguments:  testcafe -q -F Smoke tests/e2e/tests/*
* browser name and version: HeadlessChrome 91.0.4472.77 / Linux 0.0
* platform and version:          locally on Mac, and Circle CI v2.1

**Comment by vrunda-s** [comment] 2021-06-17 17:56
You can try to loop through following sample code.

<details>

```
import { Selector } from 'testcafe';

fixture(`Getting Started`).page(`http://devexpress.github.io/testcafe/example`);

test('My first test', async (t) => {
    await t.typeText('#developer-name', 'John Smith').click('#submit-button');
});
```

</details>

**Comment by felis2803** [comment] 2021-06-18 08:41
I was not able to reproduce this behavior.
Maybe I misunderstood your suggestion regarding a loop:
```js
import { Selector } from 'testcafe';

for (let i = 0; i < 80; i++) {
    fixture(`Getting Started`).page(`http://devexpress.github.io/testcafe/example`);

    test(`Test #${i}`, async (t) => {
        await t.typeText('#developer-name', 'John Smith').click('#submit-button');
    });
}
```
Would you please send an example where the behavior you are talking about is reproduced?

**Comment by duhseekoh** [comment] 2021-07-12 17:52
Same thing -- Have a fairly large test suite that was running fine. Upgraded to 1.14.2 (from 1.14.0) and started getting a bunch of these failures. Thought it was on our end, but then downgraded to 1.14.0 and all was well again.

**Comment by Farfurix** [comment] 2021-07-14 07:15
We didn't get any reproducible example from @vrunda-s. So, I'll close this issue.

@duhseekoh

If this issue can be reproduced with the latest TestCafe v1.15.0, please open a new issue with an example that we can run on our side.

**Closed by Farfurix** 2021-07-14 07:15 UTC
Labels: STATE: Need response, STATE: Need simple sample
