### ISSUE TITLE
TestCafe test after logs into application throws error 401 unauthorized

### ISSUE THREAD

**Issue by blerand123** [DevExpress/testcafe#5160] opened 2020-06-02 14:02 UTC
### What is your Test Scenario?
 User successfully logs in to application and navigate to a specific tab.
 
### What is the Current behavior?
Im able to log in to application using cognito and I see that im getting the authorization token but when it tries to load data im getting error 401 unauthenticated.
 
![image](https://user-images.githubusercontent.com/16356021/83528330-462e5c00-a4e9-11ea-8465-96fa1533e857.png)

### What is the Expected behavior?
Continue testing and navigating to the tab.
 
</details>

<details>

import { Selector, RequestLogger } from 'testcafe';
const url = 'http://localhost:3000/';
fixture `Export`
    .page(url)
const emailAddress = Selector('#email-address');
const emailPassword = Selector('#password');
const signInButton = Selector('.EmailSignIn_signInBtn__1u72_')
test(`Write credentials and successfully logs in to application`, async t => {
    await t
        .click(emailAddress)
        .typeText( emailAddress, process.env.FAN_USERNAME)
        .click(emailPassword)
        .typeText(emailPassword, process.env.FAN_PASSWORD)
        .click(signInButton)
        .wait(100000)// don't mind this
        .click(Selector('.Navbar_menuButton__3FuYX'))
});
</details>

### Your Environment details:
 
* testcafe version:                   1.8.6
* node.js version:                    v10.20.1
* command-line arguments:  testcafe chrome tests
* browser name and version: <hrome
* platform and version:         Linux Ubuntu 18.04.1

**Comment by miherlosev** [comment] 2020-06-03 08:15
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/2334

**Closed by miherlosev** 2020-06-03 08:15 UTC
Labels: STATE: Need response
