### ISSUE TITLE
Testcafe hangs when interacting with login page

### ISSUE THREAD

**Issue by tgrisley** [DevExpress/testcafe#7810] opened 2023-06-16 15:38 UTC
### What is your Scenario?

We are facing an issue within our TestCafe tests where they hang when interacting with the login page. TestCafe does not reach its assertion or selector timeout, instead it just completely stops. 

Please see example. 

### What is the Current behavior?

TestCafe hangs after performing an action and does not move onto next action. 

### What is the Expected behavior?

TestCafe to either move onto next action or timeout. 

### What is your public website URL? (or attach your complete example)

economist.com

### What is your TestCafe test code?

// cookie-consent.js //

```
import { RequestMock } from 'testcafe';

// Mock Evidon cookie consent to avoid interacting with the module on each new session
export function mockEvidonCookieConsent() {
  return RequestMock()
    .onRequestTo(/evidon\.com\//)
    .respond('', 200);
}

export function mockSourcepointCookieConsent() {
  return RequestMock()
    .onRequestTo(/cmp-cdn\.p\.aws\.economist\.com\/latest\/cmp\.min\.js/)
    .respond('', 200);
}

```
// example.js //

```
import { fixture , Selector } from 'testcafe';
import { xpathSelector} from './helpers';
import {
  mockEvidonCookieConsent,
  mockSourcepointCookieConsent,
} from './cookie-consent';

fixture `example fixture`
  .page('economist.com')
  .requestHooks([mockEvidonCookieConsent(), mockSourcepointCookieConsent()])
 
const emailField = xpathSelector('//*[@type="text"]');
const passwordField = xpathSelector('//*[@type="password"]');
const loginLink = Selector('.ds-masthead').find('a').withText('Log in').filterVisible();

test('example', async t => {
  await t.click(loginLink)
  await t.typeText(emailField, 'email@example.com')
  console.log('email entered')
  await t.typeText(passwordField, 'password')
  console.log('password entered')
});

test('example 2', async t => {
  await t.click(loginLink)
  await t.typeText(emailField, 'email@example.com')
  console.log('email entered')
  await t.typeText(passwordField, 'password')
  console.log('password entered')
});

test('example 3', async t => {
  await t.click(loginLink)
  await t.typeText(emailField, 'email@example.com')
  console.log('email entered')
  await t.typeText(passwordField, 'password')
  console.log('password entered')
});
```

// helpers.js //

```
import { Selector } from 'testcafe';

/**
 * Retrieves all elements that match a given xpath.
 * @param {string} xpath - xpath to search with
 * @return {Object} found elements
 */
const getElementsByXPath = Selector(xpath => {
  const iterator = document.evaluate(
    xpath,
    document,
    null,
    XPathResult.UNORDERED_NODE_ITERATOR_TYPE,
    null,
  );

  const items = [];
  let item = iterator.iterateNext();

  while (item) {
    items.push(item);
    item = iterator.iterateNext();
  }

  return items;
});

/**
 * Create a selector based on a xpath. Testcafe does not natively support xpath
 * selectors, hence this function.
 * @param {string} xpath - xpath to search with
 * @returns {Selector} returns a selector
 */
export const xpathSelector = xpath => {
  return Selector(getElementsByXPath(xpath));
};
```

### Your complete test report

None, testcafe hangs and never finishes. 

<img width="327" alt="Screenshot 2023-06-16 at 16 37 07" src="https://github.com/DevExpress/testcafe/assets/126177701/31a98678-3958-4e2c-a613-de065cdb9758">

### Screenshots

<img width="638" alt="Screenshot 2023-06-16 at 16 37 38" src="https://github.com/DevExpress/testcafe/assets/126177701/0360f858-e977-467b-b695-8d74abdd0a1d">

<img width="1202" alt="Screenshot 2023-06-16 at 16 41 31" src="https://github.com/DevExpress/testcafe/assets/126177701/c62b4610-7658-4f66-ad61-5627e42874d5">

### Steps to Reproduce

1. Run example.js
2. Notice that TestCafe will hang

### TestCafe version

2.5.1-rc.1

### Node.js version

16.20

### Command-line arguments

testcafe chrome example.js --skip-js-errors

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

macOS

**Comment by tgrisley** [comment] 2023-06-27 08:06
Hi, 

You shouldn't need a proxy to access this site, it is public facing. 

Also you do not need valid authentication credentials to replicate this issue, the example i posted above will replicate the issue, but feel free to replace that typeText with any string, you should get the same result. 

Thanks,

**Comment by Dmitry-Ostashev** [comment] 2023-06-29 08:14
Hello @tgrisley ,

I was unable to reproduce the issue. All the tests are passed with TestCafe v3.0.0. The only issue I found is that the JavaScript error occurs in the Native Automation mode. I'm not sure that it is related to the issue you described. I recommend you try using the latest TestCafe version.

**Comment by tgrisley** [comment] 2023-07-04 09:29
So tried upgrading to 3.0.0, this works when running against our production site, but seem to encounter issues when running against our staging environment. 

<img width="632" alt="Screenshot 2023-07-04 at 10 27 22" src="https://github.com/DevExpress/testcafe/assets/126177701/0088cfd5-ebfb-409e-b758-19a4bda47741">

Notice how it is trying to find a selector it has already clicked.

Also throws this error. 

<img width="846" alt="Screenshot 2023-07-04 at 10 27 53" src="https://github.com/DevExpress/testcafe/assets/126177701/d2ecf426-f4ef-4d83-ac16-12995fcb46fd">

Have sent an email to [support@devexpress.com](mailto:support@devexpress.com)

**Comment by AlexKamaev** [comment] 2023-07-07 07:38
I managed to reproduce the issue. We'll research it and update this thread once we have any news.

**Comment by Artem-Babich** [comment] 2023-07-07 09:07
Duplicate of #7865

**Closed** 2023-07-17 07:59 UTC
Labels: TYPE: bug, FREQUENCY: level 1, SYSTEM: native automation
