### ISSUE TITLE
Testcafe fails to run Angular 17/18 tests on Firefox

### ISSUE THREAD

**Issue by equipatuequipo** [DevExpress/testcafe#8221] opened 2024-06-28 10:30 UTC
### What is your Scenario?

I'm trying to create tests for an Angular 18 app.

### What is the Current behavior?

The tests fail while running them on Firefox, the browser console shows an error related to observables.

![Browser console](https://github.com/DevExpress/testcafe/assets/95863903/9929cd80-38ba-4748-bfa0-aa1b73fd3ef7)
![Error source](https://github.com/DevExpress/testcafe/assets/95863903/0325e58f-0315-4add-be81-a7fe4021c997)

Digging a little bit deeper I found out the issue comes from `hammerhead`, a part of Testcafe:

![Troublesome hammerhead code](https://github.com/DevExpress/testcafe/assets/95863903/b4da30b2-23ff-4223-b0a2-47cc085309f5)

https://github.com/DevExpress/testcafe-hammerhead/blob/dcc14065ec63616c6aff9fdb01a663a58f41052a/src/processing/script/header.ts#L55

### What is the Expected behavior?

The tests to work in all browsers

### What is the public URL of the test page? (attach your complete example)

Given that you need a browser to run the tests this only can be tested locally. I've setup a repo with instructions to reproduce: https://github.com/equipatuequipo/testcafe-angular-18

### What is your TestCafe test code?

```ts
import { Selector, fixture, test } from 'testcafe';

fixture`Error example`.page`./`;

test('Empty page', async (t) => {
  await t.expect(Selector('h1').innerText).eql('Test');
});
```

### Your complete configuration file

```js
/** @type {TestCafeConfigurationOptions} */
module.exports = {
  src: "src/tests/**/*.test.ts",
  browsers: ["firefox"],
  baseUrl: "http://localhost:4200",
  debugMode: true,
  speed: 0.5,
};

```

### Your complete test report

The test does not finish, the error is visible in the browser's console:

![Browser console](https://github.com/DevExpress/testcafe/assets/95863903/9929cd80-38ba-4748-bfa0-aa1b73fd3ef7)

### Steps to Reproduce

1. Clone the [example repo](https://github.com/equipatuequipo/testcafe-angular-18)
2. Install all dependencies: `npm i`
3. Start the webserver: `npm start`
4. Run the tests in a separate terminal: `npm run test`
5. Check the browser's console

### TestCafe version

3.6.0

### Node.js version

20.11.0

### Command-line arguments

None, all the config is in .testcaferc.js

### Browser name(s) and version(s)

Firefox 127

### Platform(s) and version(s)

Windows 10

### Other

Tested on Angular 17 and 18, problem persists.

**Comment by Bayheck** [comment] 2024-07-02 11:25
Hello,

After taking a closer look at the issue, we found out that TestCafe has a technical limitation when used with the rxjs library. TestCafe uses testcafe-hammerhead to proxy your page, and rxjs has an operator function named 'window', which interferes and replaces the global window. It breaks hammerhead attached methods like __get$ and __set$, which results in the issue you are facing.

When you use a function from the rxjs library like 'map' in your example, the whole module is sent to the client with the above mentioned 'window' operator function, which causes the issue. As a workaround, try using an alternative package for the rxjs 'map' function in your application.

**Comment by equipatuequipo** [comment] 2024-07-05 07:26
Hello, 
Thanks so much for your response! I'm a bit confused about how this issue only occurs in Firefox, while everything works perfectly in Chrome. If what you mentioned were the case, wouldn't it affect all browsers? Regarding the alternative you suggested, I've tried five different libraries, but none have managed to work properly with observables. Do you have any other suggestions? Thanks again for your help!

**Comment by Bayheck** [comment] 2024-07-10 11:32
Hello,

The issue occurs only in Firefox because Testcafe has Native Automation mode only in Chromium-based browsers. 

[https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode)

 

Could you please illustrate your attempts with alternative libraries using the example repo you shared before?

It is possible there is another issue.

**Comment by equipatuequipo** [comment] 2024-07-11 09:31
Hello,

We have tested the map function from the following libraries:

- lodash
- ramda
- observable-fns
- rxjs-operators
- Our own implementation

None of them worked correctly (they gave an error in Angular). rxjs is the library that Angular uses internally for observables, and it seems there is no alternative to this.

**Comment by Bayheck** [comment] 2024-07-19 09:20
Hello, this is a temporary technical limitation of Testcafe in Firefox.

For now, I recommend to use chromium based browsers with enabled Native Automation.

Stay tuned for any updates.

**Comment by sorin-davidoi** [comment] 2024-10-09 07:50
> After taking a closer look at the issue, we found out that TestCafe has a technical limitation when used with the rxjs library. TestCafe uses testcafe-hammerhead to proxy your page, and rxjs has an operator function named 'window', which interferes and replaces the global window. It breaks hammerhead attached methods like __get$ and __set$, which results in the issue you are facing.

I think this can be fixed by tweaking the environment detection code. The actual `window` object should be accessed via `globalThis.window` in order to avoid variables shadowing it.

I can confirm that applying this change in https://github.com/DevExpress/testcafe-hammerhead/blob/dcc14065ec63616c6aff9fdb01a663a58f41052a/src/processing/script/header.ts#L55 solves this for my particular use-case.

Support for [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility) looks good both in browsers and in NodeJS, so we should be able to use it without worrying about breaking compatibility.

The one thing I'm not sure if this change needs to be applied to other parts of the codebase. @Bayheck would you accept a patch that does this change in `header.ts` (and possibly other places)?

**Comment by Bayheck** [comment] 2024-10-18 09:47
Thank you for your help. Replacing the window with a globalThis.window does help resolve the issue. We are already working on the PR and making progress. However, we believe your proposed patch is not necessary at this time. 

Thanks for your contribution anyway.

**Closed** 2024-11-12 07:34 UTC
Labels: TYPE: bug
