### ISSUE TITLE
IE11 Selector failure

### ISSUE THREAD

**Issue by sbenyo** [DevExpress/testcafe#2241] opened 2018-03-22 09:51 UTC
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Basic Selector of input field fails on IE11:
TypeError: Object doesn't support property or method 'matches'

Works well for chrome and firefox

### What is the expected behavior?

Selector should choose input field and type value

### How would you reproduce the current behavior (if this is a bug)?

Simply run the test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 7
* testcafe version: 0.19.1
* node.js version: 8.9.1

**Comment by dc-m** [comment] 2018-03-27 08:17
I am also having this issue:

```
test('login', async t => {
    const username = Selector('#Username');
    const username = Selector('.search-btn');

    await t
        .typeText(searchInput, 'Username')
        .click(searchButton);
});

```
> Browser: IE 11.0.0 / Windows 10.0.0
> Object doesn't support property or method 'matches'

operating system: Windows 10
testcafe version: ^0.19.1
node.js version: 8.9.4

**Comment by AlexanderMoskovkin** [comment] 2018-03-27 13:04
Hi @sbenyo,

I run a [simple test](https://github.com/DevExpress/testcafe#creating-the-test) in IE11 and it works properly. 
![image](https://user-images.githubusercontent.com/12047804/37968986-524c51c6-31d8-11e8-9731-b6874dd4043c.png)

It possible the issue is specific for you page. Could you please provide us with the url of your tested page or a simple example to reproduce the problem on our side?

Additionally please take a look the the corresponding topic: [When I run a TestCafe test, I get an unexpected error. What can cause that?](https://devexpress.github.io/testcafe/faq/#when-i-run-a-testcafe-test-i-get-an-unexpected-error-what-can-cause-that)

**Comment by sbenyo** [comment] 2018-03-28 15:32
Thanks for the reply.
I fail on a big project with in Angular 5. I cannot send example of this project.

I will try to reproduce it in a simpler project that has similar environment and dependecies.

**Comment by AlexanderMoskovkin** [comment] 2018-03-29 05:38
@sbenyo Did you check whether your page raises this js-error without TestCafe when you just open it in IE?

**Comment by sbenyo** [comment] 2018-03-29 07:17
I found that we need to use "matches" polyfill for IE11. We have this:

if (!Element.prototype.matches) {
		Element.prototype.matches = Element.prototype.msMatchesSelector ||
			Element.prototype.webkitMatchesSelector;
}

If I remove it, the TestCafe Selectors seem to work. Is there a way to keep using it and still be able to run TestCafe with IE11?

**Comment by MarinaRukavitsyna** [comment] 2018-03-29 12:03
Hello @sbenyo,
Generally, TestCafe raises a similar error when a page has JS errors. To check this, please open your page in a browser and enable the browser console (press F12 for this). If there are JS errors there, you can either fix them on your website or skip them during testing using the --skip-js-errors option:
 
[When I run a TestCafe test, I get an unexpected error. What can cause that?](https://devexpress.github.io/testcafe/faq/#when-i-run-a-testcafe-test-i-get-an-unexpected-error-what-can-cause-that)

If this does not help, please send us a screenshot of your browser console when you open your page in a browser (without TestCafe) for research.

**Comment by miherlosev** [comment] 2018-05-04 15:39
Hi @sbenyo.
I've found the reason of the problem and created the issue in our proxy repository - https://github.com/DevExpress/testcafe-hammerhead/issues/1603.

**Comment by miherlosev** [comment] 2018-05-21 11:58
Fixed in https://github.com/DevExpress/testcafe/pull/2437

**Closed by miherlosev** 2018-05-21 11:58 UTC
Labels: SYSTEM: hammerhead, TYPE: bug
