### ISSUE TITLE
Upgrade to testcafe 1.14.2 fails in Test Environment - getting IP address instead of hostname in URL

### ISSUE THREAD

**Issue by mishmaccas** [DevExpress/testcafe#6345] opened 2021-06-29 06:45 UTC
Currently upgrading to TestCafe 1.14.2 causes our tests to hang in our test environment.
As far as we know we have not changed our test environment, and we can use TestCafe "testcafe": "^1.13.0" successfully
**But we cannot upgrade our automation suite with the latest TestCafe.**

i created a simple project so you can run a simple test in our environment, and hopefully you can detect WHY the test hangs after clicking a button in a particular point.

I cannot reproduce this error anywhere else so please DM with the GitHub user so i can give you access - and u can run our test.

**our backend support team did notice that in the logs we are getting IP address instead of hostname in URL.**

### What is your Test Scenario?
The test is simulating a customer adding a product to cart, and after the payment details are entered, and the Continue  button is clicked it should proceed to the next section.
 
### What is the Current behavior?
clicking **Continue to Samples** causes the test to hang, the APi call to the back end does not return

 
### What is the Expected behavior?
A sample section should appear it should ...
"keep on swimming"
 
### What is your web application and your TestCafe test code?

https://github.com/mishmaccas/test-simple-purchase
Please let me know who I give access to.
 
### Partial code where it fails

```js
 await t
        .click(locators.checkoutSubmit())
        .wait(20000) // give it 20 seconds which is a ridiculously long time
    // *** THIS IS usually WHERE THE TEST HANGS ****
    // WITH TESTCAFE VERSION 1.14.2
    //  Expect the samples page --- FAILS
    // next assertion also waits 10 seconds
    await t
        .expect(locators.samples().visible).ok()
```

### Steps to Reproduce:

Run
testcafe chrome tests/testing.js 

### Your Environment details:
 
* testcafe version:                   1.14.2
* node.js version:                    v14.17.0
* command-line arguments:  testcafe chrome tests/testing.js 
* browser name and version: Version 91.0.4472.114 (Official Build) (x86_64) 
* platform and version:          macOS Big Sur version 11.4
* other:                                   dont know

Screenshot shows the hanging
![1](https://user-images.githubusercontent.com/15898223/123749592-f2af5d00-d8f8-11eb-8bff-faa7ab05d46d.png)

**Comment by Dmitry-Ostashev** [comment] 2021-07-01 07:56
You can give access to me, and I'll try to debug your test example and find out the reason.

**Comment by mishmaccas** [comment] 2021-07-06 01:20
Dear @Dmitry-Ostashev  I have given you access to my repo, kind regards, Mish

**Comment by Dmitry-Ostashev** [comment] 2021-07-06 12:47
Thank you for your example. I reproduced the issue. It seems to be caused by the problem described here: https://github.com/DevExpress/testcafe-hammerhead/issues/2653. Please track that thread to be notified of our progress in resolving this bug.

**Closed by Dmitry-Ostashev** 2021-07-06 12:47 UTC
Labels: STATE: Need response

**Comment by mishmaccas** [comment] 2021-07-15 01:31
THank you @Dmitry-Ostashev for help, much appreciated!
