### ISSUE TITLE
Synchronous wait-Clarification

### ISSUE THREAD

**Issue by PonmaniAnnamalai** [DevExpress/testcafe#3741] opened 2019-04-24 09:10 UTC
Team,
I am automating a site using testcafe. After successful login, it has to wait the home page to be loaded successfully,
Actual:
The browser gets closed before the page is loaded.
Clarification:
Can wait for page load can be done using testcafe-react-selectors.If so can you please provide me that piece of code
I tried beforeEach but in vain.
Or can you suggest me any utilities to make it sure that page is loaded before getting closed.

**Comment by miherlosev** [comment] 2019-04-24 10:38
Please always use the [New Bug template](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) and fill-in all fields including the example and all reproduction steps because the information you provided is insufficient for me to determine the cause of the issue. . I will close this issue until you can provide an example which I can reproduce on my machine.

**Closed by miherlosev** 2019-04-24 10:38 UTC
Labels: STATE: Need response
