### ISSUE TITLE
When running test in Azure Devops, JS library is not found

### ISSUE THREAD

**Issue by munkii** [DevExpress/testcafe#6260] opened 2021-05-26 11:10 UTC
We have a website that operates fine when used normally but when it is being used by Test Cafe we get the following error 

```
 JavaScript error details:
      ReferenceError: luxon is not defined

```

Note we are using the luxon date and time JS library. The library is pulled into the page using this script element at the bottom of the page, 

`<script src="/lib/luxon/luxon.min.js"></script>`

**Comment by Farfurix** [comment] 2021-05-27 07:40
@munkii 

Hello,

Your scenario is not quite clear to me. Does this issue occur only in Azure CI, or can it be reproduced locally? We need a simple reproducible example to examine this issue. Please make sure that you are using the latest TestCafe version (v1.14.2).

**Comment by munkii** [comment] 2021-05-27 09:29
It is not reproducible on my local dev machine nor is it reproducible when the site is deployed to Azure and being used normally.

However when the site is being executed via a TestCafe test it does happen. Note these TestCafe tests are running in Azure. I am not the author of the Tests so do not have a license to run Test Cafe locally

I have since moved the luxon.js include to be loaded two scripts earlier and that seems to have stopped the issue. The two scripts now loading after do not use Luxon

**Comment by Farfurix** [comment] 2021-05-28 07:33
@munkii 

It's great to hear that the issue is fixed. Unfortunately, we cannot say anything about its cause without a reproducible example. I'll close this thread. If you come across some similar issue in the future, please open a new bug report with a reproducible example.

**Closed by Farfurix** 2021-05-28 07:33 UTC
Labels: STATE: Need response
