### ISSUE TITLE
Hammerhead failed to setAttribute on Element

### ISSUE THREAD

**Issue by Jgrabenbauer** [DevExpress/testcafe#7441] opened 2022-12-27 15:54 UTC
### What is your Scenario?

I am trying to click a button that opens up an [Integry](https://www.integry.io/]) modal but during automation I keep receiving this error:

<img width="1038" alt="Screenshot 2022-12-27 at 10 42 43 AM" src="https://user-images.githubusercontent.com/24844219/209689207-0d8bf094-acf9-4868-b170-df577d9a1f51.png">

It also doesn't work when unlocking the window and clicking it manually, but it does work fine when clicking it manually outside of automation.

### What is the Current behavior?

An error gets thrown at `t.setAttributeCore (http://localhost:65062/hammerhead.js:10:28517)` when clicking the button.

### What is the Expected behavior?

Clicking the button opens the Integry modal without any issues.

### What is your public website URL? (or attach your complete example)

DevExpress has access to our repo. Please email me if re-authentication is necessary.

### integrations_page_tests.js

```
test
    .meta({ created_on: '12/27/22', created_by: 'Justin Grabenbauer', updated_on: '', updated_by: '' })
    .meta({ scope: 'sanity', priority: 'low', showstopper: 'no', github_ID: '1585' })
    ('user_can_add_an_integration', async t => {
        
        // Purpose: To verify that a user can add an integration

        const integration_name = 'ClickFunnels Classic'

        await WorkspaceMainNavPageObjects.navigate_to_workspace_settings()
        await SettingsPageObjects.navigate_to_integrations_page()
        await t.debug()
        await IntegrationsPageObjects.connect_integration(integration_name)
})
```

### integrations_page_repo.js

```
import { Selector, t } from 'testcafe'


class IntegrationsPageObjects {
    constructor() {
        this.btn_connect_integration = Selector('button').withText('Connect integration')
    }

    async connect_integration(integration_name) {

        // Purpose: To connect an integration

        await t
            .click(this.btn_connect_integration)
            .click(Selector('div').withText(integration_name))
    }
}

export default new IntegrationsPageObjects()
```

### Your complete configuration file

```
require('dotenv').config()
const data = require('./data/data.json')
const { RequestLogger } = require('testcafe')

// TODO: See if we can make this part local to a function instead of out in the open, globally.
// Set the URL for where we want to start logging
let logger_url = data.api_endpoints.notifications_dropdown

switch(process.env.ENV) {
    case 'staging':
        logger_url = data.authenticated_urls.staging.concat(logger_url)
        break

    case 'production':
        logger_url = data.authenticated_urls.production.concat(logger_url)
        break
    }
    
const notifications_dropdown_logger = RequestLogger(logger_url)

// Agnostic for all environments
let skipped_tests = [

    // Located in all_contacts_page_tests.js
    'user_can_modify_contacts_table_columns', // 12-19-22
    
    // Located in all_products_page_tests.js
    'user_can_create_a_subscription_product', // 09-27-22
    'user_can_set_a_price_for_physical_products', // 09-27-22

    // Located in apps_page_tests.js
    'user_cannot_access_sites_when_feature_is_disabled', // 07-28-22
    'user_cannot_access_settings_when_feature_is_disabled', // 07-28-22
    'user_cannot_access_analytics_when_feature_is_disabled', // 09-16-22
    'user_cannot_access_marketing_when_feature_is_disabled', // 09-16-22
    'user_cannot_access_products_when_feature_is_disabled', // 09-16-22
    'user_cannot_access_contacts_when_feature_is_disabled', // 09-16-22
    'user_cannot_access_orders_when_feature_is_disabled', // 09-16-22
    'user_cannot_access_sales_when_feature_is_disabled', // 09-16-22

    // Located in billing_page_tests.js
    'user_can_navigate_to_billing_page', // 08-22-22

    // Located in blog_page_tests.js
    'user_is_able_to_change_blog_template', // 12-06-22
    'user_can_add_a_gif_to_blog', // 11-30-22
    'user_can_change_blog_post_style', // 12-06-22
    'user_can_clone_a_blog_post', // 11-30-22
    'user_can_create_a_blog_post', // 11-30-22
    'user_can_edit_blog_settings', // 07-06-22
    'user_can_edit_existing_blog_post_information', // 11-30-22
    
    // Located in courses_page_tests.js
    'courses_back_button_navigates_to_previous_page',
    'optin_user_can_navigate_through_course', // 12-06-22
    'user_can_log_into_customer_center_with_magic_link',

    // Located in dashboard_page_tests.js
    'user_can_navigate_to_forms_page_from_dashboard', // 11-22-22
    'user_can_navigate_to_payouts_page_from_dashboard', // 11-22-22

    // Located in funnels_page_tests.js
    'user_can_clone_a_funnel',
    'user_can_navigate_through_funnel',
    
    // Located in marketing/broadcasts_page_tests.js
    'user_can_create_new_broadcast', // 06-20-22

    // Located in marketing/templates_page_tests.js
    'user_can_create_broadcast_template', // 06-13-22

    // Located in orders/all_orders_page_tests.js
    'user_can_refund_order', // 10/18/22

    // Located in orders/order_page_tests.js
    'user_is_able_to_create_new_order', // 09-27-22
    'user_is_able_to_complete_payment_on_order', // 09-27-22
    'user_is_able_to_partially_pay_order', // 09-27-22
    'user_is_able_to_refund_order', // 09-27-22
    'user_is_able_to_set_delayed_status_on_order', // 09-27-22
    'user_is_able_to_set_processing_status_on_order', // 09-27-22
    'user_is_able_to_set_packed_status_on_order', // 09-27-22
    'user_is_able_to_set_ready_status_on_order', // 09-27-22
    'user_is_able_to_set_delivered_status_on_order', // 09-27-22
    'user_is_able_to_set_shipped_status_on_order', // 09-27-22
    'user_is_able_to_set_backorder_status_on_order', // 09-27-22
    'user_is_able_to_set_pending_status_on_order', // 09-27-22
    'user_is_able_to_set_lost_status_on_order', // 09-27-22
    'user_can_add_multiple_fulfillments_to_order', // 09-27-22
    'user_can_partially_fulfill_order', // 08-11-22

    // Located in pages_page_tests.js
    'user_can_pin_a_page_from_edit_page', //07-29-22

    // Located in pipelines_page_tests.js
    'user_can_navigate_to_pipelines_page', // 09/14/22

    // Located in reporting_page_tests.js
    'opt-ins_by_landing_page_report_displays', // 06/21/22

    // Located in sites_overview_page_tests.js
    'user_can_add_header_to_site', // 07-06-22
    'user_can_change_site_style', // 10-31-22
    'user_can_edit_site_name', // 10-04-22
    'user_can_make_site_password_protected', // 10-03-22

    // Located in themes_page_tests.js
    'user_can_edit_theme_name', // 08-08-22

    // Located in url_redirects_page_tests.js
    'user_can_delete_a_url_redirect', // 11-30-22
    'user_is_able_to_edit_url_redirect' // 11-30-22
]

// Cleanup scripts that need to be skipped, but can't be in the skipped tests
let clean_up_tests = [
    // Located in clean_up_scripts.js
    'clean_up_copies_of_funnels',
    'clean_up_copies_of_funnel_pages',
    'clean_up_copies_of_pages', 
    'clean_up_products',
    'clean_up_site_pages',
    'clean_up_workflows',
    'dismiss_notifications',
    'clean_up_collaborators',
]

// Production specific scripts needing to be skipped for various reasons
let production_skipped_tests = [
    'user_can_navigate_to_affiliate_center_page', // Disabling because the link is disabled in production as of 12/07/22
    'user_can_navigate_to_order_tags_page', // Link disabled through Launch Darkly as of 08/29/22
    'user_can_navigate_to_payments_ai_dashboard', // Production PAI account not set up as of 08/29/22
    'user_is_able_to_navigate_to_the_inbox_page', // Inbox link is not activated in production as of 08/31/22
    'customer_can_place_order_through_funnel', // Disabling until we have PAI set up in production as of 10/04/22
    'user_can_navigate_to_sequences_page', // Disabling because it's behind a feature gate in produciton as of 10/17/22
    'user_can_navigate_to_events_and_deadlines_page', // Disabling because the link is disabled in production as of 11/28/22
    'user_can_navigate_to_community_page' // Disabling because the link doesn't display in production as of 12/21/22
]

// Scripts that need to run with a single concurrency
let isolated_tests = [
    // Located in sites_overview_page_tests.js
    'user_can_make_site_public',
    'user_can_edit_site_name',
    'user_can_make_site_password_protected',
    'user_can_make_site_private',
    'user_can_edit_site_domain',
    'changing_site_domain_updates_funnel_urls',
    'changing_site_domain_updates_blog_urls',
    'changing_site_domain_updates_course_urls',
    'user_can_add_header_to_site',

    // Located in account_details_page_tests.js
    'user_can_edit_account_name',
    'user_can_edit_account_password',
    'user_can_change_account_language',

    // Located in general_page_tests.js
    'user_can_edit_workspace_details',

    // Located in blog_page_tests.js
    'user_can_edit_blog_settings',

    // Located in themes_page_tests.js
    'user_can_promote_theme_to_live_from_index_page',
    'user_can_promote_theme_to_live_from_overview_page',

    // Located in the workflow_builder_page_tests.js
    'broadcast_room_category_pulls_back_expected_pages',
    'downsell_category_pulls_back_expected_pages',
    'landers_category_pulls_back_expected_pages',
    'my_funnel_pages_category_pulls_back_expected_pages',
    'opt_in_category_pulls_back_expected_pages',
    'order_category_pulls_back_expected_pages',
    'order_confirmation_category_pulls_back_expected_pages',
    'sales_category_pulls_back_expected_pages',
    'terms_of_service_category_pulls_back_expected_pages',
    'thank_you_category_pulls_back_expected_pages',
    'upsell_category_pulls_back_expected_pages',
    'webinar_confirmation_category_pulls_back_expected_pages',
    'webinar_registration_category_pulls_back_expected_pages'
]

// Filter that joins the skipped scripts with the production skipped tests
let production_filter = skipped_tests.concat(production_skipped_tests).concat(clean_up_tests)

// Filter that joins ALL filtered scripts so that they are not run for a full suite
let full_filter = skipped_tests.concat(isolated_tests).concat(clean_up_tests)

let build_filter = () => {

    // Purpose: To set the suite that we want to run. (isolated, regression, sanity)

    var filter = {}
    
    switch(process.env.ENV) {
        case 'production':
            if(process.env.SCOPE) {
                filter = {
                    testGrep: `^(?!.*(${production_filter.join('|')})).*$`,
                    testMeta: {
                        scope: process.env.SCOPE
                    }
                }
            }
            break
        case 'staging':
            if(process.env.SCOPE) {
                filter = {
                    testGrep: `^(?!.*(${skipped_tests.join('|')})).*$`, 
                    testMeta: {
                        scope: process.env.SCOPE
                    }
                }
            } else {
                filter = {
                    testGrep: `^(?!.*(${full_filter.join('|')})).*$`
                }
            }
            break
    }

    return filter
}

let determine_concurrency = () => {

    // Purpose: To set concurrency dependant on the scope that is passed
    
    let concurrency = 5
    if (process.env.SCOPE == 'isolated') {
        concurrency = 1
    } 
    return concurrency
}

module.exports = {
    assertionTimeout: 5000,
    browsers: [
        "chrome:headless --window-size=1920,1159"
    ],
    concurrency: determine_concurrency(),
    cache: true,
    clientScripts: [
        "scripts/click_expand_all_for_courses_details_page.js"
    ],
    disableMultipleWindows: true,
    filter: build_filter(),
    hooks: {
        fixture: {
            before: async ctx => {
                // Set the notifications dropdown logger globally
                ctx.notifications_dropdown_logger = notifications_dropdown_logger
            }
        },
        // Set the request hook for the notifications dropdown logger
        request: notifications_dropdown_logger
    },
    hostname: "localhost",
    pageLoadTimeout: 30000,
    quarantineMode: {
        successThreshold: 1,
        attemptLimit: 2
    },
    reporter: [
        {
            name: "spec",
            output: "artifacts/reports/spec_results"
        },
        {
            name: "xunit",
            output: "artifacts/reports/xunit_results.xml"
        }, 
        {
            name: "testrail"
        }
    ],
    runExecutionTimeout: 1800000,
    screenshots: {
        path: "artifacts/screenshots",
        pathPattern: "${TEST}_${DATE}_${TIME}.png",
        takeOnFails: true,
        thumbnails: false
    },
    selectorTimeout: 5000,
    skipJsErrors: true,
    skipUncaughtErrors: true,
    src: "tests/**",
    testExecutionTimeout: 240000
}
```

### Your complete test report

 Running tests in:
 - Chrome 108.0.0.0 / Ventura 13

 settings - integrations
 ✖ user_can_add_an_integration (screenshots: /Users/justingrabenbauer/cf2-test-cafe-poc/artifacts/screenshots/user_can_add_an_integration_2022-12-27_10-49-53.png)

   1) The specified selector does not match any element in the DOM tree.

         | Selector('div')
       > |   .withText('ClickFunnels Classic')

      Browser: Chrome 108.0.0.0 / macOS 10.15.7
      Screenshot: /Users/justingrabenbauer/cf2-test-cafe-poc/artifacts/screenshots/user_can_add_an_integration_2022-12-27_10-49-53.png

         11 |
         12 |        // Purpose: To click the Connect integration button
         13 |
         14 |        await t
         15 |            .click(this.btn_connect_integration)
       > 16 |            .click(Selector('div').withText(integration_name))
         17 |    }
         18 |}
         19 |
         20 |export default new IntegrationsPageObjects()
         21 |

         at <anonymous> (/Users/justingrabenbauer/cf2-test-cafe-poc/pom/settings/integrations/integrations_page_repo.js:16:14)
         at asyncGeneratorStep (/Users/justingrabenbauer/cf2-test-cafe-poc/pom/settings/integrations/integrations_page_repo.js:2:258)
         at _next (/Users/justingrabenbauer/cf2-test-cafe-poc/pom/settings/integrations/integrations_page_repo.js:2:596)
         at <anonymous> (/Users/justingrabenbauer/cf2-test-cafe-poc/pom/settings/integrations/integrations_page_repo.js:2:761)
         at <anonymous> (/Users/justingrabenbauer/cf2-test-cafe-poc/pom/settings/integrations/integrations_page_repo.js:2:502)
         at IntegrationsPageObjects.connect_integration (/Users/justingrabenbauer/cf2-test-cafe-poc/pom/settings/integrations/integrations_page_repo.js:10:49)
         at <anonymous> (/Users/justingrabenbauer/cf2-test-cafe-poc/tests/settings/integrations_page_tests.js:45:39)
         at asyncGeneratorStep (/Users/justingrabenbauer/cf2-test-cafe-poc/tests/settings/integrations_page_tests.js:7:315)
         at _next (/Users/justingrabenbauer/cf2-test-cafe-poc/tests/settings/integrations_page_tests.js:7:653)

 1/1 failed (1m 17s)

 Warnings (2):
 --
  The "browsers", "concurrency", and "filter" options from the configuration file will be ignored.
 --
  The file at "/Users/justingrabenbauer/cf2-test-cafe-poc/artifacts/screenshots/user_can_add_an_integration_2022-12-27_10-49-53.png" already exists. It has just been rewritten with a recent screenshot. This situation can possibly cause issues. To avoid them, make sure that each screenshot has a unique path. If a test runs in multiple browsers, consider including the user agent in the screenshot path or generate a unique identifier in another way.

### Steps to Reproduce

1. Run script
2. Check console

### TestCafe version

2.0.0

### Node.js version

18.12.0

### Command-line arguments

ENV=staging testcafe "chrome '--window-size=1920,1159'" -t 'user_can_add_an_integration' -c1

### Browser name(s) and version(s)

Chrome 108

### Platform(s) and version(s)

macOS Ventura 13

**Comment by aleks-pro** [comment] 2023-01-03 09:55
Hello @Jgrabenbauer ,

Thank you for the example. I've managed to reproduce the issue.

**Comment by Artem-Babich** [comment] 2023-04-12 07:33
We will close this issue since it is fixed in the [Native Automation mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode). Please try the native automation mode in your tests.
Feel free to reopen the issue if you need a fix for the other browsers or you cannot use Native Automation for some reason.

**Closed by Artem-Babich** 2023-04-12 07:33 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, FREQUENCY: level 1, STATE: possibly fixed in native automation
