### ISSUE TITLE
Browser instance not shutdown (but tab/window closes)

### ISSUE THREAD

**Issue by nmackey** [DevExpress/testcafe#2226] opened 2018-03-18 22:03 UTC
### Are you requesting a feature or reporting a bug?

Reporting a bug

### What is the current behavior?

Browser window closes but browser not shutdown.

### What is the expected behavior?

The browser instance should be shutdown.

### How would you reproduce the current behavior (if this is a bug)?

Run any test suite (tried with multiple projects) with Chrome, Headless Chrome, Safari, Firefox (Headless Firefox seems to work)
With Chrome I did try moving back versions of testcafe to isolate when the bug was introduced and it seems to have been introduced between 0.17.2 and 0.18.0
This could be related to: https://github.com/DevExpress/testcafe/issues/2194 and/or https://github.com/DevExpress/testcafe/issues/2132

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: MAC OS X 10.13.3
* testcafe version: 19.1
* node.js version: 9.2.0

**Comment by graeme-plangrid** [comment] 2018-03-21 23:48
Also experiencing this as well on v.19.1. Curious if there's a fix incoming.

**Comment by Hotell** [comment] 2018-03-23 15:21
works without issues wit node 8

```
operating system: MAC OS X 10.13.3
testcafe: 0.19.1,
node.js version: 8.10.0
```

**Comment by Sushindhran** [comment] 2018-04-02 14:49
I'm seeing this as well.

node.js v8.9.4
testcafe 0.19.1
Mac OSX 10.11.6

**Comment by AndreyBelym** [comment] 2018-04-02 15:44
Hi @nmackey @graeme-plangrid @Sushindhran!

Unfortunately, I can't reproduce issue on Macs here. I need time to make a debug build. Meanwhile, if you have some free time, you can check how the `lookup` and `kill` functions from the [psnode]() package works on your machine. When closing a browser, TestCafe tries to find a browser process by using `lookup` with a piece of a command line parameter passed when browser was opened, and then uses `kill` to terminate the process. So you have to:

 1. Start the browser with a command line parameter
```
open -n -a /Applications/Google\ Chrome.app --args http://google.com
```

 2. Open Node.js REPL in a directory with the installed `psnode` module, and type something like:
```
psnode = require('psnode')
psnode.lookup({ arguments: 'google' }, (err, processList) => {global.err = err; global.processList = processList; console.log('done')})
```
 3. Wait until `'done'` will be printed to console, and then type `err` and `processList` in CLI. If you have have `ReferenceError: err is not defined` and some list printed in console, it's fine, try the last step. Otherwise share you can share the `err` output here and in the `psnode` issues.

4. Try to execute
```
processList[0]
psnode.kill(processList[0].pid, (err) => console.log(err || 'done'))
```
If all is OK, you will have an object dump and the word 'done' printed in you console (with some delay). If it displays some error, share the object dump and the error here.

**Comment by frankmariette** [comment] 2018-04-02 16:37
@AndreyBelym Just tried this out to see if it worked and had the following error. `> processList[0]
{ pid: '2024214751',
  command: '??',
  arguments:
   [ '0:04.67',
     '/Applications/Google',
     'Chrome.app/Contents/Versions/65.0.3325.181/Google',
     'Chrome',
     'Helper.app/Contents/MacOS/Google',
     'Chrome',
     'Helper',
     '--type=renderer',
     '--field-trial-handle=4432648620277866634,9616517174019563587,131072',
     '--service-pipe-token=64441D545C038F2F92E87ED15CC3920F',
     '--lang=en-US',
     '--enable-offline-auto-reload',
     '--enable-offline-auto-reload-visible-only',
     '--num-raster-threads=4',
     '--enable-zero-copy',
     '--enable-gpu-memory-buffer-compositor-resources',
     '--enable-main-frame-before-activation',
     '--enable-compositor-image-animations',
     '--service-request-channel-token=64441D545C038F2F92E87ED15CC3920F',
     '--renderer-client-id=317' ],
  ppid: '353' }
> psnode.kill(processList[0].pid, (err) => console.log(err || 'done'))
{ Error: kill ESRCH
    at Object._errnoException (util.js:1024:11)
    at process.kill (internal/process.js:183:18)
    at Function.exports.kill (/Users/frankmariette/Projects/<Project-name>/node_modules/ps-node/lib/index.js:211:13)
    at repl:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:442:10)
    at emitOne (events.js:121:20) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }`

**Comment by Sushindhran** [comment] 2018-04-02 19:34
I'm seeing the same thing.
```
{ pid: '1427822843',
  command: '??',
  arguments:
   [ '0:02.53',
     '/Applications/Google',
     'Chrome.app/Contents/MacOS/Google',
     'Chrome',
     'http://google.com' ],
  ppid: '8768' }
```
```
{ Error: kill ESRCH
    at Object._errnoException (util.js:1022:11)
    at process.kill (internal/process.js:183:18)
    at Function.exports.kill (/Users/sushindhran/Projects/test/node_modules/ps-node/lib/index.js:211:13)
    at repl:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:468:10)
    at emitOne (events.js:121:20) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
```

**Comment by Sushindhran** [comment] 2018-04-02 19:37
It works if I kill `ppid`

**Comment by frankmariette** [comment] 2018-04-02 20:54
Trying out your solution @Sushindhran I get the same result with using ppid. Trying to fork testcafe to make the fix however doesn't work for me as the test scripts seem to require them to be ran on a Windows 10 machine which I do not have access to. Maybe one of the people from testcafe can make this fix and hopefully update their contribution docs to allow mac users to make contributions as well :)

**Comment by Sushindhran** [comment] 2018-04-03 14:39
Seems like the issue is that `ps-node.lookup` doesn't find the right `pid`. The `pid` I see in `processList[0]` doesn't exist. I haven't had the time to delve deeper into this and debug. I also don't have access to a windows machine for now. :/

**Comment by AndreyBelym** [comment] 2018-04-03 15:15
Hi @frankmariette @Sushindhran, I didn't expect that the app path (`/Applications/Google Chrome/bla-bla-bla`) goes to the arguments on macOS. Could you please try to use different url (like `http://example.com`, `http://bing.com`, etc.) and accordingly run `psnode.lookup({ arguments: 'example' }, ...` or `psnode.lookup({ arguments: 'bing' }, ...` in the 2nd step?

`ppid` means Parent Process ID. You have captured info for a Chrome render process, that can be started and finished by browser time-to-time. It happened because `google` was specified as a keyword for search in arguments of process, and it matched to the Chrome app path. It can't happen with TestCafe, because TestCafe passes a special generated identifier in the browser arguments, which is quite guaranteed to be unique.

**Comment by Sushindhran** [comment] 2018-04-03 16:02
Ah, I see. Thanks @AndreyBelym. I'll try a different site.

**Comment by frankmariette** [comment] 2018-04-03 16:09
Hey @AndreyBelym I tried out using a different URL though lookup is unable to find anything so processList comes back empty. Here is the console output for the different URL. 

```
$: open -n -a /Applications/Google\ Chrome.app --args http://www.yahoo.com
$: node
> psnode = require('ps-node')
{ [Function: exports] lookup: [Function], kill: [Function] }
> psnode.lookup({ arguments: 'yahoo' }, (err, processList) => {global.err = err; global.processList = processList; console.log('done')})
undefined
> done
> processList
[]
>
```

**Comment by Sushindhran** [comment] 2018-04-03 16:10
@AndreyBelym - Tried the same with github.com

```
psnode.lookup({ arguments: 'github' }, (err, processList) => {global.err = err; global.processList = processList; console.log('done')})
undefined
> done
> processList
[ { pid: '1427822843',
    command: '??',
    arguments:
     [ '0:03.40',
       '/Applications/Google',
       'Chrome.app/Contents/MacOS/Google',
       'Chrome',
       'http://github.com' ],
    ppid: '37716' } ]
> processList[0]
{ pid: '1427822843',
  command: '??',
  arguments:
   [ '0:03.40',
     '/Applications/Google',
     'Chrome.app/Contents/MacOS/Google',
     'Chrome',
     'http://github.com' ],
  ppid: '37716' }
> psnode.kill(processList[0].pid, (err) => console.log(err || 'done'))
{ Error: kill ESRCH
    at Object._errnoException (util.js:1022:11)
    at process.kill (internal/process.js:183:18)
    at Function.exports.kill (/Users/sushindhran/Projects/test/node_modules/ps-node/lib/index.js:211:13)
    at repl:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:468:10)
    at emitOne (events.js:121:20) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
```

**Comment by AndreyBelym** [comment] 2018-04-03 16:58
Thank you kindly @Sushindhran! Looks like `ps-node` incorrectly parses output of `ps` in your case. Some of us should submit a bug report to the `ps-node` 😈. I will submit the bug and post a link to an issue here, If I reproduce the problem, or figure out what causes it.

**Comment by vigneshwar-v** [comment] 2018-04-06 16:16
any updates on this??

**Comment by AndreyBelym** [comment] 2018-04-10 08:39
Hi @vigneshwar-v. it works. I've caught a cold, so the fix was delayed a bit, but I will try to ship it ASAP now.

**Comment by vigneshwar-v** [comment] 2018-04-10 11:35
@andreybelym.. Sorry for being desperate... Take care man.. And thanks for the check-in

**Closed** 2018-04-13 16:17 UTC
Labels: OS: Mac, SYSTEM: browser natives, TYPE: bug

**Comment by gregorycv** [comment] 2018-09-06 11:26
Hi, @Sushindhran 's solution has worked for chrome but while testing in safari and firefox there are still some issues. 

Safari closes the tab, but not the browser and, in addition to that, the node process keeps running and I need to quit it with ctrl+c. 

Firefox closes the browser, but the same thing with the node process occurs.

Any suggestions how to go about this?

Huge thanks!

**Comment by AndreyBelym** [comment] 2018-09-06 12:01
Hi @gregorycv, please check the `testcafe@0.22.0`, I've made some improvements to the browser process termination code in this version.

**Comment by gregorycv** [comment] 2018-09-06 12:27
@AndreyBelym thanks for your prompt reply.
Excuse me if I am getting something wrong as I am still fairly new to GitHub and TestCafe

I am currently using TestCafe 0.22 on MacOS with Chrome 68.0.3440, Safari 11.1.1 and Firefox 61 

Once TestCafe is installed and 
`var processOptions = { arguments: browserId, psargs: '-ef' };` 
neither of the browsers close correctly after test execution

If I change that to
`{arguments: browserId, psargs: 'aux'}`
both Chrome and Firefox are closed after all tests have completed execution, but not Safari.

On top of that - in case with Firefox and Safari node process does not terminate.

Please let me know if that's an issue on my side or a more general problem.

I'd gladly share any additional information if that helps.

Thanks!

**Comment by AndreyBelym** [comment] 2018-09-06 13:36
The `psargs: 'aux'` options was used in `testcafe@0.21.0`, could you please check that it works on your machine? I've changed the `psargs` value to `-ef` because some users still reported the problem with the `aux` parameter, but not with the `-ef` parameter.

I've never reproduced the problem with hanging node process on macOS, so I will think about how to collect debug information in your case. 

TestCafe can't terminate Safari process in general, because all Safari windows and tabs in the system share the same process. It means that if TestCafe terminate the process, TestCafe will close also windows and tabs opened by a user, it would be too frustrating. Maybe it's possible to check if TestCafe's window is the only Safari window opened, and close it in this case.

**Comment by gregorycv** [comment] 2018-09-06 14:11
@AndreyBelym 
Ok, so I've tried installing 0.21.0 and running my tests, as a result:
chrome works fine both browser and node process are closed and terminated
firefox browser is closed but the process is hanged
safari browser remains open (as you've explained) and the process is hanged

**Comment by bhreinb** [comment] 2018-09-11 21:52
@AndreyBelym
I'm seeing exactly the same that @gregorycv described above with same version. Re firefox that occurs for me when I run it headless or in regular mode.

Should this ticket be re-opened?

Btw I also see as part of that test run which may be of concern

> (node:2091) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by RichieAHB** [comment] 2018-10-31 11:35
This is happening for me on macOS Mojave using Chrome 70.

**Comment by AndreyBelym** [comment] 2018-10-31 11:57
@RichieAHB, could you please try to install `testcafe@0.23.1` and check if it fixes the problem?

**Comment by RichieAHB** [comment] 2018-10-31 14:39
Is that `alpha.2` or is there a release there?

**Comment by AndreyBelym** [comment] 2018-10-31 14:41
Yes, my mistake, you should try `testcafe@0.23.1-alpha.2`.

**Comment by RichieAHB** [comment] 2018-10-31 16:04
@AndreyBelym works like a charm 👌 - also, while I'm here, I've no idea how you got your drag and dropping working in chrome. Puppeteer and Selenium both failed on this count. Great work.

**Comment by RichieAHB** [comment] 2018-10-31 16:05
@AndreyBelym - we're not that keen on requiring alpha versions on our team, so do you know (very roughly) when this might land? Thanks again.

**Comment by AndreyBelym** [comment] 2018-10-31 16:30
The current estimate for `testcafe@0.23.1` is the middle of November.
