### ISSUE TITLE
Rigid Test Structure Requirement

### ISSUE THREAD

**Issue by lsklyut** [DevExpress/testcafe#2622] opened 2018-07-13 17:57 UTC
### Are you requesting a feature or reporting a bug?

I think this is a bug - I believe that as long as we call the correct fixture/test functions, the test should run OK.

### What is the current behavior?

If we wrap the testcafe library calls in a class which is called inside our test script, the test runner will not recognize that there are tests in the file. Adding:

```
// fixture(
// test(
```

somewhere in the root file makes the test runner realize that there are in fact tests in the file. It then runs the correct test as expected.

### What is the expected behavior?

The test runner should run the provided test file regardless of the structure, if tests have been registered using the fixture() and test() functions.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://devexpress.github.io/testcafe/example

Test code

wrapper.js
```js
import { Selector } from 'testcafe';

export class WrappedFixture {
    constructor(fixtureName) {
        this.wrappedFixture = fixture(fixtureName)
    }

    setPage(pageUrl) {
        this.wrappedFixture.page(pageUrl);
    }
}

export class WrappedTest {
    constructor(testName) {
        test(testName, async t => {
            await t
                .typeText('#developer-name', 'John Smith')
                .click('#submit-button')

                // Use the assertion to check if the actual header text is equal to the expected one
                .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
        });
    }
}
```

testfile.js
```js
import { WrappedFixture, WrappedTest } from './wrapper'

new WrappedFixture('Getting Started')
  .setPage('https://devexpress.github.io/testcafe/example');

new WrappedTest('My first test');

// fixture(
// test(
```
 
This results in the test being ran correctly: 

```
$ testcafe firefox testfile.js
Using locally installed version of TestCafe.
 Running tests in:
 - Firefox 61.0.0 / Windows 10.0.0

 Getting Started
 √ My first test


 1 passed (2s)
```

Removing or altering the comments at the bottom of testfile.js will result in no tests being found. The following altered versions result in no tests being found:

```
1)
//fixture(
// test(

2)
// fixture(
//test(

3)
//fixture(
//test(

4)
<no comments at all>
```

Result:

```
$ testcafe firefox testfile.js
Using locally installed version of TestCafe.
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

Type "testcafe -h" for help.

```

This is a very simple example, and isn't very useful on its own but the idea is that I'd like to create a wrapper for the library such that when breaking changes occur (or if we switch tools), we could update only the wrapper classes without having to alter our entire test suite.

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.4
* node.js version: v8.11.3

**Comment by lsklyut** [comment] 2018-07-13 18:10
I dug into the testcafe source to see if I can help contribute to make these changes. I found the line which throws the exception, but commenting it out only causes the test runner to fail further down the call stack. Something that is collecting the tests is doing so incorrectly, I think? 

I am at a point where I want to run testcafe from my cloned version of the repo rather than the one installed via NPM (so I can debug through it). The problem is that bin/testcafe.js requires ../lib/cli but that file does not exist for me locally. I guess I need to build the project with gulp but it's failing for me locally. I'll keep digging and have a look at the travis builds to see how the project needs to be built correctly.

**Comment by AndreyBelym** [comment] 2018-07-16 08:51
Hi @lsklyut, you need to install https://github.com/gulpjs/gulp and build the project with `gulp build`. Unfortunately, this issue is a duplicate of #2074, so let's move our discussion there.

**Closed by AndreyBelym** 2018-07-16 08:51 UTC

**Comment by lsklyut** [comment] 2018-07-17 15:07
Thanks for pointing me in the right directory @AndreyBelym !
