### ISSUE TITLE
Only first test loads all resources correctly

### ISSUE THREAD

**Issue by xalvarez** [DevExpress/testcafe#4555] opened 2019-12-06 14:15 UTC
### What is your Test Scenario?

Testing a website which relies on multiple JavaScript classes.

### What is the Current behavior?

All classes are always loaded on the first test. Afterwards, not all classes are loaded.
 
### What is the Expected behavior?
All classes are always loaded.
 
### What is your web application and your TestCafe test code?

I'm testing a html page, let's say `index.html`, which includes a JavaScript module as follows:

    <script src="app.js" type="module"></script>

Additionally, `app.js` imports a JavaScript class: 

    import ExampleClass from './ExampleClass.js'

And this is how `ExampleClass` is defined:

    export default class ExampleClass {
    }

As for my test class, it defines the following fixture:

    fixture`Example`
      .page`index.html`
 
In this situation, if I run any number of tests, `ExampleClass` is **only correctly loaded the first time**. **After the first test**, no matter what this first test looks like, any other test logs a 404 for `ExampleClass` in the browser console. However, the local file's path as shown in the console log exists in the filesystem, although Testcafé fails to find it.

Sample project: https://github.com/xalvarez/testcafe-import-class-issue

### Your Environment details:
 
* testcafe version:                   1.7.0
* node.js version:                    12.13.1
* command-line arguments:   testcafe chromium test/
* browser name and version: Chromium 78.0.3904.108
* platform and version:          Ubuntu 18.04.3

**Comment by AlexKamaev** [comment] 2019-12-09 10:56
Please provide us with a sample project and test code, which demonstrate the issue.

**Comment by xalvarez** [comment] 2019-12-09 13:01
I've written this sample project to reproduce the issue: https://github.com/xalvarez/testcafe-import-class-issue

**Comment by Farfurix** [comment] 2019-12-11 11:42
@xalvarez 

Hello,

Thank you for the sample project. I reproduced the issue under Windows 10 / Chrome 79. Our team will research it and check for a suitable solution.

**Comment by miherlosev** [comment] 2021-01-11 07:57
Hi @xalvarez 

The problem is fixed in the `testcafe@1.10.1` version.

**Closed by miherlosev** 2021-01-11 07:57 UTC
Labels: FREQUENCY: level 1, TYPE: bug
