### ISSUE TITLE
TestCafe can't run type automation on input with "time" type

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#1258] opened 2017-02-20 16:41 UTC
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

test fails with an exception, when try to type in input with `time` type.

### What is the expected behavior?

TestCafe should run type automation  without exceptions

### How would you reproduce the current behavior (if this is a bug)?

run test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

page markup:
```html
<body>
<input id="input-time" type="time" step="1">
</body>
```

Test code

```js
test('type in input with "time" type', async t => {
    await t.typeText('#input-time', '11');
});

```

### Specify your

* operating system: Win10 x64
* testcafe version: 0.13.0
* node.js version: 7.2.0

**Comment by georgiy-abbasov** [comment] 2017-03-16 17:14
Some information about work realization with this type of input:
1. Internet explorer 11
![Example](https://content.screencast.com/users/GeorgeZA/folders/Jing/media/19d8c848-67bb-4f8e-95e2-c6e0d3c0bb9c/2017-03-16_1912.png)
2. Firefox 52 && 54.0a2
![Example](https://content.screencast.com/users/GeorgeZA/folders/Jing/media/d63b412d-a08e-49ed-9ba6-4c0c72878f71/2017-03-16_1910.png)
3. Edge older than 13
![Example](https://content.screencast.com/users/GeorgeZA/folders/Jing/media/192bd82f-ae33-456c-80d4-62f922fd26ba/2017-03-16_1915.png)

Work with this type isn't implemented. If we try to get input type, browser will return 'text'.

4. Edge since 13
![Example](https://content.screencast.com/users/GeorgeZA/folders/Jing/media/6f9062a1-c879-445d-a499-d25afb88ab67/2017-03-16_1925.png)
Edge has native popup control with spinners for editing time, which is showing on click on the input. It allows to select only correct time, because it's not allowed to directly type  value to input . If input has attribute specified limiters like `min` and `max`, it limits the popup spinners. Input raises "change" and "input" events on popup closing and only if actual value has changed.

5. Chrome 
![Example](https://content.screencast.com/users/GeorgeZA/folders/Jing/media/ec550e8b-764a-4115-9fb6-fd8ab4a47ba9/2017-03-16_1951.png)
Chrome allows to directly type to input, so value can be changed partially, if input was filled before. If value limits exceeded, input just show hint, when are under mouse cursor. Events are raised when the value has been filled by 'HH:MM' template as minimum and even when value is changed.

**Comment by AlexanderMoskovkin** [comment] 2017-03-17 11:17
@georgiy-abbasov please take a look at #1327 (we've discussed it in private)

**Comment by AlexanderMoskovkin** [comment] 2017-04-19 14:13
duplicate of #1327

**Closed by AlexanderMoskovkin** 2017-04-19 14:13 UTC
Labels: AREA: client, REASON: duplicate, SYSTEM: automations, TYPE: bug

**Comment by ninjaPixel** [comment] 2018-05-09 09:51
FYI, anyone who's come here via  a Google search, you can now do the following to enter a time (tested in Chrome)

```
t.typeText('#input-time', '11:00')
```
