### ISSUE TITLE
[WIP] SurveyJS test failed

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1538] opened 2017-06-15 13:59 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Tests fail: https://travis-ci.org/surveyjs/surveyjs/builds/242732574

### What is the expected behavior?
Tests should not fail. Tested functionality works when tested manually.

### How would you reproduce the current behavior (if this is a bug)?
Run the test.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
    test(`choose other`, async t => {
        const getOtherInput = Selector(() =>
            document.querySelectorAll("div:nth-child(12) input")[1]);
        let surveyResult;

        await setOptions('car', { hasOther: true });
        await t
            .click(`div:nth-child(12) label input`)
            .typeText(getOtherInput, 'Zaporozec')
            .pressKey('tab')
            .click(getOtherInput)
            .click(`input[value=Complete]`);

        surveyResult = await getSurveyResult();
        assert.equal(surveyResult.car, 'other');
        assert.equal(surveyResult['car-Comment'], 'Zaporozec');
    });
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.16.0
* node.js version:  8.0.0

**Comment by AlexanderMoskovkin** [comment] 2017-06-22 12:31
We've found the cause of the problem. It's a duplicate of #1558

**Closed by AlexanderMoskovkin** 2017-06-22 12:31 UTC
Labels: AREA: client, BROWSER: Chrome, REASON: duplicate, SYSTEM: automations, TYPE: bug
