### ISSUE TITLE
Parallel Test Option is not working 

### ISSUE THREAD

**Issue by guptaakhil** [DevExpress/testcafe#2228] opened 2018-03-19 12:42 UTC
### Are you requesting a feature or reporting a bug?

feature : Parallel Test Option is not working 

### What is the current behavior?

Serial Execution is happening

### What is the expected behavior?
script have to be excure parallel, i.e. testcafe -c 3 chrome script.js. 
three instance of chrome should open and execute it parallel the same script.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: windos 7
* testcafe version:
* node.js version:

**Comment by vivekpant28** [comment] 2018-03-19 12:54
Hi Testcafe team,

ask is that we want to use runner in headless mode to run all end to end tests together and their is no dependencies among the test scripts, so once we run these in parallel it will save our execution time.

we have followed the step mention as : 
http://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/concurrent-test-execution.html
but somehow it is not working a our end , Can you please guide us how to resolve the same.

currently we mentioned that 
...
runner..concurrency(3) 
... 
it will run scripts in sires where it is suppose to run in parallel.

**Comment by AndreyBelym** [comment] 2018-03-19 14:12
Hi @vivekpant28, @guptaakhil, please specify your Node.js and TestCafe version, installation method(NPM/Yarn, local/global, official or custom Docker image, etc.) and command that is used to start TestCafe or contents of runner file that uses TestCafe API.

Also, could you please try to run the following test (you can also download it [here]()):
```
fixture `Concurrent`.page`example.com`;

const timeline = [];

test('Long test', async t => {
    timeline.push('long started');

    await t.wait(5000);

    timeline.push('long finished');
});

test('Short test', async t => {
    timeline.push('short started');

    await t.wait(1000);

    timeline.push('short finished');
});

test('Results', async t => {
    await t.wait(6000);

    await t.expect(timeline).eql(['long started', 'short started', 'short finished', 'long finished']);
});
```

**Comment by guptaakhil** [comment] 2018-03-20 03:43
Hi we have beenused the same command but it's not performed expected Behaviour, 

testcafe Version : 0.18.6
node version : v6.10.3
npm version : 3.10.10


please help us to find out Problem area.

**Comment by AndreyBelym** [comment] 2018-03-20 07:33
Hi @guptaakhil, could you please provide me the command you have used to start TestCafe together with the report?

**Comment by AndreyBelym** [comment] 2018-03-20 08:46
@guptaakhil, please, run Testcafe using the following command 
```
testcafe chrome test.js --concurrency 2
``` 
for the following test:
```
//test.js
fixture `Concurrent`.page`example.com`;

const timeline = [];

test('Long test', async t => {
    timeline.push('long started');

    await t.wait(5000);

    timeline.push('long finished');
});

test('Short test', async t => {
    timeline.push('short started');

    await t.wait(1000);

    timeline.push('short finished');
});

test('Results', async t => {
    await t.wait(6000);

    await t.expect(timeline).eql(['long started', 'short started', 'short finished', 'long finished']);
});
```

and provide me the output of the command.

Or, you can send me your test code if your webpage is accessible not only from your company network.

**Comment by vivekpant28** [comment] 2018-03-21 09:16
Hi Andrey ,

Thanks for your prompt response.
let me explain the scenario.

there are  15+ .js files for the end to end scenario, where each .js file is having a single test with specific validation. now I want to run these .js file using the testRunner, and want to run them parallel, so that overall execution time will be saved.

**Comment by miherlosev** [comment] 2018-05-03 13:51
Hi @vivekpant28.
It's a difficult to understand the reason of the problem without information from your side.
We need an example which we can reproduce locally.
I will close the issue.
Try to use the latest `TestCafe` version - `testcafe@0.19.2`.
Feel free to reopen the issue if problem persists and you can provide example to reproduce it.

**Closed by miherlosev** 2018-05-03 13:51 UTC

**Comment by AndreyBelym** [comment] 2018-05-15 07:32
@guptaakhil, you need at least 2 tests to run them concurrently with `-c 2`, or at least 4 tests with `-c 4`. It doesn't run a test in each browser multiple times, it dispatches different tests to run in a number of browser instances. Copy this testscript to different files (`testile1.js`, `testfile2.js`, `testfile3.js`, `testfile4.js`) and then run TestCafe with the following command:
```
testcafe chrome -c 2 testfile*.js
```

**Comment by guptaakhil** [comment] 2018-05-15 14:09
So, what would be option to run same test in same browser n no. Times

**Comment by AndreyBelym** [comment] 2018-05-15 15:06
You can just repeat chrome `n` times in command line arguments:
```
testcafe chrome,chrome,chrome test.js
```

or use `for` loop with concurrency:
```
// test.js
fixture `Example`
    .page `example.com`;

for (let i = 0; i < 4; i++) {
    test('Test', sync t => ...);
}
```
```
testcafe -c 4 test.js
```
