### ISSUE TITLE
Can't find transform for "Node" type.

### ISSUE THREAD

**Issue by andrzej-kodify** [DevExpress/testcafe#3129] opened 2018-11-17 20:47 UTC
### What is the Current behavior?
Test runner hangs on this exception. It happens only on emulated `ipad`

```
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message             "Warning: %s is deprecated in StrictMode. %s was passed an instance of %s which is inside StrictMode. Instead, add a ref directly to the element you want to reference.\n%s\n\nLearn more about using refs safely here:\nhttps://fb.me/react-strict-mode-find-node findDOMNode findDOMNode VisibilitySensor \n    in div (created by Context.Consumer)\n    in StyledComponent (created by ProgressiveImage__ImageSizeContainer)\n    in ProgressiveImage (created by VisibilitySensor)\n    in VisibilitySensor (created by VisibilityProgressiveImage)\n    in VisibilityProgressiveImage (created by Context.Consumer)\n    in StyledComponent (created by VideoHero__StyledProgressiveImage)\n    in a (created by Link)\n    in Link (created by Connect(Link))\n    in Connect(Link) (created by Context.Consumer)\n    in StyledComponent (created by VideoHero__VideoContainer)\n    in div (created by Context.Consumer)\n    in StyledComponent (created by VideoHero__Wrapper)\n    in VideoHero (created by HomePage)\n    in HomePage (created by Context.Consumer)\n    in WithTranslate(HomePage) (created by WithMainLayout(WithTranslate(HomePage)))\n    in main (created by WithMainLayout(WithTranslate(HomePage)))\n    in WithMainLayout(WithTranslate(HomePage)) (created by Connect(WithMainLayout(WithTranslate(HomePage))))\n    in Connect(WithMainLayout(WithTranslate(HomePage)))\n    in AppContainer (created by HotExportedComponent)\n    in HotExportedComponent (created by UniversalComponent(home))\n    in UniversalComponent(home) (created by RouteSwitcher)\n    in ErrorBoundary (created by RouteSwitcher)\n    in RouteSwitcher (created by Connect(RouteSwitcher))\n    in Connect(RouteSwitcher)\n    in TranslateProvider (created by App)\n    in ErrorBoundary (created by App)\n    in StrictMode (created by App)\n    in App (created by Connect(App))\n    in Connect(App) (created by HotExportedConnect(App))\n    in AppContainer (created by HotExportedConnect(App))\n    in HotExportedConnect(App)\n    in Provider"
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           ]
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         }
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       },
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "disableResending": true,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "allowRejecting": true,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "sessionId": "36BcllFOn"
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message     }
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message     {
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "cmd": "ready",
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "status": {
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "id": "4968.800000002375",
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "isCommandResult": false,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "executionError": null,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "pageError": null,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "resent": false,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "result": null,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "consoleMessages": {
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           "log": [],
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           "info": [],
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           "warn": [],
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           "error": []
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         }
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       },
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "disableResending": true,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "allowRejecting": true,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "sessionId": "36BcllFOn"
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message     }
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message  +1s
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message     {
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "cmd": "ready",
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "status": {
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "id": "9366.500000003725",
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "isCommandResult": true,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "executionError": null,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "pageError": null,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "resent": false,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "result": [
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           {
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message             "@t": "[[undefined]]",
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message             "data": ""
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           }
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         ],
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         "consoleMessages": {
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           "log": [],
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           "info": [],
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           "warn": [],
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message           "error": []
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message         }
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       },
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "disableResending": true,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "allowRejecting": true,
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message       "sessionId": "36BcllFOn"
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message     }
  testcafe:test-run:HeadlessChrome 70.0.3538 / Mac OS X 10.14.1:driver-message  +4s
 ✖ HomePage

   1) Error: Can't find transform for "Node" type.

      Browser: HeadlessChrome 70.0.3538 / Mac OS X 10.14.1

         192 |DecodingTransformer.prototype._handleTransformedObject = function (obj, parent, key) {
         193 |    var transformType = obj[TRANSFORMED_TYPE_KEY];
         194 |    var transform     = this.transformMap[transformType];
         195 |
         196 |    if (!transform)
       > 197 |        throw new Error('Can\'t find transform for "' + transformType + '" type.');
         198 |
         199 |    this.activeTransformsStack.push(obj);
         200 |    this._handleValue(obj.data, obj, 'data');
         201 |    this.activeTransformsStack.pop();
         202 |

         at DecodingTransformer._handleTransformedObject (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/replicator/index.js:197:15)
         at DecodingTransformer._handleValue (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/replicator/index.js:258:14)
         at DecodingTransformer.transform (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/replicator/index.js:271:10)
         at module.exports.Replicator.decode (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/replicator/index.js:559:24)
         at ClientFunctionBuilder.decode [as _processResult] (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/testcafe/src/client-functions/client-function-builder.js:142:32)
         at _processResult (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/testcafe/src/client-functions/client-function-builder.js:137:25)
         at step (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
         at <anonymous> (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13)
         at $$testcafe_test_run$$36BcllFOn$$ (/Users/xxxxx-yyyyy/projects/zzzzzz-frontend/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
```

### What is the Expected behavior?
I think it should be handled.
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    v10.13.0
* command-line arguments:  `CHROME_DEVICE=ipad node node_modules/.bin/testcafe "chrome:headless:emulation:device=${CHROME_DEVICE} --disable-dev-shm-usage --disable-gpu-sandbox --disk-cache-dir=/tmp/cache-dir --no-sandbox --disable-gpu --no-first-run --disable-setuid-sandbox --disable-client-side-phishing-detection --incognito --disable-client-side-phishing-detection --disable-extensions --disable-notifications --disable-ntp-popular-sites --disable-ntp-most-likely-favicons-from-server --disable-sync --disable-zero-browsers-open-for-tests --no-pings --safebrowsing-disable-auto-update --safebrowsing-disable-download-protection --safebrowsing-disable-extension-blacklist --safebrowsing-manual-download-blacklist --bwsi" test/functional/tests/visual --skip-js-errors --skip-uncaught-errors -s test/functional/logs/screenshots -r spec,xunit:test/functional/logs/testcafe-results-visual-${CHROME_DEVICE}.xml`
* browser name and version: Chrome 70.0.3538.102 (Official Build) (64-bit)
* platform and version:          macOS 10.14.1 (18B75)

**Comment by AlexKamaev** [comment] 2018-11-19 12:15
I ran TestCafe on a machine with the same configuration as you described but was not able to reproduce the issue using the following example:
```JS
fixture `test`
    .page `http://example.com`;
 
test(`test`, async t => {
    await t.click('h1');
});
```
 
Could you please check if the issue is reproducible on my example? If you cannot reproduce it, could you share your test project demonstrating the problem?

**Comment by AugustynsWim** [comment] 2021-05-07 11:56
Has there been a solution for this issue? Had the same issue a few days ago...

**Comment by AlexSkorkin** [comment] 2021-05-10 07:07
We didn't manage to reproduce this behavior. If you have a sample where we can replicate it, please share it with us so we can research it.

**Comment by AlexGrisin** [comment] 2021-06-30 09:36
Hello!

This issue is still reproducible in our tests when we run it in Safari browser. It often occurs when the following scenario is executed:

1. Open product lister page
2. Open any product page
3. Navigate back using client function  

I have created a sample that demonstrates the issue:
https://github.com/AlexGrisin/go-back-demo-testcafe

Run:
`npm run test-bs-safari`

Result:
`> demo-testcafe@1.0.0 test-bs-safari
> testcafe 'browserstack:safari@14.0:OS X Big Sur' test

         Running tests in:
 - Safari 14.1 / macOS 10.15.7
 (https://automate.browserstack.com/builds/86b136c3b612f7015c5a283ea91619acbdae4d44/sessions/ac6716b60b3e96134a8be81a0b5c02262402c39e)

 Fixture browser go back
 ✖ Test browser go back

   1) Error: Can't find transform for "Node" type.

      Browser: Safari 14.1 / macOS 10.15.7

   (https://automate.browserstack.com/builds/86b136c3b612f7015c5a283ea91619acbdae4d44/sessions/ac6716b60b3e96134a8be81a0b5c02262402c39e)

         196 |DecodingTransformer.prototype._handleTransformedObject = function (obj, parent, key) {
         197 |    var transformType = obj[TRANSFORMED_TYPE_KEY];
         198 |    var transform     = this.transformMap[transformType];
         199 |
         200 |    if (!transform)
       > 201 |        throw new Error('Can\'t find transform for "' + transformType + '" type.');
         202 |
         203 |    this.activeTransformsStack.push(obj);
         204 |    this._handleValue(obj.data, obj, 'data');
         205 |    this.activeTransformsStack.pop();
         206 |

         at DecodingTransformer._handleTransformedObject
      (/Users/agrisin/Projects/gstar/go-back-demo-testcafe/node_modules/replicator/index.js:201:15)
         at DecodingTransformer._handleValue
      (/Users/agrisin/Projects/gstar/go-back-demo-testcafe/node_modules/replicator/index.js:262:14)
         at DecodingTransformer._handleValue
      (/Users/agrisin/Projects/gstar/go-back-demo-testcafe/node_modules/replicator/index.js:266:18)
         at DecodingTransformer.transform
      (/Users/agrisin/Projects/gstar/go-back-demo-testcafe/node_modules/replicator/index.js:275:10)
         at module.exports.Replicator.decode
      (/Users/agrisin/Projects/gstar/go-back-demo-testcafe/node_modules/replicator/index.js:577:24)



 1/1 failed (31s)`

**Comment by AlexGrisin** [comment] 2021-06-30 09:44
Hello!

This issue is still reproducible in our tests when we run it in Safari browser. It often occurs when the following scenario is executed:

Open product lister page
Open any product page
Navigate back using client function
I have created a sample that demonstrates the issue:
https://github.com/AlexGrisin/go-back-demo-testcafe

`npm run test-bs-safari`

         196 |DecodingTransformer.prototype._handleTransformedObject = function (obj, parent, key) {
         197 |    var transformType = obj[TRANSFORMED_TYPE_KEY];
         198 |    var transform     = this.transformMap[transformType];
         199 |
         200 |    if (!transform)
       > 201 |        throw new Error('Can\'t find transform for "' + transformType + '" type.');
         202 |
         203 |    this.activeTransformsStack.push(obj);
         204 |    this._handleValue(obj.data, obj, 'data');
         205 |    this.activeTransformsStack.pop();
         206 |

         at DecodingTransformer._handleTransformedObject
      (/Users/agrisin/Projects/go-back-demo-testcafe/node_modules/replicator/index.js:201:15)
         at DecodingTransformer._handleValue
      (/Users/agrisin/Projects/go-back-demo-testcafe/node_modules/replicator/index.js:262:14)
         at DecodingTransformer._handleValue
      (/Users/agrisin/Projects/go-back-demo-testcafe/node_modules/replicator/index.js:266:18)
         at DecodingTransformer.transform
      (/Users/agrisin/Projects/go-back-demo-testcafe/node_modules/replicator/index.js:275:10)
         at module.exports.Replicator.decode
      (/Users/agrisin/Projects/go-back-demo-testcafe/node_modules/replicator/index.js:577:24)

**Comment by miherlosev** [comment] 2021-07-01 07:45
@AlexGrisin 

Thank you for the shared example. I've reproduced the problem.

**Comment by miherlosev** [comment] 2022-05-18 09:19
Duplicate of https://github.com/DevExpress/testcafe/issues/5260.

**Closed by miherlosev** 2022-05-18 09:19 UTC
Labels: TYPE: bug, FREQUENCY: level 1

**Comment by Kirdock** [comment] 2023-10-04 14:17
This problem seems to happen again
```
1) Error: Can't find transform for "Node" type.

Browser: Firefox 113.0 / Ubuntu 18.04

196 |DecodingTransformer.prototype._handleTransformedObject = function (obj, parent, key) {
197 |    var transformType = obj[TRANSFORMED_TYPE_KEY];
198 |    var transform     = this.transformMap[transformType];
199 |
200 |    if (!transform)
> 201 |        throw new Error('Can\'t find transform for "' + transformType + '" type.');
202 |
203 |    this.activeTransformsStack.push(obj);
204 |    this._handleValue(obj.data, obj, 'data');
205 |    this.activeTransformsStack.pop();
206 |
at DecodingTransformer._handleTransformedObject (/.../node_modules/replicator/index.js:201:15)
at DecodingTransformer._handleValue (/.../node_modules/replicator/index.js:262:14)
at DecodingTransformer._handleValue (/.../node_modules/replicator/index.js:266:18)
at DecodingTransformer.transform (/.../node_modules/replicator/index.js:275:10)
at module.exports.Replicator.decode (.../node_modules/replicator/index.js:577:24)
```
The "duplicate of" is not completely right. Both is related to Firefox and a certain workflow of actions but the error message are different

**Comment by AlexKamaev** [comment] 2023-10-06 08:21
Hello @Kirdock,

This issue was marked "closed as complete", so please create a separate issue and share a simple sample that reproduces the incorrect behavior. Use the following link: [https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&projects=&template=bug_report.yaml](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&projects=&template=bug_report.yaml)
