### ISSUE TITLE
Sockets hanging with node16

### ISSUE THREAD

**Issue by andrzej-woof** [DevExpress/testcafe#7097] opened 2022-06-17 12:59 UTC
### What is your Scenario?

Web app that makes client side fetch to two API endpoints, both on localhost but one is not running, so doesn't accept connections (which is fine, error is handled and app is functional)

Running tests with node v14.x is just fine, after switching to v16 tests start to break after a while
Symptoms observed in chrome network tools are that calls to both API endpoints are in `pending` state

After a while of debugging I've noticed that testcafe's behaviour for requests that are supposed to fail (since there's no server listening) is much different in node16 than node14
Looking at network tools:
Node v16
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/40596514/174300644-9653887e-a5d5-4127-9333-26c1b25a0ec1.png">

Node v14
<img width="618" alt="image" src="https://user-images.githubusercontent.com/40596514/174300961-6a9b0545-ef31-4f2a-9e02-a069d3f339ee.png">

As you can see, in node 14 such request fails instantly, as it should. With node 16 the request is `pending`.
I cannot prepare a sample that reproduces my exact problem (where after a while both `/api` calls are constantly `pending` in subsequent tests) but I'm assuming maybe sockets are not properly closed in my case and just saturate some system limits

### What is the Current behavior?

Fetch requests that are supposed to fail are `pending`

### What is the Expected behavior?

Requests should fail immediately if there's no server listening on the other end

### What is your public website URL? (or attach your complete example)

https://github.com/andrzej-kodify/testcafe-hanging-sockets
Launch server
```
npm run serve
```

Launch tests with node 16
```
npm run test:debug
```
and look in chrome network tools on how failed requests behave. Tests are passing, no JS errors.

Do the same with node 14 - requests fail immediately, and there's a JS error (as fetch exception is not handled)

### What is your TestCafe test code?

// https://github.com/andrzej-kodify/testcafe-hanging-sockets

```js
const { Selector } = require("testcafe");

fixture('Fixture');

for (let i=0; i<1000; i++) {
    test(`Test ${i}`, async (browser) => {
        await browser.navigateTo('http://localhost:3666/');
        await browser.expect(Selector('#response').innerText).match(/[0-9]+/);
    });
}
```

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.19.0

### Node.js version

version v14.18.1 runs fine, versions 16+ (e.g. v16.15.1) fail

### Command-line arguments

chrome

### Browser name(s) and version(s)

Version 102.0.5005.61 (Official Build) (arm64)

### Platform(s) and version(s)

macOS 12.4

### Other

I've made silly workaround by applying this patch in my actual tests
https://github.com/andrzej-kodify/testcafe-hanging-sockets/blob/main/testcafe-hammerhead%2B24.5.16.patch

**Comment by xiaowanfeng** [comment] 2022-07-08 03:02
I meet this issue to

![image](https://user-images.githubusercontent.com/9332113/177908667-62f449a5-5634-4b78-bab0-b2956abca782.png)

The request is pending

**Comment by marliz97** [comment] 2022-07-08 10:29
Have the same issue, but only with multipart/form-data requests. In my case issue persists in both node14 and node16
<img width="1792" alt="file-upload-debug" src="https://user-images.githubusercontent.com/45404644/177974352-348e5f30-7cb0-49bd-b3f8-2c63871e76f3.png">

**Comment by vizdatom** [comment] 2022-10-07 07:55
Hello, I experience the same issue with pending requests, when I create a request to non-existing domain, so the DNS fails to resolve the domain name, and the error is not passed to the client.

**Comment by VasilyStrelyaev** [comment] 2022-10-10 10:56
Thank you for the additional information! We increased the frequency level for this issue, which will give it higher priority during our future planning.

**Comment by cattermo** [comment] 2022-11-24 13:57
Can someone please work on this?! We are stuck with super old Testcafé since this bug prevents us from upgrading node version. We have this problem with node 14 as well 😢

**Comment by miherlosev** [comment] 2022-11-29 07:41
Hi @cattermo,

This issue may be fixed in the latest version of TestCafe (`2.1.0`). Please try running the tests in the latest TestCafe version and let us know your results.

**Comment by cattermo** [comment] 2022-12-08 09:18
> Hi @cattermo,
> 
> This issue may be fixed in the latest version of TestCafe (`2.1.0`). Please try running the tests in the latest TestCafe version and let us know your results.

Ok, so we have upgraded now since a couple of weeks back. Problem is, we are having so many intermittent errors where requests are just stuck and causing "Failed to fetch" errors, similar to when we tried last time to upgrade, found this bug reported, and decided to downgrade again. The "intermittent" part means that different random tests will have this error almost every test run but by using quarantine mode we can be lucky and have all tests pass.

Findings from trying to investigate this issue:

- The "stuck" requests are nowhere to be found in our own logs. Seems they are never sent. 
- We only see this problem when running Testcafe, never for real users.
- We only see this problem when running tests against a real environment, not against localhost
- The process for how it happens (intermittently) is usually
    - Load GUI (React SPA)
    - All ajax requests stuck in pending
    - "Failed to fetch" javascript error fails test OR
    - Element X not found (since API request stuck)

Other info:
- We are using CORS (api on different sub-domain)

**Comment by dcsaszar** [comment] 2022-12-29 15:58
FYI after upgrading to 2.2.0 I learned about `"experimentalProxyless": "true"` and gave it a try.
With this option, I run into this issue. I've never experienced this issue without the `experimentalProxyless` option. Node v16.14.2.

**Comment by aleks-pro** [comment] 2023-01-05 09:00
Hello @dcsaszar ,

Thank you for pointing out the issue to us.
According to your description, the cause of the problem most likely is different from the original issue in this thread, although the symptoms are the same. Could you please [create a separate issue](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml) with a project sample that we can use to reproduce the problem? It will help us to improve the `Proxyless` mode and take it out of the experimental state.

**Comment by cattermo** [comment] 2023-01-05 09:05
One more comment to this, we really can't get Testcafe to work on node 16/18 without a lot of requests stuck in pending (intermittently). The `experimentalProxyless` option did not make any difference. It works well with node v14.18.3 and Testcafe v2.1.0.

**Comment by aleks-pro** [comment] 2023-01-11 07:53
Hi @cattermo ,

Since the problem in your project can be reproduced with the experimental `Proxyles`s mode enabled, I'm not sure that this issue and the issue from the original post are the same. Could you share your project sample and a test with which we can reproduce the problematic behavior?

**Comment by dandoniev** [comment] 2023-01-24 16:46
This problem is also relevant to REST API requests if there's several of them at the same moment. Node v16.16.0, Testcafe v2.2.0

**Comment by miherlosev** [comment] 2023-01-26 06:38
Hi @dandoniev,

Thank you for sharing this information. Did you try using the [experimentalProxyless](https://testcafe.io/documentation/402639/reference/command-line-interface#--experimental-proxyless) option?

**Comment by dandoniev** [comment] 2023-01-26 09:13
Hi @miherlosev, yes I tried it, but application's authorization fails in case experimentalProxyless option enabled

**Comment by miherlosev** [comment] 2023-01-30 07:23
@dandoniev

In this case, could you please share an example where the issue can be reproduced?

**Comment by Artem-Babich** [comment] 2023-05-05 07:01
Hi,
Would you please check if this issue is reproduced in Node 18 with the latest TestCafe version? Please also note that in v2.2.5, we renamed the experimental-proxyless option to native-automation.

**Comment by aleks-pro** [comment] 2023-05-22 09:47
Hello @cattermo ,

If you manage to reproduce the problematic behavior, feel free to reopen the issue. If you encounter some new problem, please create a separate issue with a reproducible example.

**Comment by tomasVizdal** [comment] 2023-09-06 12:56
Hello,
this problem still persists in Firefox and Safari. I am using tetscafe version 3.2.0 and node 18.17.1. Do you plan to fix that for Firefox and Safari?

**Comment by aleks-pro** [comment] 2023-09-08 10:50
I reproduced the problematic behavior using the example shared in the original post in the environment with the following configuration:
- TestCafe version 3.0.0,
- NodeJS versions 16.17.0, 18.4.0, 20.1.0,
- Browsers: Chrome 116.0.0.0, Safari 16.6, Firefox 117.0,
- MacOS Ventura 13.5.1.

I will reopen the issue, but currently, we cannot give any estimates on when we will fix it.

**Comment by cattermo** [comment] 2023-09-08 11:11
@aleks-pro And there it was automatically closed again 😅 . Can someone re-open and remove the "Need response" label?

**Closed** 2023-11-22 09:40 UTC
Labels: TYPE: bug, SYSTEM: hammerhead, FREQUENCY: level 2, STATE: possibly fixed in native automation
