### ISSUE TITLE
TestCafe freezes when trying to access MailDev

### ISSUE THREAD

**Issue by mkubrycz** [DevExpress/testcafe#1871] opened 2017-10-12 11:32 UTC
### Are you requesting a feature or reporting a bug?

It's a bug.

### What is the current behavior?

When accessing [maildev](https://www.npmjs.com/package/maildev) testcafe freezes and gives this error message:
```bash
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 61.0.3163 / Linux 0.0.0

 Testing maildev
ERROR The Chrome 61.0.3163 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```

it happens when I try to access maidev with `navigateTo` and when I use `useRole` with maildev role

### What is the expected behavior?

I should be able to use maildev server for local email testing

### How would you reproduce the current behavior (if this is a bug)?

just install maildev and run the server, then try to access it within the test.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: local

Test code

```js

```

### Specify your

* operating system: ubuntu gnome 17.04
* testcafe version: tested on 18.0 and 17.2
* node.js version: 8.6.0

**Comment by AlexanderMoskovkin** [comment] 2017-10-12 12:51
Hi @mkubrycz,

I've tried to run it on my windows machine. It works ok. 

I've setup `maildev@1.0.0-rc2` version (since the `1.0.0-rc3` doesn't work on windows for now according to https://github.com/djfarrelly/MailDev/issues/185).

I've run the following test:
```js
import { Selector, Role } from 'testcafe';

fixture `maildev`;

const role = Role('http://localhost:1080/', async t => {
    await t
        .click(Selector('.fa.fa-bell-o[title="Automatically show new emails as they arrive"]'));
});

test('test', async t => {
    await t
        .navigateTo('http://localhost:1080/')
        .typeText(Selector('.search-input.ng-pristine.ng-valid'), 'Mail')
        .click(Selector('.fa.fa-refresh'));
});
```

We'll try to run it on a linux machine with the latest `maildev` version soon.

Meanwhile could you please take a look at my test? It possible I should change it somehow to replicate yours. And have you tried to run it in some other browser?

**Comment by mkubrycz** [comment] 2017-10-12 13:42
ok, I've tested your code and it works, both on `0.14` and `1.0.0-rc3`. It seems like the real issue is when a message is received by maildev because I'm still getting freezes in my tests. I used firefox 56.0 as well and with the same result. I don't have any issues when doing everything manually though.

**Comment by AlexanderMoskovkin** [comment] 2017-10-12 14:29
@mkubrycz Take a look at my example: https://github.com/AlexanderMoskovkin/gh-1871

I start the `maildev` server and send mails via `nodemailer` each 1 second. In the test I execute some actions with the maildev UI. It works properly on my side.

Could you please try to update my example according your project to reproduce the issue?

**Comment by mkubrycz** [comment] 2017-10-12 15:28
I can't reproduce this, it's weird because all I do before opening maildev UI is send email via my app UI. It seems like issue with my setup, your example works just fine. Thank you for your help

**Comment by AlexanderMoskovkin** [comment] 2017-10-12 15:39
Please, let me know if you have some progress with this issue.

**Comment by mkubrycz** [comment] 2017-10-16 10:27
I tried debugging again and got this message:
```bash
1) Error on page "http://localhost:1080/#/":

      Uncaught Error: [$rootScope:infdig]

   http://errors.angularjs.org/1.2.3/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3A%20function%20()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bl%26%26a%3D%3Dh.absUrl()%7C%7C(l%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20l%7D%3B%20newVal%3A%207%3B%20oldVal%3A%206%22%5D%2C%5B%22fn%3A%20function%20()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bl%26%26a%3D%3Dh.absUrl()%7C%7C(l%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20l%7D%3B%20newVal%3A%208%3B%20oldVal%3A%207%22%5D%2C%5B%22fn%3A%20function%20()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bl%26%26a%3D%3Dh.absUrl()%7C%7C(l%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20l%7D%3B%20newVal%3A%209%3B%20oldVal%3A%208%22%5D%2C%5B%22fn%3A%20function%20()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bl%26%26a%3D%3Dh.absUrl()%7C%7C(l%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20l%7D%3B%20newVal%3A%2010%3B%20oldVal%3A%209%22%5D%2C%5B%22fn%3A%20function%20()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bl%26%26a%3D%3Dh.absUrl()%7C%7C(l%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20l%7D%3B%20newVal%3A%2011%3B%20oldVal%3A%2010%22%5D%5D
```

it happens every time after I refresh the maildev page after it hangs in debug mode.

**Comment by AlexanderMoskovkin** [comment] 2017-10-23 10:52
@mkubrycz Have you found any ways how to make the test hanging every run? Unfortunately I still can't reproduce it

**Comment by mkubrycz** [comment] 2017-10-24 09:22
@AlexanderMoskovkin unfortunately no, I ended up using [MailCatcher](https://mailcatcher.me/) instead of MailDev and it works just fine.

**Comment by AlexanderMoskovkin** [comment] 2017-10-24 10:32
Since we can't reproduce it in the stable way and you found a workaround could we close the issue?

**Closed** 2017-10-30 18:06 UTC
Labels: To be reproduced, TYPE: bug
