### ISSUE TITLE
Testcafe execution is stuck while using Chrome Version 130.0.6723.59

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe#8312] opened 2024-10-23 02:37 UTC
### What is your Scenario?

Looks like Testcafe test execution is stuck while using Chrome Version 130.0.6723.59 with Testcafe Version 3.7.0-rc.1..

I also noticed this issue not happening on same chrome browser version if I was not using following the video option 

`--video artifacts/videos --video-options singleFile=true,failedOnly=false,pathPattern=${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4`

### What is the Current behavior?

- Chrome browser Version 130.0.6723.59 was opened and test execution is stuck for long hours 
- Firefox browser was opened and test executed successfully   

### What is the Expected behavior?

Test should execute successfully 

### What is the public URL of the test page? (attach your complete example)

none

### What is your TestCafe test code?

https://github.com/shyedhu/testcafe-poc/blob/main/README.md

### Steps to Reproduce

1. git clone https://github.com/shyedhu/testcafe-poc.git
2. cd testcafe-poc
3. npm install
4. npm run test:local:chrome

### TestCafe version

3.7.0-rc.1

### Node.js version

v22.3.0

### Command-line arguments

NONE

### Browser name(s) and version(s)

Chrome Version 130.0.6723.59 (Official Build) (x86_64)

### Platform(s) and version(s)

MacOS Ventura Version 13.6.6

**Comment by ayemelyanenko-chegg** [comment] 2024-10-23 05:57
I am also seeing this issue even without upgrading to TestCafe RC 3.7.0. The tests hang with --disable-native-automation and Chrome 130 and TestCafe version 3.6.2. The issue seems to be with this specific Chrome version 130.0.6723.69-1 which was released today, on October 22nd and that's when the issues started to happen. Seems to also happen on ubuntu/debian images as well

**Comment by deepanshugoyal1989** [comment] 2024-10-23 10:11
I am also getting the same issue,....Testcafe test execution getting stuck while using Chrome Version 130.0.6723.59 with Testcafe Version 3.7.0-rc.1.

**Comment by josephgavin** [comment] 2024-10-23 15:23
Hey I'm also having the same issue as the others here. Same version of chrome and testcafe. I upgraded testcafe because of the chrome error that was fixed with 3.7.0-rc.1, but now when I run my tests they just hang. This is in headless mode btw, based on context I think others had it not working in headed.

**Comment by shyedhu** [comment] 2024-10-23 17:17
> I am also running into this issue. We run through azure pipelines using agents but this is an issue on our local machines as well. We do run headless, but this is also an issue with out headless. We can an error about a websocket.
> 
> My testcafe does not "hang" it actually crashes and kills the run.

@jdnick27  you can try testcafe v3.7.0-rc.1 to resolve websocket issue

**Comment by shyedhu** [comment] 2024-10-23 17:19
> --video



> I am also seeing this issue even without upgrading to TestCafe RC 3.7.0. The tests hang with --disable-native-automation and Chrome 130 and TestCafe version 3.6.2. The issue seems to be with this specific Chrome version 130.0.6723.69-1 which was released today, on October 22nd and that's when the issues started to happen. Seems to also happen on ubuntu/debian images as well

I was facing the issue only Chrome version 130 when i was enabled --video options in command line

**Comment by ayemelyanenko-chegg** [comment] 2024-10-24 22:11
As a workaround, if you have Microsoft Edge installed, you can use that for your tests for now as Edge is Chromium based

**Comment by Bayheck** [comment] 2024-10-25 08:26
Hello,

We have released TestCafe 3.7.0-rc.2, which addresses this issue. Please try it and let us know if the issue is gone.

**Comment by JavaJung** [comment] 2024-10-25 10:10
TestCafe 3.7.0-rc.2 looks good so far, on laptop and in ubuntu image run. Just prior to this update it seemed to work to remove screenshot and video options in testcaferc.json as a workaround

**Comment by Bayheck** [comment] 2024-10-29 12:43
I will close this issue as it was fixed in the PR: [https://github.com/DevExpress/testcafe/pull/8315](https://github.com/DevExpress/testcafe/pull/8315)

**Closed by Bayheck** 2024-10-29 12:43 UTC
Labels: TYPE: bug

**Comment by josephgavin** [comment] 2024-10-30 12:34
After upgrading I am now seeing the following issue instead when I try to run my tests:

```
ERROR Unable to open the "chrome:headless" browser due to the following error:

Error: connect ECONNREFUSED ::1:53426
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

Our tests were functional before the breaking chrome upgrade. As stated above I upgrade to 3.7.0-rc.1 and ran in to the same failure as other above. I have now upgraded to 3.7.0-rc.2

**Comment by Bayheck** [comment] 2024-10-31 11:49
Please create a separate ticket using this [template ](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)and also share a [Minimal Working Example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) in that ticket so that the TestCafe team can research the issue and help you.
