### ISSUE TITLE
Unexpected popup browser window makes TestCafe hang

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6132] opened 2021-04-13 08:49 UTC
See the following SC ticket for details, the test example, and the website to reproduce the issue: https://supportcenter.devexpress.com/internal/ticket/details/T988555

When the Multiple Browser Window support is enabled, an unexpected popup window is shown and the test gets stuck.

* testcafe version:                   1.14.0
* browser name and version: Chrome
* platform and version:          Windows 10

**Comment by AlexKamaev** [comment] 2021-05-06 13:04
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2625

**Closed** 2021-05-14 14:21 UTC
Labels: STATE: Awaiting release, SYSTEM: window management, TYPE: bug, support center

**Comment by mhanci92** [comment] 2021-05-18 14:49
I don't have insight to your internal tickets, but this sounds like an issue to me that I'm currently facing with the latest version of TestCafé (1.14.2). As I can't share the url to the website where the error occurs, I will briefly explain the issue to give you an overview on what is happening until I can supply a minimal example for reproduction. 

As part of a test, we click on a button which leads to a document being downloaded. The download url is being supplied by our backend, and the frontend basically calls a window.open(documentUrl, "_blank") on it. TestCafe opens a blank window (about:blank), where the download is being completed in. Though, the test hangs from there, the empty window stays there, and testcafe sooner or later runs into an error with the message "Cannot switch to the window.".

**Comment by AlexKamaev** [comment] 2021-05-19 08:33
@mhanci92
I managed to reproduce the problem. However, I'm not sure that it's the same issue as yours.
As I understand, your code is similar to the following one:

```HTML
<body>
    <a onclick="window.open('/fonts.zip')">click me</a>
    <h1>Header</h1>
</body>
</html>
```

Could you confirm that your link looks like the link described above? Please test this simple page with TestCafe and share your results with us.
If you can reproduce the problem with this code, please create a separate ticket using the following form: [https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md)

As a temporary workaround, you can try using the `disableMultipleWindows` option ([https://testcafe.io/documentation/402639/reference/command-line-interface#--disable-multiple-windows](https://testcafe.io/documentation/402639/reference/command-line-interface#--disable-multiple-windows)) or add the `download` attribute to your link.

**Comment by mhanci92** [comment] 2021-05-19 12:53
Hey @AlexKamaev,
first of all, thank you for your fast reply. Yes, your example is pretty much resembles the one that I would supply:

```html
<html>
  <head>
    <script>
      function download() {
        window.open("testcafe-download.zip");
      }
    </script>
  </head>
  <body>
    <h1>TestCafe Download</h1>
    <button onclick="javascript:download();">Download Test File</button>
  </body>
</html>
```

With this code, the bug is reproducable in TestCafé version 1.14.2. Also, thanks for suggesting and workaround for this issue. The workaround I came up with was actually overriding the window.open method in the following way before clicking the button that triggers that download (and subsequently opens up the second window):

```typescript
import { Selector, ClientFunction } from "testcafe";

fixture`My download tests`.page("file://C:/Users/path/to/testcafe-test.html").beforeEach(async (t) => {
  console.log("Another test starts..");
});

export const overrideWindowOpen = ClientFunction(() => {
  // @ts-ignore
  window.open = function (url) {
    // @ts-ignore
    window.__lastWindowOpenUrl = url;
  };
});
test("First download test", async (t) => {
  const downloadButton = Selector("button");

  await t.expect(Selector("button").exists).ok("Seems like there page is missing key components!");
  await overrideWindowOpen();
  await t.click(downloadButton);
});
```
Calling this ClientFunction right before clicking the button solved the issue for me as a workaround.

As suggested, I will open a separate bug ticket.

**Comment by mhanci92** [comment] 2021-05-20 09:59
Hey @AlexKamaev,
as suggested, I opened a new issue for the described problem: https://github.com/DevExpress/testcafe/issues/6242

**Comment by wolfwell5** [comment] 2022-03-29 07:01
> 
`test("First download test", async (t) => {
  const downloadButton = Selector("button");

  await t.expect(Selector("button").exists).ok("Seems like the page is missing key components!");
  await overrideWindowOpen();
  await t.click(downloadButton);
  const downloadUrl = await getLastWindowOpenUrl();
  await t.navigateTo(downloadUrl);
});`

This work around examples really helps, thx very much **mhanci92**
