### ISSUE TITLE
"Pass the selector without 'await' warnings" in loops and siblings

### ISSUE THREAD

**Issue by viktorss89** [DevExpress/testcafe#5660] opened 2020-10-26 13:18 UTC
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
A simple test (I will attach it below). When I finish executing it I get this message.
` You passed a DOM snapshot property to the assertion's 't.expect()' method. The property value is assigned when the snapshot is resolved and this value is no longer updated. To ensure that the assertion verifies an
  up-to-date value, pass the selector property without 'await'.`
I get this message when I have loops or expects using the siblings property (prevSibling, sibling, nextSibling)

### What is the Expected behavior?
I believe these warnings are not correct

#### Provide the test code and the tested page URL (if applicable) 
####Your complete test code (or attach your test files)
I have many different tests where this happens, but for example:

A method in the ValidationRules page object class
```
verifyValidationGridItemsRuleState(state) {
    const element = Selector('tbody > tr > td').withText('items');
    return t.expect(element.prevSibling().textContent).contains(state);
  }
```

A test in the ValidationRules test class
```
test.meta({ testIssueKey: 'PEXPL-3351', userStoryIssueKey: 'PEXPL-38'})(
  'Verify that system displays WARNING level validation if the Campaign´s grid does not have any grid item', async t => {
    await t.navigateTo(preconditions['PEXPL-99'].url.valid as string);
    await utils.goToTab(TAB_NAME_VALIDATION_RULES);
    await validationRules.verifyValidationGridItemsRuleState( VALIDATION_RULES_WARNING);
```

This is the stackTrace:
``` 
You passed a DOM snapshot property to the assertion's 't.expect()' method. The property value is assigned when the snapshot is resolved and this value is no longer updated. To ensure that the assertion verifies an
  up-to-date value, pass the selector property without 'await'.

     19 |    return t.expect(selector.exists).notOk();
     20 |  }
     21 |
     22 |  verifyValidationGridItemsRuleState(state) {
     23 |    const selector = Selector('tbody > tr > td').withText('items');
   > 24 |    return t.expect(selector.prevSibling().textContent).contains(state);
     25 |  }
     26 |
     27 |  verifyValidationIsInHeroStageRuleState(state) {
     28 |    const selector = Selector('tbody > tr > td').withText('stage');
     29 |    return t.expect(selector.prevSibling().textContent).contains(state);

     at ValidationRulesPage.verifyValidationGridItemsRuleState (xxx/ValidationRulesPage.ts:24:43)
     at <anonymous> (xxx/CampaignValidationTest.ts:45:27)
     at fulfilled (xxx/CampaignValidationTest.ts:5:58)
 --
```

### Your Environment details:
 
* testcafe version:                   1.9.4
* command-line arguments:  npx testcafe chrome:headless
* browser name and version: Chrome 85
* platform and version:          macOs

**Comment by Ogurecher** [comment] 2020-10-27 07:42
@viktorss89, Thank you for your report. This issue is a duplicate of https://github.com/DevExpress/testcafe/issues/5449 and https://github.com/DevExpress/testcafe/issues/5389. We've already merged [the fix](https://github.com/DevExpress/testcafe/pull/5584) into the master branch. It should be available in the next stable version.

**Closed by Ogurecher** 2020-10-27 07:42 UTC
Labels: STATE: Need response
