### ISSUE TITLE
JavaScript window.open causes TC to lose focus of new window

### ISSUE THREAD

**Issue by Tall-KU-RideOn** [DevExpress/testcafe#6554] opened 2021-09-21 15:33 UTC
### What is your Test Scenario?
Need to validate that when clicking a button that uses JavaScript's `window.open()` function, the new page is opened and can be validated with .expect()
 
### What is the Current behavior?
When using ClientFunction calling the JavaScript window.open(), TestCafe loses focus of the newly opened window
 
### What is the Expected behavior?
TestCafe doesn't lose focus of the new page and fully loads the page to utilize assertions
 
### What is your web application and your TestCafe test code?
I was able to fully reproduce this with the following code using public websites

 
```
 import { Selector, t, ClientFunction } from 'testcafe';

fixture`Testing Window.open()`.page`https://www.google.com/`;

test('Testing Window.open() of JavaScription', async (t) => {
  const openNewWindow = ClientFunction(() =>
    window.open('https://www.zwift.com/', '_blank', 'noopener,noreferrer')
  );

  await openNewWindow();
  const getURL = ClientFunction(() => window.location.href);
  await t.expect(getURL()).contains('zwift');
  await t.debug();
});
```

### Steps to Reproduce:
Execute the provided code to see TestCafe stall out while the new page continuously loads

 
### Your Environment details:
 
* testcafe version:                   1.16.0
* node.js version:                    v14.16.1
* command-line arguments:  testcafe chrome test_switchNewWindow.js
* browser name and version: Chrome 93.0.4577.82
* platform and version:          macOS 10.15.7

**Comment by Farfurix** [comment] 2021-09-22 08:38
@Tall-KU-RideOn 

Hello,

Your test code looks unusual. As far as I understand, your page contains the `window.open` logic in some click handler and you don't need to use `ClientFunction` in your test code to open a new window.

It looks like this issue is a duplicate of [https://github.com/DevExpress/testcafe/issues/6400](https://github.com/DevExpress/testcafe/issues/6400). In this case, you can test your click logic by using [the `--disable-multiple-windows` option](https://testcafe.io/documentation/402841/guides/advanced-guides/multiple-browser-windows#disable-support-for-multiple-windows). If your usage scenario is different, please share a complete example page and your "click and check the current location" test.

**Closed by Farfurix** 2021-09-22 08:38 UTC
Labels: STATE: Need response

**Comment by Tall-KU-RideOn** [comment] 2021-09-22 14:17
@Farfurix - Why does my test code look `ususual`?  Please explain as that statement is extremely vague.  Did you even execute my code?  Why don't I need to utilize the `ClientFunction`?  I have to b/c of below:

We are writing a page within Vue.  The HTML button tag, doesn't have a `onclick=openNewWindow()` attribute.  The handle is written within the Vue file.

The code `window.open('https://www.zwift.com/', '_blank', 'noopener,noreferrer')` is a direct copy/paste from this Vue file (different webpage of course).  But this is **valid** JavaScript code...

I can not share the exact test scenario that I am doing, that is why I provide exact steps to **reproduce** the issue.

**Comment by Farfurix** [comment] 2021-09-23 07:36
@Tall-KU-RideOn 

> The code window.open('https://www.zwift.com/', '_blank', 'noopener,noreferrer') is a direct copy/paste from this Vue file (different webpage of course). But this is valid JavaScript code...

I don't know anything about your test project. That's why I suggested that you share some example project. Your case will be considered in the context of the [https://github.com/DevExpress/testcafe/issues/6400](https://github.com/DevExpress/testcafe/issues/6400) issue. Your usage case looks similar to this issue.

> I can not share the exact test scenario that I am doing, that is why I provide exact steps to reproduce the issue.

I ran your test and the result was similar to the mentioned issue. Based on the information you provided, you'll need to check your scenario after we fix the [https://github.com/DevExpress/testcafe/issues/6400](https://github.com/DevExpress/testcafe/issues/6400) issue.
