### ISSUE TITLE
In nativeAutomation, setFileUpload does nothing

### ISSUE THREAD

**Issue by tandreys** [DevExpress/testcafe#7832] opened 2023-06-26 09:45 UTC
### What is your Scenario?

Scenario need to upload a file

### What is the Current behavior?

await t.setFileUpload does nothing

### What is the Expected behavior?

await t.setFileUpload sets the file to upload

### What is your public website URL? (or attach your complete example)

https://www.htmlquick.com/reference/tags/input-file.html

### What is your TestCafe test code?

import { Selector } from 'testcafe';

fixture `Sandbox`
test('fileinput', async t =>{
    await t.navigateTo("https://www.htmlquick.com/reference/tags/input-file.html");
    
    await t.maximizeWindow();
 
    var input = "[name='uploadedfile']";
    await t.setFilesToUpload(input, "C:\\Windows\\win.ini");
    await t.expect (Selector(input).value).contains("win.ini")
    //await t.click('[value="Send data"]');
    //await t.expect(Selector('caption').innerText).contains('Uploaded files');
    await t.debug();
})

### Your complete configuration file

"skipJsErrors": true,

### Steps to Reproduce

I have the same issue on a server that I cannot share so I tried to find a public website to reproduce.
Here the sendData is failing because of target='blank' under nativeAutomation so I just check the value of the input.
Running with nativeAutomation, the input is not set.
With the option --disable-native-automation , test is passing

### TestCafe version

3.0.0

### Node.js version

18.16.0 and 16.19.2

### Command-line arguments

--disable-multiple-windows 

### Browser name(s) and version(s)

chrome

### Platform(s) and version(s)

Windows 11, Ubuntu 20

**Comment by AlexKamaev** [comment] 2023-06-28 09:34
Hello. I managed to reproduce the problematic behavior. It occurs due to multiple issues:

1. The value of an input element is not set in Native Automation mode
2. New page is open after form submitting. Currently, the Native Automation mode does not allow you to run tests in multiple windows.
While we can research the first issue, the second one is a [limitation](%5Bhttps://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode#q-what-are-the-limitations-of-native-automation%5D(https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode#q-what-are-the-limitations-of-native-automation)) of the Native Automation mode.
3. It looks like `--disable-multiple-windows` works incorrectly in Native Automation mode. We'll research this behavior.

We recommend using `--disable-native-automation` until issues 1 and 3 are fixed.

**Comment by miherlosev** [comment] 2023-06-30 07:11
Hi @tandreys,

> The value of an input element is not set in Native Automation mode

This issue was fixed in this PR - [https://github.com/DevExpress/testcafe/pull/7841](https://github.com/DevExpress/testcafe/pull/7841).

Other issues are related to the `Support using multiple windows in the native automation mode` feature. So, I will close this issue in favor of [https://github.com/DevExpress/testcafe/issues/7661](https://github.com/DevExpress/testcafe/issues/7661)

**Closed by miherlosev** 2023-06-30 07:11 UTC
Labels: TYPE: bug, FREQUENCY: level 1, SYSTEM: native automation
