### ISSUE TITLE
Chrome and Firefox are not able to load certain web pages

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#6155] opened 2021-04-20 07:11 UTC
Use the following test example to reproduce the issue:
```js
import { Selector } from 'testcafe';

fixture `Chrome tests`
    .page `https://www.apple.com`;

test('Basic test', async t => {
    await t
        .click(Selector('#ac-globalnav a').withText('Mac'))
        .click(Selector('#ac-globalnav a').withText('iPad'))
        .click(Selector('#ac-globalnav a').withText('TV')); //this step hangs in Chrome and Firefox
});
```

Refer to [the private ticket](https://supportcenter.devexpress.com/internal/ticket/details/T991599) for additional info

### Your Environment details:
 
* testcafe version:                  1.14.0
* node.js version:                    v12.18.0
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 90
* platform and version:           macOS 10.15

**Comment by aadilwani** [comment] 2021-04-21 11:47
Try to check if it works with version 1.10.0

**Comment by aleks-pro** [comment] 2021-04-23 07:14
I cannot load this page under TestCafe 1.10.1: `https://www.apple.com`.

**Comment by AlexKamaev** [comment] 2021-04-29 14:54
The issue relates to incorrect processing of the Desctructuring assignment in some cases.
I created a separate issue in the testcafe-hammerhead repository: https://github.com/DevExpress/testcafe-hammerhead/issues/2627

As for this issue, I found that the cause is in the `hls.js` script file:
```JS
for (let [e, t] of this.sbContexts) { // we have `e` declaration here
    let e = t.sourceBuffer;           // and another declaration here
    if (e) {                          // but these are different variables
        if (!e.ended) return;
        if (e.updating) return void (this._needsEos = !0);
    }
}
```
We can work around the issue if we rename the `e` variable inside the loop as follows:
```JS
for (let [e1, t] of this.sbContexts) { // we have `e1` declaration here
    let e = t.sourceBuffer;            // and `e` declaration here
    if (e) {                          
        if (!e.ended) return;
        if (e.updating) return void (this._needsEos = !0);
    }
}
```
I was able to work around this issue by using Request Mocks and modifying the source code of `hls.js`. Please note that this is a temporary workaround specific to this site. If anything changes in the `hls.js` file, the workaround may stop working.

Here is the code:
```JS
import { Selector, RequestMock } from 'testcafe';

const fetch = require('node-fetch');

fixture `Chrome tests`
    .page `https://www.apple.com`;

let hljs = null;

const mock = RequestMock()
    .onRequestTo(async request => {
        if (request.url.includes('hls.js')) {
            const res = await fetch(request.url);

            hljs = await res.text();

            hljs = hljs.replace('let[e,t]of this.sbContexts', 'let[e1,t]of this.sbContexts');

            return true;
        }

        return false;
    })
    .respond((req, res) => {
        res.statusCode = '200';
        res.headers['content-type'] = 'text/javascript';

        res.setBody(hljs);
    });


test.requestHooks(mock)('Basic test', async t => {
    await t
        .click(Selector('#ac-globalnav a').withText('Mac'))
        .click(Selector('#ac-globalnav a').withText('iPad'))
        .click(Selector('#ac-globalnav a').withText('TV')); //this step hangs in Chrome and Firefox
});

```
I modified the initial `hls.js` file using the Request Mocks mechanism. I renamed the `e` variable in a specific code line to prevent the error from being processed inside `testcafe-hammerhead`.

I'll close this issue. Please refer to [https://github.com/DevExpress/testcafe-hammerhead/issues/2627](https://github.com/DevExpress/testcafe-hammerhead/issues/2627)

**Closed** 2021-04-29 14:54 UTC
Labels: TYPE: bug, support center
