### ISSUE TITLE
An .after hook runs before --debug-on-fail pauses

### ISSUE THREAD

**Issue by samanthablasbalg** [DevExpress/testcafe#6133] opened 2021-04-13 15:06 UTC
### What is your Test Scenario?
I'm testing an aspect of our software that creates a new UI element, and I want the test to clean up after itself when it is completed because we are using a persistent test environment. I've set up the test to create the UI element, exercise that UI element, and then used a test `.after` hook to delete the UI element when the test is complete.
 
### What is the Current behavior?
The exercise portion of my test was failing, and I wanted to see why, so I used `--debug-on-fail` in my CLI. Instead of pausing when the failure occurred, the steps in the `.after` hook ran, so I could not see why the test actually failed.
 
### What is the Expected behavior?
I expect that the test will actually pause where the failure occurs so that I can open the console and do the investigation that I need. Instead, I had to comment out my entire `.after` block to achieve this.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
This is not going to be a terribly useful example, I don't think, since it's not something y'all can run, but just wanted to include it for illustrative purposes.
```js
import { RequestMock } from 'testcafe';
import { snapshotUser } from '../helpers/helperFunctions';
import snapshot from '../helpers/snapshot';
import freezeTime from '../helpers/freezeTime';

import ABTestIndexPage from '../pages/abTesting/abTestIndexPage';
import ABTestShowPage from '../pages/abTesting/abTestShowPage';
import Chooser from '../pages/abTesting/chooser';
import SunriseModal from '../pages/abTesting/sunriseModal';

const abTestIndexPage = new ABTestIndexPage();
const abTestShowPage = new ABTestShowPage();
const abTestStartedModal = new SunriseModal();
const chooser = new Chooser();

const mockPipedream = RequestMock()
  .onRequestTo({url: 'https://pipedream.wistia.io/mput?topic=metrics', method: 'POST', isAjax: true})
  .respond(null, 200, { 'access-control-allow-origin': '*' });

fixture('Tier 1 > AB Tests').requestHooks(freezeTime, mockPipedream);

const projectName = 'A/B Testing Project';
const controlMediaName = 'Happy Six Months Zephyr';
const variantMediaName = 'Zephyr Escapes';

test('Tier 1 > A/B Testing', async (t) => {
  // Create a new A/B Test
  await t
    .useRole(snapshotUser)
    .navigateTo('/ab-tests')
    .hover(abTestIndexPage.testActionsMenu)
    .click(abTestIndexPage.newABTestButton)
    .expect(abTestShowPage.titleText.textContent).contains('Untitled A/B Test');
  await snapshot(t, { name: 'AB Tests > Create an A/B Test' });

  const controlButton = await abTestShowPage.getChooseVideoButton('control');
  const variantButton = await abTestShowPage.getChooseVideoButton('against');

  // Choose control media
  await t.click(controlButton);
// TEST FAILS HERE - I expect the UI to pause at this moment so I can click around
  await chooser.chooseMedia(projectName, controlMediaName);
  await snapshot(t, { name: 'AB Tests > Choose challenger Video' });

  // Choose variant media and start test
  await t
    .click(variantButton);

  await chooser.chooseMedia(projectName, variantMediaName);

  // Validate both medias chosen state and start test
  await t.click(abTestShowPage.startABTestButton);
  await snapshot(t, { name: 'AB Tests > Start A/B Test (Modal)' });

  // View embed code
  await t.click(abTestStartedModal.viewEmbedCodeButton);
  await snapshot(t, { name: 'AB Tests > Start A/B Test (Modal)' });

  // Complete the test
  await t
    .click(abTestShowPage.endTestButton);

  const variantWinnerButton = abTestShowPage.getDeclareWinnerButton(variantMediaName);

  await t.click(variantWinnerButton);
  await snapshot(t, { name: 'AB Tests > Start A/B Test (Modal)' });
})
.after(async (t) => {
  await t.navigateTo('/ab-tests');
  const deleteButton = abTestIndexPage.getDeleteButton('Untitled A/B Test');

  await t
    .hover(abTestIndexPage.getABTestTitleLink('Untitled A/B Test'))
    .setNativeDialogHandler(() => true)
    .click(deleteButton)
// INSTEAD, TEST PAUSES HERE - The UI item I'm trying to test has been deleted and any context I was hoping to gain was lost
    .expect(abTestIndexPage.getABTestTitleLink('Untitled A/B Test').exists).notOk()});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Create a test that fails
2. Add a `.after` block
3. Run --debug-on-fail
 
### Your Environment details:
 
* testcafe version:                   1.13.0
* node.js version:                    v14.15.4
* command-line arguments:   yarn testcafe chrome testcafe/refresh/ab_testing.js -s testcafe/output/screenshots --debug-on-fail
* browser name and version: 
* platform and version:          
* other:

**Comment by rob4629** [comment] 2021-04-14 16:32
Seems to be a duplicate of https://github.com/DevExpress/testcafe/issues/3237

**Comment by samanthablasbalg** [comment] 2021-04-14 17:17
Oop! I did look for this in the issue list but I guess I didn't scroll back far enough.

**Comment by rob4629** [comment] 2021-04-14 18:31
I previously ran in to this issue, that's the only reason I knew there was an existing issue

**Comment by AlexanderMoiseev** [comment] 2021-04-15 07:28
Hello, 

Yes, you are right, we've marked it as a duplicate. Please follow the [issue](https://github.com/DevExpress/testcafe/issues/3237) to stay tuned

**Closed** 2021-04-15 07:29 UTC
Labels: STATE: Duplicate
